### ISSUE TITLE
Different package resolution with conda and mamba when installing pytorch

### ISSUE THREAD

**Issue by thomasaarholt** [mamba-org/mamba#1001]
Using `mamba` in a fresh install of mambaforge, I went to install the pytorch CPU version today on a computer without a CUDA GPU. I was surprised to see that cudatoolkit (1GB) was included in the packages to be installed. Then by accident I did the same thing again using `conda`, and realised that it was excluded in that case.

The following two commands result in different output:
`conda create --name torchtest pytorch torchvision torchaudio cpuonly -c pytorch`
`mamba create --name torchtest pytorch torchvision torchaudio cpuonly -c pytorch`

To be clear: The conda result is correct. By including the `cpuonly` package, this somehow tells conda that the normal dependency of `pytorch` on `cudatoolkit` should be avoided. I believe it is a ["mutex metapackage"](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#mutex-metapackages), like the `nomkl` package is. I am not familiar with how they work.

I believe this is related to #924 and may be fixed in openSUSE/libsolv#448, but I thought I'd mention it anyway.

**Comment by wolfv** [comment]
This is a duplicate. The pytorch package is not a mutex package, it's using deprecated conda "track_features". https://github.com/pytorch/pytorch/issues/40213

**Comment by wolfv** [comment]
https://github.com/mamba-org/mamba/issues/336

**Comment by wolfv** [comment]
Would be great if you can leave a comment on the pytorch repo, or even the PR that attempts to fix this: https://github.com/pytorch/builder/pull/488

**Comment by wolfv** [comment]
PS. you can use pytorch from conda-forge, it should work fine

**Comment by thomasaarholt** [comment]
Thanks, I didn't spot #336 when I searched before creating the issue! 

Having a look at the pytorch builder now.
