### ISSUE TITLE
Better error description with incorrect download

### ISSUE THREAD

**Issue by AntoinePrv** [mamba-org/mamba#1003]
It would be a nice addition to add the name of the package in this line

https://github.com/mamba-org/mamba/blob/72a3d4efeb2702152798449caa3234eed25dc60a/src/core/transaction.cpp#L812

Something like
```cpp
throw std::runtime_error(std::string{"Found incorrect download: "} + t->name() + ". Aborting");
```

**Comment by wolfv** [comment]
yeah that would be great. do you want to make a PR for that?
