### ISSUE TITLE
Config prepend/append should raise on scalar types

### ISSUE THREAD

**Issue by adriendelsalle** [mamba-org/mamba#1019]
Description
---

The current implementation of `micromamba config prepend` or `micromamba config append` should raise when passing a key of a scalar type.

`./micromamba config prepend json true` gives the following YAML file:
```
json:
  - true
```
which is incorrect and will raise errors during later use

cc @marimeireles

**Comment by marimeireles** [comment]
Hum! thanks for catching that. I'll check your PR now.
