### ISSUE TITLE
Config prepend/append keys should be rc configurable

### ISSUE THREAD

**Issue by adriendelsalle** [mamba-org/mamba#1021]
Description
---

`prepend` or `append` works with any `Configurable` key to an rc file, even if this `Configurable` is not rc configurable.
We should also filter this property.

**Comment by marimeireles** [comment]
I don't understand the difference.
If you want me to fix it we can discuss this further.

**Comment by adriendelsalle** [comment]
Hey @marimeireles 
It's just that a `Configurable` that is not `rc_configurable` will never take its value from a rc file, so we should just throw an error when using `config append` or `config prepend` to not let the user think the value is added to a rc file and will be considered.

That's already fixed in the PR in opened.
