### ISSUE TITLE
Explicit file permissions

### ISSUE THREAD

**Issue by alippai** [mamba-org/mamba#1022]
This is a little feature request. 
I'd like to share environments on NFS with my group. Being able to set the default permissions (660, 770 resp) in the main .condarc file would make the admin tasks easier.

**Comment by wolfv** [comment]
Is this somethign that's implemented in conda?
I'd be happy to review a PR for this but maybe this is something that's better done at a different layer?

**Comment by alippai** [comment]
This is not implemented in the original, it's a new feature request.
I was thinking about the different layer part: if the files are written with 777 and we rely on the umask, it might work. I'll have to try it out. What do you think, would this be the preferred approach instead of app controlled permissions?

**Comment by wolfv** [comment]
I can't really answer this question because I don't think I fully get what this should do.

Do you want to change the default permissions for every file installed by mamba in a given environment? I think currently we're just installing with whatever permissions are embedded in the .tar.bz2 package file.

**Comment by alippai** [comment]
Good question. I'll close this issue until I have better understanding how this works with other package managers.

**Comment by wolfv** [comment]
@alippai I think others are doing what you're asking by installing from a different user account into a folder where others only have read permissions. 

Here is some info for Anaconda that should work the same with mamba: https://docs.anaconda.com/anaconda/install/multi-user/#multi-user-anaconda-installation-on-linux
