### ISSUE TITLE
json output broken in mamba 0.14.0

### ISSUE THREAD

**Issue by beenje** [mamba-org/mamba#1029]
With mamba 0.13.0, running `mamba update --quiet --json` properly returns some json:

```
$ mamba update --quiet --json -y --name foo flask
{
  "message": "All requested packages already installed.",
  "success": true
}
```

With mamba 0.14.0, some extra strings are printed in stdout and breaks the json parsing:

```
$ mamba update --quiet --json -y --name foo flask
Pinned packages:
  - python 3.7.10

{
  "message": "All requested packages already installed.",
  "success": true
}
```

**Comment by wolfv** [comment]
@adriendelsalle we should have used `Console::print`. Could you take care of this?

**Comment by adriendelsalle** [comment]
Yep sure I'll have a look

**Comment by adriendelsalle** [comment]
> @adriendelsalle we should have used `Console::print`. Could you take care of this?

It's correctly done using `Console::print` in `micromamba`. The issue is in `mamba` only.
I also noticed a couple of other prints that could break the JSON output in `mamba` and we should improve and test. I'll open another issue for those.

**Comment by wolfv** [comment]
Thanks, sorry I didn't realize we were printing from python here :)
