### ISSUE TITLE
Old broken packages in a channel completely break mamba install

### ISSUE THREAD

**Issue by asmeurer** [mamba-org/mamba#1034]
I have some old packages in a channel that are built against old versions of Python which have apparently been completely removed from both defaults and conda-forge. When I try to install the newest version of the package, mamba completely fails with an error like `nothing provides python 3.3* needed by *-py33_0`. 

Example:

```
$ mamba install jedi=0.18

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.14.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['jedi=0.18']

pkgs/main/osx-64         [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/osx-64            [====================] (00m:00s) No change
asmeurer/noarch          [====================] (00m:00s) No change
nvidia/noarch            [====================] (00m:00s) No change
rapidsai/osx-64          [====================] (00m:00s) No change
asmeurer/osx-64          [====================] (00m:00s) No change
numba/osx-64             [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
rapidsai/noarch          [====================] (00m:00s) No change
nvidia/osx-64            [====================] (00m:00s) No change
conda-forge/noarch       [====================] (00m:01s) Done
numba/noarch             [====================] (00m:00s) No change
conda-forge/osx-64       [====================] (00m:03s) Done

Pinned packages:
  - python 3.8.6

Encountered problems while solving:
  - nothing provides python 3.3* needed by jedi-0.9.0-py33_0
```

The broken jedi package is something I built a long time ago in my `asmeurer` channel. 

Conda has no problems just ignoring versions of packages that have missing dependencies.

**Comment by wolfv** [comment]
Do you have strict channel priority enabled?

**Comment by asmeurer** [comment]
It looks like I don't.

**Comment by wolfv** [comment]
it looks like your environment has python 3.8.6 (which is what's mentioned in the pinned packages) but etiher you already have jedi-0.9.0 already installed, or the error message is misleading. Not entirely sure what's going on here.

In any case, there are also some incompatibilities between the defaults and conda-forge channels (e.g. in the way they specify the python dependencies). I think it's very much recommended to (at least) turn on strict channel priority (or even better, only use conda-forge).

**Comment by asmeurer** [comment]
Why was this closed?

**Comment by wolfv** [comment]
because there is nothing I can do with the provided information, unfortunately.

Working on better solver error messages is another objective that's high on our priority list but it's also a big item. Maybe we'll have funding coming in for this, though.

**Comment by asmeurer** [comment]
What more information do you need? Maybe ask for it if you can't reproduce the problem? Closing issues without any explanation is a very bad look on this project. Mamba completely doesn't work at all for me because of this issue. This is very sad to see from this project.

**Comment by wolfv** [comment]
output of conda info + conda list would help.

But solving this kind of errors is a really difficult undertaking, especially with that many channels and (probably) a large environment.

**Comment by asmeurer** [comment]
I'm pretty sure it is happening for the reason I indicated. This isn't just a one off occurrence. This error happens for me all them time when trying to use mamba.

**Comment by wolfv** [comment]
I need to see your conda info and conda list ...

**Comment by wolfv** [comment]
If you have strict channel priority and asmeurer channel is higher in the prio etc, obviously it'll break

**Comment by asmeurer** [comment]
Here is conda info 

```
     active environment : array-apis
    active env location : /Users/aaronmeurer/anaconda3/envs/array-apis
            shell level : 1
       user config file : /Users/aaronmeurer/.condarc
 populated config files : /Users/aaronmeurer/.condarc
          conda version : 4.10.2
    conda-build version : 3.21.4
         python version : 3.8.6.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/aaronmeurer/anaconda3  (writable)
      conda av data dir : /Users/aaronmeurer/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/asmeurer/osx-64
                          https://conda.anaconda.org/asmeurer/noarch
                          https://conda.anaconda.org/rapidsai/osx-64
                          https://conda.anaconda.org/rapidsai/noarch
                          https://conda.anaconda.org/nvidia/osx-64
                          https://conda.anaconda.org/nvidia/noarch
                          https://conda.anaconda.org/numba/osx-64
                          https://conda.anaconda.org/numba/noarch
          package cache : /Users/aaronmeurer/anaconda3/pkgs
                          /Users/aaronmeurer/.conda/pkgs
       envs directories : /Users/aaronmeurer/anaconda3/envs
                          /Users/aaronmeurer/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.2 requests/2.25.1 CPython/3.8.6 Darwin/20.5.0 OSX/10.16
                UID:GID : 501:20
             netrc file : /Users/aaronmeurer/.netrc
           offline mode : False
```

Channel priority is whatever the default is. 

conda list is harder because I already upgraded the package with conda itself. I can give a list the next time I run into this issue.

**Comment by wolfv** [comment]
I've created a `.condarc` file with

```
platform: osx-64

channels:
- conda-forge
- defaults
- asmeurer
- rapidsai
- nvidia
- numba

channel_priority: flexible
```

as content (note this file only works with micromamba).

Trying to install `micromamba install jedi=0.9*=py33_0` fails with the error you indicate.

However, installing `micromamba install jedi` gives me a proper resolution with

```
  jedi                0.18.0  py39h6e9494a_2      conda-forge/osx-64     Cached
```

So I am still not sure where the issue is.

**Comment by wolfv** [comment]
Now I installed your old jedi by hand with (`conda install path/to/tar.bz2`) and i can still upgrade using 

```
(asmeurer) ➜  mamba git:(package_resolution_docs) ✗ micromamba update jedi

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

conda-forge/osx-64       Using cache
conda-forge/noarch       Using cache
pkgs/main/osx-64         Using cache
pkgs/main/noarch         Using cache
pkgs/r/osx-64            Using cache
pkgs/r/noarch            Using cache
asmeurer/osx-64          [====================] (00m:00s) No change
rapidsai/noarch          [====================] (00m:00s) No change
nvidia/osx-64            [====================] (00m:00s) No change
asmeurer/noarch          [====================] (00m:00s) No change
rapidsai/osx-64          [====================] (00m:00s) No change
nvidia/noarch            [====================] (00m:00s) No change
numba/osx-64             [====================] (00m:00s) No change
numba/noarch             [====================] (00m:00s) No change

Transaction

  Prefix: /Users/wolfvollprecht/micromamba/envs/asmeurer



  No specs added or removed.

WARNING Package tarball '/Users/wolfvollprecht/micromamba/pkgs/python_abi-3.9-2_cp39.tar.bz2' is invalid
WARNING Extracted package cache '/Users/wolfvollprecht/micromamba/pkgs/python_abi-3.9-2_cp39' has invalid size and will be removed
  Package            Version  Build               Channel                                                         Size
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  ca-certificates  2021.5.30  h033912b_0          conda-forge/osx-64                                            136 KB
  certifi          2021.5.30  py39h6e9494a_0      conda-forge/osx-64                                            141 KB
  libcxx              11.1.0  habf9029_0          conda-forge/osx-64                                            Cached
  libffi                 3.3  h046ec9c_2          conda-forge/osx-64                                            Cached
  ncurses                6.2  h2e338ed_4          conda-forge/osx-64                                            Cached
  openssl             1.1.1k  h0d85af4_0          conda-forge/osx-64                                            Cached
  parso                0.8.2  pyhd8ed1ab_0        conda-forge/noarch                                            Cached
  pip                 21.1.3  pyhd8ed1ab_0        conda-forge/noarch                                            Cached
  python               3.9.5  hd187cdc_0_cpython  conda-forge/osx-64                                             13 MB
  python_abi             3.9  2_cp39              conda-forge/osx-64                                              4 KB
  readline               8.1  h05e3726_0          conda-forge/osx-64                                            Cached
  setuptools          49.6.0  py39h6e9494a_3      conda-forge/osx-64                                            Cached
  sqlite              3.36.0  h23a322b_0          conda-forge/osx-64                                              2 MB
  tk                  8.6.10  h0419947_1          conda-forge/osx-64                                            Cached
  tzdata               2021a  he74cb21_0          conda-forge/noarch                                            Cached
  wheel               0.36.2  pyhd3deb0d_0        conda-forge/noarch                                            Cached
  xz                   5.2.5  haf1e3a3_1          conda-forge/osx-64                                            Cached
  zlib                1.2.11  h7795811_1010       conda-forge/osx-64                                            Cached

  Upgrade:
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  jedi                 0.9.0  py33_0              /Users/wolfvollprecht/Downloads/jedi-0.9.0-py33_0.tar.bz2     Cached
  jedi                0.18.0  py39h6e9494a_2      conda-forge/osx-64                                            Cached

  Summary:

  Install: 18 packages
  Upgrade: 1 packages

  Total download: 15 MB

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by wolfv** [comment]
happy to re-open if you can provide me additional details.

**Comment by dhirschfeld** [comment]
One thing I have noted previously is that `mamba` will error out if you have an environment which doesn't match pinned deps rather than updating the deps to match the pins. `conda` is a bit more permissive in that regard, and maybe `mamba` should be too as my workaround has been to first update my deps with `conda` to match the pins. 

I should probably open an issue with a repro...

**Comment by dhirschfeld** [comment]
Possibly related - https://github.com/mamba-org/mamba/issues/1002

**Comment by wolfv** [comment]
I think the only chance to know what's going on is by getting the `$PREFIX/conda-meta/history` file. 

@asmeurer if you could post the `history` file in question, I can also check what conda resolved for the `jedi` update. And we can piece together the state of the environment as it was when attempting to install `jedi`.

**Comment by asmeurer** [comment]
Does mamba use the history file when doing solves? This happened in my main environment, which has a history file dating back to 2014 with over 700 revisions. I don't know if that will be useful, but I've uploaded it here https://gist.github.com/asmeurer/c4b726cae0aa7ebbceaa3ad0d1f94e4e, along with `conda list` output. The broken mamba install was just before the recent revision that successfully installed jedi=0.18.

**Comment by wolfv** [comment]
Mamba doesn't use the history file when doing solves. But from the history file we can reconstruct the input to the solver (new specs + currently installed packages).

**Comment by wolfv** [comment]
@asmeurer I can see from your history that right before the successful install of jedi=0.18 you removed spyder (version 3.3.6). Would be cool if you had said that in this issue.

I think that was holding back your installation of jedi=0.18, at least that's how I was able to re-create the situation.

So when having an environment with spyder==3.3.6, interestingly `mamba update jedi` works, but only updates to jedi=0.17 -- as the latest available spyder version (5.0.5) can only handle that.

So to fulfill your requirement of `jedi=0.18` mamba would have to remove the installation of spyder.

As I mentioned before, solver conflict messaging could and should be improved -- but we already have open issues for that.

**Comment by asmeurer** [comment]
I did remove spyder exactly for this reason. But once spyder was removed, shouldn't it be no longer a problem?

**Comment by wolfv** [comment]
Yea, for me it works once Spyder was removed. Are you still seeing these errors?

**Comment by asmeurer** [comment]
I'm not, once I was able to manually upgrade with conda. If I see this again I'll post a more active reproducer.

**Comment by janxkoci** [comment]
FYI you could also use `mamba list --revisions` to see the state of the environment before an update.

**Comment by Keyvan-af** [comment]
I try to install fastai and  have same problem @wolfv .Can you help me to fix it?

![Untitled](https://github.com/mamba-org/mamba/assets/70849668/d9d1e8d5-abea-470b-b108-8abf0be4cc38)

**Comment by jonashaag** [comment]
Please create a new issue using the issue template
