### ISSUE TITLE
mamba doesn't call package activate scripts after the install command

### ISSUE THREAD

**Issue by beckermr** [mamba-org/mamba#1035]
It appears that mamba doesn't call package activation scripts after updating an env. Conda does do this. Here is an example. 

The package stackvana should make some env variables upon activation (`STACKVANA_ACTIVATED`).

## case 1 - mamba

```
conda create -n test-lsst python=3.8
conda activate test-lsst
mamba install stackvana=0
env | grep STACK
```

This last command outputs nothing. 

## case 2 - conda

```
conda create -n test-lsst python=3.8
conda activate test-lsst
conda install stackvana=0
env | grep STACK
```

Now this last command outputs

```
$ env | grep STACK
STACKVANA_BACKUP_LSST_DM_TAG=
STACKVANA_BACKUP_DYLD_LIBRARY_PATH=
STACKVANA_BACKUP_EUPS_PKGROOT=
STACKVANA_BACKUP_LD_LIBRARY_PATH=
STACKVANA_BACKUP_LSST_HOME=
STACKVANA_BACKUP_SCONSUTILS_USE_CONDA_COMPILERS=
STACKVANA_BACKUP_LSST_LIBRARY_PATH=
STACKVANA_BACKUP_LSST_PYVER=
STACKVANA_ACTIVATED=1
 eval "export STACKVANA_BACKUP_${envvar}=\"${oldval}\"";
 eval backval="\$STACKVANA_BACKUP_${envvar}";
 eval "unset STACKVANA_BACKUP_${envvar}";
```

I think maybe the deactivate scripts should be called and then activate called again?

**Comment by beckermr** [comment]
cc @wolfv

**Comment by wolfv** [comment]
Thanks. Yeah we need to create a "mamba.sh" script that puts some re-activation after install. This needs to be done at shell level, unfortunately. 

We should port the conda scripts for that and replace conda with mamba there...

**Comment by beckermr** [comment]
OK. This is a very serious bug. People rely on activation for properly functioning envs.

**Comment by wolfv** [comment]
yeah, i agree and it's quite high on my prio list. 

The problem is that mamba needs to be at the shell level for this to properly function (just like `conda` is actually calling a bash function).
For `conda`, this is setup during `conda shell init`, and same for `micromamba`.

However for mamba we don't have an equivalent for `mamba shell init` yet. Probably we should have `mamba shell init` that forwards all args to `conda shell init` and also adds some stuff to the `bashrc` / `zshrc` ... for mamba.

**Comment by wolfv** [comment]
btw micromamba doesn't have this issue :)

**Comment by ReimarBauer** [comment]
similiar problem
https://github.com/mamba-org/mamba/issues/664

**Comment by isuruf** [comment]
See https://github.com/conda/conda/pull/10783 for a PR

**Comment by beckermr** [comment]
I think this issue needs to stay open until a version of conda with https://github.com/conda/conda/pull/10783 is released or https://github.com/mamba-org/mamba/pull/1078 is merged.

**Comment by wolfv** [comment]
yep, I am working on another fix that wouldn't depend on a release of conda in https://github.com/mamba-org/mamba/pull/1078

**Comment by wolfv** [comment]
now it's possible to run `mamba init` to initialize bash & zsh for conda & mamba that solves this problem

**Comment by beckermr** [comment]
This is working! thank you so much!

**Comment by ReimarBauer** [comment]
Not sure if it should just run out of the box
I created an env with mamba

```
        mamba (0.15.2) supported by @QuantStack
        GitHub:  https://github.com/mamba-org/mamba
mamba                     0.15.2           py39h951de11_0    conda-forge
```
then installed the current mss package after activating

after the installation I invoke `mss -v` and it shows

```
Traceback (most recent call last):
  File "/home/reimar/miniconda3/envs/mss404/bin/mss", line 7, in <module>
    from mslib.msui.mss_pyui import main
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mss_pyui.py", line 48, in <module>
    from mslib.msui.mss_qt import ui_mainwindow as ui
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/mss_qt.py", line 38, in <module>
    from mslib.utils import config_loader, FatalUserError
  File "/home/reimar/PycharmProjects/MSS/mslib/utils.py", line 45, in <module>
    import mpl_toolkits.basemap.pyproj as pyproj
  File "/home/reimar/miniconda3/envs/mss404/lib/python3.9/site-packages/mpl_toolkits/basemap/__init__.py", line 152, in <module>
    pyproj_datadir = os.environ['PROJ_LIB']
  File "/home/reimar/miniconda3/envs/mss404/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'PROJ_LIB'
```

**Comment by isuruf** [comment]
@ReimarBauer, you need to do ` mamba init`
