### ISSUE TITLE
mamba doesn't remove orphan packages, unlike conda

### ISSUE THREAD

**Issue by benplm** [mamba-org/mamba#1037]
The help screen from `mamba remove -h` states the following:

```
Remove a list of packages from a specified conda environment.

    This command will also remove any package that depends on any of the
    specified packages as well---unless a replacement can be found without
    that dependency. If you wish to skip this dependency checking and remove
    just the requested packages, add the '--force' option. Note however that
    this may result in a broken environment, so use this with caution.
```

However, it doesn't happen to remove orphan dependencies, while `conda remove` does.

From a fresh installation of mambaforge, I ran:
`mamba install -n base wget`

Which installs the following packages in the base environment:
```
  gettext       0.19.8.1  h0b5b191_1005  conda-forge/linux-64     Cached
  libidn2          2.3.1  h7f98852_0     conda-forge/linux-64     Cached
  libunistring    0.9.10  h14c3975_0     conda-forge/linux-64     Cached
  wget            1.20.1  h22169c7_0     conda-forge/linux-64     Cached
```

When I run `mamba remove -n base wget`, it doesn't attempt to remove the dependencies:
```
  Package  Version  Build       Channel       Size
────────────────────────────────────────────────────
  Remove:
────────────────────────────────────────────────────

  wget      1.20.1  h22169c7_0  installed

  Summary:

  Remove: 1 packages
```

However, when I run `conda remove -n base --offline wget`, it correctly detects the dependencies:
```
  removed specs:
    - wget


The following packages will be REMOVED:

  gettext-0.19.8.1-h0b5b191_1005
  libidn2-2.3.1-h7f98852_0
  libunistring-0.9.10-h14c3975_0
  wget-1.20.1-h22169c7_0
```

Maybe there's another way to remove orphan packages with mamba?

**Comment by wolfv** [comment]
This is related to #31 

I think once we add that information to the solver, we should be able to get it to remove orphaned pacakges. 
Interested in hacking on this?

**Comment by benplm** [comment]
Thanks for pointing to the related issue. I would gladly have a look, but unfortunately I've got 0 experience with C++.
