### ISSUE TITLE
Small output issues

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1039]
Currently mamba pinnings aren't printed with a newline at the end (cc @adriendelsalle)
You get `Pinned packages: - python 3.6       - xyz 3.5 ...`

And currently progress bar in quiet mode prints one line too many per download.

**Comment by adriendelsalle** [comment]
Hi @wolfv !

In which case it happens?
I just tested but it works as expected:
https://github.com/mamba-org/mamba/blob/cb9b4e8ed3c5077f1c0b2749b80c54f909879f41/mamba/mamba.py#L571

**Comment by adriendelsalle** [comment]
Same for the progress I can't reproduce.
Could you please give me a hint?

**Comment by wolfv** [comment]
`pinned_specs_info` doesn't contain newlines though :)

**Comment by wolfv** [comment]
https://github.com/mamba-org/mamba/blob/cb9b4e8ed3c5077f1c0b2749b80c54f909879f41/mamba/mamba.py#L541

**Comment by wolfv** [comment]
same in mamba_env.py

**Comment by wolfv** [comment]
for the progress bars: this is what ti looked like with micromamba 0.4.0: https://github.com/mamba-org/mamba/runs/2915908836#step:5:123

and this is what it looks like now:

https://github.com/mamba-org/quetz/runs/2904949892#step:4:302
