### ISSUE TITLE
Implement / respect "force" flag for package removal?

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1042]
Now that we correctly prune dependencies when removing a package it might also be useful to have a force flag that removes a package without pruning the deps. cc @adriendelsalle

**Comment by jakirkham** [comment]
Yes this would be useful. @quasiben and I were actually just looking for this 😄

**Comment by wolfv** [comment]
The current behavior of mamba is like this :) only with the next release it’ll change, hehe

**Comment by gunstonej** [comment]
+1 i look forward to seeing this behaviour!
