### ISSUE TITLE
Mamba segfault

### ISSUE THREAD

**Issue by datapythonista** [mamba-org/mamba#1049]
Looks like Mamba started to randomly segfault in the [Ibis](https://github.com/ibis-project/ibis) CI recently, I guess since 0.14.1 was released. 

From our CI:

[1565 Segmentation fault      mamba env update -n base --file=environment.yml](https://github.com/ibis-project/ibis/pull/2841/checks?check_run_id=2956453388#step:3:472)

I didn't check in detail the first couple of times I saw it failing, but this last time seems it's in a Windows build with this version:

[mamba              conda-forge/win-64::mamba-0.14.1-py38hdd88130_0](https://github.com/ibis-project/ibis/pull/2841/checks?check_run_id=2956453388#step:3:310)

I guess the other times it was also in the Windows builds, but not sure.

Let me know if I can provide further information. The file we're running is this [environment.yml](https://github.com/ibis-project/ibis/blob/master/environment.yml), to which we add the Python version dynamically (the last fail is Python 3.7, unsure about the previous).

**Comment by datapythonista** [comment]
Probably related, we've been having `Connection reset by peer` from conda-forge servers frequently. Maybe that's what's causing the segfault, when it happens from mamba and not conda.

**Comment by wolfv** [comment]
Hey, thanks for letting me know! 

Was it Happening for the first time yesterday? In that case it could be related to a libsolv patch that I published. I'll have a look!

**Comment by wolfv** [comment]
And sorry for the trouble!

**Comment by wolfv** [comment]
I tried to reproduce using this file:

```
name: ibis-dev
channels:
  - nodefaults
  - conda-forge
dependencies:
  # Ibis hard dependencies
  - multipledispatch
  - numpy
  - pandas
  - pytz
  - regex
  - toolz
  - cached_property # for 3.7 compat, functools.cached_property is for >=3.8
  - setuptools

  # Ibis soft dependencies
  - sqlalchemy
  - python-graphviz

  # Dev tools
  - asv
  - black=19.10b0
  - click # few scripts in ci/
  - flake8
  - flake8-comprehensions # used by flake8, linting of unnecessary comprehensions
  - isort
  - jinja2<3 # feedstock
  - mypy
  - plumbum # few scripts in ci/ and dev/
  - pydocstyle
  - pytest
  - pytest-cov
  - pytest-mock

  # Release
  - twine
  - wheel
  - conda-smithy
  - conda-build # feedstock
  - ruamel.yaml # feedstock
  - pygit2 # dev/genrelease.py

  # Docs
  - pip
  - pip:
    - pysuerga
  - ipython
  - jupyter
  - matplotlib
  - nbconvert
  - nbsphinx
  - nomkl
  - semantic_version=2.6 # ibis-project/ibis/issues/2027
  - sphinx<4.0.0 # ibis-project/ibis/issues/2771
  - sphinx-releases
  - sphinx_rtd_theme
  - python=3.7
  - pyarrow
  - pytables
```

But so far I haven't been successful ...

One thing to note is that in the CI you are installing with

`mamba env update -n base --file env.yml`

So that you're installing these new packages into the base environment. In general I would probably do it differetnly (since this way the python vesrion of hte base env probably needs to be changed). Would be cleaner to make a new env.

**Comment by datapythonista** [comment]
> Was it Happening for the first time yesterday?

Sorry for the delay. I was checking, and seems like it was, but we didn't have much activity in our CI the days before, so can't really tell which of the two releases caused it. My bet is that this is failing when conda servers return the connection reset by peer. And that happens in waves from time to time. Not sure if that would be easy to emulate. I can try to have a look next week if you think that can be useful.

Thanks a lot for the help, and also for the advice. I thought that reusing the base environment it'd probably save a bit of time of installing packages already there. But it probably makes more sense to make sure our dependencies are installed in a clean environment. I'll have a look.

**Comment by wolfv** [comment]
No worries. Is it still happening?

**Comment by datapythonista** [comment]
> No worries. Is it still happening?

We only had a CI run since I opened the issue, and it didn't fail with the segfault. I'm going to force few more and see.

**Comment by wolfv** [comment]
Thanks!!

**Comment by wolfv** [comment]
Hey @datapythonista did you have a chance to trigger a re-run? Did this happen again?

**Comment by datapythonista** [comment]
Sorry for the delay. I kept trying, and I couldn't get it failing until now, but I just had a build with the segfault: https://github.com/ibis-project/ibis/pull/2828/checks?check_run_id=3004472824#step:3:477

**Comment by wolfv** [comment]
I just published a new libsolv version that fixes at least one issue with the previous implementation of this PR: https://github.com/openSUSE/libsolv/pull/457

I hope this also helps here but I am not sure, still, where exactly the issue lies.

**Comment by wolfv** [comment]
I checked today with valgrind, and only found two relatively minor things:

- #1069 a jump depending on an uninitialized variable
- https://github.com/openSUSE/libsolv/pull/460 A memcpy with overlapping areas

**Comment by wolfv** [comment]
hey @datapythonista I had a bit more of a look and let the workflow run 2 times in my fork, and indeed also got a segfault: https://github.com/wolfv/ibis/runs/3017295242

However, I also noticed that you're mixing anaconda and conda-forge in the base env (specifically the zlib package is kept from the anaconda channel). That _could_ be a source of problems. I am trying to run it right now with strict repo priority to see if that improves things.

However, in general I think your current strategy is not optimal: you install things in the base env which also changes the python version (your base env is first 3.8, then you change it to 3.7).

I think it would be quite a bit cleaner to either use the [provision-with-micromamba](https://github.com/mamba-org/provision-with-micromamba) action or the [setup-miniconda](https://github.com/marketplace/actions/setup-miniconda) action (which let's you select mamba as well).

You could do the modifications to the env yaml in a simple step right before executing one of these two actions (just append the python pin in the `run:...` step).

**Comment by wolfv** [comment]
hey @datapythonista I finally found it: [`a50a034` (#457)](https://github.com/openSUSE/libsolv/pull/457/commits/a50a03413a788c0a06bb81188a9c6f7b7d23c746)

😅 

Sorry for this issue, 100% my fault. I'll push another update to the libsolv conda package.

And many thanks for reporting!

**Comment by datapythonista** [comment]
Amazing, thanks a lot for the fix, all the advice, and for mamba itself (it's saving me loads of time, we have problems with the conda solver all the time until we switched).

I created an issue for your suggestions on how to install our environment, will be taking care of them soon: https://github.com/ibis-project/ibis/issues/2846
