### ISSUE TITLE
URL auth incorrectly parsed/sent to server

### ISSUE THREAD

**Issue by afranchuk** [mamba-org/mamba#1065]
It's not immediately clear when this regression was introduced, nor where it's coming from, however in mamba version 0.8.2, one could pass a url with auth parameters that didn't have a username specified (e.g. https://:APIKEY@something.com), where there are services which support having the api key as the password and it works as expected with no username. However, in at least mamba version 0.13, this broke and instead (after inspection with wireshark) mamba ends up sending `(nil):PASSWORD` to the server (the empty username is replaced with a username of `(nil)`).

To clarify, this was actually tested with micromamba, but I am assuming that the issue does not lie there.

**Comment by afranchuk** [comment]
Note this isn't very high priority since specifying a username along with the request is still an option.

**Comment by wolfv** [comment]
Thanks for the notice. I quickly grepped our code and we don't use `(nil)` anywhere, so I am suspecting that this comes from libcurl.

**Comment by wolfv** [comment]
btw you can use the python server included in the repo to write some test for this auth behavior.

**Comment by afranchuk** [comment]
Yeah I would have submitted a PR but I couldn't find `(nil)` in conda nor mamba. I think it may be the result of a `printf` of `0` as `%p`? It's a little odd that something changed along the way to cause that though, I don't think the string pointer should ever be formatted (nor should it technically ever be null versus pointing to null). So maybe that's not the source. It also doesn't feel like it's _just_ libcurl seeing as it worked in 0.8.

**Comment by wolfv** [comment]
One possible thing is that libcurl changed in the meantime. 

E.g. it would be interesting to see what this returns: 

https://github.com/mamba-org/mamba/blob/23ee3a6a9a21d53568dfe0a4e2496d481b9b82c9/src/core/url.cpp#L42-L57

Maybe we can add some tests?
