### ISSUE TITLE
[micromamba] Unlinking currently stops when missing a file

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1067]
When unlinking (removing) a package and a file is gone, the unlinking stops:

```
Unlinking requests-2.25.1-pyhd3deb0d_0
ERROR   No such file or directory: '/Users/wolfvollprecht/micromamba/lib/python3.9/site-packages/requests-2.25.1.dist-info'
```

I think missing files should be ignored instead.

**Comment by adriendelsalle** [comment]
It looks like it's not raising an error anymore
I just added a test but also refined a bit the logs
