### ISSUE TITLE
micromamba is awful long to type

### ISSUE THREAD

**Issue by jasongrout** [mamba-org/mamba#1068]
I tried switching to micromamba for a few days, and found that it is *really* long to constantly type out. I tried renaming the program binary to `mm`, but then `mm activate` wouldn't work (I think the name "micromamba" is hardcoded for the activate/deactivate shell configuration). I didn't spend a ton of time fixing it, just switched back to mambaforge for now, but thought I would note the issue here for feedback.

**Comment by wolfv** [comment]
hey, thanks for the feedback! I agree it's pretty long.

I think it would have worked with the `alias` function: `alias mm=micromamba`

The reason is that when micromamba is properly installed and the shell initialized, `$ micromamba` will actually call a _shell_ function (because for activate / deactivate we have to operate on the shell level).

We could set a `mm` alias during shell init for users that want that.

**Comment by jasongrout** [comment]
> I think it would have worked with the `alias` function: `alias mm=micromamba`

Indeed, that seems to work great. Thought I tried that, but I guess not. Thanks!

Feel free to close this issue. I think adding a note to the docs about alias would be great. Perhaps considering changing the command (`umamba`?) if others also complain?

**Comment by adriendelsalle** [comment]
I would also prefer `umamba` :)

**Comment by jasongrout** [comment]
> I would also prefer `umamba` :)

This may be really picky....but I think "mamba" is hard to type fast on a US keyboard. I find that I'm often typing mabma or mmaba or something like that. I think the problem for me is that there are two duplicate letters typed by one hand interspersed with letters on the other hand. It is kind of hard to precisely time the two `m`s in between the letters the other hand is typing if I am going for speed. With "conda", for example, there is a cadence with the different letters (you type the `c`, then you can basically just slap your hands down for the "onda" in one motion from right to left across the keyboard).

Anyways, I'm really enjoying using `mm` as a shortcut - it *is* very fast to hit `m` twice in succession.

That said, I do agree that umamba is an improvement over mamba for typing often.

**Comment by jasongrout** [comment]
Just a thought: `mba` would be very fast to type on a US keyboard, and sort of hits the important sounds in "mamba" :).

**Comment by adriendelsalle** [comment]
thanks for the suggestions!

other ideas could be:
- define aliases at `shell init`, using a CLI option `--set-alias mm:micromamba`
- define aliases when installing/activating an auto-completer

> Just a thought: `mba` would be very fast to type on a US keyboard, and sort of hits the important sounds in "mamba" :).

Similarly `boa` makes it shorter/faster to type, but it would be a major change and would be probably confusing for a lot of people using `mamba`.

**Comment by certik** [comment]
Cannot micromamba simply become mamba and replace it now? You can call into Python when needed, and over time remove the Python dependency step by step?

**Comment by jasongrout** [comment]
As a follow-up: I've been using a shell alias `mm` for a while now, and I still *really* like it. `mm` is just so easy and quick to type.

**Comment by ccelik97** [comment]
As a follow up to when it comes to being picky about the CLI keywords I'd like to say that `mm` alias breaks the flow of typing due to the necessity of double pressing a key (I mean I do play fighting games on a keyboard where double pressing a key is common just fine but it's not as easy as to type left/right and/or right/left hand finger keywords on a QWERTY xd).

If it wasn't prone to cause confusion with the `conda` keyword I'd have aliased it to `comda` but that's out of the picture;

What about `alias mc=micromamba` (or `mcm`, `mcmb` etc)? As far as I know "Miniconda" refers to the minimal conda environment (instead of Anaconda), not the package manager (`conda`) itself so it shouldn't cause as much of an immediate confusion as something like `comda` would?

**Comment by cosmojg** [comment]
> hey, thanks for the feedback! I agree it's pretty long.
> 
> I think it would have worked with the `alias` function: `alias mm=micromamba`
> 
> The reason is that when micromamba is properly installed and the shell initialized, `$ micromamba` will actually call a _shell_ function (because for activate / deactivate we have to operate on the shell level).
> 
> We could set a `mm` alias during shell init for users that want that.

Allowing the user to set an alias during shell init sounds like the most elegant solution. At the very least, it gets around all the bikeshedding about what the abbreviated alias should be. I imagine running something like the following:

`micromamba shell init --shell fish --prefix ~/micromamba --alias mm`

Which appends something like the following to my config.fish (or bashrc/zshrc/etc.):

```
# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
set -gx MAMBA_EXE "/usr/local/bin/micromamba"
set -gx MAMBA_ROOT_PREFIX "/Users/cosmo/micromamba"
set -gx MAMBA_ALIAS "mm"
$MAMBA_EXE shell hook --shell fish --prefix $MAMBA_ROOT_PREFIX --alias $MAMBA_ALIAS | source
# <<< mamba initialize <<<
```

And `$MAMBA_EXE shell hook --shell fish --prefix $MAMBA_ROOT_PREFIX --alias $MAMBA_ALIAS` outputs something like the following:

```
if not set -q MAMBA_SHLVL
  set -gx MAMBA_SHLVL "0"
  fish_add_path --move $MAMBA_ROOT_PREFIX/condabin
end

if not set -q MAMBA_NO_PROMPT
  function __mamba_add_prompt
    if set -q CONDA_PROMPT_MODIFIER
      set_color -o green
      echo -n $CONDA_PROMPT_MODIFIER
      set_color normal
    end
  end

  if functions -q fish_prompt
      if not functions -q __fish_prompt_orig
          functions -c fish_prompt __fish_prompt_orig
      end
      functions -e fish_prompt
  else
      function __fish_prompt_orig
      end
  end

  function return_last_status
    return $argv
  end

  function fish_prompt
    set -l last_status $status
    if set -q MAMBA_LEFT_PROMPT
        __mamba_add_prompt
    end
    return_last_status $last_status
    __fish_prompt_orig
  end

  if functions -q fish_right_prompt
      if not functions -q __fish_right_prompt_orig
          functions -c fish_right_prompt __fish_right_prompt_orig
      end
      functions -e fish_right_prompt
  else
      function __fish_right_prompt_orig
      end
  end

  function fish_right_prompt
    if not set -q MAMBA_LEFT_PROMPT
        __mamba_add_prompt
    end
    __fish_right_prompt_orig
  end
end


function mm --inherit-variable MAMBA_EXE
  if test (count $argv) -lt 1 || contains -- --help $argv
    $MAMBA_EXE $argv
  else
    set -l cmd $argv[1]
    set -e argv[1]
    switch $cmd
      case activate deactivate
        $MAMBA_EXE shell -s fish $cmd $argv | source || return $status
      case install update upgrade remove uninstall
        $MAMBA_EXE $cmd $argv || return $status
        $MAMBA_EXE shell -s fish reactivate | source || return $status
      case '*'
        $MAMBA_EXE $cmd $argv
    end
  end
end



# Autocompletions below

function __fish_mamba_envs
  mm env list | tail -n +11 | cut -d' ' -f3
end

function __fish_mamba_packages
  mm list | awk 'NR > 3 {print $1}'
end

function __fish_mamba_universal_optspecs
    string join \n 'h/help' 'a-version' 'b-rc-file=+' \
                   'c-no-rc' 'd-no-env' 'v/verbose' \
                   'o/-log-level=+' 'q/quiet' 'y/yes' \
                   'e-json' 'f-offline' \
                   'g-dry-run' 'i-experimental' 'r/root-prefix=+' \
                   'p/prefix=+' 'n/name=+'
end

function __fish_mamba_has_command
  set -l want_prefix $argv
  set -l argv (commandline -opc)
  # Remove MAMBA_EXE
  set -e argv[1]
  # Parse common options
  argparse -i (__fish_mamba_universal_optspecs) -- $argv 2>/dev/null; or return 1
  # Parse other options. This only works for boolean --flags so far.
  set -l argv (string replace -r -- " ?-[^ ]+" "" "$argv")
  # Normalize whitespace
  set -l argv (string replace -r "\s+" " " "$argv")
  test "$want_prefix" = "$argv"
end

function __fish_mamba_complete_subcmds
  for line in (string split \n (string trim $argv[2]))
    set tmp (string replace -r '\s{5,}+' ___ (string trim $line))
    set cmd (string split ___  $tmp -f 1)
    set description (string split ___ $tmp -f 2)
    if test -z $description
      complete -x -c mm -n $argv[1] -a $cmd
    else
      complete -x -c mm -n $argv[1] -a $cmd -d $description
    end
  end
end


function __fish_mamba_needs_env
  set -l cmd (commandline -opc)
  test $cmd[-1] = "-n"
end


# Top level commands
# Generated by "micromamba --help"
__fish_mamba_complete_subcmds '__fish_mamba_has_command' '
  shell                       Generate shell init scripts
  create                      Create new environment
  install                     Install packages in active environment
  update                      Update packages in active environment
  repoquery                   Find and analyze packages in active environment or channels
  remove                      Remove packages from active environment
  list                        List packages in active environment
  package                     Extract a package or bundle files into an archive
  clean                       Clean package cache
  config                      Configuration of micromamba
  info                        Information about micromamba
  constructor                 Commands to support using micromamba in constructor
  env                         List environments
  activate                    Activate an environment
  run                         Run an executable in an environment
  ps                          Show, inspect or kill running processes
  auth                        Login or logout of a given host
  search                      Find packages in active environment or channels
'

# TODO: deactivate
# TODO: run

# env subcommand
# Generated by "micromamba env --help"
__fish_mamba_complete_subcmds '__fish_mamba_has_command env' '
  list                        List known environments
  export                      Export environment
  remove                      Remove an environment
'
# env subcommand
# Generated by "micromamba config --help"
__fish_mamba_complete_subcmds '__fish_mamba_has_command config' '
  list                        List configuration values
  sources                     Show configuration sources
  describe                    Describe given configuration parameters
  prepend                     Add one configuration value to the beginning of a list key
  append                      Add one configuration value to the end of a list key
  remove-key                  Remove a configuration key and its values
  remove                      Remove a configuration value from a list key. This removes all instances of the value.
  set                         Set a configuration value
  get                         Get a configuration value
'

# repoquery
__fish_mamba_complete_subcmds '__fish_mamba_has_command repoquery' '
  search
  depends
  whoneeds
'


# shell
__fish_mamba_complete_subcmds '__fish_mamba_has_command shell' '
  init
  deinit
  hook
  activate
  deactivate
  reactivate
'

# Commands that need environment as parameter
complete -x -c mm -n '__fish_mamba_has_command activate' -a '(__fish_mamba_envs)'
complete -x -c mm -n '__fish_mamba_has_command shell activate' -a '(__fish_mamba_envs)'

# Commands that need package as parameter
complete -x -c mm -n '__fish_mamba_has_command remove' -a '(__fish_mamba_packages)'
complete -x -c mm -n '__fish_mamba_has_command uninstall' -a '(__fish_mamba_packages)'
complete -x -c mm -n '__fish_mamba_has_command upgrade' -a '(__fish_mamba_packages)'
complete -x -c mm -n '__fish_mamba_has_command update' -a '(__fish_mamba_packages)'

# Environment name
complete -x -c mm -n '__fish_mamba_needs_env' -a '(__fish_mamba_envs)'
```

**Comment by butaixianran** [comment]
conda and miniconda all use "conda" as command. micromamba can do the same.

**Comment by richlysakowski** [comment]
micromamba is way too hard to type.  mamba is borderline hard, and much harder than conda.  conda just rolls off the fingers.  mamba requires a mental pause to learn to type the mba at the end.  

I vote for moving micromamba out of the vocabulary and typing pool.

**Comment by ccelik97** [comment]
> micromamba is way too hard to type. mamba is borderline hard, and much harder than conda. conda just rolls off the fingers. mamba requires a mental pause to learn to type the mba at the end.
> 
> I vote for moving micromamba out of the vocabulary and typing pool.

What about `mamma`? It's easier to type for sure.

Also, the project icon could change to [🤌](https://emojipedia.org/pinched-fingers/) aka `Mamma Mia!`

**Comment by jasongrout** [comment]
> As a follow-up: I've been using a shell alias mm for a while now, and I still really like it. mm is just so easy and quick to type.

For what it's worth, I'm perfectly happy with my `mm` shell alias, after using it for more than a year.

**Comment by certik** [comment]
I still think `micromamba` should become just `conda` and so does `mamba`, perhaps a layered approach: use just `conda` which uses `micromamba`, which dispatches to `mamba` or old `conda` for things it cannot do.

**Comment by francois-rozet** [comment]
To add my grain of salt, I alias `micromamba` as `conda` in my `.bashrc`. This is great to leverage years of `conda` muscle memory, but you lose the auto-completion feature.

**Comment by ccelik97** [comment]
> To add my grain of salt, I alias `micromamba` as `conda` in my `.bashrc`. This is great to leverage years of `conda` muscle memory, but you lose the auto-completion feature. I do like `umamba` though.

Maybe you could try the auto-expanding abbreviations, as you type.
- For Zsh: https://github.com/olets/zsh-abbr
- Fish has it too.
With this, when you type `conda` it can turn into `micromamba` the moment you input the `a`.

_(You can use Zsh as your user shell only, e.g. the one you manually do things in,
as virtually everything you could sanely wish to do with Bash are doable with Zsh too,
and still execute all your scripts via Bash as usual, it if needs to be said.)_

Anyway, I still stand by my earlier suggestion xd:
```bash
alias mamma=micromamba
```
(Easy & fluent to _type & keep typing_ e.g. spacebar afterwards.)

**Comment by jjerphan** [comment]
`micromamba` is here to stay and we recommend using aliases.

**Comment by jasongrout** [comment]
> micromamba is here to stay 

+1

> and we recommend using aliases. 🙂

Would you be opposed to adding a section to the installation docs or a FAQ mentioning aliases, so this recommendation was a bit more discoverable than a github issue?
