### ISSUE TITLE
Notify users of updates for mamba

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1070]
conda shows a banner when a newer conda version is available. 

It would be cool to do the same for mamba / micromamba.

we could have a function that finds the latest available version and prints it if it's higher than the currently installed one.

**Comment by mparry** [comment]
This is a bit annoying in some scenarios - e.g. we turn conda's notice off for CI etc. - so please make it configurable, or maybe just respect the existing conda config key.
