### ISSUE TITLE
minor feature request: option to disable splash art

### ISSUE THREAD

**Issue by jamestwebber** [mamba-org/mamba#1074]
I love it and all, but it does take up a lot of real estate in my console 😬 Sometimes it's nice to have a compact log.

It'd be nice to be able to configure a flag or environment variable to silence it (or have a smaller version?) when desired. Sort of similar to how homebrew has a flag to turn off their emojis.

**Comment by adriendelsalle** [comment]
Hi @jamestwebber !

This is related to https://github.com/mamba-org/mamba/issues/984
You'll find there a bunch of solutions to your desired behavior.

Please let us know if it fits your needs, and feel free to continue the discussion on this other thread.

**Comment by jamestwebber** [comment]
Sorry about that! The env variable solution works fine for me, and if a `mambarc` option arrives I'll use that then.
