### ISSUE TITLE
`mamba init` add powershell support

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1088]
`mamba init` works for bash & zsh now. But not yet for powershell. Would be cool to add support for that, too.

**Comment by wolfv** [comment]
I think we might have to reopen this since it is related to `mamba` and not `micromamba`. Mamba still doesn't have the `mamba activate` working on powershell :/

**Comment by jjerphan** [comment]
Closing as a duplicate of https://github.com/mamba-org/mamba/issues/1717.
