### ISSUE TITLE
Mamba couldn't resolve host

### ISSUE THREAD

**Issue by kfourspr** [mamba-org/mamba#1089]
We have noticed some issues with the latest 0.15 mamba release.  I get the error that it cannot resolve the host name when it's checking the cache for the various remote repository channels.  This error goes away when reverting back to 0.14.1.  I've reproduced this error from both Centos and Red hat linux systems.  Was anything changed with the remote repository caching/ downloading the repo.json files between those releases?

**Comment by wolfv** [comment]
@kfourspr can you post more details of your configuration?

- what channels are used?
- what authentication (http basic auth or token auth?)

You could also post the output of mamba (potentially with `-v` to get more info). Thanks

**Comment by kfourspr** [comment]
Our Channel list from the condarc looks like the following.  We were using http basic auth.
channels:
  - defaults
  - file:///several_file_channels
  - conda-forge

**Comment by wolfv** [comment]
what operating system and what channel did fail to resolve?

**Comment by kfourspr** [comment]
Red Hat Enterprise Linux Server release 7.9 (Maipo)

Both the main anaconda channel and conda-forge

**Comment by wolfv** [comment]
the major thing that's changed is the channel stuff so that URLs are computed differently. I can't judge wether this impacts you in this case.

If you can, please post some logs with `-v` (e.g. `mamba clean -i && mamba create -n something xtensor -v`

**Comment by kfourspr** [comment]
This issue seems to be resolved in 0.15.3 and was still broken in 0.15.2

**Comment by kfourspr** [comment]
https://github.com/mamba-org/mamba/compare/0.15.2...0.15.3#diff-f01b06e6121ec3840b7c6a21adc304e82aa2cf775abbab8fdd7660870f32e288 I wonder if this change is what causes it to be able to resolve the channels again.
