### ISSUE TITLE
Ability to remove unused packages disappear 

### ISSUE THREAD

**Issue by AlphaScorpii-dev** [mamba-org/mamba#1092]
I have an environment, set up with Conda, where I installed a few packages like pandas, sympy, etc...
I kept a backup of that environment for testing.

In this environment, I first try to `mamba remove`, with no issue.

> Removing specs: ['pandas-datareader']
> Transaction
> 
>   Prefix: C:\Users\gv6\AppData\Local\miniforge3\envs\science
> 
>   Removing specs:
> 
>    - pandas-datareader
> 
> 
>   Package              Version  Build           Channel       Size
> --------------------------------------------------------------------
>   Remove:
> --------------------------------------------------------------------
> 
>   - libxslt             1.1.33  h65864e5_2      installed
>   - lxml                 4.6.3  py39h4fd7cdf_0  installed
>   - pandas-datareader   0.10.0  pyh6c4a22f_0    installed
> 
>   Summary:
> 
>   Remove: 3 packages
> 
>   Total download: 0  B
> 
> --------------------------------------------------------------------

However, after updating my environment with `mamba update --all`, trying `mamba remove` again will just propose the main package for removal.

> Removing specs: ['pandas-datareader']
> Transaction
> 
>   Prefix: C:\Users\gv6\AppData\Local\miniforge3\envs\science
> 
>   Removing specs:
> 
>    - pandas-datareader
> 
> 
>   Package              Version  Build         Channel       Size
> ------------------------------------------------------------------
>   Remove:
> ------------------------------------------------------------------
> 
>   - pandas-datareader   0.10.0  pyh6c4a22f_0  installed
> 
>   Summary:
> 
>   Remove: 1 packages
> 
>   Total download: 0  B
> 
> ------------------------------------------------------------------

**Comment by AlphaScorpii-dev** [comment]
As I said, I have a copy of the environment, so if necessary I can run commands before / after the update to check what has been altered.
I noticed that a command like `conda env export --from-history` returns the whole list of packages after the update, whereas it would just return the list of manually installed packages before.

**Comment by AlphaScorpii-dev** [comment]
Here is the output for `mamba update --all`
It seems to aggressively write all the packages as manually installed for some reason.

> Looking for: ['argon2-cffi', 'async_generator', 'attrs', 'backcall', 'backports', 'backports.functools_lru_cache', 'bleach', 'brotlipy', 'bzip2', 'ca-certificates', 'certifi', 'cffi', 'chardet', 'charset-normalizer', 'colorama', 'conda', 'conda-package-handling', 'cryptography', 'cycler', 'debugpy', 'decorator', 'defusedxml', 'entrypoints', 'freetype', 'icu', 'idna', 'importlib-metadata', 'intel-openmp', 'ipykernel', 'ipython', 'ipython_genutils', 'ipywidgets', 'jbig', 'jedi', 'jinja2', 'jpeg', 'jsonschema', 'jupyter', 'jupyterlab_pygments', 'jupyterlab_widgets', 'jupyter_client', 'jupyter_console', 'jupyter_core', 'kiwisolver', 'krb5', 'lcms2', 'lerc', 'libarchive', 'libblas', 'libcblas', 'libclang', 'libcurl', 'libdeflate', 'libiconv', 'liblapack', 'libpng', 'libsodium', 'libsolv', 'libssh2', 'libtiff', 'libxml2', 'libxslt', 'lxml', 'lz4-c', 'lzo', 'm2w64-gcc-libgfortran', 'm2w64-gcc-libs', 'm2w64-gcc-libs-core', 'm2w64-gmp', 'm2w64-libwinpthread-git', 'mamba', 'markupsafe', 'matplotlib', 'matplotlib-base', 'matplotlib-inline', 'menuinst', 'miniforge_console_shortcut', 'mistune', 'mkl', 'mpmath', 'msys2-conda-epoch', 'nbclient', 'nbconvert', 'nbformat', 'nest-asyncio', 'notebook', 'numpy', 'olefile', 'openjpeg', 'openssl', 'packaging', 'pandas', 'pandas-datareader', 'pandoc', 'pandocfilters', 'parso', 'patsy', 'pickleshare', 'pillow', 'pip', 'prometheus_client', 'prompt-toolkit', 'prompt_toolkit', 'pycosat', 'pycparser', 'pygments', 'pyopenssl', 'pyparsing', 'pyqt', 'pyqt-impl', 'pyqt5-sip', 'pyqtchart', 'pyqtwebengine', 'pyrsistent', 'pysocks', 'python-dateutil', 'python_abi', 'pytz', 'pywin32', 'pywinpty', 'pyzmq', 'qt', 'qtconsole', 'qtpy', 'reproc', 'reproc-cpp', 'requests', 'ruamel_yaml', 'scipy', 'send2trash', 'setuptools', 'six', 'sqlite', 'statsmodels', 'sympy', 'tbb', 'terminado', 'testpath', 'tk', 'tornado', 'tqdm', 'traitlets', 'tzdata', 'ucrt', 'urllib3', 'vc', 'vs2015_runtime', 'wcwidth', 'webencodings', 'wheel', 'widgetsnbextension', 'wincertstore', 'winpty', 'win_inet_pton', 'xz', 'yaml', 'zeromq', 'zipp', 'zlib', 'zstd', '__cuda', '__win', '__archspec']
> 
> conda-forge/win-64       Using cache
> conda-forge/noarch       Using cache
> 
> Pinned packages:
>   - python 3.9.6
> 
> 
> Transaction
> 
>   Prefix: C:\Users\gv6\AppData\Local\miniforge3\envs\science
> 
>   Updating specs:
> 
>    - argon2-cffi
>    - async_generator
>    - attrs
>    - backcall
>    - backports
>    - backports.functools_lru_cache
>    - bleach
>    - brotlipy
>    - bzip2
>    - ca-certificates
>    - certifi
>    - cffi
>    - chardet
>    - charset-normalizer
>    - colorama
>    - conda
>    - conda-package-handling
>    - cryptography
>    - cycler
>    - debugpy
>    - decorator
>    - defusedxml
>    - entrypoints
>    - freetype
>    - icu
>    - idna
>    - importlib-metadata
>    - intel-openmp
>    - ipykernel
>    - ipython
>    - ipython_genutils
>    - ipywidgets
>    - jbig
>    - jedi
>    - jinja2
>    - jpeg
>    - jsonschema
>    - jupyter
>    - jupyterlab_pygments
>    - jupyterlab_widgets
>    - jupyter_client
>    - jupyter_console
>    - jupyter_core
>    - kiwisolver
>    - krb5
>    - lcms2
>    - lerc
>    - libarchive
>    - libblas
>    - libcblas
>    - libclang
>    - libcurl
>    - libdeflate
>    - libiconv
>    - liblapack
>    - libpng
>    - libsodium
>    - libsolv
>    - libssh2
>    - libtiff
>    - libxml2
>    - libxslt
>    - lxml
>    - lz4-c
>    - lzo
>    - m2w64-gcc-libgfortran
>    - m2w64-gcc-libs
>    - m2w64-gcc-libs-core
>    - m2w64-gmp
>    - m2w64-libwinpthread-git
>    - mamba
>    - markupsafe
>    - matplotlib
>    - matplotlib-base
>    - matplotlib-inline
>    - menuinst
>    - miniforge_console_shortcut
>    - mistune
>    - mkl
>    - mpmath
>    - msys2-conda-epoch
>    - nbclient
>    - nbconvert
>    - nbformat
>    - nest-asyncio
>    - notebook
>    - numpy
>    - olefile
>    - openjpeg
>    - openssl
>    - packaging
>    - pandas
>    - pandas-datareader
>    - pandoc
>    - pandocfilters
>    - parso
>    - patsy
>    - pickleshare
>    - pillow
>    - pip
>    - prometheus_client
>    - prompt-toolkit
>    - prompt_toolkit
>    - pycosat
>    - pycparser
>    - pygments
>    - pyopenssl
>    - pyparsing
>    - pyqt
>    - pyqt-impl
>    - pyqt5-sip
>    - pyqtchart
>    - pyqtwebengine
>    - pyrsistent
>    - pysocks
>    - python-dateutil
>    - python_abi
>    - pytz
>    - pywin32
>    - pywinpty
>    - pyzmq
>    - qt
>    - qtconsole
>    - qtpy
>    - reproc
>    - reproc-cpp
>    - requests
>    - ruamel_yaml
>    - scipy
>    - send2trash
>    - setuptools
>    - six
>    - sqlite
>    - statsmodels
>    - sympy
>    - tbb
>    - terminado
>    - testpath
>    - tk
>    - tornado
>    - tqdm
>    - traitlets
>    - tzdata
>    - ucrt
>    - urllib3
>    - vc
>    - vs2015_runtime
>    - wcwidth
>    - webencodings
>    - wheel
>    - widgetsnbextension
>    - wincertstore
>    - winpty
>    - win_inet_pton
>    - xz
>    - yaml
>    - zeromq
>    - zipp
>    - zlib
>    - zstd
>    - __cuda
>    - __win
>    - __archspec
>    - ca-certificates
>    - certifi
>    - openssl
> 
> 
>   Package       Version  Build       Channel                 Size
> -------------------------------------------------------------------
>   Change:
> -------------------------------------------------------------------
> 
>   - libtiff       4.3.0  h0c97f57_1  installed
>   + libtiff       4.3.0  h0c97f57_0  conda-forge/win-64      1 MB
> 
>   Upgrade:
> -------------------------------------------------------------------
> 
>   - libdeflate      1.7  h8ffe710_5  installed
>   + libdeflate      1.8  h8ffe710_0  conda-forge/win-64     61 KB
> 
>   Summary:
> 
>   Change: 1 packages
>   Upgrade: 1 packages
> 
>   Total download: 1 MB
> 
> -------------------------------------------------------------------

**Comment by wolfv** [comment]
Thanks for opening the issue. Indeed, you identified the problem correctly - we're not writing the right data to the history for update all.

**Comment by AlphaScorpii-dev** [comment]
As far as I can say, the issue is still present in latest release 0.27

**Comment by JohanMabille** [comment]
This can be done with mamba 2: `mamba remove --prune-deps`.
