### ISSUE TITLE
The miniconda env to install r with mamba display error

### ISSUE THREAD

**Issue by honghh2018** [mamba-org/mamba#1094]
Hi @mamba，
     What a geat tools improve the miniconda function.
      But i get error when using the mamba  to install r: mamba install r=4.0.2
      ERROR   Could not write out repodata file '/home/honghh/miniconda3/pkgs/cache/602d3932.json': No such file or directory
      For all, i try to tackle this issue with remove the total miniconda directory and  reinstall the latest miniconda 'Miniconda3-py39_4.9.2-Linux-x86_64.sh' once, but it was also complaint about below error:
      WARNING Could not parse mod / etag header!
      anaconda/cloud/bioconda/ [====================] (00m:00s) No change
      anaconda/cloud/bioconda/ [====================] (00m:00s) No change
      anaconda/pkgs/free/linux [====================] (00m:00s) No change
      anaconda/pkgs/free/noarc [====================] (00m:00s) No change
      anaconda/cloud/conda-for [====================] (00m:00s) No change
      pkgs/r/noarch            [====================] (00m:00s) No change
      pkgs/main/noarch         [====================] (00m:00s) No change
      pkgs/r/linux-64          [====================] (00m:00s) No change
      pkgs/main/linux-64       [====================] (00m:00s) No change
      anaconda/cloud/conda-for [                    ] (02m:04s) Finalizing...
      ERROR   Could not write out repodata file '/home/honghh/miniconda3/pkgs/cache/602d3932.json': No such file or directory

Had any tips for this?
It was appreciated.
Best,
Hanhuihong

**Comment by adriendelsalle** [comment]
Hi @honghh2018 , thanks for opening this issue and your nice comment!

This looks like a permission error on your filesystem.
I can't reproduce locally, it works well.

2 questions:
- from what channel do you expect `r=4.0.2` to be installed?
- it takes a very long time to download the repodata.json file from conda-forge, it could be corrupted but hopefully not missing. Any chance to retry with a faster connection?
