### ISSUE TITLE
Python pinning is too precise

### ISSUE THREAD

**Issue by mparry** [mamba-org/mamba#1099]
Currently mamba will pin Python at its exact semver, i.e. including the patch component. This seems incorrect, e.g. when running `mamba update --all` in an environment. I realised recently that, despite doing so semi-regularly, several of my envs had Python 3.9.1 instead of 3.9.5, which isn't something I would generally want.

Wouldn't it be more correct and/or the expected behaviour to only pin `major.minor` for it?

(I realise this functionality is based upon conda's, but I didn't think conda pinned the patch version. That said, quite a while since I used conda's solver, for obvious reasons!)

**Comment by wolfv** [comment]
Can you send a PR to fix this? https://github.com/mamba-org/mamba/blob/ceb85460fd22f6cb2e7446622b655dff7036718a/mamba/mamba.py#L492-L496

**Comment by mparry** [comment]
Sure. The associated PR seems to do the trick.

**Comment by adriendelsalle** [comment]
https://github.com/mamba-org/mamba/pull/1101#discussion_r680092430

There is something to investigate about the `python` pinning because even if the `SOLVER_LOCK` are correctly placed on solvables not matching the spec in `micromamba`, `python` is not part of the update specs when running `micromamba update --all`

**Comment by adriendelsalle** [comment]
Just checked quickly but it was a deliberate choice.
See https://github.com/mamba-org/mamba/blob/ceb85460fd22f6cb2e7446622b655dff7036718a/src/api/update.cpp#L38

Running
`micromamba create -n pins python=3.7.0` installs `python=3.7.0`
`micromamba update -n pins -a` proposes `python=3.7.10` (pinning is `python=3.7.*`)
`micromamba update -n pins -a python` proposes `python=3.9.6`

**Comment by mparry** [comment]
This issue concerns mamba though, not micromamba. (I hadn't actually tested the latter - we don't use it much currently.)

**Comment by adriendelsalle** [comment]
@mparry yep thanks for the precision, I mention it because the solving step should be the exact same for both, which is not the case.

**Comment by mparry** [comment]
Addressed by #1101
