### ISSUE TITLE
Handle multiple package cache and envs dirs

### ISSUE THREAD

**Issue by adriendelsalle** [mamba-org/mamba#1110]
Description
---

`libmamba` currently only consider `root_prefix` for packages cache and `envs/` directory when using a named environment.
We should be able to support multiple cache and env dirs, and make them configurable from rc files using `pkg_dirs` and `envs_dirs`.

The notion of `root_prefix` maybe also has to be modified in multiple places to be sure the `root_prefix` is a read-only source.
I think about some places like:
https://github.com/mamba-org/mamba/blob/ceb85460fd22f6cb2e7446622b655dff7036718a/src/core/channel.cpp#L62

**Comment by yarnabrina** [comment]
@adriendelsalle, @wolfv

Is there any plan to support `envs_dirs` in the configuration file for micromamba? Details of the issues are available in #1999. Personally I'm not much interested in multiple directories, but having control over the location is required for our particular use case of managing backup of Kubeflow notebooks.

**Comment by dhirschfeld** [comment]
I've ended up here after discovering that `micromamba` appeared to be ignoring my `envs_dirs` config.

I just have one env dir, but I'd like to be able to change it from the default of `$ROOT_PROFIX/envs`

**Comment by adriendelsalle** [comment]
sorry for the late reply, looks like `envs_dirs` config is set after `env_name`:
```bash
trace    libmamba Compute configurable 'env_name'
trace    libmamba Compute configurable 'envs_dirs'
```
a dependency should be added

the hook also looks like incorrect:
https://github.com/mamba-org/mamba/blob/ab22b6398533bcbd01f7642f7921636facbb6cfa/libmamba/src/api/configuration.cpp#L456
it should probably pick the first writable envs dir provided
