### ISSUE TITLE
mamba 0.15.x fails to expand default_channels from condarc

### ISSUE THREAD

**Issue by ConceptualWempa** [mamba-org/mamba#1115]
We override the default_channels list in our condarc to point to an artifactory caching proxy of repo.anaconda.com/pkgs/*

In mamba-0.14.x this list was correctly expanded in place of the 'defaults' keyword in the channels list, for all install-related sub-commands (install, update, create), somewhere inside this call in mamba.utils.get_index():

site-packages/mamba/utils.py:49:    real_urls = calculate_channel_urls(channel_urls, prepend, platform, use_local)

I _think_ the actual expansion occurs here in Channel.urls():

site-packages/conda/models/channel.py:181:        if self.canonical_name == UNKNOWN_CHANNEL:
site-packages/conda/models/channel.py:182:            return Channel(DEFAULTS_CHANNEL_NAME).urls(with_credentials, subdirs)

In mamba-0.15, there was a major overhaul of get_index(), moving much of the logic previously sourced from the conda package into the mamba codebase.  In the process, this expansion got lost - the result of which is, these operations use the "default defaults" embedded in the base conda package (i.e. repo.anaconda.com/pkgs/*), ignoring the overridden default_channels list in the condarc.  This behavior is exhibited by all 0.15.x versions so far (up to 0.15.2, as of submission).

Since this code is only exercised for install-related sub-commands, 'mamba info' shows the expected (substitute) default_channels entries expanded in the channel list, and 'mamba search' does use the substitute channels.

I was considering submitting a patch, but the get_index() change is fairly extensive, and I don't really understand the motivation behind it, so any patch I came up with would likely be clumsy, at best.

**Comment by as-ec** [comment]
This seems like it's in the same code area as https://github.com/mamba-org/mamba/issues/1113

**Comment by adriendelsalle** [comment]
Hi @ConceptualWempa !
Indeed this looks like the same bug as mentioned by @as-ec .

> I was considering submitting a patch, but the get_index() change is fairly extensive, and I don't really understand the motivation behind it, so any patch I came up with would likely be clumsy, at best.

Since `0.15.0`, `mamba` is using `libmamba` implementation of `Channel` instead of `conda`'s one. We need to figure out what's is not/not well implemented.

**Comment by wolfv** [comment]
@ConceptualWempa can you provide me your configuration values and your expected result?

I'll have a look

**Comment by wolfv** [comment]
I pushed a fix for this in #1119
