### ISSUE TITLE
Need help to show how to use repoquery with -c

### ISSUE THREAD

**Issue by opoplawski** [mamba-org/mamba#1127]
```
$ mamba repoquery -c intel  search numpy-base
usage: mamba repoquery [-h] {whoneeds,depends,search} ...
mamba repoquery: error: argument subcmd: invalid choice: 'intel' (choose from 'whoneeds', 'depends', 'search')
```
took me a while to find out that it needs to be at the end.

**Comment by wolfv** [comment]
Yeah I agree that's a little annoying!

We're adding the parsers from conda here: https://github.com/mamba-org/mamba/blob/2af07f74b71a581d8218e4e7e9bd67392d6c08b5/mamba/mamba.py#L838-L842

We can add them to the parent (`p`), however, then I think they don't work in the subcommands anymore... Any idea how to do this in a better way?

**Comment by opoplawski** [comment]
I'm afraid I know next to nothing about python argument parsing.  As long as the usage string mentioned how to use them properly, that would be a big help.

**Comment by wolfv** [comment]
Would be cool if you could make a PR to improve the Usage string
