### ISSUE TITLE
[micromamba] --auto-activate-base has no effect on init

### ISSUE THREAD

**Issue by maresb** [mamba-org/mamba#1138]
I would expect that when I run `micromamba shell init --shell=bash --auto-activate-base`, the `--auto-activate-base` should be inserted into the `micromamba shell hook` command which gets added in `~/.bashrc`.

With the current behavior, `--auto-activate-base` has no effect with `micromamba shell init --shell=bash`.

**Comment by maresb** [comment]
Looking at [`shell_init.cpp`](https://github.com/mamba-org/mamba/blob/master/src/core/shell_init.cpp), it seems to me like some substantial refactoring would probably be required in order to feed the boolean value of this flag into the necessary functions. Thus I sadly can't provide a PR.

**Comment by wolfv** [comment]
I checked, and auto-activate-base is actually handled inside the call to `hook`.

If you add `auto_activate_base: true` into your `.condarc` it should automatically add it to the end of what is printed with `micromamba shell hook`.

**Comment by wolfv** [comment]
I am removing the CLI option which didn't have any effect.
