### ISSUE TITLE
0.14.1 (and 0.15.3) selects incorrect package

### ISSUE THREAD

**Issue by as-ec** [mamba-org/mamba#1148]
When resolving dependencies mamba appears to select the first match rather than the most specific match when a local version label is used. 

```
$ conda  search -c https://artifactory.epoch.capital/artifactory/api/conda/epoch/gtp/release infra=6178
Loading channels: done
# Name                       Version           Build  Channel             
infra                    6178+LABEL 7fbc86c99a385335151c8392aa1ac195fc330294  artifactory/api/conda/epoch/gtp/release
infra                           6178 7fbc86c99a385335151c8392aa1ac195fc330294  artifactory/api/conda/epoch/gtp/release
```
In the above `mamba search` generates the same.

When installing mamba picks the local labelled version, not the version 6178.
```
mamba install -q -n md-proxy -c https://artifactory.epoch.capital/artifactory/api/conda/epoch/gtp/release -c https://artifactory.epoch.capital/artifactory/api/conda/conda-forge infra=6178
[.... ascii noise removed ...]
  + infra        6178+LABEL  7fbc86c99a385335151c8392aa1ac195fc330294  artifactory.epoch.capital/artifactory/api/conda/epoch/gtp/release/linux-64         61 MB
```

with conda 6178 is selected:

```
conda install -q -n md-proxy-c https://artifactory.epoch.capital/artifactory/api/conda/epoch/gtp/release -c https://artifactory.epoch.capital/artifactory/api/conda/conda-forge infra=6178

[.... ascii noise removed ...]
  infra              artifactory/api/conda/epoch/gtp/release/linux-64::infra-6178-7fbc86c99a385335151c8392aa1ac195fc330294
```

We're using the `+` here as conda "acnowledges" [PEP-440](https://www.python.org/dev/peps/pep-0440) for versions which allows for a local version label: `<public version identifier>[+<local version label>]`

**Comment by wolfv** [comment]
@as-ec the code that is supposed to do these comparisons is here: https://github.com/openSUSE/libsolv/blob/3d88b0ca5188e8d4a180ff30e7c183f71a367d0c/src/conda.c#L206-L211

Would be great if you could tackle this in libsolv! 

In general you could also set the build number to something higehr and that should work?

**Comment by wolfv** [comment]
maybe your problem is that only one of the two packages has a local version, and that that's handled wrongly.

**Comment by as-ec** [comment]
> maybe your problem is that only one of the two packages has a local version, and that that's handled wrongly. 

It's possible, it's seems to be the case that it won't pick the wrong local version (where there is an alternate), but that's only after an ad-hoc test so YMMV.

(aside)
For context (if you're interested), we use the conda-forge conda quite extensively. We have a channel for common packages (e.g. a compiler build, libs we want like boost). We have channels for our own firm specific binaries and libraries. We have channels for distributions that wrap the above up with configuration. We build different 'profiles' of binaries and use local versions to distinguish the non-default build. (We're revisiting this idea, as it's a pain for various reasons, but we need to be able to deploy old packages so it won't go away as a requirement). 

>In general you could also set the build number to something higehr and that should work?

The issue with that approach I have a set of historical packages with dependencies on other historical packages and they need to work. 

> Would be great if you could tackle this in libsolv!

I've never looked at libsolv, I guess in the first instance a failing test would be a good start. I assume there's some conda-specific unit tests in that code?

**Comment by wolfv** [comment]
hm, I am unsure what you mean with "local" version (since both versions in your search command seem to come from the same channel, so the channel priority should be equivalent).

Ok I see why you're preferring local versions. Thanks for the explanation.

Yeah, a failing test would be great. Unfortunately, right now, I think libsolv only has their own 'unit tests' which uses some text format. It would be nice to write some unit tests using `Check` or some other C testing framework.

**Comment by as-ec** [comment]
by local version I mean the 'local version label' that's described in PEP-440 [here](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers).

**Comment by as-ec** [comment]
Experimenting a bit, it's a bit of a mindfield in conda as well. Let's say we have a package A which depends on a package B. Let's say we have these versions:

A=1000 depends on B=1000
A=1000+LABEL depends on B=1000+LABEL

If the repo we are installing from has:
A=1000-buildNumber
A=1000+LABEL-buildNumber
B=1000+LABEL-buildNumber

then `conda install A=1000` will install A=1000+LABEL as it cannot resolve dependencies for A=1000 (no B=1000). I imagine there are quite a few use-cases where this is not what is wanted.

The only way I can find to say "install A but not any variant" is to do `conda install A=1000=buildNumber` (where I have the build number).

So, even if this issue is fixed and mamba works like conda, local version labels seem like  a bit of a minefield.

**Comment by wolfv** [comment]
and if A depends on `B>=1000,<1001`?

**Comment by as-ec** [comment]
...then the local label version is not returned.

**Comment by as-ec** [comment]
.... I thought about this a bit more and my conclusion was that I should move away from local labels and use build string appending instead, e.g. version=someBuildNumber_LABEL. The spec on how this is matched is more more specific and it does what you'd expect, including with wildcards.
