### ISSUE TITLE
Conda creates lock file

### ISSUE THREAD

**Issue by marcelned** [mamba-org/mamba#1150]
Running vannila conda creates lock files like `mambaforge-pypy3/pkgs/cache.pid383991.conda_lock`.

This prevents `mamba` from running, I have to manually delete said files.

This happens sporadically.

**Comment by wolfv** [comment]
@jaimergp any idea?

**Comment by jaimergp** [comment]
Looks like `conda` is not cleaning properly after those operations. Are you force exiting or something? We are not using anything else than conda's own locking mechanisms, which try to match the pid too, so this shouldn't be happening :/

**Comment by adriendelsalle** [comment]
Since we moved to `libmamba` implementation, I think this should be fixed in the next release

**Comment by adriendelsalle** [comment]
Closes by https://github.com/mamba-org/mamba/pull/1238
