### ISSUE TITLE
[micromamba] relative path in environment.yml not handled properly

### ISSUE THREAD

**Issue by marscher** [mamba-org/mamba#1154]
Within a recipe I'm performing a development installation using pip like this:

The recipe resides within a subdirectory, e.g. the top level directory contains a setup.py
``` yaml
dependencies:
  - pip
  - pip:
    - -e ../
```

When I create a environment using this file, I receive the following error:
```
Installing pip packages: -e ../
2021-09-06T14:01:47.1013804Z ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /home/runner/micromamba/envs
```
It seems that some process changed the working directory from the source/working directory to the envs dir of micromamba. But I could not figure out where this happens exactly. Note that the environment is being created by provision-with-micromamba. So there is no external, or explicit changing of directories.

Here you can have a look at the complete setup: https://github.com/marscher/weldx/blob/8b4213692ca81427deade4ebe6c55f558373672c/.github/workflows/docs.yml

**Comment by marscher** [comment]
You're right, sorry for opening it up in the wrong spot. 

I do not understand how I could fake a local path with a https url. Since the environment should match the cloned working copy, I do not think this is easy. However I could extract the git hash and pass it on to pip. Is that what you mean?

**Comment by wolfv** [comment]
so basically at some point we changed our implementation a bit and started to write a temporary "requirements.txt" file and use that with pip to install from (using `pip install -r {tempfile.txt}`.

Now maybe we need to go back on this to also support what you are trying here? Or that should anyways be handled seperately? It seems a bit of a hack, to be honest :)

Here is our code:

https://github.com/mamba-org/mamba/blob/505aba9a35adf46e99954e0bb26604a6c9ef442b/src/api/install.cpp#L31-L70

**Comment by wolfv** [comment]
although the `conda` code to do this looks pretty similar to ours:

https://github.com/conda/conda/blob/master/conda_env/installers/pip.py

Is the difference the `-U`?

**Comment by marscher** [comment]
It is a hack indeed. But a very convenient one :)

the `-U` option just tells pip to upgrade packages during the installation procedure.

**Comment by marscher** [comment]
I guess it is totally fine to have a intermediate requirements.txt, but somewhere the `cwd` is changed. This could also happen during the javascript routine setting up micromamba in the first place. I just started to transition to micromamba for CI.

**Comment by wolfv** [comment]
@marscher it's not "your fault" -- we explicitly set the `cwd` to the target prefix here: https://github.com/mamba-org/mamba/blob/505aba9a35adf46e99954e0bb26604a6c9ef442b/src/api/install.cpp#L56-L57

Do you want to suggest a change to set it to the ... current work directory?

**Comment by wolfv** [comment]
for conda, they figure out a `pip_workdir` based on the environment file location:

https://github.com/conda/conda/blob/bef6dbbb74df379b9a262551cd85be9ed2ae2e03/conda_env/installers/pip.py#L34-L40

**Comment by marscher** [comment]
> for conda, they figure out a `pip_workdir` based on the environment file location:
> 
> https://github.com/conda/conda/blob/bef6dbbb74df379b9a262551cd85be9ed2ae2e03/conda_env/installers/pip.py#L34-L40

This makes sense, right? If you depend on any file lying next to the environment file or recipe you won't find it in case it is specified by a relative path.
So it would be a proper solution to set the cwd like conda in this case.

**Comment by wolfv** [comment]
yep, I think it would be good to have the same behavior in mamba. 

PR welcome! :)

**Comment by marscher** [comment]
I hope that removing the change of working directory should fix this and not break anything else.

**Comment by wolfv** [comment]
I left a comment. IN the conda code I linked they explicitly compute a working directory. Would be good to emulate that.
