### ISSUE TITLE
[micromamba] cmake build missing SOLVER_FLAG_STRICT_REPO_PRIORITY

### ISSUE THREAD

**Issue by gdolle** [mamba-org/mamba#1155]
Hi all, 

I got this error

```sh
mamba-0.15.3/src/api/install.cpp:461:28: error:  SOLVER_FLAG_STRICT_REPO_PRIORITY’ was not declared in this scope
  461 |                          { SOLVER_FLAG_STRICT_REPO_PRIORITY,
```

Is it related to libsolv (I'm currently on last release 0.7.19) ?

**Comment by wolfv** [comment]
we have some patches that we apply to the conda-forge recipe of libsolv. 

They are related to open pull requests on libsolv: https://github.com/openSUSE/libsolv/pull/459 and https://github.com/openSUSE/libsolv/pull/449
