### ISSUE TITLE
Ascii Art banner causes environment export issues

### ISSUE THREAD

**Issue by marcelned** [mamba-org/mamba#1156]
`mamba list --explicit > spec-file.txt` writes ascii art banner at the top of the file, so that new users following [the official conda docs](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#building-identical-conda-environments) will encounter an error trying to restore the environment with `mamba create --name myenv --file spec-file.txt`

**Comment by wolfv** [comment]
Indeed. This would be great to fix. Do you think you could make a PR?
