### ISSUE TITLE
mamba does not support the "mamba update --all one_package==x.x.x" like conda

### ISSUE THREAD

**Issue by zhangfeiran** [mamba-org/mamba#1162]
This is useful to update all packages while excluding one specific package

**Comment by wolfv** [comment]
I think you could achieve that with pinned packages in the environment (add the package to `myenv/conda-meta/pinned` file.

But yeah, would be nice to have such a feature. Should be quite straightforward to do in `mamba.py` file. Would you be interested in making a PR?

**Comment by zhangfeiran** [comment]
I've made a PR in #1164, and tested it working, but not sure if it breaks something else or not...

Pinning that package also works, thank you.
