### ISSUE TITLE
conda env create -n [NAME] re-uses the most recent environment.yml if none is supplied

### ISSUE THREAD

**Issue by GDelevoye** [mamba-org/mamba#1166]
Hello,

I just had a strange issue. Instead of doing : 

```console 
(base) user@computer:$ mamba create -n newenv
```

I mistakenly did : 

```console
(base) user@computer:$ mamba env create -n newenv 
```

I was very surprised that, **instead of creating a new empty environment, it created an environment with the most recent environment.yml I used earlier** , and tried to install packages I never asked to

# SUMMARY

## Current behaviour :  

```mamba env create -n myenv``` with no "-f" option implicitely re-uses the last environment.yml file used

## Expected behaviour : 

```mamba env create -n myenv``` with no "-f" option should produce an empty environment

## Config

Ubuntu 20.03 LTS x86_64
mamba 0.15.3
conda 4.10.3

**Comment by GDelevoye** [comment]
Update : It seems that conda has a similar behaviour after all. Although not intuitive/logical (from my point of view) it seems that this is not a mamba issue after all. I close the issue.

**Comment by wolfv** [comment]
Thanks
