### ISSUE TITLE
Should mamba warn when latest version of a given software isn't resolvable?

### ISSUE THREAD

**Issue by sorenwacker** [mamba-org/mamba#1170]
I was just installing MaxQuant with Mamba:
 
    mamba install -c bioconda maxquant

I was a bit puzzles as Mamba wanted to install a rather old version of the software:

> Encountered problems while solving:
  - nothing provides mono >=5.0.0 needed by maxquant-1.6.2.10-0

I had to specify the version manually to get a more up to date version.

    mamba install -c bioconda -c conda-forge maxquant=2

I wonder if this is a bug or intentional. If the latter, what is the rationale behind that?

**Comment by wolfv** [comment]
Apparently you forgot the `-c conda-forge` in the first invocation.

What can we do if the latest version can't be resolved?!

One option could be to print the latest available version as a warning/info to the user.

**Comment by dhirschfeld** [comment]
> *One option could be to print the latest available version as a warning/info to the user.*

I think that could be very useful! I've also wanted that when an update fails to update, saying "[nothing to do](https://github.com/mamba-org/mamba/blob/48a43455e54218a676d21114965779a3298debbe/src/api/update.cpp#L51)" when in fact there *is* a newer package but it is incompatible with your existing environment.

**Comment by sorenwacker** [comment]
Oh, and without the `conda-forge` mamba was not able to find the correct `mono` version? The maxquant package is from the `bioconda` channel.

**Comment by wolfv** [comment]
yes, mono is prob only available from conda-forge.
