### ISSUE TITLE
mamba 0.15.3 fresh install crashes / is terminated immediately with SIGKILL

### ISSUE THREAD

**Issue by bjarchi** [mamba-org/mamba#1182]
I wanted to try out mamba, and had a completely fresh Miniforge install, so I decided to install it via:
`❯ conda install mamba -n base -c conda-forge`
which installed mamba 0.15.3

Then activate base and try to run any mamba command (so far) and I get this to stdout:
`❯ mamba search xtensor                                                                                                        ─╯
fish: Job 1, 'mamba search xtensor' terminated by signal SIGKILL (Forced quit)`

And a python crash dump:  [mamba_crash_log-0.txt](https://github.com/mamba-org/mamba/files/7230529/mamba_crash_log-0.txt)

This is on a Mac mini (M1) running OS 11.6 (Big Sur); Miniforge was installed via homebrew, which installed current Miniforge (4.10.3_5). As far as I can tell this should be supported as there is a native M1 mamba package, and searching didn't yield anything usefully similar. I tried both deactivating and reactivating the conda environment, and completely closing and reopening the shell with no change in results. 

More environment details: 

* Mac mini M1 / OS 11.6
* Fish shell in iterm2
* mamba 0.15.3 via conda install
* python 3.9.6 via Miniforge
* installed mamba into base environment

Not sure what else would be helpful for me to provide. I'm happy to provide more information or help with debugging as much as my experience and time allow.

**Comment by xhochy** [comment]
This could be https://github.com/conda-forge/libssh2-feedstock/issues/46, can you try whether `conda install 'libssh2<1.10'" fixes this?

**Comment by ismail** [comment]
Lower than syntax didn't work here, so I've tried `conda install libssh2=1.09` and it did fix the crash.

**Comment by wolfv** [comment]
Is this fix working?

**Comment by ismail** [comment]
> Is this fix working?

I am not the original reporter, but the fix is working here (M1 with macOS 12 beta).
