### ISSUE TITLE
Support for spec syntax "h5py[build=mpi*]"

### ISSUE THREAD

**Issue by paugier** [mamba-org/mamba#1194]
Thanks for mamba! It is great!

I tend to prefer the syntax `"h5py[build=mpi*]"` to the equivalent `"h5py=*=mpi*"`.

Unfortunately, it seems that mamba does not like it.

```
mamba create -n env_hdf5 "h5py[build=mpi*]"
```

selects the nompi version of h5py:

```
  h5py                     3.4.0  nompi_py39h7e08c79_101  conda-forge/linux-64     Cached
  hdf5                    1.12.1  nompi_h2750804_100      conda-forge/linux-64     Cached
```

In contrast, `conda  create -n env_hdf5 "h5py[build=mpi*]` gives:

```
  h5py               conda-forge/linux-64::h5py-3.4.0-mpi_mpich_py39ha1f86df_1
  hdf5               conda-forge/linux-64::hdf5-1.12.1-mpi_mpich_h9c45103_0
```

It seems that it it just a matter of parsing the spect, because mamba understands `"h5py=*[build=mpi*]"`.

**Comment by wolfv** [comment]
yeah I think this mgiht be related to a bug in the conda matchspec parser: https://github.com/conda/conda/pull/9980

**Comment by wolfv** [comment]
Maybe we should stop using the conda matchspec parser and rely on our implementation in `mamba` as well ...
