### ISSUE TITLE
More specific exceptions

### ISSUE THREAD

**Issue by jaimergp** [mamba-org/mamba#1196]
Right now, the idiom to run the solver and diagnose problems is like this:

```python
solved = solver.solve()
if not solved:
    raise RuntimeError(solver.problems_to_str())
```

This does not really allow to classify [exception types like `conda` does](https://github.com/conda/conda/blob/master/conda/exceptions.py). I am thinking of something like this could work, following `requests` style:

```python
solver.solve()
solver.raise_for_errors()
```

If it was successful, nothing happens. If it did fail, `raise_for_errors()` could parse the `libsolv` message and raise the most adequate exception type.

**Comment by wolfv** [comment]
I think this makes a lot of sense. Would be happy to have that in mamba!
