### ISSUE TITLE
potentially supporting more OSs than Conda?

### ISSUE THREAD

**Issue by dimpase** [mamba-org/mamba#1213]
It's not 100% clear whether Mamba ecosystem (i.e. Micromamba, Quetz, etc) is ready to support OSs beyond what's offered by Conda, e.g. FreeBSD would be a natural candidate. 

(This is more of a question than an issue).

**Comment by wolfv** [comment]
Hi @dimpase I don't think that there would be an issue in getting micromamba to run on FreeBSD. I guess that all dependencies and a C++ compiler are available! 

However, one would also need to have packages for FreeBSD to make this worthwhile :) Most conda packages currently need a host-installed `glibc` -- I don't know how FreeBSD works -- does it have glibc?

By the way, you can already use "arbitrary" subdirectories by passing `-c "mychannel[freebsd-64, noarch]"` on the command line, for example (just need to have the corresponding files on the server)!

If we figure out a good way to name the subdir, we could also add it to the pre-configured ones (incl. automatic detection of FreeBSD) cf: https://github.com/mamba-org/mamba/blob/3553249edb50c0293d9dc6555317f7fcb9e55652/include/mamba/core/context.hpp#L23-L28

Anything specifc you have in mind for the support?!

**Comment by dimpase** [comment]
it would be nice to have [SageMath](https://sagemath.org) installable on FreeBSD this way.

**Comment by wolfv** [comment]
There is nothing actionable here, so I am closing this issue for now. If you are interested in bootstrapping micromamba on FreeBSD or adding packages for FreeBSD to conda-forge or another channel, feel free to open with concrete issues :)
