### ISSUE TITLE
Mamba always wants to change `qt`

### ISSUE THREAD

**Issue by pkgw** [mamba-org/mamba#1225]
Whenever I run a `mamba update --all`, Mamba wants to "change" my `qt` package (from conda-forge) in a noop way:

```
Change:

- qt                                5.12.9  hda022c4_4  installed
+ qt                                5.12.9  hda022c4_4  conda-forge/linux-64     Cached
```

Small updates seem pretty fast, so it's not killing my performance, but it's annoying. Any ideas as to why this might be happening?

**Comment by wolfv** [comment]
@pkgw what mamba version are you using? Do you have a Anaconda token? Can you check the URL recorded in `pkgs/qt-5.12.9-hda022c4_4/info/repodata_record.json`?

**Comment by pkgw** [comment]
Oh, right — recently I had to reinstall my Qt-related packages and this problem went away. (I somehow had ended up with a combination of pip- and mamba-installed packages.) The noop "change" still seems like a bug, but without being able to reproduce the issue anymore, I think the best thing to do here is close this issue.

**Comment by wolfv** [comment]
Thanks. Maybe an update to mamba also fixed this. At some point we were not comparing the cleaned URL, but the URL with token vs the URL without token.
