### ISSUE TITLE
[micromamba] add self-update

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1230]
We should add a function to micromamba to do a self-update.

It could find the latest version from `anaconda.org` and then download and replace itself. We could look at homebrew.

**Comment by wolfv** [comment]
When updating `oh-my-zsh` it's pretty cool that they print a changelog like this:

<img width="970" alt="Screenshot 2021-11-01 at 15 27 36" src="https://user-images.githubusercontent.com/885054/139687751-dc0ab7b1-7b42-4294-82fd-4834edccdb2e.png">

**Comment by YYYasin19** [comment]
The implementation for the core swapping should still be fairly easy, right? Just downloading and swapping the executable in a safe manner.

The harder question, in my opinion, would be: How should the interface look like? 

- `update` is already taken for updating packages in an environment.
- `upgrade` always feels unclear to me on what it does
- `self-update` sounds reasonable but should make it clear that its definitely updating the core executable (as opposed to `micromamba update micromamba` within an environment)

I really like showing the changelog as well! Maybe even just for `--dry-run`?

**Comment by wolfv** [comment]
@cossio we do have `micromamba self-update` since version 1.0.

The other option is to run `curl micro.mamba.pm/install.sh | bash` to reinstall.

We're missing the display of the changelog (will open a new ticket for that).
