### ISSUE TITLE
micromamba python:noarch ERROR   stoull 

### ISSUE THREAD

**Issue by mariusvniekerk** [mamba-org/mamba#1244]
When installing the following two lockfiles in order

https://gist.github.com/mariusvniekerk/cb227d238193a073abbb687385bf19ae

using 

```
micromamba create -p foo --file lockfile0.lock
micromamba install --v -p foo --file lockfile1.lock
```

The second command will crash with the following output

```
INFO    Installing explicit specs for platform # total_size: 14209509
INFO    Parsing MatchSpec https://conda.anaconda.org/conda-forge/noarch/appdirs-1.4.4-pyh9f0ad1d_0.tar.bz2
INFO    Using OpenSSL backend
INFO    Starting to download targets
INFO    Transfer done ...
INFO    Transfer finalized, status: 200 [https://conda.anaconda.org/conda-forge/noarch/appdirs-1.4.4-pyh9f0ad1d_0.tar.bz2] 12840 bytes
INFO    Download finished, validating '/root/micromamba/pkgs/appdirs-1.4.4-pyh9f0ad1d_0.tar.bz2'
INFO    Extracting "/root/micromamba/pkgs/appdirs-1.4.4-pyh9f0ad1d_0.tar.bz2" to "/root/micromamba/pkgs/appdirs-1.4.4-pyh9f0ad1d_0"
Finished appdirs                              (00m:00s)               0  B     50 KB/s
INFO    No python version given to TransactionContext, leaving it empty
Linking appdirs-1.4.4-pyh9f0ad1d_0
INFO    Installing Python noarch package
INFO    Compiling "__pycache__/appdirs.cpython-.pyc"
ERROR   stoull
```

It appears as if in the second case micromamba isn't aware of the python already installed into `foo`

**Comment by adriendelsalle** [comment]
Hi @mariusvniekerk, thanks for opening this issue.
I can reproduce it and will have a look. I tried to `activate` the env before the second command, without further success
```
micromamba create -n foo --file lockfile0.lock
micromamba activate foo
micromamba install -v -n foo --file lockfile1.lock
```

**Comment by wolfv** [comment]
@adriendelsalle i think the problem is that we're not looking into the existing prefix when starting the transaction, and then we're not putting the proper value for the Python version into the TransactionContext.

**Comment by adriendelsalle** [comment]
Yes it looks like for explicit transactions we are not loading the prefix as repo (the `installed` one)
