### ISSUE TITLE
  - nothing provides requested package

### ISSUE THREAD

**Issue by ne1al** [mamba-org/mamba#1246]
Hello,
I am new to mamba but heard of its great performance. I am having issues resolving environments for kraken2 package using conda on macOS Catalina. I thought of trying mamba but I encountered an error. Could you advise?
The code:
`mamba install kraken2 -c conda-forge`

The Error:
```
Pinned packages:
  - python 3.9.*


Encountered problems while solving:
  - nothing provides requested kraken2
```

**Comment by wolfv** [comment]
you need to get thsi package from `-c bioconda` channel

**Comment by ne1al** [comment]
Super! I had to set up rsync first. Thank you.
