### ISSUE TITLE
Feature request: solver webservice

### ISSUE THREAD

**Issue by maresb** [mamba-org/mamba#1247]
Apologies if this isn't the correct forum, I'm happy to migrate this somewhere else.

With mamba, the solver runs lightning-fast. The current bottleneck is now the download of these large repo-data files. It's a bit of a drag to have to download 30 MB of repo-data to install a 10k package.

Wouldn't it be cool if solving happened in the cloud, without the need to constantly refresh the local repo-data? That would be very useful for bandwidth-limited connections (*glancing at Deutsche Bahn...*).

This could be a great task for the QuantStack superstars :superhero:!

**Comment by wolfv** [comment]
We have this in the quetz plug-ins :)

**Comment by maresb** [comment]
Dude, is there anything you haven't already done!?!? :laughing: 

https://github.com/mamba-org/quetz/tree/master/plugins/quetz_mamba_solve

**Comment by wolfv** [comment]
:) glad you find it useful!
