### ISSUE TITLE
Implement changeps1 config

### ISSUE THREAD

**Issue by adriendelsalle** [mamba-org/mamba#1256]
micromamba ignoring my config.
The content of my `.condarc`:
```
channels: [conda-forge]
changeps1: false
auto_activate_base: true
```
This config is working with `mamba` but not `micromamba`.

If I run `micromamba config list | grep 'changeps1'` it will return no result.

Running `micromamba config sources` I get
```
Configuration files (by precedence order):
~/.condarc
```

_Originally posted by @RayPS in https://github.com/mamba-org/mamba/issues/966#issuecomment-876464065_

**Comment by wolfv** [comment]
It's done! :)

**Comment by wolfv** [comment]
part of #1304
