### ISSUE TITLE
mamba create -p directory/envname fails when directory does not exist

### ISSUE THREAD

**Issue by vroetman** [mamba-org/mamba#1258]
`mamba create -p directory/envname package` fails when directory `directory` does not exit.

This was introduced in mamba [0.15.3 line 511](https://github.com/mamba-org/mamba/blob/fe4ecc5061a49c5b400fa7e7390b679e983e8456/mamba/mamba.py#L511) with

    with FileLock(context.target_prefix):
        prefix_data = api.PrefixData(context.target_prefix)
        prefix_data.load()

In mamba version 0.17.0, it fails on line 509 of mamba.py:

    mamba create -p asdf/asdf ripgrep
    ...
      File "/home/vroetman/mf/lib/python3.9/site-packages/mamba/mamba.py", line 660, in create
        return install(args, parser, "create")
      File "/home/vroetman/mf/lib/python3.9/site-packages/mamba/mamba.py", line 509, in install
        with FileLock(context.target_prefix):
      File "/home/vroetman/mf/lib/python3.9/site-packages/conda/lock.py", line 69, in __init__
        assert isdir(dirname(self.path_to_lock)), "{0} doesn't exist".format(self.path_to_lock)

    AssertionError: /home/vroetman/asdf/asdf doesn't exist

A workaround is to create the directory in advance, or to use conda.

**Comment by adriendelsalle** [comment]
Hi @vroetman 

This should be fixed by https://github.com/mamba-org/mamba/pull/1238, using `libmamba` lock files in `mamba`.
We will cut a release soon!
