### ISSUE TITLE
zsh completion with `bashcompinit`

### ISSUE THREAD

**Issue by MaxCan-Code** [mamba-org/mamba#1262]
The bash completion works on zsh by following a similar instruction from pipx: https://github.com/pypa/pipx/blob/main/src/pipx/constants.py#L55-L64

**Comment by adriendelsalle** [comment]
@MaxCan-Code could you please elaborate a bit?
Is it something you would like to have in the documentation?

**Comment by MaxCan-Code** [comment]
Yes, documenting it would be helpful
