### ISSUE TITLE
mamba cannot be found after activating environment

### ISSUE THREAD

**Issue by kylekeppler** [mamba-org/mamba#1265]
Using mambaforge in bash within VS Code on Windows 10.

After I activate an environment (`conda activate myenv`), `mamba` cannot be found. It is able to be found within the base environment.

```
user@host MINGW64 /c/workspace/myproj (feature/myfeature)
$ mamba
bash: mamba: command not found
```

Where _should_ `mamba` be found? 

These items are at the beginning of `$path` after activating:

```
/c/apps/mambaforge/envs/myenv
/c/apps/mambaforge/envs/myenv/Library/mingw-w64/bin
/c/apps/mambaforge/envs/myenv/Library/usr/bin
/c/apps/mambaforge/envs/myenv/Library/bin
/c/apps/mambaforge/envs/myenv/Scripts
/c/apps/mambaforge/envs/myenv/bin
/c/apps/mambaforge/condabin
```

`where` can find `mamba`, but `which` cannot:
```
user@host MINGW64 /c/workspace/myproj (feature/myfeature)
$ where mamba
C:\apps\mambaforge\condabin\mamba.bat

user@host MINGW64 /c/workspace/myproj (feature/myfeature)
$ which mamba
which: no mamba in <$path>
```

and `mamba.bat` does exist at `/c/apps/mambaforge/condabin`:
```
user@host MINGW64 /c/workspace/myproj (feature/myfeature)
$ ls /c/apps/mambaforge/condabin
_conda_activate.bat  activate.bat  conda.bat  conda_auto_activate.bat  conda_hook.bat  deactivate.bat  mamba.bat  rename_tmp.bat
```

I _can_ run `mamba` if I include the extension: `$ mamba.bat`. So guess I've found a workaround.

Any ideas why `mamba` alone does not work?

**Comment by wolfv** [comment]
you need to `init` the right shell. Run `mamba init`.

**Comment by kylekeppler** [comment]
Thanks @wolfv!

**Comment by psobolewskiPhD** [comment]
I've got this same issue on macOS after updating mamba to the latest release.
I'm using `fish` shell, which I guess isn't really supported? but previously mamba in `base` worked in all other envs...

**Comment by wolfv** [comment]
There was an issue with 0.18 release that we're fixing right now https://github.com/conda-forge/mamba-feedstock/pull/137
