### ISSUE TITLE
Installing poppunk package, missing dependencies

### ISSUE THREAD

**Issue by ne1al** [mamba-org/mamba#1266]
Hello!
I am asking if there is an automated way to install all needed dependencies for [poppunk package](https://anaconda.org/bioconda/poppunk) without having to install them manually from conda-forge channel? 
I am going into infinite loop of installing different dependencies (gfortran_impl_osx-64, xorg-libxcomposite, xorg-libxcursor, etc) and it does not seem to be ending.
Thanks

**Comment by wolfv** [comment]
Can you give some more context? What commands are you running and what channels are you using?

**Comment by ne1al** [comment]
**1. Command:**
`mamba install -c bioconda prokka
`
**2. Then I receive many of the below:**
```
Encountered problems while solving:
  - nothing provides gfortran_impl_osx-64 as needed by prokka
```
**3. Then I try to install the needed packages or libraries using the conda forge channel**
`mamba install -c conda-forge gfortran_impl_osx-64
`
**4. Again I try to install prokka:**
`mamba install -c bioconda prokka
`
Then I keep getting multiple of nothing provides X as needed by Y

**Comment by adriendelsalle** [comment]
@ne1al did you just tried `mamba install -c bioconda -c conda-forge prokka`?
It works fine for me on linux-64.

**Comment by wolfv** [comment]
for `bioconda` you always need to use `conda-forge` as well.

or run these commands:

```
conda config --add channels bioconda
conda config --add channels conda-forge
```

please read the docs: https://bioconda.github.io/user/install.html

**Comment by ne1al** [comment]
@adriendelsalle It worked perfectly fine! I used to install packages from bioconda channel only. Thanks a lot!
@wolfv Thank you
