### ISSUE TITLE
Problem solving `__cuda` constraints

### ISSUE THREAD

**Issue by pentschev** [mamba-org/mamba#1267]
It should be possible to install newer `cudatoolkit` builds than the CUDA/NVIDIA driver version installed a machine. The following works on a machine with CUDA 11.2, when requesting `cudatoolkit=11.5`:

```
$ conda create -n tmp -c conda-forge python=3.8 conda-forge::cudatoolkit=11.5
```

However, mamba seems to be unable to resolve that conflict:

```
$ mamba create -n tmp -c conda-forge python=3.8 conda-forge::cudatoolkit=11.5

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.17.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['python=3.8', 'conda-forge::cudatoolkit=11.5']

rapidsai-nightly/noarch  [====================] (00m:00s) No change
rapidsai-nightly/linux-6 [====================] (00m:00s) No change
nvidia/linux-64          [====================] (00m:00s) No change
nvidia/noarch            [====================] (00m:00s) No change
conda-forge/noarch       [====================] (00m:01s) Done
conda-forge/noarch       [====================] (00m:01s) Done
conda-forge/linux-64     [====================] (00m:04s) Done
conda-forge/linux-64     [====================] (00m:04s) Done
Encountered problems while solving:
  - package cudatoolkit-11.5.0-h36ae40a_9 has constraint __cuda >=11.5.0 conflicting with __cuda-11.2-0
```

It isn't clear to me whether this is a limitation on mamba resolving conflicts or if there's some special-casing that conda does to work around this problem. It's still possible to override that by having the `CONDA_OVERRIDE_CUDA=11.5` environment variable set.

Could someone more knowledgeable on mamba advise?

cc @jakirkham @bdice

**Comment by adriendelsalle** [comment]
> It should be possible to install newer cudatoolkit builds than the CUDA/NVIDIA driver version installed a machine.

@pentschev I don't understand that statement, could you please elaborate a bit more? Is it your expectation vs `conda`'s behavior or something else?

I can't really see a bug `mamba`'s side about solving this specification since the `cudatoolkit`'s dependency on `__cuda` virtual package is `__cuda >={{ major_minor }}` (see the [feedstock]( https://github.com/conda-forge/cudatoolkit-feedstock/blob/500d3b9c6b855f645d798b1186e7207a8825e0d9/recipe/meta.yaml#L475)). If you don't have `__cuda 11.5` on your machine it's then normal behavior to *not* be able to install `cudatoolkit=11.5` (except using the `CONDA_OVERRIDE_CUDA` env var to override/force the detection of your drivers).

As far as I understand, `mamba` has a correct behavior and `conda` doesn't respect the `cuda` virtual package dependency.

**Comment by wolfv** [comment]
What cuda version does `nvidia-smi` report? Or can you give the output of conda info?

**Comment by adriendelsalle** [comment]
@wolfv I tested locally with 11.4 drivers and I can reproduce the behavior: `conda` installs `cudatoolkit=11.5` and `mamba`/`micromamba` can't solve

**Comment by wolfv** [comment]
Yea conda has a bug. https://github.com/conda-forge/nspr-feedstock/pull/23

**Comment by pentschev** [comment]
This makes sense to me in general that `mamba` respects `__cuda`. In my case I have CUDA 11.2 installed, and I intentionally wanted to install the 11.5 build since beginning with CUDA 11.5 there's CUDA Enhanced Compatibility, which should allow running on any CUDA 11.x driver.

@jakirkham do you have any thoughts on the right way to move forward? Is the `__cuda` constraint something that should be relaxed in `cudatoolkit=11.5`? We can also move this discussion elsewhere, since it doesn't seem to me that `mamba` has an issue.

**Comment by wolfv** [comment]
It would be best to have this discussion on the cuda toolkit feedstock :)

**Comment by pentschev** [comment]
Agreed, I opened https://github.com/conda-forge/cudatoolkit-feedstock/issues/71 now for that. Thanks @adriendelsalle and @wolfv for the help understanding this!

**Comment by jaimergp** [comment]
I think `conda` has it as [known broken in their tests](https://github.com/conda/conda/blob/master/tests/core/test_solve.py#L357-L386).
