### ISSUE TITLE
micromamba info --json missing

### ISSUE THREAD

**Issue by jcox10** [mamba-org/mamba#1268]
Conda has `--json` available for the `conda info` command. This is used by some code scanners (such as synopsys detect) to gather information about the environment. Micromamba is missing the `--json` option for `micromamba info --json`.

```bash
./micromamba info --json
The following argument was not expected: --json
Run with --help for more information.
```

**Comment by adriendelsalle** [comment]
https://github.com/mamba-org/mamba/issues/1181

**Comment by jcox10** [comment]
Thanks for fixing this so quickly! I can confirm that with this change, micromamba now works with Synopsys Detect.
