### ISSUE TITLE
[micromamba] extraction logs `info Extracting ...`

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1282]
For some reason we see `info     Extracting "/Users/wolfvollprecht/micromamba/pkgs/keras-2.6.0-pyhd8ed1ab_1.tar.bz2" to "/Users/wolfvollprecht/micromamba/pkgs/keras-2.6.0-pyhd8ed1ab_1"` etc. all the time with micromamba, interleaved with the progressbars and stuff.

**Comment by adriendelsalle** [comment]
I think it was related to the missing init of the logger level using the context value, making it taking the spdlog default value which is info.
This should be fixed by https://github.com/mamba-org/mamba/pull/1279
