### ISSUE TITLE
Check that `mamba clean --locks` works fine

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1285]
I had a situation where I closed the terminal window while mamba was extracting. 
After running mamba again, it told me that the "same PID has already locked the file" and then exited. 

I ran `mamba clean --lock` but it didn't seem to clean up that `mamba.lock` file.

I think we shoudl also print the full path to the lock file and some more explanation.

I was also confused because I don't believe that the PID of the next mamba process would be the same as the previous one.

**Comment by ManifoldFR** [comment]
I started getting the same error as you did, today. Indeed the `mamba.lock` lockfile wasn't being cleaned up.

**Comment by adriendelsalle** [comment]
@wolfv did you checked if the lock file was orphaned (e.g. the lock file name was not corresponding to any existing file to lock)?

To avoid deletion of environment *lock* files (in user or packages' files), I put a check about existence of a file having the same name without the `.lock` extension.
https://github.com/mamba-org/mamba/blob/acc44f8cef95808dd2689f62629ff0fad28b682c/libmamba/src/api/clean.cpp#L69-L70

The error is probably more about having the same PID, any clue how to reproduce this? I'm not able to reproduce locally.
