### ISSUE TITLE
`mamba env update` asks for confirmation

### ISSUE THREAD

**Issue by tschoonj** [mamba-org/mamba#1296]
Hi all,

I noticed that recently (since 0.18.0?) `mamba env update` started asking for a confirmation, which is kind of annoying as you cannot pass `--yes` to confirm automatically when running this in scripts on e.g. CI.

Is this intentional? Would be great if a `--yes` option could be implemented, similar to what `conda` has.

**Comment by tschoonj** [comment]
Note that `conda env update` does not ask for confirmation.

**Comment by wolfv** [comment]
thanks, yes, we can fix that
