### ISSUE TITLE
Using mamba in parallel with anaconda

### ISSUE THREAD

**Issue by BptGrm** [mamba-org/mamba#1299]
Hi,

I recently came across `mamba`, and I was wondering if it could work in a specific use case : 

I have access to a shared workstation, running on Windows 10, that I want to use for GPU-based calculations.
There is already an `anaconda` install with several environments.  However, it was installed in the User folder, and since the username contains spaces, so does the path to the environments, and that's still an issue for some scripts. 

Now the official `Anaconda` way of solving that issue is to uninstall everything and reinstall it at (or closer to) root, but I have no guarantee that some of the older environments will be able to be reinstalled from scratch just as they were before.

As I've read : `Another alternative (if you want/need to avoid Anaconda entirely) is to use Mambaforge via the Miniforge distribution.`, I was wondering if it would be possible to install `mamba` through `manbaforge`, separated from `anaconda`, and have specific environments that do not conflict with each other ?

Thanks !

**Comment by wolfv** [comment]
Hi BptGrm, yes, that's totally possible. Installing `mambaforge` will give you another "base" environment. 

What's a bit tricky is how you can use the two base environments at the same time. There is not really a good solution to that. Maybe if you install the desktop shortcut when runnign the installer you will get another launcher that will launch into mambaforge env to let you modify environments.
