### ISSUE TITLE
`sys.executable` "wrong" for python 3.10

### ISSUE THREAD

**Issue by ianhi** [mamba-org/mamba#1302]
When I create a new environment with:

```
mamba create -n test python=3.10
conda activate test
```

then when in some contexts (ipython, and pre-commit) `sys.executable` reports `.../python3.1`. This is causing `pre-commit run --all-files` to fail for me and from discussion here: https://github.com/pre-commit/pre-commit/issues/2139  it would seem that this should be considered a bug in the package manager per this comment:

> if your executable is named python3.1 I'd start with whatever thing erroneously created that executable

I'm a bit confused overall about what is to be expected, and why having this link is breaking things. So I'm happy to bring this up elsewhere if this isn't the appropriate place.

**Comment by wolfv** [comment]
What mamba, and more importantly what conda version are you using?

**Comment by ianhi** [comment]
```
mamba 0.7.6
conda 4.10.3
```

**Comment by ianhi** [comment]
Oh wow, that's pretty out of date it would seem. let me try after updating

**Comment by wolfv** [comment]
Yeah conda had a bug related to this and we are using conda to do the linking

**Comment by ianhi** [comment]
Updating with `mamba upgrade mamba` and `mamba upgrade conda` then recreating the environment seems to fix this! 

Thanks!


New env for posterity:
```
mamba 0.18.1
conda 4.11.0
```
