### ISSUE TITLE
mamba env create prompts for confirmation

### ISSUE THREAD

**Issue by oliver-sanders** [mamba-org/mamba#1307]
Between mamba 0.17 and 0.18.2 `mamba env create` started to require confirmation for creating environments:

```console
$ mamba --version
mamba 0.18.2
conda 4.10.3
$ mamba env create -f <file> -n <name>
...
  Summary:

  Install: 51 packages

  Total download: 0  B

───────────────────────────

Confirm changes: [Y/n]
```

`conda env create` doesn't seem to require this confirmation step.

This is an issue for creating environments non-interactively (e.g. in CI).

This workaround does the job:

```console
$ yes | mamba env create -f <file> -n <name>
```

Extra Info:

* The environment `<name>` was not in use at the time the command was run.
* Spotted with `mamba 0.18.2` & `conda 4.10.3`.
* Doesn't occur with `mamba 0.17.0` & `conda 4.10.3`.

Thanks.

**Comment by wolfv** [comment]
this is fixed in https://github.com/mamba-org/mamba/pull/1301

Sorry for the hiccup.

**Comment by oliver-sanders** [comment]
Thanks for the speedy fix.
