### ISSUE TITLE
improve the performance of micromamba/mamba in the channel package index fetching

### ISSUE THREAD

**Issue by living1069** [mamba-org/mamba#1321]
Channel package index (CPI) is becoming bigger and bigger. The conda-forge/linux-64 CPI has reached 150MB. Micromamba/Mamba will download PCPIs again when installing another tiny program in two days. It is impossible that the channel has changed so much. 
Here is my preliminary solution: 1. prepare a package of channel package index (PCPI); 2. Micromamba/Mamba will check the cached PCPI if available; 3. Micromamba/Mamba will only check newer version of PCPI if failing to resolve. 
Maybe there is a better solution to this issue from you brilliant authors. Thanks!

**Comment by wolfv** [comment]
Hi, yes, I agree that this is an issue. 
We do have a cache, and you can set the lifetime using the `repodata_ttl` config. 

You can also use `--offline` to avoid downloading data again.

We are working on adding `zchunk` support to mamba so we only need to download what's necessary. This work is happening in https://github.com/mamba-org/powerloader
