### ISSUE TITLE
Confusing micromamba error when shell not initialized

### ISSUE THREAD

**Issue by maresb** [mamba-org/mamba#1323]
Running `micromamba activate base` when the shell is not initialized results in
```
The following arguments were not expected: base activate
Run with --help for more information.
```

This can be very confusing for new users. Or for more experienced users who are struggling with various types of Bash shells in Docker. :wink:

I would expect that the output should look something like:
```
Cannot activate an environment when the shell has not been initialized. Please run

    micromamba shell init --shell=basename($SHELL) --prefix=/path/to/conda/prefix

and restart the shell, or run

    eval "$(micromamba shell hook --shell=bash)"

to activate the current shell.
```

**Comment by sorenwacker** [comment]
There is a stackoverflow question related to this: https://stackoverflow.com/questions/78373520/how-run-jupyter-lab-inside-micromamber-apptainer-container

**Comment by maresb** [comment]
Hey @sorenwacker, I responded on SO.
