### ISSUE TITLE
A replacement for homebrew/macports?

### ISSUE THREAD

**Issue by jasongrout** [mamba-org/mamba#1330]
I'm experimenting with using micromamba as a replacement for homebrew/macports on macos.

```
mkdir /usr/local/micromamba
<some chown step so micromamba is writable - I assume it's bad practice to run micromamba as sudo?>
micromamba -p /usr/local/micromamba/env
```

Then add `/usr/local/micromamba/env/bin` to `$PATH`.

Installing a program is just activating the environment and doing `micromamba install`.

Is there anything obviously wrong with this?

**Comment by maartenbreddels** [comment]
I think the only thing missing is the `micromamba` function that needs to be injected into the `.zshrc` or `.bashrc`, so you miss the `activate/deactivate` magic from (in my case) `/Users/maartenbreddels/micromamba/etc/profile.d/mamba.sh`

**Comment by maartenbreddels** [comment]
off topic:
these `uma` `uma` 'aliases' to activate and deactivate might also be useful
```
uma() {
    \local cmd="activate"
    __mamba_activate "$cmd" "$@"
}

umd() {
    \local cmd="deactivate"
    __mamba_activate "$cmd" "$@"
}
```

**Comment by jasongrout** [comment]
Right, sorry, I forgot to mention that before I set this up I installed micromamba, including adding this shell configuration to my `.zshrc`.

**Comment by wolfv** [comment]
I think this should be perfectly fine! :)
