### ISSUE TITLE
No error output with micromamba 0.18 --json

### ISSUE THREAD

**Issue by baszalmstra** [mamba-org/mamba#1335]
We have been using `micromamba --json` internally and found a regression where error messages are no longer displayed.

The output of `micromamba 0.16.0`:
```
❯ ./micromamba.0.16.0 env create -p test xtensor "xtl <0.1" -c conda-forge --json
WARNING 'test' does not contain any filesystem separator.
        It will be handled as env name, resulting to the following
        'target_prefix': '/home/bzalmstra/micromamba/envs/test'
        If 'target_prefix' is expressed as a relative directory to
        the current working directory, use './some_prefix'
Encountered problems while solving:
  - nothing provides requested xtl <0.1

ERROR   Could not solve for environment specs
```

The output of `micromamba 0.18.0`:
```
❯ ./micromamba.0.18.1 env create -p test xtensor "xtl <0.1" -c conda-forge --json
```

Neither is perfect: `0.16.0` outputs non-json (but on stderr so that's fine for me). `0.18.1` outputs nothing. 

I would expect the error to be outputted as json as well, so I can consume it in another tool.

**Comment by wolfv** [comment]
I just tested and I get some beautiful json for the command line input you provided :)
