### ISSUE TITLE
Building micromamba: Unable to install package for sel(win).

### ISSUE THREAD

**Issue by baszalmstra** [mamba-org/mamba#1336]
I'm following the guide from [the docs](https://mamba.readthedocs.io/en/latest/developer_zone/build_locally.html).

I got the following error when running: 

```
mamba env create --name micromamba --file ./micromamba/environment-dev.yml
```

```
Unable to install package for sel(win).

Please double check and ensure your dependencies file has
the correct spelling.  You might also try installing the
conda-env-sel(win) package to see if provides the required
installer.
```

Im running:

```
$ mamba --version
mamba 0.18.2
conda 4.10.1
```

The offending line seems to be: `- sel(win): winreg`. Should that be supported?

**Comment by wolfv** [comment]
that is only supported with `micromamba` in fact :)

You can comment out this line when not building on Windows.

**Comment by baszalmstra** [comment]
Thanks! :)
