### ISSUE TITLE
'requires' error when installing tensorflow, points to already-installed package

### ISSUE THREAD

**Issue by brsolomon-deloitte** [mamba-org/mamba#1354]
Installing `tensorflow-cpu==2.6.2` shows that libprotobuf >=3.19.1,<3.20.0a0 cannot be installed, even though libprotobuf 3.19.1 is already installed.

**To reproduce**

Run following Docker container:

```
docker container run -it --rm --entrypoint=bash --user=0 \
  jupyter/all-spark-notebook
```

Run these commands:

```
cat << EOF > req.txt
jupyterhub
nbgitpuller
pyspark
boto3
elasticsearch
altair
beautifulsoup4
bokeh
bottleneck
cloudpickle
cython
dask
h5py
ipympl
ipywidgets
matplotlib-base
nltk
gensim
numba
numexpr
pandas
patsy
protobuf
pytables
scikit-learn
scikit-image
scipy
seaborn
statsmodels
xlrd
EOF

mamba install -q --file req.txt -y
mamba install -v -y -c conda-forge tensorflow-cpu==2.6.2
```

Will result in:

```
info     Problem count: 1
Encountered problems while solving:
  - package grpc-cpp-1.42.0-ha1441d3_1 requires libprotobuf >=3.19.1,<3.20.0a0, but none of the providers can be installed
```

Funny thing is, `libprotobuf` 3.19.1 _is_ installed, precisely with the version that `mamba` claims cannot be installed:

```
mamba list | grep proto
# libprotobuf               3.19.1               h780b84a_0    conda-forge
```

This appears to suggest that `libprotobuf >=3.19.1,<3.20.0a0` is not satisfied by the existing  libprotobuf 3.19.1. Huh?

**Comment by brsolomon-deloitte** [comment]
Yet again, slightly different setup, same issue (drop h5py from requirements, install tensorflow first):

```
mamba install -y -c conda-forge tensorflow-cpu
cat << EOF > req.txt
jupyterhub
nbgitpuller
pyspark
boto3
elasticsearch
altair
beautifulsoup4
bokeh
bottleneck
cloudpickle
cython
dask
ipympl
ipywidgets
matplotlib-base
nltk
gensim
numba
numexpr
pandas
patsy
protobuf
pytables
scikit-learn
scikit-image
scipy
seaborn
statsmodels
xlrd
EOF

mamba install --file req.txt -y
```

Result:

```
Encountered problems while solving:
  - package tensorflow-base-2.6.2-cpu_py39h6349a3b_2 requires libprotobuf >=3.18.1,<3.19.0a0, but none of the providers can be installed
```

Yet:

```
# mamba list | grep protobuf
libprotobuf               3.18.1               h780b84a_0    conda-forge
protobuf                  3.18.1           py39he80948d_0    conda-forge
```

**Comment by brsolomon-deloitte** [comment]
Anyone?

**Comment by wolfv** [comment]
I think you found the issue -- tensorflow-base needs protobuf 3.18 and grpc-cpp needs 3.19...
There were some migrations applied to the tensorflow feedstock that should hopefully have solved the issue: https://github.com/conda-forge/tensorflow-feedstock/pulls

**Comment by brsolomon-deloitte** [comment]
@wolfv that doesn't seem to account for the confusing error message from https://github.com/mamba-org/mamba/issues/1354#issue-1082390707, which claims that `package grpc-cpp-1.42.0-ha1441d3_1 requires libprotobuf >=3.19.1,<3.20.0a0` even though `libprotobuf               3.19.1               h780b84a_0    conda-forge` is already installed.

**Comment by wolfv** [comment]
yeah, better error messages is on our TODO list .. there are a number of other issues open regarding this. 
However, it is "correct" as in libprotobuf 3.19 can't be installed at the same time as tensorflow-cpu=2.6 (which requires 3.18)

**Comment by brsolomon-deloitte** [comment]
> However, it is "correct" as in libprotobuf 3.19 can't be installed at the same time as tensorflow-cpu=2.6 (which requires 3.18)

Okay, I understand what it is trying to say now :) Yes, agreed that a change in wording to something like "is incompatible" would have saved a lot of confusion.

**Comment by wolfv** [comment]
As mentioned before, better error messages is high on our todo list. Will tackle this, but we have a bunch of other open issues for this already.
