### ISSUE TITLE
conda bash init clobbers micromamba's init

### ISSUE THREAD

**Issue by maresb** [mamba-org/mamba#1356]
Micromamba's init adds something like this to `~/.bashrc`:

```bash
# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE="/bin/micromamba";
export MAMBA_ROOT_PREFIX="/opt/conda";
__mamba_setup="$('/bin/micromamba' shell hook --shell bash --prefix '/opt/conda' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    if [ -f "/opt/conda/etc/profile.d/mamba.sh" ]; then
        . "/opt/conda/etc/profile.d/mamba.sh"
    else
        export PATH="/opt/conda/bin:$PATH"
    fi
fi
unset __mamba_setup
# <<< mamba initialize <<<
```

If Conda's init is subsequently run, it comments out the `export PATH=…` line:

```bash
# export PATH="/opt/conda/bin:$PATH"  # commented out by conda initialize
```

Because there is no command between `else` and `fi`, this leads to a syntax error in Bash:

```
bash: /home/micromamba/.bashrc: line 128: syntax error near unexpected token `fi'
```

**Comment by maresb** [comment]
For reference, here's [the place in conda's init which comments out the export command](https://github.com/conda/conda/blob/f60f0f1643af04ed9a51da3dd4fa242de81e32f4/conda/core/initialize.py#L1296-L1309)

**Comment by wolfv** [comment]
This seems to be the place where the commenting out happens: https://github.com/conda/conda/blob/f60f0f1643af04ed9a51da3dd4fa242de81e32f4/conda/core/initialize.py#L1274-L1280

Kinda annoying that they don't stick to the confines of `>>>>> conda init <<<<....`

**Comment by maresb** [comment]
@wolfv my rough understanding is that they did it for super legacy reasons. I might be wrong, but I think there was a time when Conda didn't write the `>>> conda init` block and simply modified the `PATH` wherever it was. But since such versions are ancient by now. It's probably time for them to restrict to their init block... I'll see if I can file an issue.

By the way... on the subject of sticking to ones own init block, my `~/.bashrc` has
```
if [ -f "/micromamba_root_prefix/etc/profile.d/mamba.sh" ]; then
    . "/micromamba_root_prefix/etc/profile.d/mamba.sh"
fi
```
*within* the `conda` block (instead of the `mamba` block). :laughing: I'm not complaining though, it hasn't caused me any problems yet.
