### ISSUE TITLE
[micromamba] offline & dry-run doesn't properly work

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1368]
micromamba complains about "specified pkgs_dirs not set"

```
(ros) [w@fedora src]$ micromamba  create -n xjxjx --dry-run --offline  autoconf automake 
robostack/linux-64       Using cache
robostack/noarch         Using cache
conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
critical Specified pkgs_dir does not exist
```

**Comment by ericdill** [comment]
mambaforge fails after the installation step with this same error if i have any env vars in my pkgs_dirs in conda config:
```
pkgs_dirs
- $HOME/pkgs
```

mambaforge error
```
<snip>
Extracting mamba-0.24.0-py39hfa8f2c8_1.tar.bz2
+ PYTHON=/tmp/mambaforge-4.13.0.1/bin/python
+ MSGS=/tmp/mambaforge-4.13.0.1/.messages.txt
+ touch /tmp/mambaforge-4.13.0.1/.messages.txt
+ export FORCE
+ mkdir -p /home/eric/.conda
+ CONDA_SAFETY_CHECKS=disabled
+ CONDA_EXTRA_SAFETY_CHECKS=no
+ CONDA_CHANNELS=conda-forge
+ CONDA_PKGS_DIRS=/tmp/mambaforge-4.13.0.1/pkgs
+ /tmp/mambaforge-4.13.0.1/conda.exe install --offline --file /tmp/mambaforge-4.13.0.1/pkgs/env.txt -yp /tmp/mambaforge-4.13.0.1

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
critical libmamba Specified pkgs_dir does not exist
```

it seems that conda/mamba will respect env vars. my guess is that micromamba is not doing env var expansion properly?


full condarc:
```
envs_dirs:
  - $HOME/envs
  - /opt/envs/shared
pkgs_dirs:
  - $HOME/pkgs
channels:
  - <internal artifactory channel>
  - <other public channel>
  - <other public channel>
  - conda-forge

```

i also tried a few other things, neither of which worked:
- ❌ making `/pkgs` dir in case the variable expansion _was_ working and HOME just wasn't set in the script
- ❌ making `\$HOME/pkgs` dirs in the current path in case micromamba was just literally looking for that string
- ✅ fully qualifying the `pkgs_dirs` key to be `/home/eric/pkgs`

what do you think @wolfv ? does this make any sense to you?

**Comment by wolfv** [comment]
Ah, hmm, interesting case you found here! :) We actually have all the ingredients to expand env vars in the `.condarc` file – @jonashaag recently added that. So we could totally just expand env vars. 
I believe `~` would also work.

**Comment by jonashaag** [comment]
Don't we already do this? What version of Micromamba are you using?

**Comment by ericdill** [comment]
oh awesome thanks for the feedback. i'll try that ~. 

another slight difference i noticed between conda/mamba and micromamba. Given these two condarc's that conda config --show-sources finds:

```
# conda config --show-sources
==> /etc/conda/condarc <==
envs_dirs:
  - $HOME/envs
  - /opt/envs/shared
pkgs_dirs:
  - $HOME/pkgs
channels:
  - <internal artifactory>
  - conda-forge

==> /opt/conda/.condarc <==
channels:
  - conda-forge

==> /root/.condarc <==
envs_dirs:
  - /root/envs
  - /opt/envs/system
  - /opt/envs/shared
pkgs_dirs:
  - /root/pkgs
channels:
  - <internal artifactory>
  - conda-forge

```

conda shows this:
```
 conda config --show pkgs_dirs
pkgs_dirs:
  - /root/pkgs
```

micromamba seems to concat the values together:
```
/opt/envs/system/mambaforge-4.14.0-0-Linux-x86_64/conda.exe config list pkgs_dirs
pkgs_dirs:
  - /root/pkgs
  - $HOME/pkgs
```

**Comment by ericdill** [comment]
can confirm: ~/pkgs works where $HOME/pkgs did not. thanks so much

**Comment by jonashaag** [comment]
Aha! We do not support an undocumented feature of Conda: It will expand `$HOME` whereas the documentation says you need to use `${HOME}`. If you use `${HOME}` it should work fine.

**Comment by ericdill** [comment]
oooo my sloppy bash comes home to roost! I'm usually so paranoid about adding the braces to my bash scripts 🤕 

i can confirm that ${HOME} works

**Comment by jonashaag** [comment]
I remember we discussed adding `$foo` support but there were some challenges that I don’t remember right now so decided against it. We might want to revisit.

For the meantime do you want to contribute a small section to our Troubleshooting docs that documents this fact?

**Comment by benmoss** [comment]
I'm running into this as well. I ran the micromamba install script on a brand-new Amazon Linux machine, accepted all the defaults, and then running `micromamba create -n cool -f env.yml --offline` gives me the `critical libmamba Specified pkgs_dir does not exist` error.

Running `micromamba config list pkgs_dirs` gives me two directories, only the first of which exists:

```
pkgs_dirs:
  - /home/ssm-user/micromamba/pkgs
  - /home/ssm-user/.mamba/pkgs
```

If I `mkdir -p /home/ssm-user/.mamba/pkgs` the second the error goes away. Not clear where that directory comes from, some kind of default I guess?

**Comment by jjerphan** [comment]
We cannot reproduce this issue with 2.0, please update to 2.0.

Feel free to reopen an issue with a reproduce if you still have this issue with 2.0.

Note that 1.x is note being developed anymore, but to address security fixes.
