### ISSUE TITLE
ModuleNotFoundError: No module named 'mamba.mamba'

### ISSUE THREAD

**Issue by j4cko** [mamba-org/mamba#1374]
I tried two ways of installing mamba, downloading and installing mambaforge, and `conda install mamba -n base -c conda-forge` is indicated in the README. Unfortunately, both lead to
```
Traceback (most recent call last):
  File "/home/jakob/mambaforge/bin/mamba", line 7, in <module>
    from mamba.mamba import main
ModuleNotFoundError: No module named 'mamba.mamba'
```

I am aware that this may have to do with my system setup as I tried the same steps on a different system successfully. However, I am unable to figure out what went wrong and where things may interfere. I am using archlinux with python3.10 installed, but as far as I can see the mambaforge or conda installations are being used.

Any help is appreciated.

**Comment by wolfv** [comment]
Hmm, hard to say what went wrong here. 

Usually you'd use `mamba` from the `condabin` folder, not the `bin` folder. Not sure if that changes anything though. 

Can you post a `conda list`?

**Comment by j4cko** [comment]
sorry for the delay. The mamba executable seems correct: I get
```
which mamba                                                                                                                                                                            ─╯
/home/jakob/mambaforge/condabin/mamba
```
and attach the conda list output. It seems to be an issue on archlinux, but I am unable to figure out where the system messes up with the paths set in conda.
[condalist.txt](https://github.com/mamba-org/mamba/files/7924133/condalist.txt)

**Comment by rick-osmo** [comment]
I had the same error, immediately after running the installer.

**Comment by AaronOpfer** [comment]
One of my users just encountered this problem. It was because they had previously did `pip install --user mamba`.

`pip install --user` is a blight that should be purged with fire, in my humble opinion. Such a purge can be done via `rm -rf ~/.local/lib/python*/site-packages/`.

**Comment by JohanMabille** [comment]
mamba is not a Python package anymore in mamba 2. Closing this as outdated.
