### ISSUE TITLE
Add `micromamba run`

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#1385]
As far as I can tell there is no `run` support in Micromamba so far. I am looking for a "shortcut" to `micromamba activate myenv && stuff`, ie. `micromamba run -n myenv stuff`.

**Comment by wolfv** [comment]
yeah, I agree, that would be nice!

We have a "wrapped_subcommand" thing in the `link.cpp` that basically takes a `std::vector<std::string>` and creates a temporary script that activates a given environment and runs what's in the `std::vector<std::string>`. We could ideally re-use that function for `micromamba run ...`
