### ISSUE TITLE
Implement `micromamba lock install`

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#1389]

**Comment by wolfv** [comment]
Hey, sorry, I don't think I fully understand what this command is supposed to do :)

With the previous generation of `conda-lock` files you could just install them.

With the newer generation YML based lock files we might have to do some additional work. In fact, I'd like to make them first class citizens of micromamba: https://github.com/mamba-org/mamba/issues/1209

**Comment by jonashaag** [comment]
Uh, I got confused, installing from the `@EXPLICIT` file format already works with `micromamba create`.
