### ISSUE TITLE
Micromamba: Support environment variables in `.condarc`

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#1393]
Eg. if you have `${PASSWORD}` in your `.condarc`, works with Conda/Mamba but not Micromamba.

**Comment by wolfv** [comment]
We could pre-process the rc files and find & replace all instances of ${...} with the given env var.

**Comment by jonashaag** [comment]
We currently use `envsubst < condarc-with-vars > condarc-without-vars`

**Comment by wolfv** [comment]
makes sense. I think it wouldn't be to hard to come up with a std::regex and then match all occurences. we do have the `getenv` machinery already ...

**Comment by jonashaag** [comment]
For reference, here is the source code of `envsubst`. It's really really simple. https://github.com/autotools-mirror/gettext/blob/1f1c6330c688a00d8f1b8b41b16a11ba4037e241/gettext-runtime/src/envsubst.c#L464

**Comment by jonashaag** [comment]
I've had a look at implementing this. We could do it in a very simplistic manner by changing `YAML::Load(f)` to `YAML::Load(substitute_env_vars(read_file(f)))`. But I think we should do it a little bit more sophisticated by introducing something like `expandvars` in Conda: https://github.com/conda/conda/blob/fc56fdeb2931370845edfd14453ff738d06662dc/conda/base/context.py#L212. It was unable to identify the right place to put this logic though.

**Comment by wolfv** [comment]
@jonashaag I think if you make a C++ function that uses a regex to parse `some test ... ${MYVAR} blabla` and properly finds `${MYVAR}` and replaces it from an env var that would be a great first step. It doesn't yet have to be fully integrated as long as you can add a test e.g. from the C++ side.

**Comment by jonashaag** [comment]
I built a clone of `os.path.expandvars` (which is used by Conda). Turned out to be much more complicated than I thought, but it should be (almost) identical to Conda, whereas a regex-based solution couldn't achieve that. Will clean the code but here's a sneak peek:

```c++
std::string expandvars(std::string s)
{
    auto res = std::vector<std::string>();

    while (s.size())
    {
        const char c = s[0];
        bool is_percent = ON_WIN && c == '%';
        if (ON_WIN && c == '\'') {
            // No expansion within single quotes (Windows only)
            auto j = s.find("'", 1);
            if (j == std::string::npos) {
                res.push_back(s);
                break;
            } else {
                res.push_back(s.substr(0, j + 1));
                s = s.substr(j + 1);
            }
        } else if (c == '$' || is_percent) {
            // Variable or $$/%%
            auto has_next = s.size() > 1;
            if (has_next && (s[1] == '$' || (ON_WIN && s[1] == '%'))) {
                // $$/%%
                res.push_back(s.substr(1, 1));
                s = s.substr(2);
            } else if (has_next && (is_percent ? isalpha(s[1]) : s[1] == '{')) {
                // ${var} or %var%
                auto j = is_percent ? s.find("%", 1) : s.find("}", 2);
                if (j == std::string::npos) {
                    res.push_back(s);
                    break;
                } else {
                    auto var = s.substr(is_percent ? 1 : 2, j - (is_percent ? 1 : 2));
                    auto val = std::getenv(var.c_str());
                    if (val == NULL) {
                        res.push_back(var);
                        res.push_back(is_percent ? "%" : "}");
                    } else {
                        res.push_back(val);
                    }
                }
                s = s.substr(j + 1);
            } else {
                // s.size() >= 2
                size_t j;
                for (j = 1; j < s.size() && isalpha(s[j]); ++j);
                auto var = s.substr(1, j - 1);
                auto val = std::getenv(var.c_str());
                if (val == NULL) {
                    res.push_back(is_percent ? "%" : "$");
                    res.push_back(var);
                } else {
                    res.push_back(val);
                }
                s = s.substr(j);
            }
        } else {
            // Non-special char
            auto j = s.find_first_of(ON_WIN ? "\"'$%" : "\"$");
            if (j == std::string::npos) {
                res.push_back(s);
                break;
            } else {
                res.push_back(s.substr(0, j));
                s = s.substr(j);
            }
        }
    }

    std::string out = "";
    for (int i = 0; i < res.size(); ++i) out.append(res[i]);
    return out;
}
```

**Comment by wolfv** [comment]
Fixed in https://github.com/mamba-org/mamba/pull/1423

Thanks again!

**Comment by ulupo** [comment]
Hi @wolfv @jonashaag.  Could you provide a simple example of how a `.condarc` file with custom environment variables should be written?  What I want to be able to do is have an equivalent of this line
https://github.com/aqlaboratory/openfold/blob/3bec3e9b2d1e8bdb83887899102eff7d42dc2ba9/scripts/install_third_party_dependencies.sh#L18
in micromamba.  But I can't make it work.  Thank you in advance!
