### ISSUE TITLE
`micromamba run` missing featuress

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1396]
I think the following options will be necessary and useful: 

- [x] it may be good to support `--` as a seperator to args for the command to be run. Currently it's not possible to do `micromamba run -n jjj jupyter --help` becasue the `--help` will be interpreted by micromamba
- [x] `--cwd` argument to select current working directory 
- [x] `--no-capture-output` Don't capture stdout/stderr
- [x]  `--live-stream` Display the output for the subprocess stdout and stderr on real time

**Comment by wolfv** [comment]
I wonder if we can figure out how to "detach" a command atuomatically like sublime text does when running `subl text.txt`.
That way we could launch a run process but then put it immediately in detached mode in teh background.

**Comment by JohanMabille** [comment]
What is the difference between `--live-stream = false` and `--no-capture-output` ?

**Comment by wolfv** [comment]
I think it might be more useful to look at `docker run`: https://docs.docker.com/engine/reference/run/

They allow for selective attaching to streams.
