### ISSUE TITLE
Testing the install on test dataset fails

### ISSUE THREAD

**Issue by benhibou** [mamba-org/mamba#1400]
Hello,

I am really keen to try out your pipeline on our mouse fmri experiments. I am testing my install on Ubuntu Linux version 16.04.7 and it fails on the test data set. Command issued:

rabies -p MultiProc preprocess test_dataset/ preprocess_outputs/ --TR 1.0s --no_STC --debug

From the logs it appears the first call to ImageMath is unable to deal with a call to UnsharpMask. I am not sure if "UnsharpMask is part of ANTs or of another separate package. See log file attached.  

Thank you in advance for your help.

Benoit
[rabies_preprocess.log](https://github.com/mamba-org/mamba/files/7943255/rabies_preprocess.log)

**Comment by wolfv** [comment]
No idea what this is about. Sorry.
