### ISSUE TITLE
Kernels from envs created with mamba for use in Jupyter Hub fail to connect after server restarts

### ISSUE THREAD

**Issue by Alex-Lewandowski** [mamba-org/mamba#1403]
I am not sure if this issue belongs here or at [ipykernel](https://github.com/ipython/ipykernel). I apologize if this ball belongs in their court.

- We are using nb_conda_kernels to make kernels in multiple conda environments available for use in Jupyter Notebooks. 
- We update the jupyter_notebook_config.json to use the display names
    - `{"CondaKernelSpecManager": {"name_format": "{display_name}"}}`
- We add display names to the envs with kernda

We have been doing this with conda, and everything works. We can run notebooks using kernels from various conda envs and their short, easy to read display names show up in the kernel menus.

We tried switching to mamba and ran into trouble. If you create a new env with mamba and set its display_name, everything works until the Jupyter server is restarted, at which point the kernel cannot connect and displays "No Kernel" in the notebook.

The trouble seems to be with the version of ipykernel. In order to use kernda, it must be installed in every environment. Both conda and mamba install kernda=0.3.0 but they install different versions of ipykernel (a dependency of kernda). 

From identical yamls:
- mamba installs ipykernel=6.7.0
- conda installs ipykernel=5.5.5

If you open a notebook in the new mamba created env's kernel, it works fine. If you cat its connection file, you see something like this:
```json
{
  "shell_port": 41649,
  "iopub_port": 60299,
  "stdin_port": 58783,
  "control_port": 58641,
  "hb_port": 59663,
  "ip": "127.0.0.1",
  "key": "2875f846-602fbd69320ede84dcfd4713",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": ""
}
```

Note that the `kernel_name` is an empty string. All of the envs created with conda also end up with connection files in which `kernel_name` is an empty string.

However, if you then restart your server, the kernel can no longer connect and the connection files created do not have empty strings for the `kernel_name`. Instead they look something like this:
```json
{
  "shell_port": 35047,
  "iopub_port": 32773,
  "stdin_port": 35609,
  "control_port": 45053,
  "hb_port": 49773,
  "ip": "127.0.0.1",
  "key": "91ffeb59-dcce663b5f4738d52d99264e",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": "conda-env-.local-rtc_analysis_mamba-py"
}
```

Pinning the version of ipykernel to 5.5.5 in the enviornment yaml fixes the issue. The `kernel_name` remains an empty string after server restarts and the kernel can connect to notebooks.

**Comment by jonashaag** [comment]
Sounds like this has little to do with Mamba, given that it is fixed by pinning an older version. I am assuming that your kernda version is older using Conda because you’ve created the environment long ago? Or can you reproduce Conda and Mamba installing different versions using the same installation procedure?

**Comment by Alex-Lewandowski** [comment]
Hi @jonashaag, thanks for getting back to me so quickly!

The environment is new and we can repeat the behavior when we recreate it. Here is the yaml were are using, now with the pinned version of ipykernel in place.  https://github.com/ASFOpenSARlab/opensarlab-envs/blob/opensarlab-lib/Environment_Configs/rtc_analysis_env.yml Though, we notice the same behavior in our jupyter hub deployment with all of our yamls.

The environments we end up with have the latest version of kernda installed, regardless of whether we build them with mamba or conda:
![image](https://user-images.githubusercontent.com/37909088/151303138-40e27687-b56e-4d8e-944d-33e4fe1e421c.png)
![image](https://user-images.githubusercontent.com/37909088/151303398-6eff9ed1-f9f4-43b1-86cc-e9d4c52d7fec.png)

It's the ipykernel version that makes the difference, which is resolved differently by mamba and conda. When we build environments from the same yaml with mamba and conda, we end up with different versions of the installed packages. In this case, there seems to be a dependency conflict that conda catches and mamba doesn't. Conda installs an older version of ipykernel, which works.

**Comment by wolfv** [comment]
Sounds like a metadata problem in conda-forge. Can you inspect the metadata of the packages?
You might be able to fix this with a repodata patch https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/master/recipe

**Comment by Alex-Lewandowski** [comment]
Thanks for your help @jonashaag and @wolfv. 

I think the reason we were having this issue is that we are using the jupyter/base-notebook:hub-1.4.2 image for our Jupyter Hub. It has older versions of conda and mamba (conda=4.10.3 and mamba=0.17.0). After updating conda and mamba, it works. 

ipykernel=6.7.0 is installed. In the connection files, kernel_name remains an empty string after server restarts, and the kernels connect to notebooks.

![image](https://user-images.githubusercontent.com/37909088/151620020-6d9aa5c5-b455-4aea-90ba-00daf2877503.png)

Closing this issue.
