### ISSUE TITLE
Improve error message if conflicting packages are requested

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#1405]
```
$ mamba install 'snowflake-connector-python==2.7.2' 'snowflake-connector-python==2.7.3'

Looking for: ['snowflake-connector-python==2.7.2', 'snowflake-connector-python==2.7.3']

Pinned packages:
  - python 3.9.*


Encountered problems while solving:
  - package snowflake-connector-python-2.7.2-py38h5196458_0 requires python >=3.8,<3.9.0a0, but none of the providers can be installed
```

This error message is correct, but a more useful one would be this one that you get if you don't have `python=3.9` pinned:

```
  - cannot install both snowflake-connector-python-2.7.3-py310h1afff1e_0 and snowflake-connector-python-2.7.2-py38he943702_0
```

**Comment by wolfv** [comment]
Yeah, providing better error messages is definitly on our wish list for this year!
I recently found a function in the libsolv API to retrieve _all_ errors from the solver: https://github.com/mamba-org/mamba/blob/4cbfcf1cb403d8919b2d6c0ada39ee26a48524e2/libmamba/src/core/solver.cpp#L409-L423

This function should also return an error for "requesting conflicting specs".

**Comment by jonashaag** [comment]
Thanks for the pointer. Actually it seems that we are getting the "wrong" result from libsolv here. The `solver_problem2str` call does not get the "conflicting requests" error message. It's one of the `j`s here though: https://github.com/mamba-org/mamba/blob/4cbfcf1cb403d8919b2d6c0ada39ee26a48524e2/libmamba/src/core/solver.cpp#L362-L392

Do you think this is something that should be improved in libsolv (better select the "primary" error message)?

**Comment by wolfv** [comment]
Yeah i don't actually know how libsolv selects the error message it prints. 

What I was thinking is that we could merge many error messages and print the more unique ones more prominently.
By merging I mean -- I thought we might have a lot of:

```
Cannot install A together with B 1.1
Cannot install A together with B 1.2
Cannot install A together with B 1.3
...
```

and instead we could print `Cannot install A together with B [1.1, 1.2, 1.3]`

Another thing I thought was that when we're in interactive mode we could ask the user if she/he wants to see additional error messages via `[Y/n]` prompt.

Besides "finding" this function I haven't had a chance to play around with it much more yet. I am very curious what you find!

**Comment by jonashaag** [comment]
See https://github.com/mamba-org/mamba/pull/1424 for some work I did on this

**Comment by wolfv** [comment]
I will link this issue to #770 and close it. But we will surely be working on this in the upcoming months!
