### ISSUE TITLE
Mamba bash init clobbered by conda init

### ISSUE THREAD

**Issue by maresb** [mamba-org/mamba#1414]
The situation with conda/mamba/micromamba init scripts clobbering each other has improved with #1357 and #1355, but things are not yet working correctly...

The [current `mamba init` command](https://github.com/mamba-org/mamba/blob/32e5056cbf80aa8fae745be102044fd996152036/mamba/mamba/mamba_shell_init.py) creates a `# >>> conda initialize >>>` block for the conda init, and appends the Mamba snippet to the bottom of this block. I would have expected it to append the Mamba snippet to a subsequent separate `# >>> mamba initialize >>>` block. (Note that `micromamba shell init --shell=bash` already creates such a Mamba block.) But then when such a block is present, Micromamba is not successfully init'ed.

The good news is that it is currently possible to init all three of `conda`, `mamba`, and `micromamba` via
```bash
micromamba shell init --shell=bash
mamba init
```
and _not_ running `conda init` (which currently clobbers `mamba`).

I propose that one should be able to run the commands

```bash
micromamba shell init --shell=bash
mamba init
conda init
```

in any order to achieve a triply-activated Bash shell.

Note: #1357 is still essential since `conda init` will modify `export PATH=` statements outside of the Conda block! (TODO: file an issue in Conda since this behavior should probably be deprecated.)

**Comment by maresb** [comment]
I think a proper solution should involve planning exactly what sort of blocks should be created by `mamba` and `micromamba`, figuring out how to migrate existing blocks (at least for Mamba), and figuring out how to test. It seems to me like quite a lot to tackle, so maybe it would make sense to break this up into smaller issues?

**Comment by wolfv** [comment]
Hmm, I don't think the situation is terribly bad. If you want to have `mamba init` one should run it as replacement or after `conda init`, that's the only constraint.

Micromamba on the other hand is completely separate from this as it uses its own block.

It's slightly unfortunate that we didn't distinguish between `mamba` and `micromamba` from day one in variable names etc. and it's also still a bit fuzzy -- micromamba might well become `mamba` one day :)

**Comment by maresb** [comment]
Ya, I agree that this isn't so bad since there's now an easy workaround. I'd much rather see the linker parallelized than rewriting the entire shell init machinery. :grinning: 

Regarding the names of the blocks and the future of micromamba, I had a very similar discussion with @adriendelsalle in https://github.com/mamba-org/mamba/pull/1355#issuecomment-1003560319

I also see it as the natural progression that micromamba should hopefully eventually become mamba.

**Comment by wolfv** [comment]
I think it's actually a feature that `conda init` can override `mamba init` since those two are so closely related. One might want to switch back to `conda` and then it's a good way to clean things up.

**Comment by maresb** [comment]
Haha, I never thought of `conda init` as cleaning up like that. Makes sense.

Regarding my todo regarding conda's modifications outside of the `# >>> conda initialize >>>` block, I inquired here: https://github.com/conda/conda/issues/11030#issuecomment-1025825587

Seems like there's nothing more to do here at the moment, so closing.

**Comment by maresb** [comment]
Answer from Conda: once the old `source activate` is officially deprecated, then `conda init` should make modifications only within its own block.
