### ISSUE TITLE
Unbound variable ZSH_VERSION

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1436]
Our autocomplete bits in `micromamba.sh` use `if [[ -n "$ZSH_VERSION" ]]; then ...` to check if we're running inside ZSH or bash.

However, this fails when this script is run with `set -u` because that throws an error when `$ZSH_VERSION` is not set. 

We can use a default `${ZSH_VERSION:-}` to make sure there is no error. 

cc @jtpio thanks for finding this

**Comment by wolfv** [comment]
fixed by #1440 cc @jtpio

**Comment by jtpio** [comment]
Nice thanks @wolfv!

I'll try it out once a new micromamba release is out. Unless there is a nightly build uploaded somewhere.

**Comment by jtpio** [comment]
Looks like the `0.21.0` release fixes it: https://github.com/jtpio/replite/pull/22

Thanks @wolfv for the fix!
