### ISSUE TITLE
How to correctly make a conda package depend on `mamba` / `libmamba`?

### ISSUE THREAD

**Issue by s-m-e** [mamba-org/mamba#1454]
The documentation [specifically states](https://mamba.readthedocs.io/en/latest/installation.html):

> Installing mamba into any other environment than base can cause unexpected behavior

Assuming that I wanted to make a (conda-forge Python) package depend on `mamba` and/or `libmamba`, a user could potentially install my package and therefore `mamba`/`libmamba` into "any other environment than base". As far as I know, there is also no way to define a dependency in such a way that it is specifically installed into `base` (please correct me if I am wrong here).

What's the correct or best approach to make a package depend on `mamba`? If I can rely on `libmamba` alone, i.e. if I do not need to interact with the CLI, could this potentially solve my problem? Or has it become safe-ish to install `mamba` into other environments?

**Comment by wolfv** [comment]
If you interact only with `libmamba` you can set the `root_prefix` to whatever you want (that defines the place for the `pkgs` and `envs` folder) and everything should work fine, regardless of where `libmamba` or `libmambapy` are installed.

It's just the interaction with conda that makes us dependent on a base environment. 

Even mamba works fine if installed in anotehr environment than base, just it will implicitly use the new environment as _root_ prefix which is often not desired. 

E.g. you'll end up with something like: rootpref/envs/mambaenv/pkgs/...

Conda has the exact same problem, only that it uses the bash functions and thus ends up calling the base env conda.

**Comment by s-m-e** [comment]
Ok, this makes sense. Thanks!
