### ISSUE TITLE
[micromamba] 0.21.0 breaks `PIP_` config env variables

### ISSUE THREAD

**Issue by austin1howard** [mamba-org/mamba#1468]
In ~Mamba~ micromamba 0.21.0, environment variables starting with `PIP_` (used to configure pip for things like extra indexes, etc.) are being stripped. I think this is part of #1422, in particular this change: https://github.com/wolfv/mamba/commit/61c5de793c756271ec2daf5462b685686d6bd999#diff-ebac1cb6982f8e508ff9d8203d56f74aa3da80115d7ca84cc525a131ef23535aR61

There may be good reason to suppress some environment variables, but this line's change only applies to running pip (or in the future some other third party package manager) so I don't think it makes sense to empty the environment variables. At least, env vars which start with `PIP_` should be passed through.

**Comment by austin1howard** [comment]
I suppose this is more directly related to #1413.

**Comment by wolfv** [comment]
Hi @austin1howard thanks for letting us know. I think it totally makes sense to run the pip command with a pass-through environment so that all env variables are inherited.

**Comment by wolfv** [comment]
I've tagged this with `micromamba` because I don't think this concerns mamba. Correct?

**Comment by austin1howard** [comment]
yeah seems so, I'm able to install through mamba v0.21.

**Comment by austin1howard** [comment]
I know it's trivial but I pushed a PR to remove that line.
