### ISSUE TITLE
Make mamba smart enough to understand obsolete dependencies?

### ISSUE THREAD

**Issue by Hoeze** [mamba-org/mamba#1469]
Hi, I just wanted to upgrade from python3.6 to python3.9 but Mamba did not like to:
```
Encountered problems while solving:
  - package contextvars-2.4-py_0 requires python >=3,<3.7, but none of the providers can be installed
```

It would be nice if mamba would understand that this dependency is not needed any more when python is >= 3.7.

**Comment by wolfv** [comment]
Did you explicitly install `contextvars` in the past or is it a dependency of another package?

If you explicitly installed it, _how_ should we make mamba smart enough to understand this?

**Comment by Hoeze** [comment]
Oh I did not think about this case.
I can't remember ever installing this by hand, but it's possible of course.

But when I do not install a package by hand, Mamba can handle that case?
I don't care about explicitly installed packages, but contextvars was a dependency of e.g. Dask.
Removing it would have uninstalled a lot of other packages.

**Comment by wolfv** [comment]
right. yeah, rpm and other package managers have a way to say: "this package provides X".

So `contextvars` would provide `contextvars` 
and then `python 3.8` would also provide `contextvars`.

Then the requirement could be satisfied by either `python 3.6 + contextvars` or `python 3.8`.

However, that would mean a lot of changes throughout the entire conda ecosystem to make this functionality happen.
