### ISSUE TITLE
Add command-line option to disable progress bar only

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#1478]
Currently the `micromamba -q` and `mamba -q` flags disable progress bars plus some other output like `Looking for [list of packages]`. In CI one typically wants to disable progress bars but not the other info. Using `-q -v` works but displays more debug output than you typically want.

**Comment by wolfv** [comment]
There is a variable on the Context to do this. I thought we also have a env var, but looks like no:

https://github.com/mamba-org/mamba/blob/9379389d9732ea0002b62565e5cf8f5a934b6722/libmamba/src/core/context.cpp#L36-L39
