### ISSUE TITLE
minor suggestion: improve colors in redesign

### ISSUE THREAD

**Issue by ngam** [mamba-org/mamba#1479]
Hi, thanks for the fancy redesign and the speedier resolver!

Minor suggestion: 

The default color scheme seems to be best suited for dark theme only (it's light gray). I recommend adopting a slightly more neutral color scheme so that the experience is relatively the same for users with dark and light themes. See screenshots:

<img width="510" alt="Screen Shot 2022-02-10 at 12 58 15" src="https://user-images.githubusercontent.com/67342040/153468445-4efb2486-e904-4fb8-884f-553dfa60fbc7.png">

<img width="515" alt="Screen Shot 2022-02-10 at 13 01 36" src="https://user-images.githubusercontent.com/67342040/153468539-da7ad762-50c6-4eb9-8700-53d4f0e92351.png">

**Comment by wolfv** [comment]
Yes, agreed. I was working towards that in https://github.com/mamba-org/mamba/pull/1458

I'll have to finish this tomorrow morning and cut a release.

**Comment by ngam** [comment]
No rush, thanks a lot :)

**Comment by ngam** [comment]
Thanks @wolfv, closing this
