### ISSUE TITLE
Incorrect cache filename used

### ISSUE THREAD

**Issue by chrisburr** [mamba-org/mamba#1481]
Mamba currently hashes the full URL for the repodata cache:

https://github.com/mamba-org/mamba/blob/f76f428dc601ce4a39782d030563554e0ac74aeb/libmamba/src/api/channel_loader.cpp#L60

However conda:
* only does this for repodata's other than `repodata.json`
* ensures the URL always ends with a `/`

https://github.com/conda/conda/blob/c75b4b561676af9a3c7946664351564725c5dd2f/conda/core/subdir_data.py#L856-L866

I **think** this is the cause of the inconsistency in https://github.com/conda/constructor/pull/487. (The rest of the fixes in that PR are valid for both conda and mamba.)

**Comment by wolfv** [comment]
Thanks for digging in to this. Let's write a test and fix this in mamba so that the cache names are consistent with conda :)

**Comment by wolfv** [comment]
This should be fixed now :)
