### ISSUE TITLE
Mamba hangs for long while before loading package records

### ISSUE THREAD

**Issue by Vinno97** [mamba-org/mamba#1485]
Hi, 

When I use Mamba on a company server, I notice it hangs for a long while before it even starts looking through repos. It could be that my company blocks some outbound requests, but I see no mention of this in the logs. 

This is the relevant output of `mamba install -vvv <some random package>`, piped to a script that adds timestamps.

```
vr 11 feb 2022 14:33:56 CET DEBUG conda.core.prefix_data:_load_single_record(172): loading prefix record /home/vincent/mambaforge/envs/segmentation-pytorch/conda-meta/cudnn-7.6.5.32-h01f27c4_1.json
vr 11 feb 2022 14:33:56 CET DEBUG conda.core.prefix_data:_load_single_record(172): loading prefix record /home/vincent/mambaforge/envs/segmentation-pytorch/conda-meta/python-flatbuffers-2.0-pyhd8ed1ab_0.json
vr 11 feb 2022 14:36:17 CET info     Loading single package record: "/home/vincent/mambaforge/envs/segmentation-pytorch/conda-meta/libopus-1.3.1-h7f98852_1.json"
vr 11 feb 2022 14:36:17 CET info     Loading single package record: "/home/vincent/mambaforge/envs/segmentation-pytorch/conda-meta/xorg-inputproto-2.3.2-h7f98852_1002.json"
```

This is very consistent and happens irregardless of the environment that I'm in. Pretty sure it's no resource limitation, as the system has NVME drives and plenty of (unused) cores and RAM. This also happens in the latest version of Mamba:
```
mamba 0.21.0
conda 4.11.0
```

I can of course provide additional information if required

**Comment by wolfv** [comment]
weird. is somethings strange in one of these files?

**Comment by jonashaag** [comment]
Can you still reproduce this?

**Comment by JohanMabille** [comment]
Closing this as it has been inactive for two years.
