### ISSUE TITLE
json.exception.type_error.302 after upgrading to 0.21.1 on windows 10

### ISSUE THREAD

**Issue by rxm7706** [mamba-org/mamba#1487]
**Describe the issue**
after mamba to 0.21.1, mamba update --all failed with a json error on windows 10.
reverting to 0.21.0, fixes the issue
only mamba update --all is affected conda update --all continues to work
mamba install "mamba==0.21.0" will fail with same error

**Workaround for the issue**
revert mamba version to fix environment
conda install "mamba==0.21.0"
pin conda-meta to mamba <0.21.1
**Update for the issue**
conda clean -f -y --all 
fixed the issue, will close the issue as this was likely just cache issue

**To Reproduce**
1. Go to mambaforge prompt
2. mamba update --all on base environment
3. mamba is updated from v 0.21.0 to v 0.21.1
4. no other packages updated except mamba, libmamba and libmambapy
5. mamba update --all again
6. error report 

**Screenshots or log output**
>>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\RXM\Apps\mambaforge\lib\site-packages\conda\exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "C:\Users\RXM\Apps\mambaforge\lib\site-packages\mamba\mamba.py", line 940, in exception_converter
        raise e
      File "C:\Users\RXM\Apps\mambaforge\lib\site-packages\mamba\mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "C:\Users\RXM\Apps\mambaforge\lib\site-packages\mamba\mamba.py", line 890, in _wrapped_main
        result = do_call(args, p)
      File "C:\Users\RXM\Apps\mambaforge\lib\site-packages\mamba\mamba.py", line 758, in do_call
        exit_code = update(args, parser)
      File "C:\Users\RXM\Apps\mambaforge\lib\site-packages\mamba\mamba.py", line 648, in update
        return install(args, parser, "update")
      File "C:\Users\RXM\Apps\mambaforge\lib\site-packages\mamba\mamba.py", line 496, in install
        index = load_channels(pool, channels, repos)
      File "C:\Users\RXM\Apps\mambaforge\lib\site-packages\mamba\utils.py", line 171, in load_channels
        repo = subdir.create_repo(pool)
    RuntimeError: [json.exception.type_error.302] type must be string, but is null
`$ C:\Users\RXM\Apps\mambaforge\Scripts\mamba update --all`

**Expected behavior**
mamba update --all should work same as version 0.21.0

**Deployment information**
Describe what you've deployed and how:
 - mamba version: [0.21.1]
 - conda version : 4.11.0
 - python version : 3.8.12.final.0
 - platform : win-64
 - user-agent : conda/4.11.0 requests/2.27.1 CPython/3.8.12 Windows/10 Windows/10.0.19043
 - Installation source: [mambaforge]
 - Deployment type: [local installation]
 - Operating system: [windows 10]

**conda info**

     active environment : base
    active env location : C:\Users\RXM\Apps\mambaforge
            shell level : 1
       user config file : C:\Users\RXM\.condarc
 populated config files : C:\Users\RXM\Apps\mambaforge\.condarc
                          C:\Users\RXM\.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.8.12.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\RXM\Apps\mambaforge  (writable)
      conda av data dir : C:\Users\RXM\Apps\mambaforge\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/pytorch/win-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/pyviz/win-64
                          https://conda.anaconda.org/pyviz/noarch
                          https://conda.anaconda.org/intake/win-64
                          https://conda.anaconda.org/intake/noarch
          package cache : C:\Users\RXM\Apps\mambaforge\pkgs
                          C:\Users\RXM\.conda\pkgs
                          C:\Users\RXM\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\RXM\Apps\mambaforge\envs
                          C:\Users\RXM\.conda\envs
                          C:\Users\RXM\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.8.12 Windows/10 Windows/10.0.19043
          administrator : False
             netrc file : None
           offline mode : False

**conda list**
packages in environment at C:\Users\RXM\Apps\mambaforge:

Name                    Version                   Build  Channel
brotlipy                  0.7.0           py38h294d835_1003    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
certifi                   2021.10.8        py38haa244fe_1    conda-forge
cffi                      1.15.0           py38hd8c33c5_0    conda-forge
chardet                   4.0.0            py38haa244fe_2    conda-forge
charset-normalizer        2.0.11             pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.11.0           py38haa244fe_0    conda-forge
conda-package-handling    1.7.3            py38h31c79cd_1    conda-forge
cryptography              36.0.1           py38hb7941b4_0    conda-forge
git                       2.35.0               h57928b3_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
krb5                      1.19.2               h20d022d_3    conda-forge
libarchive                3.5.2                hb45042f_1    conda-forge
libcurl                   7.81.0               h789b8ee_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libmamba                  0.21.1               h44daa3b_0    conda-forge
libmambapy                0.21.1           py38h2bfd5b9_0    conda-forge
libsolv                   0.7.19               h7755175_5    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libxml2                   2.9.12               hf5bbc77_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
lzo                       2.10              he774522_1000    conda-forge
mamba                     0.21.1           py38hecfeebb_0    conda-forge
menuinst                  1.4.18           py38haa244fe_1    conda-forge
miniforge_console_shortcut 2.0                  h57928b3_1    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3           py38h294d835_1009    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38haa244fe_4    conda-forge
python                    3.8.12          h7840368_2_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pywin32                   303              py38h294d835_0    conda-forge
reproc                    14.2.3               h8ffe710_0    conda-forge
reproc-cpp                14.2.3               h0e60522_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
ruamel_yaml               0.15.80         py38h294d835_1006    conda-forge
setuptools                60.8.2           py38haa244fe_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.0               h8ffe710_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0            py38haa244fe_3    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yaml-cpp                  0.6.3                ha925a31_4    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.2                h6255e5f_0    conda-forge

**Comment by rxm7706** [comment]
conda clean --all -y -f seems to fix the issue
closing this issue as clearing the cache works

**Comment by sappjw** [comment]
I get the same error on Linux on mamba, libmamba, libmambapy versions > 0.21.2.  I would rather not `conda clean -f`, but I have run `conda clean -a` and the error remains.  Version 0.21.2 works.

<pre>
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/joe/.miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/home/joe/.miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 951, in exception_converter
        raise e
      File "/home/joe/.miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 945, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/joe/.miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 901, in _wrapped_main
        result = do_call(args, p)
      File "/home/joe/.miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 769, in do_call
        exit_code = update(args, parser)
      File "/home/joe/.miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 659, in update
        return install(args, parser, "update")
      File "/home/joe/.miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 481, in install
        prefix_data.load()
    RuntimeError: [json.exception.type_error.302] type must be string, but is null

`$ /home/joe/.miniconda3/bin/mamba update --all`
</pre>
