### ISSUE TITLE
error No such file or directory

### ISSUE THREAD

**Issue by Heka666** [mamba-org/mamba#1498]
conda install mamba -n base -c conda-forge
sh: /Library/Frameworks/Python.framework/Versions/3.10/bin/conda: /Library/Frameworks/Python.framework/Versions/3.10/bin/python: bad interpreter: No such file or directory

**Comment by wolfv** [comment]
Please start from miniforge or mambaforge: https://github.com/conda-forge/miniforge

**Comment by Heka666** [comment]
conda init "$(basename "${SHELL}")"
zsh: /Library/Frameworks/Python.framework/Versions/3.10/bin/conda: bad interpreter: /Library/Frameworks/Python.framework/Versions/3.10/bin/python: no such file or directory
after installing miniforge or mamba
