### ISSUE TITLE
Docs reference `mamba.mamba_api` but `libmambapy` should be used instead

### ISSUE THREAD

**Issue by costrouc** [mamba-org/mamba#1502]
Close this issue if this is incorrect but in the docs https://github.com/mamba-org/mamba/blob/129920a304084a59bdfbe026b036185a83d94e40/docs/source/python_api.rst users are told to use `from mamba import mamba_api`. For me within version `0.21.2` this import fails. Could this be related to https://github.com/mamba-org/mamba/pull/1219. I've found that using `import libmamba as mamba_api` works to the same effect.

**Comment by wolfv** [comment]
Yeah, this needs an update, and a finish! The best reference for generic usage is the boa solver: https://github.com/mamba-org/boa/blob/master/boa/core/solver.py
