### ISSUE TITLE
Micromamba: env remove

### ISSUE THREAD

**Issue by beatslikeahelix** [mamba-org/mamba#1506]
Are there any plans for Micromamba to support `micromamba env remove --name <myenv>` in the future?

Cheers for all the great work!

**Comment by astrojuanlu** [comment]
+1! At the moment the workaround is `micromamba remove -n <myenv> --all` but it doesn't really remove the environment, only clears the specs and leaves it empty

**Comment by hadim** [comment]
`micromamba env remove -n $ENV_NAME` would be very nice to have. I am currently using `mamba` just for this.

**Comment by laclouis5** [comment]
I got the same issue with micromamba: it is currently impossible to remove entirely an environment, only its packages. Would be great to have a `micromamba env remove -n <env_name>` command!
