### ISSUE TITLE
More informative error message

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/mamba#1513]
Whenever I do any operation I'm always seeing:
```
error    Failed to open .solv file
```
Unfortunately, I'm not sure what file it's referring to so it's a bit hard to do anything about this error.

This is likely due to my base install being a system install where my normal user won't have permissions, but I can't grant permissions if I don't know what file(s) are causing the problem.

**Comment by dhirschfeld** [comment]
It appears this line is the culprit:
https://github.com/mamba-org/mamba/blob/010aad71a094755bd7620537928c3659373b5f88/libmamba/src/core/repo.cpp#L390

Maybe something like below would work to give some more context:
```cpp
#ifdef _WIN32
		auto fname = m_solv_file.wstring().c_str();
        auto solv_f = _wfopen(fname, L"wb");
#else
		auto fname = m_solv_file.c_str();
        auto solv_f = fopen(fname, "wb");
#endif
        if (!solv_f)
        {
            LOG_ERROR << "Failed to open .solv file: " << fname;
            return false;
        }
```

**Comment by wolfv** [comment]
PRs welcome! :) I agree

**Comment by dhirschfeld** [comment]
> PRs welcome! :)

For sure! Just opening an issue so it won't get forgotten as I don't have time *right now*...

**Comment by wolfv** [comment]
No worries!

**Comment by JohanMabille** [comment]
This has been totally rewritten in mamba 2. and hsould have been fixed. Feel free to open a new issue if you still have the problem.
