### ISSUE TITLE
mamba segfaults when internet disconnects

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/mamba#1514]
Just opening this as a data-point. I've just experienced a couple of segfaults with `mamba` where it segfaults when my internet disconnects:

![image](https://user-images.githubusercontent.com/881019/154798758-c0bf36bc-3123-4851-b06d-13116decbfe5.png)

I'm on 0.21.1 (WSL2/Ubuntu). I haven't noticed this before but I've only started to use WSL2 in anger recently.

**Comment by dhirschfeld** [comment]
I think WSL2 is likely a red-herring and this points to some underlying issue when the internet suddenly disconnects.

I'm not worried about it as I can just redo the command so the workaround is easy.

NB: this is actually happening with `boa` when it's trying to install a package but I'm opening here as I assume the underlying issue is here.

**Comment by dhirschfeld** [comment]
I'm assuming this is related to the internet disconnecting as my internet (or VPN) is a bit flakey and after the 1st segfault I noted that my internet was out. When it happened a 2nd time I made a point to check my internet and it was out again so that points to it being the culprit. It's certainly possible that it's just a coincidence, but if it is, I've no other clue why `mamba` segfaulted twice on me tonight.

**Comment by jjerphan** [comment]
Hi @dhirschfeld, have you met the problem again recently, or has this issue been fixed?

**Comment by dhirschfeld** [comment]
I haven't seen that since. I'll go ahead and close.
