### ISSUE TITLE
OpenTelemetry Instrumentation

### ISSUE THREAD

**Issue by 3tilley** [mamba-org/mamba#1520]
I've asked this similar question of the conda team, is there any interest in instrumenting mamba with the newly stable OpenTelemetry APIs to allow people to diagnose performance and other issues?

I guess it would have to be done at the C++ layer, and unfortunately that's not my area of expertise, there is an example [here](https://opentelemetry-cpp.readthedocs.io/en/latest/api/GettingStarted.html) though.

**Comment by wolfv** [comment]
I would say the interest from my side is at low to medium. It could be interesting to have it as an optional dependency. I wouldn't really want it in the "stock" micromamba to not make the binary bigger.

I also need to look at how we can instrument some functions properly etc.

If you want to send a PR, feel free!

**Comment by 3tilley** [comment]
Thanks for getting back to me.

What does an optional dependency mean here? Is that a C++ concept? Is it possible to instrument the C++ and have a build flag to enable it?

I'm not a C++ developer unfortunately, but I could add items to the Python piece. Is that strategic or is the goal to replace that with micromamba? I'm also wondering if the relevant data is exposed to Python. For example if I wanted to see how many channels had been downloaded, what the size of each repodata package was and how long it had taken, how many solve iterations etc.
