### ISSUE TITLE
Add `--force-reinstall` to micromamba

### ISSUE THREAD

**Issue by stellarpower** [mamba-org/mamba#1524]
Hi,

I have a broken environment on one of our machines. Why? No idea, I don't even want to look into that. I think it was a bug in an old version that is now fixed.

This involved broken files and symlinks in the unpacked packages. Thus, the files in the package are in an inconsistent state. I can try to install the package over again, or create a new environment, but htis is now symlinking back to the broken packages.

As a different use-case, I have just had to downgrade a pinned pyhton version. This means now pip won't execute, as it's looking for the wrong interpreter. The right fix seems to be to re-install pip in the enviornment, but again, this isn't an option provided in the micromamba binary. Uninstalling it mneanwhile will purge everything installed, which doesn't seem a good idea. And I can pin the package to workaround, I presume, but a force-reinstall would be nice at this point.

Thus, I would like to be able to force a reinstall, all the way from downloading the package again (skip a cached version), unpack this version again over the extracted packages,m and recreatre the symlinks inside the environment. If it would be desireable to allow different stages of this to occur separately, I would think that sensible, but I believe for my situation I would need all to be able to execute all three steps in order to replace the broken packages and ensure a clean outcome for both scenarios.

I don't know what the equivalent functionality is like in the (full) mamba, as I don't have it installed, I like my nice small binary and as little python as possiuble :). If it would be simple enough and there are no issues with copying the functionality across, then ofc it makes sense not to deviate form the behaviour and switches of the full-fat implementation.

Cheers

**Comment by wolfv** [comment]
Yes, we do have a `--force-install` in mamba ... we just need to expose it to `micromamba` and propagate the flags. Not sure it skips the cache (only if one also turns on the `--extra-safety-checks` I think it will check all SHA256 sums of extracted files).

**Comment by wolfv** [comment]
Done!

**Comment by stellarpower** [comment]
Thanks! Testing it out now :)
