### ISSUE TITLE
micromamba seems to ignore default channel in environment

### ISSUE THREAD

**Issue by stellarpower** [mamba-org/mamba#1525]
When I create an environment using micromamba, I can specify a default channel with the `-c` switch. However, when I then want to install a package, it seems that this default is ignored, and I get back "nothing provides requested PACKAGE"
Therefore, I have to specify `-c` every time. I am almost always using conda-forge as the default, as I guess a number of folks are, so it'd be nice if it could pick htis up from the environment and make the command-line a bit quickler ot use.

micromamba --version: 0.21.0
Arch:                              Ubuntu AMD64

**Comment by jonashaag** [comment]
Hi @stellarpower, just to be sure, is this a bug report of something that works differently in Conda/Mamba than Micromamba, or are you suggesting to add a new "permanent" `-c` flag?

**Comment by jonashaag** [comment]
Are you aware of the fact that you can specify this in your `.condarc`?

**Comment by stellarpower** [comment]
> Hi @stellarpower, just to be sure, is this a bug report of something that works differently in Conda/Mamba than Micromamba, or are you suggesting to add a new "permanent" `-c` flag?

Afraid I don't have either of those installed, so I can't say. I am not sure what use there is to having a default channel in the environment, if it then needs to be specified for every installation operation, so it'd be useful if it acted as if `-c theDefaultChannels` had been specified implicitly, except where the user then overrides it from the arguments.

**Comment by jonashaag** [comment]
IIUC the `-c` flag is to override a the channels for a single install command.

**Comment by wolfv** [comment]
You can use `micromamba config append channels conda-forge --env` to store this info in the `$PREFIX/.condarc` file (you can also use `prepend`).

**Comment by stellarpower** [comment]
> IIUC the -c flag is to override a the channels for a single install command.

Yeah, so currently if I run any install command without `-c`, then it fails to install saying that no channel was specified. But my environment has the default channel specified from when I created it. So this makes the `-c` flag on environment creation redundant, because it's not being referred back to as a default when I install.

Thanks for the workaround also.

**Comment by wolfv** [comment]
I understand that you want that `create ... -c mychan` would "add the channel" to the new environment. As far as I am aware, neither conda or mamba have ever operated this way. Conda does define a `default` channel though (which micromamba does not).

The easiest way around this is to create a `~/.condarc` or `~/.mambarc` file and add `channels: [conda-forge]` in there.

Maybe in the future we'll do things differently and create an automatic file that registers channels for a given environment.

**Comment by marimeireles** [comment]
I think this should be added upstream at the conda-forge docs.
There we only find instructions on how to add it to conda: https://conda-forge.org/docs/user/introduction/
I'm guessing this is the page where most users go to. The instructions for conda are different: `config --add channels conda-forge`.
