### ISSUE TITLE
Use inclusive pronouns in docs

### ISSUE THREAD

**Issue by joshhjacobson** [mamba-org/mamba#1526]
Hi all, I'm just discovering mamba and I'm really excited about the great work happening here! I was reading through the configuration documentation and noticed the line "A user may have multiple rc files located at different places on _his_ machine." Surely not all users are male!

I'm not sure whether this is the only instance of a gendered pronoun in the docs, but a quick search and update to non-gendered pronouns would be helpful in making the package more inclusive :)

Cheers!

**Comment by jonashaag** [comment]
@joshhjacobson good idea, do you want to take a stab at a PR?

**Comment by joshhjacobson** [comment]
Sure!

**Comment by joshhjacobson** [comment]
This was an easy one! I ran grep searches for he/him/his/she/her in the `docs/source/` directory and the instance mentioned above was the only one that came up.

**Comment by wolfv** [comment]
Great, thanks!
