### ISSUE TITLE
Old mamba versions in vscode Python devcontainer

### ISSUE THREAD

**Issue by janhurst** [mamba-org/mamba#1528]
Hi,

I work heavily with [vscode devcontainers](https://code.visualstudio.com/docs/remote/containers) and Anaconda Python.
Naturally mamba is a great fit here to help make package management much nicer...

One of the first things I do is install mamba into an Anaconda base environment. Lately, this has become very slow and painful. I have looked for info about python versions and mamba requirements but not quite found what I (think) I'm looking for.

When I try to do an install of mamba into the [python-3-anaconda vscode devcontainer](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/python-3-anaconda), after a very long wait I am ending up with mamba 0.7.6. 

To reproduce this:
```
docker run -it mcr.microsoft.com/vscode/devcontainers/anaconda:0-3 conda install -c conda-forge mamba
```
which results in:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - mamba


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.11.0               |   py39hf3d152e_0        16.8 MB  conda-forge
    libsolv-0.7.19             |       h780b84a_5         445 KB  conda-forge
    mamba-0.7.6                |   py39heb6f48a_0         619 KB  conda-forge
    python_abi-3.9             |           2_cp39           4 KB  conda-forge
    reproc-14.2.1              |       h36c2ea0_0          28 KB  conda-forge
    reproc-cpp-14.2.1          |       h58526e2_0          20 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        17.9 MB

The following NEW packages will be INSTALLED:

  libsolv            conda-forge/linux-64::libsolv-0.7.19-h780b84a_5
  mamba              conda-forge/linux-64::mamba-0.7.6-py39heb6f48a_0
  python_abi         conda-forge/linux-64::python_abi-3.9-2_cp39
  reproc             conda-forge/linux-64::reproc-14.2.1-h36c2ea0_0
  reproc-cpp         conda-forge/linux-64::reproc-cpp-14.2.1-h58526e2_0

The following packages will be UPDATED:

  conda              pkgs/main::conda-4.10.3-py39h06a4308_0 --> conda-forge::conda-4.11.0-py39hf3d152e_0


Proceed ([y]/n)?
```

Is this image/python version fundamentally too old to work well with mamba?

Is there something I can do to improve the speed of initial installation of mamba or obtain a more up to date version of mamba?

Kind regards,
Jan

**Comment by jonashaag** [comment]
I would have assumed that you can just specify `'mamba>=0.21'` but it has been solving for over an hour for me.

**Comment by janhurst** [comment]
I did try with the miniconda distribution, and that does solve for mamba fairly quickly with a version ~0.15.

I guess there are some tough conflicts to solve for with out of the box packages in the base Anaconda install?

**Comment by jonashaag** [comment]
I guess so

**Comment by wolfv** [comment]
Yes, the Anaconda installation is extremely large and heavily pinned down, and also not exactly 100% compatible with `conda-forge`...

**Comment by wolfv** [comment]
By the way, it would be even better to use the Miniforge or Mambaforge distributions.
