### ISSUE TITLE
Could not find Windows version by calling 'ver'

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#1535]
```
warning  Could not find Windows version by calling 'ver'
    Please file a bug report.
```

Just got this in a GitHub Actions run, env info:

```
Current runner version: '2.287.1'
Microsoft Windows Server 2022
10.0.20348
```

**Comment by jonashaag** [comment]
Error code 58 seems to be network related error though? 🤔

**Comment by jonashaag** [comment]
This hasn't happened again, maybe it was due to a one-time failure of some network mount? Closing.

**Comment by wolfv** [comment]
Ah phew! Thanks for checking
