### ISSUE TITLE
[micromamba] Channels with ports seem problematic

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1536]
@mariusvniekerk reported that channels with ports in explicit requirement files do not appear to work. E.g. 

http://localhost:49153/t/1234567/get/proxy-channel/linux-64/libgcc-ng-11.2.0-h1d223b6_12.tar.bz2#d34efbb8d7d6312c816b4bb647b818b1

results in 

critical Could not set URL (code: 4 - url = http://localhost:64244*****/get/proxy-channel/osx-arm64)

@JohanMabille maybe you could have a quick look while you are on the channel side? Maybe it's just a missing `/`?

**Comment by wolfv** [comment]
To reproduce, use an environment file like 

test.txt

```
# Generated by conda-lock.
# platform: linux-64
# input_hash: fbbf5a033b935a5fcf8e2bcf3526503345daac3a95d45696e9b411d59171c01b
@EXPLICIT
http://localhost:49153/t/1234567/get/proxy-channel/linux-64/libgcc-ng-11.2.0-h1d223b6_12.tar.bz2#d34efbb8d7d6312c816b4bb647b818b1
```

and use `micromamba create -f test.txt -n testenv

**Comment by JohanMabille** [comment]
I cannot reproduce the issue locally.

**Comment by wolfv** [comment]
Hmm, same here: 

```
info     libmamba Download error (7) Couldn't connect to server [http://localhost:49153/t/*****/get/proxy-channel/linux-64/libgcc-ng-11.2.0-h1d223b6_12.tar.bz2]
```

**Comment by wolfv** [comment]
Apparently this becomes an issue when attempting to download packages. We should have another look (Marius is actually spinning up a proper `quetz` server in his tests).

**Comment by wolfv** [comment]
@mariusvniekerk I just tried to debug this, made a quetz instance with proxy channel (just like you in the tests) and tried to fetch:

```
@EXPLICIT
http://localhost:4342/t/ef82c840678d4a123c0f45f5538a2f11/get/proxy-channel/osx-arm64/xtl-0.6.23-h260d524_1.tar.bz2#44495b40ed84ff3765523a308ca25140
```

And it was working fine with `micromamba create -n ajja -f x.txt -vvv`.

Still puzzled what's going on!
