### ISSUE TITLE
Mamba thinks that requirement isn't fullfilled for installation of a package

### ISSUE THREAD

**Issue by Anirbanm0101** [mamba-org/mamba#1548]
I am trying to install a software named ISIS (https://github.com/USGS-Astrogeology/ISIS3) for the analysis of images returned by planetary mission. I am installing it on Ubuntu 20.04 (WSL). I am following the installation process mentioned in their GitHub repository (https://github.com/USGS-Astrogeology/ISIS3/blob/dev/README.md#Installation). While performing the installation of ISIS, I am encountering the following error (screenshot attached below).

![Capture8](https://user-images.githubusercontent.com/99262949/156305619-f744bb45-3988-478e-823c-5e62556f9f56.JPG)

The error message is saying that it needs protobuf 3.9.1 but I already have that in my system. Any suggestion on how to resolve this?

**Comment by Anirbanm0101** [comment]
The issue was resolved from another repository. See this:https://github.com/USGS-Astrogeology/ISIS3/issues/4820. 
As it was resolved, I am closing this issue now.

**Comment by wolfv** [comment]
great, thanks for closing!
