### ISSUE TITLE
Wrong exit code `micromamba list foo`

### ISSUE THREAD

**Issue by tdegeus** [mamba-org/mamba#1556]
It seems that `micromamba` returns an exit code `1` on 
```
micromamba list foo
```
(i.e. for an non-existing package), which is inconsistent with `conda`
Ref https://github.com/mamba-org/provision-with-micromamba/pull/41

**Comment by wolfv** [comment]
Hmm, I agree, an empty result isn't necessarily an error... We should remove the exit status!

**Comment by wolfv** [comment]
However, if no JSON is requested it would be good to print a message to the user "No package starting with 'foo' found".

**Comment by wolfv** [comment]
Weird, I am testing locally and cannot reproduce this behavior:

```
(base) ➜  cbuild git:(master) ✗ micromamba list foo
List of packages in environment: "/Users/wolfvollprecht/micromamba"

(base) ➜  cbuild git:(master) ✗ echo $?
0
(base) ➜  cbuild git:(master) ✗ conda list foo
# packages in environment at /Users/wolfvollprecht/micromamba:
#
# Name                    Version                   Build  Channel
(base) ➜  cbuild git:(master) ✗ echo $?
0
```

I also couldn't find any indication in the source code that we'd exit with 1 or so.

**Comment by tdegeus** [comment]
I could not reproduce either locally. I got in on the CI in https://github.com/mamba-org/provision-with-micromamba/pull/41

**Comment by jjerphan** [comment]
I cannot reproduce the error as of 2.0. Feel free to recreate an issue if you still have this issue.
