### ISSUE TITLE
Add the ability to create "lockfiles"

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/mamba#157]
There's a very interesting new project - [`conda-lock`](https://github.com/mariusvniekerk/conda-lock) which allows creating an explicit spec file  ([`conda list --explicit`](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#building-identical-conda-environments)) without having to first create the environment.

i.e. you can create the lockfile without having to download and install all the packages.

It would be great if `conda-lock` could optionally use `mamba` for much faster (and parallel?) solutions.

**Comment by dhirschfeld** [comment]
I'm not sure where the functionality should be implemented but I'm just opening an issue here in case `conda-lock` requires any functionality not yet implemented in `mamba`

***xref:*** https://github.com/mariusvniekerk/conda-lock/issues/20

**Comment by dhirschfeld** [comment]
It appears that `mamba` implements all the functionality (json output / dry-run) for `conda-lock` to work.

I guess this issue can be closed then modulo any thoughts on implementing the functionality natively in `mamba`

**Comment by alanhdu** [comment]
Hi! I wanted to check whether there were any plans for `mamba` to support this natively, or whether we should continue looking to `conda-lock`.

For context, at work we've been looking into creating a wrapper around `conda`/`mamba` to handle some of the intricacies of our internal workflow, and lockfiles are definitely a feature that we'd want to support. Should we primarily engage with the `conda-lock` project, or is `mamba` planning to take on some of this "environment management" work?

**Comment by wolfv** [comment]
Hi @alanhdu we currently don't have any _immediate_ plans to support the creation of lockfiles from within mamba. 
If you are interested in contributing or sponsoring this development we could accelerate it.

I think the functionality is straight forward enough to be part of core-mamba.

**Comment by alanhdu** [comment]
That makes sense! I'll check in at work about carving out some time to contribute here, although we might just opt for building on top of `conda-lock` (my Python is significantly better than my C++). I'll let you know if we have any updates here!

**Comment by wolfv** [comment]
conda-lock supports both mamba and micromamba now, so I think we can close this.
I am not super motivated to add conda-lock functionality into mamba itself right now, because I don't have a use-case myself, and conda-lock already exists and does an excellent job.
