### ISSUE TITLE
Conda doesn't install the latest release

### ISSUE THREAD

**Issue by red8888** [mamba-org/mamba#1580]
When I look at the releases your already up to: 0.22.1
https://github.com/mamba-org/mamba/blob/master/CHANGELOG.md

But when I install mamba I get an old version:
```
conda install --yes --quiet conda-build mamba -c conda-forge
mamba --version

mamba 0.15.3
conda 4.12.0
```

**Comment by PAGWatson** [comment]
I'm seeing a similar issue.

**Comment by mfansler** [comment]
Was this the first time installing `mamba`? What does `conda update -n base -c conda-forge mamba` do?

If still stuck, we'd need to see the rest of the environment to understand what might be constraining it. I.e., share `conda list -n base` or `conda env export --from-history -n base`.

**Comment by munael** [comment]
Tried:
```sh
conda update -n base -c conda-forge mamba
```
which wanted to install/update around 200 packages...

Then tried:
```sh
mamba update -n base -c conda-forge mamba
```
and it wanted to install 4 new pkgs and update 3...

Updated from 0.15.3 to 0.22.1 .

I don't know what that's about, to be honest...
