### ISSUE TITLE
[micromamba] post-link script of qt on Windows not executed?

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1584]
@marcelotrevisani reports that this line https://github.com/conda-forge/qt-feedstock/blob/d6d71b77424020e07f371d0aeb4aaf3bd455e130/recipe/bld.bat#L188 isn't executed (at least not when explicitly installing).

**Comment by marcelotrevisani** [comment]
Try the following on windows (I just tested that on windows):
```
micromamba create -p SOME_FOLDER pyqt qt python -c conda-forge -y
```
after that try to activate that env and import pyqt ``import PyQt5``
it will fail :/
If I do the same with conda or mamba that will be fine

**Comment by jonmmease** [comment]
I'm also seeing this issue.  During installation, I also see the following warning/error while linking qt.

```
...
Linking qt-5.12.9-h556501e_6
info     libmamba ****************** Backtrace Start ******************
debug    libmamba Loading configuration
trace    libmamba Compute configurable 'create_base'
trace    libmamba Compute configurable 'no_env'
trace    libmamba Compute configurable 'no_rc'
trace    libmamba Compute configurable 'rc_files'
trace    libmamba Compute configurable 'root_prefix'
trace    libmamba Get RC files configuration from locations up to HomeDir
critical libmamba Cannot determine HOME (checked USERPROFILE, HOMEDRIVE and HOMEPATH env vars)
info     libmamba ****************** Backtrace End ********************
```

I've tried explicitly setting the `USERPROFILE` environment variable, but that doesn't seem to make a difference.

**Comment by jonmmease** [comment]
I probably won't get a chance to dig into the micromamba code itself, but let me know if there's anything else that would be helpful here!

**Comment by marcelotrevisani** [comment]
Hi @wolfv , I saw that you fixed this problem. Can you generate a new version please?

**Comment by marcelotrevisani** [comment]
I just saw that you already released it. I was checking in the release part, but I saw it in the tags :) thanks!
