### ISSUE TITLE
Instantiating `libmambapy` objects blocks `KeyboardInterrupt` exceptions

### ISSUE THREAD

**Issue by jaimergp** [mamba-org/mamba#1594]
Originally raised by @jakirkham at https://github.com/conda/conda/issues/11361

---

Stdin prompts cannot be Ctrl+C'd out if a `libmambapy` object was instantiated. I can reproduce this with `Pool()`.

This affects `mamba` and, subsequently, `conda_libmamba_solver`. I guess any Python process is affected by this, with or without conda.

Reproducer:

```python
from libmambapy import Pool

if __name__ == "__main__":
    Pool()
    while True:
        answer = input("Type X to exit: ")
        if answer.lower() == "x":
            break
```

If you try to Ctrl+C out of this, you can't because `Pool()` was instantiated. You can only press `x` and Enter. However, if you comment out the `Pool()` line , it works as expected: you can Ctrl+C because an exception is raised. Note that `Pool()` was not stored in a Python reference at all; it should have been garbage collected, but somehow it still lingers around.

**Comment by jaimergp** [comment]
I was looking into this again and found something interesting.

This snippet with a matchspec blocks Ctrl+C:

```python
from libmambapy import MatchSpec

if __name__ == "__main__":
    MatchSpec("ca-certificates")
    while True:
        answer = input("Type X to exit: ")
        if answer.lower() == "x":
            break
```

However, if no args are passed to the MatchSpec, Ctrl+C does work:

```python
from libmambapy import MatchSpec

if __name__ == "__main__":
    MatchSpec()
    while True:
        answer = input("Type X to exit: ")
        if answer.lower() == "x":
            break
```

**Comment by dholth** [comment]
https://github.com/mamba-org/mamba/blob/main/libmambapy/src/main.cpp#L157 logging and signal handling in the same bool??

**Comment by jaimergp** [comment]
I've noticed that only the objects that end up instantiating a `libmambapy.Context` object affect Ctrl+C. I wonder if this is due to this line:

https://github.com/mamba-org/mamba/blob/f2edeff4056ce81da409455c8b3a66f8c6ab3725/libmamba/src/core/context.cpp#L101

Which does this:

https://github.com/mamba-org/mamba/blob/f2edeff4056ce81da409455c8b3a66f8c6ab3725/libmamba/src/core/thread_utils.cpp#L62-L69

I'd rather not introduce threading complexity if possible.

**Comment by jaimergp** [comment]
Interesting finding. If you make sure the first time you instantiate `libmambapy.Context` happens in a thread, then things sort of work (although it takes a few Ctrl+C to eventually regain control):

For example, at the beginning of `init_api_context()` we can do this:

```python
    import threading

    t = threading.Thread(target=api.Context)
    t.start()
    while t.is_alive(): #  wait for the thread to exit
        t.join(.1)
    
    api_ctx = api.Context()
```

**Comment by jaimergp** [comment]
For the example in the first post, this fixes Ctrl+C handling:

```python
import libmambapy as lmp
import threading


if __name__ == "__main__":
    t = threading.Thread(target=lmp.Context)
    t.daemon = True
    t.start()
    while t.is_alive(): #  wait for the thread to exit
        t.join(.1)
    lmp.Pool()
    while True:
        answer = input("Type X to exit: ")
        if answer.lower() == "x":
            break
```

... how hacky is this? 😂

**Comment by dholth** [comment]
Suppose we had a flag to initialize logging (seems useful) without signal handling (seems disruptive)

**Comment by jonashaag** [comment]
Could this be solved by regularly calling https://docs.python.org/3/c-api/exceptions.html#c.PyErr_CheckSignals?

**Comment by jaimergp** [comment]
AFAICT, `PyErr_CheckSignals` is needed when there's a long running C-extension function in the main thread (so maybe it'd be useful while the solver is running, or when download/extracts are happening), but this happens as soon as the `libmambapy.Context` is initialized, with no long-running functions being called. It feels more like the signal handling logic is hijacked by that C function `default_signal_handler` I mentioned above.

**Comment by jonashaag** [comment]
Yes you are right. We should probably be propagating some signals back to Python, or not capture them in the first place.

**Comment by dholth** [comment]
https://docs.python.org/3/c-api/exceptions.html#c.PyErr_SetInterruptEx

**Comment by dholth** [comment]
It occurs to me that it might be better to just expose `set_sig_interrupted()` to the Python binding and allow libmamba to skip its own signal handling. Then a Python signal handler sets interrupted, libmamba checks it, halts, and all is well. 

Would this interact properly with the two places libmamba sets signal handlers? Or, would all of libmamba need to have its own thread for purposes of the signal handler settings?

**Comment by jakirkham** [comment]
Thanks all! 🙏
