### ISSUE TITLE
`Could not write out repodata file`, lockfile leak

### ISSUE THREAD

**Issue by ryan-williams** [mamba-org/mamba#1599]
I saw a few confusing error messages/behaviors that I wanted to ask about or at least document.

Some of this may have been fixed already; I realized after writing this all up that I was using Mamba 0.15.3, and updating to 0.22.1 seems to avoid the initial problem.

However, [this "misleading" error message is still present in HEAD](https://github.com/mamba-org/mamba/blob/8b2ed6d7af2dda5936b20a08ec8d58c896e7c8cf/libmamba/src/core/subdirdata.cpp#L585-L591), and I'm not sure if the lockfile leak is fixed (or can no longer occur due to other fixes).

In any case, leaving these breadcrumbs because it took ma a little while to track down what might be happening.

## 1. Misleading error message: `No such file or directory` (source tempfile missing), but destination path is printed

During a Docker image build, I have this step
```bash
mamba install --yes -c rapidsai -c nvidia -c conda-forge python=3.7 'rapids=21.10[build=cuda11.4_py37*]' cudatoolkit=11.4
```
It fails with:
```
Looking for: ['python=3.7', 'rapids=21.10[build=cuda11.4_py37*]', 'cudatoolkit=11.4']

nvidia/noarch            [====================] (00m:00s) Done
rapidsai/linux-64        [====================] (00m:00s) Done
pkgs/r/noarch            [====================] (00m:00s) Done
pkgs/main/noarch         [====================] (00m:00s) Done
pkgs/r/linux-64          [====================] (00m:00s) Done
pkgs/main/linux-64       [====================] (00m:00s) Done
conda-forge/noarch       [====================] (00m:01s) Done
rapidsai/noarch          [>                   ] (00m:02s) Finalizing...
nvidia/linux-64          [>                   ] (00m:02s) Failed (500), retry in 2s
conda-forge/linux-64     [             <=>    ] (00m:02s) 7 MB / ?? (3.11 MB/s)
ERROR   Could not write out repodata file '/opt/conda/pkgs/cache/04fd60c1.json': No such file or directory
```

I see versions of `Failed…` then `Done` or `Finalizing…` on several of the progress-bar lines there, but `rapidsai/linux-64` and `nvidia/noarch` seem to end on `Failed`/`Finalizing`.

I'm not sure what's causing that failure, but the error message ([subdirdata.cpp](https://github.com/mamba-org/mamba/blob/93a3f8edaeb0851d242edd8cc250626d07433db2/libmamba/src/core/subdirdata.cpp#L585-L591)) implies an issue with the "dst" of a copy, when in reality it's the "src" (a tempfile… somewhere) that's apparently missing.

I spent some time trying to figure out how I could be getting `No such file or directory` about that `/opt/conda/pkgs/cache/04fd60c1.json` path: I'm running as root, the directory exists, and the path/message are not very informative about where the problem actually is (some tempfile path that's not printed, and which in any case is missing as a symptom of a failed download? More info about that would in the error message be helpful).

<details><summary><code>conda info</code></summary>

```
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files :
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.7.9.final.0
       virtual packages : __linux=4.14.268=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.7.9 Linux/4.14.268-205.500.amzn2.x86_64 ubuntu/20.04.2 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False

```
</details>

<details><summary><code>mamba info</code></summary>

```

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.3) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files :
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.7.9.final.0
       virtual packages : __linux=4.14.268=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.7.9 Linux/4.14.268-205.500.amzn2.x86_64 ubuntu/20.04.2 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False

```
</details>

## 2. Leaked `cache.pidXX.conda_lock` file
After the above failure, there is a lockfile left laying around that causes a retry of the `mamba install …` command to hang and ultimately timeout.

In my case, it's at a path like `/opt/conda/pkgs/cache.pid1464.conda_lock`. It should be cleaned up when the previous command fails, right?

## 3. Retrying enough times eventually succeeds
After I remove the lockfile (`rm -f /opt/conda/pkgs/cache.*`), I can re-run the `mamba install` command from above, and it usually gets a little further into fetching the repodata(?) from the various channels, eventually succeeding.

[Here's a recording of it failing 5 times, sleeping for 1s in between each, before succeeding on the 6th](https://share.getcloudapp.com/nOuRDnke).

That recording uses a Docker image with this script as entrypoint:
```bash
while [ 1 ]; do
    if ! mamba install --yes -c rapidsai -c nvidia -c conda-forge python=3.7 'rapids=21.10[build=cuda11.4_py37*]' cudatoolkit=11.4; then
        rm -f /opt/conda/pkgs/cache.*
        echo "Sleeping 1s and trying again"
        sleep 1
    else
        break
    fi
done
```

I can try to build a minimal Docker image that reproduces this (right now my repro is a big image that also includes proprietary things), but hopefully some of the observed behaviors above will be enough to identify races / bugs.

## 4. No google hits for this repo's issues?
Separately, and hopefully just a transient issue, but Google seemingly hasn't indexed this repo's issues, which made it hard for me to find related issues here (especially #1128).

Searching `mamba "Could not write out repodata file" site:github.com` turned up nothing for me!

![Google SERP screenshot showing 2 results from Github Actions in unrelated repos](https://user-images.githubusercontent.com/465045/160433478-f105e275-0805-422f-a193-b12dcb98bd06.png)

**Comment by ryan-williams** [comment]
(I'm going to just preemptively close this, feel free to reopen if something seems actionable / worth fixing 😉)

**Comment by wolfv** [comment]
@ryan-williams if you have an improvement for the error message, a PR would be highly appreciated!
