### ISSUE TITLE
mamba installs PyTorch CPU version instead of the CUDA version

### ISSUE THREAD

**Issue by pjb7687** [mamba-org/mamba#1617]
The latest mamba still tries to install Pytorch "CPU".

This is a duplicate of #1349, but not a duplicate of #336.

I open the issue again since the latest Mamba (0.22.1) still has the problem.

Also a copy of comment by @bryant1410:
```
@wolfv it's not a duplicate because https://github.com/mamba-org/mamba/issues/336 is about installing the cpuonly version, while here I want to do the opposite.

I still see this issue is happening for PyTorch 1.10.2.
```

**Comment by pjb7687** [comment]
To reproduce:

```
mamba install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
```

**Comment by alienzj** [comment]
Try:
```{bash}
mamba install "pytorch=*=*cuda*"
```

**Comment by alienzj** [comment]
![image](https://user-images.githubusercontent.com/8847420/163546764-a22427dd-b002-4431-b292-6bad6962a041.png)

**Comment by shenoynikhil** [comment]
This `"pytorch=*=*cuda*" installs` pytorch 1.11, but I want pytorch 2.0.0. What could I do differently?

**Comment by bryant1410** [comment]
If you just want the latest when doing `pytorch=*=*cuda*`, maybe you miss adding the channel `nvidia`?

**Comment by shenoynikhil** [comment]
That resolved it. Thanks!

**Comment by jjerphan** [comment]
[PyTorch provides installation instructions for various configurations](https://pytorch.org/). 

We recommend following those to install PyTorch for your needs.
