### ISSUE TITLE
Could not convert: --verbose = true

### ISSUE THREAD

**Issue by l2dy** [mamba-org/mamba#1619]
`micromamba` does not recognize the `-v` flag.

```console
$ micromamba -v serach r
Could not convert: --verbose = true
Run with --help for more information.
```

**Comment by wolfv** [comment]
Hmm, this may be true but only for the search command. Other commands should accept verbose just fine (also with more than one -vvv)

**Comment by l2dy** [comment]
```
Global options:
  -v,--verbose                Set verbosity (higher verbosity with multiple -v, e.g. -vvv)
```

`-v` is a global option, and so is supposed to be supported in any subcommand.
