### ISSUE TITLE
Configurable user agent for libcurl calls

### ISSUE THREAD

**Issue by jaimergp** [mamba-org/mamba#1624]
Currently, `libmamba` [hardcodes](https://github.com/mamba-org/mamba/blob/9a5a63b96e3cf13d00dd7dbbf9c33eb476db2b4c/libmamba/src/core/fetch.cpp#L333-L334) its own user agent for the libcurl requests. It would be nice if downstream projects using libmamba(py) as a library could configure this parameter via the Context object.

Due to this, right now, `conda` using `solver=libmamba` will produce a mix of user agents:

* Repodatas are downloaded with libmamba, so the server sees `mamba/X.Y.Z ...` for these requests
* Tarballs are downloaded with conda/requests, so the server sees `conda/X.Y.Z ...` for these requests

Thanks!

**Comment by jezdez** [comment]
https://github.com/conda/conda/issues/11413 is the related bug in the conda repo (which we currently also use for conda-libmamba-solver for management issues only)

**Comment by wolfv** [comment]
Is it enough to be able to configure the beginning of the `User-agent`?

E.g. the `mamba/2.1.2` part?

Then I'd just keep concatenating the `curl_version` information whcih can be quite useful to know the version of libcurl, openssl, etc.

**Comment by wolfv** [comment]
Check out #1625
