### ISSUE TITLE
Feature Request: Support `allow_non_channel_urls` in `.condarc`

### ISSUE THREAD

**Issue by dillon-cullinan** [mamba-org/mamba#1631]
Source: https://docs.conda.io/projects/conda/en/latest/configuration.html

```
# # allow_non_channel_urls (bool)
# #   Warn, but do not fail, when conda detects a channel url is not a valid
# #   channel.
# # 
```

The main use case for this is to allow private channels in addition to "fallback" channels in case of connection failure. For example, I would like to use a pull through cache on a private server if its available, but be able to fallback to publicly available channels if connection cannot be established.

```
channels:
  - https:/mycache.com/conda/conda-forge
  - conda-forge
allow_non_channel_urls: true
```

**Comment by wolfv** [comment]
did you actually try this? I am strongly suspecting it just works

**Comment by dillon-cullinan** [comment]
I did try this and it did not work. Dug a little deeper just to see whats happening. In conda's source code it looks like this option is only applying to `403` and `404` status codes:

Ref: https://github.com/conda/conda/blob/2e081b5ab648d415a59dea458a3d695ecc9ec837/conda/core/subdir_data.py#L731

In our use case the error code is a 401, so I guess the functionality doesn't apply to us. I incorrectly assumed that this would apply to any 4xx error.

**Comment by wolfv** [comment]
Thanks for checking!
