### ISSUE TITLE
[micromamba] activate gives an error in powershell with strict-mode

### ISSUE THREAD

**Issue by m-kessler** [mamba-org/mamba#1632]
The powershell scripts I use in CI builds have usually the following options activated, to ensure that the build stops when something unexpected happens:

```
set-strictmode -version 3.0
$ErrorActionPreference='Stop'
```

Unfortunately micromamba fails to activate environments in this scenario:

```
>>> micromamba activate foo  # assuming foo exits
The variable '$Name' cannot be retrieved because it has not been set.
At line:87 char:70
+ ... -Verbose "[micromamba shell activate --shell powershell $Name]`n$acti ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidOperation: (Name:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : VariableIsUndefined
```

Tested with: 
- pwsh 7.2.2 and powershell 5.1 on Windows 10
- micromamba 0.22.0

The current version of mamba (0.22.1) does not have this problem.

**Comment by wolfv** [comment]
@m-kessler maybe you have an idea on how to fix that here? 

https://github.com/mamba-org/mamba/blob/3ed7c18a6ec09739e46cff557c2c3e52fc7dc8ff/libmamba/data/Mamba.psm1#L79-L86

**Comment by wolfv** [comment]
I guess we just have to change `$Name` to `$Args` ... PR would be very welcome :)
