### ISSUE TITLE
Make GitHub release

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#1642]
@wolfv GH shows 0.21 as the latest release, is that on purpose? I think you need to make a release on GH in addition to the tag.
<img width="166" alt="Screenshot 2022-04-22 at 09 43 42" src="https://user-images.githubusercontent.com/175722/164636884-a4990bf6-9931-49ba-bb71-0c5224e1d33e.png">

**Comment by pavelzw** [comment]
@wolfv same thing for v0.25.1
