### ISSUE TITLE
Binary size / compiling with `-O0`

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#1644]
I was wondering why the macOS binary size of micromamba is so large.

When I compile with the default settings I get a binary size of 25 MiB, same size that you get from micro.mamba.pm.

When compiling with `-Os` I get 3.7 MiB (3.9 with `-O2` and 4.0 with `-O3`). When compiling with `-O0` explicitly I get 25 MiB. So it seems like the release build of micromamba is compiled with `-O0` (= the default settings).

Shall we use `-O2` as default optimization level?

**Comment by jonashaag** [comment]
We also might want to use `-flto` on release builds for additional size reductions.

**Comment by jonashaag** [comment]
Smallest I could get is `-Oz` (Clang) and `strip` with 2.0 MiB.

**Comment by wolfv** [comment]
@jonashaag is this on macOS? And you are linking statically?

**Comment by jonashaag** [comment]
Yes and yes. With dynamic build I'm getting 27 MiB with default options, 4.2 MiB with `-Oz` and 3.4 MiB with `-Oz` + `strip`.

**Comment by jonashaag** [comment]
Turns out I was comparing apples and oranges.

The release build is fully static and is 10 MiB in size. With `-Oz -ffunction-sections -Wl,-dead_strip -Wl,-dead_strip_dylibs` I can get it down to 9.2 MiB.

I'm closing this.

**Comment by wolfv** [comment]
Btw I tried to trim down some dependencies in the "boa-forge" build of micromamba but unfortunately the produced executable is still between 8-14 megabyte: https://github.com/mamba-org/boa-forge/releases/tag/micromamba-0.23.0

**Comment by jonashaag** [comment]
Interesting, it's a bit smaller still, what did you use to trim down the size?

**Comment by wolfv** [comment]
Remove some compression libraries from libarchive and some optional stuff from libcurl (like Kerberos authentication).

**Comment by jonashaag** [comment]
Nice, maybe you can try out the (Clang specific) compile options I've given above for some extra reduction.
