### ISSUE TITLE
Option not to refresh DB cache

### ISSUE THREAD

**Issue by adrinjalali** [mamba-org/mamba#1646]
Almost every time I run `mamb`, the majority of the time is taken by it downloading the package DB, which is not small.

For `conda`, it might make sense for it to always download the DB if there are corporate customers involved and it's a requirement in that space. But for `mamba`, one could think of relaxing that requirement.

Like most package managers in the GNU/Linux world, it would be nice to have an option to update the package DB and one to upgrade/install packages. Something along the lines of `apt update` and `apt upgrade`, or `pacman -S` and `pacman -Sy`.

In most cases when I use `mamba` as a user, I don't need it to upgrade the DB cache. I think it makes sense for the users to be able to decide if they want updated package DB or not.

**Comment by jonashaag** [comment]
Doesn't the `local_repodata_ttl` do what you want? https://docs.conda.io/projects/conda/en/latest/configuration.html

**Comment by adrinjalali** [comment]
That's something, but not really equivalent to the feature I'm requesting.

Working with the ttl it means the user needs to go increase it to infinity whenever they don't want it refreshed, and then reduce it to a low number whenever they want a refresh. It does give the user the workaround, but it's a very odd workaround.

Having a constant ttl value doesn't really fix the issue, since the user doesn't know when it's gonna time out. It can be when the user has access to a very fast internet connection, or when they're on their cellphone data.

**Comment by chrisburr** [comment]
I don't think it's working but I think this is what the `--use-index-cache` flag is supposed to do?

**Comment by adrinjalali** [comment]
So I guess fixing https://github.com/mamba-org/mamba/issues/74 would kinda fix this? Then the user (or I) could have an alias to have it always enabled :)

**Comment by kongdd** [comment]
I have the same issue as @adrinjalali .

**Comment by mparry** [comment]
`--offline` already seems to achieve this, though I think that might be a bug. As it stands, `--offline` will prevent repo metadata updates but will still allow packages to be downloaded if required. The description of the option is

> Offline mode. Don't connect to the Internet.

so it does sound like package download shouldn't happen either. But I find it useful as it stands, so I'm not complaining!

**Comment by jonashaag** [comment]
Yes, apart from the one edge case with missing cache (I think the Mamba impl is better than the Conda one)
