### ISSUE TITLE
Feature request: `--mkdir` command-line option like conda

### ISSUE THREAD

**Issue by jpfeuffer** [mamba-org/mamba#1654]
Hi!

What is your policy for additional command-line options for (in this case) `micromamba create`?
I am using a tool that assumes this option under the hood and therefore I cannot use micromamba as a replacement.

Mamba does not work because of lockfile issues: #1429

**Comment by jpfeuffer** [comment]
Yes, I am not 100% sure myself but the docs say:
`-m, --mkdir           Create the environment directory if necessary.`

**Comment by wolfv** [comment]
If you run micromamba create without any specs it should just do that

**Comment by jpfeuffer** [comment]
I was about to ask that. Would you consider ignoring that option if it is specified or would you say this should be fixed in upstream consumers?

**Comment by wolfv** [comment]
If we can figure out how to add it as a hidden flag I would be fine with it. But in general, the micromamba CLI isn't 100% compatible with conda/mamba and I'm not particularly inclined to make it 100% compatible because there are some nonsensical options.
