### ISSUE TITLE
Environment variables manipulation issue under PowerShell

### ISSUE THREAD

**Issue by chawyehsu** [mamba-org/mamba#1667]
This issue was reported to conda at https://github.com/conda/conda/issues/10436, and fixed by https://github.com/conda/conda/pull/11044.

Mamba has the same issue according to: 

https://github.com/mamba-org/mamba/blob/5a61ae20ba239697fc5bad362cffe1e3ca1a66e6/libmamba/src/core/activation.cpp#L958=

![image](https://user-images.githubusercontent.com/5764917/167882350-75935ca5-ad31-4043-a9fb-bd420e370ce7.png)

**Comment by wolfv** [comment]
If you want to send the same PR to mamba, that would be highly appreciated! :)

**Comment by jonashaag** [comment]
https://github.com/mamba-org/mamba/pull/1668

**Comment by wolfv** [comment]
Thx for the fix!
