### ISSUE TITLE
Dependency resolution dependent on argument order

### ISSUE THREAD

**Issue by djhoese** [mamba-org/mamba#1672]
See https://github.com/conda-forge/botocore-feedstock/issues/1031 for the history of this issue. The summary is that installing python and s3fs from conda-forge ends up installing a very old version of botocore but only if s3fs is listed after python.

```
$ mamba create -n foo --dry-run -c conda-forge -c nodefaults s3fs python
# newer botocore

$ mamba create -n foo --dry-run -c conda-forge -c nodefaults python s3fs
# older botocore = 1.10.58
```

The other differences seem to be the version of python based on SSL build:

Good environment:

```
  + botocore              1.24.21  pyhd8ed1ab_1        conda-forge/noarch
  + s3fs                 2022.3.0  pyhd8ed1ab_0        conda-forge/noarch
  + python                 3.10.4  h9a8a25e_0_cpython  conda-forge/linux-64
```

Bad environment:

```
  + botocore              1.10.58  py_0                conda-forge/noarch       Cached
  + openssl                 3.0.3  h166bdaf_0          conda-forge/linux-64     Cached
  + python                 3.10.4  h2660328_0_cpython  conda-forge/linux-64     Cached
  + s3fs                 2021.7.0  pyhd8ed1ab_0        conda-forge/noarch       Cached
```

**Comment by jonashaag** [comment]
Same as https://github.com/mamba-org/mamba/issues/1581?

**Comment by djhoese** [comment]
Yep. Duplicate. Thanks. The whole problem started specifically with botocore that I didn't think to look for issues related to the actual problem.
