### ISSUE TITLE
mamba freezes when specifying version like "python>=3.9"

### ISSUE THREAD

**Issue by tothedistance** [mamba-org/mamba#1673]
`mamba create -n yolov5 python` works just fine and get python 3.10
`mamba create -n yolov5 "python>=3.9"` freezes.
if you specify the version in file then it will work.

I am using miniconda on windows 10, and installed mamba on base.
miniconda powershell prompt freeze, but miniconda cmd works.

**Comment by jonashaag** [comment]
What version of Miniconda are you using? Can you try some older/newer versions?

**Comment by tothedistance** [comment]
it seems the problem actually boils down to `mamba install "python>=3.9"`. I tried mamba 2.23, 2.22, 2.21 and none worked. I am not sure if this is a powershell problem or mamba problem.

**Comment by jonashaag** [comment]
If you create a file `t.py` as follows

```py
import sys
print(sys.argv)
```

and run `python t.py "python>=3.9"` in your shell, what does it print?

**Comment by jonashaag** [comment]
Could you try Micromamba as well?

**Comment by tothedistance** [comment]
looks normal.

> ['t.py', 'python>=3.9']

**Comment by tothedistance** [comment]
there is a linux url _https://micromamba.snakepit.net/api/micromamba/linux-64/latest_. should i change it to _**win-64**_

**Comment by jonashaag** [comment]
yep

**Comment by tothedistance** [comment]
__
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

warning  libmamba 'root_prefix' set with default value: C:\Users\admin\micromamba
warning  libmamba No 'channels' specified
Encountered problems while solving:
  - nothing provides requested python >=3.9

The environment can't be solved, aborting the operation
error    libmamba Could not solve for environment specs
critical libmamba UnsatisfiableError

**Comment by jonashaag** [comment]
Add `-c conda-forge`

**Comment by jonashaag** [comment]
Ok, sounds like an actual problem with Mamba then, thanks for debugging

**Comment by jonashaag** [comment]
I think this should be fixed with the next release
