### ISSUE TITLE
Micromamba download link is corrupted

### ISSUE THREAD

**Issue by erwanp** [mamba-org/mamba#1675]
We're using Micromamba in the CI of https://github.com/radis/radis  , it helped us cut down a few minutes in the test compared to Conda. Thank you ! 

However, recent downloads are corrupted
```
wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
```
Returns : 
```
bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)
It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.
You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.
```

Where:  
- local Ubuntu
- [Travis-CI](https://app.travis-ci.com/github/radis/radis/jobs/570258203)

**Comment by dhirschfeld** [comment]
Sounds like the issue reported in gitter:
https://gitter.im/conda-forge/conda-forge.github.io?at=62812381d4ef6e15af494848

**Comment by Python-37** [comment]
You can just use `http` instead of `https`.

**Comment by wolfv** [comment]
We're on it, should be resolved within 2 hours. Sorry. Will make sure this doesn't happen again.

**Comment by wolfv** [comment]
Sorry again for the inconvenience. We've setup alarms now to notify us of any SSL certificate expirations.

**Comment by erwanp** [comment]
Thank you for your reactivity @wolfv  !

**Comment by ndevenish** [comment]
Even the big people get hit by a certificate expiry occasionally :)
