### ISSUE TITLE
Linked `libstdc++.so.6` library not found after updating to mamba 0.23.3

### ISSUE THREAD

**Issue by zaneselvans** [mamba-org/mamba#1693]
I'm on Ubuntu 22.04, with `mamba` 0.23.1 installed via the `mambaforge` installer.  I ran `mamba update mamba` and it found mamba version 0.23.3 available and updated.

Subsequent calls to `mamba` result in a missing library error:

```
$ mamba env list
Traceback (most recent call last):
  File "/home/zane/mambaforge/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/zane/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/home/zane/mambaforge/lib/python3.9/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/home/zane/mambaforge/lib/python3.9/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: /home/zane/mambaforge/lib/python3.9/site-packages/libmambapy/../../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/zane/mambaforge/lib/python3.9/site-packages/libmambapy/../../../libmamba.so.2)
zsh: exit 1
```

**Comment by wolfv** [comment]
ouch. any chance you can provide me with a `conda list`?

I have just tried to recreate the problem, but didn't hit it with a fresh mamba installation.
It pulls in libstdcxx-ng 12.1.

EDIT: Ok, mamba only requires 10.X, but we actually need 12.X... will send a repodata patch

**Comment by achimgaedke** [comment]
adding the `libstdcxx-ng>=12.1` explicitly makes the installation succeede.

Are you going to trigger a new build of the conda package with the correct dependency?

**Comment by achimgaedke** [comment]
All good, I believe this can be closed - maybe in favour of a mamba-feedstock issue?

**Comment by zaneselvans** [comment]
Thanks y'all!

**Comment by ryan-williams** [comment]
Strangely, I was seeing this issue in a docker image build where Mamba 0.22.1 was installing `pyarrow`:

```bash
conda install -c conda-forge -y mamba==0.22.1
mamba install -c conda-forge -y pyarrow==8.0.0  # also observed the problem with pyarrow==5.0.0
python -c 'import pyarrow'  # ❌
# Traceback (most recent call last):
#   File "<string>", line 1, in <module>
#   File "/opt/conda/lib/python3.7/site-packages/pyarrow/__init__.py", line 65, in <module>
#     import pyarrow.lib as _lib
# ImportError: /opt/conda/lib/python3.7/site-packages/pyarrow/../../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /opt/conda/lib/python3.7/site-packages/pyarrow/../../../libarrow.so.800)
```

Upgrading to `mamba==0.23.3` fixed the issue!

```bash
conda install -c conda-forge -y mamba==0.23.3
mamba install -c conda-forge -y pyarrow==8.0.0
python -c 'import pyarrow'  # ✅ works!
```

(the above blocks are run in containers spawned from the same Docker image, which I may be able to minify+clean if it would be useful, but it's large+proprietary at the moment)

After a bunch of searching, thinking I was seeing a `pyarrow` issue, I was relieved to find the error and corroboration here, but it's amusing that @zaneselvans saw the issue when they upgraded to 0.23.3, whereas in my case that seems to be the workaround! In any case, glad to see it's basically under control and seems easy to work around, thanks.

**Comment by gabm** [comment]
The same bug happened on linux-aarch64. A PR for a fix has been submitted: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/268

**Comment by shaoqx** [comment]
Is `conda install -c conda-forge mamba` no longer the right way to use mamba? 
I installed it this way, and got 

```
conda-libmamba-solver      24.9.0           pyhd8ed1ab_0     conda-forge
libmamba                   1.5.11           hf72d635_0       conda-forge
libmambapy                 1.5.11           py39h7a57059_0   conda-forge
mamba                      1.5.11           py39hc5d2bb1_0   conda-forge
```
But when I use `mamba update ...` it deleted the symlink of libstdc++.so.6 in my environment. And mamba will not work again.
