### ISSUE TITLE
Allow spdlog to be used with external fmt lib

### ISSUE THREAD

**Issue by gdolle** [mamba-org/mamba#1694]
Hi all,

The current source code include some fmt headers bundled in spdlog, e.g
https://github.com/mamba-org/mamba/blob/master/libmamba/src/core/progress_bar_impl.cpp#L5

However, spdlog may be configured to use fmt as an external library;  SPDLOG_FMT_EXTERNAL is uncommented in `spdlog/tweakme.h`.
In that case, the fmt lib should be linked with micromamba target, and `<spdlog/bundled/fmt/*>` should be conditionnaly replaced with `<fmt/*>` whether SPDLOG_FMT_EXTERNAL is defined.

You may refer to this patch:
https://aur.archlinux.org/cgit/aur.git/tree/mamba-2022.05.20.patch?h=micromamba

**Comment by wolfv** [comment]
Hi @gdolle would you be willing to send a PR with these changes? Happy to merge them!

**Comment by gdolle** [comment]
@wolfv ok ! I created a PR. It should be a bit better than the path I suggested initally.  Feel free to modify.
