### ISSUE TITLE
numpy eigh gives incorrect result in mamba installation

### ISSUE THREAD

**Issue by rdilip** [mamba-org/mamba#1705]
In my installation of mamba's numpy (M1 chip), I noticed that the `np.eigh` function doesn't work as expected. In particular, the following code returns an error.

```python
A = np.array([[3., -1.j], [1.j, 3]])
assert np.allclose(A - A.T.conj(), 0.0)
w, z = np.linalg.eigh(A)
assert np.allclose(A @ z[:, 1], w[1] * z[:, 1])
```
`np.eigh` doesn't return an eigenvector of the input matrix. This isn't an issue for `np.eig` as far as I can tell, and is resolved by switching from the mamba installation of numpy to the pip installation.

**Comment by wolfv** [comment]
@rdilip from which channel are you installing `numpy`? Please note that this is _not_ a mamba issue at all, but rather the issue of the person who created the package.

**Comment by wolfv** [comment]
I just executed this code (with numpy from the `conda-forge` channel) and it worked fine on my M1 mac.
