### ISSUE TITLE
ModuleNotFoundError: No module named 'conda._vendor.auxlib'

### ISSUE THREAD

**Issue by Giuseppe1995** [mamba-org/mamba#1712]
Hi, 
I downloaded mamba via conda in my base environment via the command
`conda install mamba -c conda-forge`

But whichever command i try to run with mamba, let's say simply
`mamba create --help`
I get the following error:

> Traceback (most recent call last):
>   File "/srv/ngsdata/dalteriog/Tools/miniconda3/bin/mamba", line 7, in <module>
>     from mamba.mamba import main
>   File "/srv/ngsdata/dalteriog/Tools/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 53, in <module>
>     from mamba.utils import get_index, to_package_record_from_subjson, _supplement_index_with_system
>   File "/srv/ngsdata/dalteriog/Tools/miniconda3/lib/python3.8/site-packages/mamba/utils.py", line 7, in <module>
>     from .FastSubdirData import FastSubdirData
>   File "/srv/ngsdata/dalteriog/Tools/miniconda3/lib/python3.8/site-packages/mamba/FastSubdirData.py", line 23, in <module>
>     from conda._vendor.auxlib.ish import dals
> ModuleNotFoundError: No module named 'conda._vendor.auxlib'

My python version is 3.8.5. Can you tell me what is going wrong?
Thank you in advance, 
Giuseppe

**Comment by Giuseppe1995** [comment]
I upgraded it using conda, but the problem still remains

**Comment by wolfv** [comment]
The latest version is `mamba 0.23.3`. Can you show me the output of `conda list`?
