### ISSUE TITLE
How can I update the python verison from 3.7 to 3.8?

### ISSUE THREAD

**Issue by Elon-J** [mamba-org/mamba#1722]
<img width="850" alt="Screenshot 2022-06-02 173018" src="https://user-images.githubusercontent.com/88715865/171741811-6d95117e-408f-437b-9cb5-0aa1566f7f75.png">

When I use the command "mamba update python", it doesn't work.

**Comment by Paradoxdruid** [comment]
To move up a python version, you can't simply update, but would need to use, for instance, `mamba install python=3.8`.

Note that this can break things, and making a new virtual environment with the new python version is usually safer (e.g., `mamba create -n new_env python=3.8`
