### ISSUE TITLE
[Request] Complete `changeps1` implementation

### ISSUE THREAD

**Issue by chawyehsu** [mamba-org/mamba#1730]
Complete `changeps1` implementation

## Description
The config [`changeps1`](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#change-command-prompt) was added from #1304 (related to #1256), but only read/write of the config value were implemented. Actually the prompt change cannot be disabled because there is currently [no complete implemtation of the `changeps1` from the codebase](https://github.com/mamba-org/mamba/search?q=changeps1&type=code).

**Comment by victorlin** [comment]
I just tried on version 1.5.3 and it's working. Seems to be implemented here:

https://github.com/mamba-org/mamba/blob/7c5f0562c450e2fa41b4e63000a79fbab05f5e67/libmamba/src/core/activation.cpp#L138C3-L138C3

**Comment by chawyehsu** [comment]
Yeah, it was implemented.
