### ISSUE TITLE
Print warning in micromamba if not correct shebang is used if prefix is too long

### ISSUE THREAD

**Issue by traversaro** [mamba-org/mamba#1731]
In https://github.com/robotology/robotology-superbuild/pull/1145 we had a strange problem. If the latest version of `mambaforge` on Linux (powered by micromamba, if I am not wrong) is installed in a "short" prefix (such as 88 characters) then the `<prefix>/condabin/conda` and `<prefix>/condabin/mamba` scripts are well formed, and have the correct shebang that hardcodes the python of the base environment. 

If a longer prefix (>127 or similar) is used, then an incorrect sheback is used, and using mamba or conda outside of the base environment fails with an error like:
~~~
   File "/home/runner/work/paper_bergonti_2022_tro_kinematics-control-morphingcovers/paper_bergonti_2022_tro_kinematics-control-morphingcovers/robotology-superbuild/scripts/robotology-matlab/condabin/mamba", line 7, in <module>
     from mamba.mamba import main
 ModuleNotFoundError: No module named 'mamba'
~~~
for mamba or 
~~~
   File "/home/runner/work/robotology-superbuild/robotology-superbuild/robotology-superbuild-with-a-long-name-really-really-really-long-not-short-long/scripts/robotology-matlab/condabin/conda", line 12, in <module>
     from conda.cli import main
 ModuleNotFoundError: No module named 'conda'
~~~
for conda.

We understood later with @FabioBergonti that this happens as the shebang have a max limit of 127 characters (see https://stackoverflow.com/questions/10813538/shebang-line-limit-in-bash-and-linux-kernel) and so micromamba if the limit is violated, puts a shebang based on the environment that will work fine if the base environment is activated: https://github.com/mamba-org/mamba/blob/f751daf8039008aea945e88044d6c503fa9da046/libmamba/src/core/link.cpp#L157 .

I opened this issue for two reasons:
* firstly, for provide an entry point for people that are googling the problem, so that they know that **using a shorter install prefix** may be a solution for their problem
* secondly, to discuss if it could it make sense to print a warning in this case, so that debugging is easier if users encounter this problem.

**Comment by JohanMabille** [comment]
Mamba python's code has been removed in mamba 2. Now mamba is just a dynamically linked version of micromamba, and you should not see this issue anymore. Feel free to reopen it if it's not the case.
