### ISSUE TITLE
micromamba crashes when launched from home folder

### ISSUE THREAD

**Issue by akhmerov** [mamba-org/mamba#1751]
To reproduce, execute
```
sudo docker run -it --rm ubuntu:latest bash
apt update ; apt install -y curl bzip2
cd ; curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba ; cp -r bin/micromamba ~
./micromamba; echo $?
```
and observe that the exit code 1 is printed instead of the micromamba info page followed by exit code 0

I observed this behavior on Ubuntu 22.04 and CentOS 7.

If micromamba is placed in home folder, other copies of the executable placed in other location will crash as well.

**Comment by jonashaag** [comment]
Can you please try to reproduce this in an isolated environment, eg. Docker?

**Comment by akhmerov** [comment]
Done. I updated instructions to reproduce in docker.

**Comment by jonashaag** [comment]
Wow you are right. Adding a test in #1752
