### ISSUE TITLE
Fully statically linked build broken on Mac OS

### ISSUE THREAD

**Issue by AdrianFreundQC** [mamba-org/mamba#1753]
I tried to create a fully statically linked micromamba build following the documentation (https://mamba.readthedocs.io/en/latest/developer_zone/build_locally.html#fully-statically-linked) on a M1 Mac and ran into a few problems:

- [ ] `./micromamba/environment-static-dev.yml` doesn't exist. The documentation calls for installing this environment, but it doesn't exist. `./micromamba/environment-dev.yml` and `./libmamba/environment-static-dev.yml` exist and installing them both works.
- [ ] Undefined symbol:
```
Undefined symbols for architecture arm64:
  "_SCDynamicStoreCopyProxies", referenced from:
      _Curl_resolv in libcurl.a(libcurl_la-hostip.o)
ld: symbol(s) not found for architecture arm64
```
Linking Framework SystemConfiguration to libmamba fixes this. I'm currently working on a PR for this one.
- [ ] libcurl SecureTransport backend not available
```
warning  libmamba Could not use preferred SSL backend (Linux: OpenSSL, OS X: SecureTransport, Win: SChannel)
warning  libmamba Please check the cURL library configuration that you are using.
```
Looks like libcurl-static on conda-forge doesn't enable this option. libmamba falls back to using the OpenSSL backend
- [ ] `SSL certificate problem: unable to get local issuer certificate` statically linked OpenSSL doesn't find the certificate(s). Running with `--ssl-verify false` makes my micromamba build work.

**Comment by wolfv** [comment]
Hi @AdrianFreundQC great! 
Yes, unfortunately the libcurl build is a very specific (older) one from conda-forge. The last working build was 

```
    - libcurl 7.76.1 *_0           # [osx]
    - libcurl-static  7.76.1 *_0   # [osx]
```

Later builds removed the `darwin-ssl` feature from `libcurl` because it requires a newer macOS version. conda-forge tries to stay compatible with old versions of macOS.

We should create a variant in the curl-feedstock that emits a version of libcurl & libcurl-static that has darwin-ssl enabled, or we should build `libcurl` as part of the micromamba feedstock.

**Comment by alanhoyle** [comment]
The underlying issue appears to be that the micro.mamba.pm Let's Encrypt certificate has expired.  This affects the mac and linux installation instructions at https://mamba.readthedocs.io/en/latest/installation.html

```
$ wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now
$ wget https://micro.mamba.pm/api/micromamba/linux-64/latest
--2022-06-21 15:58:17--  https://micro.mamba.pm/api/micromamba/linux-64/latest
Resolving micro.mamba.pm (micro.mamba.pm)... 141.95.105.229, 152.228.167.221
Connecting to micro.mamba.pm (micro.mamba.pm)|141.95.105.229|:443... connected.
ERROR: cannot verify micro.mamba.pm's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to micro.mamba.pm insecurely, use `--no-check-certificate'.
[alanh@vm-login-2-2:~/tmp/bin] [base] 5 $ wget --no-check-certificate -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
bin/micromamba
$ ./bin/micromamba

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

Version: 0.24.0

Usage: ./bin/micromamba [OPTIONS] [SUBCOMMAND]

Options:
[....]
```

**Comment by jjerphan** [comment]
micromamba is not built and distributed for osx-arm64.

I am closing this issue in preference of https://github.com/mamba-org/mamba/issues/3541, which is the only issue which exist when building natively for osx-arm64. Feel free to reopen if you still have a problem.
