### ISSUE TITLE
[micromamba] shell init of cmd.exe _after_ powershell doesn't seem to work

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1756]
When first initializing `powershell` and then trying to initialize `cmd.exe` after, micromamba seems to silently fail.

**Comment by pavelzw** [comment]
It's not silently failing for me but failing with an error...

```
PS C:\Users\pavel> .\micromamba.exe shell init
Init powershell profile at '\\Mac\Home\Documents\WindowsPowerShell\profile.ps1'
Adding (or replacing) the following in your "\\\\Mac\\Home\\Documents\\WindowsPowerShell\\profile.ps1" file

#region mamba initialize
# !! Contents within this block are managed by 'mamba shell init' !!
$Env:MAMBA_ROOT_PREFIX = "C:\\Users\\pavel\\micromamba"
$Env:MAMBA_EXE = 'C:\Users\pavel\micromamba.exe'
(& 'C:\Users\pavel\micromamba.exe' 'shell' 'hook' -s 'powershell' -p "C:\\Users\\pavel\\micromamba") n
#endregion

Enter admin mode to enable long paths support?: [y/N] y
Windows long-path support enabled.
PS C:\Users\pavel> .\micromamba.exe shell init -s cmd.exe
info     libmamba ****************** Backtrace Start ******************
debug    libmamba Loading configuration
trace    libmamba Compute configurable 'create_base'
trace    libmamba Compute configurable 'no_env'
trace    libmamba Compute configurable 'no_rc'
trace    libmamba Compute configurable 'rc_files'
trace    libmamba Compute configurable 'root_prefix'
critical libmamba Could not use default 'root_prefix': C:\Users\pavel\micromamba: Directory exists, is not empty and not a conda prefix.
info     libmamba ****************** Backtrace End ********************
```

So it runs into [this](https://github.com/mamba-org/mamba/blob/ffddf3387011cc8b170f7b5b7f19c2ee1f0f9348/libmamba/src/api/configuration.cpp#L543) error.

**Comment by pavelzw** [comment]
Actually, the above described error also happens when trying to execute `micromamba shell init` twice in PowerShell, too.

**Comment by Karlheinzniebuhr** [comment]
Same issue

```
mamba init powershell

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.1.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

ERROR during elevated execution.
  rc: [WinError 0] The operation completed successfully.
no change     C:\ProgramData\mambaforge\Scripts\conda.exe
no change     C:\ProgramData\mambaforge\Scripts\conda-env.exe
no change     C:\ProgramData\mambaforge\Scripts\conda-script.py
no change     C:\ProgramData\mambaforge\Scripts\conda-env-script.py
no change     C:\ProgramData\mambaforge\condabin\conda.bat
no change     C:\ProgramData\mambaforge\Library\bin\conda.bat
no change     C:\ProgramData\mambaforge\condabin\_conda_activate.bat
no change     C:\ProgramData\mambaforge\condabin\rename_tmp.bat
no change     C:\ProgramData\mambaforge\condabin\conda_auto_activate.bat
no change     C:\ProgramData\mambaforge\condabin\conda_hook.bat
no change     C:\ProgramData\mambaforge\Scripts\activate.bat
no change     C:\ProgramData\mambaforge\condabin\activate.bat
no change     C:\ProgramData\mambaforge\condabin\deactivate.bat
no change     C:\ProgramData\mambaforge\Scripts\activate
no change     C:\ProgramData\mambaforge\Scripts\deactivate
no change     C:\ProgramData\mambaforge\etc\profile.d\conda.sh
no change     C:\ProgramData\mambaforge\etc\fish\conf.d\conda.fish
no change     C:\ProgramData\mambaforge\shell\condabin\Conda.psm1
no change     C:\ProgramData\mambaforge\shell\condabin\conda-hook.ps1
no change     C:\ProgramData\mambaforge\Lib\site-packages\xontrib\conda.xsh
no change     C:\ProgramData\mambaforge\etc\profile.d\conda.csh
needs sudo    C:\Users\Karl\Documents\WindowsPowerShell\profile.ps1
No action taken.
Operation failed.

(base) C:\WINDOWS\system32>
```

**Comment by jovenlaurens** [comment]
> Same issue
> 
> ```
> mamba init powershell
> 
>                   __    __    __    __
>                  /  \  /  \  /  \  /  \
>                 /    \/    \/    \/    \
> ███████████████/  /██/  /██/  /██/  /████████████████████████
>               /  / \   / \   / \   / \  \____
>              /  /   \_/   \_/   \_/   \    o \__,
>             / _/                       \_____/  `
>             |/
>         ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
>         ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
>         ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
>         ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
>         ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
>         ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝
> 
>         mamba (1.1.0) supported by @QuantStack
> 
>         GitHub:  https://github.com/mamba-org/mamba
>         Twitter: https://twitter.com/QuantStack
> 
> █████████████████████████████████████████████████████████████
> 
> ERROR during elevated execution.
>   rc: [WinError 0] The operation completed successfully.
> no change     C:\ProgramData\mambaforge\Scripts\conda.exe
> no change     C:\ProgramData\mambaforge\Scripts\conda-env.exe
> no change     C:\ProgramData\mambaforge\Scripts\conda-script.py
> no change     C:\ProgramData\mambaforge\Scripts\conda-env-script.py
> no change     C:\ProgramData\mambaforge\condabin\conda.bat
> no change     C:\ProgramData\mambaforge\Library\bin\conda.bat
> no change     C:\ProgramData\mambaforge\condabin\_conda_activate.bat
> no change     C:\ProgramData\mambaforge\condabin\rename_tmp.bat
> no change     C:\ProgramData\mambaforge\condabin\conda_auto_activate.bat
> no change     C:\ProgramData\mambaforge\condabin\conda_hook.bat
> no change     C:\ProgramData\mambaforge\Scripts\activate.bat
> no change     C:\ProgramData\mambaforge\condabin\activate.bat
> no change     C:\ProgramData\mambaforge\condabin\deactivate.bat
> no change     C:\ProgramData\mambaforge\Scripts\activate
> no change     C:\ProgramData\mambaforge\Scripts\deactivate
> no change     C:\ProgramData\mambaforge\etc\profile.d\conda.sh
> no change     C:\ProgramData\mambaforge\etc\fish\conf.d\conda.fish
> no change     C:\ProgramData\mambaforge\shell\condabin\Conda.psm1
> no change     C:\ProgramData\mambaforge\shell\condabin\conda-hook.ps1
> no change     C:\ProgramData\mambaforge\Lib\site-packages\xontrib\conda.xsh
> no change     C:\ProgramData\mambaforge\etc\profile.d\conda.csh
> needs sudo    C:\Users\Karl\Documents\WindowsPowerShell\profile.ps1
> No action taken.
> Operation failed.
> 
> (base) C:\WINDOWS\system32>
> ```

I also have the same error as him. Is there any update for the fix?

**Comment by JohanMabille** [comment]
This has been fixed in mamba 2.
