### ISSUE TITLE
Error installing snippy

### ISSUE THREAD

**Issue by erin-thei** [mamba-org/mamba#1757]
Hi all,

Pretty new to all of this. I'm trying to install snippy. Ran the command conda install -c conda-forge -c bioconda -c defaults snippy but it took hours, getting hung up on solving environment. Someone had experienced the same issue but resolved it using mamba install snippy. I tried that but got this error message: Error Message:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/erintheiller/opt/anaconda3/envs/SNIPPY/lib/python3.10/site-packages/conda/exceptions.py", line 1114, in __call__
        return func(*args, **kwargs)
      File "/Users/erintheiller/opt/anaconda3/envs/SNIPPY/lib/python3.10/site-packages/mamba/mamba.py", line 935, in exception_converter
        raise e
      File "/Users/erintheiller/opt/anaconda3/envs/SNIPPY/lib/python3.10/site-packages/mamba/mamba.py", line 929, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/erintheiller/opt/anaconda3/envs/SNIPPY/lib/python3.10/site-packages/mamba/mamba.py", line 887, in _wrapped_main
        result = do_call(args, p)
      File "/Users/erintheiller/opt/anaconda3/envs/SNIPPY/lib/python3.10/site-packages/mamba/mamba.py", line 750, in do_call
        exit_code = install(args, parser, "install")
      File "/Users/erintheiller/opt/anaconda3/envs/SNIPPY/lib/python3.10/site-packages/mamba/mamba.py", line 586, in install
        transaction.fetch_extract_packages()
    RuntimeError: Download error (28) Timeout was reached [https://conda.anaconda.org/bioconda/osx-64/perl-convert-binary-c-0.78-pl526h04f5b5a_3.tar.bz2]
    Operation too slow. Less than 30 bytes/sec transferred the last 60 seconds

`$ /Users/erintheiller/opt/anaconda3/envs/SNIPPY/bin/mamba install snippy`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=SNIPPY
                CONDA_EXE=/Users/erintheiller/opt/anaconda3/bin/conda
             CONDA_PREFIX=/Users/erintheiller/opt/anaconda3/envs/SNIPPY
           CONDA_PREFIX_1=/Users/erintheiller/opt/anaconda3
    CONDA_PROMPT_MODIFIER=(SNIPPY)
         CONDA_PYTHON_EXE=/Users/erintheiller/opt/anaconda3/bin/python
               CONDA_ROOT=/Users/erintheiller/opt/anaconda3/envs/SNIPPY
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/erintheiller/opt/anaconda3/envs/SNIPPY/bin:/Users/erintheiller/
                          opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/o
                          pt/X11/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/erintheiller/opt/anaconda3/envs/SNIPPY
            shell level : 2
       user config file : /Users/erintheiller/.condarc
 populated config files : /Users/erintheiller/.condarc
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.10.5.final.0
       virtual packages : __osx=11.2.3=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/erintheiller/opt/anaconda3/envs/SNIPPY  (writable)
      conda av data dir : /Users/erintheiller/opt/anaconda3/envs/SNIPPY/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
          package cache : /Users/erintheiller/opt/anaconda3/envs/SNIPPY/pkgs
                          /Users/erintheiller/.conda/pkgs
       envs directories : /Users/erintheiller/opt/anaconda3/envs/SNIPPY/envs
                          /Users/erintheiller/.conda/envs
               platform : osx-64
             user-agent : conda/4.13.0 requests/2.28.0 CPython/3.10.5 Darwin/20.3.0 OSX/11.2.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

(SNIPPY) Erins-MacBook-Air:~ erintheiller$ 

Can anyone help me to understand what this means and how to resolve this? 

Thanks so much in advance!

**Comment by wolfv** [comment]
Hi, your internet connections is really slow. The error says: `Operation too slow. Less than 30 bytes/sec transferred the last 60 seconds`

Is that generally an issue?
