### ISSUE TITLE
Error installing rapids with micromamba, but works with mamba

### ISSUE THREAD

**Issue by cjdoris** [mamba-org/mamba#1772]
c.f. https://github.com/cjdoris/CondaPkg.jl/issues/38

The following command
```
micromamba create -n rapids-22.06 -c rapidsai -c nvidia -c conda-forge  \
    rapids=22.06 python=3.9 cudatoolkit=11.5
```
fails with the following error message (after a lot of clobber warnings)
```
critical libmamba File exists: '/home/tyler/micromamba/pkgs/libraft-distance-22.06.00-cuda11_ged2c529_0/include/rapids/libcxx/include', '/home/tyler/condapkg_test/.CondaPkg/env/include/rapids/libcxx/include'
```
whereas the same command using `mamba` instead works fine.

This occurs on Linux, with mamba/micromamba v0.24.0.

**Comment by tylerjthomas9** [comment]
This issue has been fixed in RAPIDS/cuML v22.10
