### ISSUE TITLE
Installation of micromamba fails on macOS

### ISSUE THREAD

**Issue by pwrose** [mamba-org/mamba#1782]
The installation on MacOS 10.14.6:

`curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba`

fails with the following error message:

```
tar: bin/micromamba: Not found in archive
tar: Error exit delayed from previous errors.
```

**Comment by wolfv** [comment]
@pwrose you tried to get the `linux-64` binary on  macOS?

Can you try the following script: `curl micro.mamba.pm/install.sh | bash`? That should take care of everything :)

**Comment by pwrose** [comment]
@wolfv 

```curl micro.mamba.pm/install.sh | bash```

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   889  100   889    0     0   2476      0 --:--:-- --:--:-- --:--:--  2476
tar: bin/micromamba: Not found in archive
tar: Error exit delayed from previous errors.
bash: line 42: /Users/Peter/.local/bin/micromamba: No such file or directory

I also tried:
```curl -Ls https://micro.mamba.pm/api/micromamba/osx-64/latest | tar -xvj bin/micromamba```

tar: bin/micromamba: Not found in archive
tar: Error exit delayed from previous errors.

**Comment by jonashaag** [comment]
Curious, what's your download's md5 sum?

```
curl -Ls https://micro.mamba.pm/api/micromamba/osx-64/latest | md5
18d877c52d3798a4010122e69c00fdd9
```

**Comment by wolfv** [comment]
@pwrose maybe you can inspect the actual output that CURL retrieves (e.g. by printing it to the screen). It might be some HTML page or similar ...

**Comment by pwrose** [comment]
@jonashaag The md5 hash is different: d41d8cd98f00b204e9800998ecf8427e

tar version is: bsdtar 2.8.3 - libarchive 2.8.3

**Comment by wolfv** [comment]
I'm pretty sure you're accidentally downloading something else, e.g. a HTML page or so. Could the domain be disallowed by some IT security system?

**Comment by pwrose** [comment]
Worked fine after upgrading the OS to Catalina.
