### ISSUE TITLE
Support XDG directories

### ISSUE THREAD

**Issue by AntoinePrv** [mamba-org/mamba#1787]
The idea would be to extend and allow customization of directories used by `micromamba` (to some extend for `mamba`). This would be done according to the [`XDG`](https://wiki.archlinux.org/title/XDG_Base_Directory) specification.

Supported options are listed from highest to lowest priority
### A - Configs
- `$XDG_CONFIG_HOME/mamba/mambarc` if set
- `$HOME/.config/mamba/mambarc` new
- `$HOME/.mambarc` legacy

### B - Environments
- `$CONDA_ENVS_PATH` if set
- `$MAMBA_ROOT_PREFIX/envs/` if set
- `$XDG_DATA_HOME/mamba/envs` if set
- `$HOME/.local/share/mamba/envs`

### C - Packages
- `$CONDA_PKGS_DIRS` if set
- `$MAMBA_ROOT_PREFIX/pkgs/` if set
- `$XDG_CACHE_HOME/mamba/pkgs` if set
- `$HOME/.cache/mamba/pkgs`

### D - Authentication
Not sure if `authentication.json` should be with configs or data.

-----

At least *A* and *D* would be useful for further isolating tests (which I believe is one of the reason I'm still having trouble running tests on my local machine).

**Comment by bepoli** [comment]
I think it's worth noting that `conda` already implements this (https://github.com/conda/conda/pull/10982), which means that people storing condarc in `XDG_CONFIG_HOME/conda` will be required to move or link it if they switch to mamba. It would be nice to have the same behaviour in `mamba` and `micromamba`.

**Comment by anuramat** [comment]
what about root_prefix? it's still not xdg compliant, is it?
sorry for necroing
