### ISSUE TITLE
Bug in mamba remove [package] when [package] depends on cuda 

### ISSUE THREAD

**Issue by jamartinh** [mamba-org/mamba#1794]
Remove:
───────────────────────────────────────────────────────────────────────

  - __cuda       11.4  0                         installed

KeyError: PackageRecord(_hash=5352623804000103275, name='__cuda', version='11.4', build='0', build_number=0, channel=Channel("@"), subdir='linux-64', fn='__cuda', md5='12345678901234567890123456789012', package_type='virtual_system')

**Comment by jonashaag** [comment]
Same as https://github.com/mamba-org/mamba/issues/1770?

**Comment by Kaixhin** [comment]
I have also come across this issue when trying to `mamba uninstall pytorch`, with this cryptic message about the above `__cuda` package appearing when it fails.

**Comment by Fissium** [comment]
Is there still no solution?

**Comment by jjerphan** [comment]
I cannot reproduce the problem with mamba 1.5.10 and mamba 2.0.2.

Feel free to comment with a reproducer if you observe this issue again.
