### ISSUE TITLE
Some micromamba tests fail on osx-arm64 because xframe isn't available for that architecture

### ISSUE THREAD

**Issue by AdrianFreundQC** [mamba-org/mamba#1796]
Some micromamba test try to install or lookup the `xframe` package. However this package currently isn't available for `osx-arm64`, leading to those tests always failing when running withing an `osx-arm64` environment.

The `CONDA_SUBDIR` environment variable can be used to make conda use a specific architecture. This could improve test isolation in cases where the packages don't actually have to be run, but just looked up or installed.

Alternatively, another package, which is supported on all architectures could be used for the tests or, depending on how difficult that would be, `xframe` could be compiled for other architectures on conda-forge.

**Comment by JohanMabille** [comment]
The tests have been fixed .
