### ISSUE TITLE
Segmentation Fault (Core Dumped) sometimes but not always when installing packages

### ISSUE THREAD

**Issue by amorris28** [mamba-org/mamba#1799]
I'm on Ubuntu 20.04.1
Versions:
```
mamba 0.24.0
conda 4.13.0
```
At least 75% of the time I try to install a package, I get this error:
```
Segmentation fault (core dumped)
```
But if I rerun the same command, it will occasionally work. So, essentially I just have to keep rerunning the same command over and over until it completes. It can fail during the `Looking for... ['package']` step or after the `Confirm changes: [Y/n] y` when it actually starts installing. Here is an example command:

```
mamba install -n aes -c conda-forge -c bioconda -c r r-vegan
```

This also happens when I install packages when I create an environment, for example:
```
mamba create -n env -c conda-forge -c bioconda -c r r-base
```

I do not have this problem when I install packages using a `config.yml` like this:
```
mamba env create -f config.yml
```
That appears to work every time and so my current work around is to edit the `config.yml` and do this every time I want to install a package:
```
mamba env remove -n aes
mamba env create -f config.yml
```

Any suggestions of how to troubleshoot this?

**Comment by wolfv** [comment]
what are the contents of the `config.yml` file?

**Comment by amorris28** [comment]
config.yml:
```
name: aes
channels:
        - conda-forge
        - bioconda
        - defaults
        - R
dependencies:
        - r-base=4.1
        - r-devtools
        - r-tidyverse=1.3.1
        - r-vegan
        - r-corncob
        - r-ggpubr
        - r-ggthemes
        - r-kableExtra
        - r-captioner
        - r-flextable
        - r-ggtext
        - bioconductor-phyloseq
        - bioconductor-dada2
        - bioconductor-decontam
        - bioconductor-ancombc
        - bioconductor-aldex2
```

**Comment by amacati** [comment]
I observe a similar behavior when trying to install pytorch. Steps to reproduce:

`mamba create -n test python=3.11
mamba activate test
mamba install -c pytorch pytorch`

-> Segmentation fault (core dumped)

**Comment by amacati** [comment]
Seems specific to the installation I'm currently using. When using the micromamba Docker image the steps result in the expected "Could not solve" error.
