### ISSUE TITLE
Mamba and conda seem to be hanging

### ISSUE THREAD

**Issue by del-oxyribonucleic-acid** [mamba-org/mamba#1825]
I have tried creating new conda evs using both the conda and mamba commands (nowadays I typically use mamba, but wanted to check) and both seem to be hanging and unable to create new environments. The MAMBA icon comes up, but nothing seems to install. This is currently an issue for all users on our server, not just me. Here is an example of the code I have been using, any help is greatly appreciated!

mamba create --name illumina-utils-dev python=3.6

-- Update
It does finally install, however, it takes ~10-15 min instead of essentially instantaneous as it previously was.

**Comment by jonashaag** [comment]
Can you please run it with -v to see where it’s spending its time.

**Comment by wolfv** [comment]
Are you mixing defaults and conda-forge?
