### ISSUE TITLE
Failed to install mamba using conda

### ISSUE THREAD

**Issue by odebroqueville** [mamba-org/mamba#1837]
I typed

`conda install mamba -n base -c conda-forge`

Solving environment seemed problematic and conflicts were found, so I interrupted the process:

<img width="772" alt="Screenshot 2022-08-04 at 21 48 50" src="https://user-images.githubusercontent.com/4818315/182940053-fc40d9e6-281c-4923-b1ae-390fbcec888a.png">

**Comment by jonashaag** [comment]
Looks like you have other packages in base. It is recommended to have Conda and Mamba only.

**Comment by odebroqueville** [comment]
Anaconda installs a large number of packages by default such as Numpy, Pandas, etc.

Does this mean that we should avoid using Anaconda if we want to use mamba? Is this why it is recommended to use miniconda?

**Comment by danhamill** [comment]
I came across this today.  My workaround was to
1. uninstall `spyder` using conda.
2. install `mamba` using conda
3. install `spyder` using mamba

I have no idea what was causing the conflicts.

**Comment by jonashaag** [comment]
We recommend not to use Anaconda. There’s little we can do to improve the situation sadly.

**Comment by mayuefine** [comment]
> I came across this today with a fresh anaconda install. My workaround was to
> 
> 1. uninstall `spyder` using conda.
> 2. install `mamba` using conda
> 3. install [`spyder`](https://anaconda.org/conda-forge/spyder) using mamba
> 
> I would have never thought spyder was causing the problem until I saw this post. On my computer, conda never found the conflicting package. I have no idea what was causing the conflicts.

It's also works for me!!!

**Comment by lbdhr** [comment]
> I came across this today with a fresh anaconda install. My workaround was to
> 
> 1. uninstall `spyder` using conda.
> 2. install `mamba` using conda
> 3. install [`spyder`](https://anaconda.org/conda-forge/spyder) using mamba
> 
> I would have never thought spyder was causing the problem until I saw this post. On my computer, conda never found the conflicting package. I have no idea what was causing the conflicts.

Not work for me. And I cannot even reinstall spyder...
