### ISSUE TITLE
`micromamba shell init` changes font and terminal size when executed in PowerShell

### ISSUE THREAD

**Issue by pavelzw** [mamba-org/mamba#1841]
Here is a funny one: 

When executing `micromamba shell init` in PowerShell, the font and size of the terminal changes. 🤪

Before:
<img width="921" alt="image" src="https://user-images.githubusercontent.com/29506042/183147240-b4356e1e-b1fa-4d57-9f2e-1ae98e7fc2d4.png">

After:
<img width="980" alt="image" src="https://user-images.githubusercontent.com/29506042/183147506-3c05b58e-53cd-46bd-961f-9bc7974d6aee.png">

When opening another PowerShell instance, the font is back to normal.

~~My guess it that it has something to do with [this `termcolor::colorize` console output](https://github.com/mamba-org/mamba/blob/ffddf3387011cc8b170f7b5b7f19c2ee1f0f9348/libmamba/src/core/shell_init.cpp#L750) which may have [weird behavior in PowerShell](https://github.com/ikalnytskyi/termcolor#control-manipulators)(?)~~
It's not because of that, I tested it out with no `Console::stream()` but the bug still occurred...

**Comment by JohanMabille** [comment]
This has been fixed in mamba 2.
