### ISSUE TITLE
micromamba update fails when using channels

### ISSUE THREAD

**Issue by Telvary** [mamba-org/mamba#1846]
When specifying a package with a channel, or when using a yaml file, `micromamba update` fails. This kinda looks like https://github.com/mamba-org/mamba/issues/504 

**The issue** : 
```
(server) root@2e8550c5affe:/app# micromamba update conda-forge::gunicorn

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

error    libmamba Selected channel specific (or force-reinstall) job, but package is not available from channel. Solve job will fail.

Pinned packages:
  - python 3.8.*

Transaction

  Prefix: /opt/conda/envs/server

  All requested packages already installed
```

**Expected result**. 

- Existing packages updated
- Newly added pacakges installed

**Comment by jsoto-gladia** [comment]
@SylvainCorlay any news on this ?

**Comment by d-tork** [comment]
This is a problem for me, and I'm not even using micromamba (so #504 still). I have mamba 0.25.0 and I'm not pinning package versions, just prefixing it with the channel name. I've tried with `channel_priority` in strict, flexible, and disabled. Gives this message both with `env create -f` and `env update -f`.

**Comment by AntoinePrv** [comment]
@Telvary I'm looking at this but I cannot reproduce this issue.

Could you provide me with the steps you used to create your `server` environment, as well as the content of your conda/mamba configuration files?

**Comment by wolfv** [comment]
@AntoinePrv I think you need to _not_ configure any channels in your `.condarc` file. Then the update will fail (because no channels are loaded).

This is where we usually add channels that come from the MatchSpecs: https://github.com/mamba-org/mamba/blob/e0527eb061b0ce724dcb3c2f34db25c907ee7113/libmamba/src/api/install.cpp#L405-L413

I am not sure we go into that code path for the update.
