### ISSUE TITLE
"Command not found" after installation

### ISSUE THREAD

**Issue by rawnsley** [mamba-org/mamba#1850]
Platform: OSX on a MacBook Pro M1 and same problem on a MacBook Air M1

I followed [these installation instructions](https://mamba.readthedocs.io/en/latest/installation.html) and installation appeared to complete without any problems, albeit after several hours. I expected to be able to run the `mamba` command at this point, but the shell can't find it. At first I assumed the binary search path need to be updated, but starting a new shell didn't help.

The installation guide could do with instructions about how to check everything is working. I'm assuming you can just run the `mamba` binary because another package asked us to do this as the next step after installation.

I am very new to the Anaconda ecosystem so I might be missing something obvious.

**Comment by jonashaag** [comment]
Did you follow the

> We strongly recommend to start from mambaforge, a community project of the conda-forge community.

instructions or the

> Existing conda install

instructions?

If the latter, any reasons not to use mamba forge?

**Comment by rawnsley** [comment]
Thanks for the super quick response.

I used the second one, but only because it was similar to the instructions listed by the other library. I would probably have chosen this version anyway as I had already installed `conda` and it felt like less stuff would need to be installed. I don't mean any offence by this, but having to install a package manager for your package manager was a little confusing.

I didn't notice that the first option has the "After successful installation..." instruction that I complained about, so scratch that suggestion. You might want to move it to it's own section after the install instructions for clarity though.

I'm happy to try the mambaforge option instead. Do I need to wind back the previous installation of mamba or the installation of conda itself before I try it?

**Comment by wolfv** [comment]
That would be the most straight-forward (especially if you just started out), to remove the previous installation and install mambaforge instead.

**Comment by rawnsley** [comment]
I tried `brew install miniforge` and completed successfully, but couldn't run `mamba` so I uninstalled.

The [script based installer](https://github.com/conda-forge/miniforge#unix-like-platforms) has worked and I can now run the `mamba` command from my shell.

Thanks for you help.
