### ISSUE TITLE
Incorrect Linux version regex `[linux version not found (virtual package skipped)]`

### ISSUE THREAD

**Issue by kelszo** [mamba-org/mamba#1851]
The regex on line 301 in `libmamba/src/core/util_os.cpp` is incorrect for detecting Linux versions.

The current regex is `([0-9]+\.[0-9]+\.[0-9]+)-.*` and expects the Linux kernel version to end with `-kernel-flavour`. Ex. `5.15.59-27-generic`. Not all kernel versions end with a flavour tag however. On NixOS the kernel versions are simply `5.15.59`, meaning the current regex fails matching. This leads to the `linux version not found (virtual package skipped)` warning on certain distros.

A fix would be using a regex such as `([0-9]+\.[0-9]+\.[0-9]+)(?:-.*)?` or `^([0-9]+\.[0-9]+\.[0-9]+)(?:-.*)?$`.

**Outputs**
```
$ uname -a
Linux pc 5.15.59 #1-NixOS SMP Wed Aug 3 10:03:56 UTC 2022 x86_64 GNU/Linux

$ uname -r
5.15.59

$ micromamba --version
0.24.0
```

**Comment by wolfv** [comment]
A PR would be very welcome!

**Comment by kelszo** [comment]
Sure! Will have a PR ready later today

**Comment by wolfv** [comment]
regex seems to work according to regex101.com :)

**Comment by wholtz** [comment]
[Micromamba-docker isssue 227](https://github.com/mamba-org/micromamba-docker/issues/227) seems to indicate the updated regex is still failing to match on some linux distributions.

**Comment by wolfv** [comment]
I just ran our regex over the uname and it seems fine. Weird.

<img width="703" alt="Screenshot 2022-10-25 at 17 53 43" src="https://user-images.githubusercontent.com/885054/197822391-153ae786-fca0-4856-b0f8-94c33fc1123c.png">

**Comment by wholtz** [comment]
Yeah, I jumped the gun on the regex. I tried it in https://regex101.com/ but forget to remove the `\` escaping, so it looked like it was failing on regex.

**Comment by wolfv** [comment]
interesting, thanks for helping out with the debugging!
