### ISSUE TITLE
micromamba activate does not work in fish

### ISSUE THREAD

**Issue by Yura52** [mamba-org/mamba#1858]
If I start a new fish session and run these commands:

```
set -gx MAMBA_EXE /Users/$myname/bin/micromamba
set -gx MAMBA_ROOT_PREFIX /Users/$myname/micromamba
eval "$(micromamba shell hook --shell=fish)"
micromamba activate base
```

then the first three commands succeed, but the last one fails. Namely, the last command **activates the new environment correctly**, but **the prompt prefix remains unchanged** (i.e. no `(base)` prefix), and fish reports the error code `[4]`. This applies to non-base environments as well (like `micromamba activate my_custom_environment`). At the same time, **the analogous commands run successfully in zsh**.

Environment:
```
CPU: M1
macOS: 11.6
fish: 3.5.1
zsh: 5.9
micromamba: 0.23.2
```

Also, I don't have neither mamba nor conda on my machine.

**Comment by jonashaag** [comment]
Is this still a problem for you?

Can you try using Micromamba from Homebrew? `brew install micromamba`

**Comment by lucasfcnunes** [comment]
Same is happening with me.

What I did
```sh
curl micro.mamba.pm/install.sh | bash
micromamba install -n base python=3.10
micromamba shell reinit
micromamba config set auto_activate_base true
```
in bash it's working fine, but in fish it's not...

**Comment by jonashaag** [comment]
Can you reproduce this inside a fresh Docker container?

**Comment by agrawalsourav98** [comment]
I am also facing this issue. Works fine on zsh and bash but doesn't show env prompt in fish.
Env,
```
CPU: i5 11th Gen, i5-1145G7
kernel version: 5.14.0-1054-oem
OS: Elementary OS 6.1 (Based on Ubuntu 22.04)
fish: 3.5.1
zsh: 5.8
micromamba: 1.0.0
```
I was using mamba earlier which was working fine with the same setup.

**Comment by agrawalsourav98** [comment]
Tried to debug a little and found out that this is due to incorrect use of eval in fish shell. [Eval in fish shell](https://fishshell.com/docs/current/cmds/eval.html) joins all the parameters using a space separator. So, during activation or deactivation, the env variables are not being set correctly.

For the fix appending a `;` at the end of each command in the output of  `micromamba shell -s fish activate <env>` would fix this issue.

**Comment by jonashaag** [comment]
@agrawalsourav98 thanks for digging into this, we already fixed this particular problem on main

**Comment by lucasfcnunes** [comment]
> Can you reproduce this inside a fresh Docker container?

@jonashaag
Little too late but:
`docker run -it --rm lucasfcnunes/micromamba_fish`
source: https://github.com/lucasfcnunes/micromamba_fish

**Comment by agrawalsourav98** [comment]
> @agrawalsourav98 thanks for digging into this, we already fixed this particular problem on main

I used the latest nightly of micromamba and can confirm this is fixed.

**Comment by jonashaag** [comment]
Thanks @lucasfcnunes looks like the same issue. We should make a release soon. In the meantime you can use micromamba from main or manually copy the latest version of https://github.com/mamba-org/mamba/blob/main/libmamba/data/mamba.fish to `~/micromamba/etc/fish/conf.d/mamba.fish`

**Comment by b4rlw** [comment]
Has this issue been fixed in a release yet?
I'm still getting an error code of [4] when running `micromamba activate` or `micromamba deactivate` in fish with the latest Homebrew version, even though the operation appears to succeed.

**Comment by jonashaag** [comment]
@b4rlw if this is still an issue for you please open a new ticket
