### ISSUE TITLE
How to upgrade micromamba?

### ISSUE THREAD

**Issue by astrojuanlu** [mamba-org/mamba#1861]
I installed Micromamba [a while back](https://twitter.com/juanluisback/status/1509495267070033923) and now I have 0.22.0, but I see there have been newer versions lately. I wanted to do this before reporting a weird behavior/bug. However, I didn't find in [the docs](https://mamba.readthedocs.io/en/latest/installation.html) how to upgrade micromamba. Any pointers?

**Comment by astrojuanlu** [comment]
For the record, looks like `curl micro.mamba.pm/install.sh | bash` ("reinstalling") did the trick and nothing broke (did 1 minute of testing only). Perhaps this could be included in the docs, if it's the preferred solution?

**Comment by jonashaag** [comment]
For macOS, updates should be automatic if you use Homebrew

**Comment by astrojuanlu** [comment]
Just did `curl micro.mamba.pm/install.sh | bash` again and I'm on micromamba 1️⃣ . 0️⃣ 🎉

**Comment by jonashaag** [comment]
We also have a new `self-update` feature in 1.0.0.
