### ISSUE TITLE
Mamba error when creating new environment from yaml file

### ISSUE THREAD

**Issue by jeffwong** [mamba-org/mamba#1865]
I am provisioning a new environment using a yaml file. Small reproducible example below. When running

`mamba env create -f environment_small.yml -p conda/envs/environment_small`

I see the error `error    libmamba Selected channel specific (or force-reinstall) job, but package is not available from channel. Solve job will fail.`

Small yaml file:

```
name: foo
channels:
  - defaults
  - conda-forge
dependencies:
  - defaults::numpy
  - defaults::scipy
  - defaults::statsmodels
  - jupyterlab
```

Running MacOS 12.5 with
mamba 0.25.0
conda 4.14.0

**Comment by jonashaag** [comment]
@wolfv is this an example of https://github.com/mamba-org/mamba/issues/1862#issuecomment-1216863105 as well? If you think it’s generally not advisable to mix the both, should we add a warning to Mamba?

**Comment by jeffwong** [comment]
Using defaults and conda-forge works fine with vanilla conda though. Common use case I see is that a lot of R packages are more up to date on conda-forge, hence sometimes using the conda-forge channel.

**Comment by jonashaag** [comment]
I'll let someone else answer to that because I don't know.

In any case you might want to try using conda-forge exclusively, it works great!

**Comment by jeffwong** [comment]
@wolfv any thoughts? Will it be possible to have 2 different channels in this yaml?

**Comment by jonashaag** [comment]
xref #1924

**Comment by jonashaag** [comment]
We do not recommend to use Anaconda/defaults.

**Comment by IlyaOrson** [comment]
Unfortunately sometimes the discrepancies between channels causes some bugs and it is necessary to specify the channel per package.

Trying to solve this [pytorch installation issue on windows](https://github.com/pytorch/pytorch/issues/7579), the recommended solution is to reinstall a library with defaults: `conda install -c defaults intel-openmp -f`.

An environment file with this specification produces a working environment with conda
```yaml
name: intel-openmp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - defaults::intel-openmp
```
while mamba fails with `error    libmamba Selected channel specific (or force-reinstall) job, but package is not available from channel. Solve job will fail.`

**Comment by jonashaag** [comment]
@IlyaOrson we don't recommend to fix the channels like that, better if you were able to fix the issue with the packages so that you can use only conda-forge/pytorch but not defaults

**Comment by IlyaOrson** [comment]
I just realized that in my case the environment that conda creates from the file is also broken, and the only difference between conda and mamba is that mamba warns about it.

Since the bug comes from an upstream package, I guess it is not possible to specify a working environment from a file in this case then. The only solution is to force reinstall that library after the environment creation for now.
