### ISSUE TITLE
Offline mode attempts to download and does not accept `ctrl+c` abort for at least ~10s

### ISSUE THREAD

**Issue by corneliusroemer** [mamba-org/mamba#1869]
I tried out using the `--offline` flag to install packages. It worked for the cached index, but when some packages were not in the cache mamba attempted to download packages from the internet.

It took about 1s for each package to realize it couldn't download. When I hit `ctrl+c` to abort, mamba didn't respond.

What I think _should_ happen instead:
1. Mamba instantly recognizes that it's in offline mode and aborts without trying to download
2. Accept `ctrl+c` all the time and not trap the user for 10s

See how it doesn't accept `ctrl+c`:
<img width="1710" alt="image" src="https://user-images.githubusercontent.com/25161793/185799234-abf30c26-9794-4986-b760-13972c7df16f.png">

**Comment by jonashaag** [comment]
Would be fixed with https://github.com/mamba-org/mamba/pull/1284
