### ISSUE TITLE
Controlling mamba fetch retries

### ISSUE THREAD

**Issue by shughes-uk** [mamba-org/mamba#1871]
Does micromamba respect the conda.rc options `remote_max_retries` and `remote_read_timeout_secs`?

When we run `mamba install` on 1000 EC2 `c5.xlarge` , installing 234 packages on each instance, we consistently see at least one fail with

 ```
critical libmamba Download error (28) Timeout was reached [https://repo.anaconda.com/pkgs/main/noarch/pexpect-4.8.0-pyhd3eb1b0_3.conda]
 Operation too slow. Less than 30 bytes/sec transferred the last 60 seconds
```

We need to be able to adjust mamba to be more tolerant of situations like this and retry slightly harder. 1/1000 does not seem like a lot but we regularly run this many thousands of times a day so we have multiple failures to this per day!

**Comment by jonashaag** [comment]
Doesn't look like it's implemented. Should be easy to add `remote_max_retries`, similar to `ssl_verify`:

https://github.com/mamba-org/mamba/blob/e0527eb061b0ce724dcb3c2f34db25c907ee7113/libmamba/src/api/configuration.cpp#L1173-L1183 https://github.com/mamba-org/mamba/blob/e0527eb061b0ce724dcb3c2f34db25c907ee7113/micromamba/src/common_options.cpp#L132-L136

For `remote_read_timeout_secs` I found this, not sure what it means exactly https://github.com/mamba-org/mamba/blob/6a51a0984167012fe4c0601849532fabd8356a8c/libmamba/src/core/fetch.cpp#L234-L236
