### ISSUE TITLE
Micromamba: allow selecting category for new lockfile format

### ISSUE THREAD

**Issue by maresb** [mamba-org/mamba#1883]
Based on the lack of command-line options and skimming the source code, it appears that micromamba is hardcoded to install only packages where `category=main`. It would be convenient to, for example, specify both `main` and `dev`.

https://github.com/mamba-org/mamba/blob/e0527eb061b0ce724dcb3c2f34db25c907ee7113/libmamba/src/core/transaction.cpp#L1572

**Comment by maresb** [comment]
@jvansanten, while you're in the codebase, depending on how motivated you are at the moment, perhaps this would be an easy fix?

**Comment by jvansanten** [comment]
On it. Since it touches the same parts, I'll wait for #1908 before opening another PR.
