### ISSUE TITLE
Previously working mamba now throwing `ImportError: Library not loaded: '@rpath/libsolv.1.dylib'` on apple silicon

### ISSUE THREAD

**Issue by corneliusroemer** [mamba-org/mamba#1897]
I use mamba on my M1 apple silicon (arm64) MacBookPro.

I have installed conda/mamba using mambaforge about a month ago. Things were working well.

I'm using the native arm version.

Today I installed rust via `brew install rustup`.

Suddenly when I try to run mamba to install something I get the following error and traceback:
```txt
❯ mamba update --all              
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: dlopen(/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/libmambapy/bindings.cpython-310-darwin.so, 0x0002): Library not loaded: '@rpath/libsolv.1.dylib'
  Referenced from: '/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/libmambapy/bindings.cpython-310-darwin.so'
  Reason: tried: '/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/libmambapy/../../../libsolv.1.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/opt/homebrew/Caskroom/mambaforge/base/lib/python3.10/site-packages/libmambapy/../../../libsolv.1.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/opt/homebrew/Caskroom/mambaforge/base/bin/../lib/libsolv.1.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/opt/homebrew/Caskroom/mambaforge/base/bin/../lib/libsolv.1.dylib' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))), '/usr/local/lib/libsolv.1.dylib' (no such file), '/usr/lib/libsolv.1.dylib' (no such file)
```

Is it possible that rust changed something there messing up mamba? I don't understand enough about how mamba works to be able to debug this on my own.

I have rosetta activated and use some intel environments - but the base environment uses arm.

This is my `$PATH`: `/opt/homebrew/Caskroom/mambaforge/base/bin:/opt/homebrew/Caskroom/mambaforge/base/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/corneliusromer/.cargo/bin:/opt/homebrew/opt/fzf/bin`

Any idea what's going on? Thanks a lot!

**Comment by wolfv** [comment]
@corneliusroemer it does look like such a situation to me. sorry about that, but not much we can do here I think!

**Comment by corneliusroemer** [comment]
@wolfv hmm I don't think I did something totally crazy so would he good to at east warn users once we figure out how that happened.

Have you got an idea for how I can get it working again?

I can't even export the envs I think as it's totally broken.

Maybe get conda conda somehow?

I should condaify mamba? Conda should work.

Btw, fat Mac libraries could solve the problem above?

Can I get the dylib executable from somewhere?

**Comment by isuruf** [comment]
@wolfv, mamba could disallow installing packages from two subdirs  (except for noarch) in the same environment unless some flag is set.

**Comment by corneliusroemer** [comment]
I've just encountered this same error again. Back when I opened this issue I did a clean reinstall since I didn't know better how to solve.

But now I've found a much less painful way:
```
conda activate base
micromamba remove python 
micromamba install python mamba
```

This did it for me after I had inadvertently switched Python from arm -> osx without switching arch of libmambapy (this is what the error above seems to refer to)

I'll close this as I now know where the error came from (switching Python architecture without switching mamba architecture)
