### ISSUE TITLE
Mamba not installing packages? Says: nothing provides requested

### ISSUE THREAD

**Issue by mwersebe** [mamba-org/mamba#1901]
Hi All, 

I am bit confused. I am trying to set up an environment using a brand new install of Mamba on a new Apple computer with an M1 chip. A lot of software that I use day to day returns "nothing provides requested." Again this a brand new install of Mamba. 

For instance, bcftools, whenI run:

`mamba install -c bioconda bcftools `

returns this:
```


                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.25.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['bcftools']

bioconda/osx-arm64                                          Using cache
bioconda/noarch                                             Using cache
conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
Encountered problems while solving:
  - nothing provides requested bcftools

```

Any Ideas how to fix this? 

Interesting, I was able to install "sourmash." But this was just a random software.

**Comment by jonashaag** [comment]
There simply is no build for M1 of that package. See eg the package in conda-forge (I’m not familiar with the bioconda channel): https://anaconda.org/bioconda/bcftools

You can install a x86 version of Conda and use macOS’ x86 translation layer Rosetta.

**Comment by jonashaag** [comment]
![B8674EF2-86ED-4948-A929-85A2A565CCFC](https://user-images.githubusercontent.com/175722/188332723-9516ad2b-4ae5-44c5-a3e9-fcad3f1a4bd8.jpeg)

**Comment by venkatasg** [comment]
Is there anyway to use the arm64 version of mamba, while creating x86 environments? I believe this was possible with anaconda using a command like `conda env config vars set CONDA_SUBDIR=osx-64` when creating the environment.

**Comment by jonashaag** [comment]
Yes use `--platform`
