### ISSUE TITLE
manually add conda json files 

### ISSUE THREAD

**Issue by Axolotl233** [mamba-org/mamba#1902]
Hi community,

I've been using micromamba for a month, and it's a wonderful tool, but here i meet a question.

I have frequent failures when updating conda cache files due to network reasons, is there have a way that add json file manually to micromanba cache, i can download json files in personal computer.

Thanks,
Nemo

**Comment by jonashaag** [comment]
If you have problems with those downloads, don’t you also have problems with the package downloads?

**Comment by Axolotl233** [comment]
> If you have problems with those downloads, don’t you also have problems with the package downloads?

no, the packages download has been fine... of course it maybe 'illusion' because package download only start after json updated.

so i have other question, if there any possible add conda mirrors site to instead default chanel, it seemly more friendly for chinese user

**Comment by jonashaag** [comment]
I foudn this, not sure if it works https://github.com/vra/mirrors-china#anaconda-包加速

If you're using conda-forge then there seems to be https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge  as well.

**Comment by jonashaag** [comment]
yep

**Comment by Axolotl233** [comment]
it is work, thank you
now you can close this issue~

**Comment by Axolotl233** [comment]
hi, sorry for reopening this issue,

here i get errors when i config the conda source as you suggested, the message is `SSL peer certificate or SSH remote key was not OK`  when load json file.

I have tested that miniconda is normally working when using these mirrors, so how to fix it with micromamba?

Thanks,
Nemo

**Comment by jonashaag** [comment]
Can you please make a new issue for this, using the issue template?
