### ISSUE TITLE
The mamba initialize block gets written to `.bashrc` on Ubuntu and to `.bash_profile` on Windows + macOS

### ISSUE THREAD

**Issue by pavelzw** [mamba-org/mamba#1913]
The `# >>> mamba initialize >>>` block gets written to `.bashrc` on Ubuntu and to `.bash_profile` on Windows + macOS when executing `micromamba shell init`. This probably has something to do with how it was done [at Anaconda](https://github.com/conda/conda/blob/0dbf85e0546e0b0dc060c8265ec936591ccbe980/conda/core/initialize.py#L439). Let's look into why this was done that way. 

For `micromamba`, we could maybe simplify it, too, since the goal is not to have a drop-in replacement like with `mamba`.

Fun fact: For `zsh`, it gets written into the `.zshrc` for all systems, not `.zprofile` on macOS.

**Comment by jonashaag** [comment]
I asked in the Conda Slack a few days ago. Got no answer. Someone suggested we open an issue in conda/conda (with the "feature request" template) to discuss this. Feel free to do it, otherwise I'll do it next week.

**Comment by pavelzw** [comment]
Okay here is a small git blame timeline:

This is now:
```py
bashrc_path = expand(join('~', '.bash_profile' if (on_mac or on_win) else '.bashrc'))
```

This was done by [ce821aca](https://github.com/conda/conda/commit/ce821aca18856e689b695db31c737b4ea65ed06e) in order to support MSYS2 on Windows. 

It looked like this before (in `initialize.py`):
```py
bashrc_path = expand(join('~', '.bash_profile' if on_mac else '.bashrc'))
```

Before that, the same line was found in `main_initialize.py` ([34744e8c](https://github.com/conda/conda/commit/34744e8c17903c6da4cf23dc432b7f686353c4b2))

And this is the initial state which was added by [21b57d59](https://github.com/conda/conda/commit/21b57d5913e1ecaaebea51fbec5759d30ef353db).

**Comment by pavelzw** [comment]
@jonashaag 
> Feel free to do it

Done, [conda/conda#11830](https://github.com/conda/conda/issues/11830).

**Comment by jonashaag** [comment]
https://github.com/conda/conda/pull/11849
