### ISSUE TITLE
Support shell init for `tcsh`

### ISSUE THREAD

**Issue by pavelzw** [mamba-org/mamba#1914]
For real™ feature parity with conda, we would also need to support shell initialization for `tcsh`, see [here](https://github.com/conda/conda/blob/0dbf85e0546e0b0dc060c8265ec936591ccbe980/conda/core/initialize.py#L524-L534).

**Comment by AntoinePrv** [comment]
Hi @pavelzw I think this is supported today with micromamba? Or am I missing something?
