### ISSUE TITLE
Cannot import name 'mamba_api' from 'mamba'

### ISSUE THREAD

**Issue by davidbrochart** [mamba-org/mamba#1918]
From [the documentation](https://mamba.readthedocs.io/en/latest/python_api.html#using-internal-mamba-apis): "you can import the mamba_api using `from mamba import mamba_api`".
But using mamba v0.25.0:
```py
>>> from mamba import mamba_api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'mamba_api' from 'mamba' (/home/david/mambaforge/lib/python3.10/site-packages/mamba/__init__.py)
```

**Comment by wolfv** [comment]
Did you check what's in thsi folder? `/home/david/mambaforge/lib/python3.10/site-packages/mamba/` -- are we missing to install something or are the docs wrong?

**Comment by davidbrochart** [comment]
There is a `api.py` file, with `install` and `create` functions, which corresponds to the [high-level Python API](https://mamba.readthedocs.io/en/latest/python_api.html#high-level-python-api).
But the internal mamba APIs don't seem to be there (no `mamba_api` in `__init__.py` file).

**Comment by jjerphan** [comment]
Closing as irrelevant for 2.0 since `mamba` is not a namespace anymore (`libmambapy` still is present). Feel free to reopen if you still have problems, David. :slightly_smiling_face:
