### ISSUE TITLE
Installing mamba from PyPI

### ISSUE THREAD

**Issue by davidbrochart** [mamba-org/mamba#1920]
We can currently install mamba with `conda install mamba` or `mamba install mamba`. But is there anything preventing to build wheels and be able to `pip install mamba`?

**Comment by aplowman** [comment]
I tried installing mamba from this repository via:

```
pip install "git+https://github.com/mamba-org/mamba.git#egg=mamba&subdirectory=mamba"
```

and get this error:
```
ERROR: Could not find a version that satisfies the requirement conda>=4.14.0 (from mamba) (from versions: 3.0.6, 3.5.0, 3.7.0, 3.17.0, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.7, 4.0.8, 4.0.9, 4.1.2, 4.1.6, 4.2.6, 4.2.7, 4.3.13, 4.3.16)
ERROR: No matching distribution found for conda>=4.14.0
```

I think conda is not published to PyPI, which would be a prerequisite for publishing mamba to PyPI I guess?

**Comment by jonashaag** [comment]
Are you using a very old version of Python?

**Comment by aplowman** [comment]
> pip install "git+https://github.com/mamba-org/mamba.git#egg=mamba&subdirectory=mamba"

No, Python 3.11.3 on Windows.

**Comment by jjerphan** [comment]
Installing mamba from PyPI would be an anti-pattern: we recommend installing component of mamba (as a framework) from conda-forge.
