### ISSUE TITLE
Change version name for CI builds of `micromamba`

### ISSUE THREAD

**Issue by pavelzw** [mamba-org/mamba#1929]
It would be nice for the `micromamba` CI builds to have a custom version name instead of `0.25.1`.

Some suggestions for names:
- `nightly-yyyy-mm-dd`
- `nightly-yyyy-mm-dd-hh:mm`
- `nightly-sha-<commit-sha>`
- `nightly-<commit-run-id>` (the number in `https://github.com/mamba-org/mamba/actions/runs/<commit-run-id>`)

Other suggestions are welcome :)

**Comment by jonashaag** [comment]
Since they are not actually “nightlies” I think we should just have the commit SHA. How are other projects doing the naming?

We can include the SHA somewhere in the `—-version` information for releases as well!
