### ISSUE TITLE
Cache failing for fully static Windows CI builds for `micromamba`

### ISSUE THREAD

**Issue by pavelzw** [mamba-org/mamba#1930]
Investigate this:

![image](https://user-images.githubusercontent.com/29506042/190518233-c56071f7-85cb-4298-bee3-6d612c97d890.png)

This was in [this](https://github.com/mamba-org/mamba/actions/runs/3061265445) CI run but always happens when the Windows static build pipeline steps get executed (at least the `Saving cache failed` part... the `Failed to restore` part does not happen always, see [here](https://github.com/mamba-org/mamba/actions/runs/3016452320)).

Maybe if the caching works correctly, we could reactivate the Windows CI builds for every CI run if they are fast enough.

**Comment by jonashaag** [comment]
https://github.com/hendrikmuhs/ccache-action/issues/100?
