### ISSUE TITLE
[micromamba] `package compress` does not include symlinks to directories

### ISSUE THREAD

**Issue by romain-intel** [mamba-org/mamba#1932]
It seems that `package compress` does not include links to directories in the archive.

To reproduce:
 - create a directory containing (for example):
```
info/
  dir/
    baz
  ln_dir -> dir/
  foo
```
- From the directory containing `info`, run `micromamba package compress . foo.conda` or `micromamba package compress . ../foo.tar.bz2` (for some reason, for bz2, it doesn't work if you create in the same directory.
- Once compressed, extract the archive using `micromamba package extract`. Note that baz and foo are there but ln_dir is not.

I verified that `cph` for example does properly include the symlink to a directory. Other symlinks (to non directories) work fine.

This is with micromamba version 0.25.1.

**Comment by romain-intel** [comment]
Awesome. I'll give 0.26.0 a try. Thanks for fixing this so quickly!

**Comment by wolfv** [comment]
that would be great if you can try again. I noticed some other discrepancy though: conda internally sorts the archive entries so that `info/...` files comes first, and then sorted by size (smallest to largest). We do not do that yet, it would be nice, though.

**Comment by romain-intel** [comment]
Hello. Apologies for taking so long to get back to this. I was pulled away on some other project and just recently came back to this. At any rate. I did test this with 0.26.0, 0.27.0 and 1.0.0 and all still seem broken. I used the test case in my original message and verified that compress/extract does keep the empty symlink to a directory and transmute similarly does not work (the context for where this comes up is that I use micromamba to transmute packages and some, specifically ncurses, has directory symlinks). I can use cph for now so it is not a blocker but micromamba seems faster and does not create a bunch of temporary directories so would prefer to use micromamba if possible.

**Comment by wolfv** [comment]
This is hopefully even more fixed in #2177 

I'll also add a test (derived from conda-package-handling).

**Comment by romain-intel** [comment]
This is fixed in 1.2.0. Closing for now.

**Comment by wolfv** [comment]
Awesome! :)
