### ISSUE TITLE
`bash: __add_sys_prefix_to_path: command not found...` when running any `mamba` command

### ISSUE THREAD

**Issue by hermidalc** [mamba-org/mamba#1950]
With the latest mamba I'm suddenly getting `bash: __add_sys_prefix_to_path: command not found...` anytime I run any `mamba` command. Didn't used to happen

My setup:

```bash
# packages in environment at /home/hermidalc/soft/mambaforge:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
conda                     22.9.0          py310hff52083_0    conda-forge
conda-package-handling    1.9.0           py310h5764c6d_0    conda-forge
cryptography              37.0.4          py310h597c629_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libarchive                3.5.2                hb890918_3    conda-forge
libcurl                   7.83.1               h7bff187_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libmamba                  0.25.0               hd8a31e3_2    conda-forge
libmambapy                0.25.0          py310hab0e683_2    conda-forge
libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsolv                   0.7.22               h6239696_0    conda-forge
libsqlite                 3.39.3               h753d276_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libxml2                   2.9.14               h22db469_4    conda-forge
libzlib                   1.2.12               h166bdaf_3    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.25.0          py310hf87f941_2    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3           py310h5764c6d_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.6          h582c2e5_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
reproc                    14.2.3               h7f98852_0    conda-forge
reproc-cpp                14.2.3               h9c3ff4c_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
ruamel_yaml               0.15.80         py310h5764c6d_1007    conda-forge
setuptools                65.4.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
tzdata                    2022d                h191b570_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.7.0                h27087fc_1    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

**Comment by hermidalc** [comment]
> Hmm, I see that you've also update `conda` to the latest `22.9.0` release. It's possible that this has broken some things :/

I you download the latest Mambaforge, install it, then after `mamba update --all`, it results in the environment above with that version of `conda`

**Comment by wolfv** [comment]
Argh, so they changed quite a bit over here: https://github.com/conda/conda/pull/11666/files ... that means that mamba is not yet compatible with this version of conda, unfortunately.

**Comment by hermidalc** [comment]
> Argh, so they changed quite a bit over here: https://github.com/conda/conda/pull/11666/files ... that means that mamba is not yet compatible with this version of conda, unfortunately.

Thanks, I just downgraded it was fine, no biggie

**Comment by jonashaag** [comment]
Fixed in next release

**Comment by corneliusroemer** [comment]
What's the workaround @hermidalc? What's the command to downgrade what? That would be helpful, thanks!

**Comment by hermidalc** [comment]
> > What's the workaround @hermidalc? What's the command to downgrade what? That would be helpful, thanks!
> 
> Yes, after installing mamba downgrade conda to 4.14.0

And make sure not to upgrade it accidentally when running `mamba update --all`

**Comment by corneliusroemer** [comment]
Thanks @hermidalc, so this worked for me to get from 0.25.0 with conda 22.9.0 to mamba 0.27.0

> I had difficulties updating my environment from using mamba 0.25.0 to 0.27.0
> 
> This may have something to do with the temporary pinnings that were introduced because mamba 0.25.0 is incompatible with conda 22.9.0
> 
> Here is how I resolved it: 0. Activate base environment: `conda activate base`
> 
> 1. Downgrade conda to v4: `mamba install conda=4`
> 2. Update mamba: `mamba update mamba`
> 3. Update conda: `mamba update conda`
> 
> Not sure whether there's an easier way to do this, but this could help others who have the same issue I had, same as: #1950 #1969
https://github.com/mamba-org/mamba/issues/2003

**Comment by hermidalc** [comment]
> Thanks @hermidalc, so this worked for me to get from 0.25.0 with conda 22.9.0 to mamba 0.27.0, see https://github.com/mamba-org/mamba/issues/2003
> 
> 
> 
> > I had difficulties updating my environment from using mamba 0.25.0 to 0.27.0
> 
> > 
> 
> > This may have something to do with the temporary pinnings that were introduced because mamba 0.25.0 is incompatible with conda 22.9.0
> 
> > 
> 
> > Here is how I resolved it: 0. Activate base environment: `conda activate base`
> 
> > 
> 
> > 1. Downgrade conda to v4: `mamba install conda=4`
> 
> > 2. Update mamba: `mamba update mamba`
> 
> > 3. Update conda: `mamba update conda`
> 
> > 
> 
> > Not sure whether there's an easier way to do this, but this could help others who have the same issue I had, same as: #1950 #1969
> 
> 

Ok thanks, so the fixed mamba got released. I haven't upgraded yet still on 0.25.0

**Comment by corneliusroemer** [comment]
Yeah this was confusing, and somehow it didn't work to just `mamba update --all`, that yielded me conda 22.9.0 again, something fishy going on. I hope my workaround is reproducible!
