### ISSUE TITLE
Add `micromamba enter` to open a new subshell in an environment

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#1959]
Something like

```
micromamba enter myenv
```

that's more or less

```
micromamba run -n myenv $SHELL
```

Other name suggestions?

**Comment by baszalmstra** [comment]
Yes please! I prefer shell too because its used in other tools as well (nix, poetry, ..)

**Comment by jonashaag** [comment]
I didn't want to suggest `shell` because I was worried it's too confusing to have `shell init` and `shell`, which are somewhat related but still very different

**Comment by wolfv** [comment]
Indeed, that's unfortunate.

**Comment by baszalmstra** [comment]
Mm very unfortunate

**Comment by wholtz** [comment]
The default command for `micromamba run` to execute could be `$SHELL`. Currently there is not a default.

**Comment by jonashaag** [comment]
We have this now with `micromamba shell` :)
