### ISSUE TITLE
command not found: __add_sys_prefix_to_path

### ISSUE THREAD

**Issue by ivaquero** [mamba-org/mamba#1969]
Hi, I came across an error msg after I update conda to 22.9.0

```console
mamba update --all

mamba:14: command not found: __add_sys_prefix_to_path
```

Though it doesn't affect anything, I would like to know how to solve this.

OS: macOS 12.6 Monterry M1
Mamba Version: 0.25.0
Python Version: 3.10.6

**Comment by jonashaag** [comment]
#1950

**Comment by corneliusroemer** [comment]
Got the same error, could you add the tile to include `mamba:14:` so that it's easier to find this issue with the exact same versions as you.
