### ISSUE TITLE
Download large files first

### ISSUE THREAD

**Issue by wholtz** [mamba-org/mamba#1971]
In #1944 @shughes-uk suggested that large packages should be first in the download queue. I thought this was a worthwhile suggestion to consider and didn't want the idea to get lost with #1944 (correctly) closing.

**Comment by wolfv** [comment]
I think we're already doing this 

https://github.com/mamba-org/mamba/blob/25be29a831f9012b8eb891f218860d549d549819/libmamba/src/core/transaction.cpp#L1223
