### ISSUE TITLE
Nothing happens when running mamba

### ISSUE THREAD

**Issue by radioflyer28** [mamba-org/mamba#1972]
Like the title says, any mamba command combination returns to a new shell.

Versions:
- Windows 10
- Mamba 0.26.0
- Conda 22.9.0

Steps to reproduce above env, a fresh install of Miniconda and Mamba:
1. Install latest stable Miniconda3 (64bit) on Windows 10 via exe
2. Update conda `conda update -n base -c defaults conda`
3. Add conda-forge repo `conda config --add channels conda-forge` & `conda config --set channel_priority strict`
4. Make conda and pip play nice `conda config --set pip_interop_enabled True`
5. Install Mamba `conda install mamba -n base -c conda-forge`

**Comment by wolfv** [comment]
@radioflyer28 thanks for the report. Are you on cmd.exe or powershell?

**Comment by wolfv** [comment]
I just tried followign your steps, and it seems to work for me. Did you run the `conda init` and `mamba init` stuff and activated your environment?

**Comment by radioflyer28** [comment]
I was running from the Powershell shortcut that Miniconda made, so it was already starting inside the base environment and I didn't need to init or activate.

I discovered the issue was with Miniconda adding a registry entry key `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor\AutoRun` whose value used an if statement that started `conda_hook.bat` (I wish I copied down the exact value). Deleting this AutoRun key fixed it...
