### ISSUE TITLE
Micromamba 0.26.0 fails on OSX Mojave 10.14

### ISSUE THREAD

**Issue by ndevenish** [mamba-org/mamba#1980]
New versions of micromamba pulled from `https://micro.mamba.pm/api/micromamba/osx-64/latest` on our older CI machine:
```
$ ./micromamba
dyld: Symbol not found: __ZNSt3__14__fs10filesystem16filesystem_errorD1Ev
  Referenced from: /Users/scisoft/t/bin/./micromamba
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/scisoft/t/bin/./micromamba
Abort trap: 6
```
I couldn't see any notes on expected platform support or older platforms being dropped. Is this just too old now?

**Comment by jonashaag** [comment]
I'm not sure if we should continue to support old versions of macOS if it requires a lot of effort from our side. With old macOS versions you'll soon be unable to use most of the development software in the first place. Ecosystem support of old macOS releases is much worse than of old Linux distro versions.

**Comment by ndevenish** [comment]
I'm somewhat sympathetic to that point of view; If the conclusion of this is a deliberate decision to not support, then that's something we just have to work with (and probably forces our deliberately-old-CI-machine policy to update - "Oh No"). I'd just personally have a preference for it to be noted as a platform drop, rather than a mystery surprise :)

**Comment by wolfv** [comment]
Thanks for chiming in! 

There are two ways to continue supporting older macOS versions:

- Add back `ghc-filesystem` and allow usage of it via some compile-time flag that we activate for macOS builds
- Figure out if we can statically link the necessary parts of the OSX SDK

Both options require some dev time, but it should be doable with a reasonable effort.

One argument to keep supporting old macOS versions is that Miniforge / Mambaforge uses `micromamba` and we need to align with conda-forge here.
