### ISSUE TITLE
`warning  libmamba Could not create proc dir`

### ISSUE THREAD

**Issue by wholtz** [mamba-org/mamba#1981]
Transfering [mamba-org/micromamba-docker issue #215](https://github.com/mamba-org/micromamba-docker/issues/215) to here.

@shughes-uk reported 

> Using 0.26.0 I see this when using `micromamba run`
> 
> ```
> libmamba Could not create proc dir: "/home/mambauser/.mamba/proc"
> ```

I am able to reproduce this on macOS (v12.6) without using docker:
```bash
$ ./micromamba run /bin/bash
warning  libmamba Could not create proc dir: "/Users/MyUserID/.mamba/proc"
$ 
```

Probably related to #1979 and #1975.

**Comment by jonashaag** [comment]
I have this as well

**Comment by wolfv** [comment]
Thanks for the report! The `run` functionality seems to work though. I'll have a look right now, but might only be able to fix it by tomorrow morning.
