### ISSUE TITLE
libmambaapy external spdlog header

### ISSUE THREAD

**Issue by gdolle** [mamba-org/mamba#1986]
It seems this issue https://github.com/mamba-org/mamba/issues/1694 camed back for libmambaapy in release 0.26, 
https://github.com/mamba-org/mamba/blob/898262552790d448d19463245ba170d96c24e1f7/libmambapy/src/main.cpp#L12

PS: spdlog/spdlog.h should be used instead (or `spdlog/tweakme.h` before `spdlog/fmt`) and add a cmake rule, cf. here https://github.com/mamba-org/mamba/blob/898262552790d448d19463245ba170d96c24e1f7/micromamba/CMakeLists.txt#L70-L78

**Comment by jonashaag** [comment]
Sorry for that. Would you mind fixing it again and adding a pre-commit linting (or a test) step to avoid this in the future?

**Comment by wolfv** [comment]
@gdolle if you can review this PR https://github.com/mamba-org/mamba/pull/1987 asap, we can release it today.
