### ISSUE TITLE
Conda vs mamba activate and deactivate

### ISSUE THREAD

**Issue by jorgsk** [mamba-org/mamba#1994]
The mamba [documentation](https://mamba.readthedocs.io/en/latest/user_guide/mamba.html) gives a warning that that conda should be used for activation and deactivation. I've tried to find out why but I haven't found the reason why this is. It could be nice to mention the reason why together with the warning.

However, after creating an environment with mamba, the following message is printed to screen:

```
To activate this environment, use

     $ mamba activate era_acute_post_processor

To deactivate an active environment, use

     $ mamba deactivate
```

It seems that an updated is needed in either place, depending on which is right. Does anyone know what is the current best practise?

**Comment by wolfv** [comment]
Indeed, we added the `mamba activate ...` capability later, so this part of the documentation is probably misleading and a leftover. 
However, we have not implemented `mamba activate` for all shells. Most notably, we have not yet implemented it on PowerShell ... if you want to help there, that would be awesome!

**Comment by jorgsk** [comment]
OK, good to know! That task is probably beyond me - but I can make a PR for a change to the docs by adding the information you wrote, and noting that it works with Bash.

**Comment by jonashaag** [comment]
@jorgsk that would be great!

**Comment by cdeepali** [comment]
@jonashaag, shall I work on updating the docs for this as I see that documents are yet to be updated.

**Comment by cdeepali** [comment]
I've added a PR - https://github.com/mamba-org/mamba/pull/2176.  Please let me know your views on it.

**Comment by jjerphan** [comment]
conda, mamba and micromamba can now be used to activate and deactivate environment.
