### ISSUE TITLE
mamba v0.27.0 update will hide hostname

### ISSUE THREAD

**Issue by jase11** [mamba-org/mamba#1995]
After I update mamba from version 0.25.0 to 0.27.0, the hostname in the terminal cannot be displayed.

Before update:
<img width="680" alt="ConEmu64_EKC8DeJwxI" src="https://user-images.githubusercontent.com/27488572/194551460-a43f770b-01c5-4b6f-a2d1-367de110eeef.png">

After update:
<img width="698" alt="ConEmu64_juqFTYTqQN" src="https://user-images.githubusercontent.com/27488572/194551115-2d9378fe-479e-4ad4-8f41-3eaac81e9165.png">

**Comment by wolfv** [comment]
Could this be related to https://github.com/conda/conda/issues/11893 and https://github.com/conda/conda/issues/11942 ?

**Comment by jase11** [comment]
Thanks for your immediate reply. I'm glad to see that someone has noticed this before.

**Comment by hermidalc** [comment]
I'm seeing the similar thing since trying 0.27.0, after you run `mamba activate <...>` my entire bash prompt with disappear, no only that when I then run `mamba deactivate` it hangs the shell and even with Ctrl+C I cannot get out of it. I'm on Fedora 36

**Comment by loodvn** [comment]
And the fix for completeness: https://github.com/conda/conda/issues/11885#issuecomment-1259519190 
``` try running conda init bash and then restarting your shell and see if that fixes it?```

**Comment by jase11** [comment]
> try running `conda init bash` and then restarting your shell and see if that fixes it?

Yes, it works.

**Comment by wolfv** [comment]
Closing as this is a conda issue that has been fixed.
