### ISSUE TITLE
Consider adding an optional Cargo like experience

### ISSUE THREAD

**Issue by certik** [mamba-org/mamba#200]
This is a bit relevant to our recent discussion here: https://github.com/j3-fortran/fortran_proposals/issues/55#issuecomment-622974918, but separate. 

Right now when developing a new Python package using Conda, you have to create a Conda environment and enable it, for example:
```
conda create -n dev toml
conda activate dev
```
and you have to do `conda activate dev` every time you open a new terminal and want to do any work on your new package. 

Rather, I really like how Rust handles this exact problem, and we are developing the same workflow for Fortran, but it would also work for Python and I think Mamba is a great candidate to provide such an interface. The closest tool in Python that allows such a workflow is [Poetry](https://github.com/python-poetry/poetry), however it fails to easily switch Python versions (https://github.com/python-poetry/poetry/issues/2382) and overall seems fragile so far, but the high level idea I think is correct. 

The workflow for Python would be:
```
$ mamba new mypkg
$ cd mypkg
$ tree
.
├── Mamba.toml
└── src
    └── main.py

1 directory, 2 files
$ mamba build
```
The last command installs all the dependencies as specified in `Mamba.toml` using Conda, but does not require you to manually load any environment (it does it behind the scene).
Then this runs the application in `src/main.py`:
```
$ mamba run
...
Hello, world!
```
The actual layout should probably be modified to be compatible with the Python packaging layout, but you get the idea. The way this works is that it runs the app in a Conda environment, but behind the scene, so you never have to manually load anything. 

Then of course:
```
$ mamba test
```
will run tests, say using pytest or unittests (configurable). 

`mamba publish` would create a pypi package out of this and allow to upload it.

See how Cargo in Rust does it. This could really help making Python development very robust.

**Comment by wolfv** [comment]
hey @certik,
thanks for getting back to this! 

It totally sounds like a great idea. I understand that having this kind of workflow would be very nice. My colleague @martinRenou recently added some bash foo that adds a specific command (e.g.`cmd xeus`) that will jump to the xeus folder and activate the xeus conda environment.

None of what you are saying is impossible, I think it would require minimal glue on top of mamba :) We're currently pushing very hard on getting rid of the remaining Python code (locally I have a small C++ file that exposes a minimal CLI to create new conda environments without any "conda / Python".
This works fine for UNIX so far, Windows will need a couple of changes to properly work but it's well within reach (probably lands within this week).

Are you interested in collaborating for this so we can use `mamba` for Fortran? I am convinced this would be the ideal tool for you guys and if it's not I am happy to help 100%.

Making `mamba-build` (a fast `conda-build`) is a top priority for me and we already have a couple of the important pieces for that.

**Comment by dhirschfeld** [comment]
With conda, creating a dev env is a bit of a process:
```
conda install -n mypkg-dev mypkg --only-deps
conda activate mypkg
cd mypkg
pip install --no-deps -e .
```

IIUC the install command will only use the deps from a published package rather than a `meta.yaml`. I did suggest allowing to use a `meta.yaml` over in https://github.com/conda/conda/issues/7248#issuecomment-491112938 but it probably got lost in the noise. I still think that would be a very useful feature.

In that issue, automatically activating the environment when `cd`'ing to a folder was also discussed but I don't personally find it too much of a burden to manually activate an env... and I've no idea how you could even implement that feature!

**Comment by certik** [comment]
I strongly recommend that you play with Cargo and Rust just a little bit, to get what I am talking about. It's hard to explain beyond what I tried above, but the end user development experience is miles ahead of Python. 

I think we can catch up, but we need to first understand what the goal is. Currently all Python efforts in this area feel like just fixing the biggest issues and calling it good enough. It might be easier to do a video chat to explain it.

**Comment by LeslieGerman** [comment]
Just my 2 cents:

Maybe you should try [conda-devenv](https://github.com/ESSS/conda-devenv) and/or [direnv](https://github.com/direnv/direnv), even [with conda](https://github.com/direnv/direnv/issues/326#issuecomment-574779485).

**Comment by jonashaag** [comment]
There is https://github.com/prefix-dev/pixi now

**Comment by certik** [comment]
I see that @wolfv has fixed this issue with pixi! Great job. I played with pixi, and I think it does it exactly as I was imagining. Better in fact, as above I was still thinking of specific to C++ or specific to Python, and pixi does it for both.
