### ISSUE TITLE
"mamba init" command not working. Required to install MOOSE. Please help.

### ISSUE THREAD

**Issue by subhomoy2002** [mamba-org/mamba#2000]
I am trying to download a software called MOOSE using the instructions given on this link https://mooseframework.inl.gov/getting_started/installation/conda.html.
But, as soon as I reach the command "mamba init", I am getting the following error provided in the screen shot below.
![Screenshot of mamba command error](https://user-images.githubusercontent.com/111292429/194742791-37e3883e-aa2d-4f36-af2b-8e9a86eaed54.png)
Please help me to resolve this issue.

**Comment by wolfv** [comment]
maybe you only installed `conda`? Can you try `conda install mamba -c conda-forge`?

**Comment by jonashaag** [comment]
The tutorial says to install Mambaforge so I guess they have it installed. Maybe something wrong with shell setup.

**Comment by jonashaag** [comment]
@subhomoy2002 if you don't make any progress, consider trying out Micromamba instead of Mamba(forge): https://mamba.readthedocs.io/en/latest/installation.html#micromamba

**Comment by subhomoy2002** [comment]
> The tutorial says to install Mambaforge so I guess they have it installed. Maybe something wrong with shell setup.

Can you please elaborate on what kind of issues in shell setup can yield this error?

**Comment by jonashaag** [comment]
Lots :D Can you please share the output of `echo $PATH` and `which conda`

**Comment by jonashaag** [comment]
Otherwise, since you already have a working Conda setup, you can simply use the Mamba solver with Conda, which should give the most important speedups that Mamba has over Conda: https://github.com/conda-incubator/conda-libmamba-solver#getting-started

Or just use Micromamba.
