### ISSUE TITLE
[micromamba] bug in solver? installing wrong jupyterlab version

### ISSUE THREAD

**Issue by jamestwebber** [mamba-org/mamba#2017]
Spent a solid amount of time debugging my docker container before I realized that somehow, `micromamba` installed jupyterlab `2.1.0` instead the most recent version. When asked it will installed `3.4` no problem but for some reason if given no guidance it will install the old version.

Steps to reproduce:

```
docker run -it --rm mambaorg/micromamba bash
micromamba install python pip jupyterlab  # will attempt to install jupyterlab=2.1.0
```

I assume this is a bug in the solver, I can't imagine why this would be desired behavior?

**Comment by jamestwebber** [comment]
I guess this is a dupe of https://github.com/mamba-org/mamba/issues/1581

**Comment by jonashaag** [comment]
Probably!
