### ISSUE TITLE
[Bug] Why mamba can't run in my conda env?

### ISSUE THREAD

**Issue by forestbat** [mamba-org/mamba#2018]
I renamed my conda env, and then when I run mamba commands such as `mamba -h`, cmd and pwsh tells me:
```
(my1stconda) PS C:\Users\UserName\IdeaProjects\hydro-lstm-test> mamba -h
系统无法执行指定的程序。(System can't execute appointed program.)
```
However，when I run mamba commands in anaconda prompt，it is normal：
```
(my1stconda) C:\Users\UserName>mamba --h
menuinst called from non-root env C:\ProgramData\Anaconda3\envs\my1stconda
usage: mamba [-h] [-V] command ...

conda is a tool for managing and deploying applications, environments and packages.

Options:

positional arguments:
  command
    clean        Remove unused packages and caches.
    compare      Compare packages between conda environments.
    config       Modify configuration values in .condarc. This is modeled after the git config command. Writes to the
                 user .condarc file (C:\Users\k6789\.condarc) by default.
    create       Create a new conda environment from a list of specified packages.
    info         Display information about current conda install.
    init         Initialize conda for shell interaction.
    install      Installs a list of packages into a specified conda environment.
    list         List linked packages in a conda environment.
    package      Low-level conda package utility. (EXPERIMENTAL)
    remove       Remove a list of packages from a specified conda environment.
    rename       Renames an existing environment
    run          Run an executable in a conda environment.
    search       Search for packages and display associated information. The input is a MatchSpec, a query language
                 for conda packages. See examples below.
    uninstall    Alias for conda remove.
    update       Updates conda packages to the latest compatible version.
    upgrade      Alias for conda update.
    notices      Retrieves latest channel notifications.
    repoquery    Query repositories using mamba.

options:
  -h, --help     Show this help message and exit.
  -V, --version  Show the conda version number and exit.
```

And even if I reinstalled mamba，the problem still exists.
How to solve it？

**Comment by jonashaag** [comment]
Do you have Mamba installed in another env than `base`? That's not recommended.

**Comment by forestbat** [comment]
> Do you have Mamba installed in another env than `base`? That's not recommended.

Mamba works normally before I rename my conda env.

Why should someone install mamba in `base` env？

**Comment by jonashaag** [comment]
https://mamba.readthedocs.io/en/latest/installation.html#existing-conda-install

> To get mamba, just install it into the base environment

**Comment by forestbat** [comment]
> https://mamba.readthedocs.io/en/latest/installation.html#existing-conda-install
> 
> > To get mamba, just install it into the base environment

Now I try to install mamba to base environment, however it still crashed:
```
PS C:\Users\UserName> conda install mamba
Collecting package metadata (current_repodata.json): done
Solving environment: |
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:
……
Downloading and Extracting Packages
……
Verifying transaction: failed

RemoveError: 'requests' is a dependency of conda and cannot be removed from
conda's operating environment.
```
How to resolve this?

**Comment by jonashaag** [comment]
Not sure what's your environment's state. Maybe it's best to start from a fresh Mambaforge install.

**Comment by forestbat** [comment]
> Not sure what's your environment's state. Maybe it's best to start from a fresh Mambaforge install.

I downloaded `Mambaforge-Windows-x86_64.exe` and installed it, however it still occured mistake:

```
(base) PS C:\Users\UserName> mamba -h
mamba : 无法将“mamba”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ mamba
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (mamba:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by jonashaag** [comment]
Hmm... can you plesae show `conda list -n base`

**Comment by jonashaag** [comment]
Sorry I don’t know either. Maybe this is using the environments again? Try removing the old stuff before installing Mambaforge. 

Or just use Micromamba which doesn’t have those problems :)

**Comment by forestbat** [comment]
> Sorry I don’t know either. It looks like this is using the old base environment again? It has a lot of stuff not shipped with Mambaforge. You should never install stuff into base except for Conda and Mamba. Try removing the old stuff before installing Mambaforge.
> 
> Or just use Micromamba which doesn’t have those problems :)

Ok, now I used micromamba to manage my packages. You can choose to close the issue or keep it open.
