### ISSUE TITLE
How to keep pybind11-stubgen stubs for libmambapy up to date

### ISSUE THREAD

**Issue by dholth** [mamba-org/mamba#2020]
https://github.com/mamba-org/mamba/pull/1983#issuecomment-1271589502

- build extension module
- run pybind11-stubgen against that module. Put these in build/stubs? for gitignore reasons?
- copy generated stubs over existing stubs (changing module name because we `import *` in Python)

**Comment by wolfv** [comment]
How about we add the stub-generation to one of the CI phases and check that the checked in stubs are up to date? If they are not, we will either ask the person that opened the PR to rerun `pybind11-stubgen` or run it ourselves.

**Comment by dholth** [comment]
I hope someone else will be able to follow these instructions to update the CI.

**Comment by wolfv** [comment]
Working on this in #2025

**Comment by wolfv** [comment]
We have an "OK" solution for this now :)
