### ISSUE TITLE
Why does mamba often redownload conda-forge/osx-64 channel index rather than checking/using cached version? 

### ISSUE THREAD

**Issue by corneliusroemer** [mamba-org/mamba#2021]
I'm using mamba 0.27.0 on an M1 mac.

I'm confused why mamba often seems to redownload the entire package index (~25MB) instead of simply checking whether there have been any changes, e.g. using etag or time of last modification.

Where can I read more about the package index cache, and how to configure it?

There seem to be 3 different modes:
1. Use cache
2. Download index and see whether there are changes

For some reason the index seems to be downloaded for certain channels but not for others. This is odd.

What's the difference between "Using cache" and "No change"? The operation leading to "No change" is slower, does this mean the whole index is redownloaded and compared, instead of using some faster way like a hash? How does "Using cache" work? Is there a time to live of the cache or do you check some hash every time?

<img width="900" alt="image" src="https://user-images.githubusercontent.com/25161793/195692360-5187af8c-9721-4a41-b9bf-41a1c35d7521.png">

It seems that some indexes are updated every few seconds, is that realistic? Or is it a bug in mamba and or the index server?

**Comment by jonashaag** [comment]
I‘m on mobile so pardon the short response:

IIUC there are 3 scenarios:

1. Local cache is up to date (has etag/whatever that’s recent enough) — no download
2. Local cache is not up to date, will check upstream and receive HTTP 304 — no download but we made an HTTp request 
3. Same as 2 but we actually have a newer package index. We need to download the entire index, unfortunately partial downloads are not yet implemented (although very much WIP)


If an index is downloaded every time it probably means it doesn’t send some HTTP headers relevant for caching.  

There is an option that I don’t remember right now that controls the maximum frequency for steps 2/3. I have it set to a couple of hours.

**Comment by corneliusroemer** [comment]
Thanks! What's the difference between 1. and 2.? In 1 you don't even make a request? How do you know that local cache is up to date then?

Could it be that the package index is faulty and updated too often despite no fundamental changes?

**Comment by jonashaag** [comment]
Yes essentially the HTTP cache headers say: don‘t check for changes in the next X seconds. Eg for conda-forge that would be something like 20 minutes because that‘s the frequency of their repodata updates. 

Then when you check for updates it might still be the case that there are none. You send the server your local cache‘s timestamp and it will respond with HTTP 304 „Not Modifies“. In that case we don‘t download and update anything but we still made the request. 

If the index has bad or no cache headers then Mamba will have to check every time you install anything. And/or if the server does not support responding with 304 then whenever Mamba makes a request it will have to perform a download.

**Comment by jonashaag** [comment]
xref https://github.com/mamba-org/mamba/issues/1504

**Comment by jonashaag** [comment]
Try this as a benchmark `curl https://conda.anaconda.org/bioconda/noarch/repodata.json >/dev/null`

**Comment by corneliusroemer** [comment]
Some more tests, it looks like it's mamba related?

<img width="1623" alt="image" src="https://user-images.githubusercontent.com/25161793/196199814-1d227fbf-e92f-44de-a535-1f04fc44eb20.png">

**Comment by jonashaag** [comment]
Hm, interesting. I think Mamba doesn't download the `bz2` but the "uncompressed" one (which uses HTTP gzip compression). And the 3.6 MiB file is too small for benchmarking. But the 180 MiB file seems large enough and indeed Mamba download performance is bad.

What's your `download_threads` setting?

What version of Mamba are you on? Can you try a newer/older one?

**Comment by corneliusroemer** [comment]
Aha, that may be it! It could be that the gzip compression takes time on the server!

Well the `conda-forge/osx-64` is 23.8 MB ;) that should be large enough.

mamba 0.27.0

Happy to try out lower/higher version. Can you reproduce? I'm happy to try out stuff but would be good to know whether this is just me.

How do I find download_threads? Couldn't find anything in docs and info etc.

**Comment by corneliusroemer** [comment]
Here osx-64, why don't you use .bz2?

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/25161793/196228645-70246fac-9456-4ed4-9314-ff13312d5a66.png">

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/25161793/196228656-86ae6fbf-622a-445b-9200-1fdc4911b77c.png">

**Comment by jonashaag** [comment]
> It could be that the gzip compression takes time on the server!

I don't think so, it's very likely pre-compressed

**Comment by corneliusroemer** [comment]
This is mamba 0.24, same thing, it's always been like this, always had to wait for a few seconds, up to 10 - just never really closely looked at _how_ slow it was (2.8MB/s)
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/25161793/196229246-5f791023-ab33-4ea5-ad09-e91adb9d534a.png">

nIs it just me? Can you not reproduce with `mamba clean -i; mamba update --all`

**Comment by jonashaag** [comment]
> Even the uncompressed is much faster:

I'm not sure you can compare this. Does curl report the speed relative to the compressed or uncompressed file size?

**Comment by corneliusroemer** [comment]
>I'm not sure you can compare this. Does curl report the speed relative to the compressed or uncompressed file size?

Probably the raw size. Even if not, it is definitely much faster. It takes only 3 seconds even if downloading uncompressed. Vs 10 seconds for mamba.

**Comment by jonashaag** [comment]
For me it's roughly the same _duration_ of download with curl and Mamba:

```
conda-forge/noarch                                   9.9MB @   3.7MB/s  3.0s
```

```
time curl https://conda.anaconda.org/conda-forge/noarch/repodata.json >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 67.8M  100 67.8M    0     0  27.0M      0  0:00:02  0:00:02 --:--:-- 27.1M

________________________________________________________
Executed in    2.52 secs      fish           external
```

Baseline:

```
curl https://speed.hetzner.de/100MB.bin > /dev/null
100  100M  100  100M    0     0  29.4M      0  0:00:03  0:00:03 --:--:-- 29.5M
```


The `.bz2` one seems be be MUCH faster with 0.5 s. Even if you add `| bunzip2` it's still only 1 s.

**Comment by jonashaag** [comment]
For `osx-64` curl reports the same download speed and it takes 6 s to download (via curl). With `bz2` it takes a little over 1 s via curl.

**Comment by jonashaag** [comment]
I guess it would be good to change to the `bz2` variant if it's available for a channel.

**Comment by corneliusroemer** [comment]
Right, so you can reproduce that mamba is very slow in downloading - or at least, it shows you download speed of compressed yet downloads at speed of uncompressed?). Maybe that's where the confusion comes in.

How exciting that we may have figured out a way to make mamba updates much faster 😄

**Comment by jonashaag** [comment]
> How do I find download_threads? Couldn't find anything in docs and info etc.

Yeah unfortunately not everything is documented yet. You can put it into your `.condarc`:

```
local_repodata_ttl: 10000  # don't update repodata if younger than ~3 h
download_threads: 5  # default
```

**Comment by jonashaag** [comment]
> it shows you download speed of compressed yet downloads at speed of uncompressed

Yeah that seems to be the key point here. Mamba and curl report different numbers. But the duration that's being reported seems accurate and similar to what curl reports.

**Comment by jonashaag** [comment]
Yeah we might want to consider increasing that number. It isn't actually the number of _threads_ (xref https://github.com/mamba-org/mamba/pull/1963) and the curl default is 50 if you use `curl --parallel`.

**Comment by wolfv** [comment]
Hmm, I always thought that Anaconda was somehow limiting the total download speed to ~3 Mb/s for repodata.json but maybe that isn't the case :)
Currently we're passing the supported compression schemes manually into libcurl. I wonder if this change could help: 

```
    curl_easy_setopt(
                m_handle, CURLOPT_ACCEPT_ENCODING, "gzip, deflate, compress, identity");
```

to 

```
            curl_easy_setopt(
                m_handle, CURLOPT_ACCEPT_ENCODING, "");
```

which will add all libcurl-supported encodings automatically. Don't really think it will change much though.

I am on not-great hotel wifi right now -- could someone compare:

```
curl --compressed https://conda.anaconda.org/conda-forge/noarch/repodata.json > /dev/null
# vs.
curl https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2 > /dev/null
```

I am not a big fan of the added complexity of using `bz2` encoded files and I also don't like `bz2` anymore (zstd would be cool!).

Also, the upcoming `jlap` format is going to make this much better for interactive / local use (incremental repodata patch updates). Implementation has been started here: https://github.com/mamba-org/mamba/pull/2029

The `.jlap` files are already available on the anaconda.org website: https://conda.anaconda.org/conda-forge/linux-64/repodata.jlap so hopefully we can try it soon :)

**Comment by jonashaag** [comment]
```
$ hyperfine -M 5 'curl https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2 > /dev/null'
Benchmark 1: curl https://conda.anaconda.org/conda-forge/noarch/repodata.json.bz2 > /dev/null
  Time (mean ± σ):     742.2 ms ± 226.6 ms    [User: 108.3 ms, System: 26.6 ms]
  Range (min … max):   496.5 ms … 1097.8 ms    5 runs

$ hyperfine -M 5 'curl --compressed https://conda.anaconda.org/conda-forge/noarch/repodata.json > /dev/null'
Benchmark 1: curl --compressed https://conda.anaconda.org/conda-forge/noarch/repodata.json > /dev/null
  Time (mean ± σ):      3.117 s ±  0.414 s    [User: 0.481 s, System: 0.109 s]
  Range (min … max):    2.523 s …  3.561 s    5 runs
```

**Comment by wolfv** [comment]
So at least it looks like it's not "mamba"'s fault :) It could be possible that the Anaconda CDN servers aren't caching the gzipped response and it's slowly encoded on the fly?! Or Anaconda could limit the bandwidth / speed on purpose for this file?! Idk

**Comment by jonashaag** [comment]
The `bz2` file is 10% smaller than the gzip compressed download, so that doesn't explain the 5x slowdown.

Also bandwidth doesn't seem to be limited:

```
Download of uncompressed json
100 67.9M  100 67.9M    0     0  22.8M      0  0:00:02  0:00:02 --:--:-- 22.8M
                                 ^^^^^ bandwidth
Download with --compressed
100 9682k    0 9682k    0     0  3285k      0 --:--:--  0:00:02 --:--:-- 3292k
                                 ^^^^^ bandwidth
```

**Comment by jonashaag** [comment]
> > It could be that the gzip compression takes time on the server!
> 
> I don't think so, it's very likely pre-compressed

This didn't age well @corneliusroemer. Another lesson in: Never make assumptions, and if you do, verify them.

**Comment by wolfv** [comment]
The conda slack or the infra repo under conda or conda-incubator

**Comment by corneliusroemer** [comment]
Sometimes not being a pro has advantages @jonashaag 

This does indeed look like a server issue - but why don't you just move to bz2?

**Comment by wolfv** [comment]
Yes, I think the `conda/infra` place would be ideal! :)

**Comment by corneliusroemer** [comment]
I've opened something here: https://github.com/conda/infra/issues/637

**Comment by wolfv** [comment]
I am going to close this for the moment. The repodata.zst support should land with the next release (optionally enable with `repodata_use_zst: true` in the `~/.condarc` file.

**Comment by corneliusroemer** [comment]
Great news :) Very happy to see that `zst` speedup landing in production soon. Well done @jonashaag @wolfv & co

**Comment by corneliusroemer** [comment]
As far as I'm aware, `repodata_use_zst` only works with `micromamba` for now - not with mamba. Is that correct?

Do you plan on including it in `mamba` at some point? @jonashaag @wolfv
