### ISSUE TITLE
Mamba Warning after Installation

### ISSUE THREAD

**Issue by MichWeb75** [mamba-org/mamba#2030]
Hi,
I tried to install mamba v0.27 into a preconfigured mamba v0.25 mamba forge installation. It does not work, but after removal I get the following error :  Each time I call mamba --version

bash: __add_sys_prefix_to_path: Command not found

Which script is causing the command not found warning ?

Best,
Michael

**Comment by jonashaag** [comment]
https://github.com/mamba-org/mamba/issues/1950
