### ISSUE TITLE
Mamba v0.27.0 on Windows 10 has a tendency to die suddenly 

### ISSUE THREAD

**Issue by DManowitz** [mamba-org/mamba#2032]
When downloading a large install (say, >50 packages), mamba v0.27.0 on my Windows 10 machine has a tendency to die suddenly during download and/or extraction of packages.  I do not see this behavior with mamba v0.25.0 (and I haven't tried 0.26.0 yet).

This behavior should be evident when installing a package with many dependencies, such as geoviews, spyder, or anaconda.

**Comment by jonashaag** [comment]
Can you please monitor memory usage during the installation?

**Comment by DManowitz** [comment]
I upgraded to mamba v1.1.0, and recently it just died while decompressing files after the download had completed.  Not that many files had been downloaded.  I did not have a chance to monitor memory usage.

**Comment by jonashaag** [comment]
You might want to reduce the number of download/extract threads (in condarc)

**Comment by DManowitz** [comment]
I might consider that, but I have done quite a bit of installing using mamba 0.25.0, and I haven't seen this issue with that version.

**Comment by jonashaag** [comment]
We increased download buffer size (and concurrency? Not sure) in 0.26 so that might be related
