### ISSUE TITLE
Is `micromamba` safe to run in parallel from multiple processes sharing the same pkg cache?

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/mamba#2035]
Sorry, more of a usage question / discussion than an actual issue. I'm a bit hesitant to clutter up the QuantStack gitter channel with usage questions but happy to do so if that's the preferred channel?

**Comment by wolfv** [comment]
We do use a file lock to make sure that only one process is writing to the package cache at the same time, so yes, it should be fine.

Let us know if you encounter issues!

**Comment by dhirschfeld** [comment]
Thanks @wolfv - will do. Closing as asked & answered! :+1:
