### ISSUE TITLE
Subdir ignored in `channel/subdir` specifier

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#2041]
```
conda create -n xxx 'conda-forge/noarch::git'
...
PackagesNotFoundError: The following packages are not available from current channels:

  - conda-forge/noarch::git
...
```

```
mamba create -n xxx 'conda-forge/noarch::git'
...
  added / updated specs:
    - conda-forge/osx-arm64::git
...
```

This also applies when installing from `environment.yml` files.

**Comment by jonashaag** [comment]
In 1.5.1:

```
micromamba create -n xxx conda-forge/osx-64::git
conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
critical libmamba The package "conda-forge/osx-64::git" is not available for the specified platform
```

**Comment by jonashaag** [comment]
> * Was it different before?

Yes, it ignored the constraint, see initial post.

> * Does it work with `micromamba create -n xxx conda-forge/osx-64::git -c conda-forge/osx-64`?

No.


> * I think the following should not throw but `return false;`

Not sure, this was changed in #2300 for good reasons I think

**Comment by jonashaag** [comment]
Related issue: https://github.com/mamba-org/mamba/issues/2431

**Comment by delsner** [comment]
I could take a look at this. But before I get started, I would like to understand what's the precise problem at the moment and whether we would like to fix it for `1.x`.

## Status Quo

**1.x** 

```
❯ build/1.x/micromamba/micromamba create -n xxx conda-forge/osx-64::git -c conda-forge/osx-64
conda-forge/osx-64                                          Using cache
conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
critical libmamba The package "conda-forge/osx-64::git" is not available for the specified platform
```
returns that the package is not available, even though it is available in subdir `osx-64`. 

**main**

```
❯ build/main/micromamba/micromamba create -n xxx conda-forge/osx-64::git -c conda-forge/osx-64
conda-forge/osx-64                                          Using cache
conda-forge/noarch                                          Using cache
conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
conda-forge/osx-arm64                                       Using cache

Transaction

  Prefix: /Users/delsner/opt/micromamba/envs/xxx

  Updating specs:

   - conda-forge/osx-64::git
```

seems to work fine (?).

## Possible TODOs

- [ ] Fix channel handling in `1.x` to match `main`
- [ ] Fix tests/code for #2300 (see #2789)
- [ ] Extend tests to make sure `pkgs/main::package_name` works correctly (https://github.com/mamba-org/mamba/pull/2300#discussion_r1305872903)

If it's not worth investigating this further because it seems to be fixed in `main`, we can probably close #2041, #2789, and perhaps also #2226 and #2102.

**Comment by jonashaag** [comment]
It would be nice if it worked without `-c`, just like Conda, but it's more important that it doesn't ignore the subdir (which it doesn't seem to be)

**Comment by delsner** [comment]
> It would be nice if it worked without -c, just like Conda...

I believe on `main` the behavior is similar to Conda even without `-c`?

```
❯ build/main/micromamba/micromamba create -n xxx conda-forge/osx-64::git
conda-forge/osx-arm64                                7.7MB @   3.9MB/s  1.9s
conda-forge/osx-arm64                                7.7MB @   3.7MB/s  2.0s
conda-forge/noarch                                  12.8MB @   5.0MB/s  2.5s
conda-forge/noarch                                  12.8MB @   4.5MB/s  2.8s
critical libmamba The package "conda-forge/osx-64::git" is not available for the specified platform                                                                    /11.5s

❯ conda create -n xxx conda-forge/osx-64::git
Channels:
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

InvalidSpec: The package "conda-forge/osx-64::git" is not available for the specified platform
```

**Comment by jonashaag** [comment]
You right, then it seems like there is nothing to do here. If you're really interested you can fix the tests but it's not a priority.

I'd assume that a back port to 1.x is difficult, and it's not a priority
