### ISSUE TITLE
Mamba 1.0.0 switches from cpython 3.9 to pypy39

### ISSUE THREAD

**Issue by chrisburr** [mamba-org/mamba#2082]
One of the conda-forge CI jobs started failing with the release of mamba 1.1.1: https://app.circleci.com/pipelines/github/regro/libcfgraph/31840/workflows/4488f304-9d57-4a3a-bb21-085a65237f8e/jobs/45699

It appears to be due to cpython being replaces with pypy. To reproduce in docker:

```bash
docker run --rm -it continuumio/miniconda3:latest bash
```

Then run:

```bash
conda config --add channels conda-forge
conda install mamba -y
mamba install pip
```

This doesn't happen if I foce `'mamba<1'` in both install commands:

```bash
conda config --add channels conda-forge
conda install 'mamba<1' -y
mamba install pip 'mamba<1'
```

**Comment by wolfv** [comment]
I just merged the OpenSSL 3 migration as well. Could that have been the issue?

**Comment by chrisburr** [comment]
Ah yes I think that's the cause as `mamba install pip 'openssl=1.1.1*'` avoids it and `conda install pip` doesn't try to update `openssl` at all.

I think `mamba` is treating `aggressive_update_packages` differently to conda and it appears condor only tries to do patch updates to `openssl` and editing `aggressive_update_packages` in the config avoids the issue.

**Comment by wolfv** [comment]
Hmm, but is `cpython` not compatible with `openssl 3` or is there another package in the dependencies that isn't compatible?

**Comment by chrisburr** [comment]
> Hmm, but is cpython not compatible with openssl 3 or is there another package in the dependencies that isn't compatible?

Everything is compatible with either. I can guide it to keep cpython by forcing the ABI package:

```
mamba install pip 'python_abi=3.9'
```

There are however fewer packages installed/changed if PyPy is chosen which I guess is why mamba is favouring PyPy.

Even if I do `conda update openssl` to get OpenSSL 3.0.0 it always keeps cpython.

**Comment by pentschev** [comment]
I have seen the same (or similar?) issue today on creating an environment `python=3.9` first, followed by `pandas` install:

```python
$  mamba create -c conda-forge -n pandas python=3.9
...
$ conda activate pandas
$ mamba install -c conda-forge pandas
...
  Install:
...
  + pandas             1.5.2  py39h3aff93f_1       conda-forge/linux-64     Cached
  + pypy3.9            7.3.9  hd671c94_7           conda-forge/linux-64     Cached
  + python-dateutil    2.8.2  pyhd8ed1ab_0         conda-forge/noarch       Cached
  + python_abi           3.9  3_pypy39_pp73        conda-forge/linux-64     Cached
...
  Downgrade:

  - python            3.9.15  hba424b6_0_cpython   conda-forge
  + python            3.9.12  0_73_pypy            conda-forge/linux-64     Cached
```

Creating the environment with `python=3.9` and `pandas` all in one command brings only CPython (as I expected):

```python
$ mamba create -n pandas python=3.9 pandas
```

**Comment by jakirkham** [comment]
For more context on Peter's comment, a new `build/number` of `pandas` was created recently ( https://github.com/conda-forge/pandas-feedstock/pull/147 ). However most of the CPython packages didn't publish due to an issue ( https://github.com/conda-forge/pandas-feedstock/issues/150 ) whereas the PyPy packages did. AFAICT `mamba` seems to prefer getting the latest `build/number` for a package so chose the PyPy package over the CPython package (with an older `build/number`) in this case.

**Comment by jjerphan** [comment]
We cannot reproduce this issue with 2.0, please update to 2.0.

Feel free to reopen an issue with a reproduce if you still have this issue with 2.0.

Note that 1.x is note being developed anymore, but to address security fixes.
