### ISSUE TITLE
mamba not found

### ISSUE THREAD

**Issue by restrepd** [mamba-org/mamba#2083]
I installed mamba:

conda install -c conda-forge mamba

And when I try to run it:

mamba env create -f environment.yml -n caiman

I get the message:

Command 'mamba' not found, did you mean:
  command 'samba' from deb samba (2:4.15.9+dfsg-0ubuntu0.2)
Try: sudo apt install <deb name>

I am running 

Ubuntu 22.04.1 LTS
conda 22.9.0

Thanks!

diego

**Comment by jonashaag** [comment]
Did you restart the shell? What environment did you install Mamba into? See https://mamba.readthedocs.io/en/latest/installation.html#installation

**Comment by paulimer** [comment]
I have the same issue, running conda 22.9.0 on CentOS Stream 8.

**Comment by jonashaag** [comment]
Did you restart the shell? What environment did you install Mamba into? See [mamba.readthedocs.io/en/latest/installation.html#installation](https://mamba.readthedocs.io/en/latest/installation.html#installation)

**Comment by restrepd** [comment]
Yes, I restarted the shell /bin/bash

Ubuntu 22.04.1 LTS

Thanks!

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
http://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420


From: Jonas Haag ***@***.***>
Date: Monday, November 7, 2022 at 3:03 AM
To: mamba-org/mamba ***@***.***>
Cc: Restrepo, Diego ***@***.***>, Author ***@***.***>
Subject: Re: [mamba-org/mamba] mamba not found (Issue #2083)
[External Email - Use Caution]

Did you restart the shell? What environment did you install Mamba into? See mamba.readthedocs.io/en/latest/installation.html#installation<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmamba.readthedocs.io%2Fen%2Flatest%2Finstallation.html%23installation&data=05%7C01%7Cdiego.restrepo%40cuanschutz.edu%7C1a0095d44c284aef475608dac0a74c53%7C563337caa517421aaae01aa5b414fd7f%7C0%7C0%7C638034122019837306%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9rWQLHzu4hYDsFdGp1kzMGM9H%2BAlSRATHR%2Fa6CAE%2F68%3D&reserved=0>

**Comment by jonashaag** [comment]
What Conda environment did you install Mamba into? Did you follow the installation guide that I linked?

**Comment by jonashaag** [comment]
You might want to try Mambaforge.

**Comment by paulimer** [comment]
So avoiding `conda` altogether?
I will try it when I have time, thanks.

**Comment by jeskowagner** [comment]
Might be a long shot, but have you checked `which conda` is where you would expect? It could be that your `$PATH` precendence is off.

**Comment by paulimer** [comment]
`which conda` 's output is:
```
$ which conda
conda ()
{ 
    \local cmd="${1-__missing__}";
    case "$cmd" in 
        activate | deactivate)
            __conda_activate "$@"
        ;;
        install | update | upgrade | remove | uninstall)
            __conda_exe "$@" || \return;
            __conda_reactivate
        ;;
        *)
            __conda_exe "$@"
        ;;
    esac
}
```
But I do not know if this is expected or not.
My PATH is 
```
echo $PATH
/home/etheimer/.local/bin:/home/etheimer/bin:/usr/share/Modules/bin:/usr/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
```

**Comment by jeskowagner** [comment]
Oh sorry, could you please try `whereis conda`? I'm guessing that you might have a conda installation in `Modules` that is taking precedence. While that might work, it would not necessarily be configured appropriately (still just a guess, not sure if that's what's happening).

**Comment by paulimer** [comment]
Here you go:
```
$ whereis conda
conda: /usr/bin/conda /usr/share/conda
```
Yes that's it, conda is installed when I check `sudo dnf list --installed | grep conda`

**Comment by paulimer** [comment]
Uninstalled, and it's all good, thanks a lot for the help!

**Comment by jeskowagner** [comment]
Fantastic, glad we got it sorted!

**Comment by restrepd** [comment]
Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
