### ISSUE TITLE
libarchive conflict: Cannot install mamba on a clean Anaconda install

### ISSUE THREAD

**Issue by SkirOwen** [mamba-org/mamba#2086]
I'm trying to install mamba on a new Anaconda install.  
I downloaded the latest version of Anaconda and install it.

I run this command in the terminal:
```shell
conda install mamba -c conda-forge -n base
```

Then conda takes a long time to solve the environment and end up finding conflicts. 

I tried on both on Linux (Ubuntu in WSL) and on MacOS, same behaviour.

**Comment by jonashaag** [comment]
If it's an option for you you can try to use the recommended Mambaforge installation: https://mamba.readthedocs.io/en/latest/installation.html

**Comment by jonashaag** [comment]
I'm testing this here and it's already taking 20 minutes to resolve. https://github.com/jonashaag/mamba/pull/10

**Comment by jonashaag** [comment]
Canceled it after 2 hours. Maybe it will work better with the Mamba solver.

**Comment by jonashaag** [comment]
There is a conflict with `libarchive=3.6` (we require `libarchive<3.6`). I'm now trying this:

```
conda install -n base "libarchive<3.6"
conda install -c conda-forge -n base mamba
```

**Comment by jjerphan** [comment]
We cannot reproduce this issue with 2.0, please update to 2.0.

We also recommend using Miniforge instead and to avoid mixing channel from Anaconda's with conda-forge.

Feel free to reopen an issue with a reproduce if you still have this issue with 2.0.

Note that 1.x is note being developed anymore, but to address security fixes.
