### ISSUE TITLE
mamba repoquery depends does not work without specifying a channel

### ISSUE THREAD

**Issue by samtygier-stfc** [mamba-org/mamba#2088]
https://mamba.readthedocs.io/en/latest/user_guide/mamba.html#repoquery gives a examples
`mamba repoquery depends xtensor` and `mamba repoquery depends -t xtensor`

When run these only give
```
Executing the query xtensor
No entries matching "xtensor" found
```
unless a channel is explicitly given as a argument, e.g.
`mamba repoquery depends --channel conda-forge -t xtensor`

`mamba repoquery search xtensor` works without a channel.

I think `depends` ought to work like `search`, as the docs suggest.

```
# mamba info

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.27.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : base
    active env location : /mambaforge
            shell level : 1
       user config file : /root/.condarc
 populated config files : /mambaforge/.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.10.6.final.0
       virtual packages : __linux=5.15.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /mambaforge  (writable)
      conda av data dir : /mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /mambaforge/pkgs
                          /root/.conda/pkgs
       envs directories : /mambaforge/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.10.6 Linux/5.15.0-52-generic ubuntu/20.04.1 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

I see this on ubuntu 20.04 installed from Mambaforge, and also in a fresh ubuntu docker environment.

**Comment by jonashaag** [comment]
Curious. Does `mamba search` and `mamba install` work for you without `-c`?

**Comment by samtygier-stfc** [comment]
Yes `mamba search` and `mamba install` work without a channel.

I don't think this is a local config issues, because I can reproduce with docker.
`docker run -it --rm condaforge/mambaforge mamba repoquery search xtensor`
shows results

`docker run -it --rm condaforge/mambaforge mamba repoquery depends xtensor`
shows `No entries matching "xtensor" found`

**Comment by jonashaag** [comment]
If I understand correctly `depends` and `whoneeds` work only on installed packages

**Comment by psobolewskiPhD** [comment]
I've run into this too.

> If I understand correctly `depends` and `whoneeds` work only on installed packages

If this is the case, then the docs should reflect that.

**Comment by samtygier-stfc** [comment]
`sudo docker run -it --rm condaforge/mambaforge bash -c "mamba install xtensor; mamba repoquery depends  xtensor"`
Works, so either the package needs to be installed or the channel specified.

**Comment by hadim** [comment]
On that topic, I also noticed a difference between `mamba` and `micromamba` (note that the below apply to both `whoneeds` and `depends`):

```bash
# Works as excepted
docker run -it --rm condaforge/mambaforge bash -c "mamba repoquery depends -c conda-forge xtensor"

# Return an error "No entries matching "xtensor" found"
docker run -it --rm mambaorg/micromamba:1.0.0 bash -c "micromamba repoquery depends -c conda-forge xtensor"
```

I know they are a couple of "on purpose" differences between `mamba` and `micromamba` and so I wonder whether the difference above is a known and expected one or not?

(let me know if I should open a new issue on that)

**Comment by jonashaag** [comment]
@wolfv
