### ISSUE TITLE
Do not show mamba ASCII art banner when `-q` if `-q` is passed

### ISSUE THREAD

**Issue by corneliusroemer** [mamba-org/mamba#2089]
It surprised me that you show the mamba ASCII art banner even when I ask for quiet output (`-q`).

Not quite sure what is quiet about the banner. I love mamba and have been advocating its use everywhere but this is a bit weird.

I know you have the `--no-banner`  flag, but that's an extra flag to add, and a lot of characters.

Quiet should mean quiet and not quiet plus verbose banner.

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/25161793/200194187-04e8664b-40ca-4d74-af66-0b9602c2e65a.png">

And yes, I know one can set the `MAMBA_NO_BANNER=1` environment variable. But still, that doesn't justify showing verbose banner when someone asks for quiet output.

**Comment by jonashaag** [comment]
Agreed! Should be simple to fix.

**Comment by jonashaag** [comment]
@corneliusroemer would you be up for contributing a fix? Should be fairly easy, the relevant code for Mamba is here: https://github.com/mamba-org/mamba/blob/424a18e3bbc889e6f3de1461b9862caafcc89f46/mamba/mamba/mamba.py#L877

You could simply try the changes in your existing Mamba install:

```
vim $(python -c 'import mamba.mamba as m; print(m.__file__)')
```

**Comment by corneliusroemer** [comment]
Here we go @jonashaag thanks for the pointer.

Tested on my local installation and it worked. Hope it passes more thorough tests but the build setup seems somewhat complicated.

https://github.com/mamba-org/mamba/pull/2097
