### ISSUE TITLE
ENH: Add short alias for `repoquery`, e.g. `rq`

### ISSUE THREAD

**Issue by corneliusroemer** [mamba-org/mamba#2090]
I like how fast `mamba repoquery search` is compared to `mamba search` but it's quite annoyingly long to type out.

Would it be possible to add an alias for `repoquery`, like e.g. `rq`?

The only downside would be that you'd not be able to use `rq` in the future as subcommand but how likely is this?

`mamba rq search` is much easier to type than `mamba repoquery search` - this alias would also be very helpful for `depends` and `whoneeds`

**Comment by jonashaag** [comment]
Or use `micromamba search` which is very fast as well :)

**Comment by jonashaag** [comment]
I‘m not a Fan of adding those kind of shorthands. You can easily add a shorthand to your shell.

**Comment by corneliusroemer** [comment]
Alright, you convinced me :)
<img width="1539" alt="image" src="https://user-images.githubusercontent.com/25161793/200195814-09feb2fa-3edc-4f96-9672-c334492bdba8.png">

I can alias to `umamba` ;)

**Comment by jonashaag** [comment]
I'll take the liberty to close this as "won't fix".
