### ISSUE TITLE
Explicit custom platforms have been broken since 0.23.0

### ISSUE THREAD

**Issue by afranchuk** [mamba-org/mamba#2102]
We use explicit platform specifications which use a custom platform (e.g. `linux-64-cxx03`). This is passed to micromamba with `-c CHANNEL[linux-64-cxx03]`. We recently tried to update the version of micromamba we are using and this broke.

In 0.22.0, this works. The URL used to fetch the package is `CHANNEL/linux-64-cxx03/...`.
In 0.23.0, this fails in a weird way: rewriting the URL as `CHANNEL-cxx03/linux-64/...`.
In 0.23.2, this fails in a slightly less weird way, but still wrong: rewriting the URL as `CHANNEL/linux-64-cxx03/linux-64/...`.

I believe this has to do with #1670. I've not yet found the change(s) in 0.23.0 that introduced the issue.

As commentary for #1670: I realize this behavior is to keep compatibility with old conda channels which have the platform at the end, but such an approach that relies on string manipulation and matching a set of known platforms is bound for error (and doomed when it comes to custom platforms). I think the use of such code should be limited as much as possible, including being ignored entirely if explicit platforms are provided.

**Comment by jonashaag** [comment]
Related: https://github.com/mamba-org/mamba/issues/2041

**Comment by jonashaag** [comment]
I think this is fixed
