### ISSUE TITLE
Why there is mistake when installing micromamba？

### ISSUE THREAD

**Issue by forestbat** [mamba-org/mamba#2106]
I want to install micromamba to my docker container，however it crashed with this report： 
```
(base) root@7332828622c8:/# wget https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
--2022-11-10 12:24:53--  https://micro.mamba.pm/api/micromamba/linux-64/latest
Resolving micro.mamba.pm (micro.mamba.pm)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘micro.mamba.pm’

bzip2: Compressed file ends unexpectedly;
        perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
        Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.
```
Why it appaers and how to solve it?

**Comment by jonashaag** [comment]
Does the micro.mamba.pm site work in your browser?

**Comment by forestbat** [comment]
I open micro.mamba.pm in my browser，and it only gives me a json with <html><body>

detail | "Not Found"
-- | --

</body>
</html>`

**Comment by jonashaag** [comment]
Where did you get that wget command from? Doesn’t it miss some options to redirect to stdout?

**Comment by forestbat** [comment]
I get `https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba` from [this doc](https://mamba.readthedocs.io/en/latest/installation.html#linux-and-macos)and put it after wget directly.

**Comment by jonashaag** [comment]
Does it work with the exact command that’s in the docs?

**Comment by jonashaag** [comment]
Oh I see there is a confusing question reference to wget there in the docs, never mind that

**Comment by wholtz** [comment]
You could build upon of our [official micromamba container](https://github.com/mamba-org/micromamba-docker). Or use the official micromamba container as a source to copy the `micromamba` binary into your container:

```Dockerfile
FROM ubuntu:jammy   # Replace with your desired base image

COPY --from=mambaorg/micromamba:1.0.0 /bin/micromamba /bin/micromamba
```

**Comment by wholtz** [comment]
The direct answer to your question, is that `wget` by default saves the file and does not sent it to the standard out. So the pipe isn't getting the expected output. to use `wget` you'd need to do:

```bash
wget -O - https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
```

**Comment by wholtz** [comment]
PR to remove reference to `wget` in the above referenced documentation: #2126

**Comment by forestbat** [comment]
Thank for @wholtz 's answer，but I have changed another computer and installed micromamba from `curl` command.
And I will try this answer later.
