### ISSUE TITLE
error while compiling libmamba solv/conda.h: No such file or directory

### ISSUE THREAD

**Issue by jhcuarta** [mamba-org/mamba#2110]
Hi
I encountered the following error while compiling libmamba

[  1%] Building CXX object libmamba/CMakeFiles/libmamba.dir/src/core/link.cpp.o
In file included from /home/jason/Documents/mamba-main/libmamba/include/mamba/core/transaction.hpp:26,
                 from /home/jason/Documents/mamba-main/libmamba/include/mamba/core/link.hpp:20,
                 from /home/jason/Documents/mamba-main/libmamba/src/core/link.cpp:18:
/home/jason/Documents/mamba-main/libmamba/include/mamba/core/repo.hpp:18:10: fatal error: solv/conda.h: No such file or directory
   18 | #include "solv/conda.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [libmamba/CMakeFiles/libmamba.dir/build.make:264: libmamba/CMakeFiles/libmamba.dir/src/core/link.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:118: libmamba/CMakeFiles/libmamba.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by jonashaag** [comment]
Can you please tell what are the full build steps that you used?

**Comment by wolfv** [comment]
Where did you get `libsolv` from? You need a build of libsolv that enabled conda (or take the one from conda-forge).

**Comment by jhcuarta** [comment]
Hi
I get libsolv using the following commands
sudo apt-get install libsolv-tools libsolv-dev libsolv-perl

https://github.com/openSUSE/libsolv
cd /home/jason/Documents/libsolv-master
mkdir build
cd build
cmake ..
make
sudo make install

And for compiling I used
git clone https://github.com/mamba-org/mamba.git
cd mamba
mkdir -p build
cd build
cmake .. -DBUILD_LIBMAMBA=ON -DBUILD_SHARED=ON -DBUILD_LIBMAMBA_TESTS=ON
make

When I try to locate conda.h I get

locate conda.h
/home/jason/Documents/libsolv-master/ext/repo_conda.h
/home/jason/Documents/libsolv-master/src/conda.h
/home/jason/mambaforge-pypy3/include/solv/conda.h
/home/jason/mambaforge-pypy3/include/solv/repo_conda.h
/home/jason/mambaforge-pypy3/pkgs/libsolv-0.7.22-h6239696_0/include/solv/conda.h
/home/jason/mambaforge-pypy3/pkgs/libsolv-0.7.22-h6239696_0/include/solv/repo_conda.h

I had set path environment for /home/jason/Documents/libsolv-master/src/ but error continues

**Comment by jonashaag** [comment]
Why not use the official development environment?

**Comment by jhcuarta** [comment]
I'm trying to build from scratch since I had issues installing packages that used defaults channel

**Comment by jonashaag** [comment]
Yeah, don't use the default channels.

If you don't want to change your `.condarc` I think you should be able to do something like

```
mamba create --override-channels -c condo-forge -f environment.yml
```

**Comment by jhcuarta** [comment]
Hi 
anyhow wolfv said I can use conda.h, where should I put it, theres no solv folder in mamba-main, is there a workaround for compiling

**Comment by wolfv** [comment]
@jhcuarta you cannot use the `libsolv` provided by `apt` because it does not include the proper `conda` files.
You'd need to compile it from source and use the `-DENABLE_CONDA` flag (you can find the build script used in conda-forge here: https://github.com/conda-forge/libsolv-feedstock/blob/main/recipe/build.sh
