### ISSUE TITLE
Library Import error: Conda works but mamba does not

### ISSUE THREAD

**Issue by ajaymur91** [mamba-org/mamba#2112]
Hello,
I was trying to install psi4 (a computational chemistry package). Mamba failed to produce a working psi4 package but conda succeeded. See below:

conda create -n test1 -c psi4 -c conda-forge psi4
conda activate test1
python 
>>> import psi4 (works)

mamba create -n test2 -c psi4 -c conda-forge psi4
conda activate test2
python 
>>> import psi4 (fails)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hosts/soja/exports/home/muralidharan.a.2/software/miniconda/envs/test2/lib/python3.10/site-pac                                                                                                                           kages/psi4/__init__.py", line 54, in <module>
    from . import core
ImportError: libecpint.so.1: cannot open shared object file: No such file or directory

**Comment by wolfv** [comment]
what other channels are you using and what is the output of `conda list / mamba list`?

**Comment by ajaymur91** [comment]
@wolfv Thanks for reaching out. 

I tried to recreate this issue with a separate (fresh) instance of conda.
-Installed fresh
-conda update conda
-conda install -n base -c conda-forge mamba
-mamba create -n test2 -c psi4 -c conda-forge psi4
-conda activate test2
-python

With this setup, the psi4 package works now. 
-import psi4 (works)
