### ISSUE TITLE
Command 'mamba' not found

### ISSUE THREAD

**Issue by danyanim2006** [mamba-org/mamba#2125]
Hi,
I am facing a similar issue with Mamba. I installed Mamba using miniforge.
https://github.com/conda-forge/miniforge#mambaforge
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
bash Mambaforge-$(uname)-$(uname -m).sh

When I try to create a new environment using "mamba create -n nameofmyenv ", I am getting an error
Command 'mamba' not found, did you mean:
command 'samba' from deb samba (2:4.15.9+dfsg-0ubuntu0.2)
Try: sudo apt install

I have restarted the shell and also conda is working fine.
( I am using Ubuntu 22.04)

**Comment by jonashaag** [comment]
What's the output of `which conda`?

**Comment by jonashaag** [comment]
Is this an old Anaconda install? Not sure where Mambaforge installs to

**Comment by danyanim2006** [comment]
The conda version is 
conda 22.9.0

**Comment by jonashaag** [comment]
No I was wondering if installed Anaconda (not Mambaforge) before and didn’t remove it and now you’re not actually using the Mambaforge install

**Comment by danyanim2006** [comment]
Yes, the Anaconda was installed prior to installing mambaforge

**Comment by jonashaag** [comment]
I think you have the same problem as https://github.com/mamba-org/mamba/issues/2083. Uninstall Anaconda first and remove any traces from `~/.bashrc` (or whatever shell you used).

**Comment by danyanim2006** [comment]
Thanks, so should I also uninstall Mambaforge and if so, how can i uninstall it

**Comment by jeskowagner** [comment]
If you'd like to use mambaforge, the recommended route would be to uninstall Anaconda. For details on how to do that, please see [here](https://docs.anaconda.com/anaconda/install/uninstall/). 
Afterwards, open a new shell and type `which conda` again, which should hopefully return the mambaforge installation of conda.

If this does not point you to your mambaforge installation, there are some more things you could try. Perhaps the most obvious is to open `~/.bashrc` and check the contents of the block starting with `# >>> conda initialize >>>`. Are the paths there pointing towards the folder you installed mambaforge in? If not, remove this block and reininstall mambaforge following the [instructions](https://mamba.readthedocs.io/en/latest/installation.html). Let us know how it goes!

**Comment by jonashaag** [comment]
I meant to uninstall Anaconda first.

I was sort of hoping you would have some more insight into this particular problem. I'm trying to prevent as many of these trillion bug reports that stem from unsupported ways of installing Mamba...

**Comment by jeskowagner** [comment]
I don't have additional insight unfortunately. I guess one could have some sort of flowchart like this that covers the potential cases? (with further explanations beneath it)
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/35219306/203632531-fd2adc13-7c12-4cf9-8000-3b3571cf8413.png">

**Comment by danyanim2006** [comment]
> If you'd like to use mambaforge, the recommended route would be to uninstall Anaconda. For details on how to do that, please see [here](https://docs.anaconda.com/anaconda/install/uninstall/). Afterwards, open a new shell and type `which conda` again, which should hopefully return the mambaforge installation of conda.
> 
> If this does not point you to your mambaforge installation, there are some more things you could try. Perhaps the most obvious is to open `~/.bashrc` and check the contents of the block starting with `# >>> conda initialize >>>`. Are the paths there pointing towards the folder you installed mambaforge in? If not, remove this block and reininstall mambaforge following the [instructions](https://mamba.readthedocs.io/en/latest/installation.html). Let us know how it goes!

Hi, thanks for the suggestion. I was not able to do these until recently. I have removed the anaconda installation and updated the mambaforge installation. Now which conda returns the mambaforge installation of conda. I think it works! thanks all.

**Comment by jjerphan** [comment]
Feel free to comment or reopen this issue if it has not been solved. :slightly_smiling_face:
