### ISSUE TITLE
micromamba install package successfully, but report "no version information available" when using the package.

### ISSUE THREAD

**Issue by sheep-liu** [mamba-org/mamba#2136]
I recently tried using micromamba and it was really fast and it was amazing. 
But after I installed some software with micromamba, I got some weird errors, which never happened when I was using conda.
below is the err/warning:
```bash
$ samtools view -H test.sorted.bam
samtools: /public/home/test/Micromamba/envs/snakemake/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /public/home/test/Micromamba/envs/snakemake/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /public/home/test/Micromamba/envs/snakemake/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
@HD     VN:1.6  SO:coordinate
@SQ     SN:chr1 LN:248956422
@SQ     SN:chr2 LN:242193529
@SQ     SN:chr3 LN:198295559
@SQ     SN:chr4 LN:190214555
......
```
When using other tools, such as htop, a similar error was encountered:
```bash
htop: /public/home/test/Micromamba/envs/snakemake/bin/../lib/libtinfow.so.6: no version information available (required by htop)
htop: /public/home/test/Micromamba/envs/snakemake/bin/../lib/libncursesw.so.6: no version information available (required by htop)
htop: /public/home/test/Micromamba/envs/snakemake/bin/../lib/libncursesw.so.6: no version information available (required by htop)
htop: /public/home/test/Micromamba/envs/snakemake/bin/../lib/libncursesw.so.6: no version information available (required by htop)
```
At first I suspected that there was a problem with the shared library file on the server, but when I changed to another server, the same error reappeared.
I don't know how to solve it. 
I will be very grateful if you can help me to solve this problem.

**Comment by wholtz** [comment]
Hello @sheep-liu - Thank you for your interest in micromamba.

Can you please post the commands you used generate your conda environments along with the output of `uname -a`?

**Comment by sheep-liu** [comment]
The system info:

```bash
$ uname -a
Linux moon 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

And I download `micromamba` from below url:

```R
https://micro.mamba.pm/api/micromamba/linux-64/latest
```

Then I initiate the `micromamba`:

```bash
./bin/micromamba shell init -p $HOME/Micromamba
```

I create the environment with the command:

```bash
micromamba create -y -n snakemake
micromamba activate snakemake
micromamba install -y snakemake fastqc multiqc fastp bwa deeptools bedtools bcftools samtools sambamba htop macs2 pigz bedops
```

**Comment by wholtz** [comment]
If that `micromamba install ...` command worked without supplying any channels, then you must have one or more configuration files that are coming into play. Can you please post the output from:

```bash
micromamba config sources
```

and

```bash
micromamba config list
```

thanks!

**Comment by sheep-liu** [comment]
Yes, I have a configuration file:

```bash
$ micromamba config sources
Configuration files (by precedence order):
~/.mambarc

$ micromamba config list
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
always_yes: false
show_banner: false
```

**Comment by wholtz** [comment]
I was able to replicate the issue using a smaller test case where only `htop` is installed. With that test case, removing the first channel from your `.mambarc` file fixed the issue. Please try this with your full conda environment and report back if it resolves the issue.

**Comment by sheep-liu** [comment]
!!!!!!!!!!
You are awesome!!!
I have given up using conda totally and switched to micromamba.
Although I do not sure what happens after I removed the first channel from `.mambarc`, the issue indeed has been fixed.

**Comment by jonashaag** [comment]
Is this reproducible with using only the main channel or only conda-forge?

**Comment by sheep-liu** [comment]
> Is this reproducible with using only the main channel or only conda-forge?

I am not sure about this, but after I remove the `main` channel, the exception was indeed fixed.

**Comment by wholtz** [comment]
> Is this reproducible with using only the main channel or only conda-forge?

Can anyone name a package within main that uses ncurses? `htop`, `nano`, `sc` all are not in main.....

**Comment by wholtz** [comment]
For more information see https://stackoverflow.com/a/72464818/16596758 and links within.
