### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by piscesvivian** [mamba-org/mamba#2145]
An unexpected error has occurred. Conda has prepared the above report.

Operation too slow. Less than 30 bytes/sec transferred the last 60 seconds.

It's downloading for a big package, above 1GB, Why this always happens? Whether there are network speed requirements for using MAMBA ?

**Comment by jonashaag** [comment]
There are some similar issues already reported, did you check them?

**Comment by wolfv** [comment]
You can use `MAMBA_NO_LOW_SPEED_LIMIT=0` as environment variable to disable this behavior.

**Comment by tzickel** [comment]
@wolfv Just making sure you mean MAMBA_NO_LOW_SPEED_LIMIT=1 yes ? (Since this post is the first google search for this issue).
