### ISSUE TITLE
linking error with  curl 7.86

### ISSUE THREAD

**Issue by AshishDurgapal** [mamba-org/mamba#2154]
Curl Version : 7.86
Platform : MAC arm64
OpenSSL enabled : yes

Curl lib has been successfully built but getting linking error while link with application.

./configure --host=x86_64-apple-darwin20.3.0 --target=arm64-apple-macos11 CFLAGS="-arch arm64 -fPIC" CC="/usr/bin/gcc" --without-zlib --with-ssl=/*********/openssl-1.1.1k --disable-ldap --disable-ldaps

Undefined symbols for architecture arm64:
  "_SCDynamicStoreCopyProxies", referenced from:
      _Curl_resolv in libcurl.a(libcurl_la-hostip.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jonashaag** [comment]
Same as issue as this? ****

**Comment by AshishDurgapal** [comment]
@jonashaag , Yes. 
Do you any workaround for the issue  as no solution have been provided in  #1732

**Comment by jonashaag** [comment]
OK thanks closing as duplicate then. Unfortunately I don't

**Comment by jonashaag** [comment]
Except for this PR https://github.com/mamba-org/mamba/pull/1759 maybe
