### ISSUE TITLE
Mamba install caused conda plugin error

### ISSUE THREAD

**Issue by RichStack** [mamba-org/mamba#2160]
Hi, wonder if someone can help me.
I'm working on a Ubuntu linux shell on a HPC cluster.
I have miniconda installed and my aim was to install an R environment. First I wanted to install mamba to speed up install of R packages etc.
` conda install mamba -n base -c conda-forge -y`
that worked fine, but my next command
` conda update --all`
gave me this error
`PluginError: Error while loading conda plugins from entrypoints: /home/rjs202/miniconda3/lib/python3.9/site-packages/libmambapy/../../../libmamba.so.2: undefined symbol: archive_write_add_filter_zstd`
I'm getting this error when trying to run most of my conda commands. I think I broke everything!
Can anyone help.
Many thanks.

**Comment by jonashaag** [comment]
Is it possible for you to try the recommended installation option (Mambaforge, see docs)?
