### ISSUE TITLE
"critical libmamba Operation not supported" on cifs mounted drive

### ISSUE THREAD

**Issue by behinger** [mamba-org/mamba#2169]
Hi! I am trying to use PythonCall.jl which internally calls micromamba. Unfortunately, I have a **cifs mounted** windows net drive where I need to install my packages to (the default of `PythonCall.jl`).

------
I pruned down the internal call to:
```
/home/ehinger/.julia/artifacts/8d5103d84a46e89c60d007a7d30b926037514616/bin/micromamba -r /home/ehinger/.julia/scratchspaces/0b3b1443-0f03-428d-bdfb-f27f9c1191ea/root create -y -p /store/users/ehinger/tmp/.CondaPkg/env "libstdcxx-ng[version='>=3.4',channel='conda-forge']" "python[version='>=3.7,<4']" -c anaconda -c conda-forge --log-level 1 -vvv
```
and I get the following error (I pruned the log, with log-level 1 it is quite long)

```bash
info     libmamba All targets to download are cached
Linking libstdcxx-ng-12.2.0-h46fd767_19
debug    libmamba Linking package 'libstdcxx-ng-12.2.0-h46fd767_19' from '/home/ehinger/.julia/scratchspaces/0b3b1443-0f03-428d-bdfb-f27f9c1191ea/root/pkgs/libstdcxx-ng-12.2.0-h46fd767_19'
debug    libmamba Unlocking '/store/users/ehinger/tmp/.CondaPkg/env/conda-meta'
info     libmamba Freeing transaction.
info     libmamba Freeing solver.
info     libmamba Freeing pool.
critical libmamba Operation not supported: '/home/ehinger/.julia/scratchspaces/0b3b1443-0f03-428d-bdfb-f27f9c1191ea/root/pkgs/libstdcxx-ng-12.2.0-h46fd767_19/lib/libstdc++.so', '/store/users/ehinger/tmp/.CondaPkg/env/lib/libstdc++.so'
```
---

Note that if I change the target path to a non-cifs drive (e.g. `/home/ehinger/tmp`), it works without error.

Any help is greatly appreciated!

**Comment by jonashaag** [comment]
Looks like we try to do some operation on the file that's not supported by the file system.

Are you familiar with `strace` or similar tool? Could you have a look what operation is being attempted? My guess would be some kind of `chmod`.

**Comment by behinger** [comment]
good idea - didnt use it, but this is the line that breaks:
```
symlink("libstdc++.so.6.0.30", "/store/users/ehinger/tmp/.CondaPkg/env/lib/libstdc++.so") = -1 EOPNOTSUPP (Operation not supported)                                                
```
which makes sense, on cifs we cant use symlinks. Can I disable symlinks? I tried the `always_copy = True` flag in ~/.mambarc or via `--always_copy` but with no success (also not 100% sure what it does, but it sounds like it should stop symlinks?)

btw. I just noticed, the shipped version is 0.25.1 - but when I use v1.1 (also with `always_copy` flag) I get same error (but more informative ;-))

`│critical libmamba filesystem error: cannot copy symlink: Operation not supported `

**Comment by jonashaag** [comment]
Micromamba does not share code with Conda so it must be unrelated

**Comment by jonashaag** [comment]
Relevant code seems to be here, could you run with `trace` log level and compare the output with the code?

https://github.com/mamba-org/mamba/blob/68ed35ba131dbe3cd0d355d2a8f5ecd97511d861/libmamba/src/core/link.cpp#L716-L765

**Comment by jonashaag** [comment]
Hm unfortunately I lack understanding of what's going on here :(

**Comment by behinger** [comment]
could it be, that it detects a path_type `SOFTLINK` and thus jumps into:

L758 `else if (path_data.path_type == PathType::SOFTLINK)`

That would explain why the flags have no influence.

Indeed the `libstdc++.so` is a symlink (not sure where the path_data.path_type comes from). But if I replaced the `libstdc++.so` with a hardcopy of the target, the same error occured.

**Comment by jonashaag** [comment]
This seems to be the only place where we set `path_type = SOFTLINK` but I'm not familiar with that part of the code https://github.com/mamba-org/mamba/blob/68ed35ba131dbe3cd0d355d2a8f5ecd97511d861/libmamba/src/core/package_paths.cpp#L177

**Comment by behinger** [comment]
mh. ok - thanks for your help! I am not familiar enough with c++ & filesystems to do anything here

**Comment by behinger** [comment]
I found a solution. Using "mfsymlinks" in my mount -cifs, I can circumvent the problem.
This allows for "pseudo"-symlinks, which are only interpretable using the linux-cifs mount command. 

This is only then not a solution, if you need to access your files from windows as well. honestly, I dont know what would happen.

More info: https://unix.stackexchange.com/questions/328027/symlink-support-with-windows-cifs-server-and-linux-client 

Thanks for your help!

**Comment by behinger** [comment]
Addendum for anyone who ever needs to put conda environments on a CIFS mounted drive: Don't.

While you can fix the symlink issue as described before, you will now run into a CaseSensitive issue. E.g. the package `ncurses` has symlinks named `2019A.so` as well as `2019a.so` in the same folder. This leads to crashes, because after copying the first file, you can't copy the second file anymore and you get an `critical libmamba filesystem error: cannot copy symlink: File exists`

While there might be a solution for more modern filesystems (e.g. recent windows now supports CaseSensitive Folders/Files) - this was not the case for my drive, unfortunately.

So if you stumble upon this issue, I hope you have more luck than I had!

**Comment by wolfv** [comment]
sorry to hear that and thanks for leaving this note!
