### ISSUE TITLE
Packages that are only available as `.conda` artifacts are not reliably found

### ISSUE THREAD

**Issue by michaelosthege** [mamba-org/mamba#2172]
I tried `mamba create -n testenv -c conda-forge "sunode==0.4.0"` and got `nothing provides numpy >=1.23.5,<2.0a0 needed by sunode-0.4.0-py310hd5a9e38_1`.

This prompted me to try `mamba create -n testenv -c conda-forge "numpy==1.23.5"` resulting in `nothing provides requested numpy 1.23.5`.

My OS is Windows x64 and I did this with latest `mamba v0.27.0`.

Earlier today I had similar problems with `pymc==5.0.0` and `sunode==0.4.0` and got them resolved by updating the feedstocks to release not only `.conda` artifacts (the new default), but also `.tar.bz2` artifacts as was the default until a month or so ago.
```yaml
conda_build:
  pkg_format: 2    # makes .conda artifacts
  pkg_format: None # makes .tar.bz2 artifacts
```

Strangely enough, this fixed the install of `pymc==5.0.0, sunode==0.4.0, numpy==1.23.5` for my colleague (also on Windows).

Since [NumPy 1.23.5 is currently only listed with `.conda` artifacts](https://anaconda.org/conda-forge/numpy/files), and it worked for my colleague but not for me,
this falsifies my theory that it was a matter of having `.tar.bz2` artifacts.

**Comment by beckermr** [comment]
Did you try conda?

A useful debugging data point and a possible workaround.

**Comment by michaelosthege** [comment]
> Did you try conda?
> 
> A useful debugging data point and a possible workaround.

Yes, did that two minutes ago in a Python 3.9 env created with `mamba create -n murefidev -c conda-forge "python=3.9"`

```
>>> conda install -c conda-forge "numpy==1.23.5"
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - numpy==1.23.5

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
```
with
```
>>> conda --version
conda 4.12.0
```

**Comment by beckermr** [comment]
Works fine for me

```
$ conda create -n testenv -c conda-forge "numpy==1.23.5"

***

NOTE: You are using the EXPERIMENTAL libmamba solver integration.

If something is not working as expected, please:

1. Go to https://github.com/conda/conda/issues/new/choose
2. Choose the "Libmamba Solver Feedback (Experimental Feature)" option

Thank you for your help!

***

pkgs/r/osx-64                                                 No change
pkgs/main/noarch                                              No change
pkgs/r/noarch                                                 No change
pkgs/main/osx-64                                     4.8MB @   3.5MB/s  1.6s
conda-forge/noarch                                  10.6MB @   3.5MB/s  3.5s
conda-forge/osx-64                                  25.9MB @   4.3MB/s  7.4s
Collect all metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/beckermr/mambaforge/envs/testenv

  added / updated specs:
    - numpy==1.23.5


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgfortran-5.0.0          |11_3_0_h97931a8_27         143 KB  conda-forge
    libgfortran5-11.3.0        |      h082f757_27         1.4 MB  conda-forge
    numpy-1.23.5               |  py311h62c7003_0         6.3 MB  conda-forge
    python_abi-3.11            |          3_cp311           6 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         7.8 MB

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/osx-64::bzip2-1.0.8-h0d85af4_4 None
  ca-certificates    conda-forge/osx-64::ca-certificates-2022.12.7-h033912b_0 None
  libblas            conda-forge/osx-64::libblas-3.9.0-16_osx64_openblas None
  libcblas           conda-forge/osx-64::libcblas-3.9.0-16_osx64_openblas None
  libcxx             conda-forge/osx-64::libcxx-14.0.6-hccf4f1f_0 None
  libffi             conda-forge/osx-64::libffi-3.4.2-h0d85af4_5 None
  libgfortran        conda-forge/osx-64::libgfortran-5.0.0-11_3_0_h97931a8_27 None
  libgfortran5       conda-forge/osx-64::libgfortran5-11.3.0-h082f757_27 None
  liblapack          conda-forge/osx-64::liblapack-3.9.0-16_osx64_openblas None
  libopenblas        conda-forge/osx-64::libopenblas-0.3.21-openmp_h429af6e_3 None
  libsqlite          conda-forge/osx-64::libsqlite-3.40.0-ha978bb4_0 None
  libzlib            conda-forge/osx-64::libzlib-1.2.13-hfd90126_4 None
  llvm-openmp        conda-forge/osx-64::llvm-openmp-15.0.6-h61d9ccf_0 None
  ncurses            conda-forge/osx-64::ncurses-6.3-h96cf925_1 None
  numpy              conda-forge/osx-64::numpy-1.23.5-py311h62c7003_0 None
  openssl            conda-forge/osx-64::openssl-3.0.7-hfd90126_1 None
  python             conda-forge/osx-64::python-3.11.0-h559f36b_0_cpython None
  python_abi         conda-forge/osx-64::python_abi-3.11-3_cp311 None
  readline           conda-forge/osx-64::readline-8.1.2-h3899abd_0 None
  tk                 conda-forge/osx-64::tk-8.6.12-h5dbffcc_0 None
  tzdata             conda-forge/noarch::tzdata-2022g-h191b570_0 None
  xz                 conda-forge/osx-64::xz-5.2.6-h775f41a_0 None


Proceed ([y]/n)? 
```

Maybe that new version of numpy dropped python 3.9?

**Comment by jonashaag** [comment]
What are the differences between your colleague's setup and yours? Do you have the same `.condarc`? In particular, do you use the same channels? Are you using some corporate mirror?

**Comment by michaelosthege** [comment]
> Works fine for me

You appear to be on osx; I'm on Windows

> Maybe that new version of numpy dropped python 3.9?

No, this is the link to the `.conda` artifact for NumPy 1.23.5 under Python 3.9 on Windows: https://anaconda.org/conda-forge/numpy/1.23.5/download/win-64/numpy-1.23.5-py39hceebc26_0.conda

My `.condarc`:

```
unsatisfiable_hints: true
```

He has

```
channels:
  - conda-forge
  - defaults
channel_priority: strict
```

Our `mamba info` differs mainly in the `conda version` and directory paths: https://www.diffchecker.com/YhLiY8r8

My colleague is on `conda version 22.9.0` under Python 3.9.13 while I'm on `conda version 4.12.0` and Python 3.7.2.

Maybe I need to update my conda and base environment Python versions?
What is a safe way to do that?

**Comment by jonashaag** [comment]
If you could reproduce this in a Docker container that would be great

**Comment by michaelosthege** [comment]
Interestingly I can create the environments on my personal computer with `conda 22.9.0`, `python 3.8.15` and `mamba 1.1.0`.

I suspect the Python version of the base environment, because the 3.7 on my work PC is quite old.
I'll to to get it updated and see if that helps.

**Comment by jonashaag** [comment]
> If you could reproduce this in a Docker container that would be great

I just realized that this wasn’t helpful because you can’t build Windows Docker containers (right?)

**Comment by jonashaag** [comment]
I don’t think updating the base Python will have any effect. As long as you can run a recent version of Mamba you should be able to install `.conda` packages.

Try removing most channels from your condarc (eg keep only conda-forge)

**Comment by michaelosthege** [comment]
0.27.0 is the latest mamba version that runs with a Python 3.7 base environment.

Since this would create problems eventually, I decided to upgrade my base environment - by removing all envs, uninstalling miniconda and then installing the current miniconda.

And it helped: With a current miniconda running a Python 3.9 base, and `mamba` 1.1.0 I can finally create the environments 🥳
