### ISSUE TITLE
install from lockfile doesn't respect pkgs_dirs

### ISSUE THREAD

**Issue by alchzh** [mamba-org/mamba#2187]
a command like `micromamba install --name explicit --file conda-lock.yml` ignores configured pkgs_dirs due to 7ea1ab9 and https://github.com/mamba-org/mamba/blob/f32b42e3f23f585df28c59aa0e0c43b2333737eb/libmamba/src/api/install.cpp#L568

I would like to use lockfiles in tandem with a shared package cache on my server environment for large environment updates.

Is there a reason for the current behavior?

**Comment by hmaarrfk** [comment]
Could it be that this is stopping our offline installs at conda-forge? xref: https://github.com/conda-forge/miniforge/issues/419

**Comment by hmaarrfk** [comment]
Is the fix that that the line should look more like:
https://github.com/mamba-org/mamba/blob/f32b42e3f23f585df28c59aa0e0c43b2333737eb/libmamba/src/api/install.cpp#L422

**Comment by alchzh** [comment]
I'm guessing there was a decision made with good reason to find the pkgs for manually instead of like that.  @wolfv ?

**Comment by hmaarrfk** [comment]
I think it is causing us to also create a random folder in the user's directory: https://github.com/conda-forge/miniforge/issues/420

**Comment by alchzh** [comment]
Thank you for getting this in!
