### ISSUE TITLE
mamba upgrade to 1.x

### ISSUE THREAD

**Issue by cbagdel** [mamba-org/mamba#2188]
https://stackoverflow.com/questions/74862017/mamba-upgrade-to-1-x 

I have mamba 0.27 installed on my mac OS. How can I upgrade to mamba 1.x?

Can I simply do a fresh re-installation of the newer version, if I want to keep my existing mamba environments and settings?

I checked mamba's documentation, and I searched in internet, but could not find any "how to upgrade" information.

thanks a lot in advance!

**Comment by jonashaag** [comment]
You can simply update mamba via `mamba install`. No reinstall needed.

**Comment by cbagdel** [comment]
thanks a lot. 
for me `mamba update mamba` has also worked. 
https://stackoverflow.com/questions/74862017/mamba-upgrade-to-1-x/74954867#74954867
