### ISSUE TITLE
Installing on Offline cpu machine

### ISSUE THREAD

**Issue by divastar** [mamba-org/mamba#2223]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

offline

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Reproducible with Conda

### Describe your issue

Hi I need mamba for work on offline cpu centos7 machine.
I downloaded the repo and used Mambaforge-Linux-x86_64.sh to install mambaforge
now I used commands conda activate
and mamba create -n myenv python=3.8

now I got Runtime error: Download error https://conda.anaconda.org/conda-forge/noarch/repodata.json]
Could not resolve host: conda.anaconda.org

how I can download all the needed dependencies to proceed on the offline machine?
thank you

**Comment by jonashaag** [comment]
How are you planning to install packages without access to the internet?

**Comment by divastar** [comment]
Hi [jonashaag](https://github.com/jonashaag),
yes I need to install on offline machine which doesn't have an access to the internet
thank you

**Comment by jonashaag** [comment]
How are you planning to do so? Do you have experience doing that with Conda (not Mamba)?

**Comment by jonashaag** [comment]
You can download all the `.conda` and `.tar.bz2` files you need and then `mamba install ...list of files...`

**Comment by divastar** [comment]
Thank you! what url I download this from?

**Comment by jonashaag** [comment]
Try using `mamba env export --explicit`!

**Comment by divastar** [comment]
Hi [jonashaag](https://github.com/jonashaag),
thank you for your response
so I got this list of files:
https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2022.12.7-ha878542_0.conda
https://conda.anaconda.org/conda-forge/linux-64/ld_impl_linux-64-2.39-hcc3a1bd_1.conda
https://conda.anaconda.org/conda-forge/linux-64/tzdata-2022g-h191b570_0.conda
https://conda.anaconda.org/conda-forge/linux-64/Libgomp-12.2.0-h65d4601_19.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-2_gnu.tar.bz2  v
https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.8-h7f98852_4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libffi-3.4.2-h7f98852_5.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libnsl-2.0.0-h7f98852_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libuuid-2.32.1-h7f98852_1000.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libzlib-1.2.13-h166bdaf_4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ncurses-6.3-h27087fc_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openssl-3.0.7-h0b41bf4_1.conda
https://conda.anaconda.org/conda-forge/linux-64/xz-5.2.6-h166bdaf_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libsqlite-3.40.0-h753d276_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/readline-8.1.2-h0f457ee_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tk-8.6.12-h27826a3_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-3.9.15-hba424b6_0_cpython.conda
https://conda.anaconda.org/conda-forge/noarch/setuptools-66.0.0-pyhd8ed1ab_0.conda
https://conda.anaconda.org/conda-forge/noarch/wheel-0.38.4-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/noarch/pip-22.3.1-pyhd8ed1ab_0.tar.bz2

Tried to mamba install ld_impl_linux-64-2.39-hcc3a1bd_1.conda
But still got this Runtime error:
File "home/user/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line110, in get_index is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
RuntimeError: download error (28) Timeout was reached [https://conda.anaconda.org/conda-forge/noarch/reposata.json
Could not resolve host: conda.anaconda.org

Is this a way to tell it not to download from https://conda.anaconda.org but to use only local resources?
Thank you!

**Comment by jonashaag** [comment]
Try passing `--offline` although I would not be surprised if it still failed (=> bug)

**Comment by divastar** [comment]
Hi [jonashaag](https://github.com/jonashaag),
thank you for your response.
So it lookes like I managed to install the above external dependencies using --offline
Now I tried to create new env with mamba create --offline -n myenv python=3.8
I got:
"Looking for ['python=3.8']
conda-forge/linux-64
conda-forge/noarch
Could not solve for environment specs
Encountered problems while solving:
  -nothing provides requested python 3.8**
The environment can't be solved, aborting the operation"

It means I need to place in  python 3.8 package?

**Comment by jonashaag** [comment]
You need to pass the file names instead of `python=3.8`.

**Comment by divastar** [comment]
Hi [jonashaag](https://github.com/jonashaag),
thank you for your responce so you mean I can do mamba create --offline -n myenv Python-3.9.gz ?
this gives me:
Looking for: ['Python-3.9.gz']
conda-forge/linux-64
conda-forge/noarch
Could not solve for environment specs
Encountered problems while solving:
   -nothing provides requested Python-3.9.gz

The environment can't be solved, aborting the operation


or for example if I have this ready other new env folder
with lib and bin and conda-meta subfolders what files should I list with the mamba create -n
all those in the bin for example?

I also activated this env which was created outside of this this system
and try to install downloaded numpy.zip for example: mamba install --offline numpy-1.24.zip
which was inside the same directory but I got:
Looking for: ['numpy-1.24.1.zip']
conda-forge/linux-64
conda-forge/noarch

Pinned packages:
     - python .9.*
Could not solve for environment specs
Encountered problems while solving:
   -nothing provides requested numpy-1.24.zip

The environment can't be solved, aborting the operation

**Comment by jonashaag** [comment]
.zip and .gz are not Conda file formats. Try passing a full path to a downloaded Conda package file. 

You can also set up local channels, check the Conda documentation on that. 

There’s also conda-pack

**Comment by divastar** [comment]
Hi [jonashaag](https://github.com/jonashaag),
I passed all the downnloaded .conda packages to  mamba create --offline -n myenv
and it created an environment which I mamba activate
now for example trying to install one of the downloaded packages numpy.zip
which gave me :

mamba install --offline numpy-1.24.zip
Looking for: ['numpy-1.24.1.zip']
conda-forge/linux-64
conda-forge/noarch
Could not solve for environment specs
Encountered problems while solving:
-nothing provides requested numpy-1.24.zip

The environment can't be solved, aborting the operation

**Comment by jonashaag** [comment]
.zip is not a Conda compatible file format

**Comment by jonashaag** [comment]
Closing due to lack of feedback
