### ISSUE TITLE
Wrong error message when attempting install of unavailable package for a given python version

### ISSUE THREAD

**Issue by mexanick** [mamba-org/mamba#2234]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

wrong error message

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Didn't try

### Describe your issue

Instead of "no compatible numba package found for python 3.11" mamba attempts to install a numba version for python 2.7:
```shell
mamba create -c conda-forge -n foo python=3.11 numba 
...
Looking for: ['python=3.11', 'numba']

pkgs/main/noarch                                              No change
pkgs/r/linux-64                                               No change
pkgs/r/noarch                                                 No change
pkgs/main/linux-64                                   5.1MB @   2.1MB/s  2.4s
conda-forge/noarch                                  10.9MB @   3.8MB/s  3.0s
conda-forge/linux-64                                29.1MB @   4.8MB/s  6.4s
Could not solve for environment specs
Encountered problems while solving:
  - package numba-0.38.0-py27_0 requires python >=2.7,<2.8.0a0, but none of the providers can be installed

The environment can't be solved, aborting the operation
```

**Comment by jonashaag** [comment]
Please try the new experimental solver messages and report any ideas for improvement here: https://github.com/mamba-org/mamba/issues/2078

Thanks!
