### ISSUE TITLE
Mamba command is not recognized in an environment other than base

### ISSUE THREAD

**Issue by foobar41** [mamba-org/mamba#2246]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

Mamba not working in another environment

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not reproducible with Conda

### Describe your issue

I created a new environment with mamba then tried to install some packages
`mamba create --name gpu`
`mamba activate gpu`
`mamba install tensorflow-gpu`
But this is what it shows: `'mamba' is not recognized as an internal or external command,
operable program or batch file.`

I also tried `mamba create --name gpu tensorflow-gpu` and it perfectly works

Now I cannot install additional packages except those which I have done while creating the environment

Please help

**Comment by jonashaag** [comment]
Try searching for that error message in the issue tracker
