### ISSUE TITLE
conda 23.1.0 breaks mamba init

### ISSUE THREAD

**Issue by davidwagnerkc** [mamba-org/mamba#2248]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

No results for "no_user"

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not reproducible with Conda

### Describe your issue

`conda` release 23.1.0 last week includes https://github.com/conda/conda/pull/11949 which removes `no_user` from args. This causes `mamba init` (on 0.25.0, then 1.2.0 after upgrade) to throw an attribute error:

```
'Namespace' object has no attribute 'no_user'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/davidwagner/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/home/davidwagner/anaconda3/lib/python3.9/site-packages/mamba/mamba.py", line 935, in exception_converter
        raise e
      File "/home/davidwagner/anaconda3/lib/python3.9/site-packages/mamba/mamba.py", line 928, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/davidwagner/anaconda3/lib/python3.9/site-packages/mamba/mamba.py", line 886, in _wrapped_main
        result = do_call(args, p)
      File "/home/davidwagner/anaconda3/lib/python3.9/site-packages/mamba/mamba.py", line 758, in do_call
        exit_code = shell_init(args)
      File "/home/davidwagner/anaconda3/lib/python3.9/site-packages/mamba/mamba_shell_init.py", line 75, in shell_init
        if args.no_user:
    AttributeError: 'Namespace' object has no attribute 'no_user'
```

Specifically in that PR this change eliminates `no_user` and only keeps `user`:
![image](https://user-images.githubusercontent.com/20519655/214622403-32a1c1cd-b5a8-4e57-ad8b-0af5ac6434bc.png)

From a glance at `mamba_shell_init.py` (https://github.com/mamba-org/mamba/blob/main/mamba/mamba/mamba_shell_init.py#L84) it looks like `mamba` could pull this block of changes in to resolve this. 

![image](https://user-images.githubusercontent.com/20519655/214622522-9c3a6c51-020c-44b3-8fcb-9327e3dbd501.png)

### mamba info / micromamba info

```shell
active environment : base
    active env location : /home/davidwagner/anaconda3
            shell level : 5
       user config file : /home/davidwagner/.condarc
 populated config files : /home/davidwagner/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /home/davidwagner/anaconda3  (writable)
      conda av data dir : /home/davidwagner/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/davidwagner/anaconda3/pkgs
                          /home/davidwagner/.conda/pkgs
       envs directories : /home/davidwagner/anaconda3/envs
                          /home/davidwagner/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.9.12 Linux/5.15.0-1027-gcp ubuntu/22.04.1 glibc/2.35
                UID:GID : 1009:1010
             netrc file : None
           offline mode : False
```

**Comment by davidwagnerkc** [comment]
I should add that I resolved this locally with downgrading `conda<23`. So in about info dump `conda==22.11.1` does not show issue, only when I was on `conda==23.1.0`

**Comment by davidwagnerkc** [comment]
Okay last update. I did upgrade to `conda=23.1.0` and changed `mamba_shell_init.py` to use the newer `for_user = args.user and not args.system` and `mamba init` appears to work properly. 

Not sure if that is the proper fix or not, but hopefully that is helpful.

**Comment by jonashaag** [comment]
Thanks, attempting a fix in #2249

**Comment by ReimarBauer** [comment]
By this I triggered it too, and by updating my mamba version it is solved too

```
. $HOME/mambaforge/etc/profile.d/conda.sh 
. $HOME/mambaforge/etc/profile.d/mamba.sh
mamba init
```

**Comment by c2b2pss** [comment]
I just posted the same error.  I don't understand the fix.  Also, how do I upgrade mamba specifically? Please post commands for newbie! :-)

**Comment by ReimarBauer** [comment]
I guess you are looking for
`mamba update -n base mamba`

and from another posting in #2270 you can repair a broken env by  one in a good state. An example for windows

```
conda activte ENV_IN_GOOD_STATE

c:/Users/r.bauer/Miniconda3/envs/mssenv/Scripts/conda.exe install -p C:\Users\r.bauer\Miniconda3\envs\ENV_TO_REPAIR python conda==22.9.0
```

**Comment by jonashaag** [comment]
@ReimarBauer do you have Conda installed in an env other than base? That’s not supported.

**Comment by ReimarBauer** [comment]
@jonashaag it was there, that was a rather old installation. 
The current windows testinstallation has it on  C:\Users\r.bauer\mambaforge\Scripts\conda.exe
