### ISSUE TITLE
Mamba hangs forever for version >=0.17  on synchronized NFS filesystem

### ISSUE THREAD

**Issue by nigiord** [mamba-org/mamba#2252]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

hang OR stuck OR forever 

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not reproducible with Conda

### Describe your issue

Hi, we’ve been having issues with mamba on a shared HPC server since version 0.17.0. The issue is still present on the last version of mamba (1.2.0).

### Description
Any mamba install/update/create command hangs forever without any error message (see below). Commands work normally with conda (even though it’s very slow). The process cannot be cancelled with CTRL+C and must be killed from another terminal session.

Using `git bisect`, I pinpointed that the bug was introduced at the following commit:

```
d8da02d4c740eff9408b0227f1dabbe6f57bf5e8 is the first bad commit
commit d8da02d4c740eff9408b0227f1dabbe6f57bf5e8
Author: Adrien DELSALLE <ad.delsalle@gmail.com>
Date:   Tue Aug 3 19:30:13 2021 +0200

    enable support of multiple caches in umamba
    fix wrong call to path::touch in PackageCacheData::create_directory, causing wrong result
    handle multiple caches
    split tarball cache, extracted dir cache and repodata index one
    add and update tests
    update bindings
    add pytest-lazy-fixture dep
    improve locks
    use lockfiles with a more granular approach
    update mamba according to api changes
    handling case of expired but still valid repodata
    re-use the same cache for all tests
    do not use existing cache on the host to avoid permission errors on win
    refactor a bit the LockFile private methods
    add a factory try_lock method to handle exceptions
    update MSubdirData::load according to LockFile improvements
    use cache valid_extracted_dir
    reset valid_extracted_dir cache when extracting it again

:040000 040000 1120574e7d7c48b031c26dfa6fd434060acac936 a99f6d56c9118fd536816f8966a8bd498d71dcc5 M      include
:040000 040000 9160c4a0c88738ce9f37558b064290b96c948240 1a34d6b2de65e0562f298b8c76066d15ef8794bf M      mamba
:040000 040000 93111bf18d5649f248583a324d37e1dc8f65e146 83553eeaf98d2a9fae92a820c9372014bec9424c M      src
:040000 040000 c7b7a328f469ab5f380d03e08e44a171471f28e0 c717fd323f19af2f1f5c88705a33b7754eb70980 M      test
```

I speculate this might be due to our specific set-up that relies on multiple shared file systems, since mamba is installed on a dedicated shared nfs partition.

In the past we identified hang issues with other utilities like sqlite, that apparently are related to file locking on NFS systems (see [https://www.sqlite.org/howtocorrupt.html#_filesystems_with_broken_or_missing_lock_implementations](https://www.sqlite.org/howtocorrupt.html#_filesystems_with_broken_or_missing_lock_implementations) for example). But strangely the bug with mamba is also present when I install mamba on a xfs partition (/tmp).

The breaking commit makes huge changes on lockfiles and cache, but I’m not sure where to go from there. Any recommendation on things I could test for in order to pinpoint where the issue lies?

The log extracts below were made using the mamba-dev environnement I used for the git dissect (the built version of mamba is exactly the one corresponding to the commit mentionned above), hence why the version mentioned in the log is 0.16.0.

### mamba info / micromamba info

```shell
__    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.16.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : base
    active env location : /CONDAS/users/<snip>/mamba-dev
            shell level : 1
       user config file : /home/<snip>/.condarc
 populated config files : /home/<snip>/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.15.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /CONDAS/users/<snip>/mamba-dev  (writable)
      conda av data dir : /CONDAS/users/<snip>/mamba-dev/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /CONDAS/users/<snip>/packages
       envs directories : /CONDAS/users/<snip>
                          /CONDAS/users/<snip>/mamba-dev/envs
                          /home/<snip>/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.28.2 CPython/3.9.15 Linux/3.10.0-1127.19.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 284513:10000
             netrc file : None
           offline mode : False
```

### Logs

```shell
/CONDAS/users/<snip>/mamba-dev/bin/mamba install -n testenv tqdm -vvv

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.16.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

DEBUG conda.gateways.logging:set_verbosity(246): verbosity set to 3

Looking for: ['tqdm']

TRACE conda.gateways.disk.delete:rm_rf(165): rm_rf /CONDAS/users/<snip>/testenv.pid12756.conda_lock
INFO    Reading cache files '/tmp/tmpza9.*' for repo index 'installed'
DEBUG   Loading JSON file '/tmp/tmpza9yvjtd'
DEBUG   Checking if '/CONDAS/users/<snip>/packages' is writable
TRACE   '"/CONDAS/users/<snip>/packages/urls.txt"' exists, checking if writable
DEBUG   '/CONDAS/users/<snip>/packages' writable
INFO    Searching index cache file for repo 'https://conda.anaconda.org/conda-forge/linux-64/repodata.json'
DEBUG   Locking directory '/CONDAS/users/<snip>/packages/cache'
[HANG FOR DAYS, CANNOT BE CANCELLED WITH CTRL+C, MUST KILL PROCESS]
```

### ~/.condarc

```yaml
auto_activate_base: false
channel_priority: strict
channels:
  - conda-forge
  - bioconda
  - defaults
```

**Comment by jonashaag** [comment]
You might want to debug with `strace` or even gdb/lldb to see where it hangs.

**Comment by wolfv** [comment]
Thanks for the debugging and even git bisecting! I wonder if this has to do with the lockfiles... 

Indeed, if you could try `strace` that would help us to further understand where it hangs.

**Comment by pbordron** [comment]
@nigiord and I use the same infrastructure and share this problem.

I did the test with `strace` and mamba hangs after those 2 lines

```
open("/CONDAS/users/pbordron/packages/cache/cache.lock", O_RDWR|O_CREAT, 0666) = 7                                                                           
fcntl(7, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=21, l_len=1}  
```

If I set the `CONDA_PKGS_DIRS` env var to something different from a nfs share, there is no more hang

```
CONDA_PKGS_DIRS=/tmp/conda-pbordron/ mamba create -p /tmp/conda-pbordron/env python
```

**Comment by wolfv** [comment]
thanks for the confirmation ... we have a fix for micromamba (it has a `use_lockfiles` options that can be set to `false` to prevent lockfiles globally).
But as far as I remember we haven't added that to mamba yet... Is micromamba an option for you?

**Comment by pbordron** [comment]
We can use micromamba instead of mamba, we will give it a try.

**Comment by nigiord** [comment]
Thank you @pbordron for the follow-up with strace! I remember finding the option `use_lockfiles : false` during my early googling and testing it at one point but I didn’t know micromamba and mamba had different options.

I wonder if we could make mamba display a warning when an option from .condarc or .mambarc is ignored / not recognized.

As @pbordron mentioned we can probably use micromamba as a workaround, but it would indeed be perfect if this option could be implemented for mamba too.

**Comment by pbordron** [comment]
We look at the nfs mount options with our sysadmin

Using `local_lock=all` instead of the default `local_lock=none` for the NFS share solve the issue with mamba.

**Comment by JohanMabille** [comment]
> As @pbordron mentioned we can probably use micromamba as a workaround, but it would indeed be perfect if this option could be implemented for mamba too.

We are going to move everything from mamba (python code) to libmamba / micromamba so they should be at feature parity in the end. Closing this issue for now since it can be solved with a configuraion of the nfs. Feel free to open a new more specific issue about the `use_lockfiles` option if you need it.
