### ISSUE TITLE
[Feature] Can I directly export the connection of the package I need to download?

### ISSUE THREAD

**Issue by relic-yuexi** [mamba-org/mamba#2254]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

this is not a bug

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Didn't try

### Describe your issue

I found that there is a file **urls.txt** in the pkgs directory, which records the address of the package to be downloaded, but the source code seems to be added only when it is downloaded, **so there is no way to directly output the address of all the packages to be downloaded to the txt, and then I download it by myself through a downloader**, such as idm or other multi-threaded downloader, I found that the download speed is faster than using mamba Download many times faster than using mamba, currently found mamba seems to be parallel download rather than multi-threaded, so my download speed is still only 10~100kb/s, but if I use the downloader multi-threaded download will be able to reach more than 10Mb/s.

**Comment by jonashaag** [comment]
Thanks for the report! Mamba should be as fast as any other downloaded. It’s unlikely that having more threads will make things faster because downloads aren’t typically CPU bound.

Are you using the latest version?

Could you maybe record a short video of Mamba downloading, vs. some other downloader?

You can also try increasing the `download_threads` (which doesn’t actually add more threads; the name is confusing) setting to something like 20.

During download can you please watch your CPU utilization, does the CPU max out at 100%?

Thanks!

**Comment by relic-yuexi** [comment]
I use the latest version,1.2.0. I used windows and install the mambafore.
Actually the slow part is from conda.anaconda.org/nvidia/win-64/ , the other channel is great.

**Comment by relic-yuexi** [comment]
> Thanks for the report! Mamba should be as fast as any other downloader. It’s unlikely that having more threads will make things faster because downloads aren’t typically CPU bound.
> 
> Are you using the latest version?
> 
> Could you maybe record a short video of Mamba downloading, vs. some other downloader?
> 
> You can also try increasing the `download_threads` (which doesn’t actually add more threads; the name is confusing) setting to something like 20.
> 
> During download can you please watch your CPU utilization, does the CPU max out at 100%?
> 
> Thanks!


https://user-images.githubusercontent.com/53668275/216215513-dd175379-1218-45a5-80e5-f4d3dfad3e04.mp4


https://user-images.githubusercontent.com/53668275/216215745-056baa0b-de65-4c2d-9531-d4be929b5913.mp4



As you can see,it is slow to download. And when i use the downloader, it's fast than the mamba. So i want to get the download urls before use the mamba download it.

Maybe this example file is a little small.But last time i download the 2G file, it's the same speed as this time.

**Comment by jonashaag** [comment]
Curious. I just tried to download that and it works just fine. Do you have some proxy configured in the downloader in the second video that you don't have configured for Mamba?

**Comment by relic-yuexi** [comment]
> Curious. I just tried to download that file and it works just fine. Do you have some proxy configured in the downloader in the second video that you don't have configured for Mamba?

Maybe yes, i use a software like vpn to surf on the web. In China, it's hard to download foreign resource files. But if i close the software, i will easily get error sometimes.

**Comment by jonashaag** [comment]
Isn't there a China mirror of most Conda channels?
