### ISSUE TITLE
Libmamba can not be installed on miniconda 23.1.0

### ISSUE THREAD

**Issue by fschramka** [mamba-org/mamba#2270]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

#1724

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Reproducible with Conda

### Describe your issue

1. Install a fresh miniconda [from here](https://docs.conda.io/en/latest/miniconda.html) - we use the Python 3.9 for Linux64 release [link](https://repo.anaconda.com/miniconda/Miniconda3-py39_22.11.1-1-Linux-x86_64.sh)
2. Update your conda environment with `conda update -n base conda` [as suggested here](https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community)
3. Try to install libmamba (`conda install -n base conda-libmamba-solver`)

It will not be able to install libmamba - this is the last part of the output:

> specifications were found to be incompatible with your system:
> 
>   - feature:/linux-64::__glibc==2.31=0
>   - feature:|@/linux-64::__glibc==2.31=0
>   - brotlipy -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
>   - cffi -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
>   - conda-package-handling -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
>   - cryptography -> libgcc-ng -> __glibc[version='>=2.17']
>   - libffi -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
>   - libgcc-ng -> __glibc[version='>=2.17']
>   - libstdcxx-ng -> __glibc[version='>=2.17']
>   - ncurses -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
>   - openssl -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
>   - pycosat -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
>   - python=3.9 -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
>   - ruamel.yaml -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
>   - ruamel.yaml.clib -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
>   - sqlite -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
>   - tk -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
>   - xz -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
>   - zlib -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
>   - zstandard -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
> 
> Your installed version is: 2.31

The full output is longer than 65'536 - could not post it :) 

**Workaround:**
Do not install the conda 23.1.0 release (=do not update conda before installing libmamba). If you do it the other way around (first install libmamba on conda 22, then update), it will work.

**Comment by ReimarBauer** [comment]
I got into this today too.  And it happens after updating an old installation.

```
msst) C:\Users\r.bauer\workspace\MSS>conda info
C:\Users\r.bauer\Miniconda3\envs\msst\Lib\site-packages\conda_package_streaming\package_streaming.py:19: UserWarning: zstandard could not be imported. Running without .conda support.
  warnings.warn("zstandard could not be imported. Running without .conda support.")
C:\Users\r.bauer\Miniconda3\envs\msst\Lib\site-packages\conda_package_handling\api.py:29: UserWarning: Install zstandard Python bindings for .conda support
  _warnings.warn("Install zstandard Python bindings for .conda support")
C:\Users\r.bauer\Miniconda3\envs\msst\Lib\site-packages\conda_package_streaming\package_streaming.py:19: UserWarning: zstandard could not be imported. Running without .conda support.
  warnings.warn("zstandard could not be imported. Running without .conda support.")
C:\Users\r.bauer\Miniconda3\envs\msst\Lib\site-packages\conda_package_handling\api.py:29: UserWarning: Install zstandard Python bindings for .conda support
  _warnings.warn("Install zstandard Python bindings for .conda support")

     active environment : base
    active env location : C:\Users\r.bauer\Miniconda3\envs\msst
            shell level : 2
       user config file : C:\Users\r.bauer\.condarc
 populated config files : C:\Users\r.bauer\.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.11.0.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\r.bauer\Miniconda3\envs\msst  (writable)
      conda av data dir : C:\Users\r.bauer\Miniconda3\envs\msst\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\r.bauer\Miniconda3\envs\msst\pkgs
                          C:\Users\r.bauer\.conda\pkgs
                          C:\Users\r.bauer\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\r.bauer\Miniconda3\envs\msst\envs
                          C:\Users\r.bauer\.conda\envs
                          C:\Users\r.bauer\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.11.0 Windows/10 Windows/10.0.14393
          administrator : False
             netrc file : None
           offline mode : False


(msst) C:\Users\r.bauer\workspace\MSS>mamba info
C:\Users\r.bauer\Miniconda3\envs\msst\Lib\site-packages\conda_package_streaming\package_streaming.py:19: UserWarning: zstandard could not be imported. Running without .conda support.
  warnings.warn("zstandard could not be imported. Running without .conda support.")
C:\Users\r.bauer\Miniconda3\envs\msst\Lib\site-packages\conda_package_handling\api.py:29: UserWarning: Install zstandard Python bindings for .conda support
  _warnings.warn("Install zstandard Python bindings for .conda support")
Traceback (most recent call last):
  File "C:\Users\r.bauer\Miniconda3\envs\msst\Scripts\mamba-script.py", line 6, in <module>
    from mamba.mamba import main
  File "C:\Users\r.bauer\Miniconda3\envs\msst\Lib\site-packages\mamba\mamba.py", line 53, in <module>
    from mamba.mamba_shell_init import shell_init
  File "C:\Users\r.bauer\Miniconda3\envs\msst\Lib\site-packages\mamba\mamba_shell_init.py", line 8, in <module>
    from conda.core.initialize import initialize, initialize_dev, make_initialize_plan
  File "C:\Users\r.bauer\Miniconda3\envs\msst\Lib\site-packages\conda\core\initialize.py", line 71, in <module>
    from menuinst.knownfolders import get_folder_path, FOLDERID
  File "C:\Users\r.bauer\Miniconda3\envs\msst\Lib\site-packages\menuinst\__init__.py", line 23, in <module>
    from .win32 import Menu, ShortCut
  File "C:\Users\r.bauer\Miniconda3\envs\msst\Lib\site-packages\menuinst\win32.py", line 18, in <module>
    from .winshortcut import create_shortcut
ModuleNotFoundError: No module named 'menuinst.winshortcut'
```

**Comment by ReimarBauer** [comment]
I recognized that I can repare a broken env by any existing env 

```
conda activte ENV_IN_GOOD_STATE

c:/Users/r.bauer/Miniconda3/envs/mssenv/Scripts/conda.exe install -p C:\Users\r.bauer\Miniconda3\envs\ENV_TO_REPAIR python conda==22.9.0
```

**Comment by jonashaag** [comment]
@ReimarBauer note that you are mixing the anaconda channels and Conda-forge. That’s not something we recommend because it may cause a lot of trouble.

**Comment by ReimarBauer** [comment]
@jonashaag Can I solve this by removing the defaults channel or do I have to base everything on mambaforge?

**Comment by ReimarBauer** [comment]
Got the  answer https://mamba.readthedocs.io/en/latest/installation.html 
-> Changing our docs :)
