### ISSUE TITLE
`micromamba shell -n myenv` broken in 1.3.0

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#2271]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

/

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

```
⋊> ~ micromamba shell -n base
critical libmamba The given prefix does not exist: "base"
⋊> ~ micromamba run -n base ls
...works fine...
```

Curious why this isn't covered by a test

**Comment by jonashaag** [comment]
With 1.3.1 we now have

```
$ micromamba env list | grep boa
  boa                 /Users/j/micromamba/envs/boa
$ micromamba shell -n boa
critical libmamba The given prefix does not exist: "envs/boa"
```

I wonder why the test is ok.

**Comment by Hind-M** [comment]
> $ micromamba env list | grep boa
> boa                 /Users/j/micromamba/envs/boa
> $ micromamba shell -n boa
> critical libmamba The given prefix does not exist: "envs/boa"

That means that the `root_prefix` is considered empty while it's supposed to be  `/Users/j/micromamba/`. Is it related to a special setting of the `root_prefix`?

**Comment by jonashaag** [comment]
See my test case in #2305
