### ISSUE TITLE
timeout is too short with `mamba run`

### ISSUE THREAD

**Issue by nicolergay** [mamba-org/mamba#2295]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

is:issue timeout

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

I am getting an intermittent timeout error with `mamba run` that I do not see when I activate the mamba environment and run the same command. This sometimes gives me an error:
```
mamba run -n okta [some command]           
ERROR: HTTPSConnectionPool(host=[url], port=[port]): Read timed out. (read timeout=0.5)

ERROR conda.cli.main_run:execute(47): `conda run [some command]` failed. (See above for error)
```
This consistently works:
```
mamba activate okta
[some command]
```
So it seems like there is a 0.5-second timeout specific to using `mamba run`? How can I change this? Notably, this is an intermittent problem with a private tool, so reproducibility is a bit challenging. 

### mamba info / micromamba info

```shell
active environment : base
    active env location : /Users/nicoleg/mambaforge
            shell level : 1
       user config file : /Users/nicoleg/.condarc
 populated config files : /Users/nicoleg/mambaforge/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.2.1=0
                          __unix=0=0
       base environment : /Users/nicoleg/mambaforge  (writable)
      conda av data dir : /Users/nicoleg/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/nicoleg/mambaforge/pkgs
                          /Users/nicoleg/.conda/pkgs
       envs directories : /Users/nicoleg/mambaforge/envs
                          /Users/nicoleg/.conda/envs
               platform : osx-arm64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.10.9 Darwin/22.3.0 OSX/13.2.1
                UID:GID : 4312:1916
             netrc file : None
           offline mode : False
```

**Comment by nicolergay** [comment]
The command is working in mamba right now, so I'm not going to test in conda. Do you know where that 0.5-second timeout is specified?

**Comment by jonashaag** [comment]
There should be no such thing

**Comment by jonashaag** [comment]
I would be surprised if we were making HTTP requests in `run` (in fact I think `mamba run` is just an alias for `conda run`)

**Comment by nicolergay** [comment]
The HTTP request is through the internal tool installed in the `okta` environment. It's not clear if this is a mamba issue, and the problem is intermittent, so closing this.
