### ISSUE TITLE
devcontainer feature?

### ISSUE THREAD

**Issue by nick-youngblut** [mamba-org/mamba#2307]
I'm using [fig-cli](https://fig.io/), specifically the devcontainer feature `ghcr.io/withfig/features/fig:1`. `fig` adds commands to the .bashrc in my devcontainer, and these must be at the top and bottom of the .bashrc. So, if I install conda/mamba via the `postCreateCommand`, then the `# >>> conda initialize >>>` block is appended in the .bashrc *after* the fig command, which breaks fig. 

So, it would be great to have a mamba devcontainer feature (that is compatible with fig). More generally, installing mamba via a devcontainer feature would make conda/mamba installation easier when using VS Code devcontainers.

**Comment by jonashaag** [comment]
@maresb

**Comment by maresb** [comment]
@nick-youngblut, have you seen the recently created micromamba [devcontainer feature](https://github.com/mamba-org/devcontainer-features/)? It's not exactly Mamba, but maybe it would still suit your needs? It's fairly new so we'd be glad to have feedback about how it works for you.

**Comment by nick-youngblut** [comment]
Thanks for pointing out the micromamba devcontainer feature! That's awesome! 🚀 

In regards to using mamba with fig, the `mamba initialize` code block comes before the fig-post code block, so that fixes my issue with fig. Thanks for your help! 

I'm guessing that I will still need to add channels (e.g., bioconda) via the postCreateCommand. Is that correct?

**Comment by nick-youngblut** [comment]
One small thing: it would help if the default channels were listed on the [README docs](https://github.com/mamba-org/devcontainer-features/tree/main/src/micromamba). Based on my `~/.condarc`, the defaults are conda-forge, bioconda, and defaults. It would be helpful to know that in the docs.

**Comment by maresb** [comment]
Thanks @nick-youngblut for the feedback!

Could you use `micromamba init` in place of `mamba init`?

Regarding the devcontainer feature default channels, there are none. (We didn't want to play favorites.) Thus without any further setup, it is generally necessary to use the `--channel` flag so that micromamba has a source. Perhaps your `~/.condarc` is coming from somewhere else?

**Comment by nick-youngblut** [comment]
Thanks @maresb for the info! The `~/.condarc` was a remnant of an old mamba install.

**Comment by maresb** [comment]
@nick-youngblut, great, glad it's working! And if you run into any other problems or questions regarding the features, feel free to open issues on [mamba-org/devcontainer-features](https://github.com/mamba-org/devcontainer-features/)

**Comment by nick-youngblut** [comment]
@maresb I was just trying to find [mamba-org/devcontainer-features](https://github.com/mamba-org/devcontainer-features/) again since you mentioned it. It is kind of hard to find. For instance, as far as I can tell, there is no mention of the feature in https://github.com/mamba-org/vscode-micromamba/blob/main/README.md
