### ISSUE TITLE
RISC-V support and micromamba bootstrap build 

### ISSUE THREAD

**Issue by ifsheldon** [mamba-org/mamba#2308]
Hi! I want to build a `micromamba` for my RISC-V SBC, but to setup a dev env for micromamba, a micromamba needs to be installed first as said in the documentation. This gets me stuck. 

So now I have two questions:
* Do we have a plan to add RISC-V support? I think a minimum support for managing pure-python (or any architecture-independent) packages should be possible and easy.
* Can we somehow bootstrap building `micromamba` without an existing `micromamba`?

**Comment by jonashaag** [comment]
Are there any packages for RISC-V in the first place?

**Comment by wolfv** [comment]
This is a good question! I think we'd love to have support on more platforms :)

If you can get micromamba/libmamba dependencies from somewhere else / from source, this should be totally doable.

We do use `vcpkg` on Windows to get dependencies for the Windows build. If vcpkg works on RISC-V then that might be viable. 

I can give you more details or you can look at the micromamba feedstock: http://github.com/conda-forge/micromamba-feedstock

You need `libarchive`, `libcurl`, and a couple more packages.

**Comment by ifsheldon** [comment]
> Are there any packages for RISC-V in the first place?

I guess any pure-Python packages work since there're ports of Python and some Python packages in distros like Debian.

**Comment by ifsheldon** [comment]
> If vcpkg works on RISC-V then that might be viable.

The support is there but not in a stable release yet. I guess we can see it works this week when 2023-02-24 is released. Related PR of vcpkg is [this](https://github.com/microsoft/vcpkg-tool/pull/894).

> I can give you more details or you can look at the micromamba feedstock

I'm not very familiar with feedstocks. Can you give me some pointers? Maybe we can wait a bit until the end of this week when a new vcpkg is released?

**Comment by jonashaag** [comment]
This is the build script: https://github.com/conda-forge/micromamba-feedstock/blob/main/recipe/build.sh

Here you’ll find the list of dependencies: https://github.com/conda-forge/micromamba-feedstock/blob/main/recipe/meta.yaml all of those are found as feedstocks. In general you should be able to use any of the dependencies installed from any package manager (or simply using the source distribution). So you might want to start with any Linux distribution that has a lot of packages and see how far you’ll get.

**Comment by dtcxzyw** [comment]
Hi! The risc-v support for ```vcpkg``` is now available: https://github.com/microsoft/vcpkg/releases/tag/2023.02.24. I am trying to port ```mamba``` to linux-riscv32/64 platforms. Could you assign this issue to me?

**Comment by ifsheldon** [comment]
Thanks. I've been too busy to try it out these days. I can help with writing a bootstrapping documentation.

> port `mamba`

I guess you are referring to micromamba? Because `mamba` still needs `conda` as a dependency, porting micromamba may be easier.

**Comment by dtcxzyw** [comment]
@ifsheldon I have successfully built ```micromamba``` on my risc-v machine. Here is my bootstrapping script: https://gist.github.com/dtcxzyw/9fe5a3d7404d4234bc675a7847a3fa48. Hope it helps you.

However, it cannot install any ```conda-forge``` packages since the channels for linux-riscv32/64 are not available.
Here are some related issues/PRs:
https://github.com/conda-forge/conda-forge.github.io/issues/1744
https://github.com/conda/conda/pull/12319

I will make some contributions to ```conda``` and ```conda-forge``` for risc-v support. There's still a long way to go. 😂

**Comment by ifsheldon** [comment]
> However, it cannot install any conda-forge packages since the channels for linux-riscv32/64 are not available.

I am not very familiar with the internals of conda-forge, but I guess any packages marked as "noarch" should in theory be able to be installed? For example, I don't see any reasons why [`toposort`](https://anaconda.org/conda-forge/toposort) cannot be installed.

**Comment by jonashaag** [comment]
Yes but you need the Python dependency. So you’ll have to at least port the Python package (or fake it with some hacking)
