### ISSUE TITLE
Add another path to conda initialize block in .bashrc file?

### ISSUE THREAD

**Issue by Dwrgi** [mamba-org/mamba#2321]
Is it possible to add another path to the conda initialize block in my .bashrc file so that I don't have to use the full path when wanting to activate my conda based environments rather than the mamba based ones?

After some "fun" yesterday (see Background below), I now have to use 'conda activate /home/sara/anaconda3/envs/my_env' rather than 'conda activate my_env', since mamba has muscled in on conda initialize. I don't really have an issue with that (since everything seems to work fine), other than that it would be nice to be able to activate any of them without having to give the full path.

The conda initialize block in my .bashrc file:

```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/sara/mambaforge/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/sara/mambaforge/etc/profile.d/conda.sh" ]; then
        . "/home/sara/mambaforge/etc/profile.d/conda.sh"
    else
        export PATH="/home/sara/mambaforge/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

**Background:**
I was trying to install medaka as one of several programs in an existing conda env that I was setting up, but it would not install in it, so I tried to set up a separate conda env for medaka (which didn't work either for some reason - it has in the past). I found a comment suggesting to use mamba so I went ahead and did that. 

In the process, I seem to have linked all my subsequent envs to mambaforge:

```
sara@VB-ubuntu:~$ conda info --envs
# conda environments:
#
                      *  /home/sara/anaconda3
                         /home/sara/anaconda3/envs/homopolish_env
                         /home/sara/anaconda3/envs/perfect_assembly_env
                         /home/sara/anaconda3/envs/pyani_env
                         /home/sara/anaconda3/envs/roary_env
base                     /home/sara/mambaforge
hypo_env                 /home/sara/mambaforge/envs/hypo_env
medaka_env               /home/sara/mambaforge/envs/medaka_env
trycycler_env            /home/sara/mambaforge/envs/trycycler_env
```

**Comment by giladgressel** [comment]
I ran into this yesterday and solved it with
`conda config --append envs_dirs /home/amar/miniconda3/envs/`

So for you, I think you need
`conda config --append envs_dirs /home/sara/anaconda3/envs/`

this adds another place for env names to exist.
https://stackoverflow.com/questions/58369030/could-not-find-conda-environment
That SO post pointed me in the right direction.

**Comment by Dwrgi** [comment]
> I ran into this yesterday and solved it with `conda config --append envs_dirs /home/amar/miniconda3/envs/`
> 
> So for you, I think you need `conda config --append envs_dirs /home/sara/anaconda3/envs/`


Thanks! That seems to have solved it. 😃
