### ISSUE TITLE
Failed with initial frozen solve

### ISSUE THREAD

**Issue by CraigScullyClemmons** [mamba-org/mamba#2323]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

#1735, not resolved

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Reproducible with Conda

### Describe your issue

I just downloaded the most recent version of Anaconda, 2022.10, and I am on python 3.9. The following command entered into the base environment of the Anaconda terminal:

conda install -c conda-forge mamba

yields the following errors:

failed with initial frozen solve. Retrying with flexible solve.
failed with repodata from current_repodata.json, will retry with next repodata source.
failed with repodata from current_repodata.json, will retry with next repodata source.

I've tried this process about five times and it never installs. What am I doing wrong? The reason I'm trying to install mamba into the base environment is because I am following this tutorial: https://github.com/EricThomson/CCN_caiman_mesmerize_workshop_2023 and as a very new programmer, I don't want to deviate from the steps, especially since mamba is just the first of many libraries that will go on to be installed.

**Comment by jonashaag** [comment]
Please use the Mambaforge installation method. The installation steps provided in that tutorial are not supported.

**Comment by CraigScullyClemmons** [comment]
Thanks! I did so and it's working as expected :)
