### ISSUE TITLE
mamba not found after fresh install from mambaforge on Ubuntu Focal Fossa

### ISSUE THREAD

**Issue by rbavery** [mamba-org/mamba#2327]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

Done. Other issues start with an existing Anaconda installation

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

not reproducible this way since we are starting from mambaforge

### mamba info / micromamba info

```shell
mamba does not run, command not found
```

### Logs

```shell
none
```

### environment.yml

```yaml
none
```

### ~/.condarc

```yaml
none
```

## The Issue
```
 wget https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh
bash Mambaforge-Linux-x86_64.sh -b

```

```output
Linking conda-22.11.1-py310hff52083_1
Linking mamba-1.1.0-py310h51d5547_3
Transaction finished
installation finished.
```
```
mamba
```
```output
mamba not found
```

I would expect mamba to be available after running the bash script. exiting and then re-sshing also id not make mamba available.

**Comment by jonashaag** [comment]
It looks like the path where Mambaforge was installed is missing.

**Comment by rbavery** [comment]
@jonashaag yeah any idea why the installer wouldn't set that? it is installed in my home dir

```
ubuntu@ip-172-31-30-99:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
ubuntu@ip-172-31-30-99:~$ ls
mambaforge
```

**Comment by jonashaag** [comment]
I don’t know, please move this conversation to the Mambaforge bug tracker. Closing here. We don’t maintain Mambaforge here. Thank you!
