### ISSUE TITLE
mamba not found after activate environment

### ISSUE THREAD

**Issue by mjohenneken** [mamba-org/mamba#2335]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

mamba not found after activate environment 

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Reproducible with Conda

### Describe your issue

I installed mamba as Micromamba into my user directory. I'm working with Miniforge prompt from the start menu entry.

Running `mamba create env -n myMamba` and `mamba activate myMamba` the `mamba` command is not found.

I have another miniconda installed on the system. Could this be a path issue? 

There was a similar issue before in https://github.com/mamba-org/mamba/issues/1265

### mamba info / micromamba info

```shell
(base) C:\Users\MYUSER>mamba info

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.1.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


     active environment : base
    active env location : C:\Users\MYUSER\mambaforge
            shell level : 1
       user config file : C:\Users\MYUSER\.condarc
 populated config files : C:\Users\MYUSER\mambaforge\.condarc
                          C:\Users\MYUSER\.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.6=0
                          __win=0=0
       base environment : C:\Users\MYUSER\mambaforge  (writable)
      conda av data dir : C:\Users\MYUSER\mambaforge\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\MYUSER\mambaforge\pkgs
                          C:\Users\MYUSER\.conda\pkgs
                          C:\Users\MYUSER\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\MYUSER\mambaforge\envs
                          C:\Users\MYUSER\.conda\envs
                          C:\Users\MYUSER\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.10.9 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by jonashaag** [comment]
> I installed mamba as Micromamba

What does this mean?

What's in your `$PATH`?

**Comment by jonashaag** [comment]
I don't recommend having more than one miniconda/miniforge/Anaconda/... installation per system

**Comment by mjohenneken** [comment]
Sorry, i got confused by the naming of the different projects. I mean mambaforge which is a miniforge with mamba in the base env. Miniforge is a miniconda with conda-forge as default channel. Miniconda is the small Anaconda distribution. Micromamba is a reduced binary of mamba binary for CI builds.

mambaforge: https://github.com/conda-forge/miniforge#mambaforge

> I don't recommend having more than one miniconda/miniforge/Anaconda/... installation per system

Thanks I was in doubt whether this is a good idea.

> What's in your $PATH?

C:\Users\MYUSER\mambaforge;C:\Users\MYUSER\mambaforge\Library\mingw-w64\bin;C:\Users\MYUSER\mambaforge\Library\usr\bin;C:\Users\MYUSER\mambaforge\Library\bin;C:\Users\MYUSER\mambaforge\Scripts;C:\Users\MYUSER\mambaforge\bin;C:\Users\MYUSER\miniconda3\condabin;

I guess its an issue that should be addressed by the conda-forge repo. mamba is working flawlessly when installed in my other miniconda install.
