### ISSUE TITLE
Libcurl isolation / powerloader

### ISSUE THREAD

**Issue by Hind-M** [mamba-org/mamba#2336]
In the context of completely isolating `libcurl` and restrict this dependency to [powerloader](https://github.com/mamba-org/powerloader/issues/159), the header inclusion should be removed from:
https://github.com/mamba-org/mamba/blob/main/libmamba/src/api/info.cpp#L20
where it's used to get curl version:
https://github.com/mamba-org/mamba/blob/main/libmamba/src/api/info.cpp#L151

This would be replaced with `powerloader` version...

**Comment by JohanMabille** [comment]
Closing this issue since the integration of powerloader is stopped for now.
