### ISSUE TITLE
Libarchive leftovers removal?

### ISSUE THREAD

**Issue by Hind-M** [mamba-org/mamba#2337]
Libarchive headers are included in:

- https://github.com/mamba-org/mamba/blob/main/libmamba/include/mamba/core/fetch.hpp#L12
(apparently not used?)
- https://github.com/mamba-org/mamba/blob/main/libmamba/src/api/info.cpp#L19
used in
https://github.com/mamba-org/mamba/blob/main/libmamba/src/api/info.cpp#L152
(to get libarchive version (won't be needed in case of complete removal))
- https://github.com/mamba-org/mamba/blob/main/libmamba/src/core/package_handling.cpp
(where it's mainly used)

**Comment by wolfv** [comment]
Are you planning to get rid of `libarchive` entirely? Because I think that will be a bit hard. But yes, could be that there are some unused function sin fetch.cpp now (since we have the streaming extraction0.

**Comment by Hind-M** [comment]
> Are you planning to get rid of `libarchive` entirely? 

Not necessarily, but at least keep it contained in one place and private (I don't know if `powerloader` uses it for example, but it doesn't seem to). To be investigated.
