### ISSUE TITLE
Implement a package "REPL" like Julia has

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#234]
Julia has this feature in the REPL where you press `]` to enter the package mode, and then you can modify your environment. 

It would be quite easy to do something similar for mamba, where instead of one-shot commands one would stay in a REPL and execute the same commands in the REPL. 
The benefit is that we don't need to reload package / repository data into memory so everything will feel super-snappy.

**Comment by wolfv** [comment]
@certik 's https://github.com/certik/terminal has the necessary features for this so we're definitely going to make the switch.

**Comment by wolfv** [comment]
![Screenshot from 2020-05-14 09-50-55](https://user-images.githubusercontent.com/885054/81908001-e834e580-95c8-11ea-95ac-55b07dca9452.png)

**Comment by certik** [comment]
Cool! I can help polish it.  Please report any bugs, or if you want to change any design or API.

**Comment by certik** [comment]
Also let me know if you want to move it to some organization at github rather than my username.
