### ISSUE TITLE
undefined symbol: curl_url_cleanup

### ISSUE THREAD

**Issue by ovo-Tim** [mamba-org/mamba#2355]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

undefined symbol: curl_url_cleanup

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not reproducible with Conda

### Describe your issue

![](https://user-images.githubusercontent.com/116942368/223437086-925a28a7-1637-4e19-a4e6-067d1907bece.png)
![](https://user-images.githubusercontent.com/116942368/222907777-9f55dbb8-4282-443b-8f05-6570878d67f5.png)

### mamba info / micromamba info

```shell
❯ mamba info
Traceback (most recent call last):
  File "/usr/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/tim/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/home/tim/mambaforge/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/home/tim/mambaforge/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: /home/tim/mambaforge/lib/python3.10/site-packages/libmambapy/../../../libmamba.so.2: undefined symbol: curl_url_cleanup
```

### Logs

```shell
❯ mamba info
Traceback (most recent call last):
  File "/usr/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/tim/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 49, in <module>
    import libmambapy as api
  File "/home/tim/mambaforge/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/home/tim/mambaforge/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: /home/tim/mambaforge/lib/python3.10/site-packages/libmambapy/../../../libmamba.so.2: undefined symbol: curl_url_cleanup
```

### ~/.condarc

```yaml
❯ cat ~/.condarc
channels:
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/main/
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/free/
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/cloud/conda-forge/
ssl_verify: true
```

**Comment by ovo-Tim** [comment]
I may found the problent,I installed curl7.26.0 when I install pythonocc-core
![图片](https://user-images.githubusercontent.com/116942368/223448866-dd89da3c-7d7b-4885-af3c-8ab704e22a25.png)

**Comment by ovo-Tim** [comment]
If I use `mamba install curl` first,when I install `pythonocc-core` it will
![图片](https://user-images.githubusercontent.com/116942368/223453651-7f43076f-dbca-482b-b690-372e4c0fae2e.png)

**Comment by GGboy-Zzz** [comment]
I have the sample problem with @ovo-Tim , can you give some suggestions to solve it? it even influence my conda use thanks @jonashaag

**Comment by jonashaag** [comment]
Please go through the troubleshooting guide and open a new ticket if it's still an issue after that.

**Comment by ovo-Tim** [comment]
> I have the sample problem with @ovo-Tim , can you give some suggestions to solve it? it even influence my conda use thanks @jonashaag

@GGboy-Zzz  Just create a new environment and install it. I think `pythonocc` will influence mamba dependencies.

**Comment by GGboy-Zzz** [comment]
but i have install it into base environment, there is a problem with my basic environment. Whenever I use Conda's command line, I will output an error：“Error while loading conda entry point: conda-libmamba-solver (......libmamba.so.2: undefined symbol: curl_url_cleanup )”,which makes me crazy!

**Comment by jonashaag** [comment]
If you're up to switch to Micromamba :)

**Comment by ovo-Tim** [comment]
@GGboy-Zzz I think you have to reinstall mamba. Because you don't have any available package manager now.
