### ISSUE TITLE
How to uninstall  mamba?

### ISSUE THREAD

**Issue by dwygs** [mamba-org/mamba#2365]
I try to install mamba but it's not work. so i want to remove it and reinstall again. 
I try to use this command “conda uninstall mamba” to remove it but received such an error：
![image](https://user-images.githubusercontent.com/92436095/224238752-f564c8c0-f3f3-4114-b21f-6689b6069098.png)

**Comment by Hind-M** [comment]
Did you install it using conda? If so what was the command used? Did you specify the channel using the `-c, --channel` option?

**Comment by dwygs** [comment]
> 

Thanks for your reply，this issue has been resolved by reinstalling anaconda. 
yes,i install it by this command ''conda install mamba -c conda-forge'' ,I think my Python version(3.7) is too low causing the installation to fail, As for the 'CondaMemoryError' , maybe there are too many installation packages in my environment causing problems when ‘Solving environment’

**Comment by dwygs** [comment]
> Did you install it using conda? If so what was the command used? Did you specify the channel using the `-c, --channel` option?

Thanks for your reply，this issue has been resolved by reinstalling anaconda.
yes,i install it by this command ''conda install mamba -c conda-forge'' ,I think my Python version(3.7) is too low causing the installation to fail, As for the 'CondaMemoryError' , maybe there are too many installation packages in my environment causing problems when ‘Solving environment’
