### ISSUE TITLE
Change clang-format rules

### ISSUE THREAD

**Issue by Hind-M** [mamba-org/mamba#2368]
Because of #2290 and `includes` sorting, it may happen quite often that local/mamba headers are included before third party libraries or even c++ standard library headers which is not recommended and prone to bugs.
cc @AntoinePrv

**Comment by AntoinePrv** [comment]
I would also like to get rid of that! It seems that it is a hard-coded rule in clang-format header sorting that the header "matching" the cpp file is put at the top.
