### ISSUE TITLE
Cannot create an environment if the target prefix is an empty folder

### ISSUE THREAD

**Issue by peterschmidt85** [mamba-org/mamba#2402]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Search tried in issue tracker

is:issue Non-conda folder exists at prefix 

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not reproducible with Conda

### Describe your issue

I'm running `micromamba` in a Docker container, where I'm creating a new environment and intending to save it as an output artifact.

To save the environment, I mount the target folder within the container to a local folder.

```bash
docker run -v $(pwd)/envs/myenvs:/opt/conda/envs/myenv mambaorg/micromamba bash -c "micromamba create -n myenv pandas -c conda-forge -y"
```

This action results in the following error:

```text
error    libmamba Non-conda folder exists at prefix
critical libmamba Aborting.
```

This error occurs because `micromamba` expects the target folder to be non-existent. However, in my case, this is not possible.

Note that both conda and miniforge work perfectly.

Additional notes:

This issue is a significant impediment to integrating `micromamba` with [https://github.com/dstackai/dstack](https://github.com/dstackai/dstack).

A possible solution could be to make the default behavior the same as `conda` and `miniforge` by allowing the empty target folder. Alternatively, a configuration option or an environment variable could disable this check.

### mamba info / micromamba info

```shell
environment : base (active)
           env location : /opt/conda
      user config files : /home/mambauser/.mambarc
 populated config files :
       libmamba version : 1.4.0
     micromamba version : 1.4.0
           curl version : libcurl/7.88.1 OpenSSL/3.1.0 zlib/1.2.13 zstd/1.5.2 libssh2/1.10.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       virtual packages : __unix=0=0
                          __linux=5.15.49=0
                          __glibc=2.31=0
                          __archspec=1=aarch64
               channels :
       base environment : /opt/conda
               platform : linux-aarch64
```

**Comment by jonashaag** [comment]
As a workaround can you mount `env/` instead?

**Comment by peterschmidt85** [comment]
@jonashaag Thanks for coming back.

I attempted the workaround that you suggested, but it led to another issue.

```bash
docker run -v $(pwd)/envs:/opt/conda/envs mambaorg/micromamba bash -c "micromamba create -v -n myenv pandas -c conda-forge -y"
```

Here's the output:

```
critical libmamba filesystem error: cannot copy: Permission denied [/opt/conda/pkgs/libstdcxx-ng-12.2.0-hc13a102_19/lib/libstdc++.so.6.0.30] [/opt/conda/envs/myenv/lib/libstdc++.so.6.0.30]
```

Do you have any ideas on what might be causing this problem?"

**Comment by jonashaag** [comment]
Ah yeah it's trying to hardlink but `pkgs/` and `envs/` are on different file systems (one is a mount and the other is inside Docker). Looks like you need to mount the entire `/opt/conda` or disable hardlinking (not sure if that's implemented)

**Comment by jonashaag** [comment]
If my hypothesis is correct then maybe we should be falling back to copying instead of hardlinking in case of an error

**Comment by peterschmidt85** [comment]
I tried to use the `--always-copy` flag; however, it did not prove helpful as it continued to attempt a soft-link. 

Does this imply that `--always-copy` is not yet supported? It would be beneficial to have this feature supported.

**Comment by peterschmidt85** [comment]
Together with @wolfv, we found out that the problem is caused by VirtioFS (the new Docker file-sharing implementation). If I switch from VirtioFS to gRPC FUSE, the `Permission denied` issue goes away.

Here's a related issue in the Docker repo: https://github.com/docker/for-mac/issues/6243
