### ISSUE TITLE
Micromamba create env doesn't show the message about how to activate the environment

### ISSUE THREAD

**Issue by xmnlab** [mamba-org/mamba#2407]
Currently, when we create a new environment with micromamba it doesn't show a message explaining how to activate the new environment.

## Expected

It would be nice to have something like:

```
To activate this environment, use

     $ micromamba activate mynewenvironment

```

**Comment by xmnlab** [comment]
if there is no objection, I can work on this issue :)

**Comment by JohanMabille** [comment]
Sure, any help is very welcome!

**Comment by xmnlab** [comment]
Nice, I working on that! thanks!

**Comment by wholtz** [comment]
I would like to see it also inform the user about the very useful `micromamba run ...` option....

```
To activate this environment, use

     $ micromamba activate mynewenvironment

Or to execute a single command in this environment,  use

    $ micromamba run -n mynewenvironment mycommand

```
