### ISSUE TITLE
is "No other packages should be installed to base" outdated?

### ISSUE THREAD

**Issue by petrelharp** [mamba-org/mamba#2444]
In [the documentation](https://mamba.readthedocs.io/en/latest/user_guide/troubleshooting.html#no-other-packages-should-be-installed-to-base) it states that
> Installing packages other than Conda and Mamba into the base environment is not supported. Mamba must live in the same environment as Conda, and Conda does not support having packages other than Conda itself and its dependencies in base.

Is this still accurate, given the [current recommendation](https://mamba.readthedocs.io/en/latest/installation.html) to *not* install mamba using an existing conda, but rather using mambaforge?

If so, this presents a problem, because some packages, notably jupyter (see [here](https://stackoverflow.com/questions/64090066/different-jupyterlab-working-directories-for-different-environments) or [here](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/867) for instance), have global (user-level) configuration and data and so are not really designed to be installed in separate conda environments, and so ought to be installed globally (i.e., in base?). So if it is still true it would be helpful to clarify *why* it is not supported.

(ps. thanks!!!)

**Comment by jonashaag** [comment]
No, this is still up to date. Mambaforge will provide you with a base environment with Conda and Mamba installed.

The problem with installing things to base is that it may break Conda and Mamba, eg. if some funny versions of libraries are installed. Unfortunately not all potential problems are covered by the version pins imposed by Conda and Mamba. Also, sometimes you might accidentally downgrade Conda or Mamba if installing other packages.

Maybe it is safe to install Jupyter into base. If it works for you that's fine!

**Comment by petrelharp** [comment]
Thanks for the clarification! And, all the good work. Moving ahead, with fingers crossed...
