### ISSUE TITLE
`mamba info` seems to not include the Mamba version

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#2458]
In some/all? of the bug reports we see `mamba info` output that doesn’t include the mamba version. It’s very important for diagnosis though

**Comment by Hind-M** [comment]
That's because we use `conda info` which doesn't have this info. The `mamba` version is included in the banner though, but I guess that bug reports and such disable it.
We could add the `mamba` version to `conda` output but I'm wondering if it's better to leave it to the upcoming "refactoring" to plug everything to libmamba ant stop using `conda`...
Micromamba's output seems much more relevant...

```
environment : /home/hind/miniconda3/envs/test_micromamba (active)
env location : /home/hind/miniconda3/envs/test_micromamba
user config files : /home/hind/.mambarc
populated config files : 
libmamba version : 1.4.2
micromamba version : 1.4.2
curl version : libcurl/7.82.0 OpenSSL/3.1.0 zlib/1.2.13 libssh2/1.10.0 nghttp2/1.47.0
libarchive version : libarchive 3.5.2 zlib/1.2.12 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.2
virtual packages : __unix=0=0
              __linux=5.14.0=0
              __glibc=2.31=0
              __archspec=1=x86_64
   channels : 
base environment : /home/hind/micromamba
   platform : linux-64
```

**Comment by Hind-M** [comment]
We could also plug it directly to use libmamba's `info` in the same way as `install`, `create`, ...
This will depend on how we would want to do the plugging at the end.

**Comment by Klaim** [comment]
I think the timing to get to not using conda is too far and we should probably inject the version in the output yeah

**Comment by Hind-M** [comment]
Well actually I think that even the ugly workaround wouldn't probably work because of the `json` format case (which is printed in `conda`'s code), and I guess that's what the bug reports ask for...

**Comment by AntoinePrv** [comment]
> I think that appending the mamba version to conda's output would be a bit ugly but can still be a "temporary" workaround...

I think that's a good workaround

> Well actually I think that even the ugly workaround wouldn't probably work because of the json format case (which is printed in conda's code),

Maybe in that case we can override `print` with a context manager to get the output to a string, parse it, add en entry, and serialize it again. Even dirtier, but I think it's acceptable given the future of mamba.

**Comment by Klaim** [comment]
The json case must not log indeed, but nothing prevent from adding an extra field in the top-level json object?

**Comment by Hind-M** [comment]
> EDIT: even better, [contextlib.redirect_stdout](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout)

Yep!

**Comment by Hind-M** [comment]
> The json case must not log indeed, but nothing prevent from adding an extra field in the top-level json object?

Well it's logged in `conda` using python `logging`... Anyway, I submitted a PR for the "ugly" fix.
