### ISSUE TITLE
  - package rgi-6.0.2-pyha8f3691_0 requires lxml 4.6.5, but none of the providers can be installed

### ISSUE THREAD

**Issue by hazmup** [mamba-org/mamba#2514]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

N/A

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

I am trying to use the rgi package in a snakemake pipeline that creates a dedicated rgi environment.

I also tried installing on a regular conda env and got the same error with more detail. I have tried installing the latest version of mambaforge and snakemake fresh.

When running the pipeline I am getting the following:
```bash
CreateCondaEnvironmentException:
Could not create conda environment from envs/rgi.yaml:
Command:
mamba env create --quiet --file ".snakemake/conda/f3d6759e159ec196e8194997c9a3badd_.yaml" --prefix "snakemake/conda/f3d6759e159ec196e8194997c9a3badd_"
Output:
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
Could not solve for environment specs
The following package could not be installed
└─ rgi 6.0.2** is uninstallable because it requires
└─ biopython 1.78.* , which conflicts with any installable versions previously reported.
```

Before updating mambaforge I was getting a different error, which was:
```bash
CreateCondaEnvironmentException:
Could not create conda environment from /users/pa22/sgkionis/envs/rgi.yaml:
Command:
mamba env create --quiet --file "/users/pa22/sgkionis/.snakemake/conda/5c021401d755900074c6e4e5ddab192f_.yaml" --prefix "/users/pa22/sgkionis/.snakemake/conda/5c021401d755900074c6e4e5ddab192f_"
Output:
Could not solve for environment specs
Encountered problems while solving:

    package rgi-6.0.2-pyha8f3691_0 requires lxml 4.6.5, but none of the providers can be installed

The environment can't be solved, aborting the operation
```

This is on a computer cluster running SLURM.

### mamba info / micromamba info

```shell
active environment : base
    active env location : /users/pa22/sgkionis/mambaforge
            shell level : 1
       user config file : /users/pa22/sgkionis/.condarc
 populated config files : /users/pa22/sgkionis/mambaforge/.condarc
                          /users/pa22/sgkionis/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /users/pa22/sgkionis/mambaforge  (writable)
      conda av data dir : /users/pa22/sgkionis/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /users/pa22/sgkionis/mambaforge/pkgs
                          /users/pa22/sgkionis/.conda/pkgs
       envs directories : /users/pa22/sgkionis/mambaforge/envs
                          /users/pa22/sgkionis/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.10 Linux/3.10.0-1160.88.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 1718:1709
             netrc file : None
           offline mode : False
```

### environment.yml

```yaml
channels:
  - bioconda
  - conda-forge
dependencies:
  - rgi = 6.0.2
```

### ~/.condarc

```yaml
channels:
  - conda-forge
channel_priority: strict
```

**Comment by jonashaag** [comment]
Is it because of the strict channel prio?

**Comment by hazmup** [comment]
After changing to channel-prio: true I get the following error:
`CreateCondaEnvironmentException:
Could not create conda environment from /users/pa22/sgkionis/envs/rgi.yaml:
Command:
mamba env create --quiet --file "/users/pa22/sgkionis/.snakemake/conda/f3d6759e159ec196e8194997c9a3badd_.yaml" --prefix "/users/pa22/sgkionis/.snakemake/conda/f3d6759e159ec196e8194997c9a3badd_"
Output:
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
error    libmamba Error opening for reading "/users/pa22/sgkionis/mambaforge/envs/snakemake/pkgs/python-3.8.5-h4d41432_2_cpython/info/index.json": No such file or directory
error    libmamba Error when extracting package: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
error    libmamba Error when extracting package: [json.exception.type_error.316] invalid UTF-8 byte at index 0: 0x80
error    libmamba Error when extracting package: std::bad_alloc
error    libmamba Error when extracting package: std::bad_alloc

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/users/pa22/sgkionis/mambaforge/envs/snakemake/lib/python3.11/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/users/pa22/sgkionis/mambaforge/envs/snakemake/lib/python3.11/site-packages/conda_env/cli/main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/users/pa22/sgkionis/mambaforge/envs/snakemake/lib/python3.11/site-packages/conda/notices/core.py", line 121, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/users/pa22/sgkionis/mambaforge/envs/snakemake/lib/python3.11/site-packages/conda_env/cli/main_create.py", line 152, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/users/pa22/sgkionis/mambaforge/envs/snakemake/lib/python3.11/site-packages/mamba/mamba_env.py", line 153, in mamba_install
        transaction.fetch_extract_packages()
    RuntimeError: Resource temporarily unavailable

`$ /users/pa22/sgkionis/mambaforge/envs/snakemake/bin/mamba create --quiet --file /users/pa22/sgkionis/.snakemake/conda/f3d6759e159ec196e8194997c9a3badd_.yaml --prefix /users/pa22/sgkionis/.snakemake/conda/f3d6759e159ec196e8194997c9a3badd_`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=snakemake
                CONDA_EXE=/users/pa22/sgkionis/mambaforge/bin/conda
             CONDA_PREFIX=/users/pa22/sgkionis/mambaforge/envs/snakemake
           CONDA_PREFIX_1=/users/pa22/sgkionis/mambaforge
    CONDA_PROMPT_MODIFIER=(snakemake)
         CONDA_PYTHON_EXE=/users/pa22/sgkionis/mambaforge/bin/python
               CONDA_ROOT=/users/pa22/sgkionis/mambaforge/envs/snakemake
              CONDA_SHLVL=2
                    CPATH=/apps/EL7/COMMON/compilers/intel/18.0.5/ipp/include:/apps/EL7/COMMON/c
                          ompilers/intel/18.0.5/mkl/include:/apps/EL7/COMMON/compilers/intel/18.
                          0.5/tbb/include
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/apps/EL7/COMMON/compilers/intel/18.0.5/debugger_2018/gdb/intel64/shar
                          e/info:/apps/EL7/COMMON/compilers/intel/18.0.5/debugger_2018/gdb/intel
                          64_mic/share/info
          LD_LIBRARY_PATH=/apps/EL7/COMMON/compilers/intel/18.0.5/impi/2018.4.274/intel64/lib:/a
                          pps/EL7/COMMON/compilers/intel/18.0.5/compilers_and_libraries/linux/co
                          mpiler/lib/intel64:/apps/EL7/COMMON/compilers/intel/18.0.5/tbb/lib/int
                          el64/gcc4.4:/apps/EL7/COMMON/compilers/intel/18.0.5/ipp/tools/intel64/
                          perfsys:/apps/EL7/COMMON/compilers/intel/18.0.5/mkl/lib/intel64:/apps/
                          EL7/COMMON/compilers/intel/18.0.5/debugger_2018/libipt/intel64/lib:/ap
                          ps/EL7/COMMON/compilers/intel/18.0.5/ipp/lib/intel64:/apps/EL7/COMMON/
                          compilers/intel/18.0.5/compilers_and_libraries/linux/lib/intel64:/apps
                          /EL7/COMMON/compilers/gnu/8.5.0/lib64:/apps/EL7/COMMON/compilers/gnu/8
                          .5.0/lib
               LD_PRELOAD=<not set>
             LIBRARY_PATH=/apps/EL7/COMMON/compilers/intel/18.0.5/lib/intel64:/apps/EL7/COMMON/c
                          ompilers/intel/18.0.5/ipp/lib/intel64:/apps/EL7/COMMON/compilers/intel
                          /18.0.5/mkl/lib/intel64:/apps/EL7/COMMON/compilers/intel/18.0.5/tbb/li
                          b/intel64/gcc4.4
        LMOD_PACKAGE_PATH=/apps/EL7/COMMON/modulefiles/config
                  MANPATH=/apps/EL7/COMMON/compilers/intel/18.0.5/impi/2018.4.274/man/common:/ap
                          ps/EL7/COMMON/compilers/intel/18.0.5/man/common:/apps/EL7/COMMON/compi
                          lers/intel/18.0.5/debugger_2018/gdb/intel64/share/man:/apps/EL7/COMMON
                          /compilers/intel/18.0.5/debugger_2018/gdb/intel64_mic/share/man::/apps
                          /EL7/COMMON/compilers/gnu/8.5.0/share/man:/usr/share/lmod/lmod/share/m
                          an
      MIC_LD_LIBRARY_PATH=/apps/EL7/COMMON/compilers/intel/18.0.5/compilers_and_libraries/linux/
                          compiler/lib/mic:/apps/EL7/COMMON/compilers/intel/18.0.5/mpirt/lib/mic
                          :/apps/EL7/COMMON/compilers/intel/18.0.5/compiler/lib/mic:/apps/EL7/CO
                          MMON/compilers/intel/18.0.5/mkl/lib/mic:/apps/EL7/COMMON/compilers/int
                          el/18.0.5/tbb/lib/mic
         MIC_LIBRARY_PATH=/apps/EL7/COMMON/compilers/intel/18.0.5/lib/mic:/apps/EL7/COMMON/compi
                          lers/intel/18.0.5/mpirt/lib/mic:/apps/EL7/COMMON/compilers/intel/18.0.
                          5/tbb/lib/mic
               MODULEPATH=/apps/EL7/COMMON/modulefiles/compilers:/apps/EL7/COMMON/modulefiles/pa
                          rallel:/apps/EL7/COMMON/modulefiles/libraries:/apps/EL7/COMMON/modulef
                          iles/applications:/apps/EL7/COMMON/modulefiles/tools:/apps/EL7/IVY/mod
                          ulefiles/parallel:/apps/EL7/IVY/modulefiles/libraries:/apps/EL7/IVY/mo
                          dulefiles/applications:/apps/EL7/IVY/modulefiles/tools
                  NLSPATH=/apps/EL7/COMMON/compilers/intel/18.0.5/lib/intel64/locale/%l_%t/%N:/a
                          pps/EL7/COMMON/compilers/intel/18.0.5/ipp/lib/intel64/locale/%l_%t/%N:
                          /apps/EL7/COMMON/compilers/intel/18.0.5/mkl/lib/intel64/locale/%l_%t/%
                          N:/apps/EL7/COMMON/compilers/intel/18.0.5/debugger_2018/gdb/intel64_mi
                          c/share/locale/%l_%t/%N:/apps/EL7/COMMON/compilers/intel/18.0.5/debugg
                          er_2018/gdb/intel64/share/locale/%l_%t/%N
                     PATH=/users/pa22/sgkionis/mambaforge/envs/snakemake/bin:/users/pa22/sgkioni
                          s/mambaforge/condabin:/apps/EL7/COMMON/compilers/intel/18.0.5/impi/201
                          8.4.274/intel64/bin:/apps/EL7/COMMON/compilers/intel/18.0.5/vtune_ampl
                          ifier/bin64:/apps/EL7/COMMON/compilers/intel/18.0.5/debugger_2018/gdb/
                          intel64_mic/bin:/apps/EL7/COMMON/compilers/intel/18.0.5/bin:/apps/EL7/
                          COMMON/compilers/gnu/8.5.0/bin:/usr/local/bin:/usr/bin:/usr/local/sbin
                          :/usr/sbin:/opt/ibutils/bin:/usr/lpp/mmfs/bin:/users/pa22/sgkionis/bin
          PKG_CONFIG_PATH=/apps/EL7/COMMON/compilers/gnu/8.5.0/lib64/pkgconfig:/apps/EL7/COMMON/
                          compilers/gnu/8.5.0/lib/pkgconfig
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
   __LMOD_REF_COUNT_CPATH=/apps/EL7/COMMON/compilers/intel/18.0.5/ipp/include:1;/apps/EL7/COMMON
                          /compilers/intel/18.0.5/mkl/include:1;/apps/EL7/COMMON/compilers/intel
                          /18.0.5/tbb/include:1
__LMOD_REF_COUNT_INFOPATH=/apps/EL7/COMMON/compilers/intel/18.0.5/debugger_2018/gdb/intel64/shar
                          e/info:1;/apps/EL7/COMMON/compilers/intel/18.0.5/debugger_2018/gdb/int
                          el64_mic/share/info:1
__LMOD_REF_COUNT_LD_LIBRARY_PATH=/apps/EL7/COMMON/compilers/intel/18.0.5/impi/2018.4.274/intel64/lib:1;
                          /apps/EL7/COMMON/compilers/intel/18.0.5/compilers_and_libraries/linux/
                          compiler/lib/intel64:1;/apps/EL7/COMMON/compilers/intel/18.0.5/tbb/lib
                          /intel64/gcc4.4:1;/apps/EL7/COMMON/compilers/intel/18.0.5/ipp/tools/in
                          tel64/perfsys:1;/apps/EL7/COMMON/compilers/intel/18.0.5/mkl/lib/intel6
                          4:1;/apps/EL7/COMMON/compilers/intel/18.0.5/debugger_2018/libipt/intel
                          64/lib:1;/apps/EL7/COMMON/compilers/intel/18.0.5/ipp/lib/intel64:1;/ap
                          ps/EL7/COMMON/compilers/intel/18.0.5/compilers_and_libraries/linux/lib
                          /intel64:1;/apps/EL7/COMMON/compilers/gnu/8.5.0/lib64:1;/apps/EL7/COMM
                          ON/compilers/gnu/8.5.0/lib:1
__LMOD_REF_COUNT_LIBRARY_PATH=/apps/EL7/COMMON/compilers/intel/18.0.5/lib/intel64:1;/apps/EL7/COMMON
                          /compilers/intel/18.0.5/ipp/lib/intel64:1;/apps/EL7/COMMON/compilers/i
                          ntel/18.0.5/mkl/lib/intel64:1;/apps/EL7/COMMON/compilers/intel/18.0.5/
                          tbb/lib/intel64/gcc4.4:1
 __LMOD_REF_COUNT_MANPATH=/apps/EL7/COMMON/compilers/intel/18.0.5/impi/2018.4.274/man/common:1;/
                          apps/EL7/COMMON/compilers/intel/18.0.5/man/common:2;/apps/EL7/COMMON/c
                          ompilers/intel/18.0.5/debugger_2018/gdb/intel64/share/man:1;/apps/EL7/
                          COMMON/compilers/intel/18.0.5/debugger_2018/gdb/intel64_mic/share/man:
                          1;/apps/EL7/COMMON/compilers/gnu/8.5.0/share/man:1;/usr/share/lmod/lmo
                          d/share/man:1
__LMOD_REF_COUNT_MIC_LD_LIBRARY_PATH=/apps/EL7/COMMON/compilers/intel/18.0.5/compilers_and_libraries/linux/
                          compiler/lib/mic:1;/apps/EL7/COMMON/compilers/intel/18.0.5/mpirt/lib/m
                          ic:1;/apps/EL7/COMMON/compilers/intel/18.0.5/compiler/lib/mic:1;/apps/
                          EL7/COMMON/compilers/intel/18.0.5/mkl/lib/mic:1;/apps/EL7/COMMON/compi
                          lers/intel/18.0.5/tbb/lib/mic:1
__LMOD_REF_COUNT_MIC_LIBRARY_PATH=/apps/EL7/COMMON/compilers/intel/18.0.5/lib/mic:1;/apps/EL7/COMMON/com
                          pilers/intel/18.0.5/mpirt/lib/mic:1;/apps/EL7/COMMON/compilers/intel/1
                          8.0.5/tbb/lib/mic:1
__LMOD_REF_COUNT_MODULEPATH=/apps/EL7/COMMON/modulefiles/compilers:1;/apps/EL7/COMMON/modulefiles/
                          parallel:1;/apps/EL7/COMMON/modulefiles/libraries:1;/apps/EL7/COMMON/m
                          odulefiles/applications:1;/apps/EL7/COMMON/modulefiles/tools:1;/apps/E
                          L7/IVY/modulefiles/parallel:1;/apps/EL7/IVY/modulefiles/libraries:1;/a
                          pps/EL7/IVY/modulefiles/applications:1;/apps/EL7/IVY/modulefiles/tools
                          :1
 __LMOD_REF_COUNT_NLSPATH=/apps/EL7/COMMON/compilers/intel/18.0.5/lib/intel64/locale/%l_%t/%N:1;
                          /apps/EL7/COMMON/compilers/intel/18.0.5/ipp/lib/intel64/locale/%l_%t/%
                          N:1;/apps/EL7/COMMON/compilers/intel/18.0.5/mkl/lib/intel64/locale/%l_
                          %t/%N:1;/apps/EL7/COMMON/compilers/intel/18.0.5/debugger_2018/gdb/inte
                          l64_mic/share/locale/%l_%t/%N:1;/apps/EL7/COMMON/compilers/intel/18.0.
                          5/debugger_2018/gdb/intel64/share/locale/%l_%t/%N:1
    __LMOD_REF_COUNT_PATH=/apps/EL7/COMMON/compilers/intel/18.0.5/impi/2018.4.274/intel64/bin:1;
                          /apps/EL7/COMMON/compilers/intel/18.0.5/vtune_amplifier/bin64:1;/apps/
                          EL7/COMMON/compilers/intel/18.0.5/debugger_2018/gdb/intel64_mic/bin:1;
                          /apps/EL7/COMMON/compilers/intel/18.0.5/bin:1;/apps/EL7/COMMON/compile
                          rs/gnu/8.5.0/bin:1;/usr/local/bin:1;/usr/bin:1;/usr/local/sbin:1;/usr/
                          sbin:1;/opt/ibutils/bin:1;/usr/lpp/mmfs/bin:1
__LMOD_REF_COUNT_PKG_CONFIG_PATH=/apps/EL7/COMMON/compilers/gnu/8.5.0/lib64/pkgconfig:1;/apps/EL7/COMMO
                          N/compilers/gnu/8.5.0/lib/pkgconfig:1

     active environment : base
    active env location : /users/pa22/sgkionis/mambaforge/envs/snakemake
            shell level : 2
       user config file : /users/pa22/sgkionis/.condarc
 populated config files : /users/pa22/sgkionis/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.11.3.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /users/pa22/sgkionis/mambaforge/envs/snakemake  (writable)
      conda av data dir : /users/pa22/sgkionis/mambaforge/envs/snakemake/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /users/pa22/sgkionis/mambaforge/envs/snakemake/pkgs
                          /users/pa22/sgkionis/.conda/pkgs
       envs directories : /users/pa22/sgkionis/mambaforge/envs/snakemake/envs
                          /users/pa22/sgkionis/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.29.0 CPython/3.11.3 Linux/3.10.0-1160.88.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 1718:1709
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

error    libmamba Error when extracting package: basic_string::_M_construct null not valid
error    libmamba Error when extracting package: [json.exception.type_error.316] invalid UTF-8 byte at index 1: 0x6A
error    libmamba Error when extracting package: basic_string::_M_create
error    libmamba Error when extracting package: std::bad_alloc
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
`

**Comment by hazmup** [comment]
Before updating mamba, I tried installing the rgi package on a separate regular env and it worked fine. Although I might have not specified a version, so it installed a very earlier one.

**Comment by hazmup** [comment]
users on /users type gpfs (rw,relatime)

**Comment by jonashaag** [comment]
Yeah GPFS is a network file system, those sometimes cause trouble. If you can, put the environment on a non-network file system.

**Comment by hazmup** [comment]
All the available locations on the cluster are GPFS, so I don't think I can do that. Do you think it would work if I revert back to a previous version of mamba? Because no nothing is running.

**Comment by jonashaag** [comment]
I'm not an expert on network filesystems so I don't know. I would be surprised if the problem was because of an update...

You'll see a lot of bug reports about network filesystems on this bug tracker. Maybe you can install the environment to `/tmp` if it has enough space. Maybe removing the entire Mambaforge installation and installing it again will help.

**Comment by hazmup** [comment]
Thank you for all your help so far.

> Maybe you can install the environment to /tmp if it has enough space.

How can I do that?

**Comment by hazmup** [comment]
Thank again. What worked for me eventually was to manually delete the environment and let snakemake recreate it on the next run. Removing mambaforge did not remove the environments snakemake had left.
