### ISSUE TITLE
micromamba v1.4.4 not available from https://micro.mamba.pm/

### ISSUE THREAD

**Issue by wholtz** [mamba-org/mamba#2536]
Conda forge and https://micro.mamba.pm/api/micromamba/linux-64/latest still do not have the v1.4.4 release of micromamba.

**Comment by RoyiAvital** [comment]
Also for Windows https://micro.mamba.pm/api/micromamba/win-64/latest won't give the `1.44` version.

**Comment by RoyiAvital** [comment]
Also not on https://github.com/mamba-org/micromamba-releases

**Comment by ChiefGokhlayeh** [comment]
Any reason why the web installers are still not updated to 1.4.4?

**Comment by pavelzw** [comment]
Micro.mamba.pm points to the releases from conda-forge which everybody forgot to update. 

https://github.com/conda-forge/micromamba-feedstock/pull/120

**Comment by pavelzw** [comment]
[This](https://github.com/mamba-org/mamba/issues/2595#issue-1758169030) comment explains how the release process currently works and why there are no binaries yet sometimes.

**Comment by pavelzw** [comment]
Thanks to @mikemhenry and @AntoinePrv there now is a 1.4.4 on conda-forge and thus on [mamba-org/micromamba-releases](https://github.com/mamba-org/micromamba-releases) and micro.mamba.pm so this issue can be closed.
