### ISSUE TITLE
micromamba: No channels in initial setup/base

### ISSUE THREAD

**Issue by kfsone** [mamba-org/mamba#2550]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

forge: Mambaforge
mini: curl micro.mamba.pm/install.sh | bash
windows: powershell instructions: https://mamba.readthedocs.io/en/latest/installation.html#windows

### Search tried in issue tracker

no channels

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

Technically an issue with the documentation, but also a pointless barrier to entry

in docker/sandbox,
- follow installation instructions for mambaforge and/or micromamba: https://mamba.readthedocs.io/en/latest/installation.html and others eg https://prefix.dev/docs/mamba/introduction
- attempt to mamba/micromamba install anything

```
(base) PS C:\Users\WDAGUtilityAccount> mm install wheel

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

warning  libmamba No 'channels' specified
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ wheel   does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs
```

in a similar vein, running the Windows mambaforge installer does not ask for or set the MAMBA_FORGE_ROOT, so the user experience is a little odd.

### mamba info / micromamba info

```shell
micro 1.4.3
```

### Logs

```shell
root@625b6930d533:/# micromamba install -v wheel

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

info     libmamba Parsing MatchSpec wheel
warning  libmamba No 'channels' specified
info     libmamba All targets to download are cached
info     libmamba All targets to download are cached
info     libmamba Adding package record to repo __archspec
info     libmamba Adding package record to repo __glibc
info     libmamba Adding package record to repo __linux
info     libmamba Adding package record to repo __unix
info     libmamba Parsing MatchSpec wheel
info     libmamba Parsing MatchSpec wheel
info     libmamba Adding job: wheel
info     libmamba Problem count: 1
info     libmamba Parsing MatchSpec wheel
info     libmamba Parsing MatchSpec wheel
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ wheel   does not exist (perhaps a typo or a missing channel).
info     libmamba Freeing solver.
critical libmamba Could not solve for environment specs
root@625b6930d533:/#
```

### environment.yml

```yaml
n/a
```

### ~/.condarc

```yaml
none created
```

**Comment by jonashaag** [comment]
Good point, we could change the warning that Micromamba prints to also print instructions, and we could extend the docs.

Would be nice if you were to send a PR for one or the other (or both :))!

**Comment by iandol** [comment]
Note that trying to add a default channel using the `config` subcommand also fails:

```
micromamba config --add channels conda-forge
The following arguments were not expected: conda-forge channels --add
```

**Comment by Jn58** [comment]
> Note that trying to add a default channel using the `config` subcommand also fails:
> 
> ```
> micromamba config --add channels conda-forge
> The following arguments were not expected: conda-forge channels --add
> ```

try 
```shell
micromamba config append channels conda-forge
```

**Comment by iandol** [comment]
@Jn58 -- thanks for the pointers. I naively followed the "conceived as a drop-in replacement for conda" documentation. I didn't find this obviously documented (maybe that was me being dumb), so this could be future improvement for the micromamba docs...

**Comment by jonashaag** [comment]
Please make a PR! Thanks :-)

**Comment by Hind-M** [comment]
Closing this as the command is mentioned [here](https://github.com/mamba-org/mamba/blob/main/docs/source/installation/micromamba-installation.rst?plain=1#L141).
