### ISSUE TITLE
mamba--conda update --all (error messge>>CorruptedEnvironmentError: The target environment has been corrupted. Corrupted environments most co...)

### ISSUE THREAD

**Issue by yuanping-Zhou** [mamba-org/mamba#2551]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

executing transaction>>ctrl+c matter

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

when download a package or update the conda using mamba, but the final step "Executing transaction" didn't work:
                                           conda update --all
 I tried to press the "ctrl+c" to stop the the process, cause the errors below:
      CorruptedEnvironmentError: The target environment has been corrupted. Corrupted 
                           environments most co
then when I run the code again, cause the same errors:
what should i do:

**Comment by yuanping-Zhou** [comment]
the full reminder is below!

The target environment has been corrupted. Corrupted environments most commonly
occur when the conda process is force-terminated while in an unlink-link
transaction.
  environment location: /home/yuanping/miniconda3
  corrupted file: /home/yuanping/miniconda3/conda-meta/r-bh-1.81.0_1-r42hc72bb7e_0.json


CorruptedEnvironmentError: The target environment has been corrupted. Corrupted environments most commonly
occur when the conda process is force-terminated while in an unlink-link
transaction.
  environment location: /home/yuanping/miniconda3
  corrupted file: /home/yuanping/miniconda3/conda-meta/r-bh-1.81.0_1-r42hc72bb7e_0.json

**Comment by yuanping-Zhou** [comment]
solution:
the final solution is run :
                            cd ~/minconda3/conda-meta/
                            rm r-bh-1.81.0_1-r42hc72bb7e_0.json
                            mamba install -y  bioconductor-deseq2
but the package still couldn't be installed still.

**Comment by jjerphan** [comment]
We cannot reproduce this issue with 2.0, please update to 2.0.

Feel free to reopen an issue with a reproduce if you still have this issue with 2.0.

Note that 1.x is note being developed anymore, but to address security fixes.
