### ISSUE TITLE
Handling of environment.yaml is confusing

### ISSUE THREAD

**Issue by stefanv** [mamba-org/mamba#2574]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

Yes

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

Mamba's behavior is confusing when it comes to `environment.yaml` files. This is a widely recommended approach for creating conda environments, so even if it is unsupported, it will be tried in practice:

```
$ mamba create -f environment.yaml -n test0
```

The first error the user runs into is:

```
The following package could not be installed
└─ environment.yaml   does not exist (perhaps a typo or a missing channel).
```

Ah, the `-f` flag is not available? Looks like it needs: `--file`:

```
$ mamba create --file environment.yaml -n test0
```

Resulting in:

```
could not parse 'name: test' in: environment.yaml

CondaValueError: could not parse 'name: test' in: environment.yaml
```

Pretty confusing. **Would it be possible to detect this scenario and provide instructions to the user on how to proceed?** From looking around the issue tracker, it sounds like that approach should be:

1. Create an empty environment: `mamba create -n test`
2. Activate the environment: `mamba activate test`
3. Update the environment: `mamba update -n test --file environment.yaml`

That still doesn't work for me (`CondaValueError: could not parse 'name: test' in: environment.yaml`), but is as far as I got.

### mamba info / micromamba info

```shell
active environment : test
    active env location : /home/stefan/mambaforge/envs/test
            shell level : 2
       user config file : /home/stefan/.condarc
 populated config files : /home/stefan/mambaforge/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=6.1.8=0
                          __unix=0=0
       base environment : /home/stefan/mambaforge  (writable)
      conda av data dir : /home/stefan/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/stefan/mambaforge/pkgs
                          /home/stefan/.conda/pkgs
       envs directories : /home/stefan/mambaforge/envs
                          /home/stefan/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.10 Linux/6.1.8-100.fc36.x86_64 fedora/36 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### environment.yml

```yaml
name: test
dependencies:
  - pip
  - pip:
    - --pre --index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple --extra-index-url https://pypi.org/simple
    - matplotlib
```

**Comment by jonashaag** [comment]
Interesting edge case! We should fix this.
