### ISSUE TITLE
Unable to read repodata subdir mismatch (github actions -- however, works fine on local laptop)

### ISSUE THREAD

**Issue by geoHeil** [mamba-org/mamba#2575]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

Unable to read repodata JSO; subdir

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

critical libmamba Unable to read repodata JSON file 'pkgs/main/linux-64', error was: parse error line 593230: subdir mismatch

Strangely, when manually executing the environment yaml on my laptop (osx, m2, in rosetta mode) it works fine. I can only discover this issue in CI/github actions (platform linux x86). There, however also persistently when caches are deleted

### mamba info / micromamba info

```shell
# syntax=docker/dockerfile:1.5.2
FROM mambaorg/micromamba:1.4.3 AS builder

COPY  environment.yml /tmp/env.yaml
RUN micromamba install -y --name base -f /tmp/env.yaml && \ 
    micromamba clean --all --yes --force-pkgs-dirs --tarballs

```

### Logs

```shell
critical libmamba Unable to read repodata JSON file 'pkgs/main/linux-64', error was: parse error line 593230: subdir mismatch
```

### environment.yml

> EDIT: even with this simplified environment yml file I can reproduce the issue

```yaml
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - pandas<3
  - pip
  - grpcio<=1.48.1
  - pip:
      - dagster==1.3.9
  
```

### ~/.condarc

```yaml
none/see dockerfile
mambaorg/micromamba:1.4.3
```

**Comment by smileness** [comment]
I have same issue, just started from this morning .
Yesterday same Docker File build did great but not today

**Comment by geoHeil** [comment]
Seems to be an exact duplicate of : https://github.com/mamba-org/mamba/issues/2363 - closing here to focus the discussion

**Comment by Alex-Lewandowski** [comment]
This issue just started for us today as well.
