### ISSUE TITLE
action: completion not in {init,deinit,reinit,hook,activate,deactivate,reactivate}

### ISSUE THREAD

**Issue by Whisht** [mamba-org/mamba#2576]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

completion

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

1. Install `micromamba` with `brew install micromamba`
2. Config `~/.mamabarc` with only `conda-forge` channels set.
3. After running `micromamba shell completion`, I got this error `action: completion not in {init,deinit,reinit,hook,activate,deactivate,reactivate}`.

Noticing that I didn't install conda, only set `.condarc` .

### mamba info / micromamba info

```shell
__  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/


            environment : base (active)
           env location : /Users/mac/micromamba
      user config files : /Users/mac/.mambarc
 populated config files : /Users/mac/.mambarc
                          /Users/mac/.condarc
       libmamba version : 1.4.4
     micromamba version : 1.4.4
           curl version : libcurl/7.88.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0
     libarchive version : libarchive 3.5.3 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8
       virtual packages : __unix=0=0
                          __osx=13.4=0
                          __archspec=1=x86_64
               channels : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nodefaults/osx-64
                          https://conda.anaconda.org/nodefaults/noarch
       base environment : /Users/mac/micromamba
               platform : osx-64
```

### Logs

```shell
action: completion not in {init,deinit,reinit,hook,activate,deactivate,reactivate}
Run with --help for more information.
```

### environment.yml

```yaml
channels:
  - conda-forge
```

### ~/.condarc

```yaml
channels:
 - nodefaults
```

**Comment by jonashaag** [comment]
Thanks for the report! I looks like this was removed long ago in https://github.com/mamba-org/mamba/pull/1304 but we never updated the documentation.

**Comment by Whisht** [comment]
Thanks for your reply. So in the current micromamba, how could I turn on auto-completion? I didn't find other instructions in #1304. I added `autocomplete: true` in `.mambarc`, but nothing happened.

**Comment by jonashaag** [comment]
It should be working out of the box if you use the normal shell activation. What shell are you using?

**Comment by Whisht** [comment]
I used `zsh` as the default shell. I figured out that autocompletion not working because of the terminal tool I used. **In [warp](https://www.warp.dev/) the autocompletion not working** bucased this behavior is overrided by `warp`. Anything works well in `iterm2`. Thanks again.
