### ISSUE TITLE
Document micromamba's support for `conda-lock`

### ISSUE THREAD

**Issue by mfisher87** [mamba-org/mamba#2578]
Some relevant discussion in #1884 

I was pleasantly surprised to find that `micromamba` was able to use my `conda-lock` "unified" lockfile to bootstrap a new environment, and I was confused when `mamba` did not also support it. I looked for but couldn't find:

* A complete list of environment specification formats supported by Mamba (the _Micromamba_ user guide does have this [here](https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html?highlight=environment%20yaml#specification-files))
* Mention of conda-lock's new "unified" lockfile (named `conda-lock.yml` by default) support in the web docs (this [is mentioned in the GitHub README](https://github.com/mamba-org/mamba#installing-lock-files), though!).

I think I'll probably have time to contribute the documentation change in the next two weeks if nobody else has already done it by then. I'll post here or link a (draft) PR when I get started!

One question: Mamba supports the specification file formats that conda does, i.e. [`environment.yml` format](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually) (can be [generated](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#exporting-the-environment-yml-file) with `conda env export`), and [explicit spec files](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#building-identical-conda-environments) (generated with `conda list --explicit`). Does it support any other specification formats I am not aware of?

**Comment by jonashaag** [comment]
It supports line separated requirements, as Conda does, with `mamba create -f`.

I wonder why Mamba doesn’t support lock files since it should be mostly implemented in libmamba which is shared among both.

**Comment by mfisher87** [comment]
>I wonder why Mamba doesn’t support lock files since it should be mostly implemented in libmamba which is shared among both.

I also wonder! In the Mamba user guide, I documented that `mamba` supports all the same specification file formats as `conda`. I figure there's no need to go in depth until `mamba` starts to support more specification formats :)
