### ISSUE TITLE
Add `--target` for `micromamba update`

### ISSUE THREAD

**Issue by BastianZim** [mamba-org/mamba#2581]
It would be great if `micromamba update --all` could not only be run for the currently activated environment but for an environment that is specified with `--target, -t`. Or, alternatively, it would be even better if there would be a `--all-environment` flag that would allow me to update all environments at once.

**Comment by jonashaag** [comment]
For other commands this is done with `-n`/`-p`. Does that not work here?

**Comment by BastianZim** [comment]
Ahh found it – thanks
