### ISSUE TITLE
micromamba reads `~/micromamba/etc/profile.d/micromamba.sh` from older versions

### ISSUE THREAD

**Issue by pavelzw** [mamba-org/mamba#2628]
When using the latest macOS homebrew build of micromamba (https://github.com/Homebrew/homebrew-core/pull/135110), some micromamba commands don't work anymore

```
$ eval "$(micromamba shell hook)" # works
$ micromamba create -n testenv python # works
[...]
$ micromamba run -n testenv python
The following argument was not expected: --shell
Run with --help for more information.
/var/folders/rz/q1r4tv0n6ll38q18fbk419mc0000gn/T/mambafCZWLOVkCne: line 5: exec: python: not found
$ micromamba activate testenv
The following argument was not expected: --shell
Run with --help for more information.
```

**Comment by pavelzw** [comment]
I can also reproduce this behavior with the latest CI static build.

**Comment by AntoinePrv** [comment]
This is the type of errors I had when working on #2538

**Comment by pavelzw** [comment]
Okay so the reason is the following: 

from executing `micromamba shell init` with an older micromamba version, micromamba created a `$HOME/micromamba/etc/profile.d/micromamba.sh` which contained (among others)

```
__mamba_activate() {
    \local ask_conda
    ask_conda="$(PS1="${PS1:-}" __mamba_exe shell --shell bash "$@")" || \return
    \eval "$ask_conda"
    __mamba_hashr
}
```

When upgrading micromamba with homebrew, this file did not change however the CLI format changed which leads to the observed behavior. Apparently this file is read by the current micromamba version and thus `micromamba shell hook` is not the latest version of the shell hooks.

I think micromamba should not read this file at all (and not even create it) but instead micromamba should always use its own shell hooks that are shipped with the binary.

**Comment by jonashaag** [comment]
I agree, we have at least one other issue about this. I think we just need someone to delete this logic from the code base

**Comment by AntoinePrv** [comment]
@pavelzw great work, thank! CLI API are not easy to track, sorry about the regression.

So `micromamba shell init` would make this release work, right?

> When upgrading micromamba with homebrew, this file did not change however the CLI format changed which leads to the observed behavior. Apparently this file is read by the current micromamba version and thus micromamba shell hook is not the latest version of the shell hooks.
>
> I think micromamba should not read this file at all (and not even create it) but instead micromamba should always use its own shell hooks that are shipped with the binary.

I have no objection, every state left on the device is making harder to move forward. I do not have full visibility on this though. Gonna try a PR to start with.

**Comment by AntoinePrv** [comment]
One thing I don't understand is that the initialization of the shell is done with
```bash
# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE="/home/antoine/workspace/github.com/mamba-org/mamba/build/cmake/micromamba/micromamba";
export MAMBA_ROOT_PREFIX="/home/antoine/.local/share/mamba";
__mamba_setup="$("$MAMBA_EXE" shell hook --shell zsh --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    if [ -f "/home/antoine/.local/share/mamba/etc/profile.d/micromamba.sh" ]; then
        . "/home/antoine/.local/share/mamba/etc/profile.d/micromamba.sh"
    else
        export  PATH="/home/antoine/.local/share/mamba/bin:$PATH"  # extra space after export prevents interference from conda init
    fi
fi
unset __mamba_setup
# <<< mamba initialize <<<
```
So `profile.d` should only be read if setting `__mamba_setup` fails. Is that the case for you? I don't have failure there on my end.

**Comment by AntoinePrv** [comment]
> eval "$(micromamba shell hook)" # works

With micromamba 1.4.5, this should also not work. I have "error    libmamba Please provide a shell type."
