### ISSUE TITLE
Troubleshooting: upgrading to micromamba 1.4.5

### ISSUE THREAD

**Issue by JohanMabille** [mamba-org/mamba#2633]
Upgrading to micromamba 1.4.5 from a previous version breaks micromamba with the following error:
```bash
The following argument was not expected: --shell
Run with --help for more information.
```

The fix is to run `./micromamba shell init  -s <your_shell> -p ~/micromamba` after the upgrade.

**Comment by hadim** [comment]
I had the same error. I went back to 1.4.4. I'll try your fix.

**Comment by jjerphan** [comment]
We recommend using the solution provided in the description of the issue or reinstalling micromamba.
