### ISSUE TITLE
`nodefaults` repodata should not be downloaded

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#2638]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

nodefaults

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

I think we should not be downloading https://conda.anaconda.org/nodefaults/noarch etc repodata, but instead special case `nodefaults`.

**Comment by chuston-zvelo** [comment]
Seeing this today:
`RuntimeError: Download error (23) Failed writing received data to disk/application [https://conda.anaconda.org/anaconda/noarch/repodata.json.zst]`

Is this related to the above?

**Comment by jonashaag** [comment]
No but it's being fixed in a PR right now
