### ISSUE TITLE
mamba install from my private  conda proxy server  channel,  happen an error :   Operation too slow. Less than 30 bytes/sec transferred the last 60 seconds

### ISSUE THREAD

**Issue by xiaohaiGit** [mamba-org/mamba#2639]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

no

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

I think Mamba should provide a configuration item to address this issue. I have my own private Conda service built through Nexus. But whenever a package does not exist on the private Conda service, the private Conda service will pull the package from the source, but this process may be lengthy, resulting in Mamba not receiving data within 60 seconds, leading to an error.

I think Mamba should improve this mechanism, such as providing a certain configuration to extend this time, or directly providing a configuration to turn it off.

### mamba info / micromamba info

```shell
I install by command : 
conda install mamba
```

### Logs

```shell
mamba 下载错误 RuntimeError: Download error (28) Timeout was reached [http://172.16.11.226:8081/repository/conda-aliyun/main/linux-64/cudatoolkit-10.1.243-h6bb024c_0.conda]
    Operation too slow. Less than 30 bytes/sec transferred the last 60 seconds
```

### environment.yml

```yaml
no
```

### ~/.condarc

```yaml
no
```

**Comment by jonashaag** [comment]
Please search related issues, there is an environment variable that you can set

**Comment by xiaohaiGit** [comment]
thank you very much . I find a result that "You can use MAMBA_NO_LOW_SPEED_LIMIT=0 as environment variable to disable this behavior."  I will try it

**Comment by xiaohaiGit** [comment]
Hello,

I tried to set the variable as indicated above (MAMBA_NO_LOW_SPEED_LIMIT=1) but without any effect. I still have the same error while trying to install packages.

I passed the export MAMBA_ NO_ LOW_ SPEED_ Limit=0, but I still found an error. Is it because my setting method is incorrect? Can you provide a simple example? Thank you.

**Comment by xiaohaiGit** [comment]
I tried and found that I could eliminate this error，thank you very much.
