### ISSUE TITLE
Can't activate environment

### ISSUE THREAD

**Issue by ManuGraiph** [mamba-org/mamba#2648]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

Can't activate env

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

After upgrading micromamba to version 1.4.5, i can't activate environments, not even base. When i try `micromamba activate <<my_env_here>>`, it says:

"The following argument was not expected: -s"

Any idea what could it be?

### mamba info / micromamba info

```shell
environment : None (not found)
           env location : -
      user config files : /home/<user>/.mambarc
 populated config files : /home/<user>/.condarc
       libmamba version : 1.4.5
     micromamba version : 1.4.5
           curl version : libcurl/7.88.1 OpenSSL/3.1.1 zlib/1.2.13 zstd/1.5.2 libssh2/1.11.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       virtual packages : __unix=0=0
                          __linux=6.3.9=0
                          __glibc=2.37=0
                          __archspec=1=x86_64
                          __cuda=12.2=0
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /home/<user>/micromamba
               platform : linux-64
```

**Comment by Pipboyguy** [comment]
@ManuGraiph refer to https://github.com/mamba-org/mamba/issues/2633. Solves the problem for me

**Comment by ManuGraiph** [comment]
Did the trick for me too!!! Thanks!!
