### ISSUE TITLE
Is there an Anaconda Distribution equivalent in the Mamba ecosystem?

### ISSUE THREAD

**Issue by ubalklen** [mamba-org/mamba#2652]
I want to jump on the Mamba wagon and bring people from my company with me. But one feature I'm missing is the Anaconda Distribution that comes with a lot of data science packages. This is because many of the users here are beginners, and the distribution make it easy for them to start coding. People also like the Anaconda Navigator.

Is there an equivalent of that in Mamba?

**Comment by jonashaag** [comment]
Not that I know of.

**Comment by jjerphan** [comment]
We recommend using the [Miniforge distribution](https://github.com/conda-forge/miniforge) which come with mamba
