### ISSUE TITLE
Micromamba 1.4.7 is no longer able to resolve the anaconda channel in a fresh install

### ISSUE THREAD

**Issue by gab1one** [mamba-org/mamba#2663]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Downloaded micromamba binary, see:
https://github.com/gab1one/micromamba-bug-demonstrator/blob/master/Dockerfile#L8C5-L8C85

### Search tried in issue tracker

micromamba, anaconda channel

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

When trying to create an environment with micromamba 1.4.7, it failed. I did not have this error with previous versions of micromamba with the same environment. It seems to be caused by the `anaconda` channel that can no longer be resolved for some reason in this version.

I made a small demonstrator repo that allows to easily verify this: https://github.com/gab1one/micromamba-bug-demonstrator/tree/master

### mamba info / micromamba info

```shell
libmamba version : 1.4.7
    micromamba version : 1.4.7
          curl version : libcurl/7.88.1 OpenSSL/3.1.1 zlib/1.2.13 zstd/1.5.2 libssh2/1.11.0 nghttp2/1.52.0
    libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
      envs directories : /root/micromamba/envs
         package cache : /root/micromamba/pkgs
                         /root/.mamba/pkgs
           environment : None (not found)
          env location : -
     user config files : /root/.mambarc
populated config files :
      virtual packages : __unix=0=0
                         __linux=6.3.8=0
                         __glibc=2.35=0
                         __archspec=1=x86_64
              channels :
      base environment : /root/micromamba
              platform : linux-64
```

### Logs

```shell
critical libmamba Multiple errors occured:
    Download error (23) Failed writing received data to disk/application [https://conda.anaconda.org/anaconda/noarch/repodata.json.zst]
    Failure writing output to destination
    Subdir pkgs/r/noarch not loaded!
    Subdir anaconda/noarch not loaded!
    Subdir conda-forge/noarch not loaded!
```

### environment.yml

```yaml
name: demo
channels:
  - defaults
  - anaconda
dependencies:
  - python=3.10
```

**Comment by JohanMabille** [comment]
Thanks for reporting, this issue has been fixe din https://github.com/mamba-org/mamba/pull/2661 (not released yet).

**Comment by JohanMabille** [comment]
micromamba and mamba 1.4.8 have been released, we can close this one.

**Comment by gab1one** [comment]
Thank you for the quick fix 🎉

**Comment by dan-blanchard** [comment]
I'm still seeing this issue with micromamba 1.4.9
