### ISSUE TITLE
Running 'mamba create  -n some_env python=3.9' breaks mamba/conda with 'Unable to start process using C:/.../anaconda3/python.exe...' 

### ISSUE THREAD

**Issue by martin-sedlacek** [mamba-org/mamba#2664]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

unable to create process 

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

When I try to create a python 3.9 environment running 'mamba create  -n some_env python=3.9', my entire mamba/conda installation breaks with 'Unable to start process using C:/.../anaconda3/python.exe...'  (see screenshot below):

![mamba_err_log](https://github.com/mamba-org/mamba/assets/24992092/4c6ed810-60fb-41d5-bb9a-d404723ead2f)

In this particular screenshot I tried to install mamba into conda, but the issue happens when I just install mamba forge as well.

After restarting anaconda prompt / miniforge the issue persists and I am no longer able to invoke mamba/conda:

![next_err](https://github.com/mamba-org/mamba/assets/24992092/18a17d15-387a-4429-ab11-e0256446dd41)

I tried to reinstall several times but the issue always appears. Seems like the breaking point occurs when downloading from conda-forge, perhaps I somehow broke my channels since I see nvidia, pytorch3d, and others, which I added manually in the past trying to bypass a different issue.

Any advice as to why this could be happening and how to fix it is appreciated.

### mamba info / micromamba info

```shell
NA - mamba env is broken and I cannot invoke this command
```

### Logs

```shell
(see screenshots in description)
```

**Comment by jjerphan** [comment]
Duplicates of #1717 which has been fixed in 2.0.

Feel free to reopen an issue with a reproduce if you still have this issue with 2.0.
