### ISSUE TITLE
Micromamba colors "list" results, but Mamba doesn't

### ISSUE THREAD

**Issue by morags** [mamba-org/mamba#2677]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

...

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

I've recently tried Micromamba, and found that it colors the results of the `list` command to show whether a package was installed directly by the user, or as a dependency (similar to what [`conda-tree leaves`](https://github.com/conda-incubator/conda-tree) does). Neither Mamba nor Conda provide this useful functionality.

I'm using Windows Pro 64bit, and have tried PowerShell and the Command Line both on their own, and through Windows Terminal and ConEmu.

**Comment by jjerphan** [comment]
Closing since 2.0 unified this behavior on mamba and micromamba.
