### ISSUE TITLE
Micromamba >v1.4.5 broken with cygwin

### ISSUE THREAD

**Issue by 0xbe7a** [mamba-org/mamba#2683]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

yes

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

I'm using micromamba with cygwin. My .bash_profile looks like

```
# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE='/cygdrive/c/Users/USER/.bin/micromamba.exe';
export MAMBA_ROOT_PREFIX='/cygdrive/c/Users/USER/micromamba_prefix';
eval "$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX")"
# <<< mamba initialize <<<
````

With micromamba <=1.4.5 `shell hook --shell bash` checked if `!hook_source_path().empty()` and if true just emitted the file shell hook without substituting `$MAMBA_EXE`. Only if `hook_source_path()` was empty would  `get_hook_contents` be used to emit the shell hook. Crucially `get_hook_contents` replaced `$MAMBA_EXE` with the path to the binary on its own. However, this produces a broken config, as the replaced path is in windows format which cant be opened by cygwins bash. PR #2631 changed the behavior of `shell hook` so that  `get_hook_contents` is always used which breaks my cygwin config.

I'm not really sure how to tackle this problem, but i think a `--no-replace` option for shell hook would solve my issue.

**Comment by jonashaag** [comment]
I think we should use the equivalent of `cygpath -u` for `get_hook_contents` in bash

**Comment by jonashaag** [comment]
I wonder why this hasn't been found in the tests.

**Comment by AntoinePrv** [comment]
Thank you for reporting @0xbe7a 

If I understand correctly, the issue can be solved by using `/unix/like/paths`?
More precisely changing the format [here](https://github.com/mamba-org/mamba/blob/b3b6cd6d07f8badf49f7f746e624a23d024baba8/libmamba/src/core/shell_init.cpp#L534)?
I think it is safe to make it always unix-like when using unix shells.

**Comment by 0xbe7a** [comment]
Yes, i think the assumption should hold in general and would solve my issue!

**Comment by 0xbe7a** [comment]
I can't build micromamba in the enterprise enviroment im using. I could test out the artifacts from the CI builds, however the CI Build [micromamba - win-64](https://github.com/mamba-org/mamba/actions/runs/5587615116/jobs/10213210706#logs) is failing

**Comment by 0xbe7a** [comment]
I was able to build micromamba using a nasm from archive.org:
https://github.com/0xbe7a/mamba/actions/runs/5592226011

**Comment by pavelzw** [comment]
> That should be a temporary VCPKG issue 🤞

Let's hope https://github.com/microsoft/vcpkg/issues/32600 is fixed soon 😅

**Comment by jonashaag** [comment]
I'll reopen because it's not fixed.

**Comment by goyalyashpal** [comment]
as this is related with unix shells on windows, saying just for recrods; that micromamba 1.4.9 works fine with msys2 3.4.7.x86_64.

**Comment by goyalyashpal** [comment]
> I'm using msys2 with zsh as shell(not Git Bash) but I cannot get micromamba working

hi! i may have helped, but i don't have enough information. read here: https://tinyurl.com/stack-checklist/

**Comment by vickunwu** [comment]
> > I'm using msys2 with zsh as shell(not Git Bash) but I cannot get micromamba working
> 
> hi! i may have helped, but i don't have enough information. read here: https://tinyurl.com/stack-checklist/

@goyalyashpal 
I've managed to get the micromamba auto completion works by modifying the following line in my rc file:
`eval "$("$MAMBA_EXE" shell hook --shell ${SHELL##*/} --root-prefix "$MAMBA_ROOT_PREFIX" | sed "s#$(cygpath -w $MAMBA_EXE|sed 's|\\|\\\\|g')#$MAMBA_EXE#g")"`

The reason I did this is that msys2 do not recognize windows path (e.g. 'C:\micromamba\micromamba.exe') that called in the shell hook.

But when I tried to activate a certain env, here's the output:
```zsh
(eval):.:7: no such file or directory: C:\Users\vickunwu\scoop\persist\micromamba\mamba\envs\whisperx\etc\conda\activate.d\openssl_activate.sh^M
```
I guess it's the same issue but this time I'm not able to do hacks anymore as it's controlled by the program.

**Comment by goyalyashpal** [comment]
> msys_shell.cmd to spawn a mingw64 session in Windows terminal

that script is no longer required as there are dedicated .exe launchers now.

but i launch the bash session _directly_ from konsole or wezterm terminal. konsole allows picking default shell in its settings - i picked bash there.

i have faint memory it _might_ be related to that, but can't say for sure

**Comment by goyalyashpal** [comment]
> ```shell
> scoop\persist\micromamba\mamba\envs
> ```

i installed micromamba directly - without using scoop. just guessing here - that as scoop is windows only, and u seemed to be facing errors in that direction - so, maybe try direct install of micromamba too.

https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html#umamba-install

**Comment by goyalyashpal** [comment]
_self hiding as offtopic_

---

> Otherwise, I would rather use Git Bash as it seems to have less compatibility issues.

i am using msys2 bash since 2 yrs now, and faced no problems that i am aware of.

so, just curious, why are u using zsh, and what compatibility issues do u think msys2 has that gwf doesn't?

**Comment by vickunwu** [comment]
1. Git Bash natively use USERPROFILE as its home dir, it's more convenient to move downloaded files into my working dir.
2. Msys2 has a [git rev-parse](https://www.msys2.org/docs/git/) issue and you have to do extra tweaks to mitigate it.
3. Zsh have more plugins and there's a lot of tutorials about it.

**Comment by ThomasMarwitzQC** [comment]
@0xbe7a and I discovered a quick fix that you can use as long as this is not fixed and you don't want to abandon Cygwin:

```
# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
export MAMBA_EXE='/cygdrive/c/Users/thomas/.bin/micromamba';
export MAMBA_ROOT_PREFIX='/cygdrive/c/Users/thomas/micromamba_prefix';
eval "$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX")"
# <<< mamba initialize <<<

__mamba_exe() (
    "${MAMBA_EXE}" "${@}"
)

micromamba activate base
```
