### ISSUE TITLE
conda export does not export pip as a dependency of conda and throws syntax error with Windows runner

### ISSUE THREAD

**Issue by JohannesWiesner** [mamba-org/mamba#2686]
I am using `mamba-org/setup-micromamba@v1` to solve an environment using an input `.yml` file and then export the solved environment using:

`conda env export -p "${MAMBA_ROOT_PREFIX}/envs/test" | grep -v "^prefix: " > test_solved.yml` (see [this link](https://github.com/mamba-org/setup-micromamba/issues/75#issuecomment-1568755530))

When I use the `ubuntu-latest` runner, everything works fine, but when I use the `windows-latest` image, two strange things happen:

1.) Normally, `pip` itself should appear as a dependency itself in the conda section before the pip packages get listed. This does not happen.
2.) When inspecting the exported `.yml` file there seems to be a syntax error. The first package under the `pip:` section looks like this:

```
  - pip:
      - ==9.2.6
```

I created a minimal repo to reproduce this error: https://github.com/JohannesWiesner/test_push_yml/tree/main

**Comment by jonashaag** [comment]
I transfered the issue to the Mamba org

**Comment by jjerphan** [comment]
Solved by https://github.com/mamba-org/mamba/pull/3623 first released in 2.0.4.
