### ISSUE TITLE
How to see effective yaml configuration?

### ISSUE THREAD

**Issue by chebee7i** [mamba-org/mamba#2697]
The documentation at https://mamba.readthedocs.io/en/latest/user_guide/configuration.html is very useful.  As part of it, there is a segment which says:

-----

The resulting configuration written using YAML syntax is:
```console
channels:
  - my-channel  # 'CLI'
  - conda-forge  # '~/.mambarc'
always_yes: true  # 'MAMBA_ALWAYS_YES' > '~/.mambarc'
```

----

Is there any way that we can generate such a yaml file (bonus: with attribution included)?

**Comment by danpf** [comment]
https://github.com/mamba-org/mamba/issues/2697
`micromamba config list --sources`

run `micromamba config list --help` for other arguments to alter the output with more or less descriptors.
