### ISSUE TITLE
Mamba / Micromamba uses incorrect `channel_alias` when base env is active 

### ISSUE THREAD

**Issue by 0xbe7a** [mamba-org/mamba#2704]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

yes

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

I have two `condarc` Files: One at `/opt/conda/.condarc` and one at `$HOME/.condarc`. Both specify multi-channels and a `channel_alias`. When querying the `channel_alias` with `micromamba config get channel_alias`, micromamba correctly returns the `channel_alias` from the users `.condarc`. However, the channels listed in `micromamba info` and which are used for all repo operations are build from the `channel_alias` from the `.condarc` at `/opt/conda/.condarc`. 

This behaviour is only present when the current environment is the base environment, and micromamba works as expected when using any other environment.

Conda works as expected in all cases

To reproduce see https://github.com/0xbe7a/mamba_bug_docker

### Logs

```shell
Home Config
     1	channel_alias: https://correct_repo.com
     2	channels:
     3	  - conda-forge
     4	custom_multichannels:
     5	  conda-forge:
     6	    - channel_alias
Root Config
     1	channels:
     2	  - conda-forge
     3	channel_alias:
     4	  https://wrong_repo.com
     5	custom_multichannels:
     6	  conda-forge:
     7	    - ext-conda-anaconda-forgemicromamba info

       libmamba version : 1.4.9
     micromamba version : 1.4.9
           curl version : libcurl/7.88.1 OpenSSL/3.1.1 zlib/1.2.13 zstd/1.5.2 libssh2/1.11.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /home/mambauser/.mamba/pkgs
            environment : base (active)
           env location : /opt/conda
      user config files : /home/mambauser/.mambarc
 populated config files : /opt/conda/.condarc
                          /home/mambauser/.condarc
                          /opt/conda/.condarc
       virtual packages : __unix=0=0
                          __linux=5.15.49=0
                          __glibc=2.31=0
                          __archspec=1=aarch64
               channels : https://wrong_repo.com/ext-conda-anaconda-forge/linux-aarch64
                          https://wrong_repo.com/ext-conda-anaconda-forge/noarch
       base environment : /opt/conda
               platform : linux-aarch64
config get channel_alias
channel_alias: https://correct_repo.com
switching to test_env_not_base
Empty environment created at prefix: /opt/conda/envs/test_env_not_base
micromamba info

       libmamba version : 1.4.9
     micromamba version : 1.4.9
           curl version : libcurl/7.88.1 OpenSSL/3.1.1 zlib/1.2.13 zstd/1.5.2 libssh2/1.11.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /home/mambauser/.mamba/pkgs
            environment : test_env_not_base (active)
           env location : /opt/conda/envs/test_env_not_base
      user config files : /home/mambauser/.mambarc
 populated config files : /home/mambauser/.condarc
                          /opt/conda/.condarc
       virtual packages : __unix=0=0
                          __linux=5.15.49=0
                          __glibc=2.31=0
                          __archspec=1=aarch64
               channels : https://correct_repo.com/channel_alias/linux-aarch64
                          https://correct_repo.com/channel_alias/noarch
       base environment : /opt/conda
               platform : linux-aarch64
```

**Comment by jonashaag** [comment]
Thanks for providing a reproducer!

**Comment by 0xbe7a** [comment]
Any update on this, i still experience this issue with `micromamba` 1.5.1 ?

**Comment by 0xbe7a** [comment]
The bug seems to stem from an overlap between the `root` and `target_prefix` paths.

**Details:**

In `libmamba`, the code at [this location](https://github.com/mamba-org/mamba/tree/main/libmamba/src#L1823C13-L1823C13) is designed to compute and add all `rc` file locations. It processes paths for the `system` location, followed by the `root` location (`/opt/conda/` in my case), and finally the `target_prefix`. 

However, for the `base` environment, the `target_prefix` is `/opt/conda`, identical to the `root`. This results in the `.condarc` file at `/opt/conda/.condarc` being loaded twice.

**Evidence:**

Running `micromamba config sources` yields the following results:

- In the `base` environment:
  ```
  Configuration files (by precedence order):
  /opt/conda/.condarc
  ~/.condarc
  /opt/conda/.condarc
  ```

- In any other environment:
  ```
  Configuration files (by precedence order):
  ~/.condarc
  /opt/conda/.condarc
  ```

This issue causes the configuration in the `target_prefix` to take precedence over the configuration in the home directory, resulting in incorrect channel sources.

**Expected Behavior:**

The expected behavior would be to include the configuration from the `target_prefix` only if the environment prefix is not `base`. Since `base` environment's `target_prefix` is already covered by the `root`, it should not be added again to avoid duplication.

**Comment by 0xbe7a** [comment]
conda seems to solve this problem by using an [IndexedSet](https://boltons.readthedocs.io/en/latest/setutils.html) (see [here](https://github.com/conda/conda/blob/f6fed7869a17d3fdc9a378b901595ae0b849e472/conda/common/configuration.py#L1418)) so a configuration file only keeps its lowest precedence
