### ISSUE TITLE
`micromamba env create` should default to `-f environment.yml`

### ISSUE THREAD

**Issue by apoorvkh** [mamba-org/mamba#2708]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

micromamba env create defaults environment.yml

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

I notice that `micromamba env create` is simply an alias for `micromamba create`.

This is different behavior than conda, because `conda env create` has a default flag `-f environment.yml` and `conda create` does not respect this.

So the command `micromamba env create` should create an environment from `environment.yml`, but it does not.

The above issue does not apply to `mamba env create`. That has the same functionality as `conda env create`.

### mamba info / micromamba info

```shell
libmamba version : 1.4.9
     micromamba version : 1.4.9
           curl version : libcurl/7.88.1 OpenSSL/3.1.1 zlib/1.2.13 zstd/1.5.2 libssh2/1.11.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       envs directories : /home/username/micromamba/envs
          package cache : /home/username/micromamba/pkgs
                          /home/username/.mamba/pkgs
            environment : /home/username/.venv (active)
           env location : /home/username/.venv
      user config files : /home/username/.mambarc
 populated config files : /home/username/.mambarc
       virtual packages : __unix=0=0
                          __linux=3.10.0=0
                          __glibc=2.17=0
                          __archspec=1=x86_64
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
       base environment : /home/username/micromamba
               platform : linux-64
```

**Comment by jonashaag** [comment]
I'm not sure if this design is on purpose

**Comment by apoorvkh** [comment]
Fair enough. Although I think this is indeed how many people use `conda env create` (i.e. defaulting to `environment.yml`).

If the goal of `mamba` is to match the functionality of `conda`, maybe this should be added anyway (despite odd design)?

**Comment by jonashaag** [comment]
The `micromamba` CLI is not designed to be compatible to `conda` and `mamba`
