### ISSUE TITLE
Suggestion on your documentation

### ISSUE THREAD

**Issue by SarahBeecroft** [mamba-org/mamba#2709]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

yes

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

Hi, 

I love your work with Mamba.  

I wanted to offer suggestion on your documentation page about installations as I think it's causing confusion with a lot of users. I work in bioinformatics support so I'm seeing it come up a lot that people will do  `conda install -n base --override-channels -c conda-forge mamba 'python_abi=*=*cp*'` as the default even though it's *not* recommended. I think that is happening just because that is first on the installation instructions page, and you know how we all tend to skim read these things! Can I suggest putting your favoured installation method at the top, and this one further down if you don't want people using it?

Thanks, 

Sarah

**Comment by jonashaag** [comment]
<img width="704" alt="Screenshot 2023-07-26 at 10 28 39" src="https://github.com/mamba-org/mamba/assets/175722/b9b16fce-b671-44c6-b132-ef723fabb5a6">

How can you miss the two red banners here?

But ok I'll add more warning

**Comment by SarahBeecroft** [comment]
I think that people that are just looking for the quick instructions seemingly take the first `code block` they see. I write a _lot_ of user documentation at the supercomputing centre and this experience is not uncommon. I would really strongly suggest move the undesirable method further down. People can't install what they don't see. Up to you though.

**Comment by jonashaag** [comment]
Thanks, great idea, will do!

If you have any other tips to share from your experience writing documentation that might be applicable here, please share!
