### ISSUE TITLE
`micromamba shell` broken since 1.4.5

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#2712]
I think this change https://github.com/mamba-org/mamba/pull/2527 broke `micromamba shell`

With 1.4.4, if I do

```
micromamba shell -n ...
which python
```

I get the environment's Python.

With 1.4.5, I get the system wide Python. Probably something off with PATH.

cc @AntoinePrv 

fyi @0xbe7a

**Comment by jonashaag** [comment]
On Cygwin I get

```
The following argument was not expected: --shell
Run with --help for more information.
```

**Comment by zN3utr4l** [comment]
This error is related to this issue?

**micromamba --version ->1.4.9**

```
Installing pip packages: django==3.2.20, djongo, pymongo==3.12.3, sqlparse==0.2.4, djoser, django-celery-beat, django-celery-results, django-pgviews-redux, djangorestframework, django-etc, django-filter, de
The following argument was not expected: --shell
Run with --help for more information.
critical libmamba pip failed to install packages
```

```
name: base
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.9
  - pip:
    - django==3.2.20
    - --extra-index-url https://Feed:PSW@pkgs.dev.azure.com/Company/_packaging/Feed/pypi/simple/ 
    - my-pkg
```

**Comment by AntoinePrv** [comment]
@zN3utr4l No I don't think so.

@jonashaag I indeed see the environment `bin` dir not being the first entry in `PATH`. Investigating a fix.

**Comment by AntoinePrv** [comment]
@jonashaag is it `micromamba shell -n ` giving you `The following argument was not expected: --shell` on Cygwin?

**Comment by jonashaag** [comment]
And now I'm getting

```
micromamba shell -n base
warning  libmamba 'root_prefix' set with default value: C:\Users\USER\micromamba
The system cannot find the path specified.
```

But

```
micromamba run -n base which python
warning  libmamba 'root_prefix' set with default value: C:\Users\USER\micromamba
/cygdrive/c/Users/USER/micromamba/python
```

**Comment by AntoinePrv** [comment]
So we cannot reproduce `The following argument was not expected: --shell` ? 

For the PATH #2722 should do it

**Comment by jonashaag** [comment]
Looks like it; I deleted my entire `~/micromamba` a few days ago, maybe that fixed it. Although now I get another problem during `self-update`:

```
micromamba self-update


  Installing micromamba version: 1.4.9 (currently installed 1.4.5)

Transaction starting
micromamba                                           3.8MB @   3.7MB/s  1.0s
Download only - packages are downloaded and extracted. Skipping the linking phase.
The following arguments were not expected: C:\Users\USER\micromamba -p
Run with --help for more information.
```

**Comment by zN3utr4l** [comment]
I upgraded my micromamba windows version from 1.4.1 to 1.4.9 and the error came out

**Comment by AntoinePrv** [comment]
Let's track the `self-update` bug in another issue.

**Comment by RoyiAvital** [comment]
I am on `1.5.0` and I still have this issue:

![image](https://github.com/mamba-org/mamba/assets/7347975/4839f9ae-aa62-4762-867f-57fdeb4984f6)

So the error I get is:

```
The following argument was not expected: --shell
Run with --help for more information.
```

I could trace it back to `_mamba_activate`:

```cmd
@"%MAMBA_EXE%" shell --shell cmd.exe %* 1>%UNIQUE%
```

After the first time I create the environment (See https://github.com/mamba-org/mamba/issues/1907) I always just update the binary of `micromamba.exe` in the root folder.

Could it be that the scripts are not updated?

**Comment by RoyiAvital** [comment]
@AntoinePrv , I got this:

```cmd
Setting cmd.exe AUTORUN to: "D:\Applications\Programming\MambaPython\condabin\mamba_hook.bat"
Windows long-path support already enabled.
```

What does it mean setting `Setting cmd.exe AUTORUN`?
I had my MicroMamba environment defined with `micromamba.exe shell hook -s cmd.exe -p <MAMBA_ROOT_PREFIX> -v`.
Does this keep the same `-p` folder path or created something global?

**Comment by RoyiAvital** [comment]
What's the mechanism the shell hook register system variables?
In my `cmd` shell I can always see a variables named `MAMBA_BAT` and `MAMBA_EXE` and `D:\Applications\Programming\MambaPython\condabin;` is added to the `PATH` variable.

Yet I don't see those in the `Environment Variables` in Windows:

![image](https://github.com/mamba-org/mamba/assets/7347975/127f3ea7-3ee7-4e78-9dce-7023a6f065a3)

I wonder, what does `micromamba` do to register those?
I don't find them on registry as well.

**Comment by RoyiAvital** [comment]
Ok I have found, it seems it will register `AutoRun` in `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor`.
