### ISSUE TITLE
[mamba] RuntimeError: Could not set URL

### ISSUE THREAD

**Issue by Hind-M** [mamba-org/mamba#2721]
See https://github.com/jupyterhub/mybinder.org-deploy/issues/2714

**Comment by Hind-M** [comment]
It seems that the problem comes from not setting the `url` [here](https://github.com/mamba-org/mamba/blob/main/mamba/mamba/utils.py#L31).
I'm not sure where the `url` to use should be coming from (conda, channel url, ...)?
@AntoinePrv any ideas?

**Comment by AntoinePrv** [comment]
@Hind-M Perhaps we should switch to 
```python
    prefix_data = api.PrefixData(context.target_prefix)
    prefix_data.add_packages(api.get_virtual_packages())
    repo = api.Repo(pool, prefix_data)
    repos.append(repo)
 ```
 As done in #2632 where we remove uses of `load_conda_installed`.

**Comment by Hind-M** [comment]
> @Hind-M did you manage to reproduce the issue. 

Yes, by running `mamba env update -p path_to_test_env --file test_env.yml`

`test_env.yml`:
```
channels:
  - conda-forge
dependencies:
  - python=3.11.4
```
and having a `python` version < `3.11.4` (`3.10.12` in my case)

> Perhaps we should switch to
> 
> ```python
>     prefix_data = api.PrefixData(context.target_prefix)
>     prefix_data.add_packages(api.get_virtual_packages())
>     repo = api.Repo(pool, prefix_data)
>     repos.append(repo)
> ```
> 
> As done in #2632 where we remove uses of `load_conda_installed`.

Yes awesome, thanks!
