### ISSUE TITLE
[`win/powershell`] Installing into a different environment throws an error

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/mamba#2724]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

-

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

If you try to install into a a named environment when no current environment is active the powershell script throws an error trying to activate an empty string (after the install completes successfully)
```powershell
micromamba create -n bug-2724
# ensure no environment is active
micromamba deactivate
micromamba deactivate
micromamba install -n bug-2724 --yes bat
```
```powershell
<snip>
Transaction finished

To activate this environment, use:

    micromamba activate bug-2724

Or to execute a single command in this environment, use:

    micromamba run -n bug-2724 mycommand

Invoke-Expression : Cannot bind argument to parameter 'Command' because it is an empty string.
At line:120 char:48
+                     Invoke-Expression -Command $activateCommand;
+                                                ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Expression], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

### mamba info / micromamba info

```shell
libmamba version : 1.4.9
     micromamba version : 1.4.9
           curl version : libcurl/8.1.2-DEV Schannel zlib/1.2.13
     libarchive version : libarchive 3.6.2 zlib/1.2.13 liblzma/5.4.3 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.5
       envs directories : C:\conda\envs
          package cache : C:\conda\pkgs
                          C:\conda\pkgs
            environment : None (not found)
           env location : -
      user config files : C:\Users\hirdav.FFMA\.mambarc
 populated config files : C:\conda\.mambarc
       virtual packages : __win=0=0
                          __archspec=1=x86_64
               channels : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : C:\conda
               platform : win-64
```

**Comment by dhirschfeld** [comment]
The offending code:
https://github.com/mamba-org/mamba/blob/14aa49012a7cc61c5282dfc01e2f36b24e46b319/libmamba/data/Mamba.psm1#L115-L121

**Comment by dhirschfeld** [comment]
My PowerShell is a bit rusty these days but something like the below might work:
```powershell
if ($activateCommand) { Invoke-Expression -Command $activateCommand; };
```

I'll try to put in a PR in the next few days if no one beats me to it...

**Comment by chawyehsu** [comment]
Since the purpose of the code is to `reactivate environment`, a better solution is to add a condition to check if the `CONDA_DEFAULT_ENV` env is identical to the one user passed via the command args, i.e. the name of `-n <name>`, and just don't `reactivate` if it's not the current environment.
