### ISSUE TITLE
Confusing error message for version conflict (fiona / gdal -> old version is printed)

### ISSUE THREAD

**Issue by jorisvandenbossche** [mamba-org/mamba#273]
I did `mamba create -n test-geo libgdal=3.1 geopandas`, knowing that geopandas requires fiona, and that fiona has not yet been rebuild with libgdal=3.1 (which was only released a few days ago, as this point in time) but is pinned against libgdal 3.0. 
So I expected conflicts, and was interested to see what would happen. I get this message:

```
Encountered problems while solving.
Problem: nothing provides gdal 1.11.4 needed by fiona-1.6.3-np110py27_0
```

While this clearly pinpoints the problem to fiona / gdal combo, the confusing part of this message is that it reports something about a very old version of gdal / fiona (`fiona 1.6.3` is the oldest fiona version available on conda-forge/defaults channels, and strangely it even takes the py27 version, which should be incompatible with the python version being installed)

**Comment by AntoinePrv** [comment]
Not applicable anymore with the new error messages.
