### ISSUE TITLE
Question and possible suggestion for improvement

### ISSUE THREAD

**Issue by ignace-computing** [mamba-org/mamba#2733]
Dear mamba developers,

To me, as a new user, it was unclear how to deactivate an environment.
Finally, I found the solution here,
https://askubuntu.com/questions/1068943/what-does-this-base-mean-in-my-terminal-prompt
where I replaced `conda` with `mamba`:

`mamba deactivate`

Suggestion:
add the `deactivate` command to the list of commands that appear when you type mamba in the terminal.

Of course, any comments on my suggestion are welcome.

**Comment by jonashaag** [comment]
Interestingly even Conda doesn't report this.

Actually I think this must be fixed in Conda.

**Comment by ignace-computing** [comment]
Ok, should I file an issue in Conda?

**Comment by jjerphan** [comment]
`mamba`, `micromamba` and `conda` can be all used to deactivate environments, definitely the case as of 2.0.

Feel free to comment or open the issue if you still have problem.
