### ISSUE TITLE
Add micromamba to winget package 

### ISSUE THREAD

**Issue by Wongboo** [mamba-org/mamba#2735]
I personaly suggest adding micromamba to winget package for convenience.

**Comment by dlqqq** [comment]
Somebody already has uploaded Micromamba v1.5.5: https://github.com/microsoft/winget-pkgs/pull/130585/files. I think this issue can be closed.

As far as I know however, there's no automated GitHub workflow for uploading new releases of Micromamba to Winget. If the maintainers are open to this idea, I can open a new issue to track it.

**Comment by jonashaag** [comment]
Good to know! No, let's please keep "downstream" package release like winget elsewhere.
