### ISSUE TITLE
 Upon launching on win11, the interface displays garbled text (or characters). 

### ISSUE THREAD

**Issue by Lvjinhong** [mamba-org/mamba#2747]
- I would like to know which configuration file can be modified to change the startup interface, or to resolve this garbled text issue

![image](https://github.com/mamba-org/mamba/assets/96970081/441d2fe5-0b85-42b2-8274-2d9ea9806c84)

**Comment by jonashaag** [comment]
Please fill out the issue template

**Comment by Lvjinhong** [comment]
Sorry, I would like to know how I can modify the configuration file of mamba so that its icon does not pop up during runtime, or how to fix the issue of garbled characters. Although this doesn't affect usability, it's visually uncomfortable for me.

**Comment by jonashaag** [comment]
Please issue the issue template with full info about versions etc

**Comment by jonashaag** [comment]
Ah it says 1.4.2 in the screenshot. Next time please use the issue template and fill it out.

We have removed the banner in 1.4.9 so in your issue template you incorrectly said that the problem remains in the latest version.

In versions earlier than 1.4.9 there is some option to disable the banner, please search the issue tracker.

**Comment by Lvjinhong** [comment]
Thank you very much for your response. I will make sure to use the issue template next time. I am using the latest link from the official website, and I believe this version is the latest supported one on the Windows platform. Could you please guide me on how to locate the option to disable the banner from appearing?
