### ISSUE TITLE
Micromamba does not read `default_channels` unless `defaults` is in the channels

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#2758]
If you have no channels configured, Mamba defaults to whatever is in `default_channels`, and Micromamba defaults to an empty list of channels.

Is that a bug or a feature?

**Comment by JohanMabille** [comment]
Sounds like a bug to me, `default_channels` should be used by default.

**Comment by AntoinePrv** [comment]
Now defaults to conda-forge.
