### ISSUE TITLE
How to uninstall micromamba?

### ISSUE THREAD

**Issue by Jiayi-Pan** [mamba-org/mamba#2772]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

micromamba uninstall

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

Hi, I wanted to know how to uninstall micromamba. Cannot find relevant information on the web. Thank you

The installation command was
```
"${SHELL}" <(curl -L micro.mamba.pm/install.sh)
```

**Comment by jonashaag** [comment]
If you really searched the e list of existing issues, did you not find this? #2237
