### ISSUE TITLE
Deleted environment still leaves files after deletion

### ISSUE THREAD

**Issue by herry23xet** [mamba-org/mamba#2826]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

Yes

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

When I delete an environment with `mamba`, the folder `C:\Users\Name\mambaforge\envs` is left with the associated folder and files. This means that not everything is deleted by `mamba `or `conda`.
To delete I used the command: `mamba remove -n ENVNAME --all` and `conda remove -n ENVNAME --all`.

I have the same problem with conda. I hope I am still in the right place here.

The files that remain are shown here on the screenshots:
<img width="526" alt="Screenshot 2023-09-11 142903" src="https://github.com/mamba-org/mamba/assets/135629084/ad3e51e6-bf77-43a7-9445-27b39522c7fb">
<img width="517" alt="Screenshot 2023-09-11 142930" src="https://github.com/mamba-org/mamba/assets/135629084/b0ebd896-9172-4e7d-8c66-715e92784c9f">

Otherwise, as a workaround, can I delete the folder left by a deleted environment? In this case `data`.

### mamba info / micromamba info

```shell
mamba version : 1.5.1
     active environment : base
    active env location : C:\Users\Name\mambaforge
            shell level : 1
       user config file : C:\Users\Name\.condarc
 populated config files : C:\Users\Name\mambaforge\.condarc
          conda version : 23.7.3
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __win=0=0
       base environment : C:\Users\Name\mambaforge  (writable)
      conda av data dir : C:\Users\Name\mambaforge\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\Name\mambaforge\pkgs
                          C:\Users\Name\.conda\pkgs
                          C:\Users\Name\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Name\mambaforge\envs
                          C:\Users\Name\.conda\envs
                          C:\Users\Name\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.3 requests/2.31.0 CPython/3.10.12 Windows/10 Windows/10.0.19045
          administrator : False
             netrc file : None
           offline mode : False
```

### ~/.condarc

```yaml
channels: [conda-forge]
```

**Comment by Hind-M** [comment]
It seems that this is an issue related to `windows` and similar to this [one](https://github.com/conda/conda/issues/201) in `conda`.
Apparently it's because those files are used in some running processes and so killing those would allow removing the `env` correctly...
One way to check this is to try and remove these files manually - which won't succeed? - and point you to the corresponding running processes?

What was the output of the `remove` command btw?

**Comment by herry23xet** [comment]
The environment or the `data` folder can be deleted. However, since then I have also restarted the laptop.

So I created a new environment with name `data2` to test it:
`data2 `could be deleted without any problems. No reboot or similar was necessary.

The output of the `remove `command was here:
```
(base) C:\Users\Name>mamba remove -n data2 --all

Remove all packages in environment C:\Users\Name\mambaforge\envs\data2:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) C:\Users\Name>
```

**Comment by Hind-M** [comment]
Cool, thanks! Closing the issue then.
