### ISSUE TITLE
`lib/python3.1` should symlink to `lib/python3.1X`

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#2868]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

python3.1

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

If installing python with Conda or Pixi, you get

```
lib/python3.1 --symlink--> lib/python3.11
lib/python3.11/
```

With Micromamba you get

```
lib/python3.1/
lib/python3.11/
```

Not sure why we have the `3.1` directory in the first place but it should be a symlink

**Comment by wolfv** [comment]
This is with macOS or Linux, and not Windows, yes?

**Comment by jonashaag** [comment]
Only tested macOS.

**Comment by jonashaag** [comment]
Wait, this actually works correctly, not sure why I thought it didn't
