### ISSUE TITLE
conda 23.9.0 breaks mamba 1.5.1

### ISSUE THREAD

**Issue by aqc-carlodri** [mamba-org/mamba#2882]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

ensure

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

using mamba 1.5.1 and upgrading to conda [23.9.0](https://github.com/conda/conda/blob/main/CHANGELOG.md#2390-2023-09-27) breaks mamba:
```
$ mamba info
Traceback (most recent call last):
  File "C:\Users\cpi-eng\miniconda3\Scripts\mamba-script.py", line 6, in <module>
    from mamba.mamba import main
  File "C:\Users\cpi-eng\miniconda3\Lib\site-packages\mamba\mamba.py", line 16, in <module>
    from conda.cli.common import (
ImportError: cannot import name 'ensure_name_or_prefix' from 'conda.cli.common' (C:\Users\cpi-eng\miniconda3\Lib\site-packages\conda\cli\common.py)
```

### mamba info / micromamba info

```shell
n/a
```

**Comment by KrOstir** [comment]
Having the same issue. After updating mamba with `mamba update --all` all mamba commands give the `ImportError`. conda commands work as expected.

**Comment by aqc-carlodri** [comment]
Downgrading `conda` to 23.7.4 fixes the issue.

**Comment by jonashaag** [comment]
See https://github.com/mamba-org/mamba/pull/2878

**Comment by sweettyler** [comment]
same happened to me.

**Comment by kaczmarj** [comment]
>Soo, what is the solution? Downgrade to previous version or?


the solution at this point is to downgrade conda ([mentioned above](https://github.com/mamba-org/mamba/issues/2882#issuecomment-1742524151))

```bash
conda install -n base conda==23.7.4
mamba --help  # works now!
```

**Comment by JohanMabille** [comment]
The repodata has been [patched](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/563), mamba 1.5.1 now pins conda < 23.9.0, so a fresh install should work out of the box.

In the meantime mamba  has been [patched to support latest conda](https://github.com/mamba-org/mamba/pull/2878), we will release 1.5.2 with this fix in a few days.

**Comment by JohanMabille** [comment]
> why don't mamba's dependencies constrain the conda version???

It does, see https://github.com/conda-forge/mamba-feedstock/blob/f707a5abe0e1728326263035042ba49c505cb486/recipe/meta.yaml#L126. Unfortunately, sometimes conda releases minor versions that break backward compatibility.

**Comment by rgoubet** [comment]
When is the fix finally going to be released?

**Comment by lightlySkewed** [comment]
> When is the fix finally going to be released?

I'm curious about this as well.

**Comment by adamlynton** [comment]
Hi. The below code does not resolve for me. In fact 'conda' doesn't really work for me at all...for any package. Mamba normally works fine. So given this, what exactly is the recommended action? Yes there's a new solver for conda but again how do I install it? I really hope there's an easier way than having to reinstall my entire anaconda environment. I'm not a happy vegemite (an Australianism).

What I'd like to do is install a version of mamba that works without using conda to install it. Is there a neat way to do that?

conda install -n base conda==23.7.4
mamba --help  # works now!

conda install -n base conda-libmamba-solver
conda config --set solver libmamba

**Comment by andreiprodan** [comment]
@adamlynton thanks, works!

**Comment by alyn4437** [comment]
:). I'm glad. Doesn't help me unfortunately as the below fails to resolve...

conda install -n base conda-libmamba-solver

Might need to get the Windows 11 version of mamba.exe file from some trustworthy source when they release the Mamba 1.5.2 fix.

**Comment by adamlynton** [comment]
:). I'm glad. Doesn't help me unfortunately as the below fails to resolve...

conda install -n base conda-libmamba-solver

Might need to get the Windows 11 version of mamba.exe file from some trustworthy source when they release the Mamba 1.5.2 fix.

**Comment by JohanMabille** [comment]
> When is the fix finally going to be released?

As soon as the CI passes on the branch 1.x. I'm backporting the required bugfixes, and I will release as soon as I can.

**Comment by JohanMabille** [comment]
I've just release 1.5.2, updating the feedstock now. If you want to give it a try from source in the meantime, you can checkout https://github.com/mamba-org/mamba/tree/1.x

**Comment by adamlynton** [comment]
> I've just release 1.5.2, updating the feedstock now. If you want to give it a try from source in the meantime, you can checkout https://github.com/mamba-org/mamba/tree/1.x

So what's the easy way to install this in Win 11 x64 without using conda and mamba. If I download the zip at this github site is there a 3 step or similar command line process to install mamba 1.5.2?

**Comment by JohanMabille** [comment]
@adamlynton I'm going to open a PR to update [miniforge](https://github.com/conda-forge/miniforge). But this may take some time bfore the installer is available. Downloading the zip from this repo means building mamba from source (and therefore, getting all its dependencies, which is a nightmare without a package manager).

What is the issue of installing a fresh miniforge (even if not the latest mamba), and then upgrade mamba in this new fresh install?

**Comment by adamlynton** [comment]
> @adamlynton I'm going to open a PR to update [miniforge](https://github.com/conda-forge/miniforge). But this may take some time before the installer is available. Downloading the zip from this repo means building mamba from source (and therefore, getting all its dependencies, which is a nightmare without a package manager).
> 
> What is the issue of installing a fresh miniforge (even if not the latest mamba), and then upgrade mamba in this new fresh install?

@JohanMabille, If I install a fresh minforge, then because of Conda 23.9.0, I don't think mamba will work, so I can't use it to update itself to1.5.2. I can't use Conda either, it never resolves. Would be good if there was a set of .exe and .dll's for 1.5.2. for Win 11 x64 with their appropriate destination directories that I could just download and add. Once mamba is up I can fix all the other issues with Conda, etc.

**Comment by adamlynton** [comment]
> > If I install a fresh minforge, then because of Conda 23.9.0, I don't think mamba will work, so I can't use it to update itself to1.5.2.
> 
> mamba will work, for the reasons @jtabox exposed above. Also notice that mamba still depends on some parts from conda (and its dependencies), so it cannot be just a set of .exe and .dll (that is why we made an installer).
> 
> Installing the last miniforge, and then running `mamba update mamba` should upgrade mamba to 1.5.2 and conda to 23.9. If not, you can post the error here, we may have missed something.

Hi. I've done a 'simple reinstall' of Anaconda. Removed \env and \pkg directories under anaconda3 as advised by doc then removed anaconda from the installed programs, then completely reinstalled anaconda. 'conda' still doesn't resolve or install anything, it just can't find packages. I just have no idea what is happening here. I wish I had time for all this, I just don't.

**Comment by JohanMabille** [comment]
The solution is to install [miniforge](https://github.com/conda-forge/miniforge/releases), not Anaconda, and then update mamba. Anaconda comes with default channels which are not compatible with conda-forge and is not something [we support](https://mamba.readthedocs.io/en/latest/user_guide/troubleshooting.html#using-the-defaults-channels).

**Comment by janxkoci** [comment]
Hmm, `conda` runs out of memory on my system (conda-forge is too big), which is why I use `mamba` in the first place. Any other suggestions, aside from reinstalling `mamba` and all my packages from scratch?

**Comment by JohanMabille** [comment]
@janxkoci what issue do you have with `mamba update --all` ? If it does not work (please describe the behavior here, that should work now), I'm afraid you don't have the choice and need to reinstall miniforge.

**Comment by saimonduquet** [comment]
run `mamba update --all` in my base env (which was in 1.5.1) and mamba correctly updated to 1.5.2 with conda 23.9.0.
All mamba commands working as expected (I updated my other envs with no problem, and they execute well).
Thanks for the fix !

**Comment by JohanMabille** [comment]
Closing this issue as fixed.

**Comment by janxkoci** [comment]
@JohanMabille Sorry, I was digging a bit deeper and I seem to have a different issue. My `mamba` (and `conda` too) simply says `All requested packages already installed` to any `update` commands. Looking with `search` is even missing some versions that I know exist. It started to appear after update to `1.5.1`, but now even older versions (`1.1.0` on one HPC) have this same problem, while they worked in the past (but on another HPC I have `0.15.3` which works fine, so it's not just server-side issue either). I'll open a new issue when I have some more time.
