### ISSUE TITLE
Generate explicit spec without download/install

### ISSUE THREAD

**Issue by jchorl** [mamba-org/mamba#2901]
Hi!

I want to submit an idea.

It can be useful to separate solving from installing. You can think of explicit specs as blueprints or recipes. It can be useful to save explicit specs for e.g. reproducible build processes. And sometimes, when generating those specs, you may not want to pay the network or disk costs of doing a full install. As an example use-case, suppose you want to solve an environment locally and check in the explicit spec to source control, while having CI install the spec into an image.

I'm wondering if this is possible with micromamba today, or if there is any possibility of supporting it.

I had a look around the source:
- It looks like `install` solves the env and creates a transaction, which has all the urls required to generate an explicit env. However the `--dry-run` print options don't seem to print those urls.
- It looks like `env export` reads `conda-meta/` json files for the urls, and exports those. But this seemingly requires the packages to be installed.

If not possible today, would there be appetite for refactoring such that the output of solving could be piped straight into an explicit spec? What would be the desired UX - extra flags to `install`, a new `env` cmd, or other?

Thanks in advance, and thanks for a fantastic tool.

**Comment by jonashaag** [comment]
Related https://github.com/mamba-org/mamba/issues/2845 https://github.com/mamba-org/mamba/issues/2054

You should be able to use `create --json --dry-run` and parse the output to manually create an `@EXPLICIT` file.

Also there is https://github.com/conda/conda-lock which I think does not download/install to solve

**Comment by jchorl** [comment]
Hey thanks for the helpful response. You're right that `conda-lock` wraps `micromamba` dry-run really nicely. There's some limitations but plenty of solutions I was unaware of. Thank you!
