### ISSUE TITLE
micromamba v1.5.2 not on conda-forge

### ISSUE THREAD

**Issue by wholtz** [mamba-org/mamba#2922]

**Comment by mattwthompson** [comment]
https://github.com/conda-forge/micromamba-feedstock/pull/159

**Comment by lucasfcnunes** [comment]
I noticed this too. With v1.5.3 too (for now).

After 1.5.2 (2023-10-16) a 1.5.1-1 (2023-10-18) was pushed:
![image](https://github.com/mamba-org/mamba/assets/29926675/cc8bc457-6624-415c-bd9b-ea6a4ea74720)

**Comment by lucasfcnunes** [comment]
Now we have 1.5.1-2 instead of 1.5.3.
![image](https://github.com/mamba-org/mamba/assets/29926675/29998dc5-22b5-49b2-aa31-174c625b6f6f)

**Comment by mattwthompson** [comment]
The place to fix this would be at the feedstock repository: https://github.com/conda-forge/micromamba-feedstock
