### ISSUE TITLE
Hardcoded and default channels in `[lib|micro|]mamba` 2.0

### ISSUE THREAD

**Issue by AntoinePrv** [mamba-org/mamba#2932]
I believe we should leverage 2.0 release to make the following (breaking) changes wrt channels.
Maybe this is too naive? @JohanMabille @Hind-M @Klaim @wolfv @jonashaag @isuruf @jaimergp

### A.1 Add Conda-Forge
Conda-Forge has more packages, is open-source, and community driven. Out of the box, `[micro]mamba install python` should install from conda-forge without further configuration.

I would say this should be also the default for `libmamba`, and possible to override in API.

### A.2 Remove anything else
Since we advocate for not mixing Conda-Forge and Anaconda channels, any of `defaults`, `pkgs/main`, `pkgs/r` and the likes should **not** be included by default.

## B. Hard coded names
With the goal of simplifying API, and required implicit knowledge about the Conda ecosystem when using Mamba, I further advocate to remove special meaning for other hard-coded names, such as `defaults`, `pkgs/main`, `pkgs/r`, `local`.
This would remove the configuration option `default_channels` meant as an extra entry to append to `custom_multi_channels`.

Users/developers who wish to still use those, would have to configure them explicitly through `custom_channels` and `custom_multi_channels`.

**Comment by jaimergp** [comment]
> Out of the box, [micro]mamba install python should install from conda-forge without further configuration.

Agreed.

> I would say this should be also the default for libmamba, and possible to override in API.

My personal preference here would that libmamba itself doesn't configure any channels. The default value should be specified by the application layer, not the library.

> Remove anything else

Agreed.

> I further advocate to remove special meaning for other hard-coded names, such as defaults, pkgs/main, pkgs/r, local.

I am not against that. I would just be wary of how breaking this might be in some environments that rely on "defaults = repo.anaconda.org/pkgs/*" being the default. That said, some users have `default_channels: [conda-forge]`, which can be confusing on so many levels. Maybe a warning in a 1.x release would provide more data on whether this should be a concern or not.

**Comment by SylvainCorlay** [comment]
I am all for removing the hard-coded names, with a slight reservation on "local", since this is about interaction with conda-build rather than a hard-coded remote channel.

On the default channels, I agree we should not have any default channel in libmamba. If you want to enable conda-forge in micromamba, the the option to disable it could be more explicit like `--no-conda-forge`.

**Comment by AntoinePrv** [comment]
> If you want to enable conda-forge in micromamba, the the option to disable it could be more explicit like --no-conda-forge.

Conda-forge may be the default but it should not get special treatment either. Any change to `channels` in the config removes `conda-forge`, and requires it to be manually added back. That way the configurations options map exactly with what mamba is using. *explicit*.

**Comment by AntoinePrv** [comment]
> I am not against that. I would just be wary of how breaking this might be in some environments that rely on "defaults = repo.anaconda.org/pkgs/*" being the default. That said, some users have default_channels: [conda-forge], which can be confusing on so many levels. Maybe a warning in a 1.x release would provide more data on whether this should be a concern or not.

In fact that is the possibility. This second change could be mared deprecated first and removed later.

**Comment by Hind-M** [comment]
I totally agree!
If we want to remove the default `local` channels (and I think this would really simplify things and avoid the assumptions we have regarding location), I think a very explicit note should be printed for the user to explain what to add exactly and in which `config` (`custom_channels` or `custom_multi_channels`...). A very comprehensive documentation would be necessary to avoid loss of information which is basically in the codebase currently.

**Comment by AntoinePrv** [comment]
For the hard-coded names, the logic has been refactored out of the `Channel` and into a `ChannelContext::make_conda_compatible` factory builder, but is still available in the CLI.
