### ISSUE TITLE
Mamba resolves older packages than conda on new versions of libsolv, against a mirrored conda-forge repo in jfrog Artifactory. 

### ISSUE THREAD

**Issue by akangst** [mamba-org/mamba#2956]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

https://github.com/mamba-org/mamba/issues/848

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

Hello, 

I work in a mirrored conda repo environment. We have channels for conda-main and conda-forge mirrored via jfrog artifactory inside of our environment, so this is a question on trying to determine where my error lies, not necessarily in placing blame on the mamba package resolver. 

I have an issue where conda (up to most recent 23.9.0) will resolve up to the newest packages on conda-forge, but mamba will not on up-to-date installations. There's about a 6 month gap for me, mamba on a recent version of libsolv stops resolving packages newer than June of 2023 (tested with dask, anything later than 2023.6.1 isn't resolving for us). The weird thing here is when I downgrade to this configuration below, it starts resolving correctly and will pull latest packages in mamba. 

`libsolv=0.7.22`
which results in mamba=1.1.0 after it gets installed.

Having to go backwards 2 versions on libsolv to do this definitely feels strange and unintended. I'm wondering if someone knows what the reason might be directly, or if there's potentially some difference in package metadata in our mirror that might be contributing to this - but at that point I would expect it to affect conda and mamba, and it only affects conda.

**Comment by jonashaag** [comment]
Same as https://github.com/mamba-org/mamba/pull/2790?

**Comment by jonashaag** [comment]
Feel free to continue the discussion if this didn't fix your problem.
