### ISSUE TITLE
Please fix the Mamba home page Anti-recommendations in the Installation page Introductory message... "Here's how to install it, but don't follow these instructions..."

### ISSUE THREAD

**Issue by richlysakowski** [mamba-org/mamba#2959]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

mamba installation instructions

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

Please fix the Mamba conflicted home page Installation Introductory message... 

The message to a wanna-be first-time Mamba user is not only ambiguous, but conflicted.  If it is NOT recommended, then why is it on the main installation page???

The Mamba Home Page for installation basically says:  "Here's how to install it, but don't follow our instructions..."

    https://mamba.readthedocs.io/en/latest/mamba-installation.html

    "This way of installing Mamba is not recommended. We strongly recommend to use the Miniforge method (see above)."

    # NOT RECOMMENDED: This method of installation is not recommended, prefer Miniforge instead (see above)    
    # conda install -n base --override-channels -c conda-forge mamba 'python_abi=*=*cp*'

This is very confusing, because there are no instructions of what to do, only NOT to do! 

Do we "start over" with Miniforge?  Do we uninstall Anaconda?  Do we use our existing conda installation and environments?  Do we uninstall conda first?  Do we have reformat our hard drive on Windows? (just kidding).  Will the miniforge installation bypass conda, use conda, or obviate the need for conda?    How do we use mamba (micromamba, or miniforge/minimamba) within our existing conda environments?  

If mamba is a 100% compatible drop-in replacement for conda, then why all these restrictions and anti-recommendations? 

What will actually happen to our "base" environment if we install mamba into our conda "base" environment?
What will actually happen if we install mamba into another conda environment beside the "base" environment?

We need step-by-step explanations of WHAT TO DO (not what NOT to do), with explanations of each step (actions and reasons why, with potential negative impact of each step.)

#####################################################################
Here's the instructions I find on the home page now.  
#####################################################################
Fresh install (recommended)[¶](https://mamba.readthedocs.io/en/latest/mamba-installation.html#fresh-install-recommended)

We recommend that you start with the [Miniforge distribution](https://github.com/conda-forge/miniforge) >= Miniforge3-22.3.1-0. If you need an older version of Mamba, please use the Mambaforge distribution. Miniforge comes with the popular conda-forge channel preconfigured, but you can modify the configuration to use any channel you like.

After successful installation, you can use the mamba commands as described in [mamba user guide](https://mamba.readthedocs.io/en/latest/user_guide/mamba.html#mamba).

Note

    After installation, please :ref`make sure <defaults_channels>` that you do not have the Anaconda default channels configured.

    Do not install anything into the base environment as this might break your installation. See [here](https://mamba.readthedocs.io/en/latest/user_guide/troubleshooting.html#base-packages) for details.

Existing conda install (not recommended)[¶](https://mamba.readthedocs.io/en/latest/mamba-installation.html#existing-conda-install-not-recommended)

Warning

This way of installing Mamba is not recommended. We strongly recommend to use the Miniforge method (see above).

To get mamba, just install it into the base environment from the conda-forge channel:

# NOT RECOMMENDED: This method of installation is not recommended, prefer Miniforge instead (see above)
# conda install -n base --override-channels -c conda-forge mamba 'python_abi=*=*cp*'

Warning

Installing mamba into any other environment than base is not supported.

### mamba info / micromamba info

```shell
see above
#####################################################################
Here's the instructions I find on the home page now.  
#####################################################################
```

### Logs

```shell
see above
#####################################################################
Here's the instructions I find on the home page now.  
#####################################################################
```

### environment.yml

```yaml
see above
```

### ~/.condarc

```yaml
see above
```

**Comment by jonashaag** [comment]
Thanks, you are raising legitimate concerns. Would you be up for drafting an initial PR to address some of your points?
