### ISSUE TITLE
Package pyi stubs in Python libmambapy package

### ISSUE THREAD

**Issue by dholth** [mamba-org/mamba#2961]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

pyi stubs

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

It looks like `__init__.pyi` needs to be added to the Python package, so that developers get types and completions.

**Comment by jjerphan** [comment]
`.pyi` stubs are packaged as of 2.0 thanks to https://github.com/mamba-org/mamba/pull/2960/ (see [this line](https://github.com/mamba-org/mamba/pull/2960/files#diff-59b00a69dbef3047cd3b59eb7e28e0d03607dc6baf24dc3d407dac514a0bbee0R30)).
