### ISSUE TITLE
How to package mamba for Fedora

### ISSUE THREAD

**Issue by opoplawski** [mamba-org/mamba#2971]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

yes

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

I'm working on packaging mamba for Fedora.  With 1.5.3 I was having trouble properly installing the libmampy Python module, so I am excited to seem some changes there and a new pyproject.toml file.  Although it looks like it makes use of scikit-build which apparently is being replaced by scikit-build-core.  Has scikit-build-core been looked at?

However, I'm not having any success in building this.  The straight cmake build does not appear to install libmambapy.  Trying to build the wheel via the Fedora tooling results in libmambapy not being able to find the libmamba library.  This is apparently because libmamba isn't really "installed" at this point - just built locally.  I've tried pointing it to it with:
```
export CMAKE_PREFIX_PATH=../redhat-linux-build
```
But that ultimately fails because targets paths are not really correct since it isn't "installed".

It would be really nice to be able to have mamba built as a single package, but as it is I think it will need to get split into at least two unless a single build environment can be created that builds and installs everything properly.

**Comment by AntoinePrv** [comment]
Hi @opoplawski, nice to know Mamba is being packaged for Fedora ! I just updated [Micromamba build from source section](https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html#build-from-source) yesterday, but it seems you are more interested in libmambapy.

>  Although it looks like it makes use of scikit-build which apparently is being replaced by scikit-build-core. Has scikit-build-core been looked at?

I learned about `scikit-build-core` as I was implementing `scikit-build`. From what I understand, `scikit-build` is not deprecated and `scikit-build-core` is still in Beta, so we'll leave the migration from another time. Despite, it should not change much from a User perspective.

> The straight cmake build does not appear to install libmambapy. 

That is correct, it is meant to install `libmamba

**Comment by AntoinePrv** [comment]
Bad manipulation, did not mean to close.

**Comment by opoplawski** [comment]
Thanks for the response.  I guess I'll go with the two package version.  Giving that a go though I'm running into the following error:
```
  [1/4] Building CXX object CMakeFiles/bindings.dir/src/libmambapy/bindings/legacy.cpp.o
  FAILED: CMakeFiles/bindings.dir/src/libmambapy/bindings/legacy.cpp.o
  /usr/lib64/ccache/g++ -DFMT_SHARED -DSPDLOG_FMT_EXTERNAL -Dbindings_EXPORTS -I/home/orion/mamba/mamba-0d42e816675a182a7994070a5c7c99651f93755f/libmambapy/src/libmambapy/bindings -isystem /usr/include/python3.12 -isystem /usr/share -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64   -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -O3 -DNDEBUG -fPIC -fvisibility=hidden -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wnull-dereference -Wdouble-promotion -Wformat=2 -Wunreachable-code -Wuninitialized -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wuseless-cast -flto -fno-fat-lto-objects -MD -MT CMakeFiles/bindings.dir/src/libmambapy/bindings/legacy.cpp.o -MF CMakeFiles/bindings.dir/src/libmambapy/bindings/legacy.cpp.o.d -o CMakeFiles/bindings.dir/src/libmambapy/bindings/legacy.cpp.o -c /home/orion/mamba/mamba-0d42e816675a182a7994070a5c7c99651f93755f/libmambapy/src/libmambapy/bindings/legacy.cpp
  /home/orion/mamba/mamba-0d42e816675a182a7994070a5c7c99651f93755f/libmambapy/src/libmambapy/bindings/legacy.cpp:21:10: fatal error: mamba/core/channel.hpp: No such file or directory
     21 | #include "mamba/core/channel.hpp"
        |          ^~~~~~~~~~~~~~~~~~~~~~~~
```
It looks like `channel.hpp` is not part of the installed headers for libmamba.  Should it be?

**Comment by AntoinePrv** [comment]
This file was recently renamed. You might have a build cache that is out of date with the source code revision. 
Try to start fresh (`git clean -xdf .` if you don't have any file to loose in the repository).

**Comment by opoplawski** [comment]
Ah, my bad - I was building different commit versions.

On the latest main branch it seems like the `mamba` directory is gone now.  Is there some replacement for that and installing a `mamba` executable?

**Comment by opoplawski** [comment]
Nevermind - I just found #2942

**Comment by AntoinePrv** [comment]
Yes, mamba is gone. On our side, we intend to have `micromamba` and `mamba` roughly the same executable.
`micromamba` is fully statically linked and `mamba` dynamically and packaged with a base environment to hold these dependencies.
