### ISSUE TITLE
micromamba static build fails

### ISSUE THREAD

**Issue by jchorl** [mamba-org/mamba#2974]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

reproc

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

I'm trying to build a micromamba static binary. I've been following [these docs](https://mamba.readthedocs.io/en/latest/developer_zone/build_locally.html#build-micromamba).

Here's what I've tried:

In the micromamba repo, get a docker container up with micromamba:
```
docker run -it --rm \
    -v $(pwd):/work \
    -w /work \
    -u 0 \
    mambaorg/micromamba:1.5.1 \
    bash
```

```
rm -rf build
apt-get update && apt-get install -y make
micromamba install -y -n base -f ./dev/environment-dev.yml
micromamba install -y -n base -f ./libmamba/environment-static-dev.yml
```

```
cmake -B build/ \
    -DBUILD_LIBMAMBA=ON \
    -DBUILD_STATIC=ON \
    -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
    -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
    -DBUILD_MICROMAMBA=ON
```

This outputs:
```
-- Building libmamba v1.5.1
-- libmamba binary version: v2.0.0
-- Adding static libmamba target
-- Setting LTO for target libmamba::libmamba-static
   -> Statically linking against libmamba (static) dependencies
CMake Error at cmake/Checks.cmake:9 (message):
  Expected type "STATIC_LIBRARY" for target "reproc" but found
  "SHARED_LIBRARY"
Call Stack (most recent call first):
  libmamba/CMakeLists.txt:399 (mamba_target_check_type)
  libmamba/CMakeLists.txt:630 (libmamba_create_target)
```

I also tried passing the optional `-DMICROMAMBA_LINKAGE=STATIC` mentioned in the docs, same error.

Am I setting up the env wrong, or is there an issue with conflicting deps, or other? Any help appreciated.

### mamba info / micromamba info

```shell
(base) root@ad10e1c6869c:/work# micromamba info

       libmamba version : 1.5.1
     micromamba version : 1.5.1
           curl version : libcurl/7.88.1 OpenSSL/3.1.2 zlib/1.2.13 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.52.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /root/.mamba/pkgs
            environment : base (active)
           env location : /opt/conda
      user config files : /root/.mambarc
 populated config files : 
       virtual packages : __unix=0=0
                          __linux=5.15.0=0
                          __glibc=2.36=0
                          __archspec=1=x86_64
               channels : 
       base environment : /opt/conda
               platform : linux-64
```

### Logs

```shell
CMake Error at cmake/Checks.cmake:9 (message):
  Expected type "STATIC_LIBRARY" for target "reproc" but found
  "SHARED_LIBRARY"
Call Stack (most recent call first):
  libmamba/CMakeLists.txt:399 (mamba_target_check_type)
  libmamba/CMakeLists.txt:630 (libmamba_create_target)
```

**Comment by AntoinePrv** [comment]
It looks like the the `reproc` you're getting is dynamic, not static, so you would not be getting a fully statically linked `micromamba`.
The check is here to avoid this, since in `reproc`, both targets have the same name.

Where did you get `reproc` from? In conda-forge you need to get `reproc++-static`, if you build it, you need to pass it whichever configuration makes it static (`BUILD_SHARED_LIBS=OFF` ?)

Also any reason why not using the `micromamba` releases?

**Comment by jchorl** [comment]
> Where did you get reproc from? In conda-forge you need to get reproc++-static, if you build it, you need to pass it whichever configuration makes it static (BUILD_SHARED_LIBS=OFF ?)

I was just trying to follow the linked instructions from the mamba docs. Here's how I installed reproc:
```
micromamba install -y -n base -f ./dev/environment-dev.yml
micromamba install -y -n base -f ./libmamba/environment-static-dev.yml
```

Note that `./dev/environment-dev.yml` [includes](https://github.com/mamba-org/mamba/blob/09cbb34e5415781e2e0be3274a587e342d234f57/dev/environment-dev.yml#L17) `reproc-cpp >=14.2.4.post0`.

`./libmamba/environment-static-dev.yml` [includes](https://github.com/mamba-org/mamba/blob/09cbb34e5415781e2e0be3274a587e342d234f57/libmamba/environment-static-dev.yml#L21-L23) `reproc-static`, `reproc-cpp`, and `reproc-cpp-static`.

When I installed `dev/environment-dev.yml` and then `libmamba/environment-static-dev.yml`, I don't believe the second uninstalled anything from the first.

I just tried again with your suggested `BUILD_SHARED_LIBS=OFF`:
```
cmake -B build/ \
    -DBUILD_LIBMAMBA=ON \
    -DBUILD_STATIC=ON \
    -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
    -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
    -DBUILD_MICROMAMBA=ON \
    -DBUILD_SHARED_LIBS=OFF \
    -DMICROMAMBA_LINKAGE=STATIC
```

```
CMake Error at cmake/Checks.cmake:9 (message):
  Expected type "STATIC_LIBRARY" for target "reproc" but found
  "SHARED_LIBRARY"
Call Stack (most recent call first):
  libmamba/CMakeLists.txt:399 (mamba_target_check_type)
  libmamba/CMakeLists.txt:630 (libmamba_create_target)
```

So my gut feel is that either the env yml files need updating, the instructions need updating, or I'm just not following something correctly/passing the right args.

> Also any reason why not using the micromamba releases?

I want to experiment with a couple features that I'm not sure would be expected into upstream. I don't want to sidetrack this issue, it's about build issues. If you're curious about those features: 1. The ability to accept multiple environment ymls with `-f`. 2. Generating conda-lock yamls after solving. For why - a static binary is much easier to integrate into build/CI than a python/conda env. Anyway, I figured at least I'd get these building/working, and if they worked well, I'd approach to see if you'd be open to merging them.

**Comment by AntoinePrv** [comment]
Ok I see the issue `./libmamba/environment-static-dev.yml` is out of date since there has been quite some changes in this lately. I'll fix it.

> I was just trying to follow the linked instructions from the mamba docs. Here's how I installed reproc:

Could you point to the page, I will update it too.

**Comment by jchorl** [comment]
Thank you!!!

I was following https://mamba.readthedocs.io/en/latest/developer_zone/build_locally.html

Did this get taken down in the last ~day? It appears to be gone now...

**Comment by AntoinePrv** [comment]
> Did this get taken down in the last ~day? It appears to be gone now...

Yes, done today, I replaced it with development oriented doc, so not what you're looking for.
I'll add a `compile from source` section in the install instructions.

**Comment by jchorl** [comment]
> > Did this get taken down in the last ~day? It appears to be gone now...
> 
> Yes, done today, I replaced it with development oriented doc, so not what you're looking for. I'll add a `compile from source` section in the install instructions.

Heh - funny timing. Thanks!

**Comment by AntoinePrv** [comment]
Do you need Windows ? It's in a mixed state right now.

>  1. The ability to accept multiple environment ymls with -f

Absolutely yes. Been meaning to do it as well.

>  Generating conda-lock yamls after solving.

I think there is no code to generate conda-lock from mamba at the moment. Would definitely need at least that.

**Comment by jchorl** [comment]
> Do you need Windows ? It's in a mixed state right now.

Nope

> The ability to accept multiple environment ymls with -f

I have a functioning branch. I'd be happy to cut a PR

> Generating conda-lock yamls after solving.

I also have a functioning branch. I wasn't sure if this is something you'd accept into the project - it might be tough to maintain. If you'd be open to it, I'd also be happy to open a PR when it's ready (could be some time)
