### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by j-k** [mamba-org/mamba#2979]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

link

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

The link to the installation guide in file README.md is broken

**Comment by jonashaag** [comment]
Please send a PR to fix it, thx!

**Comment by artificial-agent** [comment]
@jonashaag here is a PR  https://github.com/mamba-org/mamba/pull/2980
