### ISSUE TITLE
[TLDR] Put the installation script in README.md

### ISSUE THREAD

**Issue by syheliel** [mamba-org/mamba#2991]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### How did you install Mamba?

Mambaforge

### Search tried in issue tracker

tldr

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

Just put the installation script in this repo's README.md. **DO NOT** put the installation guide into a split link!
The reason behind this is this page is the first candidate in google. So **KEEP IT SIMPLE**.

**Comment by jonashaag** [comment]
No
