### ISSUE TITLE
Package cache in home directory corrupted by multiple simultaneous solves

### ISSUE THREAD

**Issue by rcolfin** [mamba-org/mamba#3008]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

Package cache

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

Unable to set an alternative to ~/micromamba for the location of the package cache is resulting in corrupted downloads of packages during environment creations.  The home directory is on NFS and multiple environments are being created simultaneously on potentially different hosts

**Comment by jonashaag** [comment]
Unfortunately there is not a lot Mamba can do to help here. NFS doesn't allow for locking generally, so there is not way for the multiple Mamba processes to synchronize.

You can set your root prefix to somewhere outside of NFS

**Comment by rcolfin** [comment]
Is there an environment variable we can use for the root prefix? 

I am actually installing the environment to a location on the local disk, and if the pkgs cache was relative to the executable that could also work.

**Comment by jonashaag** [comment]
```
micromamba --root-prefix
```

**Comment by jonashaag** [comment]
https://mamba.readthedocs.io/en/latest/search.html?q=root+prefix

**Comment by rcolfin** [comment]
That looks good, thank you
