### ISSUE TITLE
Can it work under msys2 with zsh

### ISSUE THREAD

**Issue by maryjeck** [mamba-org/mamba#3020]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

yes

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

it show me :(eval):11: parse error near ^M 
when i use conda ,i write this in the .zshrc
`eval "$('/f/miniconda3/Scripts/conda.exe' 'shell.zsh' 'hook' | sed -e 's/"$CONDA_EXE" $_CE_M $_CE_CONDA "$@"/"$CONDA_EXE" $_CE_M $_CE_CONDA "$@    " | tr -d \x27\\r\x27/g')"
`
Is there any way I can use micromamba with msys2+ zsh

**Comment by jonashaag** [comment]
Can you please write complete sentences and use punctuation? It's hard to understand what you are trying to say.

**Comment by jjerphan** [comment]
Please reopen an issue with a reproducer on 2.0 and a clearer and complete description of the problem you are having.
