### ISSUE TITLE
Mamba's documentation is displayed incorrectly - iOS

### ISSUE THREAD

**Issue by herry23xet** [mamba-org/mamba#3053]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

Yes

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

When I open the documentation on my iPhone via Safari, I am shown the table of contents of the documentation, which cannot be collapsed. Screenshot:
![IMG_8505](https://github.com/mamba-org/mamba/assets/135629084/71966275-26fc-47e1-8bfe-424de0b9bece)
The website is displayed in this way and therefore cannot be used.

**Comment by jonashaag** [comment]
Can confirm

**Comment by jjerphan** [comment]
I cannot reproduce the issue using [Firefox's responsive design mode](https://firefox-source-docs.mozilla.org/devtools-user/responsive_design_mode/) on all the proposed platform, including all the proposed iPhone.
