### ISSUE TITLE
Discussion: Add runtime warning if people mix defaults and conda-forge

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#3063]
I've gone out of my way to help people avoid the "mixing defaults and conda-forge channels":

- https://github.com/mamba-org/mamba/pull/2181
- https://github.com/mamba-org/mamba/pull/2451
- https://github.com/mamba-org/mamba/pull/2569
- https://github.com/mamba-org/mamba/pull/2619
- https://github.com/mamba-org/mamba/pull/2809
- https://github.com/mamba-org/mamba/pull/2904
- https://github.com/mamba-org/mamba/pull/2908
- https://github.com/mamba-org/mamba/pull/2996

Still people make that mistake.

I propose to add a runtime warning to Mamba, or have Mamba outright refuse to work, when the channels are mixed.

**Comment by analog-cbarber** [comment]
Just to be clear, you are talking about the Anaconda default channels NOT using conda-forge AS your default?

**Comment by jonashaag** [comment]
Please rephrase the question I don't understand

**Comment by analog-cbarber** [comment]
You appear to be using the word "defaults" to refer specifically to the **Anaconda** default channels NOT to the concept of a default conda channel which could be configured to point elsewhere. I configure my conda defaults to point at conda-forge but still have some scripts that add `-c conda-forge` and it doesn't seem to cause problems.

**Comment by jonashaag** [comment]
Yeah it's fine to use non-Anaconda `defaults` channels, although I don't recommend it because it makes `environment.yml` files less well specified when you don't include the channels
