### ISSUE TITLE
Document breaking changes for v2

### ISSUE THREAD

**Issue by corneliusroemer** [mamba-org/mamba#3065]
### Describe your issue

I've noticed your recent v2.0.0alpha0 release: https://github.com/mamba-org/mamba/releases/tag/2023.12.14 and was wondering whether there was a list of breaking changes available.

The release notes only contain references to bug fixes and enhancements not mentioning any breaking changes.

This is the only recent mention of breaking change I could find in the repo: https://github.com/mamba-org/mamba/issues/2932

Thanks!

**Comment by SylvainCorlay** [comment]
Thanks @corneliusroemer,

We will be working through a series of alpha, beta, and release candidates before the final release. For the moment, we have a detailed [changelog](https://github.com/mamba-org/mamba/blob/main/CHANGELOG.md#202312), but there will be a more "high-level" explanation of what changes between Version 1 and Version 2.

The main goals with respect to backward compatibility are the following:
 - We want the mamba and micromamba command line utilities to remain compatible with Version 1.
 - However, the libmamba C++ API and Python bindings will reflect the internal refactors that mamba has gone through. We will work with downstream package maintainers (especially conda developers) through the series of pre-releases to ensure that mamba v2 still fits their needs.

**Comment by corneliusroemer** [comment]
Thanks @SylvainCorlay! You've done a great job with `(micro)mamba`, it has really made `conda` usable again. I'm looking forward to what you come up with in v2!

**Comment by jjerphan** [comment]
The breaking changes mamba 2.0 introduced have [a dedicated section in the documentation](https://mamba.readthedocs.io/en/latest/developer_zone/changes-2.0.html) thanks to #3091 and subsequent additions.
