### ISSUE TITLE
Cannot disable defaults channel

### ISSUE THREAD

**Issue by jmakov** [mamba-org/mamba#3073]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

defaults

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

Wanted to disable defaults channel after install step in makefile. Copy pasting the command [from the docs](https://mamba.readthedocs.io/en/latest/user_guide/troubleshooting.html#using-the-defaults-channels) results in error.  Also if it's not recommended, why isn't it disabled by default? `mamba create --override-channels` ... returns
```
usage: mamba create [-h] [--clone ENV] (-n ENVIRONMENT | -p PATH) [-c CHANNEL] [--use-local] [--override-channels] [--repodata-fn REPODATA_FNS] [--experimental {jlap,lock}] [--strict-channel-priority] [--no-channel-priority] [--no-deps | --only-deps] [--no-pin] [--copy] [-C] [-k] [--offline] [-d] [--json] [-q] [-v] [-y] [--download-only] [--show-channel-urls] [--file FILE] [--no-default-packages]
                    [--solver {classic,libmamba} | --experimental-solver {classic,libmamba}] [--dev]
                    [package_spec ...]
mamba create: error: one of the arguments -n/--name -p/--prefix is required
```
More info here: https://github.com/conda-forge/miniforge/issues/542

**Comment by jonashaag** [comment]
Thanks, I think it should have been `mamba env create`. Mind double
checking and  sending a PR?

It is disabled by default in most installations, but it is a very common mistake people make and so it is documented very aggressively in the troubleshooting guide.

**Comment by jmakov** [comment]
Doesn't seem to work for me:
```shell
$ mamba env create --override-channels ...
usage: mamba [-h] {create,export,list,remove,update,config} ...
mamba: error: unrecognized arguments: --override-channels
$  mamba --version
mamba 1.4.2
conda 23.3.1
```

**Comment by jonashaag** [comment]
I don't understand why you don't have the option. With Conda 23.10:

```
conda create --override-channels -p /tmp/x -c conda-forge
```

works

**Comment by AntoinePrv** [comment]
@jmakov if you want to disable defaults channels alltogether, you can also add to your `.condarc`:
```yaml
default_channels: []
```

**Comment by jmakov** [comment]
Thanks. So to share my case - I'm installing mamba from a makefile and wanted to copy paste the command from the docs.

**Comment by jonashaag** [comment]
It seems like the docs are invalid: https://github.com/conda/conda/issues/10498
