### ISSUE TITLE
Add USERINSTALLED info to solver

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#31]
Let the solver know about what packages have historically explicitly been installed by a user.

**Comment by adriendelsalle** [comment]
Hi @wolfv !

Thanks for this proposition. Could you please elaborate a bit ?
Would it help for some solving issue (wrong resolution, performance, etc.) ?

**Comment by adriendelsalle** [comment]
It appears that `remove` operation only removes the spec and not orphaned packages.
Using `libsolv` `SOLVER_USERINSTALLED`  combined with `SOLVER_CLEANDEPS` should make it possible.
