### ISSUE TITLE
Rename the requirements file

### ISSUE THREAD

**Issue by ArneBachmannDLR** [mamba-org/mamba#3150]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

Yep

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

I think it's not the best move to have unidep's requirements file have the same name as the conda/mamba requirements file.

- `conda` will get stuck on the unidep-specific `pip:` and `conda:` maps
- Impossible to transition conda and unidep or keep both requirements files in parallel
- It confuses prospective users when they encounter a repository - how would the know how to set up the environment?

I suggest renaming `requirements.yaml` to `.unidep.yaml` or similar.

**Comment by jonashaag** [comment]
What is Unidep?

**Comment by ArneBachmannDLR** [comment]
Reported to wrong project
