### ISSUE TITLE
DOC: What happened to `mamba.api`?

### ISSUE THREAD

**Issue by HaoZeke** [mamba-org/mamba#3159]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

mamba.py

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

ASV last year began supporting `mamba` [as a solver](https://github.com/airspeed-velocity/asv/pull/1238) through the `mamba.api` module ([here](https://github.com/AntoinePrv/mamba/blob/f725099ddd41fc67b66b12ba0ea275f2bfaab540/mamba/mamba/api.py)). I see now that it was removed completely on `main`, last seen as part of `v1.5.6`. Naturally this means it is [not usable anymore](https://github.com/airspeed-velocity/asv/pull/1370#issuecomment-1913251064) without vendoring in the relevant bits of `mamba.api`.

However, I was wondering if there was a more concrete migration guide / other suggestions.

**Comment by HaoZeke** [comment]
I'm also not sure if https://github.com/mamba-org/mamba/pull/3054 is related (perhaps it is for downstream "builders" like `asv`), though since `boa` still uses `libmambapy` that shouldn't affect `asv`.

**Comment by JohanMabille** [comment]
In (micro)mamba 2 we decided to drop the mamba python code, to avoid maintaining two parallel equivalent workflows. The Python bindings will still be provided, but they will simply forward the call to the C++ functions already used in micromamba, no more logic will be done on the Python side.

We are progressively progressively porting the missing API to `libmambapy`, there will be breaking changes and a migration guide will be provided when the APIs are a bit stabler.
