### ISSUE TITLE
Autoactivate environment when entering a directory

### ISSUE THREAD

**Issue by aretrace** [mamba-org/mamba#3183]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

yes #5179 on conda

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

Enable a way to automatically activate a mamba environment when entering a directory.
See: conda/conda#5179

**Comment by jonashaag** [comment]
I don't think we will want to support this feature. 

Try direnv or Pixi
