### ISSUE TITLE
Micromamba CHANGELOG.md does not have details what have changed on released 1.5.x versions.

### ISSUE THREAD

**Issue by vjmp** [mamba-org/mamba#3216]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

Not found on 1.x branch.

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

This is documentation issue, with micromamba changes identification. So https://github.com/mamba-org/mamba/blob/1.x/micromamba/CHANGELOG.md is missing details, which are needed to understand what has changed between versions.

**Comment by Hind-M** [comment]
That's because nothing changed in `micromamba` itself but rather in other entities (`mamba`, `libmamba`, ...) and so the corresponding `CHANGELOG.md` would be empty. See the global [CHANGELOG.md](https://github.com/mamba-org/mamba/blob/1.x/CHANGELOG.md) for details on the overall changes.
