### ISSUE TITLE
How to set register_envs to false with miromamba

### ISSUE THREAD

**Issue by flagarde** [mamba-org/mamba#3223]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

register_envs

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

It seems using https://github.com/mamba-org/mamba/blob/fd42d8dd8ee8cf756b8d0d600663622ac425d392/CHANGELOG.md?plain=1#L255 it is possible to avoid writting to .conda/environements. However I dind't find any way to set the value to false using micromamba. 

How to turn off it ?

Thx

### mamba info / micromamba info

```shell
libmamba version : 1.5.7
     micromamba version : 1.5.7
           curl version : libcurl/8.5.0 OpenSSL/3.2.1 zlib/1.2.13 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.5
       envs directories : /home/working/micromamba/envs
          package cache : /home/working/micromamba/pkgs
                          /home/working/.mamba/pkgs
            environment : None (not found)
           env location : -
      user config files : /home/working/.mambarc
 populated config files : 
       virtual packages : __unix=0=0
                          __linux=6.7.9=0
                          __glibc=2.39=0
                          __archspec=1=x86_64-v3
               channels : 
       base environment : /home/working/micromamba
               platform : linux-64
```

**Comment by Hind-M** [comment]
It was added indeed with #2802 but as mentioned in here https://github.com/mamba-org/mamba/issues/2783#issuecomment-1702193106, it's not yet configurable nor available using the CLI.
