### ISSUE TITLE
[Q/Bug] How do I install the shell init changes to a custom file?

### ISSUE THREAD

**Issue by NightMachinery** [mamba-org/mamba#3237]
I need to add the config file to a custom dotfile, as the standard ones will be overwritten by my provisioning system.

I thought `--rc-file` might do this, but it doesn't:
```
micromamba shell init --shell zsh --rc-file ~/.privateShell
```

**Comment by AntoinePrv** [comment]
You can simply add `eval "$(micromamba shell hook --shell zsh)"` to your file, replacing `zsh` with the correct shell you are using.
