### ISSUE TITLE
memba install errors

### ISSUE THREAD

**Issue by wangguiqian** [mamba-org/mamba#3244]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

memba install errors

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

(work) [gqwang@mn02 ~]$ mamba install r

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.18.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Looking for: ['r']

anaconda/pkgs/main/linux [====================] (00m:00s) No change                                                                             
anaconda/cloud/bioconda/ [====================] (00m:00s) No change                                                                             
anaconda/pkgs/main/linux [====================] (00m:00s) 404 Failed                                                                            

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/public/home/gqwang/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/public/home/gqwang/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 917, in exception_converter
        raise e
      File "/public/home/gqwang/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 911, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/public/home/gqwang/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 869, in _wrapped_main
        result = do_call(args, p)
      File "/public/home/gqwang/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 734, in do_call
        exit_code = install(args, parser, "install")
      File "/public/home/gqwang/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 486, in install
        index = load_channels(pool, channels, repos)
      File "/public/home/gqwang/miniconda3/lib/python3.7/site-packages/mamba/utils.py", line 128, in load_channels
        use_cache=use_cache,
      File "/public/home/gqwang/miniconda3/lib/python3.7/site-packages/mamba/utils.py", line 103, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: Multi-download failed.

`$ /public/home/gqwang/miniconda3/condabin/mamba install r`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=work
                CONDA_EXE=/public/home/gqwang/miniconda3/bin/conda
             CONDA_PREFIX=/public/home/gqwang/miniconda3/envs/work
           CONDA_PREFIX_1=/public/home/gqwang/miniconda3
    CONDA_PROMPT_MODIFIER=(work)
         CONDA_PYTHON_EXE=/public/home/gqwang/miniconda3/bin/python
               CONDA_ROOT=/public/home/gqwang/miniconda3
              CONDA_SHLVL=2
                    CPATH=
           CURL_CA_BUNDLE=<not set>
                    FPATH=
          LD_LIBRARY_PATH=
             LIBRARY_PATH=
                  MANPATH=
      MIC_LD_LIBRARY_PATH=
               MODULEPATH=/public/home/gqwang/.modulefiles:/public/home/software/opt/bio/modules
                          /all/:/public/home/software/opt/database/:/public/home/software/opt/ge
                          nomes/
                  NLSPATH=
                     PATH=/public/home/gqwang/miniconda3/envs/work/bin:/public/home/gqwang/minic
                          onda3/condabin:/public/home/software/opt/moudles/Modules/3.2.10/bin:/o
                          pt/ibm/lsf/10.1/linux3.10-glibc2.17-x86_64/bin:/usr/local/bin:/bin:/us
                          r/bin:/usr/local/sbin:/usr/sbin:/public/home/gqwang/miniconda3/bin:/pu
                          blic/home/gqwang/Software/RNAFramework:/public/home/gqwang/Software/Fu
                          nGAP
           QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : work
    active env location : /public/home/gqwang/miniconda3/envs/work
            shell level : 2
       user config file : /public/home/gqwang/.condarc
 populated config files : /public/home/gqwang/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /public/home/gqwang/miniconda3  (writable)
      conda av data dir : /public/home/gqwang/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /public/home/gqwang/miniconda3/pkgs
                          /public/home/gqwang/.conda/pkgs
       envs directories : /public/home/gqwang/miniconda3/envs
                          /public/home/gqwang/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.23.0 CPython/3.7.7 Linux/3.10.0-862.el7.x86_64 centos/7.5.1804 glibc/2.17
                UID:GID : 1622:1061
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

(work) [gqwang@mn02 ~]$ mamba install mamba=0.18 -n base

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.3) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Looking for: ['mamba=0.18']

anaconda/cloud/bioconda/ [====================] (00m:00s) No change                                                                             
anaconda/pkgs/main/linux [====================] (00m:00s) No change                                                                             
anaconda/cloud/bioconda/ [====================] (00m:00s) No change                                                                             
anaconda/cloud/conda-for [====================] (00m:00s) No change                                                                             
anaconda/pkgs/main/noarc [====================] (00m:00s) No change                                                                             
anaconda/cloud/conda-for [====================] (00m:00s) No change                                                                             
pkgs/main/linux-64       [====================] (00m:00s) No change                                                                             
pkgs/main/noarch         [====================] (00m:00s) No change                                                                             
pkgs/r/linux-64          [====================] (00m:00s) No change                                                                             
pkgs/r/noarch            [====================] (00m:00s) No change                                                                             

Pinned packages:
  - python 3.7.*

Transaction

  Prefix: /public/home/gqwang/miniconda3

  Updating specs:

   - mamba=0.18
   - ca-certificates
   - certifi
   - openssl

  Package          Version  Build           Channel                                                                Size
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  + libmamba        0.18.2  h3985d26_0      mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64       1 MB
  + libmambapy      0.18.2  py37hab1676c_0  mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64     315 KB
  + libzlib         1.2.13  hd590300_5      mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64     Cached
  + pybind11-abi         4  hd8ed1ab_3      mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch        10 KB
  + yaml-cpp         0.6.3  he1b5a44_4      mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64     208 KB

  Change:
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  - _libgcc_mutex      0.1  main            installed                                                                  
  + _libgcc_mutex      0.1  conda_forge     mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64     Cached

  Upgrade:
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  - c-ares          1.11.0  h470a237_1      installed                                                                  
  + c-ares          1.27.0  hd590300_0      mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64     Cached
  - libcurl         7.78.0  h0b77cf5_0      installed                                                                  
  + libcurl         7.86.0  h7bff187_1      mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64     348 KB
  - libgcc-ng       11.2.0  h1234567_1      installed                                                                  
  + libgcc-ng       13.2.0  h807b86a_5      mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64     Cached
  - libgomp         11.2.0  h1234567_1      installed                                                                  
  + libgomp         13.2.0  h807b86a_5      mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64     Cached
  - libnghttp2      1.41.0  hab1572f_1      installed                                                                  
  + libnghttp2      1.51.0  hdcd2b5c_0      mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64     608 KB
  - mamba           0.15.3  py37h7f483ca_0  installed                                                                  
  + mamba           0.18.2  py37h6dacc13_0  mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64      41 KB
  - openssl         1.1.1o  h166bdaf_0      installed                                                                  
  + openssl         1.1.1w  hd590300_0      mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64       2 MB
  - zlib            1.2.11  h7b6447c_3      installed                                                                  
  + zlib            1.2.13  hd590300_5      mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64     Cached

  Downgrade:
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  - _openmp_mutex      5.1  1_gnu           installed                                                                  
  + _openmp_mutex      4.5  2_gnu           mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64     Cached

  Summary:

  Install: 5 packages
  Change: 1 packages
  Upgrade: 8 packages
  Downgrade: 1 packages

  Total download: 5 MB

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] y
Downloading  [====>                                                                                               ] (00m:00s)    1.85 MB/s      
Extracting   [>                                                                                                   ] (--:--)                     
ERROR   File not valid: file size doesn't match expectation "/public/home/gqwang/miniconda3/pkgs/yaml-cpp-0.6.3-he1b5a44_4.tar.bz2"
        Expected: 213138
File size validation error.                                                                                                                     
Downloading  [=====>                                                                                              ] (00m:00s)    1.83 MB/s      
Extracting   [>                                                                                                   ] (--:--)                     
ERROR   File not valid: file size doesn't match expectation "/public/home/gqwang/miniconda3/pkgs/mamba-0.18.2-py37h6dacc13_0.tar.bz2"
        Expected: 41797
File size validation error.                                                                                                                     
Downloading  [======>                                                                                             ] (00m:00s)    2.00 MB/s      
Extracting   [>                                                                                                   ] (--:--)                     
ERROR   File not valid: file size doesn't match expectation "/public/home/gqwang/miniconda3/pkgs/pybind11-abi-4-hd8ed1ab_3.tar.bz2"
        Expected: 9906
File size validation error.                                                                                                                     
Downloading  [============>                                                                                       ] (00m:00s)    3.48 MB/s      
Extracting   [>                                                                                                   ] (--:--)                     
ERROR   File not valid: file size doesn't match expectation "/public/home/gqwang/miniconda3/pkgs/libmambapy-0.18.2-py37hab1676c_0.tar.bz2"
        Expected: 322761
File size validation error.                                                                                                                     
Finished libnghttp2                           (00m:00s)             608 KB      2 MB/s                                                          
Downloading  [============================================>                                                       ] (00m:00s)    5.60 MB/s      
Extracting   [>                                                                                                   ] (--:--)                     
ERROR   File not valid: file size doesn't match expectation "/public/home/gqwang/miniconda3/pkgs/libcurl-7.86.0-h7bff187_1.tar.bz2"
        Expected: 356854
File size validation error.                                                                                                                     
Downloading  [====================================================================================================] (00m:00s)   10.89 MB/s      
Extracting   [============>                                                                                       ] (00m:00s)        1 / 8      
ERROR   File not valid: file size doesn't match expectation "/public/home/gqwang/miniconda3/pkgs/libmamba-0.18.2-h3985d26_0.tar.bz2"
        Expected: 1534565
File size validation error.                                                                                                                     
Finished openssl                              (00m:00s)               2 MB      4 MB/s                                                          
Downloading  [====================================================================================================] (00m:00s)   10.89 MB/s      
Extracting   [=========================>                                                                          ] (00m:00s)        2 / 8      

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/public/home/gqwang/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/public/home/gqwang/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 927, in exception_converter
        raise e
      File "/public/home/gqwang/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 921, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/public/home/gqwang/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 879, in _wrapped_main
        result = do_call(args, p)
      File "/public/home/gqwang/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 757, in do_call
        exit_code = install(args, parser, "install")
      File "/public/home/gqwang/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 613, in install
        downloaded = transaction.prompt(repos)
    RuntimeError: Found incorrect download: yaml-cpp. Aborting

`$ /public/home/gqwang/miniconda3/condabin/mamba install mamba=0.18 -n base`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=work
                CONDA_EXE=/public/home/gqwang/miniconda3/bin/conda
             CONDA_PREFIX=/public/home/gqwang/miniconda3/envs/work
           CONDA_PREFIX_1=/public/home/gqwang/miniconda3
    CONDA_PROMPT_MODIFIER=(work)
         CONDA_PYTHON_EXE=/public/home/gqwang/miniconda3/bin/python
               CONDA_ROOT=/public/home/gqwang/miniconda3
              CONDA_SHLVL=2
                    CPATH=
           CURL_CA_BUNDLE=<not set>
                    FPATH=
          LD_LIBRARY_PATH=
             LIBRARY_PATH=
                  MANPATH=
      MIC_LD_LIBRARY_PATH=
               MODULEPATH=/public/home/gqwang/.modulefiles:/public/home/software/opt/bio/modules
                          /all/:/public/home/software/opt/database/:/public/home/software/opt/ge
                          nomes/
                  NLSPATH=
                     PATH=/public/home/gqwang/miniconda3/envs/work/bin:/public/home/gqwang/minic
                          onda3/condabin:/public/home/software/opt/moudles/Modules/3.2.10/bin:/o
                          pt/ibm/lsf/10.1/linux3.10-glibc2.17-x86_64/bin:/usr/local/bin:/bin:/us
                          r/bin:/usr/local/sbin:/usr/sbin:/public/home/gqwang/miniconda3/bin:/pu
                          blic/home/gqwang/Software/RNAFramework:/public/home/gqwang/Software/Fu
                          nGAP
           QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : work
    active env location : /public/home/gqwang/miniconda3/envs/work
            shell level : 2
       user config file : /public/home/gqwang/.condarc
 populated config files : /public/home/gqwang/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /public/home/gqwang/miniconda3  (writable)
      conda av data dir : /public/home/gqwang/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /public/home/gqwang/miniconda3/pkgs
                          /public/home/gqwang/.conda/pkgs
       envs directories : /public/home/gqwang/miniconda3/envs
                          /public/home/gqwang/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.23.0 CPython/3.7.7 Linux/3.10.0-862.el7.x86_64 centos/7.5.1804 glibc/2.17
                UID:GID : 1622:1061
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

### mamba info / micromamba info

```shell
(base) [gqwang@mn02 ~]$ conda info

     active environment : base
    active env location : /public/home/gqwang/miniconda3
            shell level : 1
       user config file : /public/home/gqwang/.condarc
 populated config files : /public/home/gqwang/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /public/home/gqwang/miniconda3  (writable)
      conda av data dir : /public/home/gqwang/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /public/home/gqwang/miniconda3/pkgs
                          /public/home/gqwang/.conda/pkgs
       envs directories : /public/home/gqwang/miniconda3/envs
                          /public/home/gqwang/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.23.0 CPython/3.7.7 Linux/3.10.0-862.el7.x86_64 centos/7.5.1804 glibc/2.17
                UID:GID : 1622:1061
             netrc file : None
           offline mode : False

(base) [gqwang@mn02 ~]$ conda info

     active environment : base
    active env location : /public/home/gqwang/miniconda3
            shell level : 1
       user config file : /public/home/gqwang/.condarc
 populated config files : /public/home/gqwang/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /public/home/gqwang/miniconda3  (writable)
      conda av data dir : /public/home/gqwang/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /public/home/gqwang/miniconda3/pkgs
                          /public/home/gqwang/.conda/pkgs
       envs directories : /public/home/gqwang/miniconda3/envs
                          /public/home/gqwang/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.23.0 CPython/3.7.7 Linux/3.10.0-862.el7.x86_64 centos/7.5.1804 glibc/2.17
                UID:GID : 1622:1061
             netrc file : None
           offline mode : False

(base) [gqwang@mn02 ~]$ conda info

     active environment : base
    active env location : /public/home/gqwang/miniconda3
            shell level : 1
       user config file : /public/home/gqwang/.condarc
 populated config files : /public/home/gqwang/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /public/home/gqwang/miniconda3  (writable)
      conda av data dir : /public/home/gqwang/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /public/home/gqwang/miniconda3/pkgs
                          /public/home/gqwang/.conda/pkgs
       envs directories : /public/home/gqwang/miniconda3/envs
                          /public/home/gqwang/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.23.0 CPython/3.7.7 Linux/3.10.0-862.el7.x86_64 centos/7.5.1804 glibc/2.17
                UID:GID : 1622:1061
             netrc file : None
           offline mode : False
```

### ~/.condarc

```yaml
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
```

**Comment by jjerphan** [comment]
This must has been fixed since 2.0, feel free to reopen if it has not been the case.
