### ISSUE TITLE
Mamba keep downloading the repodata for every install

### ISSUE THREAD

**Issue by jonbakerfish** [mamba-org/mamba#3257]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

...

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

Eveytime I run `mamba install ...`, the most time-consuming part is downloading the repo data:
```
conda-forge/noarch                                  88.7MB @   5.7MB/s 15.7s
conda-forge/linux-64                               249.2MB @   1.4MB/s 2m:52.2s
```

Can we stop downloading this data if multiple `mamba install` happens in a short time period?

**Comment by jjerphan** [comment]
Duplicates #3431.
