### ISSUE TITLE
miniforge3/bin/conda shebang points to wrong python

### ISSUE THREAD

**Issue by tibuch** [mamba-org/mamba#3270]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

https://github.com/mamba-org/mamba/issues/2224

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

I installed miniforge3 with:
```
curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
bash Miniforge3-$(uname)-$(uname -m).sh
```
But I changed the default install directory to a different one.

After installation and shell initialization I wanted to use the `mamba` command and got the following error:
```
/usr/bin/env: ‘python’: No such file or directory
```

I was able to track the issue down to `miniforge3/bin/conda` and `miniforge3/bin/mamba` where the shebang points to `#!/usr/bin/env python`.
I checked in an older miniforge installation and there the shebang points to `#!/path/to/install_dir/miniforge3/bin/python`.

After changing the shebang in `miniforge3/bin/conda` and `miniforge3/bin/mamba` everything works as expected.

__Note:__ I hope this is the correct repo to report this issue. Unfortunately, I could not find the place where the `conda` and `mamba` files are created.

### mamba info / micromamba info

```shell
mamba version : 1.5.7
     active environment : base
    active env location : /path/to/install_dir/miniforge3
            shell level : 1
       user config file : /home/user-name/.condarc
 populated config files : /path/to/install_dirminiforge3/.condarc
                          /home/user-name/.condarc
          conda version : 24.1.2
    conda-build version : not installed
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=ivybridge
                          __conda=24.1.2=0
                          __cuda=11.8=0
                          __glibc=2.28=0
                          __linux=4.18.0=0
                          __unix=0=0
       base environment : /path/to/install_dir/miniforge3  (writable)
      conda av data dir : /path/to/install_dir/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /path/to/install_dir/miniforge3/pkgs
                          /home/user-name/.conda/pkgs
       envs directories : /path/to/install_dir/miniforge3/envs
                          /home/user-name/.conda/envs
               platform : linux-64
             user-agent : conda/24.1.2 requests/2.31.0 CPython/3.10.14 Linux/4.18.0-372.26.1.el8_6.x86_64 rocky/8.6 glibc/2.28 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.7
                UID:GID : 66903:30065
             netrc file : None
           offline mode : False
```

### Logs

```shell
N/A
```

### environment.yml

```yaml
N/A
```

### ~/.condarc

```yaml
N/A
```

**Comment by jjerphan** [comment]
1.x is note being developed anymore, but to address security fixes.

As of 2.0, mamba and micromamba do not depend on python, so this is rather a problem to be reported on [`conda-forge/miniforge`](https://github.com/conda-forge/miniforge) to me.
