### ISSUE TITLE
Possible to disallow a version without making it a dependency?

### ISSUE THREAD

**Issue by calebzulawski** [mamba-org/mamba#3281]
If I have a broken package e.g. foo 1.2.3, is there a way (maybe in condarc/mambarc?) to exclude that from solving, without making it a dependency?  `foo !=1.2.3` works when it's already a dependency, but if it's not a dependency, it adds it unnecessarily.

I think this is similar to `constrains` in a package, except I would like to avoid making a new channel/package.

**Comment by jjerphan** [comment]
You can constraint your environment by adding specification to the environment's list of pinned packages (i.e. `$CONDA_PREFIX/conda-meta/pinned`).

Hence:
```bash
echo "foo!=1.2.3" >> $CONDA_PREFIX/conda-meta/pinned
```

should resolve your problem.

Please reopen this issue if it does not. :slightly_smiling_face:
