### ISSUE TITLE
ENH,SEC: Add conda-content-trust support to not bypass signature verification in conda >= 23.10

### ISSUE THREAD

**Issue by westurner** [mamba-org/mamba#3283]
- @conda/conda-content-trust: 
  https://github.com/conda/conda-content-trust/issues/123
  - Conda Security Practices > "Enabling conda signature verification"
    https://docs.anaconda.com/pro/security/#enabling-conda-signature-verification
    - > ```
      > conda install "conda>=4.10.1" "conda-token>=0.3.0" conda-content-trust
      > conda token set --enable-signature-verification <YOUR_PRODUCT_TOKEN>
      > ```
      >> Conda version 23.10+ uses libmamba as the default solver, which bypasses signature verification. If you are using conda 23.10 or later, you must configure your .condarc file to use the classic environment solver by running the following command:
      >> `conda config --set solver classic`

- conda-content-trust
  - src: https://github.com/conda/conda-content-trust
  - docs: https://docs.anaconda.com/pro/security/
  - TUF package signatures for conda packages
  - `verify_signature()`
    https://github.com/conda/conda-content-trust/blob/main/conda_content_trust/authentication.py#L253

**Comment by JohanMabille** [comment]
This has been implemented in mamba 2.

**Comment by westurner** [comment]
- https://github.com/mamba-org/mamba/blob/392c5f15c2abc534a145c5fba1e8f0b470acd7f6/libmambapy/CHANGELOG.md?plain=1#L132
  - https://github.com/mamba-org/mamba/pull/3192
