### ISSUE TITLE
[Docs]  all the file systems are not supporting such links？

### ISSUE THREAD

**Issue by gapplef** [mamba-org/mamba#3316]
https://github.com/mamba-org/mamba/blob/221c671fcd2d913c35a91566bf85098ed5b61265/docs/source/advanced_usage/more_concepts.rst?plain=1#L133-L137

What's the meaning here by "`all the file systems are not supporting such links`" ?
Shouldn't it be `not all the file systems are supporting such links`?

**Comment by Hind-M** [comment]
Thanks for reporting!
