### ISSUE TITLE
https://micro.mamba.pm/api/micromamba/linux-64/latest downloads 2.0.0rc1

### ISSUE THREAD

**Issue by pavelzw** [mamba-org/mamba#3349]
xref https://github.com/mamba-org/micromamba-releases/issues/49

CC @JohanMabille @Klaim @AntoinePrv

**Comment by Hind-M** [comment]
Is that fixed now with https://github.com/mamba-org/micromamba-releases/pull/50 and https://github.com/mamba-org/micromamba-releases/pull/51 merged?

**Comment by maxnoe** [comment]
No:

```
❯ curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -C /tmp --strip-components=1 -xvj bin/micromamba
bin/micromamba &&  /tmp/micromamba --version
```

**Comment by Hind-M** [comment]
Seems to be okay now.
