### ISSUE TITLE
Python 3.12 support in `libmambapy`?

### ISSUE THREAD

**Issue by lucascolley** [mamba-org/mamba#3360]
Is `libmambapy` supposed to be installable in a Python 3.12 env? https://github.com/scipy/scipy/pull/21243#issuecomment-2247915911 suggests not.

**Comment by jjerphan** [comment]
Hi Lucas,

In the comment you linked `libmambapy` is being install from Anaconda's channels (AKA `defaults`), but [`libmambapy` is available on conda-forge's channels (AKA `conda-forge` for python 3.12](https://prefix.dev/channels/conda-forge/packages/libmambapy).

Hence, the following should work:

```
mamba install -c conda-forge "python>=3.12" libmambapy
```

**Comment by lucascolley** [comment]
@czgdp1807 could you give that a try?

**Comment by czgdp1807** [comment]
Benchmarks work but I get the following error after executing https://github.com/mamba-org/mamba/issues/3360#issuecomment-2255873100,

```zsh
Couldn't load asv.plugins._mamba_helpers because
No module named 'conda'
```

**Comment by jjerphan** [comment]
You probably need to update conda or asv in the environment you are using.

**Comment by Hind-M** [comment]
Hi @czgdp1807!
Did you manage to get rid of the error and make it work?

**Comment by Hind-M** [comment]
Closing this as it seems to be resolved.
Feel free to reopen if anything else comes up.

**Comment by lucascolley** [comment]
I checked locally that I have no issues running `asv` with `"environment_type": "mamba"` in a Python 3.12 env. Thanks!
