### ISSUE TITLE
micromamba cannot handle blank lines in conda-meta/pinned

### ISSUE THREAD

**Issue by opoplawski** [mamba-org/mamba#3374]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

pinned blank

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

With a blank line in `conda-meta/pinned`, installing packages with micromamba fails with:
```
info     libmamba Parsing MatchSpec
critical libmamba Invalid spec, no package name found:
```
I don't have this problem with conda or mamba.

### mamba info / micromamba info

```shell
libmamba version : 1.5.8
     micromamba version : 1.5.8
           curl version : libcurl/8.6.0 OpenSSL/3.2.1 zlib/1.2.13 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.5
       envs directories : /opt/anaconda/envs
                          /root/conda/envs
          package cache : /var/cache/conda/pkgs
                          /root/.conda/pkgs
            environment : None (not found)
           env location : -
      user config files : /root/.mambarc
 populated config files : /etc/conda/condarc.d/nwra.yml
       virtual packages : __unix=0=0
                          __linux=4.18.0=0
                          __glibc=2.28=0
                          __archspec=1=x86_64-v2
                          __cuda=12.4=0
               channels : https://anaconda.org/main/linux-64
                          https://anaconda.org/main/noarch
       base environment : /root/micromamba
               platform : linux-64
```

**Comment by jjerphan** [comment]
I cannot reproduce this issue as of 2.0.

I am closing this issue as completed since development on 1.x is not going to happen but for security fixes.
