### ISSUE TITLE
"micromamba run" does not forward exit code

### ISSUE THREAD

**Issue by Tyler-g-hudson** [mamba-org/mamba#3395]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

is:issue is:open exit status run 

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

Environment: in Docker image, acquired from Dockerhub `mambaorg/micromamba:1.5.8`
This works across any micromamba environment

Micromamba version:
```
$ micromamba --version
1.3.1
```

Steps to recreate:
```
$ micromamba run -n {my env name} /bin/bash -c exit 1
$ echo $?
0
```

This appears to be an analogue to [Conda issue #8385](https://github.com/conda/conda/issues/8385)

### mamba info / micromamba info

```shell
__
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/


            environment : base (active)
           env location : /opt/conda
      user config files : /home/{user}/.mambarc
 populated config files : 
       libmamba version : 1.3.1
     micromamba version : 1.3.1
           curl version : libcurl/7.87.0 OpenSSL/3.0.8 zlib/1.2.13 libssh2/1.10.0 nghttp2/1.47.0
     libarchive version : libarchive 3.6.2 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.2
       virtual packages : __unix=0=0
                          __linux=3.10.0=0
                          __glibc=2.28=0
                          __archspec=1=x86_64
               channels : 
       base environment : /opt/conda
               platform : linux-64
```

**Comment by luciorq** [comment]
You are probably missing some quotes so, the "exit 1" is passed correctly to `bash -c`


```bash
micromamba create -y -n bash-env -c conda-forge bash;
micromamba run -n bash-env bash -c "exit 1";
builtin echo "${?}";
```

**Comment by Tyler-g-hudson** [comment]
@luciorq This helped me resolve my problem, thanks!
