### ISSUE TITLE
`--force-reinstall` doesn't seem to work after pip uninstalling

### ISSUE THREAD

**Issue by corneliusroemer** [mamba-org/mamba#3399]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

force reinstall

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

After the following steps, even a force reinstall doesn't seem to help, which feels like a bug in force-reinstall:

1. Create env with `python` and `snakemake` with `micromamba create -n bug python snakemake`
2. Reinstall snakemake with pip: `pip install snakemake`
3. Uninstall snakemake with pip: `pip uninstall snakemake`
4. Force reinstall snakemake with micromamba: `micromamba install snakemake --force-reinstall`

Micromamba reports everything is fine - but that's not true. `snakemake` is not found in path:

```
$ micromamba install snakemake --force-reinstall   
conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
bioconda/osx-arm64                                          Using cache
bioconda/noarch                                             Using cache

Pinned packages:
  - python 3.11.*


Transaction

  Prefix: /Users/corneliusromer/micromamba/envs/snakemake

  Updating specs:

   - snakemake


  Package      Version  Build       Channel        Size
─────────────────────────────────────────────────────────
  Reinstall:
─────────────────────────────────────────────────────────

  o snakemake   8.16.0  hdfd78af_0  bioconda     Cached

  Summary:

  Reinstall: 1 packages

  Total download: 0 B

─────────────────────────────────────────────────────────



Transaction starting
Reinstalling snakemake-8.16.0-hdfd78af_0

Transaction finished

To activate this environment, use:

    micromamba activate snakemake

Or to execute a single command in this environment, use:

    micromamba run -n snakemake mycommand

$ which snakemake
snakemake not found
```

**Comment by jjerphan** [comment]
We cannot reproduce this issue with 2.0, please update to 2.0.

Feel free to reopen an issue with a reproduce if you still have this issue with 2.0.

Note that 1.x is note being developed anymore, but to address security fixes.
