### ISSUE TITLE
Micromamba cannot be activated in shell scripts

### ISSUE THREAD

**Issue by Missthepast** [mamba-org/mamba#3439]
Hello, may I ask **how to activate micromamba installed using the official installation method in a shell script**.Using absolute path activation in shell scripts also generates errors. Here are the methods I have tried.
![image](https://github.com/user-attachments/assets/896e35cb-e595-412c-adb8-001e1cff5397)
It can be initialized correctly, but cannot activate using source.
![image](https://github.com/user-attachments/assets/6ab92838-8a66-4e62-8dc1-392d48ac0a94)
I am using Docker and Ubuntu environment.
Is there any way to solve this problem? **Use micromamba in the shell script to activate the specified environment.** Currently, I only have micromamba in my environment.

**Comment by jjerphan** [comment]
It seems `source` does not exist in your shell session, see this line:

```
main.sh: 4: source: not found
```

you can try the following as an alternative:

```
. ~/.bashrc
```

Please reopen this issue if this has not solved your problem.
