### ISSUE TITLE
from 1.5.9, micromamba cannot run on CentOS 6 with GLIBC 2.12

### ISSUE THREAD

**Issue by gzm55** [mamba-org/mamba#3443]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

glibc

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

from 1.5.9, micromamba requires GLIBC 2.17, which cannot run on CentOS 6.

**Comment by h-vetinari** [comment]
This is because of the way things are packaged in conda-forge, which (after many many years of talking about it), switch to CentOS 7 / glibc 2.17 by default a few months ago. If you can convince the mamba-feedstock maintainers, it might still technically be possible to opt into building against an older `c_stdlib_version`...

**Comment by gzm55** [comment]
> This is because of the way things are packaged in conda-forge, which (after many many years of talking about it), switch to CentOS 7 / glibc 2.17 by default a few months ago. If you can convince the mamba-feedstock maintainers, it might still technically be possible to opt into building against an older `c_stdlib_version`...

this breaking change should be introduced in mamba 2.0, not a patch version.

**Comment by gzm55** [comment]
> This is because of the way things are packaged in conda-forge, which (after many many years of talking about it), switch to CentOS 7 / glibc 2.17 by default a few months ago. If you can convince the mamba-feedstock maintainers, it might still technically be possible to opt into building against an older `c_stdlib_version`...

@h-vetinari did you mean https://github.com/conda-forge/mamba-feedstock this repo?

**Comment by h-vetinari** [comment]
Given the title of the issue, you probably want https://github.com/conda-forge/micromamba-feedstock

**Comment by h-vetinari** [comment]
> this breaking change should be introduced in mamba 2.0, not a patch version.

CentOS 6 is EOL for 4 years. It's not a breaking change, you're just on an unsupported system. (Also, how would you imagine 1000s of libraries to all synchronize a new major version release for a change like this? 🤔)

**Comment by jjerphan** [comment]
GLIBC 2.12 is unfortunately too old to be supported by conda-forge builds.

Feel free to reopen if this really is a problem for you.
