### ISSUE TITLE
Incorrect Miniforge Version Recommendation in mamba-installation Docs?

### ISSUE THREAD

**Issue by zvanderbosch** [mamba-org/mamba#3449]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

Tried search, no previous issues reported.

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

**Documentation Issue**

The first sentence of the "Fresh install (recommended)" section of the [mamba installation](https://github.com/mamba-org/mamba/blob/main/docs/source/installation/mamba-installation.rst) instructions says:

"We recommend that you start with the [Miniforge distribution](https://github.com/conda-forge/miniforge) >= ``Miniforge3-22.3.1-0``."

My question is simply, should this instead be ``Miniforge3-23.3.1-0``?  I searched through the [miniforge releases](https://github.com/conda-forge/miniforge/releases) and couldn't find any 22.x versions earlier than ``22.9.0-0``. Also, it would make sense for ``23.3.1-0`` to be recommended here since it appears this was the first version that bundled the ``conda-libmamba-solver`` and ``mamba``, making the ``Mambaforge`` and ``Miniforge3`` installers essentially identical.

**Comment by Hind-M** [comment]
Absolutely! Thank you for reporting this!
If you don't mind opening a PR fixing it, that would be great :)
