### ISSUE TITLE
Micromamba 2.0rc5 - libmamba Error parsing version ""

### ISSUE THREAD

**Issue by bertaveira** [mamba-org/mamba#3453]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

error parsing version

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

I tried the latest rc of micromamba 2.0rc5 as well as the latest master build #af81975 for windows. I noticed it did not work to create an environment from a yaml spec file because it would not accept versions of packages where it would request greater or lower than a certain version. If I make it greater or equal then it works.

Example of a YAML file that fails:
```
channels:
  - conda-forge
dependencies:
  - python > 3.11
  - numpy < 2.0
 ```
With this file if one would create an environment using `micromamba create -f .\environment.yaml -p .\.env` you get this fault:
```
critical libmamba Error parsing version "". Empty version.
```

One can make it not throw that error and create an environment just by changing the versions to this:
```
channels:
  - conda-forge
dependencies:
  - python >= 3.11
  - numpy <= 2.0
 ```

### environment.yml

```yaml
channels:
  - conda-forge
dependencies:
  - python > 3.11
  - numpy < 2.0
```

**Comment by jjerphan** [comment]
I confirm that this is a regression for `micromamba`.
