### ISSUE TITLE
InvalidVersionSpec: Invalid version '~1.0.1': invalid operator

### ISSUE THREAD

**Issue by liamxg** [mamba-org/mamba#3457]
Dear @jezdez,

When I run ` mamba install --file requirements.txt ` command, it printed:

```
Invalid version '~1.0.1': invalid operator

InvalidVersionSpec: Invalid version '~1.0.1': invalid operator
```

Best,
Liam

**Comment by Hind-M** [comment]
Can you please fill in the issue properly, following the bug report?
(`mamba info`, `requirements` file, `.condarc` etc...)

**Comment by jjerphan** [comment]
`~` is an invalid operator `~=` should instead be used.

Feel free to reopen this issue if you need more guidance.
