### ISSUE TITLE
--copy argument no longer works with mamba create in v2.0

### ISSUE THREAD

**Issue by thomashampson** [mamba-org/mamba#3470]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

copy

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

Since the move from 1.5.10 to 2.0 I get the following error when using the `--copy` argument when using `mamba create`:
`The following argument was not expected: --copy`

### mamba info / micromamba info

```shell
mamba create --prefix $CONDA_ENV_PATH --copy --channel $CONDA_CHANNEL --channel conda-forge -y mantidworkbench m2w64-jq
```

### Logs

```shell
The following argument was not expected: --copy
```

**Comment by JohanMabille** [comment]
You can use`--always-copy` instead. We will add the `--copy` flag back for backward compatibility.

**Comment by thomashampson** [comment]
> You can use`--always-copy` instead. We will add the `--copy` flag for backward compatibility.

Thanks, I'll try that now.
