### ISSUE TITLE
`mamba list --full-name` seems to be missing in v2.0.0 (unintended breaking change?)

### ISSUE THREAD

**Issue by mirekphd** [mamba-org/mamba#3477]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

Yes (--full-name)

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

No

### Describe your issue

`mamba list --full-name` seems to be missing in `mamba` v2.0.0, which breaks rather popular builds such as this:
https://github.com/jupyter/docker-stacks/blob/main/images/docker-stacks-foundation/Dockerfile#L132

A workaround is to omit this version when installing `mamba` (here: with `micromamba`), like this:
```
    /tmp/bin/micromamba install \
        --root-prefix="${CONDA_DIR}" \
        --prefix="${CONDA_DIR}" \
        --yes \
        # excluding mamba==2.0.0 due to a breaking change causing these errors:
        # “The following argument was not expected: --full-name” 
        mamba"!=2.0.0" \
```

### mamba info / micromamba info

Can't install it, so can't run `mamba info`.

### Logs

```shell
------
  > [15/47] RUN set -x &&     cd /tmp &&     wget --progress=dot:giga -O - "https://micro.mamba.pm/api/micromamba/linux-64/latest" | tar -xvj bin/micromamba &&     ls -lant bin/micromamba &&     /tmp/bin/micromamba install         --root-prefix="/opt/conda"         --prefix="/opt/conda"         --yes         mamba         python="3.11" &&         rm -rf /tmp/bin/ &&     mamba --version &&     mamba list --full-name 'python' | tail -1 | tr -s ' ' | cut -d ' ' -f 1,2 | sed 's/\.[^.]*$/.*/' >> "/opt/conda/conda-meta/pinned" &&     mamba clean --all -f -y &&     fix-permissions "/opt/conda" &&     fix-permissions "/home/jovyan":
 17.65 + rm -rf /tmp/bin/
 17.65 + mamba --version
 17.66 2.0.0
 17.67 + mamba list --full-name python
 17.67 + tail -1
 17.67 + tr -s ' '
 17.67 + cut -d ' ' -f 1,2
 17.67 + sed 's/\.[^.]*$/.*/'
 17.68 The following argument was not expected: --full-name
 17.68 Run with --help for more information.
 ------
```

### environment.yml

Not used (docker container).

### ~/.condarc

Not used (docker container).

**Comment by JohanMabille** [comment]
Fixed in #3485
