### ISSUE TITLE
Shell init issue on CI

### ISSUE THREAD

**Issue by JohanMabille** [mamba-org/mamba#3478]
micromamba 2.0.0-0 shell init fails with the following message:
"warning  libmamba Not setting long path registry key; Windows version must be at least 10 with the fall 2016 "Anniversary update" or newer."

Reverting to micromamba 1.5.10-0 fixes the issue. See [this build](https://github.com/mamba-org/mamba/actions/runs/11064734845/job/30743014149#step:3:17) for an example of failure.

**Comment by jezdez** [comment]
Wondering if this is related to this change: https://github.com/mamba-org/mamba/pull/3225/files#diff-36fff103b809785e940a91bd500f4205a5e11156eebce5884cb60f1ce4c76d45

**Comment by JohanMabille** [comment]
This file is installed and used when installing / working with mamba. When installing micromamba, it is [generated](https://github.com/mamba-org/mamba/blob/main/libmamba/src/core/shell_init.cpp#L686-L750) when you run `micromamba shell init`.

**Comment by JohanMabille** [comment]
@jezdez actually you were right, this file is used to generate that of micromamba, and it was bugged. It should be fixed in #3484

**Comment by JohanMabille** [comment]
Fixed in https://github.com/mamba-org/mamba/pull/3489
