### ISSUE TITLE
`mamba env export --json` is broken in v2

### ISSUE THREAD

**Issue by mathbunnyru** [mamba-org/mamba#3492]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

mamba env export

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

Docker Stacks project uses `mamba env export -n base --json --no-builds` command

In v1 it worked fine and gave (simplified the output to only keep a few dependencies):

```
{
  "channels": [
    "conda-forge"
  ],
  "dependencies": [
    "_openmp_mutex=4.5",
    "archspec=0.2.3",
    ...
    "zstd=1.5.6"
  ],
  "name": "base",
  "prefix": "/opt/conda"
}
```

In v2, `--no-builds` gives `The following argument was not expected: --no-builds`
If I run `mamba env export -n base --json` it gives this (**and this is not even a JSON**, also simplified the output to only keep a few dependencies):

```
jovyan@2445ff61ab33:~$ mamba env export -n base --json
name: base
channels:
- conda-forge
dependencies:
- _openmp_mutex=4.5=2_gnu
- bzip2=1.0.8=h68df207_7
...
- zstd=1.5.6=h02f22dd_0
```

### mamba info / micromamba info

```shell
jovyan@2445ff61ab33:~$ mamba info

       libmamba version : 2.0.1
          mamba version : 2.0.1
           curl version : libcurl/8.9.1 OpenSSL/3.3.2 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 liblzma/5.2.6 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.6
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /home/jovyan/.mamba/pkgs
            environment : base
           env location : /opt/conda
      user config files : /home/jovyan/.mambarc
 populated config files : /opt/conda/.condarc
       virtual packages : __unix=0=0
                          __linux=6.10.4=0
                          __glibc=2.39=0
                          __archspec=1=aarch64
               channels : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /opt/conda
               platform : linux-aarch64
```
```


### Logs

_No response_

### environment.yml

_No response_

### ~/.condarc

_No response_

**Comment by mathbunnyru** [comment]
Instead of `--no-builds` I can use `--no-build` now.
`--json` still doesn't work though

**Comment by mathbunnyru** [comment]
Thank you @jjerphan

**Comment by jjerphan** [comment]
You are welcome, @mathbunnyru.
