### ISSUE TITLE
How does mamba wrapper decide which executable to use?

### ISSUE THREAD

**Issue by corneliusroemer** [mamba-org/mamba#3498]
I have multiple versions of micromamba installed (through brew, conda, and shell installer).

I would like to understand which version is used by default. I don't know, because the mamba wrapper is opaque - it's not (as usual) the first item of `which -a`.

```
$ which -a micromamba
micromamba () {
	__mamba_wrap "${@}"
}
/opt/homebrew/Caskroom/miniforge/base/bin/micromamba
/opt/homebrew/bin/micromamba
/Users/corneliusromer/.local/bin/micromamba
/Users/corneliusromer/.local/bin/micromamba
/Users/corneliusromer/.local/bin/micromamba
/Users/corneliusromer/.local/bin/micromamba
```

How does the wrapper work?

**Comment by jjerphan** [comment]
To understand how it it setup, you can execute:

```bash
where __mamba_wrap
```
and

```bash
where __mamba_exe
```

> I have multiple versions of micromamba installed (through brew, conda, and shell installer).

We recommend against having several installations of `micromamba` because this leads in practice to a lot of pathological edge cases as you have had observed in the past.
