### ISSUE TITLE
mamba 2 breaks Jupyter docker-stacks

### ISSUE THREAD

**Issue by JohanMabille** [mamba-org/mamba#3506]
See [details](https://github.com/jupyter/docker-stacks/pull/2147)

**Comment by mathbunnyru** [comment]
I think this is now the only issue which prevents Jupyter Docker Stacks from switching to v2: https://github.com/mamba-org/mamba/issues/3503

As far as I see, `[conda-libmamba-solver](https://github.com/conda/conda-libmamba-solver)` is now compatible with v2, so we're waiting for the new version to be released.
And also waiting for a new release of `mamba`, to include fixes made here.

**Comment by mathbunnyru** [comment]
One more issue preventing us from updating: https://github.com/mamba-org/mamba/issues/3582
I submitted the fix: https://github.com/mamba-org/mamba/pull/3590

**Comment by jjerphan** [comment]
@mathbunnyru: should we close this issue now that mamba 2 can be used?

**Comment by mathbunnyru** [comment]
I found one more difference between v1 and v2

v2:

```
(base) jovyan@27933482a351:~$ mamba env export --no-build --json --from-history
{
  "channels": [
    "conda-forge"
  ],
  "dependencies": [
    "conda",
    "jupyter_core",
    "jupyterhub-singleuser",
    "jupyterlab",
    "mamba",
    "nbclassic",
    "notebook>=7.2.2",
    "python=3.12"
  ],
  "name": "base",
  "prefix": "/opt/conda"
}
```

v1:

```
(base) jovyan@c5da4bba1d79:~$ mamba env export --no-build --json --from-history
{
  "channels": [
    "conda-forge"
  ],
  "dependencies": [
    "jupyter_core",
    "mamba[version='<2.0.0']",
    "python=3.12",
    "jupyterhub-singleuser",
    "jupyterlab",
    "nbclassic",
    "notebook[version='>=7.2.2']",
    "ca-certificates",
    "certifi",
    "openssl"
  ],
  "name": "base",
  "prefix": "/opt/conda"
```

**Comment by mathbunnyru** [comment]
Note the line with `notebook`.

v2's output is not compatible with conda's output when some lib was installed specifying version range

**Comment by mathbunnyru** [comment]
We only use this in testing our images, so I will change the way we do it in `docker-stacks`.
But I still think it should be fixed (to be compatible with conda).

**Comment by jjerphan** [comment]
Let's open a dedicated issue for this?

**Comment by mathbunnyru** [comment]
> Let's open a dedicated issue for this?

Yes, was just doing that 🙂

**Comment by mathbunnyru** [comment]
Done: https://github.com/mamba-org/mamba/issues/3646

**Comment by mathbunnyru** [comment]
@JohanMabille @jjerphan could you please close this issue?
