### ISSUE TITLE
Minor regression when installing from requirements.txt files with comments

### ISSUE THREAD

**Issue by ocefpaf** [mamba-org/mamba#3509]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

yes

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

Latest micromamba comments, even inline ones, as packages and fails to build envs.

See https://github.com/ioos/compliance-checker/actions/runs/11172812100/job/31059877973?pr=1109

### mamba info / micromamba info

```shell
libmamba version : 2.0.2
     micromamba version : 2.0.2
           curl version : libcurl/8.9.1 OpenSSL/3.3.2 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.6
       envs directories : /home/filipe/micromamba/envs
          package cache : /home/filipe/micromamba/pkgs
                          /home/filipe/.mamba/pkgs
            environment : base
           env location : /home/filipe/micromamba
      user config files : /home/filipe/.mambarc
 populated config files : /home/filipe/.condarc
       virtual packages : __unix=0=0
                          __linux=6.8.0=0
                          __glibc=2.39=0
                          __archspec=1=x86_64_v3
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /home/filipe/micromamba
               platform : linux-64
```

**Comment by jjerphan** [comment]
Thank you for reporting this problem, @ocefpaf.

It seems that the logs that you are providing are empty.

Do you have a specification of the environment we could use to reproduce the problem?

**Comment by ocefpaf** [comment]
Maybe this one: https://github.com/ioos/compliance-checker/actions/runs/11172812100/job/31059877973?pr=1109#step:3:29
