### ISSUE TITLE
`micromamba` cannot run in an alpine docker container

### ISSUE THREAD

**Issue by Hind-M** [mamba-org/mamba#3514]
When trying to test in an `alpine:latest` docker container, I also encountered the issue described in this SO post (the `micromamba` binary cannot be executed):

https://stackoverflow.com/questions/36279253/go-compiled-binary-wont-run-in-an-alpine-docker-container-on-ubuntu-host

(cf. https://github.com/mamba-org/mamba/issues/3388#issuecomment-2376581557).

**Comment by wholtz** [comment]
Running `micromamba` on a pure `alpine` image is prettty useless, as you need glibc for most conda packages to work and alpine does not come with glibc. But using an alpine image where glibc has been provided works for me:

```shell
$ docker run -it --rm --platform=linux/amd64 mambaorg/micromamba:alpine3.20 micromamba info

       libmamba version : 2.0.2
     micromamba version : 2.0.2
           curl version : libcurl/8.10.1 OpenSSL/3.3.2 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 bz2lib/1.0.8 libzstd/1.5.6
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /home/mambauser/.mamba/pkgs
            environment : base (active)
           env location : /opt/conda
      user config files : /home/mambauser/.mambarc
 populated config files :
       virtual packages : __unix=0=0
                          __linux=6.10.4=0
                          __glibc=2.34=0
                          __archspec=1=x86_64_v2
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /opt/conda
               platform : linux-64
```

**Comment by Hind-M** [comment]
Thanks for your feedback @wholtz!
Does this answer your question @pauldmccarthy?

**Comment by Hind-M** [comment]
Closing the issue, as it seems there is a solution for this.
Feel free to reopen if further related issues come up.

**Comment by pauldmccarthy** [comment]
Hi @Hind-M, apologies, I forgot to reply - this isn't really an issue for me, but I reported it as it indicated that there could be a problem with your build process :+1:
