### ISSUE TITLE
`micromamba` accepting txt files?

### ISSUE THREAD

**Issue by Hind-M** [mamba-org/mamba#3516]
On another note, I also noticed that the `micromamba install -f <file>` option differs from `conda install -f <file>` in the expected file format - `conda` expects to be given a plain-text file with one package constraint per line (e.g. `python=3.11`), whereas `micromamba` expects to be given a `conda` environment yml file.

So I'm wondering whether I can rely on the `micromamba` implementation continuing to accept the environment `yml` file format into the future? Or is there a chance that it will be changed to mimic the `conda` behaviour?

(cf. https://github.com/mamba-org/mamba/issues/3388#issuecomment-2388038869)

**Comment by jjerphan** [comment]
`micromamba` 2.0, 1.5.10 (and potentially previous version) do support any text file agnostically from their extension.

For instance this can be used to create and populate environment from a simple text file:

```
echo "numpy" > /tmp/spec
micromamba create -p /tmp/env -f /tmp/spec.txt -y
echo "scipy" >> /tmp/spec
micromamba install -p /tmp/env -f /tmp/spec.txt -y
```

@pauldmccarthy: could you craft a reproducer of the problem you were facing? :pray:

**Comment by pauldmccarthy** [comment]
Hi @jjerphan, I just wanted to make sure whether this was intended behaviour - i.e. can I rely on being able to pass a [conda environment `.yml` file](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually) to `micromamba install -f`? This is not possible with conda, hence the question. Thanks!

**Comment by jjerphan** [comment]
Yes, the following work:

```
micromamba create -n env_name
micromamba install -n env_name -f spec.yaml
```

**Comment by pauldmccarthy** [comment]
@jjerphan thanks!
