### ISSUE TITLE
Different exe naming for micromamba shared/static build

### ISSUE THREAD

**Issue by gdolle** [mamba-org/mamba#3531]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

exe naming

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I have this problem with Conda as well, without using Mamba

### Describe your issue

Hi,

Since version 2.x.x, there are two different targets and names for the static/shared build of micromamba which 
produces two executables : "mamba" and "micromamba" for the same software.

The naming and cmake options are very misleading for packaging regarding pre 2.x.x (as if there was two different software now...)

Would it be possible to keep only one name `mamba` or `micromamba`, or use suffix naming like `micromamba`/`micromamba_<arch>` for the static one ?

**Comment by jjerphan** [comment]
Hi,

Thank you for your report.

> Would it be possible to keep only one name `mamba` or `micromamba`, or use suffix naming like `micromamba/micromamba_<arch>` for the static one ?

Unfortunately `mamba` and `micromamba` are here to stay as independent executable names. We recommend using aliases if you have specific needs.
