### ISSUE TITLE
can mamba directly use folder of envs from conda 

### ISSUE THREAD

**Issue by NewUserHa** [mamba-org/mamba#3551]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

na

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

can mamba directly use folders of envs from conda? can the folders under envs change its folder name or be moving around?

And some packages only exists in anaconda default channels, and micromamba can use the channel like `tensorflow 2.10 gpu build`, 
therefore the must-choose option of ` I do NOT use the Anaconda default channels (pkgs/* etc.) *` can be changed to a dropdown box.

**Comment by jjerphan** [comment]
It is hard to understand your questions.

Mamba and conda can use the same environment if they are present in the same (miniforge) installation.

We recommend against using Anaconda's channels (i.e. `defaults`) and conda-forge's (i.e. `conda-forge`).

Please reopen issues with dedicated and more scopes questions so that we can better respond to them.

**Comment by NewUserHa** [comment]
I meant
* I saw the content of `.json` files in `conda-meta` folder under `envs` folder is different between `conda` and `micromamba`, is it able to use one `env` folder interchangeably with `conda` and `micromamba`
* for example the `tensorflow 2.10 gpu build` package is the last build of `tensorflow-gpu` work on windows, it only exists in the `anaconda defaults channels` repo but not in the `conda-forge` repo. So that `micromamba` can use `anaconda defaults channels` is a big advantage than `mamba`. 
so `micromamba` probably will be more welcome, the `I do NOT use the Anaconda default channels (pkgs/* etc.) *` of this repo issue template could be changed to a non-must option
