### ISSUE TITLE
mamba always rewrite `condabin\mamba.bat` after run `mamba install`

### ISSUE THREAD

**Issue by NewUserHa** [mamba-org/mamba#3552]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

na

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

because https://github.com/mamba-org/mamba/pull/3525 hasn't be published,
found after running `mamba install`, `condabin\mamba.bat` file always get rewrote

**Comment by NewUserHa** [comment]
there is no new released version. it is the current latest 2.0.1 version has this issue.

may ask if https://github.com/mamba-org/mamba/pull/3546 also fixed this issue within it

**Comment by jjerphan** [comment]
The problem has been fixed as of 2.0.4 which features both https://github.com/mamba-org/mamba/pull/3525 and https://github.com/mamba-org/mamba/pull/3546.

Please feel free to reopen this issue if you meet any problems.
