### ISSUE TITLE
error libmamba Could not lock non-existing path '.mamba\pkgs' & simple fix

### ISSUE THREAD

**Issue by dreamflow** [mamba-org/mamba#3560]
when no folders/files and configs(environment.yml , .condarc , ...)
of micromamba exist , on the very first run of
`".\micromamba-64bit.exe" create --prefix ".\64bit" python`
on Win10 , on a local ntfs drive or on a network drive ,
gives the errors
```perl
error libmamba Could not lock non-existing path '<USERPROFILE>\.mamba\pkgs'
error libmamba Could not lock non-existing path '<APPDATA>\.mamba\pkgs'
```
simple fix :
these errors vanish , if libmamba would simply first
create both ".mamba\pkgs" folders prior trying
to write its "pkgs.lock" files into these folders .

i can confirm , that these errors don't appear ,
if both ".mamba\pkgs" folders are created before .

could please this be implemented into libmamba .
it would give new micromamba users a nicer first experience .

**Comment by yeetfield** [comment]
@Hind-M How do I configure the prefix in which Mamba attempts to put its `.mamba/pkgs` directory? I'd like to avoid modifying `~` if possible. I tried setting `MAMBA_ROOT_PREFIX` as well as using `micromamba -r`.

**Comment by dreamflow** [comment]
> How do I configure the prefix in which Mamba
 > attempts to put its .mamba/pkgs directory?

on windows i do this without the env var
MAMBA_ROOT_PREFIX , but instead by temporarily ,
only during the run of micromamba-64bit.exe ,
changing the env vars USERPROFILE and APPDATA .
this works very nice because micromamba uses :
<USERPROFILE>\.mamba\pkgs
<USERPROFILE>\AppData\Roaming\mamba
<APPDATA>\.mamba\pkgs
