### ISSUE TITLE
DOC: explain how mamba2 and micromamba2 differ

### ISSUE THREAD

**Issue by lucascolley** [mamba-org/mamba#3571]
Reading the mamba 2.0 changes page in the docs, I understand the general sentiment that mamba and micromamba have become more similar to each other. I also understand from other docs pages that they are still different in that they can be installed differently.

Aside from that, how do they differ? Why might I choose to use one over the other?

**Comment by henryiii** [comment]
I'm assuming they are exactly identical, just one is statically linked and the other dynamically linked in https://github.com/Homebrew/homebrew-core/pull/195371. Could be wrong, though, based that on parts of the docs that looked updated!

**Comment by jjerphan** [comment]
We are wording this with #3610, I would invite you to give it a review if you can. :slightly_smiling_face:
