### ISSUE TITLE
GitHub releases for 2.0.2 and 2.0.3?

### ISSUE THREAD

**Issue by henryiii** [mamba-org/mamba#3577]
The repo still reports 2.0.1 as the latest version on the main GitHub page. I'm guessing these were supposed to be made from the date-based tags?

Also, where are there tags for each of the different binaries when the source is the same? This is making https://github.com/Homebrew/homebrew-core/pull/195371 confusing. :) They seem the same, so maybe just historical.

**Comment by Hind-M** [comment]
The latest reported version in https://github.com/mamba-org/mamba/releases is `2.0.2`.
`2.0.3` had some issues and was marked broken (so not mentioned in the GH page) - cf. https://github.com/mamba-org/mamba/issues/3576.
A `2.0.4` version containing the  https://github.com/mamba-org/mamba/issues/3576 fix and more will be released soonish.

> Also, where are there tags for each of the different binaries when the source is the same? This is making https://github.com/Homebrew/homebrew-core/pull/195371 confusing. :) They seem the same, so maybe just historical.

Not sure I understand what you mean. Tags are [here](https://github.com/mamba-org/mamba/tags) with the corresponding commit they refer to.

**Comment by henryiii** [comment]
There are four matching tags for each release: `2024.10.02`, `micromamba-2.0.2`, `mamba-2.0.2`, and `libmamba-2.0.2`. All point at the same commit. That seems more confusing than having a `v2.0.2` tag.

Not showing a release because it's broken is fine, and 2.0.2 is visible, so I think this is complete. Looking forward to 2.0.4, especially if it contains the fixes for brew. :)
