### ISSUE TITLE
`mamba env export --json --from-history` is broken in v2

### ISSUE THREAD

**Issue by mathbunnyru** [mamba-org/mamba#3582]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

mamba, env, export, from-history

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

When I run `mamba env export --json --from-history` it produces invalid json file:

```
{
  "channels": [
    "conda-forge"
  ],
  "dependencies": [
    "jupyter_core",
    "mamba",
    "python=3.12",
  ],
  "name": "base",
  "prefix": "/opt/conda"
}
```

Note: **--from-history** flag is important here, without it everything is ok, the json is invalid due to `,` in the last element of dependencies.

### mamba info / micromamba info

```shell
libmamba version : 2.0.3
          mamba version : 2.0.3
           curl version : libcurl/8.10.1 OpenSSL/3.3.2 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.64.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 liblzma/5.2.6 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.6
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
                          /home/jovyan/.mamba/pkgs
            environment : base
           env location : /opt/conda
      user config files : /home/jovyan/.mambarc
 populated config files : /opt/conda/.condarc
       virtual packages : __unix=0=0
                          __linux=6.10.11=0
                          __glibc=2.39=0
                          __archspec=1=aarch64
               channels : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /opt/conda
               platform : linux-aarch64
```

**Comment by mathbunnyru** [comment]
Related to: https://github.com/mamba-org/mamba/issues/3492

The `json` output was added in https://github.com/mamba-org/mamba/pull/3559/files

@jjerphan you might want to take a look

**Comment by maresb** [comment]
I'm running into a different problem of a very similar style in #3583
