### ISSUE TITLE
Cannot set permissions  : Operation not permitted

### ISSUE THREAD

**Issue by aulemahal** [mamba-org/mamba#3606]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge

### Search tried in issue tracker

"cannot set permissions"

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I didn't try

### Describe your issue

We have a shared installation of mambaforge on our shared linux machine. We've always has this issue described here : https://github.com/conda/conda/issues/7227, but I was always able to work around it by changing the permissions of the `pkgs/cache` dir periodically. 

However, since updating to the latest mamba (2.0.3), this doesn't work anymore. Even if the folder and it's files have 777 permissions, `libmamba` seems to want to set the permissions, and it fails, of course.

The user command and error:
```shell
[user@machine ~]$ mamba env create -f environment.yml
critical libmamba filesystem error: cannot set permissions: Operation not permitted [/mambaforge-dir/pkgs/cache]
```
and the folder's permissions seen by the admin:
```shell
[admin@machine cache]$ ls -alh /mambaforge-dir/pkgs/cache
total 584M
drwxrwsrwx.    2 admin thegroup 4.0K Nov 15 09:32 .
drwxrwsrwx. 5722 admin thegroup 304K Nov 14 17:05 ..
-rwxrwxrwx.    1 admin thegroup 288M Nov 14 16:58 88ec62ec.json
-rwxrwxrwx.    1 admin thegroup 134M Nov 14 16:59 88ec62ec.solv
-rwxrwxrwx.    1 admin thegroup  378 Nov 14 16:58 88ec62ec.state.json
-rwxrwxrwx.    1 admin thegroup 106M Nov 14 16:58 eb045dd1.json
-rwxrwxrwx.    1 admin thegroup  57M Nov 14 16:59 eb045dd1.solv
-rwxrwxrwx.    1 admin thegroup  376 Nov 14 16:58 eb045dd1.state.json
```

To fix the issue, I went back to mamba < 2. I didn't try other versions.

### mamba info / micromamba info

```shell
sorry I downgraded mamba before opening this issue and forgot to do that.
```

### Logs

```shell
oups, same thing.
```

### ~/.condarc

```yaml
# user:
envs_dirs:
  - /USER/DIR/.conda
pip_interop_enabled: true

# global
channels:
- conda-forge
```

**Comment by jjerphan** [comment]
Duplicates #3661.

**Comment by skol101** [comment]
Same here. Also, trying to setup shared packages cache with pkgs_dirs on .condarc.

Running on ubuntu 24. Same was on ubuntu 22.04

 libmamba version : 2.0.4
          mamba version : 2.0.4
