### ISSUE TITLE
`micromamba/src/[micro]server.cpp` files are not compiled and broken

### ISSUE THREAD

**Issue by mathbunnyru** [mamba-org/mamba#3677]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Other (please describe)

### Search tried in issue tracker

microserver

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

There are issues with these files:
- `server.cpp` includes `microserver.cpp` (yes, source file, not header)
- only `server.cpp` is mentioned in cmake files (https://github.com/mamba-org/mamba/blob/main/micromamba/CMakeLists.txt#L48-L51)
- these files are not built by default and not built in CI, and their compilation is broken

Ref: https://github.com/mamba-org/mamba/pull/3667#discussion_r1876309035

**Comment by JohanMabille** [comment]
This code needs a complete rewrite. Let's keep the source files as a reference and tackle the refactoring as soon as we can (probably starting in 2025).

**Comment by jjerphan** [comment]
You need to install [dependencies for building targets statically](dev/environment-micromamba-static.yml).

**Comment by jjerphan** [comment]
I would just remove this code if it is not used, we can always checkout to previous versions.

**Comment by wolfv** [comment]
IMO it can be removed. We've since started the `rattler-server` project: https://github.com/mamba-org/rattler-server
