### ISSUE TITLE
mamba env config vars set is not working in version >= 2

### ISSUE THREAD

**Issue by peterroelants** [mamba-org/mamba#3683]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Mambaforge or latest Miniforge.
More specificially via https://github.com/conda-forge/miniforge about 6 months ago. However I recently updated using `mamba update mamba conda `

### Search tried in issue tracker

mamba env config vars set

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

I used to be able to set environment variables in a mamba environment using `mamba env config vars set VAR_NAME=<var>`. However after upgrading to mamba version >=2 this is not working anymore and is breaking my scripts.

It seems like `mamba env config vars set` is not even available anymore.
```
❯ mamba env config --help
...
Subcommands:
  list                        List known environments
  create                      Create new environment (pre-commit.com compatibility alias for 'micromamba create')
  export                      Export environment
  remove                      Remove an environment
  update                      Update an environment
```

I installed mamba via miniforge a while back and recently updated it. Looking at the release notes it seems like this could be caused by [using micromamba under the hood since version 2](https://mamba.readthedocs.io/en/latest/developer_zone/changes-2.0.html#mamba-executable). I found [this older issue](https://github.com/mamba-org/mamba/issues/1881) stating that `mamba env config vars set` has never worked for micromamba.

Btw using conda this [`conda env config vars set`](https://docs.conda.io/projects/conda/en/latest/commands/env/config/vars/set.html) still works

### mamba info / micromamba info

```shell
libmamba version : 2.0.4
          mamba version : 2.0.4
           curl version : libcurl/8.10.1 OpenSSL/3.4.0 zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.58.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 liblzma/5.2.6 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.6
       envs directories : /home/peter/miniforge3/envs
          package cache : /home/peter/miniforge3/pkgs
                          /home/peter/.mamba/pkgs
            environment : base
           env location : /home/peter/miniforge3
      user config files : /home/peter/.mambarc
 populated config files : /home/peter/.condarc
                          /home/peter/miniforge3/.condarc
       virtual packages : __unix=0=0
                          __linux=6.8.0=0
                          __glibc=2.39=0
                          __archspec=1=x86_64_v4
                          __cuda=12.6=0
               channels : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
       base environment : /home/peter/miniforge3
               platform : linux-64
```

**Comment by jjerphan** [comment]
Duplicates https://github.com/mamba-org/mamba/issues/1881.
