### ISSUE TITLE
brew's micromamba seems to install mamba as well

### ISSUE THREAD

**Issue by BastianZim** [mamba-org/mamba#3687]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

Mamba in micromamba

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

Not applicable

### Describe your issue

I installed micromamba from brew using `brew install micromamba`. This seems to install mamba instead. 

```zsh
bastianzimmermann@Bastians-MacBook ~ % which mamba
/opt/homebrew/bin/mamba
bastianzimmermann@Bastians-MacBook ~ % which micromamba 
micromamba () {
	__mamba_wrap "$@"
}
bastianzimmermann@Bastians-MacBook ~ % type mamba
mamba is /opt/homebrew/bin/mamba
```
Why is micromamba not mentioned here?

Additionally, I have a file called `mamba` under my user, not `.mamba` and the directories from `info` don't exist.

### mamba info / micromamba info

```shell
libmamba version : 2.0.4
     micromamba version : 2.0.4
           curl version : libcurl/8.7.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.62.0
     libarchive version : libarchive 3.7.7 zlib/1.2.12 liblzma/5.6.3 bz2lib/1.0.8 liblz4/1.10.0 libzstd/1.5.6
       envs directories : /opt/homebrew/envs
          package cache : /opt/homebrew/pkgs
                          /Users/bastianzimmermann/.mamba/pkgs
            environment : base
           env location : /opt/homebrew
      user config files : /Users/bastianzimmermann/.mambarc
 populated config files : 
       virtual packages : __unix=0=0
                          __osx=15.1.1=0
                          __archspec=1=arm64
               channels : https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/osx-arm64
       base environment : /opt/homebrew
               platform : osx-arm64
```

### ~/.condarc

```yaml
No such file or directory
```

**Comment by BastianZim** [comment]
To clarify, I don't know if this is on purpose or not, it just seems odd that both are showing up.

**Comment by jjerphan** [comment]
We do not maintain the distribution of micromamba or mamba on HomeBrew.

The latest version of micromamba has been published on homebrew with https://github.com/mamba-org/mamba/issues/3687.

Related to https://github.com/mamba-org/mamba/issues/3495.

**Comment by BastianZim** [comment]
Ahh I see. So you think the issue is with the homebrew installation?

**Comment by jjerphan** [comment]
Yes, it is. Could you close this issue and reopen on on [`Homebrew/homebrew-core`](https://github.com/Homebrew/homebrew-core)?

**Comment by BastianZim** [comment]
I have heard back from homebrew and they mention that it's not an issue with them: https://github.com/Homebrew/homebrew-core/issues/200954#issuecomment-2539869725

Is their statement correct?

**Comment by BastianZim** [comment]
Ahh I see that makes sense, thank you. 

Do you think this is something worth pursuing or should I just install mamba and call it a day?

**Comment by jjerphan** [comment]
I don't think resolving this problem is the mamba development team's responsibility and priority.
