### ISSUE TITLE
`mamba info --quiet` output is empty

### ISSUE THREAD

**Issue by mathbunnyru** [mamba-org/mamba#3714]
### Troubleshooting docs

- [X] My problem is not solved in the Troubleshooting docs

### Anaconda default channels

- [X] I do NOT use the Anaconda default channels (pkgs/* etc.)

### How did you install Mamba?

Micromamba

### Search tried in issue tracker

mamba info quiet

### Latest version of Mamba

- [X] My problem is not solved with the latest version

### Tried in Conda?

I do not have this problem with Conda, just with Mamba

### Describe your issue

Before v2, `mamba info --quiet` gave a relevant information on the current mamba installation.
Now, the output is empty.

Note, that `conda info --quiet` is not empty (so v1 matched this behaviour)

### mamba info / micromamba info

```shell
active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/jovyan/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 24.11.2
    conda-build version : not installed
         python version : 3.12.8.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=aarch64
                          __conda=24.11.2=0
                          __glibc=2.39=0
                          __linux=6.10.14=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-aarch64
             user-agent : conda/24.11.2 requests/2.32.3 CPython/3.12.8 Linux/6.10.14-linuxkit ubuntu/24.04.1 glibc/2.39 solver/libmamba conda-libmamba-solver/24.11.1 libmambapy/2.0.5
                UID:GID : 1000:100
             netrc file : None
           offline mode : False
```

**Comment by mathbunnyru** [comment]
Not a huge problem, but this unfortunately made our manifest files look quite bad:
https://github.com/jupyter/docker-stacks/wiki/x86_64-default-tensorflow-notebook-87b37b4fd818

I will change our code to not use `--quiet` flag in this case.

**Comment by mathbunnyru** [comment]
And one more issue - `mamba info`s output is not similar to `conda info`s output.
For example, in mamba's output there is no `python version`

**Comment by Hind-M** [comment]
Actually, `--quiet` is not exactly the same in `mamba` and `conda`.

From `conda info --help`:
`-q, --quiet        Do not display progress bar.`

From `mamba info --help`:
`-q,--quiet         Set quiet mode (print less output)`

So to me, nothing is unexpected. I agree though that the `mamba` description is quite vague. I think that this can be improved depending on the use case, but for this one I guess using `info` without `--quiet` solves the problem IIUC?

As for the `info` output difference between `conda` and `mamba` regarding `python version`, this is also expected as `mamba 2` is no longer `python` dependent unlike `conda`.

**Comment by mathbunnyru** [comment]
> Actually, `--quiet` is not exactly the same in `mamba` and `conda`.
> 
> From `conda info --help`: `-q, --quiet Do not display progress bar.`
> 
> From `mamba info --help`: `-q,--quiet Set quiet mode (print less output)`
> 
> So to me, nothing is unexpected. I agree though that the `mamba` description is quite vague. I think that this can be improved depending on the use case, but for this one I guess using `info` without `--quiet` solves the problem IIUC?
> 
> As for the `info` output difference between `conda` and `mamba` regarding `python version`, this is also expected as `mamba 2` is no longer `python` dependent unlike `conda`.

Yes, that's exactly how I solved the problem: removed the `--quiet` flag from `mamba info` and also added `conda info` (if someone needs it): https://github.com/jupyter/docker-stacks/pull/2191/files

If this behaviour is expected, I'm fine with closing the issue, thank you!
