### ISSUE TITLE
Update doesn't follow strict channel priority the same as conda

### ISSUE THREAD

**Issue by owen-synergy** [mamba-org/mamba#396]
I'm using mamba 0.4.1 on Windows 10 - conda is configured with strict channel priority with conda-forge being the top priority channel followed by defaults. When I performed a mamba update --all it downloaded mkl to 2020.1-216 from defaults and installed the default channel mkl-service-2.3.0. When I followed that by a conda update --all, conda downgraded mkl back again and switched back to the conda-forge channel mkl-service package since that had channel priority.

I don't know if this is right or wrong but this behaviour isn't consistent with conda in terms of how it is updating packages with the strict priority (I know conda-forge always recommends strict channel priority since some of their packages aren't binary compatible with the defaults channel).

**Comment by wolfv** [comment]
Thanks for the bug report, that sounds indeed like a problem with update-all.

**Comment by wolfv** [comment]
I have looked into this briefly, and couldn't find an obvious reason for why this happens. Will have to check inside libsolv what's going on.

**Comment by owen-synergy** [comment]
Let me know if there's any extra information I can provide to help reproduce the issue.

**Comment by wolfv** [comment]
Someone was raising another issue in another channel where the problem was that pymysql was selected with a version specifier.

if the (exact) version exists on the lower prio channel, it might be chosen (when selected with the version specifier). 

https://github.com/conda-forge/pymysql-feedstock/issues/7#issuecomment-663094861

It does look like something we need to tune. That could be the same underlying reason for the inconsitstency with `update --all`

**Comment by opoplawski** [comment]
I'm seeing with:
```
mamba update  -n scipy36-intel --override-channels --strict-channel-priority -c intel -c main -c conda-forge --all
```
That it wants to install python from the main channel instead of sticking with the intel channel:
```
 Change:
─────

-  python                         3.6.3  intel_12             installed                                              
+ python                         3.6.3  h6c0c0dc_5          main/linux-64                 25 MB
```

**Comment by opoplawski** [comment]
Things are looking better with 0.15.2 so I'm going to close this.  Thanks.

**Comment by wolfv** [comment]
Thanks!
