### ISSUE TITLE
Document feature parity (or lack thereof)

### ISSUE THREAD

**Issue by h-vetinari** [mamba-org/mamba#40]
Quick question:

is there a quick reference of which commands from conda are or aren't supported? Or a version who's API is the baseline? I'd guess that 4.7.x stuff might not be included yet?

Side note: has there been any discussion yet with the conda peeps about upstreaming this? Or do you first want to prove more exhaustively that it works? I really like the idea, I'm just a bit wary of further and further splintering of the build tool ecosystem.

**Comment by wolfv** [comment]
hi @h-vetinari 

indeed, we're working from the current released 4.6.x version. We support most of the basic command, notable exception is update-all right now.

A lot of the commands are forwarded to native conda (list, info, ...).
The ones we handle are `install`, `update`, `remove`, `create`, `env create`.

**Comment by rfox12** [comment]
Related to "conda parity"... I would just like to add 2 cents and say: I've found that mamba gives me a *more optimal* environment solution in many cases!  Don't try to align to conda resolution rules just for the sake of alignment (or if you want the users to have conda resolution parity maybe add a config flag to for mamba to run in _conda mode_ and _pure mode_?)

**Comment by adriendelsalle** [comment]
Same as https://github.com/mamba-org/mamba/issues/738
