### ISSUE TITLE
Move to vcpkgs "subprocess" implementation

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#426]
We're currently using a subprocess implementation that isn't very much battle-tested on Windows.

VCPKG has a really nice implementation that I hope we could easily re-use: https://github.com/microsoft/vcpkg/blob/master/toolsrc/include/vcpkg/base/system.process.h

**Comment by wolfv** [comment]
https://github.com/benman64/subprocess/ this looks like another decent alternative

**Comment by traversaro** [comment]
Other related libraries (not sure if they suit all mamba's needs): 
* https://github.com/DaanDeMeyer/reproc
* https://gitlab.com/eidheim/tiny-process-library

If https://github.com/osrf/gazebo/pull/2864 gets merged, I plan to add tiny-process-library to conda-forge .

**Comment by wolfv** [comment]
@traversaro did you start packaging the tiny-process-library already? I am quite interested as well, as I am having some issues with the current implementation on Windows.

**Comment by traversaro** [comment]
I was waiting for upstream to merge https://gitlab.com/eidheim/tiny-process-library/-/merge_requests/38 , but that is not strictly necessary, we could start packaging it in any case or keeping that patch local for now.

**Comment by wolfv** [comment]
@traversaro I checked tiny-process-library and saw that it requires MSYS2. 

For now I am trying reproc++ in #569 and it's already better working vs what I had before :)
I think I am going to package reproc for conda-forge -- thanks for the pointers!

**Comment by traversaro** [comment]
> @traversaro I checked tiny-process-library and saw that it requires MSYS2.

To clarify, MSYS2 support in `tiny-process-library` is optional, and it works fine even without MSYS2. In any case, that's not a big problem, both `reproc++` and `tiny-process-library` are small libraries that do one job in a great way, and it will be great to have both of them in conda-forge .

**Comment by wolfv** [comment]
yeah I am trying to get reproc on conda-forge :) https://github.com/conda-forge/staged-recipes/pull/13113

**Comment by wolfv** [comment]
we've completed the transition to reproc for now. Hopefully it works well enough and I never have to touch this again :sweat_smile:
