### ISSUE TITLE
Decompression severe bottleneck in some cases

### ISSUE THREAD

**Issue by NegatioN** [mamba-org/mamba#440]
In reference to #138 , I would like to mention that compression seems to be a bottleneck if there's several packages that are large and need decompression in the same statement. The exact same packages if executed in separate statements seem to be installed quicker for example.

example slow install took `2m9s`: 
```
mamba create -y -n test -c anaconda -c defaults -c conda-forge python=3.6 numpy==1.18.* pip==20.0.2 nomkl==3.0 pandas==1.0.* pillow==6.2.0 python-confluent-kafka==1.1.0 scipy==1.3.1 ipykernel==5.1.2 pylint==2.4.3 psutil==5.6.7 google-cloud-sdk==274.0.1 tqdm==4.47.* prometheus_client==0.3.0 fire==0.3.* cudatoolkit==9.0 cudnn==7.6 gensim==3.8.0
```

(ran `conda remove -n test --all -y && conda clean -afy && rm -rf ~/.cache/` in between to hopefully get same conditions)

Example quicker install took `58.8s+12.5s`: 
```
mamba create -y -n test -c anaconda -c defaults -c conda-forge python=3.6 numpy==1.18.* pip==20.0.2 nomkl==3.0 pandas==1.0.* pillow==6.2.0 python-confluent-kafka==1.1.0 scipy==1.3.1 ipykernel==5.1.2 pylint==2.4.3 psutil==5.6.7 google-cloud-sdk==274.0.1 tqdm==4.47.* prometheus_client==0.3.0 fire==0.3.* && mamba install -y -n test cudatoolkit==9.0 gensim==3.8.0 cudnn==7.6
```

If there's anything that can be done, I'm sure loads of deployments could benefit from this. I don't know if this is entirely due to the decompression stage, but it seems like it gets stuck there a lot

Also, this is running on: `mamba==0.4.3 minconda==4.8.2`

**Comment by wolfv** [comment]
Thanks for the bug report! This is an interesting measurement. 
The main problem is that it seems difficult to make libarchive work in multiple threads. One of the underlying reasons is that when unpacking an archive, we `cd $EXTRACTION_DIR` which changes the current working directory to then extract the files. The current workdir is process-wide though ... 

So one solution that I tried in the beginning is to prepend the prefix in front of the filename to be extracted:

extract/me.py -> $PREFIX/extract/me.py

But even then there were issues when using libarchive in multithreaded mode.

One potential solution would be to just use sub-processes and call an independent executable, or more mamba instances with different command line options to spawn processes that can extract independent from each other.

**Comment by adriendelsalle** [comment]
@NegatioN we implemented parallel extraction in https://github.com/mamba-org/mamba/pull/1195
It's not yet released but should be soon-ish!

I'm tagging this issue as `outdated` and we will close it at next release.
It would be great if you could post updated benchmarks then :)

**Comment by NegatioN** [comment]
@adriendelsalle I tested the above case on a (slightly) different box than previously, but seeing times of `real    1m28.438s`, which is about 18s slower than the "best case" of the report, and waaay quicker than the worst case previous naive install. :+1: 

We're also getting 25-30% quicker builds across the board by bumping from a slightly older version, to the newest release at least :slightly_smiling_face: Threaded decompression surely must have been a big part of that :+1: Thanks!

**Comment by wolfv** [comment]
Awesome!

**Comment by loodvn** [comment]
Thanks for an awesome library! 

Extraction has still been a bottleneck for me recently on mamba since installing it yesterday. 
I'm running on a Linux CentOS cluster with 8 cores, tried e.g. pytorch and later ipywidgets and thought that extracting would be really fast (either multithreaded for each file or multiple files in parallel).

Is there some way to verify that multithreaded extraction is happening or to enforce the number of threads when running the command?

**Comment by wolfv** [comment]
@loodvn if you run `htop` you should see all cores in use (if your internet is fast enough).
