### ISSUE TITLE
libc++abi.dylib error with mamba

### ISSUE THREAD

**Issue by ericmjl** [mamba-org/mamba#448]
Hi everybody!

I get the following error with `mamba` 0.4.4 on macOS Mojave (10.14.6 (18G6020)).

```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: pybind11_object_dealloc(): Tried to deallocate unregistered instance!
[1]    34039 abort      mamba env create -f environment.yml
```

I was wondering, is this related to some C++ incompatibilities? If so, what version of c++ "things" is mamba looking out for?  (Apologies in advance for the ambiguity, I'm still learning a ton about C++ stuff.) No pressure here, I'll just fall back on `conda` for the time being. 

~~Right now, I'm just seeing if a downgrade of `mamba` to 0.4.3 helps.~~ Update: downgrading to 0.4.3 gives me the same error.

**Comment by wolfv** [comment]
@ericmjl I haven't seen an error report like this in a long time so I am assuming that the recent builds of mamba work fine.
