### ISSUE TITLE
remove thirdparty headers from public headers

### ISSUE THREAD

**Issue by JohanMabille** [mamba-org/mamba#450]
These headers should not be part of the public API.

This will allows to use the set_property(PUBLIC_HEADERS) / intall(target, PUBLIC_HEADERS DESTINATION) feature of cmake which does not preserve the directory structure.

**Comment by wolfv** [comment]
But we need to have the correct types to assign to context, and context takes fs::path types. And we're currently using the filesystem polyfill for that.

**Comment by wolfv** [comment]
We could change this so that we have a setter function for the relevant options and make the setter function take a std string

**Comment by wolfv** [comment]
I think there is only `winreg` left in our vendored dependencies, and we should be able to make a package for that.
