### ISSUE TITLE
CMakeTarget names

### ISSUE THREAD

**Issue by JohanMabille** [mamba-org/mamba#452]
some of the targets name should be improved to avoid confusion:
mamba_api -> mamba_extension
mamba -> mamba_lib

**Comment by SylvainCorlay** [comment]
> mamba_api -> mamba_extension
> mamba -> mamba_lib

- Maybe not rename `mamba`? (or call it `libmamba` directly like the produced library).
- I think that `mamba_api` should rather be called `python_mamba`. After all, we will have R bindings as well.

**Comment by JohanMabille** [comment]
`mamba` makes me think it's the target for the executable. `libmamba` is a good name. And I agree for the second name too.

**Comment by wolfv** [comment]
I think I already renamed them in the open PR

**Comment by adriendelsalle** [comment]
We renamed the targets in https://github.com/mamba-org/mamba/pull/1219:
- `mamba` -> `libmamba`
- `mamba_api` -> `libmambapy`
