### ISSUE TITLE
Computer go brrrrrrrrrrrrrrrr

### ISSUE THREAD

**Issue by gilescope** [mamba-org/mamba#463]
So I tried Mamba and it was no worse than conda at installing a conda package.

But when doing mamba install, I looked at why my core* was maxed out, it was because it was running python not c++.

You're doing everything well, please keep going so we can have less slow python and more c++.

(* we spread our compute real thin)

**Comment by wolfv** [comment]
Hi @gilescope 

indeed, mamba still uses Python, but it wraps a C++ core with `pybind11`. We are also hard at work on a pure-C++ package called `micromamba` that doesn't use Python at all :+1:

**Comment by gilescope** [comment]
Excellent news, good luck on your quest! Happy to test out once you've got something that hangs together. (I'm afraid I'm a rust dev not a c++ dev so can't really lend too much of a hand in the coding itself.)

**Comment by gilescope** [comment]
Just had a quick try of that on linux and seemed twice the speed of conda for a simple package so a great start! Keep up the good work on micromamba.
