### ISSUE TITLE
After switching to mamba and installed r-ggpubr, R could not be started: on mac os 10.14.6

### ISSUE THREAD

**Issue by ipstone** [mamba-org/mamba#474]
The error msg is  `dyld: Library not loaded: @rpath/libncurses.6.dylib`

Recently I have some similar issue (broken library) on cent OS for my R packages after using mamba . As this keeps happening I am wondering whether it's an issue with mamba, or it might be an issue with conda-forge - it seems mamba tends to find package from the forge - might there be some packages issues on the forget to cause this instead?

Currently I am trying to use `conda update -c rdonnellyr -c main --all` to fix this issue - R can be started now, but upgraded to 4.0 (which is ok).

I am just wondering what might be the cause of these, it seems conda and mamba tend to find different solutions at times. Just want to find out a way to make my setup more stable.

Thanks

**Comment by ipstone** [comment]
Just adding one note, this issue might be related to : https://github.com/ContinuumIO/anaconda-issues/issues/11184

**Comment by wolfv** [comment]
Hi @ipstone can you give me some additional information?

I am wondering: what R packages do you have, which specific package requires ncurses and what version of R are you using (or do you want to use?)
Also where are you getting these R packages from? Are you mixing conda-forge and other channels?

This _may_ be a problem with mamba, but I think it is more a problem with bad repodata as some package requires the wrong ncurses library. But I can't tell which one and from which channel it might come.

**Comment by wolfv** [comment]
This was probably either a channel-mixing problem or metadata problem with conda-forge.
