### ISSUE TITLE
Listen for keyboard interrupt to exit at prompt

### ISSUE THREAD

**Issue by bdice** [mamba-org/mamba#482]
Hi, huge fan of mamba. ❤️ 🐍 I noticed that I can't kill `mamba` with Ctrl+C when it arrives at a prompt:

```
$ mamba install package
...
Confirm changes: [Y/n]
```

I expected Ctrl+C to cancel/stop the program but Ctrl+C does nothing until I respond to the prompt with `<enter>`. This is a small issue, but it has tripped me up and made me think my terminal isn't responding several times. It would be a nice UX fix.

```
Confirm changes: [Y/n] ^C <enter>
(exits)
```

I verified that `conda` can be killed with Ctrl+C at the corresponding install-confirm prompt:

```
Proceed ([y]/n)? ^C
CondaSystemExit:
Operation aborted.  Exiting.
(exits)
```

Version: mamba 0.4.1 / conda 4.8.3.
Platform: Ubuntu 20.04, via WSL2 (Windows Subsystem for Linux).

**Comment by wolfv** [comment]
Thanks @bdice for the issue. We've been looking into this, but it's not _that_ simple since we need to enter "raw mode" in the terminal... @martinRenou did some initial work in #540 which would make this available.
