### ISSUE TITLE
mamba update doesn't work as expected

### ISSUE THREAD

**Issue by SilasK** [mamba-org/mamba#487]
I'm working on OSX mainly. 
conda 4.7.12

If I run `mamba update <package>` I get `# All requested packages already installed.``

but with conda I can update them.

**Comment by wolfv** [comment]
Hi @SilasK 

This is a very bad bug report. I am going to close it, but I am happy to re-open it once you provide me with more details: e.g. what packages are not getting updated?

**Comment by SilasK** [comment]
@wolfv Sorry. I encountered it multiple times for bioconda packages therefore I thought it would be a general problem. 

To start with 

`bbmap                                    38.79-h01d97ff_0 --> 38.86-hf29c6f4_0``

works with conda but not with bioconda.

**Comment by wolfv** [comment]
and you have bioconda properly in your channels?

**Comment by wolfv** [comment]
also it seems like your version of conda is quite old, and therefore I also believe your version of mamba is quite old. possible?

This is what I have:
```
mamba 0.5.1
conda 4.8.4
```

**Comment by SilasK** [comment]
yes, my version was quite old. sorry.
