### ISSUE TITLE
mamba doesn't like Artifactory URLs

### ISSUE THREAD

**Issue by ijstokes** [mamba-org/mamba#496]
Tried to install `dask` and `pandas` using `mamba` with my existing `.condarc`, which includes an HTTPS URL channel entry for a private Artifactory repository.  The Artifactory repo URL, with URL-embedded username and access token, caused mamba to bork.  Trace below.

```
mamba install -c conda-forge dask numpy pandas bokeh

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.5.1) supported by @QuantStack

        GitHub:  https://github.com/TheSnakePit/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

pkgs/main/noarch         [====================] (00m:00s) Done
pkgs/free/osx-64         [====================] (00m:00s) Done
pkgs/pro/noarch          [====================] (00m:00s) Done
pkgs/msys2/osx-64        [====================] (00m:00s) Done
pkgs/free/noarch         [====================] (00m:00s) Done
pkgs/pro/osx-64          [====================] (00m:00s) Done
pkgs/main/osx-64         [====================] (00m:01s) Done
conda-forge/noarch       [====================] (00m:01s) Done
pkgs/r/noarch            [====================] (00m:00s) Done
pkgs/msys2/noarch        [====================] (00m:00s) Done
pkgs/r/osx-64            [====================] (00m:00s) Done
conda-forge/osx-64       [====================] (00m:03s) Done
artifactory/api/conda/ga [====================] (00m:06s) 0 Failed
artifactory/api/conda/ga [>                   ] (00m:06s) URL using bad/illegal format or missing URL

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/stokesreesian/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/stokesreesian/anaconda3/lib/python3.7/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/Users/stokesreesian/anaconda3/lib/python3.7/site-packages/mamba/mamba.py", line 935, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/stokesreesian/anaconda3/lib/python3.7/site-packages/mamba/mamba.py", line 894, in _wrapped_main
        result = do_call(args, p)
      File "/Users/stokesreesian/anaconda3/lib/python3.7/site-packages/mamba/mamba.py", line 778, in do_call
        exit_code = install(args, parser, "install")
      File "/Users/stokesreesian/anaconda3/lib/python3.7/site-packages/mamba/mamba.py", line 418, in install
        prefix=prefix,
      File "/Users/stokesreesian/anaconda3/lib/python3.7/site-packages/mamba/utils.py", line 73, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: Download error (3) URL using bad/illegal format or missing URL [https://stokesrees.ian@example.com:LONG-TOKEN-STRINGk@artifactory.example.com/artifactory/api/conda/project-conda/noarch/repodata.json]

`$ /Users/stokesreesian/anaconda3/bin/mamba install -c conda-forge dask numpy pandas bokeh`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/stokesreesian/anaconda3/bin/conda
             CONDA_PREFIX=/Users/stokesreesian/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/stokesreesian/anaconda3/bin/python
               CONDA_ROOT=/Users/stokesreesian/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/stokesreesian/anaconda3/bin:/Users/stokesreesian/anaconda3/cond
                          abin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware
                          Fusion.app/Contents/Public:/Library/Apple/usr/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/stokesreesian/anaconda3
            shell level : 1
       user config file : /Users/stokesreesian/.condarc
 populated config files : /Users/stokesreesian/.condarc
          conda version : 4.8.4
    conda-build version : 3.19.2
         python version : 3.7.3.final.0
       virtual packages : __osx=10.15.6
       base environment : /Users/stokesreesian/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://stokesrees.ian@example.com:LONG-TOKEN-STRINGk@artifactory.example.com/artifactory/api/conda/project-conda/osx-64
						  https://stokesrees.ian@example.com:LONG-TOKEN-STRINGk@artifactory.example.com/artifactory/api/conda/project-conda/noarch
ssl_verify: true
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/osx-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : /Users/stokesreesian/anaconda3/pkgs
                          /Users/stokesreesian/.conda/pkgs
       envs directories : /Users/stokesreesian/anaconda3/envs
                          /Users/stokesreesian/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.7.3 Darwin/19.6.0 OSX/10.15.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by wolfv** [comment]
Hi @ijstokes any chance that you could try this again with the latest mamba? We had some recent improvements there.

Furthermore, I am not sure I understand the artifactory authentication format. Mamba is supposed to support "Basic HTTP Authentication" that follows the scheme: `http://user:password@someserver.com`

But the URL you posted looks like:

`https://stokesrees.ian@example.com:LONG-TOKEN-STRINGk@artifactory.example.com/artifactory` so there is an extra `@` in there if I understand correctly? I am not a artifactory user so I'd be happy to accept a PR to implement this.

We also have a server implementation in the mamba tests now that could be modified to additionally accept an authentication scheme like this.

**Comment by xhochy** [comment]
I'm using `mamba=0.7.14` and Artifactiory successfully together, this rather looks like the token was placed at the wrong point in the URL.

**Comment by wolfv** [comment]
Let me know if you still have issues @ijstokes

**Comment by VincentCroquette** [comment]
Hi @wolfv 

I work on a similar environment as @ijstokes based on Artifactory and have the same problem on Windows.
The channels in .condarc do not require any authentication in my case but mamba reports the below error:

`Executing the query xtensor

api/conda/continuum-cond [====================] (00m:00s) 403 Failed
api/conda/continuum-cond [====================] (00m:00s) 403 Failed
api/conda/forge-conda-re [<=>                 ] (00m:00s) 146  B / ?? (155.00  B/s)

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\me\AppData\Local\Miniconda\envs\mamba\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\me\AppData\Local\Miniconda\envs\mamba\lib\site-packages\mamba\mamba.py", line 882, in exception_converter
        raise e
      File "C:\Users\me\AppData\Local\Miniconda\envs\mamba\lib\site-packages\mamba\mamba.py", line 876, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "C:\Users\me\AppData\Local\Miniconda\envs\mamba\lib\site-packages\mamba\mamba.py", line 835, in _wrapped_main
        result = do_call(args, p)
      File "C:\Users\me\AppData\Local\Miniconda\envs\mamba\lib\site-packages\mamba\mamba.py", line 724, in do_call
        exit_code = repoquery(args, parser)
      File "C:\Users\me\AppData\Local\Miniconda\envs\mamba\lib\site-packages\mamba\mamba.py", line 694, in repoquery
        pool = repoquery_api.create_pool(channels, platform, use_installed)
      File "C:\Users\me\AppData\Local\Miniconda\envs\mamba\lib\site-packages\mamba\repoquery.py", line 55, in create_pool
        use_local=use_local,
      File "C:\Users\me\AppData\Local\Miniconda\envs\mamba\lib\site-packages\mamba\utils.py", line 99, in load_channels
        use_cache=use_cache,
      File "C:\Users\me\AppData\Local\Miniconda\envs\mamba\lib\site-packages\mamba\utils.py", line 74, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: Multi-download failed.
`

**Comment by wolfv** [comment]
But you're getting a 403, that means authentication of some sort is missing? How does authentication work there?

**Comment by VincentCroquette** [comment]
@wolfv Sorry, you're right, the channels require GitHub enterprise authentication. It does not seem to be an issue for conda though.

**Comment by wolfv** [comment]
Can you open a new issue and explain how GitHub enterprise authentication works in this context?

**Comment by VincentCroquette** [comment]
Sorry, I think it's the proxy authentication that's failing actually.
The proxy is configured to use NTLM authentication, and the proxy addresses are present in .condarc without the credentials which works fine with conda but apparently not with mamba.

**Comment by xhochy** [comment]
For `mamba` you need to set the `http_proxy` and `https_proxy` environment variables. The ones in the `.condarc` are not yet used.

**Comment by wolfv** [comment]
@VincentCroquette I'd be happy if you could open a separate issue for this!

**Comment by VincentCroquette** [comment]
@xhochy Thanks, do you know if these options will be supported at some point?

**Comment by wolfv** [comment]
There is a PR that contains a prototype implementation to set the values for the proxy config to libcurl.

**Comment by wulmer** [comment]
Just in case someone stumbles across this thread: there is another issue on the same (or very similar) issue: https://github.com/mamba-org/mamba/issues/1132 which already has two PRs mentioned: https://github.com/mamba-org/mamba/pull/1131 and https://github.com/mamba-org/mamba/pull/1141.
