### ISSUE TITLE
Support printing shell hooks with micromamba

### ISSUE THREAD

**Issue by maresb** [mamba-org/mamba#498]
Hi, I'd like to be able to run something similar to
```bash
eval "$(conda shell.bash hook)"
```
with `micromamba` in order to run the shell init commands without having to modify `.bashrc`. (This is especially useful when running from a non-interactive shell, e.g. in a Dockerfile build.)

Currently I am using the following ugly workaround, which I'd like to replace:
```bash
./bin/micromamba shell init -s bash -p ~/conda

# Extract init for micromamba to a separate file
sed -i -e '/^# >>> mamba initialize >>>/,/^# <<< mamba initialize <<</{w /dev/stdout' -e 'd}' .bashrc > /tmp/mambainit.sh

# Configure current shell
source /tmp/mambainit.sh
```

Since micromamba runs outside of a preexisting environment, it doesn't make sense to implement a `micromamba shell.bash hook` command. (Note that the output of `conda shell.bash hook` ends with `conda activate base`.) Instead we should probably modify the existing `micromamba shell` command.

One actual suggestion is:

```bash
micromamba shell hook -s bash -p ~/conda
```
where the `hook` subcommand prints the `>>> mamba initialize >>>` snippet to stdout, after creating the prefix in case it doesn't already exist.

**Comment by wolfv** [comment]
I totally believe this would be possible and not hard to achieve. Do you want to look into this?

**Comment by maresb** [comment]
I would really like to, but unfortunately it would take me an inordinate amount of time since I'm specialized in Python rather than C++.

**Comment by maresb** [comment]
I decided to take a quick look today. I followed the instructions, but ran into a few problems:
1. I needed to change to the `src` directory before running the `cmake` command.
2. I needed to run `make` after running the `cmake` command.
3. No executable was created. I added `-DBUILD_EXE=ON` to the `cmake` command.
4. `fatal error: yaml-cpp/yaml.h: No such file or directory` so I did `mamba install yaml-cpp`
5. Now linking fails, with the first error being:
```
/home/mares/conda/envs/mamba/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: CMakeFiles/micromamba.dir/main.cpp.o: in function `YAML::TypedBadConversion<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~TypedBadConversion()':
main.cpp:(.text._ZN4YAML18TypedBadConversionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEED2Ev[_ZN4YAML18TypedBadConversionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEED5Ev]+0x10): undefined reference to `YAML::BadConversion::~BadConversion()'
```
I'm getting nowhere fast. Any chance of getting some "Building Micromamba for Dummies" instructions?

**Comment by wolfv** [comment]
Hi @maresb 

sorry for getting back to you only so late. The best instructions are probably in the `.github/main.yml` file, but it's still a little cumbersome. I hope to be able to improve & simplify our CMake today.

In fact, I am working on your requested feature in #569. With that PR, executing `conda shell hook -s bash` will print a shell hook even without prior shell init.

**Comment by maresb** [comment]
Hi @wolfv, that's very exciting! In my scripts I'm still parsing the `.bashrc` for the hook, and would very much like to clean that up. Thanks so much for your work!

**Comment by wolfv** [comment]
yep, I think after my PR is done, the usage of micromamba in CI's will be even cleaner.

**Comment by wolfv** [comment]
Okay, with the latest changes it's possible to do 

`eval "$(./micromamba shell hook -s posix)"`

I am documenting this right now.


Micromamba also assumes a default "root prefix" in `~/micromamba` now which shoudl further help in the CI use-case.

**Comment by wolfv** [comment]
similarly on PowerShell one can do `micromamba shell hook -s powershell | Out-String | Invoke-Expression`
