### ISSUE TITLE
Suport multiple --file for multiple requirement text based files like in conda

### ISSUE THREAD

**Issue by ocefpaf** [mamba-org/mamba#509]
conda supports multiple --file args so people can mimic pip's behavior and have requirements.txt and requirements-dev.txt files separate. mamba and micromamba fails at the moment with the message:

```
--file: At Most 1 required but received 2
Run with --help for more information
```

**Comment by wolfv** [comment]
done in 0.5.3

**Comment by wolfv** [comment]
-- done for micromamba. I just saw you mentioning that this is also an issue in mamba.

**Comment by ocefpaf** [comment]
@wolfv we should close this one, right?

**Comment by wolfv** [comment]
Yeah i need to check if we do the right stuff in mamba itself. At least this works in micromamba now :)

**Comment by wolfv** [comment]
Works as well in mamba.
