### ISSUE TITLE
Problem: nothing provides requested maestro 1.2.1**

### ISSUE THREAD

**Issue by ChangliangWang** [mamba-org/mamba#511]
Dear Wolfv,

When I install MAESTRO using mamba (mamba create -n MAESTRO maestro=1.2.1), I encountered the error 'Problem: nothing provides requested maestro 1.2.1**'. Do you know how to fix it? Thanks very much for your help.

Best regards,
Changliang.

**Comment by wolfv** [comment]
you need to use the right channel.
