### ISSUE TITLE
Repodata file truncated, preventing install

### ISSUE THREAD

**Issue by rgerkin** [mamba-org/mamba#512]
From a fresh install of miniconda 3.8 and mamba 0.5.1 in WSL2, Windows 10 2004, no matter what I try to install with mamba (e.g. `mamba install numpy`) I get this strange error:
```
rgerkin@COMPUTER:~$ mamba install numpy
... Mamba logo, etc. excised...
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
oxfordcontrol/noarch     [====================] (00m:00s) No change
oxfordcontrol/linux-64   [====================] (00m:00s) No change

Looking for: ['numpy']


# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/rgerkin/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/rgerkin/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/home/rgerkin/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 935, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/rgerkin/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 894, in _wrapped_main
        result = do_call(args, p)
      File "/home/rgerkin/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 778, in do_call
        exit_code = install(args, parser, "install")
      File "/home/rgerkin/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 552, in install
        repo = subdir.create_repo(pool)
    RuntimeError: Could not read JSON repodata file (/home/rgerkin/miniconda3/pkgs/cache/e7b11566.json) parse error line 1
```

If I look at that .json file, it is truncated:
```
rgerkin@COMPUTERL:~$ more /home/rgerkin/miniconda3/pkgs/cache/e7b11566.json
{"_cache_control":"","_etag":"","_mod":"Sat, 31 Aug 2019 21:43:24 GMT","_url":"https://conda.anaconda.org/oxfordcontrol/
linux-64/repodata.json",
rgerkin@COMPUTER:~$
```
I have no idea why mamba (or conda, or whatever is trying to create this file) is leaving it truncated.  If I delete the truncated JSON file, it just gets created again in the process of trying to install a package with `mamba`, resulting in the same error.  I don't know if whatever is trying to create the JSON file is simply failing completely, or is not finishing before mamba tries to read it, or what.  This occurs in an Ubuntu shell in Windows terminal, or WSL2 Ubuntu's own terminal.

**Comment by wolfv** [comment]
Hi @rgerkin thanks for your bug report!

I have just tried on WSL2 on my Windows partition and it seems to work fine. Using the latest Miniconda 3.8 installer (on Ubuntu 20.04 in WSL2) I installed mamba 0.5.3.

Did you install mamba in the root prefix (base)? It _has to be installed in the base environment_.

From there I was able to create a new environment with e.g. xtensor inside.

![image](https://user-images.githubusercontent.com/885054/94942313-680b1000-04d6-11eb-80cd-9453cedbb65e.png)

**Comment by lambiase** [comment]
I had exactly the same issue on Linux, but in my case it was caused by `/tmp` being full.
`conda` failed as well, but in a more helpful way:

```
Downloading and Extracting Packages
pyopenssl-19.1.0     | 48 KB     | ######################################################################################################################################################################### | 100% Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Rolling back transaction: done

[Errno 28] No space left on device
()
```

**Comment by wolfv** [comment]
Thanks @rgerkin there was an issue with our error handling in file streams. We now do more error checking and handling so that thsi issues should not occur anymore.

**Comment by xiachenrui** [comment]
> 我在 Linux 上遇到了完全相同的问题，但在我的情况下，它是由`/tmp`已满引起的。 `conda`也失败了，但以一种更有帮助的方式：
> 
> ```
> Downloading and Extracting Packages
> pyopenssl-19.1.0     | 48 KB     | ######################################################################################################################################################################### | 100% Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> Rolling back transaction: done
> 
> [Errno 28] No space left on device
> ()
> ```

Thanks a lot, I meet the same problem and it disappeared when clean the `/tmp`
