### ISSUE TITLE
mamba does not seem to respect configured source priorities?

### ISSUE THREAD

**Issue by michaelaye** [mamba-org/mamba#513]
I have set environment specific conda-forge priority:

```bash

(py37) C:\Users\kmich>conda config --show-sources
==> C:\Users\kmich\anaconda3\envs\py37\.condarc <==
pinned_packages:
  - conda-forge::numpy
  - conda-forge::gdal
channels:
  - conda-forge
  - defaults

==> C:\Users\kmich\.condarc <==
ssl_verify: True
channels:
  - defaults
```

but doing an `update --all` without providing the channel on the command-line, `mamba` wants to replace all my `conda-forge` packages with same versions from the defaults channel:

```bash
  wheel                    0.35.1  py_0               pkgs/main/noarch       Cached
  widgetsnbextension        3.5.1  py37hc8dfbb8_1     installed
  widgetsnbextension        3.5.1  py37_0             pkgs/main/win-64       868 KB
  wincertstore                0.2  py37_1003          installed
  wincertstore                0.2  py37_0             pkgs/main/win-64       Cached
  xz                        5.2.5  h62dcd97_1         installed
  xz                        5.2.5  h62dcd97_0         pkgs/main/win-64       Cached
  yaml                      0.2.5  he774522_0         installed
  yaml                      0.2.5  he774522_0         pkgs/main/win-64       Cached
  zeromq                    4.3.2  ha925a31_3         installed
  zeromq                    4.3.2  ha925a31_3         pkgs/main/win-64       Cached
  zlib                     1.2.11  h62dcd97_1009      installed
  zlib                     1.2.11  h62dcd97_4         pkgs/main/win-64       Cached
  zstd                      1.4.5  h1f3a1b7_2         installed
  zstd                      1.4.5  ha9fde0e_0         pkgs/main/win-64       Cached
```

```
(py37) C:\Users\kmich>mamba --version
mamba 0.5.1
conda 4.8.5
```

**Comment by michaelaye** [comment]
still the case with 

$ mamba --version                                                                                                                                                   (py37) 
mamba 0.6.4
conda 4.9.0

on Linux.

**Comment by wolfv** [comment]
Are you using strict channel priority (strongly recommended for conda-forge)?

**Comment by michaelaye** [comment]
why does that matter if strict feature equivalency is a premise of `mamba`? Unless it's not, but that's how I would interpret "drop-in replacement". Currently `mamba` is not a drop in replacement as it behaves very different, in an environment-breaking fashion. The alternative of course is to restrict the scope of `mamba` to a certain feature subset with certain required configurations. But then these would need to be called out in the README and docs, I'd say. I looked but couldn't find any mention of `channel_priority` in the README.

**Comment by wolfv** [comment]
The conda-forge.org homepage states quite clearly that one should use strict-priority :)

But I think your channel priorities are mixed up regardless. I haven't really tested the stacking of multiple condarc's and have hoped that conda would handle that nicely for us.
You can inspect the assigned priorities by adding `-v` to the mamba command.

Also this is where the channels are loaded. Would be interesting to see which order you get them in:
https://github.com/mamba-org/mamba/blob/master/mamba/utils.py#L92

Looking forward to hear from you!

**Comment by michaelaye** [comment]
I'm sorry, can you provide a full command I'm supposed to call, so far I'm getting this (apparently, by default my env channel setup is ignored?):

```python
In [1]: from mamba.utils import load_channels

In [2]: load_channels()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-fdc8437f3e74> in <module>
----> 1 load_channels()

TypeError: load_channels() missing 3 required positional arguments: 'pool', 'channels', and 'repos'

In [3]: from mamba.utils import get_index

In [4]: get_index()
pkgs/r/noarch            [====================] (00m:00s) Done
pkgs/main/noarch         [====================] (00m:00s) Done
pkgs/r/linux-64          [====================] (00m:00s) Done
pkgs/main/linux-64       [====================] (00m:01s) Done
Out[4]: 
[(<mamba.mamba_api.SubdirData at 0x7fb418398bf0>,
  Channel("pkgs/main/linux-64")),
 (<mamba.mamba_api.SubdirData at 0x7fb41b6c4bf0>, Channel("pkgs/main/noarch")),
 (<mamba.mamba_api.SubdirData at 0x7fb418143370>, Channel("pkgs/r/linux-64")),
 (<mamba.mamba_api.SubdirData at 0x7fb418143bb0>, Channel("pkgs/r/noarch"))]

```

I would be surprised if my channel priorities are "mixed up", because I am using a very straight forward setup that, IIUC, is fully supported (apart from the recent addition of channel_priority, my work-around for this always has been channel-binding of specific packages that could "accidentally" pick up packages from `default`, like numpy or gdal.)
Here's my standard miniconda setup from scratch:

* install miniconda
* leave base at `defaults` and untouched otherwise
* create py37 (e.g.) environment
* add environment specific channel using `conda config --env --add channels conda-forge`

The environment specific channel priority is really a heaven's sent feature of conda and one of its main attractions as otherwise it would nearly be impossible to have clearly independent conda environments. Note I add zero channel dependencies to the base condarc for that reason and I bet there are many people out there doing the same, at least the students going through my conda school ;) https://www.youtube.com/watch?v=U3UZBeTDYmw (i'll need to update for the channel_priority flag).
That's it

**Comment by wolfv** [comment]
Thanks, yeah I can check out this use case!

This is how to get verbose debugging output:

```
mamba create -n abcdef xtensor --dry-run -v
```

This prints a lot. If you pipe it through grep to get only the Channel stuff:

```
mamba create -n abcdef xtensor --dry-run -v | grep Channel
```

High prio => Higher number
First number is priority for strict priority, and second one is "subpriority" that should decide in draws.


Channel: https://conda.anaconda.org/robostack/linux-64, prio: 0 : 8
Channel: https://conda.anaconda.org/robostack/noarch, prio: 0 : 7
Channel: https://conda.anaconda.org/conda-forge/linux-64, prio: 0 : 6
Channel: https://conda.anaconda.org/conda-forge/noarch, prio: 0 : 5
Channel: https://repo.anaconda.com/pkgs/main/linux-64, prio: 0 : 4
Channel: https://repo.anaconda.com/pkgs/main/noarch, prio: 0 : 3
Channel: https://repo.anaconda.com/pkgs/r/linux-64, prio: 0 : 2
Channel: https://repo.anaconda.com/pkgs/r/noarch, prio: 0 : 1

**Comment by michaelaye** [comment]
I'm getting this:

```bash
Channel: https://conda.anaconda.org/conda-forge/linux-64, prio: 0 : 6
Channel: https://conda.anaconda.org/conda-forge/noarch, prio: 0 : 5
Channel: https://repo.anaconda.com/pkgs/main/linux-64, prio: 0 : 4
Channel: https://repo.anaconda.com/pkgs/main/noarch, prio: 0 : 3
Channel: https://repo.anaconda.com/pkgs/r/linux-64, prio: 0 : 2
Channel: https://repo.anaconda.com/pkgs/r/noarch, prio: 0 : 1

``` 
with this setting:
```bash
➤ conda config --show-sources                                                    (py37) 
==> /home/maye/.condarc <==
channels:
  - conda-forge
  - defaults
report_errors: True

==> /home/maye/miniconda3/envs/py37/.condarc <==
channels:
  - conda-forge
  - defaults
```
Note, I added `conda-forge` to the main condarc for debugging purposes.
This seems wrong? Conda-forge and and pkgs/main should not have the same priority like this? Unless you are really not supporting mamba to work without setting `channel_priority`, because it looks correct in that case:

```
Channel: https://conda.anaconda.org/conda-forge/linux-64, prio: 2 : 1
Channel: https://conda.anaconda.org/conda-forge/noarch, prio: 2 : 0
Channel: https://repo.anaconda.com/pkgs/main/linux-64, prio: 1 : 1
Channel: https://repo.anaconda.com/pkgs/main/noarch, prio: 1 : 0
Channel: https://repo.anaconda.com/pkgs/r/linux-64, prio: 1 : 1
Channel: https://repo.anaconda.com/pkgs/r/noarch, prio: 1 : 0

```

**Comment by michaelaye** [comment]
But yeah, `channel_priority` does not help with `mamba` completely ignoring the environment condarc:

```bash
Channel: https://repo.anaconda.com/pkgs/main/linux-64, prio: 2 : 1
Channel: https://repo.anaconda.com/pkgs/main/noarch, prio: 2 : 0
Channel: https://repo.anaconda.com/pkgs/r/linux-64, prio: 2 : 1
Channel: https://repo.anaconda.com/pkgs/r/noarch, prio: 2 : 0
Channel: https://conda.anaconda.org/conda-forge/linux-64, prio: 1 : 1
Channel: https://conda.anaconda.org/conda-forge/noarch, prio: 1 : 0
maye@pop-os:~/.config
➤ conda config --show-sources                                                    (py37) 
==> /home/maye/.condarc <==
channel_priority: strict
channels:
  - defaults
report_errors: True

==> /home/maye/miniconda3/envs/py37/.condarc <==
channels:
  - conda-forge
  - defaults
```

**Comment by michaelaye** [comment]
BTW, you used the term `stacking` before. I'm not sure conda uses that for applying nested condarcs. In any case, it's a loaded term for actually stacking the PATHs of different conda envs, using `conda activate --stack <env_name>`, but most likely you know that. Just wanted to make sure there's no confusion here.

**Comment by wolfv** [comment]
I tested this behavior by adding 3 channels to `~`, `root_prefix` and `conda_prefix`.

Conda puts the channel from root prefix into the lowest priority, then home and then conda_prefix.

It's exactly the same behavior as mamba (because we're using the exact same code, in mamba we're not touching config file loading).

You can find the channel order by calling `conda info` that should list the channels in the proper order.
