### ISSUE TITLE
"--no-banner" doesn't work with "mamba env create"

### ISSUE THREAD

**Issue by MattF-NSIDC** [mamba-org/mamba#514]
Just discovered this project today, pretty sweet!

We attempted to replace a `conda env create` command with mamba, but didn't want the banner. The command:

```
mamba --no-banner env create -f /tmp/environment.yml
```

Returned:
```
usage: conda-env [-h] {create,export,list,remove,update,config} ...
conda-env: error: invalid choice: 'env' (choose from 'create', 'export', 'list', 'remove', 'update', 'config')
```

P.S.: I had to read the source code to find the `--no-banner` option as it wasn't documented in `mamba --help`. It was one of the first things I wanted to change, and it took quite some time to figure it out.

**Comment by martinRenou** [comment]
Instead of `mamba --no-banner env create -f /tmp/environment.yml`, can you try `mamba env create -f /tmp/environment.yml --no-banner`, it should work.
