### ISSUE TITLE
Request for uploading micromamba binary releases as artifacts on each tagged release on GH

### ISSUE THREAD

**Issue by nehaljwani** [mamba-org/mamba#526]
It would be awesome if a release of micromamba is uploaded on the releases page with each tag. Would make it very easy to bootstrap conda (or should I say mamba?) environments.

**Comment by wolfv** [comment]
It's a very good idea. We could go two ways: either set up a seperate CI, or we could periodically check fi a new release is out and fetch the package from conda-forge and add it to the release (maybe with a cron job on github actions).
That way we'd have only one source-of-truth build pipeline (conda-forge).

**Comment by wolfv** [comment]
thx for your PR's on micromamba feedstock by the way, very much appreciated!

**Comment by wolfv** [comment]
Hi @nehaljwani 

we're doing builds now over at boa-forge: https://github.com/mamba-org/boa-forge/releases

**Comment by nehaljwani** [comment]
Thank you @wolfv ! It would be great if you could update the README/docs on this repo to point to that page 🙂

**Comment by wolfv** [comment]
yep, I am waiting a bit more for it to "stabilize" :)
