### ISSUE TITLE
Respect channel-specific specs in environment.yml

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#534]
This was encountered in the repo2docker project: https://github.com/jupyterhub/repo2docker/issues/973

**Comment by martinRenou** [comment]
Working on it!

**Comment by wolfv** [comment]
we have handling for this in the `mamba.py` and that needs to be ported to `mamba_env.py`.

**Comment by martinRenou** [comment]
I see. Thanks for the precision :)

**Comment by michaelaye** [comment]
Is/was this related to #513 ?
