### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by jrwrigh** [mamba-org/mamba#542]
Is there any documentation for this? I see a `.readthedocs.yml` file, but can't find a link to Read-the-Docs site. It'd be nice as a reference to determine what features are not currently implemented in <code>mamba</code> and as documentation for `mamba` exclusive arguments (like the `reposearch` mentioned in the README).

Love the project though. Installing packages is _so_ much easier.

**Comment by wolfv** [comment]
You can find the barebones docs at mamba.readthedocs.io

We can always use more docs. But I am still going to close this for now.
