### ISSUE TITLE
Unable to confirm changes on Windows on 0.6

### ISSUE THREAD

**Issue by olivier-lacroix** [mamba-org/mamba#543]
Hi there,

After upgrading to mamba 0.6, I am unable to progress past the "Confirm changes: [Y/n]" prompt in cmd.exe 

Downgrading to 0.5.3 fixes the issue

**Comment by philip-khor** [comment]
Seeing similar behaviour in Windows Terminal Preview 1.4.2652.0

**Comment by owen-synergy** [comment]
I'm getting this too with Windows 10 cmd prompt

**Comment by owen-synergy** [comment]
Doesn't work for me in the Anaconda Powershell Prompt either

**Comment by wolfv** [comment]
Sorry! Yes, this code changed. We will make a patch release asap!

**Comment by wolfv** [comment]
fixed with #544

**Comment by olivier-lacroix** [comment]
Thanks @wolfv for the quick fix!
