### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by jason-sachs** [mamba-org/mamba#547]
Is there any shred of hope of asking for Python 2.7 support?

I know, Python 2.7 support is EOL as of Jan 1 2020. But I'm stuck in 2.7-land due to legacy concerns, and conda is so darn slow as of around Conda 4.5.0; it can take 5-10 minutes just to give me an answer that I have incompatible packages. I have to go to an earlier conda version (that is less robust? idk why they changed it).

**Comment by jason-sachs** [comment]
(alternatively, can mamba be used from a Python 3 base environment to create/manage Python 2 environments in Anaconda/miniconda?)

**Comment by wolfv** [comment]
@jason-sachs the second question: yes, that's totally possible. You can install python 2.7 packages with mamba from a python 3 base env.

I think there should be old python 2.7 builds of mamba. I don't really think we want to support Python 2.7 any longer for new code, though... sorry about that.

**Comment by jason-sachs** [comment]
OK, I'll try it out in miniconda3. (or if I keep having headaches I'll try micromamba)

**Comment by jason-sachs** [comment]
yay, everything seems to work with Miniconda3-4.7.12.1-Windows-x86_64.exe (the last BSD3 installer for Miniconda3)

Thank you guys so much! I was at my wit's end with conda being unusable because of the slowness/errors.

I'll run a couple of tests to make sure all is ok + I can run in my expected python 2 environment, + then I'll close.

**Comment by jason-sachs** [comment]
ick... spoke too soon, I need to find PySide :/ -- not sure if the problem is mamba or the various repos

**Comment by wolfv** [comment]
did it work out? I saw you on gitter, getting the advice to use the old `free` channel?

**Comment by jason-sachs** [comment]
Yep, works well. I do wish that conda would separate the idea of base/default environment from package-manager environment; I'd like to run python 2.7 in my base/default environment without having to `activate` anything, but use conda/mamba with Python 3 -- actually I don't really care what Python environment it uses as long as it works.
