### ISSUE TITLE
Suggestion: provide a canonical docker image

### ISSUE THREAD

**Issue by akhmerov** [mamba-org/mamba#549]
Taking this over from [twitter](https://twitter.com/wuoulf/status/1319578459673427968).

I would like to propose a "canonical" dockerfile that could be used in CI, analogous to continuumio/miniconda. @wolfv also suggested to build an image from that file and publish it as an action with any new version of microconda.

I'm not yet certain what should go into the said dockerfile, aside of the minimal wget & tar.

**Comment by wolfv** [comment]
We don't even need wget or tar. Just the extracted micromamba binary should be enough (as it comes with libarchive, curl statically linked in).

In the dockerfile we could just `CP micromamba /bin/micromamba` from the host system, for example.

**Comment by adriendelsalle** [comment]
Hi @akhmerov @wolfv !

It could be related to this [similar issue on Quetz](https://github.com/mamba-org/quetz/issues/44#issuecomment-676494489), talking about the way to handle `docker` recipes.

The [draft PR](https://github.com/mamba-org/quetz/pull/60) I started for `Quetz` also questioned about what repo to use for publishing the artefact @SylvainCorlay : 
- do you want to store all your images on a `QuantStack` org, such as [`continuumio`](https://hub.docker.com/u/continuumio) ?
- use [thesnakepit](https://hub.docker.com/u/thesnakepit) or [mambaorg](https://hub.docker.com/u/mambaorg) created today to follow the project renaming ?

**Comment by wolfv** [comment]
there is a mamba-forge docker image in conda-forge now.

**Comment by akhmerov** [comment]
Sounds great! Can you please link the image or the dockerfile? I tried searching for "mamba-forge", but to no avail.

**Comment by wolfv** [comment]
The PR implementing it: https://github.com/conda-forge/docker-images/pull/169

**Comment by wolfv** [comment]
The dockerhub image: https://hub.docker.com/r/condaforge/mambaforge

**Comment by wolfv** [comment]
please provide feedback how it goes! We still need to do something about micromamba.

**Comment by marcindulak** [comment]
It looks like the image is not versioned, only provides the `latest` tag.

**Comment by wolfv** [comment]
you can help in this issue @marcindulak https://github.com/conda-forge/docker-images/issues/43

**Comment by wholtz** [comment]
I recently created a micromamba docker image: [git repo](https://github.com/buildcrew/micromamba_docker) and [images on dockerhub](https://hub.docker.com/r/willholtz/micromamba). Versioned builds are created automatically when there are new commits on the main branch or new version tags added to https://github.com/buildcrew/micromamba_docker. I haven't yet tried to have new releases of micromamba kick off the build, but currently it appears that binary builds on https://micromamba.snakepit.net/ are lagging source releases, as v0.7.10 is not yet available at https://micromamba.snakepit.net/api/micromamba/linux-64/0.7.10.

**Comment by wolfv** [comment]
@wholtz your dockerfile looks awesome. Would you mind it if we make an "official" version from it?

**Comment by wolfv** [comment]
Actually, if you're up for it, you could move your repo to mamba-org, and become a part of the org. then we could share maintainership for the docker image. We can push it to https://hub.docker.com/u/mambaorg then

**Comment by wholtz** [comment]
@wolfv - Moving the repo to mamba-org sounds great.  Please start the process and let me know if you need me to do any steps.

**Comment by wolfv** [comment]
Awesom @wholtz! I just made you a member of the mamba-org organisation which will allow you to transfer the repo. You'll keep full ownership and admin rights on the repo, of course.

**Comment by wholtz** [comment]
@wolfv - repo transferred to mamba-org. Looks like someone will have to give me rights on the repo. Also, I would like to rename it to micromamba-docker to match the org naming convention.

**Comment by wolfv** [comment]
Awesome, this is a great contribution. Thanks @wholtz! I made you admin on the repo, and proceeded with the rename :tada:

**Comment by wolfv** [comment]
Keeping the issue open until we have continuously updating docker image on dockerhub.

**Comment by wolfv** [comment]
@wholtz I want to point out one small thing I just read in the readme: while it's true that micromamba requires glibc, many other programs that are on anaconda defaults or conda-forge channel require glibc as well :) So even if we had a Alpine image and working micromamba, few packages of the popular channels would work. (Just as an FYI)

**Comment by wholtz** [comment]
@wolfv Yes,  the issue that I reference (#527) makes that pretty clear, but I changed the README.md to state this a little more directly.

Can I help set up the automatic docker builds on dockerhub?

**Comment by wolfv** [comment]
Cool! 

For the automatic docker-push I was thinking of using GitHub Actions. If you want to give that a go, I'd be happy :) We might want to run the github action on-demand and as a cron-job (since there is a delay after tagging a release on github and the release on conda-forge / anaconda.
Maybe we can check every 24 or 12 hours for a new release.

**Comment by ddobrinskiy** [comment]
This is amazing.

I switched CI for my projects to micromamba, and compared to using a miniconda docker image, this reduced build times more than 2x

Thank you guys.

**Comment by wholtz** [comment]
@ddobrinskiy That's awesome! I'm going to put that quote somewhere more visible.

**Comment by wolfv** [comment]
Yes, I think there are now two very good sources for docker images with mamba or micromamba:

- [condaforge/mambaforge](https://hub.docker.com/r/condaforge/mambaforge)
- [mamba-org/micromamba](https://hub.docker.com/r/mambaorg/micromamba)

So closing this is fine.
