### ISSUE TITLE
Failed to get all the deps of imagemagick (and maybe other)

### ISSUE THREAD

**Issue by FanchTheSystem** [mamba-org/mamba#564]
When trying to install **imagegick**, it failed to find the dependencies on **xorg-libxau**

In an empty env with conda:
```
$ conda install imagemagick
[...]
$ conda list | grep xorg-libxau
xorg-libxau               1.0.9                h14c3975_0    conda-forge
```

In an empty env with mamba:
```
$ mamba install imagemagick
[...]
Executing transaction: ...working... g_module_open() failed for /opt/conda/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: libXau.so.6: cannot open shared object file: No such file or directory

g_module_open() failed for /opt/conda/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: libXau.so.6: cannot open shared object file: No such file or directory

done
$ conda list | grep xorg-libxau

```

Tested with mamba 0.6.0 and 0.6.1 with conda 4.9.0

Please also note that **imagemagick** depend on **graphviz** and **xorg-libx11**, both depend on **libxcb**, which depend on **xorg-libxau**, which provide the missing  **libXau.so.6**

**Comment by wolfv** [comment]
What channels and are you using strict priority?

**Comment by FanchTheSystem** [comment]
For my test I am using this docker image:
https://github.com/FanchTheSystem/docker-mamba/blob/master/Dockerfile

So the channels are conda-forge and bioconda (but I think bioconda is not used for imagemagick)

I have launch a build with 0.6.5 to try with this version

**Comment by FanchTheSystem** [comment]
![image](https://user-images.githubusercontent.com/882203/97752092-adc9f100-1af3-11eb-9325-bd4a2a72ba4c.png)

**Comment by wolfv** [comment]
Thanks for the detailed bug report! It looks like there might be an issue with transaction ordering...
Can we be sure that no packages from defaults are pulled in?

**Comment by FanchTheSystem** [comment]
Thank you for the great work with mamba (I should have said this before ;) )

I think you're are right the issue seems to be related to the default channel.

Maybe you have docker installed on your computer, so you can see by yourself the output of : 

1.
```
docker run -it registry.gitlab.com/ifb-elixirfr/docker-images/mamba:0-6-4 mamba install --yes imagemagick
```
Failed with the error reported on my first message.

2.
```
docker run -it registry.gitlab.com/ifb-elixirfr/docker-images/mamba:0-6-4 conda install --yes imagemagick
```
Work as expected.


3.
```
 docker run -it registry.gitlab.com/ifb-elixirfr/docker-images/mamba:0-6-4 mamba install --yes --override-channels --channel conda-forge imagemagick
```
Work well when conda-forge is forced to be the only used channel

**Comment by FanchTheSystem** [comment]
As you can see in the Dockerfile, I think it is a very common way to install conda and mamba, so maybe it should work without the need to force a channel.

**Comment by coroa** [comment]
The linked `Dockerfile` does not follow the [recommended](https://bioconda.github.io/user/install.html#set-up-channels) channel ordering (`conda-forge`, `bioconda`, then defaults) and does not enable [strict](https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it) `channel_priority`, which I suspect is the default for mamba (as it is scheduled for conda 5).

@FanchTheSystem Can you try and amend the Dockerfile to reverse the add calls as suggested by the [bioconda docs](https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it) and retry. And if that fixes the problem raise it as an issue on https://github.com/FanchTheSystem/docker-mamba ?

**Comment by FanchTheSystem** [comment]
Thank you @coroa I have fixed the Dockerfile, and now it work with every version of mamba 0.6.0 0.6.1 and 0.6.4

There is still something strange, is that conda find a solution when the channel config is not well set, and mamba does not find it.

**Comment by coroa** [comment]
> There is still something strange, is that conda find a solution when the channel config is not well set, and mamba does not find it.

No, that is not strange, conda's default resolver (for version <5) adds a penalty to channels with lower priority but still allows them, unless you configure it with `channel_priority: strict` to take the package from the highest priority channel in which it appears (no compromises).

Mamba has this strict channel priority by default, ie. by design it forbids penalized solutions of current conda versions (since in ABI world are prone to breakage).

**Comment by FanchTheSystem** [comment]
Yes I have understand it after my message, it is why I have closed the issue some hour later ;)
