### ISSUE TITLE
create_default_packages from `.condarc` not respected when creating from environment file

### ISSUE THREAD

**Issue by coroa** [mamba-org/mamba#566]
With `.condarc` containing:

```yaml
channels:
  - conda-forge
  - defaults
create_default_packages:
  - pip
  - ipython
  - ipykernel
  - black
  - pylint
  - flake8
  - flake8-black
```

While `mamba create` will pull in the default packages:
```
$ mamba create -n tmp python=3.8
[...]
Looking for: ['python=3.8', 'pip', 'ipython', 'ipykernel', 'black', 'pylint', 'flake8', 'flake8-black']
[...]
```

An environment file with the same contents (ie. `dependencies: - python=3.8`), will not include the default packages listed in `.condarc`:
```
$ mamba env create -f environment.yml
[...]
Looking for: ['python=3.8']
[...]
```

This is with `mamba 0.6.4`, `conda 4.8.5`

**Comment by wolfv** [comment]
does this work with conda?

**Comment by coroa** [comment]
I was convinced it would, but a short test shows, it does not. That's a bummer.

I still think it should. There is an issue in the tracker agreeing with me, but it has been sitting idle, since this January: https://github.com/conda/conda/issues/9580 .

Don't know how mamba wants to proceed here then, though.

**Comment by wolfv** [comment]
Yeah, I could see a flag for this being interesting. As a default, no: environment files are used to recreate exact environments... so this behavior would be very broken when suddenly default packages appear in there.

I am going to close this issue, but feel free to work with upstream conda on implementing this. 

Also, you could easily add your default packages to the environment.yml with a bit of code, for a workaround.

**Comment by coroa** [comment]
Environment files can be used to re-create exact environments, but more often i would argue are used to re-create *compatible* environments.

The default use case for `create_default_packages` are packages like `ipython` or `ipykernel`, that are not necessary for a functioning library or python installation but rather part of how the user wants to interact with it, but yes the work-around of adding them to the environment files is of course possible.

Thanks
