### ISSUE TITLE
mamba ignores requested channel

### ISSUE THREAD

**Issue by luk-f-a** [mamba-org/mamba#571]
hi, we've started using mamba for CI and it's great! thanks for this tool.

There seems to be a problem with the channels. The following environment.yml fails to install `numba==0.52.0rc2` and silently installs `numba=0.51.2` instead because 0.52.0rc2 does not exist in `defaults` or `conda-forge`.

```
channels:
  - defaults
  - conda-forge
dependencies:
   [... other dependencies...]
  - numba::numba==0.52.0rc2 
```
Conda correctly installs `numba==0.52.0rc2`.
The problem goes away if the numba channel is explicitly listed in the channels section. Why is it necessary to declare the channel twice? I thought that writing `numba::numba==0.52.0rc2` would be enough.

**Comment by wolfv** [comment]
What mamba version are you using? This was fixed recently

**Comment by luk-f-a** [comment]
0.5.3

**Comment by wolfv** [comment]
latest is 0.6.5

**Comment by michaelaye** [comment]
this is back in 0.7.6:

```
mamba update --all -c conda-forge  
[...]
  soupsieve               2.0.1  py_1               installed                      
  soupsieve                 2.1  pyhd3eb1b0_0       pkgs/main/noarch          31 KB
  tbb                    2020.2  h4bd325d_1         installed                      
  tbb                    2020.3  hfd86e86_0         pkgs/main/linux-64         1 MB
  tblib                   1.6.0  py_0               installed                      
  tblib                   1.7.0  py_0               pkgs/main/noarch          16 KB
  xlrd                    1.2.0  pyh9f0ad1d_1       installed                      
  xlrd                    2.0.1  pyhd3eb1b0_0       pkgs/main/noarch          90 KB
```
As you can see, `mamba` suggests packages from `pkgs/main` instead of `conda-forge`.

```
$ mamba --version                                                                                                                                    (py37) 
mamba 0.7.6
conda 4.9.2
```
```
$ conda config --show-sources                                                                                                                        (py37) 
==> /home/klay6683/.condarc <==
pinned_packages: []

==> /home/klay6683/miniconda3/envs/py37/.condarc <==
pinned_packages:
  - conda-forge::opencv
  - conda-forge::gdal
  - conda-forge::numpy
channels:
  - conda-forge
```

**Comment by wolfv** [comment]
It seems like you're adding the defaults channel somewhere, otherwise this should not be possible.

**Comment by wolfv** [comment]
Also feel free to open a new issue. I don't think this is related to the parent issue here.

**Comment by michaelaye** [comment]
i have found out that this is caused by `channel_priority=flexible`. Setting it to `strict` produces the expected results. 
However, IMHO, it's bad UX that a command-line option is not trumping any other configured settings. It is customary in any GNU command line utils that command line options are over-ruling anything set in configuration files.
