### ISSUE TITLE
Anaconda micromamba 0.6.x not statically linked

### ISSUE THREAD

**Issue by obilaniu** [mamba-org/mamba#572]
The `README.md` documentation suggests, quote,

> # micromamba
> micromamba is a tiny version of the mamba package manager. It is a pure C++ package with a separate command line interface. It can be used to bootstrap environments (as an alternative to miniconda), but it's currently experimental. The benefit is that it's very tiny and does not come with a default version of Python.
> 
> micromamba works in the bash & zsh shell on Linux & OS X. It's completely statically linked, which allows you to drop it in some place and just execute it.
>
> Note: it's advised to use micromamba in containers & CI only.
>
> Download and unzip the executable (from the official conda-forge package):
>
>     wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba

But the binary obtained from the latest package is not statically linked;  In fact, `readelf -d` reports

```
Dynamic section at offset 0xaafdd0 contains 33 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libresolv.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../lib]
```

Either the documentation is wrong, or the Anaconda recipe is wrong.

**Comment by wolfv** [comment]
All other libraries (curl, libarchive, libsolv,...) are in fact statically linked as you can see.

These are libraries that we require from the host system. I think this was the pattern I found with other statically linked executables, too, and it has worked quite well so far.

The only issue is running on alpine Linux which uses musl libc.

**Comment by obilaniu** [comment]
> All other libraries (curl, libarchive, libsolv,...) are in fact statically linked as you can see.
> 
> These are libraries that we require from the host system. I think this was the pattern I found with other statically linked executables, too, and it has worked quite well so far.
> 
> The only issue is running on alpine Linux which uses musl libc.

Okay, but _"It's completely statically linked, which allows you to drop it in some place and just execute it."_ suggests that it's entirely self-contained and could be run standalone on any capable Linux kernel. If that isn't true, I'd alter the README to say something to the effect of _"most dependencies are statically linked, and we only require Glibc plus base system libraries"_.

**Comment by wolfv** [comment]
@obilaniu have you seen "fully statically linked" executables that link all of these libraries? I was under the impression that it's not done, usually.

E.g. https://stackoverflow.com/questions/57476533/why-is-statically-linking-glibc-discouraged#:~:text=The%20most%20important%20reason%20why,C%20library%2C%20that's%20no%20problem.

But yeah, we can change the readme to mention that we only run on glibc for now ... which is also a restriction for the conda-packages on conda-forge. 
It should be straightforward to get a musl  build though, if someone is interested.

**Comment by obilaniu** [comment]
@wolfv It's rare to see fully statically-linked executables, but they do exist, and most often in a "bootstrap" context; This is why I was initially very excited by micromamba's description. If micromamba still relies on certain "base" libraries, it's more fragile, particularly if it is being compiled on a machine with a very new Glibc and is then copied to a machine with an older Glibc.

In fact, I thought the reason why this might not be possible would be legal reasons - statically linking those various libraries might (?) run afoul of the (L)GPL licenses?

One package that is not-uncommonly distributed as fully statically linked is Busybox; it implements a few core Unix utilities with fully statically linked executables, as is useful on embedded platforms.

**Comment by wolfv** [comment]
interesting! 
We compile on the conda-forge infrastructure which makes sure that we do support relatively old distributions (Centos 6 & OS X 10.12, and I think Windows has a better back-compat story).

I am not sure about the license implications but we're also quite interested in keeping the binary size as small as possible, so leaving out these libraries helps with that.
So far we have had a pretty good experience with the current binaries.

**Comment by traversaro** [comment]
One thing that I miss is that even with micromamba supported running on system based on  musl libc, without conda channels that provide musl binaries (if I am not wrong), what is the use of micromamba? For example Julia's BinaryBuilder/Yggdrasil/ support musl binaries, but they are treated as a completely different architecture, see https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/tag/XML2-v2.9.10%2B0 .

**Comment by wolfv** [comment]
indeed, we could treat musl like we do with linux-arm64... it could be linux-musl-x64 etc.

Theoretically, it would be straightforward to have support in mamba/conda/micromamba. But it would add an additional entry to the build matrix and I am not sure wether it's worth it or not.

However, with boa-forge (github.com/mamba-org/boa-forge) we aim at building out a source-distribution. In that context, we could make it simple to rebuild a stack using musl as libc.

**Comment by obilaniu** [comment]
@wolfv The remaining libraries still being dynamically linked to are mostly C library-related.

The [musl C library](https://www.musl-libc.org/intro.html) is liberally-licensed and lightweight, which is why containers frequently use Alpine Linux + musl.

If you were to statically link against musl-libc you would be able to safely copy and run the resulting `micromamba` on any distro, even on Glibc-based systems, and it ought not to be much heavier than it already is (10MB; the _entirety_ of musl is allegedly [426KB](https://www.etalabs.net/compare_libcs.html), but not all of that will be needed).

Further, if Anaconda shipped an installable `glibc` package (which at present it does not, to my knowledge), then a fully-statically-linked `micromamba` could be used to install a working Glibc-based environment _even on systems where the C library is musl, is damaged (!) or even accidentally deleted (!!!!)_.

**Comment by wolfv** [comment]
If you have a prototype for this id be happy about a PR :)

**Comment by obilaniu** [comment]
@wolfv @traversaro The attached [Singularity.txt](https://github.com/mamba-org/mamba/files/5506025/Singularity.txt) recipe file, in conjunction with the Singularity 3.6.4 container technology, currently builds a **6.9 MiB fully-statically-linked `/usr/bin/micromamba`** (>30% smaller than the current dynamically-linked Anaconda build) that is capable of `micromamba create`'ing the build environment of Mamba without any problems whatsoever.

     singularity build micromamba.sif Singularity.txt    # micromamba.sif is 192 MiB
     singularity shell micromamba.sif
     Singularity> cp /usr/bin/micromamba .
     Singularity> exit

The container recipe is Alpine Edge Linux-based, but because the `micromamba` is fully-statically-linked with `musl-libc` and _all_ other libraries, it can run anywhere. The container recipe includes the patch in #576, but once that's merged, that part of the recipe may be struck off.

As a minor detail, Mamba's CMake build system is too difficult for me to hack to convince it to use a valid final link line, so in the recipe, the `make` step deliberately fails, whereupon I supply the correct link command for a fully static link.

**Comment by traversaro** [comment]
Thanks @obilaniu, this is quite interesting. For the trailing `-Wl,-Bdynamic` problem in CMake, perhaps setting the [`CMAKE_LINK_SEARCH_END_STATIC`](https://cmake.org/cmake/help/v3.18/variable/CMAKE_LINK_SEARCH_END_STATIC.html#variable:CMAKE_LINK_SEARCH_END_STATIC) CMake option at the CMake invocation to `ON`  could help.

**Comment by wolfv** [comment]
Wow this is interesting! 

I'm planning to refactor our cmake soon. Hopefully we can get support for a fully static micromamba into our configurations

**Comment by obilaniu** [comment]
@wolfv @traversaro You were right - in the end I used the related `set_target_properties(micromamba PROPERTIES LINK_SEARCH_END_STATIC ON)` to solve my link problems.

So with the following [Singularity.txt](https://github.com/mamba-org/mamba/files/5507935/Singularity.txt) recipe, the #572 patch has been removed since it's already merged, and instead there are three patches against `CMakeLists.txt` that implement the minimum changes required for a fully-static, successful CMake build against `musl` (at least on Alpine).

The gist of the patchset in the recipe is, in order:
1. No need for Kerberos (`libgssapi_krb5.a`, `libkrb5.a`, `libk5crypto.a`, `libkrb5support.a`). Also, musl-libc integrates `libiconv.a`, so there's no need to explicitly pull it in.
2. Alpine's `libarchive.a` wants some new dependencies, so add them (`libacl.a`, `libbrotlidec.a`, `libbrotlienc.a`, `libbrotlicommon.a`)
3. For a fully-static link, one must use the `-static` flag and the linker search option must be set to `-Wl,-Bstatic` at the end. Furthermore, musl integrates `librt`, `libdl` and `libresolv` within itself (just as with `libiconv`), so there's not only no need to pull those in explicitly, but self-evidently they must not be forced to dynamic linkage when we are trying to implement a fully-static build.

If there are plans to refactor the build system soon, I hope this recipe might serve as both a "supported use-case" and a step (return?) to fully-statically-linked Conda `micromamba` packages.

**Comment by wolfv** [comment]
Thanks @obilaniu for exploring this!

I wanted to point out some additional work I have been doing: in [boa-forge](https://github.com/mamba-org/boa-forge) I am gathering (new-style, "boa") recipes to bootstrap micromamba from. One interesting feature about these recipes is that they can have "features" (which are compile-time features). E.g. it's possible to add/remove unused compression algorithms from libarchive to further shrink the executable -- we don't use brotli as of know etc.
Maybe we could also add a recipe for `musl` in boa-forge, and then sooner or later switch over to the boa-forge recipes to bootstrap micromamba ...

The current builds served on anaconda.org have the nice property to be built on "public" conda-forge infrastructure, relying on the same base-packages as the rest of the ecosystem etc. So for that sake I think the "official" builds on conda-forge will stay as they are for a little while longer but it would be _great_ to support this usecase in CMake soon. I'll try to make our CMake better today.

**Comment by obilaniu** [comment]
@wolfv I have updated my [Singularity recipe](https://github.com/mamba-org/mamba/files/5523066/Singularity.txt) after your changes earlier today. They introduced new dependencies and I therefore needed to update my patches.

Particularly noteworthy is that you are now statically linking `libreproc++.a`, but I believe you're missing `libreproc.a`, on which `libreproc++.a` depends.

It turns out that it wasn't `libarchive` but `libcurl` that introduced the Brotli dependency, so I modified the recipe to download the `APKBUILD` for `curl` and tweak it with a `--without-brotli` at the `./configure` step, then rebuild the package and install it. I also switched the other from-source CMake builds (`yaml-cpp`, `libsolv`, `libreproc` and `micromamba` itself) from `Release` to `MinSizeRel` mode.

The combined result is that my `micromamba` is now down to **5.8 MB, fully statically linked**, even with your new dependencies.

**Comment by wolfv** [comment]
awesome! yeah, we have some important improvements for the upcoming release, including the usage of reproc. I also repaired that same issue this morning. 
I am going to try to put out a new release of micromamba today, and then we can see how to integrate your ideas with our tools.

**Comment by wolfv** [comment]
Hi @obilaniu I have a custom pipeline for building micromamba here: https://github.com/mamba-org/boa-forge/runs/1693702406

I am wondering if you would know how we could build musl-libc in a first step, and link against that from all further downstream packages? I guess the advertised solution would be to use `CC=musl-gcc` ... maybe we can figure out the required flags ourselves...
Or we could run on a musl-base image and link statically to it.

**Comment by obilaniu** [comment]
@wolfv Oh, thanks!

I realize I haven't shared my latest Singularity recipe, so I'll do that now:
- [Singularity.txt](https://github.com/mamba-org/mamba/files/5807567/Singularity.txt)  (Works for 0.7.6)

Building musl-libc from scratch is probably overkill. As depicted in the recipe, my preference is to `apk install alpine-sdk` plus everything else I can get "for free" _(`curl` being an exception - I patch and rebuild that package to drop a dep on Brotli)_, then build from source that which I cannot, and finally run the Mamba build.

**Comment by obilaniu** [comment]
@wolfv Further to this: I have now managed a **4.5 MB, fully-statically-linked, musl-based** `micromamba` 0.7.10 for x86_64 using hard-core LTO optimization. Compressed with `xz` it takes 1.9 MB. This compares with the 11.0 MB, partially-statically-linked, glibc-based `micromamba` 0.7.9 for x86_64 currently served by Anaconda cloud, and even the `.tar.bz2` tarball takes 4.9 MB, which is more space than my own build.

[This `micromamba.zip` file](https://github.com/mamba-org/mamba/files/5863788/micromamba.zip), unpacked, contains a patchset and 6 Singularity recipes to construct `micromamba`.

The _same_ Zip file, renamed to `micromamba`, **is** the micromamba executable constructed by the recipes, and as a statically-linked executable can be dropped in anywhere, should you be daring and trusting enough to try it _(However: don't run untrusted binaries from the Internet!)_.

As the Singularity container recipes show, I have a rather extensive process:

 1. `alpine-edge.sif`: Grab the latest Alpine Linux base and update it to Alpine Edge.
 2. `alpine-bareuser.sif`: Following the Alpine [wiki](https://wiki.alpinelinux.org/wiki/Include:Setup_your_system_and_account_for_building_packages), create a user `dev` for package development purposes and add him to `sudoers`. But don't yet install any major development packages.
 3. `alpine-user.sif`: Install development packages _temporarily_, set up `dev`'s private package repository and add it to `/etc/apk/repositories`, and `git clone` the Alpine `aports` repo, then effectively uninstall the development packages. 
 4. `alpine-lto.sif`: Install the development packages, check out `aports` `master` branch, patch it with `aports.patch`, then `abuild -r` with LTO only those packages that are transitive dependencies of `alpine-sdk`. Built packages are automatically placed in `dev`'s private repository. However, the `musl` package is excluded, because it fails to work with LTO. I go out of my way to override the `linux-headers` package (default 5.7.8) with a much older version (3.10.108; 3.10 is the antique kernel series used in RHEL 7).
 5. `lto-deps.sif`: Now that LTOed, transitive `alpine-sdk` dependencies are available from the local repo, install `alpine-sdk` again, automatically pulling in the recompiled packages from the local repo. Compile the rest of the dependencies of `micromamba` available in `aports` with LTO as well. Save packages to `dev`'s private repo.
 6. `micromamba.sif`: Install the `alpine-sdk` one last time, along with the huge collection of LTOed recompiled static libraries now available. Next, clone/copy/compile the last few dependencies of `micromamba`: CLI11 1.9.1, yaml-cpp 0.6.3, reproc++ 14.2.1 and libsolv 0.7.17. The final steps are to patch the `CMakeLists` of `micromamba` suitably for the musl environment just constructed above, then build, install and strip `/usr/bin/micromamba`.

The whole process from scratch takes several hours because some 200 packages are rebuilt from source. It took an even longer amount of time to debug and disable some failing testsuites. Nevertheless, the breakdown of the recipes means that in general, you only need to recreate the top-level Singularity image `micromamba.sif`. Further speedup could be had by APK-packaging the final four dependencies, but I can still just about bear the current rebuild time.

**Comment by wolfv** [comment]
Wow, that is some impressive work you have there!
I have also worked further on a micromamba build using github actions and `boa` as a build tool. 
I have a custom pipeline now that builds all dependencies of micromamba from scratch and publishes a nightly release to github releases:

Recipes: https://github.com/mamba-org/boa-forge
Example release: https://github.com/mamba-org/boa-forge/releases/tag/nightly-tag-2021.01.25.1439

It's not as small as your result and also not statically linked to libc, though. On the other hand, it produces builds for Windows and OS X as well :)

I would be very interested to see if we can add in musl into these boa recipes ... I feel it should be possible but I have no experience with that.

One other upside is that the process of building these ~8-10 dependencies takes only roughly 20 to 30 minutes on github actions with 2 cores.

**Comment by obilaniu** [comment]
@wolfv I notice that you've struck out in the [micromamba](https://github.com/mamba-org/boa-forge/blob/master/micromamba_recipe/CMakeLists.txt) recipe the LZMA, LZO, LZ4, libcom_err/e2fsprogs and nghttp2 dependencies. So which compression algorithms are in fact allowed by the Conda package spec?

My LTOed `micromamba` is currently compiling with all of those extra dependencies, perhaps I could trim even more. The Ext fileysstem support is a particularly obvious one to remove, but what use does micromamba make of nghttp2?

**Comment by obilaniu** [comment]
@wolfv Well, I just went ahead and tried it out, and removing all of those extra dependencies, I only get a shrinkage from 4.5 to 4.3 MB, a minor shrinkage. Half is due to nghttp2 and half to the removal of the extra compression algorithms.

It seems like LTO has done an excellent job stripping away dead code, so I'm unsure if it's really worth it for my build to disable features that future-proof `micromamba`, particularly the compression algorithms (when packages switch to better compression than bzip2).
