### ISSUE TITLE
Creating environment from yml file installs in root

### ISSUE THREAD

**Issue by davidbrochart** [mamba-org/mamba#578]
It looks like:
```bash
$ mamba env create -f environment.yml
```
ignores the environment name and always installs in the root environment.

**Comment by wolfv** [comment]
I have this yaml file that I test with:

```
name: testenv
channels:
  - conda-forge
dependencies:
  - python >=3.6,<3.7
  - importnb >=0.5.2
  - ipykernel >=5.1
  - ipython >=7.2
  - jupyterlab >=0.35.4,<0.36
  - nodejs >=8.12,<9
  - pillow
  # - robotframework >=3.1
  - tornado <6
```

using 

`mamba env create -f testenv.yml`

And it works fine. 

Are you sure you didn't do `mamba create -f environment.yml`? That command doesn't understand yaml files.

**Comment by davidbrochart** [comment]
I just tried and I don't have the same behavior as before, meaning it works fine but it seems to use conda under the hood. I can recognize it because of:
```
Downloading and Extracting Packages
nodejs-8.12.0        | 12.0 MB   | ########################################################################################################## | 100% 
python_abi-3.6       | 4 KB      | ########################################################################################################## | 100% 
ipython-7.16.1       | 1.1 MB    | ########################################################################################################## | 100% 
...
```

**Comment by wolfv** [comment]
yeah that's true, one of the big "warts" of conda is that `conda env` and `conda create` are two completely seperate things. `conda env` is implemented in a seperate module, and we actually have to do another monkey patch to make mamba work with it:

**Comment by wolfv** [comment]
https://github.com/mamba-org/mamba/blob/master/mamba/mamba_env.py#L102

**Comment by davidbrochart** [comment]
Maybe we could rewrite so that it uses mamba? In the end it is just a sequence like:
- `mamba create -n testenv`
- `source activate testenv`
- `mamba install all_the_dependencies`

**Comment by wolfv** [comment]
it's using mamba for the solving part, but not for the installation part right now.
I think that's "good enough" right now. For micromamba, we already have a completely new way to read yml environment files, and the API is less confusing (IMO).
