### ISSUE TITLE
timeout on solver

### ISSUE THREAD

**Issue by beckermr** [mamba-org/mamba#580]
We've been having trouble with really long solves. We are not sure why, but a timeout option would be useful. I tried from python but I could not get it to work, probably due to the solver being down in C++.

**Comment by beckermr** [comment]
cc @wolfv

**Comment by wolfv** [comment]
@beckermr is this still something that would be useful for the bot? afaik you found a workaround, right?

**Comment by beckermr** [comment]
I do have a workaround, but I think we should push on this issue. I suspect this is an actual bug in libsolv.
