### ISSUE TITLE
Ability to Remove Mamba Banner?

### ISSUE THREAD

**Issue by habemus-papadum** [mamba-org/mamba#587]
Hi -- Is it possible to not print the mamba banner on every invocation?  
```
                 __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝
```

The following:
`mamba list --explicit > test.txt` produces an invalid file because it contains the banner the very top. 

Thanks for the great work!

**Comment by wolfv** [comment]
yeah, good point! do you want to put in a PR to disable banner printning with `list`?

**Comment by habemus-papadum** [comment]
Sure- I'll give it a shot

**Comment by TwelfthGhast** [comment]
You can currently suppress this with `--quiet` right?

**Comment by tstenner** [comment]
Or [`--no-banner`](https://github.com/mamba-org/mamba/blob/57b7edec6387f55dc7e8bb75264036914c7e467d/mamba/mamba.py#L816).

**Comment by nikhilweee** [comment]
Just to add to @tstenner's answer and to save you from some typing each time you invoke `mamba`, you could also set the environment variable `MAMBA_NO_BANNER` like so. This way, none of the `mamba` commands would show any banner.
```
$ export MAMBA_NO_BANNER=1
```

**Comment by habemus-papadum** [comment]
All good answers.  Apologies if they were already in the docs.  Thank you!

**Comment by phil-blain** [comment]
I just stumbled on this issue and noticed neither `--no-banner` nor `MAMBA_NO_BANNER` are mentioned in the docs, nor in the output of `mamba -h`...

**Comment by wolfv** [comment]
@phil-blain PRs are always welcome! :)

**Comment by looooo** [comment]
it would be nice to have the banner disabled by default. things like `mamba run` results in different output compared to `conda run`. Although it is a really nice artwork ;)

**Comment by corneliusroemer** [comment]
`--quiet` didn't suppress the banner until this recent PR. So quiet should work from >1.0.0 onwards

https://github.com/mamba-org/mamba/pulls?q=is%3Apr+is%3Aclosed
