### ISSUE TITLE
Ability to solve for a different environment?

### ISSUE THREAD

**Issue by habemus-papadum** [mamba-org/mamba#588]
Hi, 

Is there a way to "solve packages" for an architecture different than the host machine on which mamba is running? Ideally, there would be some command like:

```
mamba solve --arch linux-64 <package & channel flags> 
```

that could be run on MacOS and produces an output similar to `conda list --explicit`

**Comment by wolfv** [comment]
hey, yeah, that's possible with a weird-ish syntax (same as conda):

`CONDA_SUBDIR=linux-64 mamba create -n test --dry-run --json package-channel-stuff`

This functionality is used in conda-lock: https://github.com/conda-incubator/conda-lock to produce lock-files for multiple platforms. I think that's the project you might be looking for :)

**Comment by habemus-papadum** [comment]
Yup!  that's exactly where I was going.  thanks
