### ISSUE TITLE
undefined symbol: curl_url_cleanup

### ISSUE THREAD

**Issue by THZ34** [mamba-org/mamba#594]
An error has happened after I running 'conda update --all'
$mamba
Traceback (most recent call last):
  File "/software/anaconda3/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/software/anaconda3/lib/python3.8/site-packages/mamba/mamba.py", line 52, in <module>
    import mamba.mamba_api as api
ImportError: /software/anaconda3/lib/python3.8/site-packages/mamba/mamba_api.cpython-38-x86_64-linux-gnu.so: undefined symbol: curl_url_cleanup

**Comment by wolfv** [comment]
can you show a `conda list` and what channels you use?

**Comment by wolfv** [comment]
specifically what version of curl do you have now?

**Comment by THZ34** [comment]
Thank you for your reply, the following is the information about mamba and curl.
mamba                     0.7.1            py38hc157fb9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
curl                      7.26.0                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

**Comment by wolfv** [comment]
That should really not be possible since mamba requires a version of libcurl >=7.71 ... How did you install mamba?
Also, it's advised to not mix packages from anaconda-default channel and conda-forge like this.

**Comment by THZ34** [comment]
Ok, I will update my curl, thanks again.

**Comment by ovo-Tim** [comment]
![图片](https://user-images.githubusercontent.com/116942368/222907749-e747d2d6-5c0d-475d-a656-384fc36f6235.png)
![图片](https://user-images.githubusercontent.com/116942368/222907777-9f55dbb8-4282-443b-8f05-6570878d67f5.png)
I met this problent again,What shoud I do?

**Comment by jonashaag** [comment]
Please open a new issue with the issue template, thanks!
