### ISSUE TITLE
[micromamba] set root ca for windows and OS X

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#596]
we currently set some custom root certificate locations for different Linux distros in main.cpp, but not yet for Windows or OS X.

**Comment by wolfv** [comment]
which effectively disable SSL verification on those system.

**Comment by dhirschfeld** [comment]
Related? https://github.com/mamba-org/mamba/issues/530

**Comment by wolfv** [comment]
Interesting! For micromamba, we do explicitly set some paths here: https://github.com/mamba-org/mamba/blob/d44d945d2e3b56fd1f77e85e6764c98a9505d0b0/src/micromamba/main.cpp#L169-L177

To make curl look into those for CA certificates. I saw that there is some Windows Registry entry for certificates, but yes, the better idea might be to link with a OpenSSL that was build against sschannel and not having to deal with this?

But you were experiencing this with regular mamba, as far as I understand? In that case the OpenSSL from conda-forge should depend on `ca-certificates` and place fresh `ca-certificates` into the prefix, and curl has a hard-coded path to those.

I'll have to look deeper into this...

**Comment by wolfv** [comment]
Also of note is that from what I saw on StackOverflow, there are no CA Certificates easily available on OS X ... except for in the keychain but no idea if we can use that with curl.

**Comment by dhirschfeld** [comment]
>  OpenSSL from conda-forge should depend on ca-certificates and place fresh ca-certificates into the prefix

On Windows, (self/company signed) certificates are added to the Windows Certificate Store which is only accessible via the schannel interface (IIUC).

Our internal repo server uses a company-signed certificate which isn't in any `ca-certificates` bundle so SSL fails without using schannel.

**Comment by dhirschfeld** [comment]
As I type that I recall that you can make `certifi` work with the Windows Certificate Store via some black magic:
https://gitlab.com/alelec/python-certifi-win32

...I'll check it that works for `mamba`. Still, on Windows it would be nice for it to Just Work out of the box if enabling schannel isn't too painful.

**Comment by dhirschfeld** [comment]
In case it's interesting there's a fair bit of discussion over in:
https://github.com/psf/requests/issues/2966#issuecomment-724123540

**Comment by dhirschfeld** [comment]
`certifi` works for python (requests) so it does work for `conda`.

For `mamba` I think the curl library needs to be compiled with schannel support (#530)

**Comment by wolfv** [comment]
Fixed by using SChannel on Windows and SecureTransport on OS X.
