### ISSUE TITLE
[micromamba] Support transmute?

### ISSUE THREAD

**Issue by asford** [mamba-org/mamba#599]
_Mostly a check if you'd be open a PR on this._

The `transmute` implementation in `boa` is pretty thin, and could be ported to micromamba. A statically-linked and performant `transmute` implementation would be very useful to help build package caching pipelines.

Would you be open to adding `transmute` to the micromamba cli?

**Comment by wolfv** [comment]
Howdy!

I am not entirely convinced that micromamba is the right place for this, and I am also unsure wether this would increase the binary size or not. Hypothetically, currently we should be able to `strip` all functions for writing archives when linking micromamba.

But I think writing a standalone tool, similar to conda-package-handling, based on libmamba, linked statically or not, would be awesome! 

One problem that I currently have is that using libarchive in a multithreaded fashion seems to be impossible, so we can only have one decompression job at a time. One issue is that libarchive usually `cd's` into the directory where the file should be extracted, and the current working directory is set _per process_. I had a solution that re-wrote the extraction filenames on the fly to the absolute extraction destination and that kinda-worked but meh.

So one idea would be to have this other small executable (mamba-package-handling or whatever), and spawn subprocesses for the extraction jobs. That way we could scale to use all cores of the computers mamba is running on... And IMO this program could also have the transmute functionality.

So yeah, in that sense I am quite interested in this!
