### ISSUE TITLE
Activation issue on Windows caused by whitespaces in path

### ISSUE THREAD

**Issue by adriendelsalle** [mamba-org/mamba#605]
Hi !

I'm facing an activation issue on Windows.
It is probably due to whitespaces in my path entries, such as `C:\Program Files (x86)\some_dir`.

It looks like related to this [part](https://github.com/mamba-org/mamba/blob/457fbda0c6157b99220099494b9bde24f16571b1/data/_mamba_activate.bat#L22).

If I just add quotes around the command, it works:
``` shell
@SET "PATH=!_sysp!;!_sysp!\Library\mingw-w64\bin;!_sysp!\Library\usr\bin;!_sysp!\Library\bin;!_sysp!\Scripts;!_sysp!\bin;%PATH%"
``` 

Are you able to reproduce?
I will be happy to make a PR if it is confirmed :)

Thanks !

**Comment by wolfv** [comment]
Hi, thanks for opening this issue. Yes, that sounds like a problem!
I think there is a way to get a shortened, space-free path on Windows. Here is the code where I exctracted these functions from:

https://github.com/conda/conda/blob/e5a596438122ae15347aec16a2370423d7917b46/conda/shell/condabin/_conda_activate.bat#L12-L23

Note that conda doesn't use the `MAMBA_ROOT_PREFIX` stuff, but rather finds the "root" sys-prefix through other means (e.g. through python invokation).

So maybe there is some magical `%%~dpA` or other weird way of turning the path into a short path? 

@dhirschfeld often has really good answers, too.

**Comment by adriendelsalle** [comment]
Thanks for your reply @wolfv !
I should have opened a draft PR. 

Let's dig a bit this question before using my (too?) simple fix!

**Comment by wolfv** [comment]
nope, I think your fix is fine. Sorry, didn't properly read the entire message.

**Comment by wolfv** [comment]
I fixed a similar thing with the same technique last week :) cmd.bat is the worst.

**Comment by adriendelsalle** [comment]
I couldn't disagree ;)
