### ISSUE TITLE
Stages verbosity

### ISSUE THREAD

**Issue by adriendelsalle** [mamba-org/mamba#608]
Hi!

A simple question about verbosity.

At this time I use the `-q` flag to reduce verbosity. In that case I don't receive anymore info about the "linking" stage but still have the package plan output.
I would have expected maybe to have nothing displayed. Is this a description of a `silent` mode and not a `quiet` mode?
In that case the `quiet` mode should only display major stages?

Default level of verbosity also leads to a lot of info displayed during the "linking" stage : it lists all the packages one by one.
Would it be possible/desirable to reduce this verbosity to a stage description such as "Linking packages" (BTW "Transaction starting" is not very expressive IMHO) and use one of the verbosity levels (`-v` to `-vvv`) to display more?

Thanks for your thoughts!

**Comment by wolfv** [comment]
In general we tried to stay somewhat close to how conda operates. I think they also display the transaction in quiet mode. 

But having a second pair of eyes thinking deeply about what to display when would be great and there is definitely room for improvement!

**Comment by adriendelsalle** [comment]
It keep this in mind and will propose something more detailed in the coming weeks

**Comment by adriendelsalle** [comment]
Similar but not same as https://github.com/mamba-org/mamba/issues/643
