### ISSUE TITLE
micromamba and caching pkgs-folder

### ISSUE THREAD

**Issue by kmuehlbauer** [mamba-org/mamba#612]
For work with CI it is often desirable to cache the `pkgs` folder. Normally only the archives (tar.bz2) are cached.

When doing this and trying to create a new environment micromamba breaks. Packages resolving works nice, it also detects that no package needs to be downloaded, but then it breaks with the below error.

```
Transaction starting
INFO    transaction.cpp:379 Found python version in packages to be installed 3.8.6
Linking libgfortran5-9.3.0-he4bcb1c_17
INFO    link.cpp:917 Executing install for "/home/data/kai/projects/micromamba_test/pkgs/libgfortran5-9.3.0-he4bcb1c_17"
WARNING link.cpp:919 Opening: "/home/data/kai/projects/micromamba_test/pkgs/libgfortran5-9.3.0-he4bcb1c_17/info/paths.json"
terminate called after throwing an instance of 'std::system_error'
  what():  failed to open /home/data/kai/projects/micromamba_test/pkgs/libgfortran5-9.3.0-he4bcb1c_17/info/files: No such file or directory
Abgebrochen (Speicherabzug geschrieben)
```
Copy from gitter chat @wolfv:

> in mamba, we actually rely on conda to detect this ...
> since we're not using conda with micromamba, we need to launch an unpack process if it isn't yet unpacked
> we could also do more validation of the unpacked contents (which we are also not doing right now), such as verifying file size and MD5 sum of the contents vs. what's expected from the package
> obviously PR's welcome :)

As a workaround for caching one can remove the tar.bz2 archives before cache creation. This will save at least some space and time for now.

**Comment by adriendelsalle** [comment]
Hi!

I can confirm that in others situations such as a process interruption when downloading and unpacking, when you will try to resume by launching again micromamba the same errors occurs: status of packages are `cached` and the linking step will just fail silently in my case.

I will add more details to reproduce soon.

**Comment by wolfv** [comment]
We've been making micromamba much more robust against these sorts of failures in the past couple of weeks, so I am confident that this is not an issue anymore.
