### ISSUE TITLE
[micromamba] strict channel prriority

### ISSUE THREAD

**Issue by beckermr** [mamba-org/mamba#613]
I am pretty sure micromamba is not respecting strict channel priority in condarc files.

**Comment by wolfv** [comment]
No, micromamba isn't yet reading the condarc file. 

You can pass --strict-priority though.

Since we have the yaml-cpp based yaml parser now, we should be able to add this functionality quite easily though.

**Comment by beckermr** [comment]
Thanks @wolfv! This command line switch works well enough for me now.

**Comment by wolfv** [comment]
sorry I think it's `--strict-channel-priority` (like conda).

**Comment by beckermr** [comment]
No worries! I wrote this in github actions in case you were not aware @wolfv. 

https://github.com/beckermr/provision-with-micromamba

Happy to move the repo to mamba-org if that is of interest to you!

**Comment by wolfv** [comment]
that's cool! 

I think it'd be great to have a github action like that under `mamba-org` :) We should be able to add some more config, right? (e.g. add a github-yaml option for the environment file to select etc.?

**Comment by beckermr** [comment]
Great! It has an `environment-yaml` option already but yeah we can def add more config. 

I'll start the transfer. Can you add me to the mamba-org so I can retain write access to the repo?

**Comment by wolfv** [comment]
yes for sure!

**Comment by beckermr** [comment]
I guess I'll the permissions to make public-repos? Github is so weird sometimes. It is giving me the error: `You don’t have the permission to create public repositories on mamba-org`

**Comment by wolfv** [comment]
hmm, can you make it private, and I'll make it public right after?

**Comment by beckermr** [comment]
I don't think so. The github docs say 

> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository

I will transfer it to you and then you can put it in mamba-org and add me as an admin to the repo afterward.

**Comment by wolfv** [comment]
Done! https://github.com/mamba-org/provision-with-micromamba

And you are an admin of that repo, too.

**Comment by beckermr** [comment]
Awesome! I updated the readme and the updates now appear on the github actions marketplace too!

**Comment by wolfv** [comment]
strict channel prio is supported, and we're working towards reading `condarc/mambrc` files in #702
