### ISSUE TITLE
[micromamba] Use of condarc ? Workaround ?

### ISSUE THREAD

**Issue by slamer59** [mamba-org/mamba#614]
Hello, 
I am using artifactory and I read that micromamba does not use condarc. 

https://github.com/mamba-org/mamba/issues/613#issuecomment-735429444

How to define other channel ? 

Regards

**Comment by wolfv** [comment]
you can define other channels from the command line (e.g. `-c conda-forge`) (or send a PR to add condarc reading to micromamba).

**Comment by slamer59** [comment]
Thanks. It works with `-c url` 

I use often the alias and never try the full url. Not sure to be at ease to do a PR.

**Comment by wolfv** [comment]
yeah, we will get there... it just takes a bit of time and love to have all the features in micromamba :)

**Comment by slamer59** [comment]
Of course. No worries ! The fact is that mamba is really great ! And micromamba is even better for dokerization. So great expectation is there ^^
