### ISSUE TITLE
[micromamba] Respect pinned file, multiple --file support in install command?

### ISSUE THREAD

**Issue by buhrmann** [mamba-org/mamba#616]
Hi, happy user of micromamba here. Just wanted to comment on a couple of issues I'm still having compared to using conda.

Allow pinning
The situation I have is that in our build system we incrementally create docker images, installing additional python dependencies in each step. Using conda that's easy, since I can easily pin the versions of base packages and know that any later packages I install won't try to update pinned packages, which applies especially to the Python version itself. With micromamba that doesn't seem to be the case, since every call of `micromamba install ...` will try to update Python to the latest version, for example. The only way around this is to specify packages I want to be "pinned" explicitly in each call to install (or requirements file), which is not very convenient.

Allow specification of multiple --file arguments
Another issue is that sometimes it would speed things up considerably (I imagine) if instead of multiple calls to install, I could install the dependencies of multiple packages (local requirement files) at the same time, so the solver will only have to be executed once. In conda this can be done with multiple --file arguments, or using something like conda-merge. Of course, this would only be practical if pip requirements were also supported in environment files (#589). Alternatively, if micromamba supported plain requirement files (non-yaml, like pip's), then it would be easy to merge them in a script. The command mentions support for "yaml", "explicit" or "plain", but it's not clear what these are (~~a pip-like file with each package on a separate line didn't seem to work, e.g.~~).

Or perhaps I'm missing some other trick to make incremental installations into the same environment with pinned specs easier and/or (even) faster?

Edit: install with basic requirements file format does work just fine.

**Comment by wolfv** [comment]
Hi @buhrmann thanks for the feedback! Yes, this part of micromamba has to be (and will be) improved.

**Comment by wolfv** [comment]
this should be fixed by #710
