### ISSUE TITLE
Revert version string parsing changes for file requirements and pinned specs

### ISSUE THREAD

**Issue by dariober** [mamba-org/mamba#622]
Hi- It seems the version string is not correctly parsed when using the `--file` arguments. For example, on a new environment, this works:

```
mamba install 'perl =5.22'
...
...
        mamba (0.7.4) supported by @QuantStack
...
Looking for: ['perl=5.22']
...
  Updating specs:

   - perl==5.22
...
  perl     5.22.2.1  0      conda-forge/linux-64     Cached
...
Confirm changes: [Y/n] 
```
----
However, if I put `perl =5.22` in `requirements.txt` and use the `--file` argument I get:

```
echo 'perl =5.22' > requirements.txt

mamba install --file requirements.txt 
...
...
Looking for: ['perl==5.22']

Encountered problems while solving.
Problem: nothing provides requested perl 5.22
```

Am I missing something?

**Comment by wolfv** [comment]
I think the `=` sign is superflous in this case `echo "perl 5.22"` should probably work. I'll check why this happens -- but I do think that we're using conda's parsing for the initial parsing here.

**Comment by wolfv** [comment]
fixed this in https://github.com/mamba-org/mamba/pull/775

**Comment by tholam** [comment]
The behavior here seems to be consistent with `conda install --file requirements.txt` from my testing just now.  Wouldn't this change break compatibility?

**Comment by wolfv** [comment]
Thanks @tholam, you're right indeed.

**Comment by tholam** [comment]
@wolfv will this be done before the next release?

**Comment by wolfv** [comment]
Yes

**Comment by wolfv** [comment]
reverted with #785
