### ISSUE TITLE
Reimplement: mamba env create -f env.yml

### ISSUE THREAD

**Issue by davidbrochart** [mamba-org/mamba#633]
Currently:
```bash
mamba env create -f env.yml
```
falls back to conda.
We could reimplement it with:
```bash
mamba create -n env_name packages_in_env.yml -c channels_in_env.yml
```
by parsing the YAML file. What do you think?

**Comment by wolfv** [comment]
the issue I can see is that this behavior does not match `conda` which (afaik) doesn't implement YAML environments under the `conda create` command.

**Comment by davidbrochart** [comment]
What I mean is that whatever the file specified after `-f` is, we get the package name, packages and channels, and use them in `mamba create`. It should be the same behavior, right?

**Comment by vv111y** [comment]
I almost exclusively create envs via `-f foo.yaml`  
Will mamba provide its functionality for this use case anytime soon?

**Comment by wolfv** [comment]
@vv111y we have the same command. It's just only the solving that is done inside mamba, everything else is done by conda in this case.

Also, we're working towards better command line interfaces in micromamba.

**Comment by vv111y** [comment]
okay so we will see some acceleration?

**Comment by akaszynski** [comment]
It would still be ideal to create directly from a file, but one alternative is to `update` an existing env:
```
mamba env update -n <your-env> --file environment.yml
```

**Comment by jucor** [comment]
Thanks @akaszynski for the solution, creating an empty environment with the right name then using mamba to update it from the `environment.yml` worked like a charm.

**Comment by vnlitvinov** [comment]
Isn't it already working as intended? I've just created a new environment running `mamba env create -f env.yml` with mamba from latest minimamba release...

**Comment by davidbrochart** [comment]
It uses mamba to solve, but conda to download and install the packages.

**Comment by janxkoci** [comment]
Sorry, but if updating an env works (with `mamba env update -n foo -f foo.yml`), what exactly is missing for `mamba env create -f foo.yml` to be fully implemented in `mamba`? Most of the relevant code (e.g. parsing yml files, mentioned in the first post) should already be in place for `env update` to work, right?

Unless `mamba env update` also uses `conda` for the actual download and installation?

**Comment by ba-tno** [comment]
Just in case it's helpful for someone: I made [a gist with a Powershell script](https://gist.github.com/ba-tno/d7165217cfc5f4279e36f3eeb206d081) which combines the `conda env create` and `mamba env update` commands.
If the script from the gist is in your PATH you can do: `mamba_create.ps1 .\environment.yml`

**Comment by nelsoncardenas** [comment]
I would like to use Mamba to replace Conda as my environment manager, but not having the option to use an environment.yml file is a significant drawback

**Comment by jonashaag** [comment]
???

**Comment by janxkoci** [comment]
@nelsoncardenas I installed **mambaforge**, where `mamba` is the default package manager, but it still also includes `conda`. In fact I'm not aware of any way of installing `mamba` that won't also give you `conda` along with it.

Personally, I use `mamba` for everything except those few things that still don't work. That's probably also why they still pack `conda` with it..

**Comment by janxkoci** [comment]
@NumesSanguis:
> When creating a VM with JupyterLab on the Google Cloud Platform, the conda base environment is already full with packages. Trying to install Mamba here results in an over 2 hour wait with the following output:

Can you try with:

```
conda install --freeze-installed -c conda-forge mamba
```

This should avoid updating/downgrading existing packages and just give you compatible mamba version (if there is such version).

**Comment by NumesSanguis** [comment]
> `conda install --freeze-installed -c conda-forge mamba`

@janxkoci Currently not on a project that this is needed, but will let you know once I've been able to test that.

**Comment by nelsoncardenas** [comment]
Sorry, I'm a new user and English is not my native language, so I can miss understand the situation. I was having problems when I was trying to create an environment because it took a lot of time.

My solution was to uninstall mamba and conda and install again conda, but I changed the default solver to be based on mamba.

**Comment by wiwa** [comment]
Extremely non-obvious that `mamba env create` falls back to `conda`. I am now using `mamba env create -f env.yml --solver=libmamba` to get around `conda` being killed.

**Comment by jjerphan** [comment]
As of mamba 2.0, mamba does not depend on conda anymore, and this issue must have been resolved.

```
mamba env create -n env_name -f env_specification.yml
```

can be used.

Can you confirm, @davidbrochart?

**Comment by jjerphan** [comment]
As of mamba 2.0, mamba does not depend on conda anymore, and this issue must have been resolved.

```
mamba env create -n env_name -f env_specification.yml
```

can be used.
