### ISSUE TITLE
[micromamba] feature request: flush output (stdout/stderr) while working so that progress becomes visible

### ISSUE THREAD

**Issue by vjmp** [mamba-org/mamba#635]
Problem: we are using micromamba inside application and capturing/passing thru outputs to users, and currently part of output gets chunked on buffer sized blocks. And that causes output tearing and also makes progress invisible as output appears only after buffer gets flushed.

Solution candidate: flushing stdout/stderr after each complete line would stop tearing and also make progress visible for end users.

**Comment by wolfv** [comment]
Are you forwarding the progress bars? Or just the `Linking package-xyz...`?

I'll look into properly flushing this.

**Comment by vjmp** [comment]
Passing thru everything that appears in stderr/stdout, no filtering, no interpreting. And no progress bars, just "progress" in that sense that there is some output happening in underlying system.
