### ISSUE TITLE
KeyError with private channel in environment.yml

### ISSUE THREAD

**Issue by sanzoghenzo** [mamba-org/mamba#637]
I deployed my quetz instance and uploaded some packages to a private channel;

Another project uses those packages, so I added them to my environment.yml file along with

```yml
channels:
  - https://conda.sws-digital.com/t/<TOKEN>/channels/stable
```

(this is until [conda#100118](https://github.com/conda/conda/issues/10018) is solved).

If I try to `mamba env create -n myenv -f environment.yml` (the same applies to `mamba update`), I get

```
Traceback (most recent call last):
  File "/home/a.ghensi/miniforge3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/home/a.ghensi/miniforge3/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/home/a.ghensi/miniforge3/lib/python3.8/site-packages/conda_env/cli/main_update.py", line 124, in execute
    result[installer_type] = installer.install(prefix, specs, args, env)
  File "/home/a.ghensi/miniforge3/lib/python3.8/site-packages/mamba/mamba_env.py", line 89, in mamba_install
    conda_transaction = to_txn(
  File "/home/a.ghensi/miniforge3/lib/python3.8/site-packages/mamba/utils.py", line 254, in to_txn
    sdir = lookup_dict[split_anaconda_token(c)[0]]
KeyError: 'https://conda.sws-digital.com/channels/stable/noarch'
```

[This is the full log](https://github.com/mamba-org/mamba/files/5716207/mamba_private_channel_error.log).

As a side note, mamba should obfuscate the token from the url in the log; I had to delete them by hand; see all the occurrences of `[...]`.

It seems that the `c.url(with_credentials=False)` [used as lookup_dict key](https://github.com/mamba-org/mamba/blob/3788c4ff2ca376bdbd50581ee261de622f5c6984/mamba/utils.py#L242) doesn't match the `split_anaconda_token(c)[0]` result.

**Comment by wolfv** [comment]
@s22chan can you take a look? I think we might have to revert your latest edit (https://github.com/mamba-org/mamba/pull/625/files)

Regarding token filtering: would be great to filter stdout automatically, but haven't had the time to properly look into that yet.

**Comment by wolfv** [comment]
conda filters tokens in this file:

https://github.com/conda/conda/blob/master/conda/gateways/logging.py

**Comment by s22chan** [comment]
that seems like an odd use case for me, since checking in your token to github (instead of injecting it via a secret into your .condarc) sounds like a security risk.

I'm fine with that since I can pin to the current version, but it's odd that mamba is parsing channels in .condarc differently than an environment.yml

**Comment by s22chan** [comment]
Also would it fix things? It looks like the key is still without the token:

> KeyError: 'https://conda.sws-digital.com/channels/stable/noarch'

**Comment by wolfv** [comment]
Hmm, I think I need to check what's going on Monday... I briefly thought this might be related to the recent changes in mamba, but this might in fact be unrelated.

**Comment by s22chan** [comment]
@sanzoghenzo can you confirm which mamba version you used to generate that log?

**Comment by sanzoghenzo** [comment]
> @sanzoghenzo can you confirm which mamba version you used to generate that log?

My bad, I was on 0.7.3; upgrading to 0.7.6 seems to have fixed that.

> that seems like an odd use case for me, since checking in your token to github (instead of injecting it via a secret into your .condarc) sounds like a security risk.

This is embarassing... I thought I must specify the channel in my environment.yml to ensure it is considered... Still learning about conda internals!
I think I'll go with the .condarc injection.
Thanks and sorry for wasting your time!

**Comment by vdsbenoit** [comment]
I have a similar issue on my computer with version 0.7.6 (and my colleague too). 

The only difference is that I try to install a package with `mamba install my_package` instead of an `environment.yml` file.

So to summarize, I have a private channel in my `.condarc` that contains a token. Let's say my `.condarc` is the following :  
````yaml
channels:
  - https://username:token@my-private-conda-repo.com/api/conda/conda
  - conda-forge
````
The package `my_package` only exists on my private channel. When I run  `mamba install my_package`, I get the following error : 
````
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 882, in exception_converter
        raise e
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 876, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 835, in _wrapped_main
        result = do_call(args, p)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 716, in do_call
        exit_code = install(args, parser, "install")
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 593, in install
        index,
      File "C:\Miniconda3\lib\site-packages\mamba\utils.py", line 254, in to_txn
        sdir = lookup_dict[split_anaconda_token(c)[0]]
    KeyError: 'https://username:token@my-private-conda-repo.com/api/conda/conda/noarch'
````
<details>
<summary>My setup info</summary>

````
  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Miniconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Miniconda3\python.exe
               CONDA_ROOT=C:\Miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\username
                     PATH=
             PSMODULEPATH=
         PYTHONIOENCODING=utf-8
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : base
    active env location : C:\Miniconda3
            shell level : 1
       user config file : C:\Users\username\.condarc
 populated config files : C:\Users\username\.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Miniconda3  (writable)
           channel URLs : https://username:token@my-private-conda-repo.com/api/conda/conda/win-64
                          https://username:token@my-private-conda-repo.com/api/conda/conda/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Miniconda3\pkgs
                          C:\Users\username\.conda\pkgs
                          C:\Users\username\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda3\envs
                          C:\Users\username\.conda\envs
                          C:\Users\username\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.7.3 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
````
</details>

**Comment by wolfv** [comment]
ok, this is not really a "token" in the conda sense, it's the Simple HTTP Auth ... but still this should work. Could you open another issue?

**Comment by vdsbenoit** [comment]
Thank you for answering! You are right. I will do that
