### ISSUE TITLE
[micromamba] fails when TMP has spaces in it

### ISSUE THREAD

**Issue by vjmp** [mamba-org/mamba#651]
This script reproduces problem in my linux. 

    #!/bin/sh
    
    export MAMBA_ROOT_PREFIX=/tmp/space
    export TMP="/tmp/spa ce"
    
    rm -rf $MAMBA_ROOT_PREFIX $TMP
    mkdir -p $MAMBA_ROOT_PREFIX $TMP
    
    echo "channels:" > $MAMBA_ROOT_PREFIX/any.yaml
    echo "- conda-forge" >> $MAMBA_ROOT_PREFIX/any.yaml
    echo "dependencies:" >> $MAMBA_ROOT_PREFIX/any.yaml
    echo "- python=3.8" >> $MAMBA_ROOT_PREFIX/any.yaml

    bin/micromamba create --strict-channel-priority -y -f $MAMBA_ROOT_PREFIX/any.yaml -p $MAMBA_ROOT_PREFIX/buggy

**Comment by vjmp** [comment]
Now it seems to fail all the time. This is error I see:

    terminate called after throwing an instance of 'std::runtime_error'
      what():  Could not read JSON repodata file (/home/user/tmp/pathing/pkgs/cache/b556ea5a.json) parse error line 1

And that file looks like this (clearly broken, just one line):

    {"_cache_control":"public, max-age=1200","_etag":"W/\"50097877e1fcb71d9a1113f5dfc023b3-13\"","_mod":"Fri, 08 Jan 2021 06:21:08 GMT","_url":"https://conda.anaconda.org/conda-forge/linux-64/repodata.json",

**Comment by wolfv** [comment]
As discussed in private there are two problems here:

- mamba does not handle file errors very well yet (fixes coming in #653)
- the temp dir did not exist. Users need to make sure that the directory exists and is writable from the mamba process (error handling will give info about this)

**Comment by wolfv** [comment]
I added better error handling/reporting to micromamba in #653.

I tested with a `tmp` that has spaces in it and it seems to work fine (as long as the TMP folder exists :)
