### ISSUE TITLE
mamba is not setting PROJ_LIB env at installation time

### ISSUE THREAD

**Issue by ReimarBauer** [mamba-org/mamba#664]
Just for documenting something I've recognized by installing MSS, see https://github.com/Open-MSS/MSS/issues/630

In short, it seems that the PROJ_LIB env is set when the `conda env` is reactivatet but not at installation time.
I can live with that and will document this in our docs.

`conda install` seems to set the env PROJ_LIB during the installation, so no reactivation is needed.

**Comment by wolfv** [comment]
thanks for the report. Indeed, that is a mamba-specific problem since the `conda`-command is actually a wrapper bash-script that calls reactivate after installing a package.

To fix this we would need to make the `mamba` command a similar bash-script. That would also fix other issues, such as #481

**Comment by wolfv** [comment]
We do have `mamba init` now that will correct this.
