### ISSUE TITLE
Add support for use_only_tar_bz2 conda flag

### ISSUE THREAD

**Issue by rs2** [mamba-org/mamba#666]
See:
* https://stackoverflow.com/a/58717064
* https://github.com/mamba-org/mamba/blob/d43f49927262b709d8da7dea13d1509583c0ae2a/mamba/utils.py#L142-L173

**Comment by wolfv** [comment]
Thanks for the bug report. Indeed one will need to modify the behavior in libsolv (add a flag) to skip those two if's: https://github.com/openSUSE/libsolv/blob/4bc791c0d235eb14bfe4c5da607206bfdfa6983d/ext/repo_conda.c#L270-L273

PR's are warmly welcome!

**Comment by tl-hbk** [comment]
@wolfv does this PR solve this issue?  https://github.com/openSUSE/libsolv/pull/434  I assume the only follow up is modifying mamba to call `repo_add_conda` with the flag if `use_only_tar_bz2` is set

**Comment by wolfv** [comment]
awesome, yes, this looks great!

**Comment by tl-hbk** [comment]
@wolfv when do you think you'll be able to release this?

**Comment by wolfv** [comment]
End of this week hopefully!
