### ISSUE TITLE
installed spake2 with mamba (in Python 3.9 env), but "module not found"

### ISSUE THREAD

**Issue by jeanmonet** [mamba-org/mamba#671]
Hi,
The following just occurred: when installing `spake2` with `mamba`, the package is not available to be imported in Python (package not found - the installation is made in a Python 3.9 environment):

```bash
Python 3.9.1 (default, Dec 11 2020, 14:32:07) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spake2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'spake2'
```

When removing and installing with `conda`, the package becomes available for import in Python. I assume it is a problem related to `mamba`.

```
# Base env:
conda                     4.9.2            py39hf3d152e_0    conda-forge
conda-package-handling    1.7.2            py39h38d8fee_0    conda-forge
mamba                     0.7.10           py39h951de11_0    conda-forge
python                    3.9.1                hdb3f193_2
```

**Comment by wolfv** [comment]
Hi, this is an issue with the metadata on conda-forge. The vesion that installed on my part was for ptyhon 2.7.

Can you check the metadata ofthe spake2 packagge? also the package "feedstock" is archived on conda-forge: https://github.com/conda-forge/spake2-feedstock/

So it's nt really maintained anymore. Please ask on conda-forge gitter - maybe you want to maintain that package?
