### ISSUE TITLE
[micromamba] Does not check if an environment exists or not

### ISSUE THREAD

**Issue by ashwinvis** [mamba-org/mamba#682]
This should be self explanatory:

```sh
avmo@archmage ~ 
$ micromamba activate this-env-does-not-exist
avmo@archmage ~ 
$                                                                                                                                                                  (this-env-does-not-exist)
avmo@archmage ~                                                                                                                                                                              
$ echo $CONDA_PREFIX                                                                                                                                               (this-env-does-not-exist)
/home/avmo/.micromamba/envs/this-env-does-not-exist
avmo@archmage ~ 
$ echo $CONDA_PROMPT_MODIFIER                                                                                                                                      (this-env-does-not-exist)
(this-env-does-not-exist) 
```

**Comment by wolfv** [comment]
yep. do you want to make a PR? would be cool to add a check!

**Comment by ashwinvis** [comment]
:sweat_smile: I don't know if I have the C++ skills to do that. It should be here right?

https://github.com/mamba-org/mamba/blob/master/include/mamba/activation.hpp

If you can give a rough guess how it should look like, I can try.

**Comment by wolfv** [comment]
This is also a good place: https://github.com/mamba-org/mamba/blob/ae61462d41df8af568f63ce450b1a9d240f712e4/src/micromamba/main.cpp#L341-L351

**Comment by ashwinvis** [comment]
@wolfv Using v0.11.3. Noticed that this behaviour is back and the guard is gone. Regression?

**Comment by ashwinvis** [comment]
Certainly looks like it was removed:

https://github.com/mamba-org/mamba/blob/48a43455e54218a676d21114965779a3298debbe/src/api/shell.cpp#L104-L115

in #824.

**Comment by wolfv** [comment]
Thanks for noticing!

**Comment by adriendelsalle** [comment]
Hi!
I removed this check after discussing with @wolfv that at some point it can be cool to activate whatever prefix.
I guess I moved too fast and if it can/could make sense to activate a non-env prefix (TDC), it's totally confusing to activate something that doesn't exists.

**Comment by ashwinvis** [comment]
I don't think there is any utility in activating an environment before it exists. It would lead to typos in `micromamba activate ...` commands  and scripts which would go undetected.

**Comment by wolfv** [comment]
yeah, we came to the same conclusion as you. Let's remove this behavior :)
