### ISSUE TITLE
mamba fails to use cached repos it the tar file has been cleaned

### ISSUE THREAD

**Issue by s22chan** [mamba-org/mamba#686]
starting with https://github.com/mamba-org/mamba/commit/d361e1e2d57b33a360314a5926b391235ac7e868

it appears that all cached packages must be extracted, but if an  environment has called `conda clean -a`, then the validation code doesn't check if the packages are already extracted and throws an EXTRACT_ERROR with the missing tar.bz2 file.

I'm not sure how you want to handle detection of extracted packages (exists? timestamp?) so it wouldn't be an obvious fix for me to implement.

**Comment by wolfv** [comment]
I think the state of this is much better now.
