### ISSUE TITLE
Support --prune flag in 'mamba install' 

### ISSUE THREAD

**Issue by LunarLanding** [mamba-org/mamba#688]
Matching changes done to channel/package specs to an environment could be done efficiently by supporting the prune flag properly; however conda env --prune [...] takes in account the history of conda install commands, and while a fix is in the works, it is taking a very long time (the issue was first reported in 2018 : https://github.com/conda/conda/issues/7279 ).
The current workaround is deleting and recreating the environment. Given how fast mamba is at solving plus caching, this works for now. In fact the only package I recall ever taking a long time to setup is jupyter, with its build step.
Either way, I wonder if it would be possible to support --prune directly in mamba install. Perhaps with a different name to not cause confusion ('-sync'?).

**Comment by ahgraber** [comment]
Does #327 enable the `--prune` flag?

**Comment by wolfv** [comment]
@LunarLanding you're mentioning `mamba install` but are you actually referring to `mamba env update`? Because I cannot really see how we'd prune with a regular install.

For `mamba env update` we could implement a prune flag which would basically just re-solve the environment from scratch, removing all packages that are there.

**Comment by LunarLanding** [comment]
@ahgraber  sorry haven't had the time to test it yet.
@wolfv either needs a source of truth, yes.

I mentioned `mamba install` because at some point I was using it for its different behavior regarding respecting channels in specs; I fed it the environment spec via arguments; but that's a different unrelated issue. 
For `mamba env` the source of truth would come from `--file environment.yml`.

The process would be as you say: resolve environment to get a package spec (fast), leave already installed packages as is, remove those not in the spec, install the ones that are not present in the installation.

**Comment by LunarLanding** [comment]
@ahgraber  I just tested. Removing a package with no dependencies from the environment file and then running `mamba env update --prefix $PREFIX --file environment.yml --prune` does not uninstall it.

**Comment by wolfv** [comment]
@LunarLanding we haven't worked on this yet.

You're welcome to give this a hand! I think it shouldn't be too hard to add that flag to `mamba_env.py` -- just resolve the entire environment.

**Comment by LunarLanding** [comment]
@wolfv  thanks for the clarification, it's understandable; and thanks for the pointer, I initally thought I would have to touch the C implementation, but if it's doable via python then I'll try it.
