### ISSUE TITLE
[micromamba] additional robustness improvements

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#696]
#### environments

- [x] whenever some other process modifies the environment, it should be locked down
- [x] flag to check if there are additional / missing files / SHA256 match in environment
- [ ] Windows: before doing anything, try to rename environment? If renaming fails, we know that there is a file lock somewhere

#### packages cache

- [x] lightweight checks & removal (currently SHA256 is always checked)
- [ ] record hash of files in package directory: suggestion to hash file name, file size, modification date of all files under `pkgs/mypkg-0.1.0-blabla/` (that would include info files). This hash would be stored in the `info/` dir
- [x] lock files: whenever a tar.bz2 file is downloaded and scheduled for extraction, we should add a lock file with the name of the file + PID of the locking process. This is quite challenging as we also need to wait for the extraction & release of the file lock

**Comment by mariusvniekerk** [comment]
i've been using regular old python filelock to prevent package cache corruption

**Comment by wolfv** [comment]
A global lock for the entire cache folder? I've been thinking a lock per package name would be cool (also a bit more engineering...)
