### ISSUE TITLE
libcurl certificate revocation checks break conda compatibility in restricted network scenarios

### ISSUE THREAD

**Issue by mparry** [mamba-org/mamba#697]
I've been evaluating mamba as a drop-in conda replacement for our internal usage and so far it looks great. However, there's one problem that I've run into where on many of our servers, that have no internet access, repository connections fail due to failed certificate revocation checks. (We have internal conda repo proxies/mirrors configured, so the servers can connect to those, but not anything outside, including revocation servers.)

Would it be possible to either a) disable these checks entirely, which would arguably offer maximum compatibility with conda, or b) at least provide an option to disable them?

**Comment by mparry** [comment]
Note that this is very straightforward to do:

```cpp
curl_easy_setopt(handle, CURLOPT_SSL_OPTIONS, CURLSSLOPT_NO_REVOKE);
```

I'd be happy to open a PR for option a, if that's acceptable.

**Comment by wolfv** [comment]
Hi @mparry indeed, I haven't run across this one yet. 

Would be great if you can open a PR. Maybe we add this as an option for `--ssl-verify`? 

e.g. `--ssl-verify no-revoke`?

**Comment by mparry** [comment]
I guess it depends what you're aiming for with mamba exactly. If you want it to work as closely as possible to conda out of the box then, since conda / requests don't do these checks at all, I think it should just be turned off by default (maybe with an option to re-enable it).

**Comment by tl-hbk** [comment]
This is something I'd like to see added as well.

@wolfv I was wondering if you had any thoughts on @mparry's last comment about conda not doing these checks or if you'd prefer to keep these checks as an option if there should be a different way other than `ssl-verify` since I'm under the impression that that would prevent passing a custom cacert bundle.

**Comment by wolfv** [comment]
thanks @tl-hbk for fixing this. @mparry once the next release of mamba/micromamba is out, you can use the env var `MAMBA_SSL_NO_REVOKE=1` to disable revocation checking.
