### ISSUE TITLE
[bug] nothing provides __osx >=10.10 needed by [pkg] when creating from file

### ISSUE THREAD

**Issue by simone-pignotti** [mamba-org/mamba#698]
Hi,

I believe the creation of an environment from a YAML file has a little bug, at least on MacOS. Running `mamba env create -f env.yml` with the following content:
```
name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - python-kaleido
```
returns:
```
conda-forge/osx-64       Using cache
conda-forge/noarch       Using cache
pkgs/main/osx-64         Using cache
pkgs/main/noarch         Using cache

Looking for: ['python-kaleido']

Encountered problems while solving.
Problem: nothing provides __osx >=10.10 needed by kaleido-core-0.1.0-h35c211d_0
```
while `mamba create -n test python-kaleido`, which should be equivalent since I have the same channel priorities in my `~/.condarc`, completes successfully.

Is anyone able to replicate this?

Thanks!
Simone

**Comment by simone-pignotti** [comment]
PS `conda env create -f env.yml` works!

**Comment by wolfv** [comment]
Hi @simone-pignotti I believe this was recently fixed (this PR https://github.com/mamba-org/mamba/pull/661). What mamba version are you on?

**Comment by simone-pignotti** [comment]
Hi @wolfv, thanks it works with the latest mamba release (I was on 0.7.8, I should have updated before opening this sorry!).

**Comment by wolfv** [comment]
No worries.

Cheers!
