### ISSUE TITLE
"Cannot remove directory" error shouldn't terminate the process

### ISSUE THREAD

**Issue by zbs** [mamba-org/mamba#699]
I'm using mamba to create an environment
```
mamba env create -f config.yml -p mamba_env python=3.8
```
but it fails with 
```
Caught a filesystem error: Read-only file system: '/conda_install/pkgs/<packageName>-main'
```

The `pkgs` cache is read-only, and I don't have write access:

- I think the script shouldn't terminate on that error; it doesn't need to clean things up in order to create a directory
- Is there a workaround I can use in the meantime? Perhaps bypassing the cache altogether?
- I think it would be great if this behavior could be suppressed with a flag when desired (e.g. `--skipInvalidDirRemoval`)

**Comment by wolfv** [comment]
@zbs yes, you can use the previous mamba version. I am fixing that.
