### ISSUE TITLE
[Feature request/RFC] Resolve conda envs in parallel

### ISSUE THREAD

**Issue by abhi18av** [mamba-org/mamba#706]
Hi Mamba team,

Thanks for the wonderful initiate!

I was wondering whether using `mamba` it'd be possible to resolve conda environments in parallel. From a preliminary experimentation here  (Credit - Gregor Sturm https://github.com/nextflow-io/nextflow/issues/1819#issuecomment-783505784) 

-    clean conda cache
```
conda clean -af
```
-  run in two terminal windows in parallel

```
mamba create -n test-mamba2 python=3.8 star rsem fastqc gatk

mamba create -n test-mamba1 python=3.7 star rsem fastqc gatk
```

-    Error message:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  truncated bzip2 input
zsh: abort (core dumped)  mamba create -n test-mamba2 python=3.8 star rsem fastqc gatk
```

I'm initiating a conversation here to see if you could guide us towards a solution using `mamba`?

**Comment by wolfv** [comment]
Hi @abhi18av thanks for filing this issue. 

Indeed, we're also looking at more "stability improvements" here https://github.com/mamba-org/mamba/issues/696

This feature requires "locking" of either the `pkgs` directory, or the packages in that directory. 

Locking the entire `pkgs` directory with a lockfile should be quite straight-forward to implement. Locking single packages would be harder.

**Comment by abhi18av** [comment]
Thanks for the quick revert @wolfv !

> Locking the entire pkgs directory with a lockfile should be quite straight-forward to implement. 

Hmm, interesting way to approach this. Allow me to highlight one of the scenarios which would affect our use case.

In Nextflow, users often end up running hundreds of tool and therefore, possibly creating and using `conda` envs in parallel. Do you think that due to the locking of `pkgs` by one of these `conda/mamba` processes, it might end up causing some of these to fail due to timeout?

**Comment by wolfv** [comment]
I don't know how large these environments are and how long the timeouts are so I can't judge on this. But yes, it's very much possible that things time out if there are low timeouts.

**Comment by wolfv** [comment]
Is this something you're seeing? timeouts?

**Comment by abhi18av** [comment]
Yup, this env creation get timed out. 

Probably because often there's a bigger dependency trail behind the bioinformatics tools hosted by the popular bioconda project http://bioconda.github.io/

**Comment by wolfv** [comment]
Merging this into #739

**Comment by abhi18av** [comment]
Happy to see this moving forward! Thanks @wolfv
