### ISSUE TITLE
Update README to explain base env installation requirement

### ISSUE THREAD

**Issue by ralexx** [mamba-org/mamba#708]
I would like to submit a simple PR to make this point (https://github.com/mamba-org/mamba/issues/631#issuecomment-744407332) explicit in the docs.

It's not immediately apparent that mamba *must* be installed into the `base` Conda env. I was also caught by the same `mamba env update -n foo -f bar.yml` gotcha as #631, because experience has taught me the hard way that I should keep my base env as minimal as possible.

**Comment by wolfv** [comment]
Yes, that would be greatly appreciated!
You could also add it to the docs (rendered at mamba.readthedocs.io)

**Comment by ralexx** [comment]
> You could also add it to the docs (rendered at mamba.readthedocs.io)

Thanks, will do. I will mark as WIP meanwhile.
