### ISSUE TITLE
mamba should be able to create environment

### ISSUE THREAD

**Issue by antonkulaga** [mamba-org/mamba#724]
I believe one of the main use-cases of conda is setting up the environment from the manually written environment.yaml files (cause automatically generated are often trash), often containing many dependencies. Without the support to create environment.yaml by mamba the benefits of mamba are quite limited to console commands.

**Comment by antonkulaga** [comment]
ups, did not notice that you already have minimamba

**Comment by wolfv** [comment]
yes, you can create environments from `yaml` files with `mamba env create -f myfile.yml`.
