### ISSUE TITLE
Constraint ignored by solver

### ISSUE THREAD

**Issue by tl-hbk** [mamba-org/mamba#725]
Constraints in the format `foo=*.dev` are being ignored by the solver.  The `MatchSpec` appears to match conda so I'd assume the problem is wherever the versions are checked to see if they match the specs provided.

```
>>> from conda.models.match_spec import MatchSpec
>>> ms = MatchSpec("foo=*.dev")
>>> ms.conda_build_form()
'foo *.dev*'
```

```
MatchSpec ms("foo=*.dev")
EXPECT_EQ(ms.conda_build_form(), "foo *.dev*")
```

**Comment by wolfv** [comment]
Hi @tl-hbk thanks for filing an issue.

Can you give me some more details on what you're trying to do and how?

Are you referring to "run-constrains" or to "requirements"?

Are you trying to install a package using `mamba install "foo=*.dev"`?

**Comment by wolfv** [comment]
When using repoquery (which should use the same mecahnism as installing) I do get some results for this query:

`mamba repoquery search "*=*dev"`

**Comment by tl-hbk** [comment]
I'm trying to install some packages using some internally hosted channels in addition to the main anaconda channels.  For some packages like `certifi` I have a patched version with `.dev` appended at the end but when I do something like `mamba create certifi=*.dev` it picks up a version that doesn't end with `.dev`

`mamba repoquery search "*=*dev"` also picks up several packages that don't end with `.dev` when I run it

**Comment by tl-hbk** [comment]
Just leaving an update on this issue.  For some reason the same issue is not reproduceable on my personal computer using the anaconda defaults and conda-forge.  Will need to investigate further though because the environment I initially tested this one vs my personal computer are pretty different (linux vs windows, self hosted channels vs not, possibly different set of packages in environment too)

**Comment by tl-hbk** [comment]
@wolfv not too familiar with c so please let me know if I made any mistakes here but it looks like the regex polyfill isn't working properly on windows in libsolv.  I tested the `regexmatch` function in `conda.c` and it seems like everything returns a match on windows while it works as expected on linux.

```
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <regex.h>

#include "util.h"

static int
regexmatch(const char *evr, const char *version, size_t versionlen, int icase)
{
  regex_t reg;
  char *buf = solv_malloc(versionlen + 1);
  int r;

  memcpy(buf, version, versionlen);
  buf[versionlen] = 0;
  if (regcomp(&reg, buf, REG_EXTENDED | REG_NOSUB | (icase ? REG_ICASE : 0)))
    {
      solv_free(buf);
      return 0;
    }
  r = regexec(&reg, evr, 0, NULL, 0);
  regfree(&reg);
  solv_free(buf);
  return r == 0;
}

int
main(int argc, char **argv)
{
    char* evr = "2020.03.04";
    char* version = ".*\\.dev.*";
    int res = regexmatch(evr, version, strlen(version), 0);
    fprintf(stderr, "regexmatch: %d\n", res);
    exit(0);
}
```

**Comment by wolfv** [comment]
Hi @tl-hbk thanks for finding this issue! I think you're right. We need to look into this polyfill and if we're using it wrongly.

Do you want to file an issue with libsolv?

**Comment by tl-hbk** [comment]
Sure I'll create it

**Comment by mlschroe** [comment]
This happens because of:
```
typedef size_t regoff_t;               // regex.h
regoff_t match_eo = -1;              // regexec.c
if (match_eo < 0)                        // later
```
As size_t is unsigned, the if statement is always wrong leading to an immediate match.

@wolfv : you imported the regex code, why does this work in the original?

**Comment by wolfv** [comment]
yep @mlschroe I am taking full responsibility here, sorry! I need to check what's going on, thanks for looking into this.

**Comment by wolfv** [comment]
ok, so I think when I took this file from musl-c I defined regoff_t myself (since it's probably not defined otherwise) and messed this up. We could try to define it as a signed integer and add one or multiple tests to libsolv. 
The original define that I should have looked at is here: https://github.com/ifduyue/musl/blob/a5aff1972c9e3981566414b09a28e331ccd2be5d/include/alltypes.h.in#L7-L10

**Comment by mlschroe** [comment]
Musl uses ssize_t instead of size_t for regoff_t, see alltypes.h:
```
TYPEDEF unsigned _Addr size_t;
...
TYPEDEF _Addr ssize_t;
...
TYPEDEF _Addr regoff_t;
```

**Comment by wolfv** [comment]
yep. my mistake.

**Comment by tl-hbk** [comment]
@wolfv are you creating a PR with the fix or should I do so?  I tested changing the typedef to `typedef long regoff_t;` and it seems to be working now.

**Comment by wolfv** [comment]
please go for it! Thanks!

**Comment by wolfv** [comment]
Thanks for fixing this in libsolv. I am going to close it here and we'll be waiting for a libsolv release. We can also patch the libsolv on conda-forge if no release shows up soon (http://github.com/conda-forge/libsolv-feedstock) cc @mlschroe should we patch or wait?
