### ISSUE TITLE
[micromamba] clean command fails when only base environment exists

### ISSUE THREAD

**Issue by phue** [mamba-org/mamba#726]
Hi,
when using the latest [micromamba-docker](https://hub.docker.com/r/mambaorg/micromamba) base image, I noticed that the `micromamba clean` command throws an error if packages are installed in the `base` environment only, presumably because it expects `/opt/conda/envs` to exist.

```
Singularity> micromamba clean
Cleaning up ...
ERROR   No such file or directory: '/opt/conda/envs'
```

**Comment by wolfv** [comment]
Thanks, yep, looks like an issue! PR's would be welcome.
