### ISSUE TITLE
Document feature compatibility between conda, mamba and micromamba

### ISSUE THREAD

**Issue by buhrmann** [mamba-org/mamba#738]
Hi, so I was getting confused about which package manager (and which specific command) supports which type of package specifications. As a result I created the below table. Perhaps something similar but extended might be useful to document about mamba/micromamba, to make it easier to identify any necessary changes when moving between them? And also to keep it updated as micromamba receives new features e.g.

Contrary to my impression, the table seems to suggest that `mamba`  is in fact a drop-in replacement for `conda`, exactly copying its API and features; while micromamba departs from that common API and feature set.

For reference, I was comparing conda 4.9.2, mamba 0.7.14, and micromamba 0.7.1:

| Feature     | conda create | conda install | conda update | conda env create | conda env update | mamba create | mamba install | mamba update | mamba env create | mamba env update | µmamba create | µmamba install | µmamba env create |
|-------------------|---|---|---|---|---|---|---|---|---|---|---|---|---|
|cmd line specs     | ✓ | ✓ | ✓ |   |   | ✓ | ✓ | ✓ |   |   | ✓ | ✓ | ✓ |
|plain spec file    | ✓ | ✓ | ✓ |   |   | ✓ | ✓ | ✓ |   |   |   |   |   |
|yml spec file      |   |   |   | ✓ | ✓ |   |   |   | ✓ | ✓ | ✓ | ✓ | ✓ |
|multiple spec files| ✓ | ✓ | ✓ |   |   | ✓ | ✓ | ✓ |   |   |   |   |   |
|allows pip specs   |   |   |   | ✓ | ✓ |   |   |   | ✓ | ✓ |   |   |   |
|mamba solver       |   |   |   |   |   | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ | ✓ |
|respects pinned specs|   | ✓ | ✓ |   | ✓ |   | ✓ | ✓ |   | ✘ |   |   |  |

## Notes

- `conda` and `mamba`:
  - `mamba` always uses the same API as `conda`, accepting the same type of inputs (cmd line args/files)
  - while `mamba install` respects pinned specs, `mamba env update` does not 
- `mamba` and `micromamba`
  - Both use the mamba solver always, i.e. no fallback to conda (?)
- `micromamba`
  - Accepts conda-structured yaml files _without_ pip dependencies in all commands
  - Has no `update` or `env update` command
  - Mentions support for multiple files in https://github.com/mamba-org/mamba/issues/509, but as of 0.7.14 this doesn't seem to work. ("ERROR   Can only handle 1 yaml file!")
  - Doesn't respect pinned specs in the `conda-meta/pinned` file

Edit

- Corrected the fact that `mamba install` respects pinned specs, but `mamba env update` does not.

**Comment by wolfv** [comment]
Yeah, this is cool! Thanks for doing this work.

yes, mamba and micromamba always use libsolv for solving.

- `update` is coming to micromamba with the next release
- multiple files are supported (but only for explicit or simple spec-files (not yaml))
- pinned packages support is also coming
- virtual package support (__osx, __glibc, ...) is also coming with the next micromamba release

So the "gap" is hopefully closing rapidly for micromamba. But yeah, some interfaces are changing slightly with micromamba, hopefully for the better. Especially we don't want the separation between `conda create` and `conda env create`.

**Comment by buhrmann** [comment]
I think I already noticed a mistake in the table. It seems that while `mamba install ...` _does_ respect the pinned file, `mamba env update` _does not_, is that the expected result?

```
mamba create -n test -c conda-forge python=3.7.6 pip=20.2 nomkl
conda activate test
echo "pandas=1.0.5" > ~/miniforge3/envs/test/conda-meta/pinned
echo "dependencies:\n- pandas" > reqs.yml
mamba env update --file reqs.yml
```

```
Transaction

  Prefix: /home/thomas/miniforge3/envs/test2

  Updating specs:

   - pandas


  Package          Version  Build                Channel                    Size
──────────────────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────────────────

  libblas            3.9.0  8_openblas           conda-forge/linux-64     Cached
  libcblas           3.9.0  8_openblas           conda-forge/linux-64     Cached
  libgfortran-ng     7.5.0  h14aa051_18          conda-forge/linux-64      22 KB
  libgfortran4       7.5.0  h14aa051_18          conda-forge/linux-64       1 MB
  liblapack          3.9.0  8_openblas           conda-forge/linux-64     Cached
  libopenblas       0.3.12  pthreads_hb3c22a3_1  conda-forge/linux-64       8 MB
  numpy             1.20.1  py37haa41c4c_0       conda-forge/linux-64     Cached
  pandas             1.2.3  py37hdc94413_0       conda-forge/linux-64     Cached
  python-dateutil    2.8.1  py_0                 conda-forge/noarch       Cached
  pytz              2021.1  pyhd8ed1ab_0         conda-forge/noarch       Cached
  six               1.15.0  pyh9f0ad1d_0         conda-forge/noarch       Cached

  Summary:

  Install: 11 packages

  Total download: 9 MB

```

while calling `mamba install pandas` instead results in

```
Transaction

  Prefix: /home/thomas/miniforge3/envs/test3

  Updating specs:

   - pandas


  Package          Version  Build                Channel                    Size
──────────────────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────────────────

  libblas            3.9.0  8_openblas           conda-forge/linux-64     Cached
  libcblas           3.9.0  8_openblas           conda-forge/linux-64     Cached
  libgfortran-ng     7.5.0  h14aa051_18          conda-forge/linux-64     Cached
  libgfortran4       7.5.0  h14aa051_18          conda-forge/linux-64     Cached
  liblapack          3.9.0  8_openblas           conda-forge/linux-64     Cached
  libopenblas       0.3.12  pthreads_hb3c22a3_1  conda-forge/linux-64     Cached
  numpy             1.20.1  py37haa41c4c_0       conda-forge/linux-64     Cached
  pandas             1.0.5  py37h0da4684_0       conda-forge/linux-64     Cached
  python-dateutil    2.8.1  py_0                 conda-forge/noarch       Cached
  pytz              2021.1  pyhd8ed1ab_0         conda-forge/noarch       Cached
  six               1.15.0  pyh9f0ad1d_0         conda-forge/noarch       Cached

  Summary:

  Install: 11 packages

  Total download: 0  B
``` 

I'll update the table above...

**Comment by LunarLanding** [comment]
I know for a fact that pinning `mypackage` to a `mychannel` channel, while this package has a more recent version in `otherchannel`  and running `mamba update --override-channels -c [otherchannel] mychannel::mypackage` gets mypackage from `otherchannel`.
If instead `mamba install ...` is used, `mypackage` is correctly pulled from `mychannel`.
This with mamba 0.12.0 and conda 4.10.1.
So I would remove the checkmark in 'respect pinned specs' for both mamba update and conda update.
