### ISSUE TITLE
[micromamba] solver not finding noarch packages 

### ISSUE THREAD

**Issue by wholtz** [mamba-org/mamba#772]
```
$ podman run -it --rm mambaorg/micromamba:0.8.2
(base) root@91221effb733:/# micromamba install -c anaconda pyopenssl=20.0.1

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

anaconda/noarch          [====================] (00m:00s) Done
anaconda/linux-64        [====================] (00m:00s) Done

Encountered problems while solving.
Problem: nothing provides requested pyopenssl 20.0.1**

ERROR   Could not solve for environment specs
(base) root@91221effb733:/#
```
The same install command works for miniconda and mamba. Version 20.0.1 of pyopenssl on anaconda is only available as a noarch package and there are arch packages for older versions.  Changing the version constraint to 19.1.0 allows the solver to find a solution with a linux-64 package.

**Comment by wolfv** [comment]
thanks for the bug report. Indeed an interesting find. One other potential issue source could be the existence of a `.conda` package for pyopenssl which should be preferred over the `.tar.bz2` package...

**Comment by wolfv** [comment]
hmm, the issue has to be a different one. If I use `https://repo.anaconda.com/pkgs/main` directly, it works fine.

Same for `-c defaults` 

And also for `-c main`

I think `anaconda` might be the deprecated channel? Is `-c anaconda --override-channels` working for conda / mamba?

**Comment by wolfv** [comment]
If you take a look at this repodata.json (https://conda.anaconda.org/anaconda/noarch/repodata.json) it actually doesn't contain that version of pyopenssl.

I think you want `-c defaults`.
