### ISSUE TITLE
Mamba not respecting pinning of MKL-blas libraries

### ISSUE THREAD

**Issue by dchandan** [mamba-org/mamba#776]
I have created a new environment with mkl-blas libraries:

> name: resc21
> channels:
>   - conda-forge
>   - defaults
> dependencies:
>   - "libblas=*=*mkl"
>   - numpy
>   - scipy

which installs MKL optimized blas libraries:
> libblas                   3.9.0                     8_mkl    conda-forge
> libcblas                  3.9.0                     8_mkl    conda-forge

Now, to pin the mkl libraries I added the following to the "pinned" file in the conda-meta directory of the new environment:
libblas[build=*mkl]

Now if I do: `conda update --all --dry-run` then no updates are indicated, but with `mamba update --all --dry-run` I receive the following output wherein it wants to upgrade my pinned packages:

>  No specs added or removed.
>
>  Package           Version  Build              Channel                  Size
>───────────────────────────────────────────────────────────────────────────────
>  Install:
>───────────────────────────────────────────────────────────────────────────────
>
>  libopenblas        0.3.12  openmp_h54245bb_1  conda-forge/osx-64       9 MB
>
>  Change:
>───────────────────────────────────────────────────────────────────────────────
>
>  libblas             3.9.0  8_mkl              installed
>  libblas             3.9.0  8_openblas         conda-forge/osx-64      11 KB
>  libcblas            3.9.0  8_mkl              installed
>  libcblas            3.9.0  8_openblas         conda-forge/osx-64      11 KB
>  libedit      3.1.20191231  h0678c8f_2         installed
>  libedit      3.1.20191231  hed1e85f_2         conda-forge/osx-64     103 KB
>  liblapack           3.9.0  8_mkl              installed
>  liblapack           3.9.0  8_openblas         conda-forge/osx-64      11 KB
>  tk                 8.6.10  h0419947_1         installed
>  tk                 8.6.10  hb0a8c7a_1         conda-forge/osx-64       3 MB
>
>  Summary:
>
>  Install: 1 packages
>  Change: 5 packages
>
>  Total download: 12 MB

I do not understand why mamba is not respecting pinning of packages like conda.

**Comment by wolfv** [comment]
Hi, I've been improving this situation yesterday.

Pinning `libblas=*=*mkl` works for me, locally! 
You might have to wait for the next release, but the fixes are on master.
