### ISSUE TITLE
OS X Big Sur / M1 first-run issues

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#780]
So, I tested micromamba on OS X Big Sur with an M1 chip.

Following discoveries:

/usr/bin/codesign exists and works, even on a vanilla system.

After installing Xcode, it stops working. It wants you to read licenses, and sign them. However, that only works with sudo (it does show the license). At the end of the license text, there is a hint: 

```
Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.
```

Running that command with sudo works, and let's me agree to the license which makes micromamba functional again. 
I wonder if we can detect the presence of xcodebuild and wether the license has been signed or not ...

**Comment by wolfv** [comment]
This here is a way to figure out if the license for the Xcode version installed is already accepted: https://stackoverflow.com/a/60906147

**Comment by chrisburr** [comment]
Interesting. I've never installed XCode only the "command line tools" so that might need some separate consideration when checking.

I've not yet managed to reproduce the issue I reported on Gitter but I'll report back if/when I do.

**Comment by jakirkham** [comment]
Did you open the Xcode app? It will go through approvals and offer to install command line tools.

**Comment by wolfv** [comment]
In my case I did not open the Xcode app before running mamba.

**Comment by chrisburr** [comment]
After another macOS update I'm having issues again with signatures being invalid and the binaries being killed as a result. I currently have the [Command Line Tools uninstalled](https://developer.apple.com/library/archive/technotes/tn2339/_index.html#//apple_ref/doc/uid/DTS40014588-CH1-HOW_CAN_I_UNINSTALL_THE_COMMAND_LINE_TOOLS_) and I have never installed XCode on this machine.

```
(base) christopherburr@christophers-mac-mini ~ % codesign -s - -f /Users/christopherburr/mambaforge/bin/fish
/Users/christopherburr/mambaforge/bin/fish: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Users/christopherburr/mambaforge/bin/fish: the codesign_allocate helper tool cannot be found or used

(base) christopherburr@christophers-mac-mini ~ % which codesign_allocate
/usr/bin/codesign_allocate
(base) christopherburr@christophers-mac-mini ~ % codesign_allocate
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

After poking around for a while I gave up and ran `xcode-select --install` which fixed the issues again. Hopefully this is all just a weird quirk of my system.

**Comment by chrisburr** [comment]
Actually I've made some progress this time, code signing seems to be checking for the existence of `/Library/Developer/CommandLineTools` and for some reason there was a junk file left lying around:

```bash
~ % ls /Library/Developer/CommandLineTools
usr
~ % ls /Library/Developer/CommandLineTools/usr
share
~ % ls /Library/Developer/CommandLineTools/usr/share/man/whatis
/Library/Developer/CommandLineTools/usr/share/man/whatis
```

Testing by explicitly deleting the directory and recreating it reproduces the issue:

```bash
~ % sudo rm -rf /Library/Developer/CommandLineTools
~ % codesign -s - -f /Users/christopherburr/mambaforge/bin/fish
/Users/christopherburr/mambaforge/bin/fish: replacing existing signature
/Users/christopherburr/mambaforge/bin/fish: signed Mach-O thin (arm64) [fish-555549442d2f7b18870a3059a8a8d2ac8c8056df]

~ % sudo mkdir /Library/Developer/CommandLineTools
~ % codesign -s - -f /Users/christopherburr/mambaforge/bin/fish
/Users/christopherburr/mambaforge/bin/fish: replacing existing signature
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
/Users/christopherburr/mambaforge/bin/fish: the codesign_allocate helper tool cannot be found or used

~ % sudo rm -rf /Library/Developer/CommandLineTools
~ % codesign --verbose=10000 -s - -f /Users/christopherburr/mambaforge/bin/fish
/Users/christopherburr/mambaforge/bin/fish: replacing existing signature
/Users/christopherburr/mambaforge/bin/fish: signed Mach-O thin (arm64) [fish-555549442d2f7b18870a3059a8a8d2ac8c8056df]
```

**Comment by chrisburr** [comment]
For reference, the initial Gitter discussion was at: https://gitter.im/conda-forge/conda-forge.github.io?at=604cc2e15d0bfb4e58a8083c

cc @chenghlee as you were active in the previous code signing discussion

**Comment by jonashaag** [comment]
Closing as stale.
