### ISSUE TITLE
provide way to customize folder for micromamba shell init

### ISSUE THREAD

**Issue by antonkulaga** [mamba-org/mamba#782]
micromamba shell init writes everything to the ~/ folder while in many cases it is not the best place to install micromamba. For instance, in my case I have a separate disk for heavy stuff, so I would like to install micromamba there instead of the home folder and editing .bashrc by hand is time consuming

**Comment by wolfv** [comment]
If you add -p /some/path that should work

**Comment by wolfv** [comment]
@antonkulaga can you check if `micromamba shell init -s whatever -p /my/prefix` works for you? That should add the root prefix wherever you want it
