### ISSUE TITLE
*Incorrect* solver error message

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/mamba#784]
Just following on from my issue on gitter - https://gitter.im/QuantStack/Lobby?at=605738c528e6153d72338884

After fixing my mis-specified version which `mamba` did warn me about I'm seeing an issue whereby `mamba` complains about a package which ***is*** definitely available:
```
Encountered problems while solving.
Problem: package mypackage-0.3.1.post025+3adfea4-0 requires msal >=1.10.0, but none of the providers can be installed
```
```
> mamba search msal --platform='linux-64' | rg 1.10.0
msal                          1.10.0    pyh44b312d_0  conda-forge
```
`conda-forge` is in my channel list `msal=1.10.0` is on `conda-forge` so it seems the error message is just incorrect?

**Comment by dhirschfeld** [comment]
I'm just opening this a a data-point for #770 but didn't want to clutter that issue up with an un-reproducible bug report. Unfortunately this is from a huge environment so it will be difficult to create a repro.

**Comment by wolfv** [comment]
I think this error can happen when msal requires a package that conflicts with a package that mypackage requires (or somewhere else in the dependency tree).

E.g. maybe mypackage requires python=2.7 and msal requires python >=3.6

**Comment by dhirschfeld** [comment]
Yeah - I figured but there's no info about what's *actually* conflicting so there's not much you can do with the info.

When I removed `msal`, `mamba` then complained about another package which was available and so on for several packages before I gave up, started from a clean slate and only added one package at a time until I found the one that caused the issue. Turns out it was `sktime`.

I'm not sure what about it conflicts, but it does have some complex deps:
```
> mamba search --info --platform="linux-64" sktime=0.5.3

sktime 0.5.3 py37hcd2ae1e_0
---------------------------
file name   : sktime-0.5.3-py37hcd2ae1e_0.tar.bz2
name        : sktime
version     : 0.5.3
build       : py37hcd2ae1e_0
build number: 0
size        : 3.9 MB
license     : BSD-3-Clause
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/sktime-0.5.3-py37hcd2ae1e_0.tar.bz2
md5         : 5aa116827869a84fc79f598b8a055c8a
timestamp   : 2021-02-06 14:23:03 UTC
constraints :
  - hcrystalball >=0.1.9
  - tsfresh >=0.17.0
  - fbprophet >=0.7.1
  - scikit-posthocs >=0.6.5
  - matplotlib >=3.3.2
  - stumpy >=1.5.1
  - seaborn >=0.11.0
dependencies:
  - libgcc-ng >=9.3.0
  - libstdcxx-ng >=9.3.0
  - numba >=0.50,<0.53
  - numpy >=1.19.5,<2.0a0
  - pandas >=1.1.0,<1.2
  - python >=3.7,<3.8.0a0
  - python_abi 3.7.* *_cp37m
  - scikit-learn >=0.23.0
  - statsmodels >=0.12.1
```

Anyway, I'm happy for this to be closed - I just thought I'd post an example of a particular failure mode where the error message doesn't help. I'm not sure what can be done to improve that though - I think it's a very difficult problem to solve.

**Comment by dhirschfeld** [comment]
Trying to install one of the problematic packages after the fact and I got the below error message:
```
Encountered problems while solving.
Problem: nothing provides comtypes needed by mypackage-0.1.0.post001+26e46d1-0
```
...which is strange since this is on linux and `comtypes` is Windows only 🤔 


Anyway, through some trial end error I found the problem was that `mypackage` required `pyjwt>=2.0` but `msal` required `pyjwt<2.0`:
```
$ mamba install 'pyjwt>=2.0'
Encountered problems while solving.
Problem: package msal-1.10.0-pyh44b312d_0 requires pyjwt >=1.0.0,<2, but none of the providers can be installed
```

`pyjwt` is a top-level dependency of both `mypackage` and `msal` so it would have been ideal if that top-level conflict could have been reported directly.

When an environment is unsolvable there are a likely a huge (~infinite?) number of inconsistent solutions. I'm wondering if there isn't a way to order the solutions where inconsistencies in top-level dependencies matter at lot more than inconsistencies in dependencies of dependencies so that those top-level conflicts can get reported to the user?

Obviously easy to say but I'm sure it's very difficult to do (if even possible).

**Comment by calebmarchent** [comment]
Adding to the incident reports: 

Am seeing similar issues of `package python-3.6.13-hffdb5ce_0_cpython requires openssl >=1.1.1j,<1.1.2a, but none of the providers can be installed`, where I have `openssl=1.1.1k=h7f98852_0`. I have playing "guess the dependency", which is quite time-consuming, so would love it if someone could resolve.

**Comment by wolfv** [comment]
I am closing this in favor of #770 where this is referenced. We already have some initial work going on in https://github.com/mamba-org/mamba/pull/1424
