### ISSUE TITLE
Feature request: add support for conda build

### ISSUE THREAD

**Issue by astrofrog** [mamba-org/mamba#79]
A common case where I run into issues where the mamba conflict resolution is super useful is when trying to diagnose issues with ``conda build``. However, for now I have to translate a conda recipe into a ``mamba create`` or ``mamba install`` command. It would be great if it would be possible to call ``mamba build``, which would then use mamba any time dependencies have to be installed (and deferring to conda for the rest). Feel free to close if this is not technically possible though!

**Comment by wolfv** [comment]
yes, i would totally love this (also because I thikn conda-build _could_ be faster).

but i am not sure how feasible it is... need to dig into conda-build source code.

**Comment by wolfv** [comment]
Hi @astrofrog 

work has started over at http://github.com/thesnakepit/boa for the conda-build replacement.

We are also working to define a next-gen `meta.yaml` spec: https://hackmd.io/@v-Cm_WlESpm7ernkHnMMyg/H1lduuqjL and would be happy to hear your opinions!

**Comment by wolfv** [comment]
as mentioned in the last comment, `conda mambabuild` can be installed by installing boa (which is also on conda-forge now: `mamba install boa -c conda-forge`).

Lots of other exciting developments going on over at boa, btw! For example, interactive fixing of recipes & patching, source rebuilds, compile time features exposed in the boa command line...
