### ISSUE TITLE
Custom platform support

### ISSUE THREAD

**Issue by afranchuk** [mamba-org/mamba#794]
I submitted an issue to the `conda` project about this: https://github.com/conda/conda/issues/10571.

As this is a client-only issue, I figured I'd submit here as well. I realize you want to keep `mamba`/`micromamba` pretty interchangeable/compatible with `conda` behavior, but changing the `mamba` channel resolution to not be so restrictive (removing the `KNOWN_CHANNELS` from the code, for instance) would make `mamba`'s behavior a superset of that of `conda` (if they don't change their behavior).

From my perspective, there's no reason you shouldn't allow arbitrary platforms/subdirs. The one thing preventing this is the actual configuration/command-line for specifying a platform, which is `<channel>/<platform>`. Thus, if `<channel>` is a file path or URL, it is not immediately obvious whether the full url/path is for a channel or a platform. This can easily be solved by either:
1. Changing the platform specification to not use `/` as a separator (remove the ambiguity in the configuration) or
2. Do the quick request to check whether the path/url contains `repodata.json`, indicating it is a platform rather than a channel.

**Comment by wolfv** [comment]
Can you not set an arbitrary value with the CONDA_SUBDIR environment variable?

**Comment by afranchuk** [comment]
In theory yes, though it breaks if the value has an extra dash in it (not very well implemented and probably not used enough). But that still is an unnatural thing when the "blessed" platforms can be specified right with the channel.

**Comment by wolfv** [comment]
I'll have to take a look at our implementation here. I'd be interesting in this and would be happy to review/merge a PR that implements this.

**Comment by afranchuk** [comment]
Any preference on whether to change the configuration of platforms (so they are not ambiguous with a `/`) versus just polling for a `repodata.json`?

**Comment by wolfv** [comment]
I need to look into this. Can you sketch a configuration setting / command line arguments of what you want to pass, and what you want to achieve?
Polling is bad because it tends to be slow, I'd say

**Comment by afranchuk** [comment]
Just to reiterate what I want to achieve: I want to be able to add a channel with an arbitrary platform name to the search/install list. For a little more detail: my use case is that I am using conda packages for c++ libraries, and unfortunately there is a need for us to support both c++ libraries with the new (c++11) abi and the old abi. In the conda ecosystem, this is not a problem because it is a *closed* one: all dependencies that a package will interact with are available through the package channels. I believe all c++ libraries in conda-forge, for example, use the new abi. However, we are using conda packages both within the conda ecosystem (while developing) and without it (when delivering), and must be able to deliver libraries that conform to both ABIs. Naturally we could use entirely separate channels/repositories for the two abis, but that would result in needless duplication of those packages which _don't_ depend on the abi (it's not _just_ c++ stuff). Aside from that, I feel using a separate platform for a different abi is in the spirit of their intended use.

And aside from _that_, there doesn't seem to be a practical reason that platforms be anything special, besides maybe `noarch` (though on that note, I kind of feel like if you specify a particular platform to use it shouldn't also automatically add `noarch`, as I mentioned in the conda issue).

## Explicit platform specification
I figure rather than using a `/` to separate the channel and platform, a far less common symbol (maybe `:` or `,`) could be used. In that case, to have the separator symbol as a part of an actual URI (besides the initial protocol `:` in the case of `:` being used), you'd need to url-encode it. A space character could also be used, but would be slightly inconvenient as most shells would require quoting the whole string if passing on the command-line (not that that's so terrible).

Alternatively, the platform could be made explicit as a separate key in the configuration yaml, something like:
```
channels:
   - url: https://something.com/conda
     platform: custom-platform
```
in which case on the command-line you might use command-line specific argument separators like `,` (i.e., in that case the specification of a `(channel, platform)` pair would necessarily be different between configuration and command-line).

The cases that should be accommodated are:
* Channel specification in yaml configuration (`channels`, `default_channels`)
* Channel specification on the command-line (`-c <url>` or `-c <path>`)
* Alias channel specification on the command-line (`-c <name>`)

## "Polling"/discovery approach
However, it _is_ convenient (and simpler to use/understand) to be able to treat the `(channel, platform)` pair as simply URI components. I realize your hesitation to polling, but I think I may have misrepresented it. In the worse case, you'd need a `HEAD` request to check for either a `repodata.json` or `channeldata.json`. With a tiny bit of caching, though, you'd *only* need one request _per distinct channel_ over the lifetime of the cache. So if the cache is persisted to the filesystem, this could be a very long time. The scheme I'm thinking of is this:
1. With the full URI of each potential channel, check the cache of known channel URIs to determine if the query URI is rooted in one of the known channel URIs. If so, you can immediately determine whether the query URI is a channel or whether it is a subdir of a channel, and return immediately with that knowledge.
2. If not in the known channel cache, make a `HEAD` request for `repodata.json`. If it exists, then you know the URI is a platform/subdir rather than a channel, and can remove one component to get the channel location and add that to the cache of known channels. If it does not exist, you can assume the URI is actually the direct channel URI and add it to the cache of known channels.

Note that this still sticks with the assumption/convention that all channel subdirs are one level deep. That's another arbitrary choice that's not limited by the server organization per-se (and bothers me a bit since it's an artificial constraint). To support arbitrarily nested subdirs, instead of a `HEAD` request for `repodata.json` you could do a `GET` and read the json if it exists, because it contains its own `info/subdir` entry which could be used to immediately get the channel root URI even if the subdir is multiple directories down (though I haven't seen a channel with such subdirs).

This small amount of caching would allow automatic detection of whether a URI is a channel or platform within a channel pretty easily, and I think it is reasonable enough to not be considered a serious slowdown since it'd just be one request per channel per cache lifetime.
