### ISSUE TITLE
[micromamba] implement config --set / --append ... commands

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#797]
It would be cool to implement the equivalent to `conda config --set / ...` commands for micromamba:

- [x] `--set`
- [x] `--prepend`
- [x] `--append`
- [x] `--get`
- [x] `--remove`
- [x] `--remove-key`

These functions should read the current config from the `~/.mambarc` file, do the necessary modifications and write out the file.

**Comment by marimeireles** [comment]
Hi @wolfv, something like this? https://github.com/conda/conda/blob/master/conda/cli/conda_argparse.py
We don't have any of these implemented right?
If you want I'm available for a quick chat!

**Comment by adriendelsalle** [comment]
@wolfv could you please update the list of what is now implemented?

Looks like `--remove` and `--remove-key` are not. Do you want to open a new issue for those 2? 
Thanks!

**Comment by marimeireles** [comment]
@adriendelsalle
We might have a problem here, mamba is currently diverging from `conda` in this aspect. Because we're treating everything as a YAML file all the time the natural resolution to remove was to make it generic.

For conda `remove-key` removes a key that's not a vector, e.g a bool, string, etc. And `remove` removes a vector option e.g `channels`.

Do you and @wolfv think we should differentiate these two?

**Comment by adriendelsalle** [comment]
Hey thanks a lot for the feedback!

I would keep `remove` as-is, working with all types, and maybe add some others commands to redirect to that one if it's convenient.
But for now it looks more confusing to have multiple commands if a single is doing the job.

**Comment by marimeireles** [comment]
I think so too and the implementation would be waaay more cumbersome. So, if @wolfv agrees we can close this one and move the card forward on the roadmap, he's in a meeting now but I'll ping him irl once it's done.

**Comment by marimeireles** [comment]
@adriendelsalle I was talking to wolf and it actually makes sense to have both.
The `remove` command receive two arguments, for example `conda --config --remove channels defaults`, so I believe we're still missing this functionality. I can do it! =)

**Comment by wolfv** [comment]
We have all of those! :)
