### ISSUE TITLE
Refactor how we set CURL options

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#798]
Currently we set cURL options for every (new) target. I think it would be enough for most cURL options to be set once, globally, for all targets.

**Comment by adriendelsalle** [comment]
https://github.com/mamba-org/mamba/pull/910 improved the situation to load certificates once, or skip it when `ssl_verify` is set to false (`<false>`).

To avoid setting options for each target, we should implement a pool of handles to reuse them again and again.

**Comment by wolfv** [comment]
I think this a) doesn't matter much and will be b) irrelevant once we start using `powerloader`. Closing :)
