### ISSUE TITLE
Problem in conda and mamba solver?

### ISSUE THREAD

**Issue by marimeireles** [mamba-org/mamba#800]
I have this project: https://github.com/conda-forge/pyls-memestra-feedstock that I was trying to build a conda package for and I ran into the following error: `autopep8 1.5.6 has requirement pycodestyle>=2.7.0, but you have pycodestyle 2.6.0.`

Here's a link for the full [log](https://pastebin.com/HfwM4k15)

This project depends on `python-language-server` that depends on `pycodestyle` and `autopep8`.
If you look into pls code you will find that it pinned a version for `pycodestyle<2.7.0`.
`68:         'pycodestyle': ['pycodestyle>=2.6.0,<2.7.0'],`

The latest version of `autopep8` (1.5.6) requires `pycodestyle>2.7.0` and that's where the issue is coming from.

When I tried to fix the above issue pinning a smaller version for `pycodestyle` it didn't work. What did work though was pinning a version for `autopep <=1.5.5`.

According to Sylvain this is a simple dependency issue that should be solved by mamba and in fact this problem is solved automatically by pip.

Is the problem on my side because I wasn't pinning the right dependency? Shouldn't mamba/conda deal with this in deeper levels by themselves?

Thanks!

**Comment by wolfv** [comment]
I just tried this:

```
mamba create -n kdslajdsad --dry-run "python >=3.4" pyyaml python-language-server memestra deprecated "frilouz >=0.0.2" "autopep8 >=1.5.5"
```

and it solved for the latest version of autopep (1.5.6).

Can you give me the exact specs that conflict?

**Comment by marimeireles** [comment]
Sorry the problem is when you actually install `pyls-memestra`.
Huh, now I'm very confused.

The way I had to do to reproduce it was to use the 0.0.12 version and modify the `meta.yml` file so it has the following content:

https://pastebin.com/rpHGT7fK

**Comment by wolfv** [comment]
yeah, the dependency in this feedstock is not correct then:

https://github.com/conda-forge/autopep8-feedstock/blob/08f47fa2854e9e19cc5cd73ce2e13bf46ccea572/recipe/meta.yaml#L23-L26

**Comment by marimeireles** [comment]
Ahhhh
:skull: thanks wolf!

**Comment by wolfv** [comment]
you can send a PR :) and add the `pip check` test in that recipe.
