### ISSUE TITLE
mamba stalls when creating environment

### ISSUE THREAD

**Issue by ArashPartow** [mamba-org/mamba#805]
### Command:

    mamba env create -n pyenv -f pyenv.yaml

### Output:

    conda-forge/linux-64     Using cache
    conda-forge/noarch       Using cache
    bioconda/linux-64        Using cache
    bioconda/noarch          Using cache
    pkgs/r/linux-64          [====================] (00m:00s) No change
    pkgs/main/linux-64       [====================] (00m:00s) No change
    cogsci/linux-64          [====================] (00m:00s) No change
    cogsci/noarch            [====================] (00m:00s) No change
    
    
    Looking for: ['alembic', 'async-timeout', 'attrs', 'backcall', 'backports', 'bleach', 'bokeh', 'boto3', 'bottle', 'brotlipy', 'bzip2', 'c-ares', 'ca-certificates', 'cachetools', 'certifi', 'cffi', 'chardet', 'click', 'colorama', 'conan', 'cryptography', 'dataclasses', 'decorator', 'defusedxml', 'deprecation', 'distro', 'dpkt', 'entrypoints', 'fasteners', 'future', 'h5py', 'hdf5', 'hpack', 'hyperframe', 'icu', 'idna', 'intel-openmp', 'ipython_genutils', 'ipywidgets', 'jinja2', 'jsonschema', 'jupyter', 'jupyter_client', 'jupyter_console', 'jupyterlab_pygments', 'krb5', 'libarchive', 'libcurl', 'libev', 'libffi', 'libgcc-ng', 'libgomp', 'libiconv', 'libnghttp2', 'libsolv', 'libssh2', 'libstdcxx-ng', 'libxml2', 'lz4', 'lz4-c', 'lzo', 'mako', 'mamba', 'markupsafe', 'marshmallow', 'marshmallow-dataclass', 'matplotlib', 'memoized-property', 'mkl', 'monotonic', 'munch', 'ncurses', 'numpy', 'openssl', 'packaging', 'pandas', 'pandocfilters', 'parso', 'patch-ng', 'pexpect', 'pickleshare', 'pip', 'pluginbase', 'prometheus_client', 'psycopg2', 'ptyprocess', 'pycparser', 'pygame', 'pygments', 'pyjwt', 'pyopenssl', 'pyparsing', 'pysocks', 'pytables', 'python', 'python-dateutil', 'python-editor', 'python-node-semver', 'python_abi', 'pytz', 'pywavelets', 'pyyaml', 'qtconsole', 'qtpy', 'readline', 'reproc', 'reproc-cpp', 'requests', 's3fs', 's3transfer', 'scipy', 'seaborn', 'semver', 'send2trash', 'setuptools', 'six', 'sortedcontainers', 'sqlalchemy', 'sqlite', 'tenacity', 'testpath', 'tk', 'toolz', 'tornado', 'tqdm', 'typeguard', 'tzlocal', 'urllib3', 'wcwidth', 'webencodings', 'wheel', 'xz', 'yaml', 'zipp', 'zlib', 'zstd']

----------------------------

### Details:

1. [pyenv.yaml](https://github.com/mamba-org/mamba/files/6216064/pyenv.yaml____.txt)
2. Other than the above no other output is made. (no spinning cursor or progress bar) it is simply stuck at that point
3. the python/mamba process was using 1.9GB of memory
4. Left the above process to run for 9.5hrs then tried to kill it
5. ctrl+c does not kill the process. Instead had to use kill -9
6. Removing pygame package from pyenv.yaml resolves the issue allowing for the environment to be created.
7. .condarc is as follows:

```
channels:
  - conda-forge
  - bioconda
  - cogsci
  - defaults
ssl_verify: true
channel_priority: strict
```

----------------------------

### Follow-up Questions:

1. Why does mamba fail to bail-out after a reasonable amount of time has passed if it can't create the specified environment?
2. Are there any verbose pr debug options that can be passed to help debug this issue?

**Comment by wolfv** [comment]
Yeah the problem is likely not using strict channel priority as recommended by conda-forge and in general mixing conda-forge and defaults. There are some incompatibilities with cf and defaults channel.

There is an open issue to add a timeout to the solver. Would you be interested in working on that?

**Comment by ArashPartow** [comment]
@wolfv:  I've tested with "channel_priority: strict" and still same issue. 

However when I commented out defaults in .condarc it **worked** As you had  noted there seems to be an incompatibility with defaults and cf - however one thing to note the problematic package actually comes from cogsci.

**Comment by JessicaS11** [comment]
I'll note here for anyone who finds these issues and is still having a problem: I had to create the .condarc file (I hadn't previously) and then remove defaults, as noted above. Even though I only had conda-forge as the only channel listed in my env.yml file, the issue persisted until I created the .condarc file (which I put in my home directory).
