### ISSUE TITLE
[micromamba] allow creation of empty environment

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#814]
When creating an empty environment, we should drop an empty "history" file into `$ENV/conda-meta/history` so that the directory is recognizable as a conda / mamba environment.

**Comment by adriendelsalle** [comment]
It's implemented as part of https://github.com/mamba-org/mamba/pull/824

What could/should be improved is to return just after having creating the folders and the `history` file, preventing the download of channels repodata files and the solver to run with empty specs.

**Comment by adriendelsalle** [comment]
We can close this now @wolfv ?
