### ISSUE TITLE
Micromamba compilation error undefined variable

### ISSUE THREAD

**Issue by gdolle** [mamba-org/mamba#817]
Hi everyone,

I get a micromamba compilation error for release 0.9.1 (maybe 0.9.0 too) from this line
https://github.com/mamba-org/mamba/blob/master/src/repo.cpp#L247

`CONDA_ADD_USE_ONLY_TAR_BZ2` seems missing ?  (Just adding a macro seems to fix the problem though)

```bash
mamba-0.9.1/src/repo.cpp:247:60: error: ‘CONDA_ADD_USE_ONLY_TAR_BZ2’ was not declared in this scope
  247 |         int flags = Context::instance().use_only_tar_bz2 ? CONDA_ADD_USE_ONLY_TAR_BZ2 : 0;
```

PS: `libgmock-dev ` package may be added in the README

Best,

**Comment by wolfv** [comment]
Hi @gdolle, 

indeed, you will have to use the very latest libsolv version as this flag was only recently introduced (thanks to @tl-hbk !).
