### ISSUE TITLE
Installing in non root env messes up -n

### ISSUE THREAD

**Issue by isuruf** [mamba-org/mamba#83]
conda create -n mamba mamba
conda install mamba
conda create -n py37 python=3.7
mamba install opbeat -n py37

Gives

`EnvironmentLocationNotFound: Not a conda environment: /home/isuru/miniconda3/envs/mamba/envs/py37`

**Comment by davidbrochart** [comment]
@isuruf did you mean:
```bash
conda create -n mamba mamba
conda activate mamba
conda create -n py37 python=3.7
mamba install opbeat -n py37
```

**Comment by wolfv** [comment]
So i just investigated thsi a little bit and it seems to be a "conda" problem that never surfaces with conda as conda is always ran from the base environment. E.g. if you install conda into a non-base environment and run it like this:

```
(xc) ~/miniconda3/envs/xc:$ ./bin/conda create -n aslkdjasd xtensor --dry-run
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/wolfv/miniconda3/envs/xc/envs/aslkdjasd

  added / updated specs:
```

you'll get the same behavior.

Conda doesn't have the same problem because in the installed shell script they utilize the `$CONDA_EXE` which is set to the one from the base environment. 

Maybe with mamba we should check what the base env is and pass this as part of the context.

**Comment by wolfv** [comment]
The context object has a property `root_prefix` that sounds like it could give us the correct prefix. We'd need to investigate.

**Comment by marouane-miftah** [comment]
Hi,

 I am seeing the same issue using:

Mac OS Big Sur v 11.2.1
conda 4.9.2

command to install mamba:
`(base) My-MBPro:~ x$ conda install mamba -c conda-forge`

When I run
`(base) My-MBPro:~ x$ conda list mamba`

I get the error:
`EnvironmentLocationNotFound: Not a conda environment: /Users/x/micromamba`

**Comment by joshua-cogliati-inl** [comment]
I have also encountered this error on conda 23.3.1 and Windows Server 2022.
For what it is worth, a work around is to install mamba in the environment, and then activate the environment and drop using -n (as in the above example could be):
```
conda create -n mamba mamba
conda activate mamba
conda create -n py37 python=3.7 mamba
conda activate py37
mamba install opbeat
```

**Comment by jjerphan** [comment]
The resolution depends on the installation of `conda` and `mamba`, especially access to the environments' prefix.

If `mamba` and `conda` come from the same installation (e.g. miniforge, which is the main one now), then all environment directory should be accessible, making all the environment resolvable with `conda`, `mamba` and `micromamba` using the `--name` flag.

If it is not the case, it might be that you environment have been created in custom directories, in which case you can (by preference):
 - specify the paths of the environments in the configuration (see [this piece of documentation](https://docs.conda.io/projects/conda/en/latest/configuration.html)), _e.g._:
    ```yaml
    # ...
    envs_dirs:
     - ~/miniforge/envs
     - /opt/some/envs
    # ...
    ```
 - export the `CONDA_ENVS_PATH` environment variable (see [this piece of documentation](https://docs.conda.io/projects/conda/en/23.1.x/user-guide/configuration/use-condarc.html#specify-environment-directories-envs-dirs), _e.g._:
    ```bash
    export CONDA_ENVS_PATH="~/miniforge/envs:/opt/some/envs"
    mamba install -n py37 opbeat
    ```
 - specify the path of the environment on the command line using the `--prefix ` flag:
    ```bash
    mamba install -p /opt/some/envs/py37 opbeat
    ```

Please do reopen or comment on this issue if you still have the problem.
