### ISSUE TITLE
mamba search --json slow?

### ISSUE THREAD

**Issue by ericpre** [mamba-org/mamba#835]
It seems that `mamba search --json` is significantly slower than `mamba search`: ~1 min 30s versus 3-4 s for `mamba search`. Is it expected?
The difference between the two seems to be the output format only.

See https://github.com/mamba-org/gator/issues/132 for background: in short, this is slowing down retrieving packages in gator.

**Comment by wolfv** [comment]
Mamba search is actually the exact same implementation as conda. Can you check if it's the same there? We have a 

Mamba repoquery search function implemented in C++ that might be faster

**Comment by ericpre** [comment]
It is possible to get the list of all packages as json using `mamba repoquery search`? It seems that it is necessary to specify a package. If I naively try `mamba repoquery search`, I get the following error:
```
mamba repoquery search: error: the following arguments are required: package_query
```

**Comment by wolfv** [comment]
What do you mean, all packages? Why not use the repodata.json directly in that case?

You can use "*" maybe?

**Comment by ericpre** [comment]
Yes, `mamba repoquery search "*" --json` seems to be providing a similar output as `mamba search --json` but much faster! I have tried `*` before but I was missing the quotation marks.
I don't know the details and I was surprised that getting the output as json would make it significantly slower but I agree that using `repodata.json` may be a more sensible/efficient approach.

**Comment by ericpre** [comment]
Closing because `mamba repoquery search "*" --json` is a good alternative.
