### ISSUE TITLE
Document how to run Python tests and/or write a more generic way to find umamba exe.

### ISSUE THREAD

**Issue by marimeireles** [mamba-org/mamba#844]
When you run Python tests it's expected that your executable is inside `.../mamba/build`:

```
umamba = os.path.join(cwd, "build", umamba_bin)
```

We have to either document how to build tests on Python and/or improve this? I don't know how to do this, this issue is mainly a question for Wolf but I don't want to ping him.
I'm using a `cbuild` folder for instance...

**Comment by Anay21110** [comment]
I can help with the documentation.
Where is the file located ?
