### ISSUE TITLE
To be fixed both upstream and here: KeyError when updating (if you have the token active)

### ISSUE THREAD

**Issue by asterbini** [mamba-org/mamba#855]
I have tried mamba as my package manager but I always got a KeyError at line 255 of utils.py because function split_anaconda_token imported from conda was'nt working on some urls.
The culprit are some urls that contains the underscore '_' char, which is not recognized by split_anaconda_token.

Fix: edit the RE inside split_anaconda_token and add '_' to the set of captured chars.
I'll paste this also upstream

**Comment by wolfv** [comment]
ref https://github.com/conda/conda/issues/10616

**Comment by asterbini** [comment]
The same RE is used in file core/url.cpp and therefore the personal token is printed in the package lists.
please change line 24 of file core/url.cpp from
```
        std::regex token_re("/t/([a-zA-Z0-9-]*)");
```
to
```
        std::regex token_re("/t/([a-zA-Z0-9-_]*)"); // added '_'
```

**Comment by asterbini** [comment]
I've added a pull request with a more general fix
https://github.com/mamba-org/mamba/pull/1057

**Comment by wolfv** [comment]
It's fixed now in this repo. Thanks @asterbini hopefully upstream conda can also do something.
