### ISSUE TITLE
Long paths support on Windows

### ISSUE THREAD

**Issue by adriendelsalle** [mamba-org/mamba#857]
Description
---

We currently disabled long path support on Windows in `cpp-filesystem` using `GHC_WIN_DISABLE_AUTO_PREFIXES` flag because `cmd.exe` doesn't support call to executable specified using the `\\?\` prefix.
This was causing an error when executing the compile script for noarch packages at install time.

See https://github.com/gulrak/filesystem/releases/tag/v1.5.0

**Comment by dhirschfeld** [comment]
Does it not work if you enable long path support in the registry?
```powershell
Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled -Value 1
```

**Comment by dhirschfeld** [comment]
If not, couldn't you just call powershell to compile the packages?

**Comment by adriendelsalle** [comment]
> Does it not work if you enable long path support in the registry?
> 
> ```powershell
> Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled -Value 1
> ```

Thanks for the tip! We should try.
Is it currently causing an issue for you @dhirschfeld ?

Mixing shells, not sure. When running a command from a shell you already know that shell will be found :). Have to investigate further

**Comment by wolfv** [comment]
@dhirschfeld I think moving to powershell will take a while ... we'd have to update a lot of conda packages and their activation scripts...
I have some attempts at a more scalable solution for all this here: https://github.com/wolfv/multisheller

But even there I am not sure it's the right solution.

**Comment by dhirschfeld** [comment]
I set that registry key on all VMs and containers and have never had a problem with long paths.

Disclaimer: That doesn't mean that there aren't any latent issues I just haven't come across.
