### ISSUE TITLE
Mamba builds unstable tensorflow environment

### ISSUE THREAD

**Issue by robertschulze** [mamba-org/mamba#861]
mamba resolution of tensorflow package creates broken keras package (on intel channel):

common first step:
`conda create --prefix somePrefix python=3.8 intelpython3_core conda`
`somePrefix\scripts\activate`
`conda install conda-forge::mamba`

As a reference, then executing `conda install tensorflow scikit-learn` builds:
+defaults/win-64::_tflow_select-2.3.0-eigen
+defaults/win-64::tensorflow-2.3.0-mkl_py38h8c0d9a2_0
+defaults/win-64::tensorflow-base-2.3.0-eigen_py38h75a453f_0 
which is working fine.

**When using `mamba install tensorflow scikit-learn` the following is selected:**
+defaults/win-64::_tflow_select-2.3.0-gpu
+defaults/win-64::tensorflow-2.3.0-mkl_py38hd19cc29_0
+defaults/win-64::tensorflow-base-2.3.0-mkl_py38ha8c2253_0 
**This environment is broken, keras givens nan results even for the simplest example scripts.**

Alternatively, using specific tensorflow packages with mamba builds working combinations:

`mamba install tensorflow-eigen scikit-learn` 
+defaults/win-64::_tflow_select-2.3.0-eigen
+defaults/win-64::tensorflow-2.3.0-mkl_py38ha39cb68_0
+defaults/win-64::tensorflow-base-2.3.0-gpu_py38h7339f5a_0
+defaults/win-64::tensorflow-eigen-2.3.0-h238604f_0 

`mamba install tensorflow-mkl scikit-learn` 
+defaults/win-64::_tflow_select-2.3.0-mkl
+defaults/win-64::tensorflow-2.3.0-mkl_py38h637f690_0
+defaults/win-64::tensorflow-base-2.3.0-gpu_py38h7339f5a_0
+defaults/win-64::tensorflow-mkl-2.3.0-h93d2e19_0 

`mamba install tensorflow-gpu scikit-learn` 
+defaults/win-64::_tflow_select-2.3.0-gpu
+defaults/win-64::tensorflow-2.3.0-mkl_py38h8557ec7_0
+defaults/win-64::tensorflow-base-2.3.0-eigen_py38h75a453f_0
+defaults/win-64::tensorflow-gpu-2.3.0-he13fc11_0 

What I am wondering is why with the vanilla `tensorflow` package, mamba builds an unstable combination.

**Comment by wolfv** [comment]
I am checking the metadata of the defaults channel right now, and I find this:

```
    "tensorflow-2.3.0-mkl_py38hd19cc29_0.conda": {
      "build": "mkl_py38hd19cc29_0",
      "build_number": 0,
      "depends": [
        "_tflow_select 2.3.0 gpu",
        "python 3.8.*",
        "tensorboard >=2.3.0",
        "tensorflow-base 2.3.0 mkl_py38ha8c2253_0",
        "tensorflow-estimator >=2.3.0"
      ],
      "license": "Apache 2.0",
      "license_family": "Apache",
      "md5": "0292935e0d5f6f76faeca8f22458f1be",
      "name": "tensorflow",
      "namespace": "python",
      "sha256": "bb892888a1737fb7d2f8bcd74c9bbc97579bbe6f96a0be92c7c8c6341f5e4c41",
      "size": 5887,
      "subdir": "win-64",
      "timestamp": 1606823001748,
      "version": "2.3.0"
    },
```

So the solution you presented as broken seems to be "fine" in the sense that that is what is expected for these requirements.

Not sure why the environment was broken in your case ... maybe you could post a longer list of packages?

**Comment by wolfv** [comment]
Hi @robertschulze I am sorry you're seeing these problems. I've contacted the conda team in a chat and let's see what they think about this package resolution.

I couldn't find anything wrong after intensive digging so I am going to close this for now.

**Comment by chenghlee** [comment]
@robertschulze: could you please re-open this ticket in https://github.com/ContinuumIO/anaconda-issues/issues? I agree with @wolfv that the mamba solution looks correct; it's more likely some bug in the dependency information that's being supplied in the defaults `repodata.json`.
