### ISSUE TITLE
[Feature] Standalone mamba

### ISSUE THREAD

**Issue by elgalu** [mamba-org/mamba#864]
As of now, mamba is suggested to be installed via conda, in the README.

Will it be possible from mamba to be installed standalone? i.e. without conda as a requirement. Thanks

**Comment by wolfv** [comment]
There are currently two options:

- use micromamba (this one is completely standalone, no conda involved at all)
- use the mambaforge installer (that comes pre-bundled with mamba): https://github.com/conda-forge/miniforge#mambaforge
