### ISSUE TITLE
With certain spec styles, mamba creates conda-incompatible environments

### ISSUE THREAD

**Issue by MattF-NSIDC** [mamba-org/mamba#869]
Hello,

When creating an environment with mamba, I am not able to install packages to that environment with conda afterwards, but I can with mamba. I receive:

```
PackagesNotFoundError: The following packages are missing from the target environment:
  - numpy==1
```

I believe this issue applies to all environments created by mamba with the below style of package specification, and I narrowed the issue down to an env with a single arbitrary package. It should reproduce with any package specified in the style `foo==X.*`, it doesn't have to be `numpy`. To reproduce this issue:

Create an environment with a very simple spec with both conda and mamba:

```
name: mamba-test
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8.*
  - numpy==1.*
```

Using `conda env create` to make this environment results in an environment where I can successfully install packages with `conda` and `mamba`. However, if I create the same environment with mamba and then try to `conda install flake8`, I get:

```
$ conda install flake8
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are missing from the target environment:
  - numpy==1
```

I think this is because mamba converts the specs to a different style in the first step of environment creation:

```
  Updating specs:

   - python==3.8
   - numpy==1
```

This can be confirmed in the `$CONDA_DIR/envs/mamba-test/conda-meta/history` file. When the environment is created by conda, the specs I provided in my `environment.yml` are represented in the history as such:

```
# update specs: ['python=3.8', 'numpy=1']
```

However, in the mamba-created environment:

```
# update specs: ['python==3.8', 'numpy==1']
```

All I need to do to make this mamba-created environment work with `conda install` again is to change those double equals signs to single equals signs in the `history` file. I haven't found any other workaround.

I believe this minimal example should be reproducible with the two most recent versions of mamba, `0.9.2` and `0.10.0`, if not more versions. I'm using `conda` `4.10.0`.

I hope to have time later to try and learn more about the mamba code base to maybe submit a pull request, but for now I am fairly ignorant of the codebase aside from some light skimming...

Thank you,
Matt

**Comment by MattF-NSIDC** [comment]
https://www.python.org/dev/peps/pep-0440/#version-matching

(Thanks to my colleague for their helpful research on this)

I believe that what mamba is doing here is wrong based on this quote from PEP440's examples:

* `== 3.1`: specifically version `3.1` (or `3.1.0`), excludes all pre-releases, post releases, developmental releases and any `3.1.x` maintenance releases.

* == 3.1.*: any version that starts with `3.1`. Equivalent to the `~=3.1.0` compatible release clause.

**Comment by MattF-NSIDC** [comment]
Maybe another useful piece of information: Mamba does _install_ to the wildcard spec correctly, giving me numpy `1.20.2` instead of `1.0.0`; it's just the history file entry created by mamba that contains the overly-strict spec for `==1` (i.e. `1.0.0`), and when conda tries to validate the environment against the history, it realizes the mismatch and bails; when mamba validates, it _doesn't_ realize the mismatch and continues along to modify the environment when it should not do so.

**Comment by opoplawski** [comment]
I just ran into this as well.

**Comment by MattF-NSIDC** [comment]
@opoplawski I haven't re-tested this a while. Just curious, did you see this problem with the most recent version of mamba? I don't think this would be fixed yet since it's still in their "triage" column.

**Comment by opoplawski** [comment]
I'm using the latest "standard" mamba from the conda-forge repo.

**Comment by wolfv** [comment]
This might be the same issue as https://github.com/mamba-org/mamba/issues/1024

We're looking into it :)

**Comment by MattF-NSIDC** [comment]
I'm confident these are exactly the same issue :) Same trigger and same manifestation. Thanks Mamba team! :)

**Comment by opoplawski** [comment]
Seems like this can be close now as well.
