### ISSUE TITLE
mamba env create fails on Windows when using netrc

### ISSUE THREAD

**Issue by FaustinCarter** [mamba-org/mamba#870]
Calling `mamba env create` will fail on Windows if the `.condarc` file points to protected channels that have their auth info stored in a `.netrc` file.

This can be fixed by explicitly doing

```bat
set HOME=%USERPROFILE%
```

prior to running `mamba env create`, which leads me to believe that since mamba is calling directly into `conda_env.cli.main` it is bypassing some useful environmental management that conda does to help Windows operation suck less.

FWIW, `mamba search` and `mamba install` both work fine.

**Comment by wolfv** [comment]
Where is the netrc file located in this case?

Could you check if curl works? (Mamba uses curl internally).

Additionally if you find the right command line flags that you need to use with curl, that would be interesting and useful information! :)

**Comment by FaustinCarter** [comment]
Netrc file is in: `%UserProfile%\.netrc`. For what it's worth, calling `conda env create` directly works just fine every time. It's only when it gets called from mamba that it fails.

I've also experimented with putting my netrc file at `%UserProfile%\_netrc` (according to some docs I've read online, Windows prefers the underscore). That didn't make any difference. `conda env create` still worked just fine, while `mamba env create` fails (unless I alias HOME to USERPROFILE).

**Comment by FaustinCarter** [comment]
After doing a little testing, it looks like running curl manually is requiring _both_ the `-n` flag, as well as aliasing `HOME` to `USERPROFILE` to work. This is both with:

`curl 7.76.1 (x86_64-pc-win32) libcurl/7.76.1 Schannel zlib/1.2.11 libssh2/1.9.0` (installed into a conda env)

as well as

`curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL` (ships with Win 10)

**Comment by FaustinCarter** [comment]
Passing `--netrc-optional` also seems to work as well as just `-n`.

**Comment by kuepe-sl** [comment]
I ran into the same issue with Mamba ignoring the `.netrc` file today.

However for me it was happening with `mamba install boa` and `mamba update --all` as well.
`mamba search boa` worked fine.

The workaround (HOME=USERPROFILE) fixed the issue temporarily.

Environment:
- mamba 0.12.2
- conda 4.10.1
- Python 3.7.10.final.0
- curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL

**Comment by FaustinCarter** [comment]
@wolfv Bumping this issue to see if maybe it can be addressed. I have tested again and it is still an issue with mamba 0.23.1.

**Comment by jonashaag** [comment]
@FaustinCarter do I understand it correctly that curl requires an explicit CLI flag for your use case to work?

Btw you might want to look into using Micromamba with `micromamba auth login`. Also, Mamba supports `${ENV_VARS}` in `.condarc`.

**Comment by FaustinCarter** [comment]
> @FaustinCarter do I understand it correctly that curl requires an explicit CLI flag for your use case to work?

I think the answer is maybe. When you pass the `-n` flag to curl, it looks for the `.netrc` file in the directory specified by `%HOME%` (I assume that mamba is passing that flag under the hood already, probably along with `--netrc-optional`). Mamba handles netrc auth fine on Windows _if_ `%HOME%` is set, but fails without it. I can imagine two ways this could be addressed in the mamba codebase:
- On install, check whether `%HOME%` is set; if not, set it to `%USERPROFILE%`
- On run, check whether `%HOME%` is set; if not, check `%USERPROFILE%` for a `.netrc` or `_netrc` file; if found, call curl with `--netrc-file %USERPROFILE%/.netrc`

**Comment by jonashaag** [comment]
Thanks!

What exactly is the logic/heuristic in Conda for dealing with netrc?

**Comment by wolfv** [comment]
I'm not sure we do something special for the `.netrc` file — maybe we should send a PR to curl to check USERPROFILE?

**Comment by FaustinCarter** [comment]
@wolfv That's actually not a bad idea. I just dug into th curl code a little bit, and it looks like it might be doable. I've copy pasted the below function that parses the netrc file (from curl/lib/netrc.c, starting at line 227) and it's clear there are three things happening:
- It ONLY checks the `HOME` env var at all on any system
- On WIN32 systems, if `HOME` was found, but `.netrc` is missing, it also looks for `_netrc`. It seems like adding a check to `USERPROFILE` and maybe even `APPDATA` (i.e. the local and roaming profile defaults) on windows might be pretty straightforward? (I don't actually know C at all though, just enough to kind of read through it).
- If `netrcfile` is passed (i.e. via the `--netrc-file` CLI flag) it skips all the checking logic and uses that file.

So it looks like the options for getting this fixed in mamba are:
- If on Windows, try to find the netrc file via mamba and if it exists pass that in directly
- Open a PR to curl that adds `USERPROFILE` if on Windows (in addition to `HOME`) and also maybe `APPDATA` (adding `APPDATA` as a possible netrc location is on their internal TODO list).

```c
int Curl_parsenetrc(const char *host,
                    char **loginp,
                    char **passwordp,
                    bool *login_changed,
                    bool *password_changed,
                    char *netrcfile)
{
  int retcode = 1;
  char *filealloc = NULL;


  if(!netrcfile) {
    char *home = NULL;
    char *homea = curl_getenv("HOME"); /* portable environment reader */
    if(homea) {
      home = homea;
#if defined(HAVE_GETPWUID_R) && defined(HAVE_GETEUID)
    }
    else {
      struct passwd pw, *pw_res;
      char pwbuf[1024];
      if(!getpwuid_r(geteuid(), &pw, pwbuf, sizeof(pwbuf), &pw_res)
         && pw_res) {
        home = pw.pw_dir;
      }
#elif defined(HAVE_GETPWUID) && defined(HAVE_GETEUID)
    }
    else {
      struct passwd *pw;
      pw = getpwuid(geteuid());
      if(pw) {
        home = pw->pw_dir;
      }
#endif
    }


    if(!home)
      return retcode; /* no home directory found (or possibly out of
                         memory) */


    filealloc = curl_maprintf("%s%s.netrc", home, DIR_CHAR);
    if(!filealloc) {
      free(homea);
      return -1;
    }
    retcode = parsenetrc(host, loginp, passwordp, login_changed,
                         password_changed, filealloc);
    free(filealloc);
#ifdef WIN32
    if(retcode == NETRC_FILE_MISSING) {
      /* fallback to the old-style "_netrc" file */
      filealloc = curl_maprintf("%s%s_netrc", home, DIR_CHAR);
      if(!filealloc) {
        free(homea);
        return -1;
      }
      retcode = parsenetrc(host, loginp, passwordp, login_changed,
                           password_changed, filealloc);
      free(filealloc);
    }
#endif
    free(homea);
  }
  else
    retcode = parsenetrc(host, loginp, passwordp, login_changed,
                         password_changed, netrcfile);
  return retcode;
}


#endif
```

**Comment by wolfv** [comment]
I think if we add some code to curl to check for these other variables that would be really cool and looks straightforward!

**Comment by jonashaag** [comment]
We may still want to look into the Conda code to see what they are doing

**Comment by FaustinCarter** [comment]
@jonashaag It looks like conda's `session.py` imports the `get_netrc_auth` function from `requests.utils` and uses that. The relevant part of that function (from requests code on github) is:

```python
netrc_file = os.environ.get("NETRC")
    if netrc_file is not None:
        netrc_locations = (netrc_file,)
    else:
        netrc_locations = (f"~/{f}" for f in NETRC_FILES)
```

Additionally, in conda's `main.py`, there is this code snippet here, which sets the netrc file location in the main `info_dict`:

```python
    netrc_file = os.environ.get('NETRC')
    if not netrc_file:
        user_netrc = expanduser("~/.netrc")
        if isfile(user_netrc):
            netrc_file = user_netrc
```

In either case, the `~` construct is used to set the home directory, and that expands to `USERPROFILE` on Windows.

**Comment by wolfv** [comment]
This is now merged in libcurl: https://github.com/curl/curl/commit/4d4eb8e587a23e565e3886b56ef6c9b471fc91a3

**Comment by FaustinCarter** [comment]
@wolfv If you know anyone over at curl that can help fix the conda-forge curl feedstock (https://github.com/conda-forge/curl-feedstock) so that this fix can be used by mamba that would be sweet. The last two libcurl releases have died in CI and I'm not entirely sure anyone is maintaining it.

**Comment by jonashaag** [comment]
Closing as we fixed this in Mamba

**Comment by FaustinCarter** [comment]
> Closing as we fixed this in Mamba

@jonashaag  can you link to the PR with the fix in this comment thread?

**Comment by jonashaag** [comment]
Sorry I meant it is fixed in curl

**Comment by wolfv** [comment]
@FaustinCarter I had a look at the feedstock today but I couldn't figure out why the tests on Windows fail. Would love some help on that.

**Comment by FaustinCarter** [comment]
> Sorry I meant it is fixed in curl

The libcurl codebase was patched, but it hasn’t been released in a form that mamba can use yet. Mamba depends on libcurl via conda-forge, and the conda-forge feedstock for libcurl is broken and hasn’t yet released the update. I’d propose leaving this open until mamba can actually rely on the dependency having the fix.

**Comment by FaustinCarter** [comment]
Curl fixed their release pipeline. This can now be closed.
