### ISSUE TITLE
[micromamba] alters filesystem when called with no arguments

### ISSUE THREAD

**Issue by wholtz** [mamba-org/mamba#876]
Somewhere between v0.9.2 and v0.11.1, micromamba started creating the prefix directory (and subdirectories conda-meta, envs, and pkgs) when called with no sub-command. I found this behavior unexpected and it broke some of my code.

**Comment by wolfv** [comment]
Thanks for filing this report @wholtz! Yes, we noticed, too. Will be fixed today!

**Comment by wolfv** [comment]
this is fixed in 0.11.2 cc @adriendelsalle for confirmation

**Comment by adriendelsalle** [comment]
Hi @wholtz thanks for reporting this issue!

Yes this should be fix in https://github.com/mamba-org/mamba/pull/875 and already released in 0.11.2
Let us know if you test it !

**Comment by wholtz** [comment]
Thanks @adriendelsalle -- 0.11.2 passed my initial test cases.
