### ISSUE TITLE
Install instructions use `conda`?

### ISSUE THREAD

**Issue by direvus** [mamba-org/mamba#890]
Conda doesn't work, that's the whole reason I have visited this webpage.

Perhaps this project should be renamed to 'orobouros'?

**Comment by wolfv** [comment]
It's a good idea to change the text to mention Mambaforge: https://github.com/conda-forge/miniforge#mambaforge

Do you want to send a PR?

**Comment by s-pike** [comment]
I came across this issue too. I've sent a Pull Request. (apologies if this is wrong - it's my first attempt at something like this!)

**Comment by ForgottenProgramme** [comment]
The PR was merged, shouldn't this issue be closed now?
