### ISSUE TITLE
[micromamba] root or target prefix check too strict?

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#908]
Activating a named env with a root prefix that is completely empty checks the root prefix, and might throw an error currently.

We need to relax the check for the root prefix in this case.

**Comment by adriendelsalle** [comment]
@wolfv  Could you please paste here a minimal example that gives you a wrong behavior to reproduce ?
Thanks

**Comment by wolfv** [comment]
mayeb something along the lines of 

```
export MAMBA_ROOT_PREFIX=/home/user/myrootprefix
mkdir -p $MAMBA_ROOT_PREFIX
micromamba create -n test
micromamba activate test
```

but it's possible this was fixed already.

**Comment by wolfv** [comment]
looks like we fixed this
