### ISSUE TITLE
Respect channel specs with `mamba update`

### ISSUE THREAD

**Issue by LunarLanding** [mamba-org/mamba#911]
Pinning `mypackage` to a `mychannel` channel, while this package has a more recent version in `otherchannel` and running `mamba update --override-channels -c [otherchannel] mychannel::mypackage` gets `mypackage` from `otherchannel`.
If instead `mamba install ...` is used, `mypackage` is correctly pulled from `mychannel`.
This with mamba 0.12.0 and conda 4.10.1.

**Comment by wolfv** [comment]
Thanks for the bug report. We'll look into it.
