### ISSUE TITLE
Mamba does not pull correct branch from github?

### ISSUE THREAD

**Issue by jennyfothergill** [mamba-org/mamba#920]
Hello :)
It seems like mamba isn't pulling the correct branch when I use pip+git in my environment.yml:
```
...
dependencies:
...
 - pip:
   - git+https://github.com/jennyfothergill/myproject@branch
```
It does correctly install the myproject repo, but on master.
I am installing like so:
```
mamba env update --name envname --file environment.yml
```

osx 10.14.6 (18G6032)
mamba 0.8.2
conda 4.10.1

**Comment by wolfv** [comment]
Hi @jennyfothergill this is actually implemented in `conda`. Did you try if this works fine with `conda`?

I am not sure how conda handles pip packages, actually, and why this wouldn't work. Would need to look into it.

**Comment by jennyfothergill** [comment]
In order to check this, I recreated my environment with both conda and mamba, and mamba pulled the correct branch. 🤦‍♀️ My mistake! Thank you for making an excellent tool.

**Comment by wolfv** [comment]
Thanks for checking again!
