### ISSUE TITLE
Python API guide abruptly stops

### ISSUE THREAD

**Issue by aaronmarkham** [mamba-org/mamba#921]
https://github.com/mamba-org/mamba/blob/master/docs/source/python_api.md
It looks like this guide was cut short....
```
Let’s walk through this example:

We first use the get_index method to download repository data from the channels.
```
Then that's it. There's more, I'm sure.

**Comment by ForgottenProgramme** [comment]
@aaronmarkham 
Hey, Aaron! 
That link doesn't work now (because the docs migrated from markdown to rst?)

Here is the working link:
https://github.com/mamba-org/mamba/blob/master/docs/source/python_api.rst

**Comment by Anay21110** [comment]
What should be added as an example?

Maybe I can help.

**Comment by wolfv** [comment]
@Anay21110  we could add the usage based on how we use it in `boa` for example: https://github.com/mamba-org/boa/blob/master/boa/core/solver.py

Although there is some caching logic in `boa` that's not needed for the general use
