### ISSUE TITLE
progress bar additional features

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#939]
cc @JohanMabille 

- [ ] toggle between the currently downloaded things (print names of downloaded packages next to progress bar)
- [x] include extraction in progress percentage. This would also solve the "waiting when hitting 100% issue". Here is some discussion on how we coudl do that with lib archive https://groups.google.com/g/libarchive-discuss/c/0MWyuZafnpM?pli=1 or https://manpages.debian.org/jessie/libarchive-dev/archive_read_extract.3.en.html
- [ ] print global download speed next to progress bar stop-watch (in MB/s for download)

**Comment by wolfv** [comment]
Hey @JohanMabille just tested, looks great. 

One nitpick, there is a double-print when transaction is starting. 

<img width="990" alt="Screenshot 2021-05-18 at 08 40 25" src="https://user-images.githubusercontent.com/885054/118603909-d0cca180-b7b4-11eb-963f-dd3e9f0a729e.png">

**Comment by jonashaag** [comment]
Seems like we have all of this now
