### ISSUE TITLE
Mamba doesn't return a proper error code when an install fails.

### ISSUE THREAD

**Issue by alanhoyle** [mamba-org/mamba#945]
I'm trying to create a Docker image with  a complex conda environment using `mamba` and the `continuumio/miniconda` base image.  In order to reduce the number of layers, I'm trying something like the following:

``` Dockerfile
RUN conda install -c conda-forge mamba && \
    conda config --add channels defaults && \
    conda config --add channels bioconda && \
    conda config --add channels conda-forge && \
    mamba install -v --yes \
        long \    
        list \
        of \
        things \
        to \
        install && \
    mamba clean --all -y
```

The problem that I'm running into is if that `mamba install [...]` command fails, it does not set the error code properly, and it proceeds to the `mamba clean --all -y`without any problems.  Docker doesn't fail out either, so it happily finishes the build and provides me with a non-working image.  

I'm working on providing a minimal `Dockerfile` to demonstrate this.

**Comment by alanhoyle** [comment]
Here is a minimal Dockerfile:  

[Dockerfile.txt](https://github.com/mamba-org/mamba/files/6481767/Dockerfile.txt)


``` Dockerfile
FROM continuumio/miniconda:latest

RUN conda install -c conda-forge mamba

RUN mamba install thisdoesnotexist

RUN echo this runs, but should not ever run
```


```
$ DOCKER_BUILDKIT=0 docker build .
Sending build context to Docker daemon  3.584kB
Step 1/4 : FROM continuumio/miniconda:latest
 ---> b8ea69b5c41c
Step 2/4 : RUN conda install -c conda-forge mamba
 ---> Using cache
 ---> e08677f94968
Step 3/4 : RUN mamba install thisdoesnotexist
 ---> Running in f2da27a5a4cb

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        Supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Getting  pkgs/main linux-64
Getting  pkgs/main noarch
Getting  pkgs/r linux-64
Getting  pkgs/r noarch

Looking for: [u'thisdoesnotexist']

6637 packages in https://repo.anaconda.com/pkgs/r/linux-64
5025 packages in https://repo.anaconda.com/pkgs/r/noarch
3481 packages in https://repo.anaconda.com/pkgs/main/noarch
21936 packages in https://repo.anaconda.com/pkgs/main/linux-64
Encountered problems while solving.
Problem: nothing provides requested thisdoesnotexist

Removing intermediate container f2da27a5a4cb
 ---> 2318cddc6f30
Step 4/4 : RUN echo this runs, but should not ever run
 ---> Running in d18f2f9ed94f
this runs, but should not ever run
Removing intermediate container d18f2f9ed94f
 ---> 09d8fd7969c7
Successfully built 09d8fd7969c7
```

Compare with the output that replaces `mamba install thisdoesnotexist` with `conda install thisdoesnotexist`:

![Screen Shot 2021-05-14 at 10 17 16 PM](https://user-images.githubusercontent.com/289779/118345385-27f71b80-b502-11eb-9427-921ad83df9be.png)

**Comment by alanhoyle** [comment]
Note that if you try this with a different Docker parent image`FROM continuumio/miniconda3` , it fails properly.  

Updating conda by running `RUN conda update conda` prior to installing mamba makes no difference.

**Comment by madhur-tandon** [comment]
The docker image `continuumio/miniconda` was last released 2 years ago. On investigation, it uses a very old version of `mamba`. Specifically, it uses `0.1.0`. While the latest version is `0.13.1`. This must be the reason behind not returning an error code.

**Comment by madhur-tandon** [comment]
The image `miniconda3` which works properly uses `mamba` with version `0.13.0` i.e. it works correctly.

**Comment by wolfv** [comment]
thanks madhur for looking into this!!

Indeed, 0.1.0 is super old and not supported anymore. Time to upgrade to Python 3 :)

Miniconda3 or Miniforge / Mambaforge are definitely recommended and come with docker images as well.
