### ISSUE TITLE
mamba does not follow conda recipe restriction as defined in meta.yaml

### ISSUE THREAD

**Issue by qisun2** [mamba-org/mamba#958]
I compared mamba and conda (in conda 4.10.1, miniconda3 with default .condarc config, latest mamba installation: conda install -c conda-forge mamba).

mamba create -c pytorch -n pytorch pytorch python=3.6
 conda  create -c pytorch -n pytorch pytorch python=3.6

Conda gives me pytorch v1.4. Mamba gives me pytorch v1.8.

It seems to me that mamba does not follow the conda recipe restriction. In the pytorch v1.8.1 recipe file meta.yaml: Pytorch v1.8 Run requires "python >=3.9,<3.10.0a0"

If I specify python3.6, pytorch 1.8 should not work according to the recipe.

**Comment by adriendelsalle** [comment]
cc @wolfv any chance to be fixed by your recent push upstream in `libsolv`?

**Comment by wolfv** [comment]
What other channels are you using @qisun2 ? There is a pytorch package on conda-forge.

I need to see the output of `mamba list`. This is very unlikely to be a bug in mamba.

However, the pytorch packages from the pytorch channel are not compatible with mamba, as they are using a deprecated way of shipping cuda enabled builds (https://github.com/mamba-org/mamba/issues/336)
