### ISSUE TITLE
`mamba env update ...` updates in wrong location if executed within custom env

### ISSUE THREAD

**Issue by tilusnet** [mamba-org/mamba#960]
Assuming I execute in active virtual env  `VENV1` with the python interpreter at `ROOT/envs/VENV1/bin/python`:

`$(VENV1) mamba env update -n VENV2 -f "my-spec-file.yml"`

I get a wrong, nested transaction prefix:

```
...
Transaction

  Prefix: ROOT/envs/VENV1/envs/VENV2
...
```

Expected: `ROOT/envs/VENV2`

**Comment by tilusnet** [comment]
Tested with:
mamba 0.9.2
conda 4.10.0

**Comment by wolfv** [comment]
You probably did not install mamba in the base environment. Mamba has to be _only_ in the base env

**Comment by tilusnet** [comment]
mamba is in the base environment.

**Comment by tilusnet** [comment]
Ah you are right: it somehow ended up installed inside `VENV1` too.

Otherwise I've got `mamba` in `bin` and in `condabin` as symlink to the former.
I guess that's correct?

**Comment by wolfv** [comment]
Yes, that is correct in bin and condabin
