### ISSUE TITLE
[micromamba] Handle menuinst menu installation

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#961]
On Windows, some packages add a start menu shortcut. That's handled through the `menuinst` (python) package: https://github.com/ContinuumIO/menuinst

We need to figure out how that works and

1. either rely on menuinst + python to add the start menu entries
2. or re-implement the logic in C++

**Comment by isuruf** [comment]
This should be implemented in mamba as well.

**Comment by wolfv** [comment]
For mamba, we should be fine since we still rely on conda's implementation of the linking -- so conda should take care of the menuinst stuff. 

For micromamba I am working on an implementation here: #975
I hope it's going to be ready at the end of the week or beginning of next week.

**Comment by wolfv** [comment]
We have the menuinst implementation in micromamba now. 

For Linux & OS X support, I opened another issue: #1016
