### ISSUE TITLE
Problem with install argument values

### ISSUE THREAD

**Issue by marimeireles** [mamba-org/mamba#968]
So, two problems here:

1. According to @adriendelsalle the order here shouldn't matter.

`mamba install --rc-file=smsmth xtensor` doesn't work but `mamba install xtensor --rc-file=smsmth`, does.

2. The install argument shouldn't accept more than one argument:

```
./micromamba install --rc-file="/home/mariana/.condarc" xtensor

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

ERROR   'rc_file' specified but does not exist at: xtensor
ERROR   Aborting.
```

But it does here because it's trying to deal with `xtensor` after it already dealt with `--rc-file`.

**Comment by marimeireles** [comment]
I'm not convinced if it's worth it to fix this issue though. It's a lot of trouble for a behavior that "looks" wrong, IMO.

**Comment by adriendelsalle** [comment]
Hi @marimeireles thanks for catching this !
It should be fixed at next release of CLI11 (see https://github.com/CLIUtils/CLI11/pull/484). I just pinged upstream.

I agree that having `mamba install --rc-file=smsmth xtensor` may look unusual but I like to be able to swap commands/subcommands or options without having to remember all the time where it has to be placed.

Let's keep it open for the moment

**Comment by wolfv** [comment]
In the micromamba build we actually vendor a newer version of cli11 that doesn't have this problem. Sorry that I forgot about that

**Comment by adriendelsalle** [comment]
We should at least document this as known issue
