### ISSUE TITLE
Accept 'yes' as an answer.

### ISSUE THREAD

**Issue by annada-behera** [mamba-org/mamba#977]
When asking for 'Confirm changes: [Y/n]' if the user replies 'yes', it is not taken as a affirmative and mamba prompts again. In all the Unix tools I've ever used, 'yes' is always taken as a affirmative reply. Even conda accepts 'yes'.

Please add this.

**Comment by wolfv** [comment]
PR welcome :)

**Comment by ibebrett** [comment]
I am happy to try to take this on as a first issue.

**Comment by ibebrett** [comment]
Although, would this mean that mamba's behavior would diverge from conda?

**Comment by ibebrett** [comment]
Looks like mamba wisely uses conda's code for this:

https://github.com/mamba-org/mamba/blob/fcc20bb45b469f7ab6116496273c288e17348fe0/mamba/mamba.py#L18

which means they probably have the goal of keeping the cli matching (at least in spirit)

**Comment by ibebrett** [comment]
Apologies, I see you mean the code paths where Console is used (in C++ land):

https://github.com/mamba-org/mamba/blob/ba6ac219c87cecfa237056e2f49ce6a25ee016f3/src/core/output.cpp#L289

I'd be happy to update these and document that yes and no are equivalent to y and n...

**Comment by ibebrett** [comment]
I tossed this together as an attempt, would really appreciate feedback!

https://github.com/mamba-org/mamba/pull/989
