### ISSUE TITLE
New package not found

### ISSUE THREAD

**Issue by maxnoe** [mamba-org/mamba#982]
We just uploaded new packages for conda-forge, but mamba is not able to find them.

Is this usual? What is the normal delay between a package being listed in the conda cloud and mamba being able to install it?

The package is the erfa one and listed here:
https://anaconda.org/conda-forge/pyerfa/files (the 1.7.3-1 build)

When doing
```
mamba create -n test -c conda-forge astropy=4.2 pyerfa=1.7.3 python=3.9 numpy=1.19 
```

mamba reports:

```
Problem: package pyerfa-1.7.3-py36h27cfd23_0 requires python >=3.6,<3.7.0a0, but none of the providers can be installed
```

It doesn't seem to find the newer 1 build.

Downloading the package and installing the file using mamba works.

**Comment by adriendelsalle** [comment]
Hi @maxnoe 

Yes it's normal [CDN](https://en.wikipedia.org/wiki/Content_delivery_network) behavior to have 1-2hour delay between uploading the package and being able to install it.
Please let us know if it works now!

**Comment by maxnoe** [comment]
@adriendelsalle Thanks for the answer. The package seems not yet available via mamba / conda, now almost 8 hours after uploading.

**Comment by wolfv** [comment]
Please ask in conda forge Gitter.

**Comment by maxnoe** [comment]
For reference: https://github.com/conda-forge/status/issues/114
