### ISSUE TITLE
option to disable wall of ascii art on every mamba command run.

### ISSUE THREAD

**Issue by cjw296** [mamba-org/mamba#984]
This takes up quite a lot of scroll buffer and I'd like to turn it off:
```

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.13.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

```

**Comment by marimeireles** [comment]
`$ export MAMBA_NO_BANNER=1` or `--no-banner`

**Comment by cjw296** [comment]
Thanks! Anything I can put in .condarc?

**Comment by adriendelsalle** [comment]
Unfortunately not, `mamba` relies on `conda` rc configuration advertised [here](https://conda.io/projects/conda/en/latest/configuration.html). You could use `quiet` for the same purpose.

Does it help ?

**Comment by cjw296** [comment]
I think quiet probably already has a meaning, so I guess this becomes a combo of one-or-other feature request:

- just remove the ascii art, feels needless tbh.

- instigate a .mambarc that enables this to be turned off.

**Comment by adriendelsalle** [comment]
The banner is also part of the tool identity.

You may feel more comfy to use `micromamba` that has a smaller banner:
```
$ micromamba --help

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

(...)
```


> instigate a .mambarc that enables this to be turned off.

For that, you should open an issue upstream on `conda`'s [issues tracker](https://github.com/conda/conda/issues).

**Comment by runette** [comment]
> The banner is also part of the tool identity.

I find this a curious thing to say.

Tools don't have identity - they have utility. I measure the value of a hammer by how well it hammers and not by who made it. If every time I used a screwdriver it first announced "This screwdriver was brought to you by Stanley" it would go in the bin (and that is actually also the reason I refuse to use Audible!)!

I am not sure what you think is gained by the banner - I doubt very much anyone will decide to use Mamba "Because it has the best graphics"!

**Comment by marimeireles** [comment]
>For that, you should open an issue upstream on conda's issues tracker.

This doesn't make sense for conda as they don't have any headers.
You think it's problem to get of their specification to add our own flag? I think it could be kinda easy since we'll have the `set` stuff merged soon.

**Comment by marimeireles** [comment]
@adriendelsalle for micromamba all commands have a `Configuration::instance()`, one way to do it would be adding a flag that sets `config.at("show_banner").set_value(false);`. You think this could work?

**Comment by adriendelsalle** [comment]
@marimeireles
You're right about `conda`, they would have not interest to implementing reading of such a configuration they would not use themselves. Unfortunately `mamba` currently totally relies on `conda` rc files parsing so we have to stick with current options. 

In `micromamba`, we could make the `show_banner` rc configurable but it would require to parse rc files before printing the banner (it's not the currently as it's done).

@runette 
Tools, and organizations building those tools, do have identity from my perspective.

There is surely still room for improvements in `mamba`, and everyone is free to fill feature requests on this issue tracker. Doing so, it will start a discussion about evolution of the project with core developers/maintainers.

We are really happy to discuss about what options/flags/etc would make the user experience even better. This has to be done in a positive and constructive way.

For this particular case, we already provide multiple ways to hide this banner if you feel the experience is better without it (CLI `--no-banner` or `--quiet`, env variable `MAMBA_NO_BANNER`).

@cjw296 
If you use `mamba` heavily, you can consider for now setting `MAMBA_NO_BANNER` env variable in your shell profile/rc file.

**Comment by cjw296** [comment]
> instigate a .mambarc that enables this to be turned off.

@adriendelsalle - my point here was that, inevitably, mamba is going to have its own config options at some point that do *not* apply to conda, for this, a `.mambarc` would be the obvious location. If "turn off banners" is the first mamba-specific setting, then so be it ;-)

> @cjw296
> If you use `mamba` heavily, you can consider for now setting `MAMBA_NO_BANNER` env variable in your shell profile/rc file.

I'm no fan of environment variables all over the place, but if it's the only way... However, I do think mamba will inevitably need its own config options at some point, so would be good to have a file for them...

**Comment by loodvn** [comment]
xref: https://github.com/mamba-org/mamba/issues/587#issuecomment-762998474 for setting env variable automatically through conda instead of shell rc file, in case it helps:

"To set the environment variable automatically each time you activate your conda environment, you can do something like the following."

`$ conda env config vars set MAMBA_NO_BANNER=1`

**Comment by dddraxxx** [comment]
> 

The command works well, but when I unset the variable `conda env config vars unset MAMBA_NO_BANNER` and re-run mamba command there is still no banner shown😂. Is there any way to solve it?

**Comment by jonashaag** [comment]
We removed the banner entirely
