### ISSUE TITLE
Expand the C/C++ API to allow access to info

### ISSUE THREAD

**Issue by runette** [mamba-org/mamba#985]
I have an application that needs to get the list of installed Conda packages. Currently, it uses the Conda CLI and screen scrapping.

When I heard about Mamba and that it had a C API I thought that this might be a better solution.

However - the current C++ and C APIs allow `install` and `list` etc to be run but the output is hardcoded to the console (as far as I can see).

It would be good if there were additional calls added to the C API that allow the string response to be returned by the API as opposed to piped to the `std::cout`

**Comment by adriendelsalle** [comment]
Hi @runette
Thanks for opening this issue!

Could you please advertise a bit your use case ? I guess you would like to parse/re-use information so you may prefer getting those using `json` output activated?

**Comment by runette** [comment]
The user case is basically explained in the following article

 https://link.medium.com/C9lddCtrTgb

And yes - what u want is the JSON formatted output.

**Comment by wolfv** [comment]
Hi @runette that's an interesting use-case. In fact, we've been talking with the FreeCAD and QGIS developers about using mamba / libmamba as a plugin manager. Now I am sure Unity already has something, but nevertheless it could be interesting for your use-case.

Relevant links:

- https://forum.freecadweb.org/viewtopic.php?f=42&t=58156
- https://github.com/qgis/QGIS-Enhancement-Proposals/issues/179

I am not entirely sure that JSON is the best option as we could just as well expose native C or C++ data structures like lists or arrays of structs (dataframes).

Anyways, JSON might be easier in terms of memory management.

**Comment by runette** [comment]
Since, in most cases the C API will be wrapped by a binding into another
language - in my case C# - I think that a JSON formatted string will
probably be the simplest and most universal solution. Marshalling the
structs gets tedious :)

Unity has its own package manager - UPM. My choice is about wrapping and
existing Conda native binary plugin (like GDAL) into a UPM package.
