### ISSUE TITLE
Improve logs

### ISSUE THREAD

**Issue by adriendelsalle** [mamba-org/mamba#987]
Description
---

Multiple improvements could be done to logs:
- [x] add a `trace` log level https://github.com/mamba-org/mamba/pull/988
  - a lot of `cURL`, `libsolv` or `libmamba` are more `trace` than `info` or even `debug` (for example, linking of all files of a packages is currently a log level `info`)
- [ ] document log levels in the developer documentation https://github.com/mamba-org/mamba/issues/996
- [ ] refactor logged messages to better use `trace` or `debug` instead of `info`
- [x] add capability to store log messages and replay them later (would fix configs that are currently not *rc configurable* such as `json` and still have a banner nicely displayed before any logs, see https://github.com/mamba-org/mamba/issues/966) https://github.com/mamba-org/mamba/pull/1255
  - this is called *backtrace* support
- [ ] add capability and flag to `micromamba` to output logs in a file, or multiple sinks (stderr, file, etc.)
  - `stderr` can be redirected easily in a shell
  - using C/C++ API, it can be pretty useful to have an API that returns the log messages instead of printing them
- [x] handle the log level independently of the verbosity https://github.com/mamba-org/mamba/pull/1255
  - `libmamba` verbosity is more related to the density of information to want to *see*, but you may still want to *log* more/less

For all of those, I would recommend to assess `spdlog` that is both compiled/header-only lib and provides (almost?) all of those features: multiples sinks, backtrace, log patterns, etc.

**Comment by wolfv** [comment]
It would also be nice to respect the CLICOLOR_FORCE environment variable in the future.

**Comment by adriendelsalle** [comment]
> CLICOLOR_FORCE

@wolfv I'm not sure in which case you expect not colorized outputs?

`termcolor` is using either `is_atty` or `colorize_index` [here](https://github.com/ikalnytskyi/termcolor/blob/67eb0aa55e48ead9fe2aab049f0b1aa7943ba0ea/include/termcolor/termcolor.hpp#L810-L815) and we are setting the latter in the `ConsoleStream` constructor

**Comment by wolfv** [comment]
yes, on terminals that are not a tty it's usually not colored unless you CLICOLOR_FORCE.

That happens on Azure logs for example. they are able to show CLI colors but they are not a TTY.

https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/Special-Shell-Variables.html
https://bixense.com/clicolors/
https://docs.conan.io/en/latest/reference/env_vars.html#clicolor

...

they all support it.

**Comment by adriendelsalle** [comment]
What I'm trying to say is that it should already be forced

**Comment by wolfv** [comment]
So

if you do `micromamba install xtensor > log.txt` do you see color in the txt file?
and if you do `CLICOLOR_FORCE=1 micromamba install xtensor > log.txt` do we see them then?

**Comment by wolfv** [comment]
e.g. with ls that wokrs:

```
ls > test.txt
vs
CLICOLOR_FORCE=1 ls > test.txt
```

**Comment by adriendelsalle** [comment]
it doesn't work on linux, you have to use `ls --color=always > test.txt`

**Comment by wfjsw** [comment]
I wonder, since the `add capability and flag to micromamba to output logs in a file, or multiple sinks (stderr, file, etc.)` is not ticked yet - is there currently a way to log a separated file to disk in addition to console output? I don't want to use STDOUT redirection as it will lose some user-faced terminal features.
