### ISSUE TITLE
mamba cannot install the latest version of biosimspace

### ISSUE THREAD

**Issue by kexul** [mamba-org/mamba#990]
Hi, this is the original issue posted here https://github.com/michellab/BioSimSpace/issues/214 , mamba cannot install the latest version of biosimspace using the following command: 
```
mamba install -c conda-forge -c omnia -c michellab/label/dev biosimspace
```

when restricting the version of biosimspace, conda can solve the environment successfully, but mamba failed.

**Comment by wolfv** [comment]
It's impossible to reproduce because I have no idea what else is in your environment.

Can you run `mamba create -n xyztest -c conda-forge -c omnia -c michellab/label/dev biosimspace`

What channels and what operating system?

**Comment by kexul** [comment]
Thanks @wolfv , your solution saves my life! The following command worked like a charm. 
```
mamba create -n xyztest -c conda-forge -c omnia -c michellab/label/dev biosimspace
```

In my previous attempt, I tried created a new conda env first by: 
```
conda create -n xyztest python=3.7
```
then use:
```
conda activate xyztest
mamba install -c conda-forge -c omnia -c michellab/label/dev biosimspace
```
then an error raised: 
```
Encountered problems while solving:
  - package python-3.7.10-hdb3f193_0 requires libffi >=3.3,<3.4.0a0, but none of the providers can be installed
```

I found that the python version in the enviroment of  this command  created  was `3.7.8`,  
```
mamba create -n xyztest -c conda-forge -c omnia -c michellab/label/dev biosimspace
``` 
And the python version in the environment created by ` conda create -n xyztest python=3.7`  was `3.7.10`, that should be the difference.
