### ISSUE TITLE
Micromamba create fails with long prefix (Windows 10)

### ISSUE THREAD

**Issue by avaissi** [mamba-org/mamba#991]
Micromamba create command fails with long prefix path on Windows 10 Pro.
LongPathsEnabled registry is set to 1, ie. long path support should be set true for my system.

I've attached the CMD output as a log file.

Note: Create command fails right after package download if prefix is set long enough.
`ERROR   The filename or extension is too long.
        : C:\Users\avaissi\Documents\tmp_rcc\my_very_long_path_this_is\my_very_long_path_this_is\my_very_long_path_this_is\my_very_long_path_this_is\my_very_long_path_this_is\my_very_long_path_this_is\my_very_long_path_this_is\my_very_long_path_this_is\envs\lab-env\conda-meta`

Windows specs:
Edition	Windows 10 Pro
Version	20H2
Installed on	‎11/‎06/‎2020
OS build	19042.985
Experience	Windows Feature Experience Pack 120.2212.2020.0

System specs:
Processor	Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz   2.90 GHz
Installed RAM	32,0 GB (31,7 GB usable)
System type	64-bit operating system, x64-based processor

[mamba_log_longpath_issue.log](https://github.com/mamba-org/mamba/files/6616025/mamba_log_longpath_issue.log)

**Comment by adriendelsalle** [comment]
Hi @avaissi , thank you for opening this issue!

It's probably related to https://github.com/mamba-org/mamba/issues/857.
I'll try to reproduce.

**Comment by adriendelsalle** [comment]
I'm able to reproduce.

At least, we need to:
- [ ] remove the `GHC_WIN_DISABLE_AUTO_PREFIXES` definition added here https://github.com/mamba-org/mamba/blob/c1516d4cb67df8bbfcba8514e1f8309d2a980108/CMakeLists.txt#L72
- [ ] fix #857 issue when running `cmd.exe` subprocesses with long paths
- [ ] fix upstream `GHC::filesystem` implementation of `create_directories`
  - see issue https://github.com/gulrak/filesystem/issues/125
  - see PR https://github.com/gulrak/filesystem/pull/126

**Comment by wolfv** [comment]
@adriendelsalle can we close this one?
