### ISSUE TITLE
Found corrupted repodata_record file warning

### ISSUE THREAD

**Issue by izahn** [mamba-org/mamba#993]
I'm trying to use `boa` / `mamba` to debug requirement conflicts over in https://github.com/conda-forge/qt-feedstock/pull/194 
and seeing some strange errors, like 

```
WARNING Found corrupted repodata_record file "/Users/runner/miniforge3/pkgs/libcxx-11.1.0-habf9029_0/info/repodata_record.json"
```
~~and
Encountered problems while solving:
package clangxx_osx-64-11.0.0-hc3ec130_0 requires clang_osx-64 11.0.0 h05bbb7f_0, but none of the providers can be installed~~

Unfortunately I don't have a Mac and so can't reproduce or investigate locally, but let me know if there is any other useful information I can provide.

**Comment by wolfv** [comment]
It's always possible to debug solver issues on other platforms, eg.:

`CONDA_SUBDIR=osx-64 mamba create -n abc clangxx_osx-64 -c conda-forge --dry-run`

Not sure what's going on here ... will have to have a deeper look tomorrow. Sorry.

**Comment by wolfv** [comment]
(locally it resolves just fine for the compiler at least).

**Comment by izahn** [comment]
> It's always possible to debug solver issues on other platforms, eg.:
> 
> `CONDA_SUBDIR=osx-64 mamba create -n abc clangxx_osx-64 -c conda-forge --dry-run`

That's great to know, thanks.

> Not sure what's going on here ... will have to have a deeper look tomorrow. Sorry.

Thanks for looking into it!

**Comment by izahn** [comment]
Just following up to confirm that the `clang` issue noted in the original report is not a mamba problem and can be ignored. The issue at hand here are the `Found corrupted repodata_record file` warnings.
