### ISSUE TITLE
Reduce code duplication in mamba config opts

### ISSUE THREAD

**Issue by marimeireles** [mamba-org/mamba#995]
From https://github.com/mamba-org/mamba/pull/838, Wolf suggested a way to reduce code duplication.
I agree with it, I started to implement it but couldn't finish it.

```
enum CONFIG_MOD_ACTION { SET, APPEND, PREPEND };

void modify_config(CONFIG_MOD_ACTION action)
{
    auto& config = Config::instance();
    config.load();
    auto& filepath = config.at("config_set_file_path").get_wrapped<fs::path>();
     ...
}

// and then in the callbacks:

subcom->callback([&]() {
    modify_config(CONFIG_MOD_ACTION::SET);
}
...
```

I'm opening this issue as a reminder that we have to get back to it.

**Comment by wolfv** [comment]
@adriendelsalle is this done?

**Comment by adriendelsalle** [comment]
I remember that I factorized some code in that subcommand but I should have another look on that before closing

**Comment by wolfv** [comment]
Done to a large part!
